### ISSUE TITLE
Doc / alias pip for python 2 and 3

### ISSUE THREAD

**Issue by parente** [jupyter/docker-stacks#10]
See chat starting about here:

https://gitter.im/jupyter/docker-stacks?at=55d5beb41250e6600d08d27d

**Comment by basnijholt** [comment]
Chat went down, but the discusion was that there is no easy way to find out how to switch to Python 2 environment when you start the image with `/bin/bash`.

**Comment by parente** [comment]
I added a section to the bottom of every relevant README about the conda environments present in each image, how to switch between them, and what key commands are available in each (python, ipython, pip, conda, ...)
