### ISSUE TITLE
help updating to julia 0.4 binary and integrating with jupyter

### ISSUE THREAD

**Issue by mikejacktzen** [jupyter/docker-stacks#100]
hi all, has anyone tried using an additional julia binary, say 0.4 and correctly configuring 0.4 with jupyter notebook?

I've tried the following but end up with kernel errors

1) untared the general linux binary of julia 0.4
    http://julialang.org/downloads/
    (Generic Linux Binary)
The ./julia executable is in
/home/jovyan/work/julia4/bin
note: the existing julia 0.3 is still installed and linked with the 'julia' command (0.4 is not linked)

2) inside julia, Pkg.add() and Pkg.build() "IJulia"
  as per instructions in 
  https://github.com/JuliaLang/IJulia.jl
note: the initial Pkg.add("IJulia") gave a warning and failed, but the following Pkg.build("IJulia") succeeds
(This seems like a typical scenario as per the instructions)

3) moved the jupyter kernel directory from /.local/share/ into $CONDA_DIR/share/
  as per line 88 in the dockerfile 
  https://github.com/jupyter/docker-stacks/blob/master/datascience-notebook/Dockerfile
note: one difference is, thru Julia 0.4 command line, it wrote the IJulia kernelspec in
     /root/.local/share/jupyter/kernels/julia-0.4
This is the ./local/share that I moved, comparing it with the docker file command
    mv /home/$NB_USER/.local/share/jupyter/kernels/* 

This gets me as far as showing julia 0.4 as a selectable notebook inside the jupyter web interface
But if I try to run it, it kernel errors out

note: the unmodified contents of kernel.json file shows
vi /.local/share/jupyter/kernels/julia-0.4/kernel.json

{
  "display_name": "Julia 0.4.2",
  "argv": [
    "/home/jovyan/work/julia4/bin/julia",
    "-i",
    "-F",
    "/root/.julia/v0.4/IJulia/src/kernel.jl",
    "{connection_file}"
  ],
  "language": "julia"
}

comparing that with julia 0.3
vi /.local/share/jupyter/kernels/julia-0.3/kernel.json
{
  "display_name": "Julia 0.3.2",
  "argv": [
    "/usr/bin/julia",
    "-i",
    "-F",
    "/home/jovyan/.julia/v0.3/IJulia/src/kernel.jl",
    "{connection_file}"
  ],
  "language": "julia"
}

**Comment by parente** [comment]
I haven't tried 0.4. Any helpful tracebacks in the notebook or in the server log in the terminal where you started the docker container?

**Comment by mikejacktzen** [comment]
I'm going to close this issue in a week (in case others run into this). 

Mostly because, I gave up on using this particular stack. I can't debug it.

I just pulled a vanilla ubuntu docker image and built julia 0.4 and jupyter from scratch, successfully.

**Comment by parente** [comment]
I'm going to close this issue because it's been inactive for a few months. I'll happily take a PR to upgrade the version of julia in the images or a recipe on the wiki about installing your own julia in the container if anyone would like to write either.
