### ISSUE TITLE
datascience-notebook needs to chown -R /home/jovyan to uid 1000 as root before starting

### ISSUE THREAD

**Issue by ainiml** [jupyter/docker-stacks#1003]
PermissionError: [Errno 13] Permission denied: '/home/jovyan/.local'

This is even starting the Deployment as root `0`

Note: new-longhorn-volume was remounted to `/home/jovyan/volume`, in order to start 

```
root@jupyterlab-5fb664fc79-k4scg:~# id
uid=0(root) gid=0(root) groups=0(root)
root@jupyterlab-5fb664fc79-k4scg:~# pwd
/home/jovyan
root@jupyterlab-5fb664fc79-k4scg:~# ls -lh
total 8.0K
drwxr-xr-x 3 root   root  4.0K Feb  6 13:32 volume
drwsrwsr-x 2 jovyan users 4.0K Jan 30 03:41 work
```

**What docker image you are using?**

`jupyter/datascience-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

`docker run -v new-longhorn-volume:/home/jovyan  jupyter/datascience-notebook:latest`

**Comment by romainx** [comment]
Hello,

There is already an option documented to handle this case. It is described in the [Docker Options](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html#docker-options) section of the documentation.

To fix this kind of problem, you can simply run the notebook with the following options: `-e CHOWN_HOME=yes -e CHOWN_HOME_OPTS='-R'`.

I have reproduced the case and fixed it successfully by using using this command line.

```bash
docker run --user root -v new-longhorn-volume:/home/jovyan \
  -e CHOWN_HOME=yes -e CHOWN_HOME_OPTS='-R' \
  -it --rm -p 8888:8888 jupyter/datascience-notebook:latest

# Set username to: jovyan
# usermod: no changes
# Changing ownership of /home/jovyan to 1000:100 with options '-R'
# Executing the command: jupyter notebook
```

Best

## Notes

To reproduce the case I had to give `sudo` rights to `jovyan` thanks to this command.

```bash
docker run --user root -v new-longhorn-volume:/home/jovyan \
        -e GRANT_SUDO=yes \
        -it --rm -p 8888:8888 jupyter/datascience-notebook:latest
```

**Comment by BothOfUsTogether2** [comment]
THANK YOU VERY MUCH

**Comment by ainiml** [comment]
see https://github.com/jupyter/docker-stacks/issues/1003#issuecomment-583768897

**Comment by RashiqAzhan** [comment]
From what I understand, this gives the container user root access, which is usually a bad idea. Is there a way we can do this without giving it root access?
