### ISSUE TITLE
datascience-notebook: newer images generate " Illegal instruction (core dumped)" when importing sympy

### ISSUE THREAD

**Issue by jlphillipsphd** [jupyter/docker-stacks#1012]
`docker pull jupyter/datascience-notebook:9f4983c5d1f3`
`docker run -it --rm --name temp jupyter/datascience-notebook:9f4983c5d1f3`
in other terminal:
`docker exec -it temp /bin/bash`
Inside the container:
```
jovyan@1016eb8fa911:~$ python
Python 3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 22:33:48)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sympy
Illegal instruction (core dumped)
```

Expected behavior: importing sympy should not cause a core dump, and allow additional code execution
(Note: the kernel dies within the notebook environment as well when importing sympy)

I have no trouble using an image which is a little older: jupyter/datascience-notebook:7a0c7325e470

Of course, I see the illegal instruction message, so here are my CPU specs (from /proc/cpuinfo within the container):
```
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 21
model           : 2
model name      : AMD Opteron(tm) Processor 6376
stepping        : 0
microcode       : 0x6000852
cpu MHz         : 2598.211
cache size      : 2048 KB
physical id     : 2
siblings        : 16
core id         : 7
cpu cores       : 8
apicid          : 79
initial apicid  : 79
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid amd_dcm aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb cpb hw_pstate ssbd ibpb vmmcall bmi1 arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold
bugs            : fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
bogomips        : 4600.06
TLB size        : 1536 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management: ts ttp tm 100mhzsteps hwpstate cpb eff_freq_ro
```

I am suspecting that there is an AVX2 requirement somewhere now perhaps? Any insight into that would be appreciated. I know some hardware may age out, but is that really the case for my poor procs? :(

**Comment by jlphillipsphd** [comment]
Just to follow-up, sympy doesn't have these problems on the host system:
```
Python 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sympy
>>> 
```

**Comment by romainx** [comment]
Hello,

Thank you for submitting this issue with all the necessary information to reproduce the problem.
However it's weird since with exactly the same procedure (just changed added the `-it` option in the command `docker exec -it temp /bin/bash`) and obviously the same image tag I'm not able to reproduce it.

```python
Python 3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 22:33:48)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sympy
>>> sympy.__version__
'1.5.1'
```

So you must be right it could be related to the host hardware. By googling around I've seen some similar issues on Python packages like `numpy`.

For information the manifest of the previous version you have successfully used in the past is available here [datascience-notebook-7a0c7325e470](https://github.com/jupyter/docker-stacks/wiki/datascience-notebook-7a0c7325e470). The  version of Python `3.7.3`  was the same as the version on your host that is working fine.

Maybe someone else could help further.
Best.

**Comment by jlphillipsphd** [comment]
Thanks for trying this out.
Thanks for following-up. I edited my comment above to include the -it option (which I was indeed using myself when I ran the command).

I am going to start looking for where in the stacks get python 3.7.6 and see if that's the culprit and why... might just have to build the stack myself if AVX2 is now a requirement since I doubt anyone will have mercy on my (now taken to be old) hardware. I am hoping it is something configured in an unexpected way for now which, if fixed, would remedy the problem for me. I will post again when I know more.

**Comment by jlphillipsphd** [comment]
I tried pulling the latest scipy-notebook and had the same issue, so it's not particularly the datascience-notebook (which makes sense: it's based off of scipy-notebook). However, there is no sympy prior to scipy-notebook.

Given this, I pulled the Dockerfile from the current master branch for both scipy-notebook and datascience-notebook and then used them to build them both locally. After that, I noticed that the import worked on both locally-built images (scipy-notebook with python 3.7.4 and then datascience-notebook with python 3.7.6).

I guess this is a workaround, but it makes me think there's something specific to the docker hub build environment that's causing the issue instead of a lack of support for my hardware?

Maybe something could be configured in the build to prevent it? I don't know what the specific problem is yet, but I'll look at the backtrace soon to see if I can find any clues.

**Comment by jlphillipsphd** [comment]
Backtrace (using GDB) from the "Illegal instruction (core dumped)" error attached.
[backtrace_info.txt](https://github.com/jupyter/docker-stacks/files/4201910/backtrace_info.txt)

**Comment by jlphillipsphd** [comment]
At this point, it seems that there is some kind of autodetection or autoconfiguration having to do with building libgmp/gmpy2 that causes the stack to have these illegal instructions on certain hardware.

For a docker container, I realize that certain hardware may just be too obsolete to be supported, but I didn't think my hardware was quite that bad yet: just my opinion :) Therefore, in order to run a container on a wide range of hardware, the particular flag or option that gets autodetected or autoset due to hardware probing would need to be adjusted to use the acceptable standard instead of relying purely on the build infrastructure hardware configuration.
 
If I can isolate the issue and provide a pull-request that would fix the issue (since I know at least that the current stacks will build just fine on my hardware), is this something that jupyter/docker-stacks even wants to address or maintain support for in the future?

**Comment by romainx** [comment]
Very interesting feedback, it definitively makes sense.

> Therefore, in order to run a container on a wide range of hardware, the particular flag or option that gets autodetected or autoset due to hardware probing would need to be adjusted to use the acceptable standard instead of relying purely on the build infrastructure hardware configuration.

I'm not a maintainer nor a specialist of this topic, so I cannot answer to your question however it's always better to master and define the supported hardware configuration instead of simply relying on the build infrastructure hardware configuration.

**Comment by jlphillipsphd** [comment]
Thanks for the feedback @romainx 

OK, I'll start looking into this then. The general plan will be to configure a fork which I will use to build on docker hub, and use that fork to isolate the change required to remedy the issue on my hardware. This will eventually lead to a PR that I can provide which should fix the issue (for my hardware at least).

This will mean ensuring that this change meets some kind of accepted standard (which still has to be decided in some way if only for this specific issue). I guess it's always still possible that my hardware really is too old for everyone :sweat_smile:, but we can see about that when I have figured it out.

I have seen some recent packages asking for AVX support, but most have seemed to remain at SSE2. My machines easily meet SSE2 (it goes up to SSE4.1) and the AVX bar, but if people here really feel that AVX2 is a must, then I will just be out-of-luck. Still, finding exactly where this setting gets detected would help avoid these kinds of issues in the future, so I'll try to work on it either way.

**Comment by jlphillipsphd** [comment]
OK, so I forked docker-stacks/master and made a public Docker Hub repo of my own using the fork to build scipy-notebook only (just configured the repo to build from the /scipy-notebook/ subdirectory). I *never* used my machine for any part of this process. Then I pulled the image that was built on Docker Hub for testing:
```
docker pull jlphillips/scipy-notebook
docker run -it --rm --name temp jlphillips/scipy-notebook
```
Then in another shell...
```
docker exec -it temp /bin/bash
jovyan@629a986b0661:~$ python
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sympy
>>> 
```
The import was successful and ran without any error... so, at this point, I am not sure how I can get an environment that will reproduce the bug for me? Do you all use a different infrastructure for your builds? How could I set up something like that?

**Comment by jlphillipsphd** [comment]
I guess the bug has been resolved by some other change. Today I pulled the latest datascience-notebook and had no issues with sympy any longer...
