### ISSUE TITLE
Why freezing the libs version?

### ISSUE THREAD

**Issue by gbrault** [jupyter/docker-stacks#1014]
Hello,
you choose to "freeze" some of the package there
[docker file lib definition](https://github.com/jupyter/docker-stacks/blob/437f1ef92733ecdb34814a28af38484acc02cd1a/scipy-notebook/Dockerfile#L18)

do you have a particular reason not to let conda do the job?

pandas is now 1.0.1 and 0.25 is a quater older...

Do you plan something to improve that?

**Comment by romainx** [comment]
A quote from the documentation bringing a part of the answer.

>  We prefer to pin the major and minor version number of packages so as to minimize rebuild side-effects when users submit pull requests (PRs).
>
> --- <cite>https://jupyter-docker-stacks.readthedocs.io/en/latest/contributing/packages.html</cite>

In the PR #1024 it's a draft of a test permitting to check outdated packages in order to update them.

Here is the raw (including dependencies) list of outdated packages in `scipy-notebook`

```
Package            Current     Newest
-----------------  ----------  --------
alembic            1.3.3       1.4.0
blas               2.14        2.15
bleach             3.1.0       3.1.1
ca-certificates    2019.11.28  2020.1.1
cffi               1.13.2      1.14.0
cloudpickle        1.2.2       1.3.0
conda              4.7.12      4.8.2
dask               2.9.2       2.11.0
dask-core          2.9.2       2.11.0
distributed        2.10.0      2.11.0
hdf5               1.10.5      1.10.6
idna               2.8         2.9
inflect            4.0.0       4.1.0
ipython            7.11.1      7.12.0
jinja2             2.11.0      2.11.1
json5              0.8.5       0.9.1
jupyter_client     5.3.4       6.0.0
jupyter_core       4.6.1       4.6.3
jupyter_telemetry  0.0.4       0.0.5
jupyterlab         1.2.5       1.2.6
krb5               1.16.4      1.17.1
libcurl            7.65.3      7.68.0
libgfortran-ng     7.3.0       8.2.0
libopenblas        0.3.7       0.3.8
libsodium          1.0.17      1.0.18
lz4-c              1.8.3       1.9.1
mako               1.1.0       1.1.1
ncurses            6.1         6.2
nodejs             13.7.0      13.9.0
oauthlib           3.0.1       3.1.0
pandas             0.25.3      1.0.1
pandoc             2.9.1.1     2.9.2
parso              0.6.0       0.6.1
pycurl             7.43.0.4    7.43.0.5
python             3.7.4       3.8.1
pyzmq              18.1.1      19.0.0
readline           7.0         8.0
requests           2.22.0      2.23.0
ruamel_yaml        0.15.80     0.15.87
seaborn            0.9.0       0.10.0
setuptools         45.1.0      45.2.0
soupsieve          1.9.4       1.9.5
sqlite             3.30.1      3.31.1
statsmodels        0.11.0      0.11.1
tqdm               4.42.0      4.43.0
urllib3            1.25.7      1.25.8
wheel              0.34.1      0.34.2
zipp               2.1.0       3.0.0
```

A last word about `pandas` the `1.0` version last from the 30-Jan-2020. Less than 1 month, not so bad :sweat_smile:

You can submit a pull request with the updated versions. It's a good way to start contributing to this repo.

**Comment by romainx** [comment]
For information just submitted a PR to bump the version of packages in `scipy-notebook` ->  #1030.

Best

**Comment by gbrault** [comment]
Many thanks!

**Comment by romainx** [comment]
You're welcome 😄 
Updated stack is available see [manifest}(https://github.com/jupyter/docker-stacks/wiki/scipy-notebook-678ada768ab1).

```python
import pandas as pd
pd.__version__
# '1.0.1'
```
Best
