### ISSUE TITLE
No pyspark in jupyter/pyspark-notebook

### ISSUE THREAD

**Issue by mjablonski-hive** [jupyter/docker-stacks#1016]
**What docker image you are using?**

`jupyter/pyspark-notebook`

**What complete docker command do you run to launch the container?**

`docker run -p 8888:8888 jupyter/pyspark-notebook`

**What steps do you take once the container is running to reproduce the issue?**

1. Visit http://localhost:8888
2. Start a python3 notebook
3.  type `import pyspark`

**What do you expect to happen?**

Import pyspark

**What actually happens?**

`ModuleNotFoundError: No module named 'pyspark'`

![image](https://user-images.githubusercontent.com/35228682/74595216-ada5c600-5036-11ea-91bf-a8b05533f5b7.png)

**Fix**

`conda install pyspark` works - it seems pyspark is not bundled during docker creation
Thanks

**Comment by romainx** [comment]
Hello,

Sorry it's a bug introduced in a recent the PR #1007 , `PYTHONPATH` was broken.
It has been fixed in PR 1017 and a test has been added to avoid this in the future.

So you can pull the last version (`jupyter/pyspark-notebook:31b807ec9e83`) it's fixed.

Sorry for the inconvenience.

**Comment by mjablonski-hive** [comment]
Works, thanks!
