### ISSUE TITLE
ROCm Support?

### ISSUE THREAD

**Issue by Hugo54x** [jupyter/docker-stacks#1032]
Is there already ROCm Support for AMD Graphic Cards?

https://github.com/RadeonOpenCompute/ROCm

Would be very nice to have if it is not already present.

**Comment by parente** [comment]
We prefer adding [recipes in the documentation](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html) over installing new packages in the images to avoid forever increasing the size of the docker images and maintenance burden of this repository. We'd be happy to review and merge a [recipe pull request](https://jupyter-docker-stacks.readthedocs.io/en/latest/contributing/recipes.html) for ROCm if you'd like to submit one.

**Comment by mathbunnyru** [comment]
@Hugo54x have you tried official installation guide?
https://docs.amd.com/bundle/ROCm_Installation_Guidev5.0/page/How_To_Install_ROCm.html

Please, check it. If it works well, I don't think we should add something to our images / docs.

**Comment by Hugo54x** [comment]
@mathbunnyru it's been quite a long time since I opened this issue and I don't know what I was trying to achieve anymore. So you can close this issue. Thx for the reminder :)
