### ISSUE TITLE
Tokens are being rejected

### ISSUE THREAD

**Issue by profbbrown** [jupyter/docker-stacks#1035]
**What docker image you are using?**

`jupyter/base-notebook`

I pulled this image on March 4. 

**What complete docker command do you run to launch the container (omitting sensitive values)?**

`docker run -p 8888:8888 jupyter/base-notebook`

**What steps do you take once the container is running to reproduce the issue?**

Connect to the suggested URL: `http://127.0.0.1:8888/?token=a4405d51cde6c...`

**What do you expect to happen?**

I expect it to take me to the home page for my notebooks, which it did prior to today.

**What actually happens?**

I get the "Token authentication is enabled" page.

Pasting in the token doesn't work; it is rejected with "invalid credentials"

**Comment by parente** [comment]
Could you run `ps aux | grep jupyter` from a terminal and see if there are jupyter processes running on your host machine?

**Comment by robmarkcole** [comment]
Can confirm I received this error when vscode was using jupyter in the background

**Comment by romainx** [comment]
@robmarkcole tanks for the confirmation. @parente and me had the same issue with VSCode plugin. We will consider adding this case in a troubleshooting section of the documentation. I've just created an issue to perform this task #1071, so I'm closing this one.

Thanks for your help.
Best.

**Comment by tim-blackmore** [comment]
I had this same problem today with Pycharm running in the background. Once Pycharm was closed I was able to use the token.

**Comment by doemerson123** [comment]
An easier way to address this is to route the ports differently. Here I route the 8001 port to 8888 (jupyter port)

``` docker run -p 8001:8888 jupyter/base-notebook```

**Comment by mathbunnyru** [comment]
@doemerson123 thank you!
could you maybe add this as a third choice here https://jupyter-docker-stacks.readthedocs.io/en/latest/using/troubleshooting.html#tokens-are-being-rejected?

**Comment by doemerson123** [comment]
PR created, great idea :)
