### ISSUE TITLE
Grant user romainx triage rights

### ISSUE THREAD

**Issue by parente** [jupyter/docker-stacks#1036]
@romainx has been helping out quite a bit with responding to issues and submitting pull requests here for the past couple months, and doing so in a positive way in keeping with the Jupyter Code of Conduct. I'd like to grant them triage rights as a stepping stone toward maintainer rights.

First, @romainx, are you interested? 😄 

Second, I don't believe we have a formal process for voting on elevating permissions in one-off Jupyter repos like this one, so I'm opening an issue here for community visibility and comment.

I'm planning to grant the permissions on March 11th.

**Comment by romainx** [comment]
@parente a big thank-you, I really appreciate your feedback and your proposal. So in short, off course I'm interested and ready to help :satisfied:!

**Comment by parente** [comment]
Granted triage role. @romainx, you should receive an invite in your email. 

https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level summarizes what the role grants.

Congrats and thank you for helping out. 🎈

**Comment by romainx** [comment]
@parente Thanks a lot. I will try my new role on the list of issues :smirk:.

**Comment by parente** [comment]
@romainx For reference, we adopted a system like JupyterLab uses to label issues here. It works reasonably well. Feel free to suggest improvements as you use it.

**Comment by romainx** [comment]
I just had a look and it sounds good. I've closed my first issue 😄
