### ISSUE TITLE
Users other than jovyan are unable to log into Jupyterhub through PAM authentication

### ISSUE THREAD

**Issue by ticoneva** [jupyter/docker-stacks#1048]
Users added through `adduser` cannot log into Jupyterhub through PAM authentication. I have tried the latest `jupyter/datascience-notebook` and `jupyter/tensorflow-notebook`  stock images and neither works, but if I revert back to an image from two years ago it does work. 

I have also tried giving a password to jovyan and it is able to log in even in the latest version, leading me to suspect that I have to tell Jupyterhub to update the list of users, or am I missing something else?

**Comment by ticoneva** [comment]
To answer my own question, launching Jupyterhub after creating the user accounts work. For reason that I do not quite understand, in the past I was able to launch Jupyterhub before creating the accounts.

**Comment by romainx** [comment]
@ticoneva sorry you were faster than us :snail:, thanks!

Maybe the answer to your question is in the [`create_system_users`](https://jupyterhub.readthedocs.io/en/stable/api/auth.html#jupyterhub.auth.PAMAuthenticator.create_system_users) parameter of the [`PAMAuthenticator`](https://jupyterhub.readthedocs.io/en/stable/api/auth.html#jupyterhub.auth.PAMAuthenticator) that is `False` by default.

> If set to True, will attempt to create local system users if they do not exist already.

Best

**Comment by ticoneva** [comment]
That's it. Thanks!

> Maybe the answer to your question is in the [`create_system_users`](https://jupyterhub.readthedocs.io/en/stable/api/auth.html#jupyterhub.auth.PAMAuthenticator.create_system_users) parameter of the [`PAMAuthenticator`](https://jupyterhub.readthedocs.io/en/stable/api/auth.html#jupyterhub.auth.PAMAuthenticator) that is `False` by default.
> 
> > If set to True, will attempt to create local system users if they do not exist already.
