### ISSUE TITLE
Please version tag docker images

### ISSUE THREAD

**Issue by ryanlovett** [jupyter/docker-stacks#105]
Can you please tag the containers at hub.docker.com? This will help our JupyterHub instances reproducibly deploy single user servers that pull from systemuser < scipy-notebook < minimal-notebook. We can alternatively maintain derivative containers images at Docker Hub but that is less desirable.

**Comment by parente** [comment]
The containers are tagged with a git SHA that links them to specific Dockerfile contents here in this repo. The details are in the README: https://github.com/jupyter/docker-stacks#stacks-tags-versioning-and-progress

The history for why this version scheme is used is in issue #12

**Comment by ryanlovett** [comment]
Thank you, sorry to have missed that.

**Comment by ryanlovett** [comment]
Would it be possible to add jupyterhub and systemuser to this build infrastructure so that they have tagged builds as well?

**Comment by parente** [comment]
Stacks for other jupyter projects fit right in with the intention of this repo. But I'll say right up front that I don't have experience with either of those, so someone knowledgeable will need to contribute and help maintain them.

**Comment by ryanlovett** [comment]
@minrk Could jupyterhub and systemuser get automatic commit-based tags? Should I file issues in those repos?

**Comment by parente** [comment]
@ryanlovett Did you open an issue against JupyterHub about versioning?  @minrk Do you think an opinionated, pre-configured-for-Docker-only set of Jupyter Hub images belong here in stacks?

**Comment by parente** [comment]
Going to close this. The images here are tagged. If someone develops a docker-ready Jupyter Hub stack, we can accept that PR.
