### ISSUE TITLE
Wrong PATH in start.sh when running as root

### ISSUE THREAD

**Issue by maresb** [jupyter/docker-stacks#1053]
I seem to have found a subtle bug in the `start.sh` script, and I have prepared a pull request to fix it.

For those not so deeply into the details, I'll first explain a bit about the context. 

In order to give the `jovyan` user `sudo` privileges, one must start the container as `root`. Thus running these Docker stacks as `root` is a common use case.

The `start.sh` script is documented [here](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html#start-sh). In short, it is a wrapper to ensure the correct environment when executing commands with `docker run` or `docker exec`. In particular, if the container is running as root, this script takes a command and uses `sudo -u jovyan` to run the command as `jovyan` instead of `root`.

When running the `sudo` command, the path is set from the `/etc/sudoers` file according to the `secure_path` variable. This variable is set by the `start.sh` script shortly before running the `sudo` command. Specifically, it appends `/opt/conda/bin` to `secure_path`.

As a result of appending the Conda path instead of prepending it, the system binaries in `/usr/bin/` take precedence over the Conda ones.

The following session illustrates the problem:

```
$ cat << EOF > wrong_python.sh
#!/bin/bash
echo "Wrong python executable invoked!"
EOF

$ chmod a+x wrong_python.sh
$ docker run \
    -it \
    --rm \
    --user root \
    -v $PWD/wrong_python.sh:/usr/bin/python:ro \
    jupyter/base-notebook \
        start.sh python \
;
Set username to: jovyan
usermod: no changes
Executing the command: python
Wrong python executable invoked!
```
What makes this particularly brutal to diagnose is that the output of `which` is misleading:
```
$ docker run \
    -it \
    --rm \
    --user root \
    -v $PWD/wrong_python.sh:/usr/bin/python:ro \
    jupyter/base-notebook \
        start.sh which python \
;
Set username to: jovyan
usermod: no changes
Executing the command: which python
/opt/conda/bin/python
```

**Comment by consideRatio** [comment]
:D crazy timing indeed! Thanks for writing this thorough issue that provides links and context etc @maresb! I'm working very actively to figure out all the details and improve some documentation that reduce future confusion, I had not yet read up on the actual documentation you linked to here, which is very good to have as it declares the intent of everything better than from within start.sh itself.

Hmm... with regards to the PATH, I think the correct call is to append conda to path in the dockerfile like ENV `PATH=conda...:$PATH` and then let make it pass through without change later.

**Comment by maresb** [comment]
Yes, I agree. Maintaining a separate `secure_path` is very confusing. Setting `PATH` from Dockerfile won't currently work. (Note: I haven't verified this.) Also, I can put scripts in `/usr/local/bin/before-notebook.d` to be run by the `run-hooks` function of `start.sh`, and I can set environment variables there. But setting `PATH` won't work. (I haven't verified this either.) **That's why I like your solution better.**

I'm skeptical about any security benefits of keeping `secure_path`, but it'd be nice to get the opinion of someone more experienced.
