### ISSUE TITLE
"Invalid Credentials" on jupyter notebook login

### ISSUE THREAD

**Issue by sumyuck** [jupyter/docker-stacks#1056]
I'm trying to access jupyter-notebook on my laptop and the actual process is running on a remote server. I have removed any hashed password in the jupyter_notebook_config.json file and also set c.NotebookApp.password = "" in the upyter_notebook_config.py file but it is still asking me for a password. I have literally tried every possible solution to it. I have even tried changing the password and then using the password in the notebook but it still says "Invalid credentials".

**Comment by sumyuck** [comment]
So I realized I just had to use the URL with the token generated rather than just browsing to localhost:port

**Comment by dvdblk** [comment]
In my case, this command: 
```
from notebook.auth import passwd; passwd()
```
Generated an `argon2` hashed password which for some reason jupyter notebook can't decode.

The solution was to use `sha1` as an argument to the function:

```
passwd(algorithm='sha1')
```

After pasting the output into `c.NotebookApp.password` I was able to log in!

**Comment by choijan78** [comment]
No way... This comments saved me!!!! 
I was suffering for 2 hours to find why I can't access to Jupiter notebook!!! Even I made password so well!!!!! 

Hahahaha.. Thank you so much! 

Watch out everybody. 
Jupyter notebook can *not* decode argon2 hashed password. 
USE sha1 !!!!!

**Comment by mathbunnyru** [comment]
@dvdblk @choijan78 if you could extend our docs to show how to generate passwords, that would be great.

**Comment by changxiaoju** [comment]
> So I realized I just had to use the URL with the token generated rather than just browsing to localhost:port

Now i face the same situation as you, but i dont quite understand what do you mean by using the URL with the token generated. is that something like http://localhost:8888/?token=c53bbd4d00828cb800c4d75af1b4fa433cdd0db90b512221? which still ask about token and password. looking forword to your reply

**Comment by Zhiwei-Zhai** [comment]
> In my case, this command:
> 
> ```
> from notebook.auth import passwd; passwd()
> ```
> 
> Generated an `argon2` hashed password which for some reason jupyter notebook can't decode.
> 
> The solution was to use `sha1` as an argument to the function:
> 
> ```
> passwd(algorithm='sha1')
> ```
> 
> After pasting the output into `c.NotebookApp.password` I was able to log in!

Thanks @dvdblk ! It works for me.

**Comment by mathbunnyru** [comment]
> Crazy that this isn't fixed... 

@throny could you please tell us what is not fixed?
We have docs describing how to generate hashed password and then how to use it.
It works well for me.

https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html

**Comment by throny** [comment]
@mathbunnyru I didn't meant you nor this project! Sorry if that was irritating, I meant the official tensorflow docker with jupyter tag.. Thanks to this issue I found a way to fix our issue.

**Comment by mathbunnyru** [comment]
Ah, ok :)
I'm glad to know our project works as expected :)
