### ISSUE TITLE
Token note working

### ISSUE THREAD

**Issue by abdoulsn** [jupyter/docker-stacks#1057]
Hello, I've an issue with token, I'm using macbook. when I past token, I got the error I`nvalid credentials `

**Comment by romainx** [comment]
Hello,

We had the same kind of issue yesterday and the user just figured out that it was a mistake on his side. Please check this issue #1056 and also ensure that you are using the URL outputted in the logs when you start the notebook. Something like the logs below.

```bash
[...]
Or copy and paste one of these URLs:
  http://3d4cf3809e3f:8888/?token=996426e890f8dc22fa6835a44442b6026cba02ee61fee6a2
  or http://127.0.0.1:8888/?token=996426e890f8dc22fa6835a44442b6026cba02ee61fee6a2
```

Best

**Comment by abdoulsn** [comment]
Hello thanks for answering, I always copy and past one of these but non worked. It ask the token.
ps: I’m running them using Kitematic so I get links from kitematic.

**Comment by parente** [comment]
@abdoulsn Could you please run `ps aux | grep jupyter` at a terminal on your mac and see if another Jupyter notebook server is running? A service running on port 8888 on your Mac will mask a service running Docker on the same port without errors in either startup.

I've hit this problem with vscode's support for notebooks launching a notebook server on my Mac which then masks one I've got running in docker.

**Comment by abdoulsn** [comment]
res
`abdoulayediallo   3412   0.2  0.1  4376556  24576   ??  S     5:05PM   0:10.37 /Users/abdoulayediallo/opt/anaconda3/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
abdoulayediallo   3411   0.0  0.0  4369428   6604   ??  S     5:05PM   0:00.98 /Users/abdoulayediallo/opt/anaconda3/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
abdoulayediallo   3410   0.0  0.0  4369428   6604   ??  S     5:05PM   0:00.99 /Users/abdoulayediallo/opt/anaconda3/bin/python -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.jupyter_daemon -v
abdoulayediallo   4245   0.0  0.0  4268324    712 s001  S+   10:23PM   0:00.00 grep jupyter`

**Comment by abdoulsn** [comment]
I restarted the mac, and just lunched it.

**Comment by romainx** [comment]
@abdoulsn Do you confirm it's Ok after the reboot?

PS: Nothing better than a reboot to solve a problem 😄 

Many thanks.

**Comment by abdoulsn** [comment]
Yes yes, I never shutdown my mac, ... thanks.

**Comment by romainx** [comment]
Ok let's close it so. Thank you @parente for the help :chocolate_bar:
