### ISSUE TITLE
no module named lxml

### ISSUE THREAD

**Issue by jamesbeake** [jupyter/docker-stacks#106]
I get the error:
"No module named lxml"
when attempting:
"import lxml"

Using python 2

Any suggestions?

Full error text:
ImportError                               Traceback (most recent call last)
<ipython-input-1-3a2be3d699bf> in <module>()
----> 1 import lxml
ImportError: No module named 'lxml'

**Comment by parente** [comment]
It's probably not in the stack image you're using. You can install it with conda or pip at runtime, or build a child Docker image that runs one of those commands to do it.

**Comment by jamesbeake** [comment]
Thanks for the tip. I'll give it a try.
By the way, I should have mentioned I'm using the Data-Science image.

**Comment by parente** [comment]
@jamesbeake did `conda install -y lxml` work for you?

**Comment by jamesbeake** [comment]
@parente It did. Thank you.
