### ISSUE TITLE
Pandas on jupyter/scipy-notebook missing optional dependency

### ISSUE THREAD

**Issue by mpmdean** [jupyter/docker-stacks#1063]
**What docker image you are using?**
jupyter/scipy-notebook

**What complete docker command do you run to launch the container (omitting sensitive values)?**
jupyter-repo2docker --editable --image-name jupyter/scipy-notebook

**What do you expect to happen?**

PyTables, an optional dependency of pandas, seems not to be installed. (See the atttached image.) I would be happy to contribute a PR on this. 
![Screen Shot 2020-04-16 at 5 09 49 PM](https://user-images.githubusercontent.com/699991/79508491-a9326500-8007-11ea-86c0-134e3f017025.png)

**Comment by romainx** [comment]
Hello @mpmdean,

Nice catch. We will be happy to have a PR for that 😄

# Rationale
`scipy-notebook` already supports [`HDF5`](https://www.hdfgroup.org/) format through the [`hdf5`](http://docs.h5py.org/en/stable/) and [`h5py`](https://www.h5py.org/) packages. So it makes sense to also support this format through `pandas`.

# Solution

You're right to do that we need to install [`pytables`](https://www.pytables.org/)
> For example, `pandas.read_hdf()` requires the `pytables package`, [...] 
> -- [pandas optional dependencies](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#optional-dependencies)

# Notes

* The minimum version required is `3.4.2` and the version `3.6.1` is available on `conda-forge`.
* According to the [installation guide](https://www.pytables.org/usersguide/installation.html) the package to install through conda is called **`pytables`**. It needs `hdf5` that is already installed.
* The import of the package `pytables` will be tested automatically. I don't know if it would be worth adding a test to check if a `HDF5` file can be read?

So thank you if you want to work on it :blush:.
Best.

**Comment by mpmdean** [comment]
@romainx @parente

I think this can now be closed following #1069

**Comment by romainx** [comment]
@mpmdean you're right a big thank-you for your help 🍰
