### ISSUE TITLE
start.sh adds conda path to secure_path for sudoers, which fails on centos redhat images

### ISSUE THREAD

**Issue by carstenpohllhind** [jupyter/docker-stacks#1064]
**What docker image you are using?**

`jupyter/base-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

This does not apply here.

**What steps do you take once the container is running to reproduce the issue?**

If you change the docker image to a redhat / centos based image, the start.sh will fail, and you will see an output similar to:
`Set username to: jovyan
usermod: no changes
Executing the command: jupyterhub-singleuser --ip=0.0.0.0
sudo: jupyterhub-singleuser: command not found`

**What do you expect to happen?**

The notebook should start, and the start should not throw an error.

**What actually happens?**

The notebook does not start.

**Additional info**

The problem lies within the sed command, that tries to get the information of the secure_path from the sudoers file. The regexp inside the sed command expects spaces before and after the equals sign, and double quotes before the path variables. This is the case in the Ubuntu / debian-esque /etc/sudoers file, but not in an centos based image, wich omits the double quotes and has trailing and leading spaces before the parameter name.

**Comment by romainx** [comment]
Hello,

Thank you for the issue and the PR #1065 that seems OK.
I have posted a review in it asking a question about one test supposed to check this behavior.

Best.
