### ISSUE TITLE
Install bottleneck in scipy-notebook to provide speed improvements to pandas

### ISSUE THREAD

**Issue by romainx** [jupyter/docker-stacks#1066]
Hello,

[`bottleneck`](https://github.com/pydata/bottleneck) is one of the two recommended dependencies of pandas, the other being `numexpr` that is already installed in `scipy-notebook`.

https://github.com/jupyter/docker-stacks/blob/dc9744740e128ad7ca7c235d5f54791883c2ea69/scipy-notebook/Dockerfile#L32

Here is a quote from the pandas documentation.

> ## Recommended dependencies
> * **`bottleneck`**: for accelerating certain types of `nan` evaluations. `bottleneck` uses specialized `cython` routines to achieve large speedups. If installed, must be Version 1.2.1 or higher.
>
> **Note**
> You are highly encouraged to install these libraries, as they provide speed improvements, especially when working with large data sets.
>  --- [Pandas recommended dependencies](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#recommended-dependencies)

The latest version of the library available in `conda-forge` is higher than the minimal version (`1.3.2`), so it's OK.  The package is lightweight (~ 120KB), it will not have a big impact on the size of the images.

If someone could submit a PR it would be great. :kissing:
Best.

**Comment by mpmdean** [comment]
@romainx @parente 

I think this can now be closed following #1069

**Comment by romainx** [comment]
@mpmdean you're right a big thank-you for your help 🍰
