### ISSUE TITLE
Create a troubleshooting page in the documentation

### ISSUE THREAD

**Issue by romainx** [jupyter/docker-stacks#1071]
Hello,

The objective is to write a troubleshooting page for know issues.

# Cases identified

Here is the list of identified known issues.

## Permission denied when mounting local folders

This is a recurring issue, there is a PR (#1078) in progress to update the documentation 

- #542
- #885
- #1003
- #1187 

## Container launching issue

In recent issues (#1035, #1057) the same problem and the same root cause have been identified.
The VS Code plugin is running (silently) in the background and it prevents users to launch their Jupyter Docker Stack.

- #1035
- #1057

## Package installation

Packages cannot be installed the cause can be the `strict` conda channel priority.

- #1085

# Template

To write the troubleshooting case we have to use a template with, for example, the following sections (this is a first draft / proposal).

- Problem
- Cause
- Solution

Best

**Comment by romainx** [comment]
Hello @trallard, great. I will be able to give you a hand if needed, however I will be off for a few days (not sure I will have the time to have a look on your contribution regarding cookie-cutter).
I had noticed that JupyterHub has a [troubleshooting page](https://jupyterhub.readthedocs.io/en/stable/troubleshooting.html), maybe we could take some ideas from this template?

Thanks a lot

**Comment by analistacarlosh** [comment]
Hey, 
Maybe this can also be added on this troubleshooting page:
https://github.com/jupyter/docker-stacks/issues/1505

**Comment by mathbunnyru** [comment]
> Hey,
> Maybe this can also be added on this troubleshooting page:
> #1505

I think I answered your question and everything works as expected and the documentation is correct.
Please, reply to me in your issue, if something looks wrong to you.

**Comment by trallard** [comment]
I am sorry I started working on this and never got around to finish it 🤦🏽‍♀️  I will get back onto this. Will perhaps open a draft PR to get feedback as I add items

**Comment by mathbunnyru** [comment]
@trallard may I ask you if you would like to continue working on this issue? :)

**Comment by trallard** [comment]
Definitely - need to keep myself accountable and get this done. Been hanging for a while sorry

**Comment by mathbunnyru** [comment]
Thanks, @trallard for your work. I think we can close this issue for now.
If there is something more to add, we will deal with it in the future.
