### ISSUE TITLE
Upgrading tensorflow to 2.2.0

### ISSUE THREAD

**Issue by rantav** [jupyter/docker-stacks#1081]
**What docker image you are using?**
`jupyter/tensorflow-notebook`

**When is the upgrade expected?**
Hi there, any thoughts on upgrading [`jupyter/tensorflow-notebook`](https://github.com/jupyter/docker-stacks/blob/master/tensorflow-notebook/Dockerfile) to [tensorflow 2.2.0](https://github.com/tensorflow/tensorflow/releases/tag/v2.2.0), released and stable a few days ago?

**Comment by romainx** [comment]
Hello,

Sure we have a PR 1080 in progress jut for that. The latest version will ba available once this PR merged.

Best

**Comment by rantav** [comment]
Great! Closing
