### ISSUE TITLE
Conda install problem: Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.

### ISSUE THREAD

**Issue by thudxz** [jupyter/docker-stacks#1085]
Hi! 

I am using the latest datascience-notebook image and want to install a bioconductor package using the following code:

`
RUN conda install -c bioconda bioconductor-geoquery
`

It returned the following message:

`
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
`

I googled and found two similar issues [https://github.com/conda/conda/issues/9653](conda/issues/9653) and [https://github.com/conda/conda/issues/9367](conda/issues/9367). However, I can not solve the problem.

**Comment by romainx** [comment]
Hello @thudxz,

We have turned `conda` channel priority to `strict`.

```bash
$ conda config --show | grep priority
# channel_priority: strict

# To see its meaning
$ conda config --describe channel_priority
```

So you can install the package by disabling it since the package you want to install comes from the `bioconda` channel.

```bash
# Install by disabling channel priority at command level
$ conda install --no-channel-priority -c bioconda bioconductor-geoquery

$ conda list | grep bio
# bioconductor-biobase      2.46.0            r36h516909a_0    bioconda
# bioconductor-biocgenerics 0.32.0                    r36_0    bioconda
# bioconductor-geoquery     2.54.0                    r36_0    bioconda
# bioconductor-limma        3.42.0            r36h516909a_0    bioconda
```

## Note

The last version `2.56` is not installed since it requires `r-base 4.0` which is not (yet) installed on `jupyter-datascience`.

```bash
$ conda search -c bioconda --info bioconductor-geoquery=2.56.0

# Loading channels: done
# bioconductor-geoquery 2.56.0 r40_0
# dependencies: 
#   - bioconductor-biobase >=2.48.0,<2.49.0
#   - bioconductor-limma >=3.44.0,<3.45.0
#   - r-base >=4.0,<4.1.0a0
# [...]
```

Please tell us if it's Ok for you?
Best

**Comment by thudxz** [comment]
It worked. Thank you.

**Comment by romainx** [comment]
Great to hear that.
Thank you.

## Note
I will add this case to the troubleshooting doc I intend to write (#1071)
