### ISSUE TITLE
Missing CONDA_PREFIX

### ISSUE THREAD

**Issue by maresb** [jupyter/docker-stacks#1086]
I conda installed [`code-server`](https://github.com/cdr/code-server) and [`jupyter-vscode-proxy`](https://github.com/betatim/vscode-binder) in order to run VS Code from JupyterLab. The feedstock for `code-server` [generates a eponymous bash script](https://github.com/conda-forge/code-server-feedstock/blob/master/recipe/build.sh) which relies on the `CONDA_PREFIX` environment variable. I get a beautiful "VS Code" launcher icon, but upon pressing it, I get the following error in the console:
```
Error: Cannot find module '/share/code-server/out/node/entry.js'
```
The error is easily explained by the fact that the `/opt/conda` prefix is defined in `CONDA_DIR` while `CONDA_PREFIX` is empty.

As far as I can tell, `CONDA_PREFIX` should be defined in any activated conda environment. (Almost all my conda experience is via these Docker images.) Hence I'm filing the issue here.

Would it be appropriate to rename `CONDA_DIR` to `CONDA_PREFIX` everywhere? And for good measure set it inside `base-notebook` to avoid breaking compatibility? Or is there some reason to instead use `CONDA_DIR`?

**Comment by bollwyvl** [comment]
CONDA_DIR is indeed non-standard. Unfortunately, just setting some env vars
is not sufficient. Not fully activating the  environment is no doubt a
source of subtle problems.... As packages get more complex (e.g anything
that uses Java, or a runtime compiler) they end up relying on activation
scripts.

About the only thing that would work for arbitrary "docker exec" is a
wrapper script in ENTRYPOINT, which might already be used for tini, to do
"source activate".

**Comment by maresb** [comment]
To clarify, I'm not actually using `docker exec`. I have my own `Dockerfile` extending these containers, so I'm still using the standard activation scripts. But perhaps this is yet another factor to consider in https://github.com/jupyter/docker-stacks/pull/1052.

**Comment by romainx** [comment]
Hi @maresb 

`CONDA_DIR` even if not standard is basically used everywhere in these images and probably elsewhere in custom images build by users. So it seems complicated to remove it. 
Moreover the two variables have not the same intend

* `CONDA_DIR`: the root of the `conda` distribution installation.
* `CONDA_PREFIX`: the path to the conda environment [source][LK1]

So they can be different when using different environment.

```bash
(base) jovyan@bf28b762e660:/opt/conda$ env | grep -E '(CONDA_DIR|CONDA_PREFIX)'
# CONDA_PREFIX=/opt/conda
# CONDA_DIR=/opt/conda

# In a custom test env
(base) jovyan@bf28b762e660:/opt/conda$ conda activate test
(test) jovyan@bf28b762e660:/opt/conda$ env | grep -E '(CONDA_DIR|CONDA_PREFIX)'
# CONDA_PREFIX=/opt/conda/envs/test
# CONDA_DIR=/opt/conda
# CONDA_PREFIX_1=/opt/conda
```

What you have pointed and that could be solved is to **properly initiate the `base` environment** in the `base-notebook` since it's not done and so the `CONDA_PREFIX` is not defined--what is not correct I agree.

```bash
# Not set at startup
$ env | grep -E '(CONDA_DIR|CONDA_PREFIX)'
# CONDA_DIR=/opt/conda

# Activating the base environment
$ conda init bash
$ bash
$ conda activate base
$ env | grep -E '(CONDA_DIR|CONDA_PREFIX)'
# CONDA_PREFIX=/opt/conda
# CONDA_DIR=/opt/conda
```
Maybe I missing something but I guess is something possible.

[LK1]:  https://docs.conda.io/projects/conda-build/en/latest/user-guide/environment-variables.html#environment-variables-that-affect-the-build-process

**Comment by romainx** [comment]
Hello,

This change has been implemented in the PR #1161 

Best.

**Comment by nthiery** [comment]
Hello!
Thank you for resolving this issue. There remains a corner case however with
the current implementation: if a barebone shell is launched, then the environment
variables are not set. For example, with a Python or C++ kernel, the following
command will just show `CONDA_DIR=/opt/conda`:
```
!env | grep CONDA 
```

Presumably one would want to launch jupyter itself with all the
environment variables configured. Maybe by using an entry
point such as `conda run jupyter ...`.

For now I am using as workaround
```
%bash --login
...
```
but this is tricky to find for end users.

Use case: in a C++ course, we include calls to compilation commands
to explain in the course notes how to compile; students also include them
in the support of their presentation to run the compilation and execution
of their programs. These compilation commands often need a fully
configured environment.

**Comment by mathbunnyru** [comment]
> Hello!
> 
> Thank you for resolving this issue. There remains a corner case however with
> 
> the current implementation: if a barebone shell is launched, then the environment
> 
> variables are not set. For example, with a Python or C++ kernel, the following
> 
> command will just show `CONDA_DIR=/opt/conda`:
> 
> ```
> 
> !env | grep CONDA 
> 
> ```
> 
> 
> 
> Presumably one would want to launch jupyter itself with all the
> 
> environment variables configured. Maybe by using an entry
> 
> point such as `conda run jupyter ...`.
> 
> 
> 
> For now I am using as workaround
> 
> ```
> 
> %bash --login
> 
> ...
> 
> ```
> 
> but this is tricky to find for end users.
> 
> 
> 
> Use case: in a C++ course, we include calls to compilation commands
> 
> to explain in the course notes how to compile; students also include them
> 
> in the support of their presentation to run the compilation and execution
> 
> of their programs. These compilation commands often need a fully
> 
> configured environment.

@nthiery could you please create a new issue using provided issue template and providing exact commands you run.

**Comment by nthiery** [comment]
Thanks for feedback. Done in #2043.
