### ISSUE TITLE
Start using ubuntu 20.04 (focal)

### ISSUE THREAD

**Issue by mathbunnyru** [jupyter/docker-stacks#1089]
As Canonical released a new LTS version of Ubuntu, it might be a good idea to start using it - various security updates, optimizations, features and package updates should be good.

**Comment by romainx** [comment]
Hello @mathbunnyru 

I though exactly about the thing. 

I've compared the size and it's basically the same (+10MB).
```bash
$ docker system df -v

# Images space usage:
# 
# REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE                SHARED SIZE         UNIQUE SIZE         CONTAINERS
# ubuntu                  focal               1d622ef86b13        3 weeks ago         73.85MB             0B                  73.85MB             0
# ubuntu                  bionic              c3c304cb4f22        3 weeks ago         64.21MB             64.21MB             0B                  0
```
And I had a look at the [FocalFossa Release Notes](https://wiki.ubuntu.com/FocalFossa/ReleaseNotes).

However I was wondering how to validate this change (mainly in term of system packages)  :worried:?

Best

**Comment by mathbunnyru** [comment]
I think it would be better to compare image sizes after installation of the dependencies. Because the dependencies might have changed as well in terms of size. For example, scipy-notebook based on 18.04 and based on 20.04.

There are so many ways how things could break. I can create a PR, try to make it build and pass all the tests and then we could wait for a while, till people, who know the infrastructure the best, verify that everything works quite fine.

I mean, it would be great to have tests for everything, but it is not something that can easily be done.

**Comment by romainx** [comment]
@mathbunnyru Yes you're right you can draft a PR and see what happen.
A full build OK will be the first test 😄

**Comment by mathbunnyru** [comment]
I already tried to build everything.
There's one big problem though.

It is impossible to install mesos package in Ubuntu 20.04 - it requires to have libcurl3 installed.

As far as I see, mesos has not been working for 2 years since Ubuntu 18.04 (https://github.com/jupyter/docker-stacks/issues/663)

And I see there is WIP to remove mesos (https://github.com/jupyter/docker-stacks/pull/911)

Unfortunately, I know nothing about mesos.

@parente could you please take a look at your pull request?
I think removing mesos will make it much easier to switch to Ubuntu 20.04.
@romainx what do you think?

**Comment by bollwyvl** [comment]
Recall, too, that Ubuntu itself won't offer upgrading between LTS versions
until the .1 release... No harm in starting the effort, but if folks are
relying on LTS stability, it might be surprising to get it "early".

**Comment by mathbunnyru** [comment]
Done
