### ISSUE TITLE
Build issue affecting r-notebook

### ISSUE THREAD

**Issue by romainx** [jupyter/docker-stacks#1090]
Hello,

We are facing a build issue affecting

- `r-notebook`
- `datascience-notebook` (not sure)

The problem is `UnsatisfiableError` thrown by `conda`, here is an extract of the [trace](https://travis-ci.org/github/jupyter/docker-stacks/builds/689508561#L3362).

<details>
<summary>Conda error</summary>

  ```bash
 UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:
Specifications:
  - alembic -> python[version='>=3.8,<3.9.0a0']
  - bleach -> python[version='>=3.8,<3.9.0a0']
  - brotlipy -> python[version='3.4.*|3.6.9|3.8.*|3.7.*',build='2_73_pypy|1_73_pypy|0_73_pypy']
  - cffi -> python[version='2.7.*|3.5.*|3.6.*|3.6.9|3.6.9|>=3.8,<3.9.0a0|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0|3.4.*',build='2_73_pypy|1_73_pypy|0_73_pypy']
  - cryptography -> python[version='3.4.*|3.6.9|3.8.*|3.7.*|<=3.3',build='2_73_pypy|1_73_pypy|0_73_pypy']
  - jinja2 -> python[version='>=3.8,<3.9.0a0']
  - jupyterlab_server -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.8,<3.9.0a0|3.4.*']
  - mako -> python[version='>=3.8,<3.9.0a0']
  - oauthlib -> python[version='>=3.8,<3.9.0a0']
  - packaging -> python[version='>=3.8,<3.9.0a0']
  - prometheus_client -> python[version='>=3.8,<3.9.0a0']
  - pygments -> python[version='>=3.8,<3.9.0a0']
  - python-dateutil -> python[version='>=3.8,<3.9.0a0']
  - python-json-logger -> python[version='2.7.*|3.5.*|3.6.*']
  - testpath -> python[version='3.4.*|>=3.8,<3.9.0a0']
Your python: python=3.7
If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
The following specifications were found to be incompatible with each other:
Output in format: Requested package -> Available versions
Package entrypoints conflicts for:
jupyterhub=1.1.0 -> entrypoints
ipykernel -> jupyter_client -> entrypoints
jupyter_client -> entrypoints
notebook=6.0.3 -> jupyter_client[version='>=5.3.4'] -> entrypoints[version='>=0.2.2']
nbconvert -> entrypoints[version='>=0.2.2']
pyjwt -> flake8 -> entrypoints[version='>=0.3.0,<0.4.0']
jupyterhub-base -> entrypoints
```
</details>

<details>
<summary>Conda config
</summary>
$ conda config --show
add_anaconda_token: True
add_pip_as_python_dependency: True
aggressive_update_packages:
  - ca-certificates
  - certifi
  - openssl
allow_conda_downgrades: False
allow_cycles: True
allow_non_channel_urls: False
allow_softlinks: False
always_copy: False
always_softlink: False
always_yes: None
anaconda_upload: None
auto_activate_base: True
auto_stack: 0
auto_update_conda: False
bld_path:
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: strict
channels:
  - conda-forge
  - defaults
client_ssl_cert: None
client_ssl_cert_key: None
clobber: False
conda_build: {}
create_default_packages: []
croot: /opt/conda/conda-bld
custom_channels:
  pkgs/main: https://repo.anaconda.com
  pkgs/r: https://repo.anaconda.com
  pkgs/pro: https://repo.anaconda.com
custom_multichannels:
  defaults:
    - https://repo.anaconda.com/pkgs/main
    - https://repo.anaconda.com/pkgs/r
  local:
debug: False
default_channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
default_python: 3.7
default_threads: None
deps_modifier: not_set
dev: False
disallowed_packages: []
download_only: False
dry_run: False
enable_private_envs: False
env_prompt: ({default_env})
envs_dirs:
  - /opt/conda/envs
  - /home/jovyan/.conda/envs
error_upload_url: https://conda.io/conda-post/unexpected-error
execute_threads: 1
extra_safety_checks: False
force: False
force_32bit: False
force_reinstall: False
force_remove: False
ignore_pinned: False
json: False
local_repodata_ttl: 1
migrated_channel_aliases: []
migrated_custom_channels: {}
non_admin_enabled: True
notify_outdated_conda: True
offline: False
override_channels_enabled: True
path_conflict: clobber
pinned_packages: []
pip_interop_enabled: False
pkgs_dirs:
  - /opt/conda/pkgs
  - /home/jovyan/.conda/pkgs
proxy_servers: {}
quiet: False
remote_backoff_factor: 1
remote_connect_timeout_secs: 9.15
remote_max_retries: 3
remote_read_timeout_secs: 60.0
repodata_fns:
  - current_repodata.json
  - repodata.json
repodata_threads: None
report_errors: None
restore_free_channel: False
rollback_enabled: True
root_prefix: /opt/conda
safety_checks: warn
sat_solver: pycosat
separate_format_cache: False
shortcuts: True
show_channel_urls: True
solver_ignore_timestamps: False
ssl_verify: True
subdir: linux-64
subdirs:
  - linux-64
  - noarch
target_prefix_override:
track_features: []
unsatisfiable_hints: True
unsatisfiable_hints_check_depth: 2
update_modifier: update_specs
use_index_cache: False
use_local: False
use_only_tar_bz2: False
verbosity: 0
verify_threads: 1
whitelist_channels: []
```
</details>

Best

**Comment by romainx** [comment]
Do not understand why this problem is resolved now. I'm a bit lost ... 😵

**Comment by parente** [comment]
I suspect there was a package rebuild or release in conda-forge causing the incompatibility which fixed thereafter.
