### ISSUE TITLE
Token authentification issue

### ISSUE THREAD

**Issue by sryadgir** [jupyter/docker-stacks#1106]
Hi,
I'm having the same issue reported here: https://github.com/jupyter/notebook/issues/2716
That issue is closed and the solutions offered there don't fix my problem.
Here are the details:
Problem: I've been using these fantastic docker images to run jupyter notebook until today when suddenly I started being prompted for a token when starting a notebook. Nothing seems to satisfy the token and the various solutions I've found online have all failed.

I'm using jupyter/minimal-notebook
I've tried:
`docker run --name jup --rm -p 8888:8888 jupyter/minimal-notebook` 
`docker run --name jup --rm -p 0:0:0:0:8888:8888 jupyter/minimal-notebook` 
`docker run --name jup --rm -p 8888:8888 jupyter/minimal-notebook start.sh jupyter notebook --ip=0.0.0.0`
`docker run --name jup --rm -p 8888:8888 jupyter/minimal-notebook start.sh jupyter notebook --NotebookApp.token=""`
`docker run --name jup --rm -p 8888:8888 -e JUPYTER_TOKEN="" jupyter/minimal-notebook`
`docker run --name jup --rm -p 8888:8888 -e PASSWORD="" jupyter/minimal-notebook`

All of these successfully run a jupyter notebook and return valid URLs that I can click on, which takes me to a page asking for a token or password. Any input value is invalid. In the above lines of code I've tried setting the token or password to "password". Inputing "password" when prompted is still invalid.

Other info that may be relevant:
- I'm running this on a Windows 10 machine that I am remotely accessing.
- I'm typically running from VS code but have also tried directly from Powershell with the same results.
- I'm typically mounting several drives in my `docker run` call, some of which are network drives. It doesn't seem like these are causing any issues since I get the same problem when I don't mount any drives, as in the above examples.

Hopefully you can help me out since using jupyter notebook from Docker has been a life saver for me!

**Comment by romainx** [comment]
Hello,

It looks like a known issue. Are you using VS Code?
If so, it could be the VS Code Jupyter plugin running in the background that is causing the issue. Check the following issues for more information.

- #1035
- #1057

Please tell us if it solves your problem.
Best.

**Comment by romainx** [comment]
Hello @sryadgir ,

I'm closing this case because we have no feedback.
Feel free to post an update if you still have the problem.

Best.
