### ISSUE TITLE
Automated build for 'ubuntu_14_04_locale_fix'

### ISSUE THREAD

**Issue by dcbishop** [jupyter/docker-stacks#111]
Seems kind of silly to have an automated build for the main images but not the image that they are based on.

**Comment by jakirkham** [comment]
The `ubuntu_14_04_locale_fix` image only exists as a base image for the one present here ( https://github.com/jupyter/notebook/blob/master/Dockerfile ). It actually has no relationship with the other images built from this repo. If you want to understand why this exists at all, please see this PR ( https://github.com/jupyter/notebook/pull/547 ).

The more general automated build question for other images built from this repo is a bit more complicated. While this was initially done, there were many issues present with how automated builds happened and so it made more sense to do them manually. Please see this issue ( https://github.com/jupyter/docker-stacks/issues/12 ) for more information about how that decision was reached.

**Comment by parente** [comment]
Thanks @jakirkham for responding. 

I think I speak for everyone when adding that we'd love to automate all the builds here too (see #7). I and others just haven't found the time to put in the effort of getting *robust* automated builds running somewhere that can take into account the dependencies and not run afoul of the problems we hit using Docker Hub automated builds.

**Comment by parente** [comment]
We'll continue to track automated builds in #7. I don't think we need to automate the ubuntu locale fix image which isn't even used here. Feel free to reopen if this is a problem.
