### ISSUE TITLE
Using squash commits in the master

### ISSUE THREAD

**Issue by mathbunnyru** [jupyter/docker-stacks#1110]
I propose to start using squash commits in the master for PRs.
It will make it much easier to read commit history.

I think GitHub handles it quite well, so maybe it's worth giving it a try.

All the details are located here:
https://cloudfour.com/thinks/squashing-your-pull-requests/

I attached `tig` from the master, which is not easy to read at all.

<img width="1552" alt="Screenshot 2020-06-14 at 19 07 29" src="https://user-images.githubusercontent.com/12270691/84599429-4d068880-ae72-11ea-993d-8d076abcf0bc.png">

**Comment by romainx** [comment]
Hello, sorry I did not react to that since I have no opinion nor feedback on how it's done on other similar project.
However it's interesting, @parente what is your opinion?

**Comment by parente** [comment]
I'm OK squashing PRs that have a lot of iteration happening in them (e.g., fix, fix, fix, typo) and as long as the original contributor name is preserved as the author in the git history (i.e., we want to recognize people for their contributions).

**Comment by mathbunnyru** [comment]
I see, there might be some problems with that.
I need to investigate this question.

**Comment by mathbunnyru** [comment]
Sometimes I do squash merging, but I'm actually fine wirth merges, so let's keep the way it is right now.

**Comment by mathbunnyru** [comment]
I started using squash merges for everything - the history looks much cleaner.

**Comment by consideRatio** [comment]
It reads clearer on the high level overview, but when you have a PR that does something somewhat advanced and broken apart in multiple commits, that kind of lower lever overview is lost. I find such lower level overview is relevant in bigger PRs only. Due to that, I think its good to avoid a policy to always do it.

I'm not so happy about a squash also makes the person merging the commit author, and destroys possible git commit's signatures etc.

Overall, I lean towards preferring not squashing. I do rebase my PRs as often I can before they are merged to help keep the commit history cleaner.

**Comment by mathbunnyru** [comment]
Thank you for your feedback @consideRatio.

> I do rebase my PRs as often I can before they are merged to help keep the commit history cleaner.

This doesn't work for me, because it's not easy to review PRs that do lots of rebases and you lose the history of your review and need to watch all the files again.

**Comment by mathbunnyru** [comment]
> I'm not so happy about a squash also makes the person merging the commit author, and destroys possible git commit's signatures etc.

@consideRatio I've just checked this and if you create a squash-merge from the GitHub website (and I always use this feature), then the author is correct.
You can see it here:
- PR: https://github.com/jupyter/docker-stacks/pull/1825
- Commit in main: https://github.com/jupyter/docker-stacks/commit/10e52ee84369aaa37630aea13c137b766ace307b

Moreover, co-author is added if needed.
