### ISSUE TITLE
Unable to Access Jupyter Notebooks

### ISSUE THREAD

**Issue by eaboyle57** [jupyter/docker-stacks#1116]
What docker image you are using?

jupyter/pyspark-notebook

I pulled this image today.

What complete docker command do you run to launch the container (omitting sensitive values)?

docker run -p 8888:8888 -p 4040:4040 -v 'C:\Users\{userID}\be\lake':/lake jupyter/pyspark-notebook:latest

What steps do you take once the container is running to reproduce the issue?

Connect to the suggested URL: http://127.0.0.1:8888/?token=a4405d51cde6c...

What do you expect to happen?

I expect it to take me to the home page for my notebooks, which it did prior to today.

What actually happens?

I get the "Token authentication is enabled" page.

Pasting in the token doesn't work; it is rejected with "invalid credentials"

Looking through many related tickets and issues, I can provide the additional context:
- While I usually use VS Code, I stopped using it to run these docker commands, nor do I have any Jupyter extensions intalled
- '''docker exec -it {container} bash
     ps aux | grep jupyter'''
    -Produces 'jovyan       7  0.2  1.9  73280 64744 ?        S    07:16   0:00 /opt/conda/bin/python /opt/conda/bin/jupyter-notebook
jovyan      34  0.0  0.0   6436   656 pts/0    S+   07:21   0:00 grep --color=auto jupyter'
- Notebook pw is '' in config nor have I ever used one before
- Token isn't accepted
- Issue occurs sporadically, I was working in a notebook, then got a 'Forbidden' error, then wasn't able to connect.  An hour later, it came back seemingly w/o any intervention.
- Power cycle laptop, restart Docker, multiple container kills, starts, and stops, nothing has helped consistently.

**Comment by Bidek56** [comment]
This seem to be a personal setup/hardware issue, I use these images all day and they work just fine.
Unless the issue can be reproduced, how can anyone debug the issue?

**Comment by eaboyle57** [comment]
Bidek, I've alluded to multiple tickets (#1035, #1057 ) in which the same issue is being encountered and troubleshooting steps led to the discovery of a recurring issue and incompatibility with other software. All you're saying is "it works on my computer".

**Comment by eaboyle57** [comment]
Found out the issue _was_ caused by VS Code.  The Python extension is starting a Jupyter server on startup which is interfering with port 8888.  Disabling Jupyter startup through VS Code has so far resolved my issue.

**Comment by DaviYokogawa** [comment]
@eaboyle57 disabling the Jupyter extension of Vscode solves my problem, but if I want to use both together, do you know how to do it?
