### ISSUE TITLE
Uploading own Jupyter file and making a docker Image for it

### ISSUE THREAD

**Issue by techie-jai** [jupyter/docker-stacks#1124]
If I upload my own juypter file and then want to make an image with that file inside, how can I do that

**Comment by Bidek56** [comment]
What do you mean by `juypter file`?

You probably want extend the existing Docker images by creating new Dockerfile with:
```
FROM jupyter/jupyter/base-notebook:latest
ADD my-newfile.json requirements.txt my-docker-image-directory/
```

Then building it by using: `docker build -t my-docker-container .`

May want to check this [tutorial](https://docs.docker.com/get-started/part2/)

**Comment by romainx** [comment]
Thanks @Bidek56 for this clear answer.
@techie-jai is it Ok for you?

**Comment by techie-jai** [comment]
Hi

Thank you for your reply. I am re-trying this today. Probably should work.

Thank you

**Comment by techie-jai** [comment]
I have a project that works perfectly on a Jupyter notebook. However, I want it to be an docker image, so that anybody can fetch and use it. I have a normal data train.csv file and a Jupyter Notebook file "myproject.pynb". I want a single image where these two files are pre-loaded and I just have to fetch and run a single image to make it work

**Comment by chenbr** [comment]
There’s many ways to skin that. Ping me and I can show you

**Comment by techie-jai** [comment]
ok sure, thanks

**Comment by techie-jai** [comment]
@chenbr where should I ping you

**Comment by parente** [comment]
@techie-jai If your project is public, you might want to try https://mybinder.org/ which allows anyone on the internet to launch a Jupyter notebook from the contents of your GitHub repository.

If you want people to run your notebooks locally or share them privately, you could also look into https://github.com/jupyterhub/repo2docker which builds a Docker images for git repositories. (It's what mybinder.org uses.)

**Comment by chenbr** [comment]
email is good..

**Comment by romainx** [comment]
Hello,

I'm closing this issue because @parente has given a smart answer and now the discussion is more a specific case and discussion than a topic for the community.
Feel free to reopen it if it's not the case.

Best.
