### ISSUE TITLE
Grant romainx maintainer rights

### ISSUE THREAD

**Issue by parente** [jupyter/docker-stacks#1133]
@romainx has continued to help triage issues, submit pull requests, and review pull requests in this repo since receiving triage rights in #1036. I'd like to grant them maintainer access which adds the ability to merge PRs after review.

Before I take that step, @romainx, are you interested? I want this change to place no new expectations on your time or commitment to the project, only afford you the privilege to click a merge button instead of a "ready to merge" button. 😁 

I'm opening an issue here for community visibility and comment like in #1036 since we have no formal process for one-off Jupyter repos.

I'll grant the access after August 8th if @romainx agrees and there's no other dissent.

**Comment by romainx** [comment]
Hello @parente,

I'm learning a lot and I feel that the work we do here is useful to the community.
So I thank you and gladly accept your proposal.
I will do my best to continue my contribution -- and avoid breaking anything.

Many thanks and see you soon.

**Comment by parente** [comment]
I see two thumbs up and no dissent. I'm granting the permissions now.

Thank you for your continued work in the Jupyter community, @romainx. 🎈

**Comment by romainx** [comment]
@parente Thank you to take care of contributors and maintainers like you do. It's really a pleasure to collaborate within this community.
