### ISSUE TITLE
Adding a Jupyter pynb and csv File in the starting

### ISSUE THREAD

**Issue by techie-jai** [jupyter/docker-stacks#1147]
Hi Team

Great work on the image.

I tried the "docker run -p 8888:8888 jupyter/scipy-notebook:17aba6048f44" and it starts the Jupyter perfectly. However, I want to know if there is a way using which I can upload my custom file to this image, so that when I pull this image and build a custom one. That custom image when starts, it has my "example.pynb" and "train.csv" already in the folder of jupyter.

Rightnow when the image starts, there are no files inside and every time I have to upload again the same 2 files with my code.

Any suggestions what changes should be done.

**Comment by parente** [comment]
Hi @techie-jai. I left a comment in your other related thread just now: https://github.com/jupyter/docker-stacks/issues/1124#issuecomment-674529076

Please let us know if mybinder.org or repo2docker help with your use case.

**Comment by romainx** [comment]
I'm closing this issue because we have already posted an answer on that.
Feel free to reopen it if it's not the case.
