### ISSUE TITLE
Create docker image of Base-Notebook with python 2.7

### ISSUE THREAD

**Issue by rhijit789** [jupyter/docker-stacks#1157]
Hi,
I want to create a new image using base-notebook docker-stacks with python 2.7. I tried doing that but I am facing some issues.

Step 27/36 : RUN conda install --quiet --yes     'notebook=6.1.3'     'jupyterhub=1.1.0'     'jupyterlab=2.2.5' &&     conda clean --all -f -y &&     npm cache clean --force &&     jupyter notebook --generate-config &&     rm -rf $CONDA_DIR/share/jupyter/lab/staging &&     rm -rf /home/$NB_USER/.cache/yarn &&     fix-permissions $CONDA_DIR &&     fix-permissions /home/$NB_USER
 ---> Running in 3082eb1336bf
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... /bin/bash: line 1:     6 Killed                  conda install --quiet --yes 'notebook=6.1.3' 'jupyterhub=1.1.0' 'jupyterlab=2.2.5'
The command '/bin/bash -o pipefail -c conda install --quiet --yes     'notebook=6.1.3'     'jupyterhub=1.1.0'     'jupyterlab=2.2.5' &&     conda clean --all -f -y &&     npm cache clean --force &&     jupyter notebook --generate-config &&     rm -rf $CONDA_DIR/share/jupyter/lab/staging &&     rm -rf /home/$NB_USER/.cache/yarn &&     fix-permissions $CONDA_DIR &&     fix-permissions /home/$NB_USER' returned a non-zero code: 137

I think this is happening because of unsupported versions of notebook or jupyterhub.
So can anyone please help me with correct versions or can tell me if anything else needs to be done.

**Comment by Bidek56** [comment]
Since Python 2.7 is no longer supported you will run into a lot of issues trying to do this.
I would suggest extending one of the old images that still have Python 2.7 if there are any at: https://hub.docker.com/r/jupyter/base-notebook/tags

**Comment by romainx** [comment]
@rhijit789 are you good with the @Bidek56 answer? 
He's right, it will be complicated for us to spend time on an old Python version

Thanks in advance for your feedback.

**Comment by romainx** [comment]
Hello,

I'm closing this issue since I think we will not go further on this topic.
If you are not happy with our answer, feel free to reopen it 😕.

Best.

**Comment by vemonet** [comment]
Hi @romainx and @Bidek56 could you point to an actual image with python2.7? There is no corresponding image when searching through the tags provided.

Another option would be to just use conda to create an environment with python 2.7

But it does not work due to `conda activate myenv2.7` not working in Docker.
