### ISSUE TITLE
ImportError: cannot import name 'accumulators'

### ISSUE THREAD

**Issue by peterklipfel** [jupyter/docker-stacks#116]
To reproduce

    docker pull jupyter/pyspark-notebook
    docker run -d -p 8888:8888 jupyter/pyspark-notebook

go to localhost:8888

run the following in the first cell

    import os
    # make sure pyspark tells workers to use python3 not 2 if both are installed
    os.environ['PYSPARK_PYTHON'] = '/usr/bin/python3'

    import pyspark
    conf = pyspark.SparkConf()

And you should see the following error

    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    <ipython-input-2-82ad3fe4c1b6> in <module>()
          3 os.environ['PYSPARK_PYTHON'] = '/usr/bin/python3'
          4 
    ----> 5 import pyspark
          6 conf = pyspark.SparkConf()
          7 

    /usr/local/spark/python/pyspark/__init__.py in <module>()
         39 
         40 from pyspark.conf import SparkConf
    ---> 41 from pyspark.context import SparkContext
         42 from pyspark.rdd import RDD
         43 from pyspark.files import SparkFiles

    /usr/local/spark/python/pyspark/context.py in <module>()
         26 from tempfile import NamedTemporaryFile
         27 
    ---> 28 from pyspark import accumulators
         29 from pyspark.accumulators import Accumulator
         30 from pyspark.broadcast import Broadcast

    ImportError: cannot import name 'accumulators'

_Note_: I have a slight complication in my setup. I don't imagine that it would matter, but if you can't reproduce, maybe this could be a difference? The docker container is running inside a vagrant box. The vagrant box is running dnsmasq. I am connecting to the notebook at mydomain.dev:8888 from osx which is also running dnsmasq.

**Comment by peterklipfel** [comment]
Debugging info:

    print(os.environ['PYTHONPATH'])

yields

    /usr/local/spark/python:/usr/local/spark/python/lib/py4j-0.8.2.1-src.zip

so it looks like py4j should be found.

**Comment by parente** [comment]
Assuming you're just using Spark locally ...

`os.environ['PYSPARK_PYTHON'] = '/usr/bin/python3'`

You shouldn't need to set this. If you're in a python3 kernel, it should be all set to the use the python binary and libs from the conda python3 environment already installed in the image.

**Comment by parente** [comment]
Here's a complete example for Python 3 that should work taken from the README:

```
import pyspark
sc = pyspark.SparkContext('local[*]')

# do something to prove it works
rdd = sc.parallelize(range(1000))
rdd.takeSample(False, 5)
```

https://github.com/jupyter/docker-stacks/tree/master/pyspark-notebook#using-spark-local-mode

**Comment by peterklipfel** [comment]
I reran the docker container to make sure everything was fresh. Created a new python 3 notebook, and pasted the following into it:

    import pyspark
    sc = pyspark.SparkContext('local[*]')

    # do something to prove it works
    rdd = sc.parallelize(range(1000))
    rdd.takeSample(False, 5)

and this was the output

    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    <ipython-input-1-8fc5272dde98> in <module>()
    ----> 1 import pyspark
          2 sc = pyspark.SparkContext('local[*]')
          3 
          4 # do something to prove it works
          5 rdd = sc.parallelize(range(1000))

    /usr/local/spark/python/pyspark/__init__.py in <module>()
         39 
         40 from pyspark.conf import SparkConf
    ---> 41 from pyspark.context import SparkContext
         42 from pyspark.rdd import RDD
         43 from pyspark.files import SparkFiles

    /usr/local/spark/python/pyspark/context.py in <module>()
         31 from pyspark.conf import SparkConf
         32 from pyspark.files import SparkFiles
    ---> 33 from pyspark.java_gateway import launch_gateway
         34 from pyspark.serializers import PickleSerializer, BatchedSerializer, UTF8Deserializer, \
         35     PairDeserializer, AutoBatchedSerializer, NoOpSerializer

    /usr/local/spark/python/pyspark/java_gateway.py in <module>()
         29     xrange = range
         30 
    ---> 31 from py4j.java_gateway import java_import, JavaGateway, GatewayClient
         32 from py4j.java_collections import ListConverter
         33 

    ImportError: No module named 'py4j'

If I run it again, I get the `accumulators` stack trace reported above

**Comment by peterklipfel** [comment]
When I go into the docker container and run `pip install py4j` (as jovyan), and then create a new notebook, the example that you provide works

**Comment by parente** [comment]
Thanks for checking. The latest build must have regressed. I'll give it a look soon.

**Comment by parente** [comment]
py4j in the spark package changed versions. Fix is:

`ENV PYTHONPATH $SPARK_HOME/python:$SPARK_HOME/python/lib/py4j-0.8.2.1-src.zip`

changes to:

`ENV PYTHONPATH $SPARK_HOME/python:$SPARK_HOME/python/lib/py4j-0.9-src.zip`

in the docker build.

I must have glossed over testing Python on the last build. Will push soon after testing.

**Comment by parente** [comment]
Pushed to Docker Hub with tag `8021f892543c`.

Thanks again @peterklipfel.

**Comment by peterklipfel** [comment]
Thanks for the quick resolution!
