### ISSUE TITLE
Sync notebooks using docker-sync

### ISSUE THREAD

**Issue by gvojtko** [jupyter/docker-stacks#1164]
Hi, how I can syncing notebooks with my local storage using docker-sync? I need to have the files saved after the container is stoped.

**Comment by Bidek56** [comment]
I think you want to mount a volume into your Docker container, that's the typical solution.

**Comment by romainx** [comment]
Thank you @Bidek56.
@gvojtko I think @Bidek56 is right, you can simply use a docker bind mount as described in [the documentation](https://jupyter-docker-stacks.readthedocs.io/en/latest/).

In this example adapted from the documentation 

> The command mounts the current working directory on the host as `/home/jovyan/work` in the container [...]
> Docker destroys the container after notebook server exit, but any files written to `~/work` in the container remain intact on the host.

```
$ docker run --rm -p 8888:8888  -v "$PWD":/home/jovyan/work jupyter/minimal-notebook
```

Could you please confirm if it answers to your question?
Many thanks.

**Comment by romainx** [comment]
I'm closing this issue because I think we've answered your question.
Feel free to reopen it if it's not the case.

Best
