### ISSUE TITLE
Proposal: Reduce the number of editors in the stacks

### ISSUE THREAD

**Issue by romainx** [jupyter/docker-stacks#1174]
Hello,

We have plenty of editors installed in the stacks + Jupyter editors.

```bash
$ update-alternatives --config editor

# There are 4 choices for the alternative editor (providing /usr/bin/editor).
# 
#   Selection    Path               Priority   Status
# ------------------------------------------------------------
# * 0            /usr/bin/jed        42        auto mode
#   1            /bin/nano-tiny      0         manual mode
#   2            /usr/bin/emacs      0         manual mode
#   3            /usr/bin/jed        42        manual mode
#   4            /usr/bin/vim.tiny   15        manual mode
```

Some of them (in fact emacs) have a significative impact on the images size.

```bash
$ packages="vim-common vim-tiny jed jed-common emacs-nox emacs-bin-common emacs-common emacsen-common nano-tiny"
$ apt-cache --no-all-versions show $packages | awk '$1 == "Package:" {p = $2} $1 == "Installed-Size:" {printf("%s: %s\n", p, $2, is)}'

# vim-common: 375
# vim-tiny: 1530
# ---
# vim-total: ~ 2 MB

# jed: 361
# jed-common: 1806
# ---
# jed-total: ~ 2 MB
 
# emacs-nox: 41291
# emacs-bin-common: 470
# emacs-common: 66816
# emacsen-common: 62
# ---
# emacs-total: ~ 100 MB
 
# nano-tiny: 177
# ---
# nano-total: 177 KB
```

# Proposal

1. Remove jed. Rationale: I don't think it is widely used 👴--but maybe I'm wrong. The last version has been released more than 10 years ago (2009)
2. Remove emacs (I don't want to create a psychodrama 😨). Rationale: It's size 🏋️. The stack is dedicated to Jupyter editors, other editors should be here has minimal helpers--but maybe I'm wrong.

Estimated size reduction: **1.63GB  -> 1.51GB** on `minimal-notebook` and all downstream images.

What is your opinion, please let me know?

Best

**Comment by Bidek56** [comment]
Emacs and Jed have to go, my grandmother stopped using those years ago. :)

**Comment by mathematicalmichael** [comment]
100% agree
