### ISSUE TITLE
Add datascience missing to datascience-notebook

### ISSUE THREAD

**Issue by EnziinSystem** [jupyter/docker-stacks#1175]
Hello,

Please add 'datascience' package to 'datascience-notebook'

```
RUN pip install datascience
```

For example, the block code below warning 'datascience' package missing.

```

from datascience import *
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

from urllib.request import urlopen 
import re
def read_url(url): 
    return re.sub('\\s+', ' ', urlopen(url).read().decode())
```

Thanks.

**Comment by romainx** [comment]
Hello,

Thanks for the suggestion. I do not know this [datascience](https://github.com/data-8/datascience) package and I'm not sure that is widely used. For example is not included in the [Anaconda distribution](https://docs.anaconda.com/anaconda/packages/py3.8_linux-64/) which gather a crafted list of packages for data science.
We try to keep the images small and maintainable so we try to select new packages with care to avoid bloating them.

Maybe I'm wrong. Let me know if you have additional information.
Best.

**Comment by romainx** [comment]
Hello @EnziinSystem,

I've no update from your side, I'm closing this issue.
Feel free to update this issue if you have additional information leading us to change our mind.

Best.
