### ISSUE TITLE
UI Distorted for jupyter notebook when run inside k8 pod

### ISSUE THREAD

**Issue by bainadeashish** [jupyter/docker-stacks#1177]
Hi Team,

I am running image custom docker image of jupyter inside kubernetes pod

below is my docker file which is very straight forward:
FROM ubuntu:latest
RUN apt-get update && apt-get -y update
RUN apt-get install -y build-essential python3.6 python3-pip python3-dev
RUN pip3 -q install pip --upgrade
RUN pip3 install jupyter
RUN mkdir src
WORKDIR src/
COPY . .
ENV TINI_VERSION v0.6.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /usr/bin/tini
RUN chmod +x /usr/bin/tini
ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["jupyter", "notebook", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--allow-root", "--NotebookApp.token=''", `"--NotebookApp.password=''"]`

I am able to get notebook running in container without issue  & can see correct API response in logs for / route , However on UI i am seeing distorted view of notebook.
& when dig down deeper i can see error in browser console like below:

The resource from “https://my-server-name/static/components/jquery-ui/themes/smoothness/jquery-ui.min.css?v=3c2a865c832a1322285c55c6ed99abb2” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).

The resource from “https://my-server-name/static/components/jquery-typeahead/dist/jquery.typeahead.min.css?v=9df10041c3e07da766e7c48dd4c35e4a” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).

Please find attached distorted image 
![Screenshot_2020-10-07 Home Page - Select or create a notebook](https://user-images.githubusercontent.com/20454523/95328191-d4b15080-08c2-11eb-9d91-fd5a8993b438.png)

On local it works like a charm using same dockerfile image.

**Comment by Bidek56** [comment]
You need to check your browser networking tab and see which resources are getting 404, then:
1. Fix your ingress to serve those resources
2. Fix your `~/.jupyter/jupyter_notebook_config.py` to serve the html resources correctly

**Comment by Bidek56** [comment]
I think this question belongs in the [Jupyter Forum](https://discourse.jupyter.org/) not here.

**Comment by romainx** [comment]
Hello @bainadeashish,

You are building a Jupyter image from scratch.
I'm sorry but I'm closing this issue because is not related to the images maintained in this repo.

Best.
