### ISSUE TITLE
always  read-only mapping to host folder

### ISSUE THREAD

**Issue by awb99** [jupyter/docker-stacks#118]
When using the:rw switch when mount a host folder into the dockers image, the access should be read and write:

`-v /some/host/folder/for/work:/home/jovyan/work:rw `

But the access still is read only.

I believe this is a bug

**Comment by awb99** [comment]
my mistake..

**Comment by parente** [comment]
You got it. The default uid=1000 and group=100. You can configure the former when you start the container if you start it as root. (The README describes how.) Or you can grant user 1000 and/or group 100 read/write in the host mount.
