### ISSUE TITLE
Volume: Permission denied

### ISSUE THREAD

**Issue by ogierpaul** [jupyter/docker-stacks#1187]
## What docker image you are using?
jupyter/minimal-notebook

## What complete docker command do you run to launch the container (omitting sensitive values)?
````
# Creating a volume with docker create -- volume
docker volume create --name stagingarea
# Start a jupyter minimal notebook container and map the volume (stagingarea) to a container directory (/data/stagingarea)
docker run -d \
  -v stagingarea:/home/jovyan/stagingarea\
  -p 8888:8888 \
  jupyter/minimal-notebook
````

## What steps do you take once the container is running to reproduce the issue?

1. Visit http://localhost:8888 & Login with token
2. Go to /home/jovyan/stagingarea
3. Attempt to create a simple notebook, or text file (Greetings.txt) in the volume

## What do you expect to happen?
- I want to: Create a simple text file and save it in the volume
- In order to: share this text file with other containers

## What actually happens?
- I have this error message: https://cloud.githubusercontent.com/assets/1175888/12765291/4ce76dfe-c9fe-11e5-86e0-b952c8a65777.png
- Similar to this issue: https://github.com/jupyter/docker-stacks/issues/114

## Why I want to do that
- I want to create a staging area so a python program  in jupyter can download data from one source, write it to a docker volume, and another service (like postgres,..) can read data from that volume and ingest it.

### Connecting as root
- It works when I run the jupyter docker image. as root -e GRANT_SUDO=yes \
````
# Creating a volume with docker create -- volume
docker volume create --name stagingarea
# Start a jupyter minimal notebook container and map the volume (stagingarea) to a container directory (/data/stagingarea)
docker run -d \
  -v stagingarea:/home/jovyan/stagingarea\
  -p 8888:8888 \
  -e JUPYTER_TOKEN=letmein \
  -e GRANT_SUDO=yes \
  --user root \
  jupyter/minimal-notebook
````

### Using a bind mount
````
docker run -d \
  -v -v /Users/paulogier/87-docker_parent/usingjupyterwithdocker/Step7_Volumes/stagingarea:/home/jovyan/stagingarea )
  -p 8888:8888 \
  -e JUPYTER_TOKEN=letmein \
  jupyter/minimal-notebook

````

**Comment by romainx** [comment]
Hello @ogierpaul,

You can use one of the following option or combination of options to achieve what you want to do and change the ownership of your mount that is by default owned by `root`.
They are described in the [Common Features](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html) chapter of the documentation.

- `CHOWN_EXTRA` option to

> Instructs the startup script to change the owner and group of each comma-separated container directory to the current value of `$NB_UID` and `$NB_GID`. The change is not applied recursively by default.

```bash
docker run -it \        
  -v stagingarea:/home/jovyan/stagingarea \
  --user root \
  -e CHOWN_EXTRA="/home/jovyan/stagingarea" \
  -p 8888:8888 \
  jupyter/minimal-notebook ls -ld /home/jovyan/stagingarea

# ...
# Changing ownership of /home/jovyan/stagingarea to 1000:100 with options ''
# ...

ls -ld ~/stagingarea
# drwxr-xr-x 2 jovyan users 4096 Nov 15 13:40 /home/jovyan/stagingarea
```

- `CHOWN_HOME` with `CHOWN_HOME_OPTS` recursive since the volume is mounted on the home directory.

>  Instructs the startup script to change the `$NB_USER` home directory owner and group to the current value of `$NB_UID` and `$NB_GID`.
> You can change modify the `chown` behavior by setting `CHOWN_HOME_OPTS` (e.g., `-e CHOWN_HOME_OPTS='-R'`).

```bash
docker run -it \
  -v stagingarea:/home/jovyan/stagingarea \
  --user root \
  -e CHOWN_HOME=yes \
  -e CHOWN_HOME_OPTS='-R' \
  -p 8888:8888 \
  jupyter/minimal-notebook

# ...
# Changing ownership of /home/jovyan to 1000:100 with options '-R'
# ...

ls -ld ~/stagingarea
# drwxr-xr-x 2 jovyan users 4096 Nov 15 14:08 /home/jovyan/stagingarea
```

## Notes

- Both solutions require to run the container with `--user root`.
- The [Common Features](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html) chapter of the documentation also describes other options that might be interesting for your use case.

Hope it will help you.

**Comment by ogierpaul** [comment]
Thank you Romain. You can close the issue.
