### ISSUE TITLE
Delete build requirements in Dockerfiles

### ISSUE THREAD

**Issue by DavidSpek** [jupyter/docker-stacks#1199]
As requested [here](https://github.com/jupyter/docker-stacks/pull/1196/files/feee7870b662e2836036cd31fb84330932937d51#r542640611) as a comment to an open PR of mine, I am opening an issue regarding deleting build requirements from the docker images after they are not needed anymore. The line in question is:
```
apt-get purge --autoremove -y curl \
```
Which is installed to add an apt key in the same `RUN` command and deleted after its use.

**Comment by mathbunnyru** [comment]
The purpose of this change is to make the layers and the overall image size smaller.

**Comment by romainx** [comment]
Hello @mathbunnyru & @DavidSpek,

Thanks for this suggestion. However I'm wondering where to apply it.

From the [man page][1]

> `purge` is identical to `remove` except that packages are removed and purged (any configuration files are deleted too).

So from my understanding, it can be used in conjonction with `apt-get remove`, but we are not removing any packages in the `Dockerfiles`.

> `autoremove` is used to remove packages that were automatically installed to satisfy dependencies for other packages and are now no longer needed.

So `autoremove` can be used to clean unused dependencies. But I tried on the last image in the lineage `all-spark-notebook` and it seems to find nothing to remove.

```bash
apt-get autoremove
# Reading package lists... Done
# Building dependency tree       
# Reading state information... Done
# 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

Did I miss something? Do you have some use cases in mind?

Many thanks.

[1]: https://manpages.ubuntu.com/manpages/bionic/man8/apt-get.8.html

**Comment by romainx** [comment]
Hello @mathbunnyru,

Ok got it. However I'm not sure in our case it's worth doing it for `wget` specially if we consider that it is used in some downstream images and that it can be useful in other circumstances. I would not be 100% for removing it. So I'm closing this issue since we have no defined action to do.

Best.
