### ISSUE TITLE
JupyterLab 3.0

### ISSUE THREAD

**Issue by romainx** [jupyter/docker-stacks#1207]
Hello,

JupyterLab `3.0.0` introduces major changes that could impact:

- the compatibility between Jupyter Notebook and JupyterLab,
- the way extensions are managed.

# Terminology

Very good status taken from https://github.com/nbgallery/docker-images/issues/17

> Some terminology, to avoid confusion:
> 
> * Jupyter back-end options:
>   
>   * [notebook](https://github.com/jupyter/notebook) server, which supports "serverextensions" (no space) that I'll refer to as old-server extensions
>   * [jupyter_server](https://github.com/jupyter-server/jupyter_server), which supports "server extensions" (space) that I'll refer to as new-server extensions
> * Jupyter front-end options:
>   
>   * [notebook](https://github.com/jupyter/notebook) - the traditional UI, often called "classic" -- but since I'm about to mention two other "classic" projects, I'll call it "Notebook UI" for clarity
>   * [lab](https://github.com/jupyterlab/jupyterlab) - the next-gen UI
>   * [jupyterlab-classic](https://github.com/jtpio/jupyterlab-classic) - the look and feel of the Notebook UI but built with Lab components
> * Compatibility layers:
>   
>   * [nbclassic](https://github.com/jupyterlab/nbclassic) - provides the Notebook UI as a new-server extension and also translates old-server extensions into new-server extensions.  (To be clear, this isn't just something that looks like the Notebook UI, it is literally the same code, running through the compatibility layer.)
> 

# Impact

## Jupyter Notebook and JupyterLab

[Jupyter Notebook][1] is deprecated and it is advised to transition to JupyterLab.

> Please note that this repository is currently maintained by a skeleton crew of maintainers from the Jupyter community. We encourage users to transition to JupyterLab, where more immediate support can occur.

See dedicated issue #1217.

## Extensions

According to the [JupyterLab changelog][2]

> Extensions can be installed without building JupyterLab with NodeJS
> In JupyterLab 3.0, a new recommended way of distributing and installing extensions as Python pip or conda packages is available. Installing such extensions does not require rebuilding JupyterLab and does not require having NodeJS installed. The previous way of distributing extensions as npm packages requiring rebuilding JupyterLab is still available as well. See the documentation for more details.

We should manage extension differently in `scipy-notebook`.

https://github.com/jupyter/docker-stacks/blob/d113a601dbb83dca72f0bc73c7e5f223426cc112/scipy-notebook/Dockerfile#L50-L59

[This issue][5] summarizes in a table the extensions currently compliant with the new version and here is the list of extensions used in `scipy-notebook`.

- [x] `ipywidgets`: https://github.com/jupyter-widgets/ipywidgets/pull/2973 `7.6`
- [x] `jupyter-matplotlib`: https://github.com/matplotlib/ipympl/pull/272 `0.6.1`
- [ ] `bokeh`: https://github.com/bokeh/bokeh/issues/10569

## JupyterHub

There is also something to check with JupyterHub since the stacks permit to launch `jupyterhub-singleuser`. It think it's well summarized in https://github.com/jupyterhub/jupyterhub/issues/2984 and this [comment](https://github.com/jupyterhub/jupyterhub/issues/2984#issuecomment-658177068).

Best

[1]: https://github.com/jupyter/notebook
[2]: https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html#v3-0
[3]: https://github.com/jupyter-server/jupyter_server
[4]: https://github.com/jupyterlab/nbclassic
[5]: https://github.com/jupyterlab/jupyterlab/issues/9461

**Comment by romainx** [comment]
@parente I have integrated your comments in the issue description. 
My first idea is to make make the switch to JupyterLab in several steps, what is your opinion?

## Switch to JupyterLab by default

With JupyterLab `2.2.x` and notebook `6.x`. 

- Switch to JupyterLab by default in the start script and so for the test.
- Update the documentation accordingly.
- Deprecate in the documentation and in the start script the usage of notebook.

## Upgrade JupyterLab

With JupyterLab `3.x` and notebook `6.x`. 

- Maintain compatibility with both backends.
- Raise the intensity of the deprecation warning (different message, enforce the usage of a specific flag to enable it in compatibility mode, etc.)

## Remove notebook support

With JupyterLab `3.x` only and `nbclassic` (to keep the user experience).

- Remove notebook support
- Provide `nbclassic`
- Switch extension installation from npm to python

**Comment by jeffyjefflabs** [comment]
Clarification question... I was following the discussion in #1209, and the decision to keep `notebook` as the default entrypoint until April seems reasonable.  However, based on the plan described here, does that mean you're planning to keep `jupyterlab` pinned to version 2 until then as well?  Lab 3 does still run as a serverextension on the old notebook back-end, even though it's not "preferred" -- so you *could* update to Lab 3 while still keeping `notebook` as the default until April.  You're maintaining a much deeper stack than we are though, so maybe that would cause other issues that we haven't seen.  (And I suppose there's a risk of Lab doing something to break that backward compatibility, although that seems unlikely in this timeframe.)

**Comment by romainx** [comment]
Hello @jeffyjefflabs,

> However, based on the plan described here, does that mean you're planning to keep `jupyterlab` pinned to version 2 until then as well? 

No we were just waiting a bit because some of the extension we are using in `scipy-notebook` were not working with JupyterLab `3.0`. At the time of writing only bokeh seems to not be supported. So I have planned to draft a PR for the upgrade this weekend because it seems reasonable now even without 1 of the 3 extensions installed.

> Lab 3 does still run as a serverextension on the old notebook back-end, even though it's not "preferred" -- so you could update to Lab 3 while still keeping `notebook` as the default until April.

Yes you're right and we know it's working. I confirm that it's exactly what we plan to do.

I hope is clearer now. Thanks for sharing this information with us.
Best

**Comment by jeffyjefflabs** [comment]
Excellent!  Thanks for the update.
