### ISSUE TITLE
How to build pyspark image with specific version of spark and python?

### ISSUE THREAD

**Issue by dporp** [jupyter/docker-stacks#1211]
Hi! 
I can not find answer either documentation and Github issues.
I have one pretty simple question: How to build pyspark-notebook with specific version of spark and python.
I have used this 
```
docker build --rm --force-rm \
    -t jupyter/pyspark-notebook:spark-2.4.7 ./pyspark-notebook \
    --build-arg spark_version=2.4.7 \
    --build-arg hadoop_version=2.7 \
    --build-arg spark_checksum=0F5455672045F6110B030CE343C049855B7BA86C0ECB5E39A075FF9D093C7F648DA55DED12E72FFE65D84C32DCD5418A6D764F2D6295A3F894A4286CC80EF478 \
    --build-arg openjdk_version=8
```
to set up a version of spark, but how to set up a version of python?
I can do it in base-notebook using arg `PYTHON_VERSION `  (from this https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile#L96).
But in this approach I have to rebuild step-by-step all notebooks: base-notebook -> minimal-notebook -> scipy-notebook -> pyspark-notebook (and change default parent image to my custom with correct python version (using build agr `BASE_CONTAINER `)). Is there a more simpler way?

In the end,  I need to build spark=2.4.x and python=3.7.x.

**Comment by Bidek56** [comment]
I would probably take one of the existing images from [Docker Hub](https://hub.docker.com/r/jupyter/pyspark-notebook) and extend it.

`FROM jupyter/pyspark-notebook
....`

**Comment by dporp** [comment]
@Bidek56 thanks.
Maybe you can give me advice on how to find `pyspark-notebook` image that uses python=3.7 in the Dockerhub?

**Comment by Bidek56** [comment]
I would start with `docker pull jupyter/pyspark-notebook:spark-2` but this image maybe using Python 3.8 already.
If you need 3.7, pulling an image from 2 years ago should do. It's easy enough to pull and do: `docker exec -it` to check the version.
Another option is to grab an older version of [Dockerfile](https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile) and start with that.
I believe Python versions come from Conda, so you need to get that correct first.

**Comment by dporp** [comment]
@Bidek56 thanks, I will do it.

**Comment by romainx** [comment]
Hello @dporp and thanks @Bidek56,

Just to add a link to a recent issue #1200 and particularly to this [comment](https://github.com/jupyter/docker-stacks/issues/1200#issuecomment-745258117) on pretty much the same topic and the same conclusion if it could help.

Best
