### ISSUE TITLE
Automatically send build times and images size for all PRs

### ISSUE THREAD

**Issue by mathbunnyru** [jupyter/docker-stacks#1214]
The idea is to be sure, that the image is not building slower than it was and the image size is acceptable.

The idea came from https://github.com/jupyter/docker-stacks/pull/1213

**Comment by romainx** [comment]
I'm waiting for your implementation, in the meantime I will do it manually 😭

**Comment by mathbunnyru** [comment]
> I'm waiting for your implementation, in the meantime I will do it manually 😭

I'll implement it for sure 👍
I think there should be an easy GitHub action to do it.

It'll take some time, because I don't have much free time at the moment, but I will try my best :)

**Comment by romainx** [comment]
@mathbunnyru obviously it's not urgent at all. But it could be interesting. For information @parente shared in #693 a notebook performing this kind of comparison https://nbviewer.jupyter.org/gist/parente/316d5c242aeb484484c8 from various tags / date directly from DockerHub.

<img width="411" alt="Jupyter_Notebook_Viewer" src="https://user-images.githubusercontent.com/7131913/104763046-a23aad80-5765-11eb-8c37-3f7fdf2facfd.png">

**Comment by mathbunnyru** [comment]
Thanks for the link!

We can't do this for the image in the PR, because it is not uploaded to dockerhub, but we can fetch the numbers for the current master and do the comparison.

**Comment by srggrs** [comment]
Hi,

not sure if this is related to this issue here, but I'm struggling to understand which image to pull with the package requirements I want. I thought the image tags were related to the PRs (e.g. [this commit](https://github.com/jupyter/docker-stacks/commit/35d3fff7709912782e97325e907fbef6d3c565b5#diff-e67b5386623ecce90c1b575564210636b1139db34546ace04be10e9c130bb3ca) would be push to docker hub with tag `35d3fff` or something like that). I'm in this situation as I want to pull down an image with Jupyter < 3 so that some extension works (e.g. bokeh).

I know that potentially I could build my own image locally using the [recipe in the docs](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html#using-pip-install-or-conda-install-in-a-child-docker-image) and intalling old version of Jupyter but I thought there was more a neat way to pull down the image I want.

Thanks.
S

**Comment by mathbunnyru** [comment]
Hi, no, I would say that this is unrelated.

But I will be glad to help you.
You probably want the latest version with `JupyterLab < 3` (not `Jupyter`).

So, all you need to do is to find the commit before lab update and use this commit's hash prefix as the tag.
Note, that not all commits are tagged, because they might be docs update and do not change the image.

You need approximately this commit (I might be not accurate, because not all commits are built):
https://github.com/jupyter/docker-stacks/commit/7e07b801d92b3db6d90010f87b06ec1ab994eef0

And you can search for this commit on dockerhub.
https://hub.docker.com/r/jupyter/scipy-notebook/tags?page=1&ordering=last_updated&name=7e07

Note, that tag starts with commit's hash, as I said.
And you will find this image: https://hub.docker.com/layers/jupyter/scipy-notebook/7e07b801d92b/images/sha256-a92c7ecfe5331038a513d0a71df0666665d003e04c4ea3ef41cf89ceb89f1f21?context=explore

And, if you want to base your image on something other than scipy-notebook, you can do the same search as I showed you (but on the page of the relevant image).

Hope this helps.

Please, if you want to continue this discussion, create a new issue.

**Comment by mathbunnyru** [comment]
I found Github Action, which will greatly simplify this task.

https://github.com/marketplace/actions/sticky-pull-request-comment

> Create a comment on a pull request, if it exists update that comment.

I think it should be quite simple to check the sizes of the latest master build images, the current PR and so on.
I will also think about adding a build time, though it might not be that good (because of network/spikes and so on).

**Comment by mathbunnyru** [comment]
Also, the build time is written in the Github Action itself, so it might not make sense to duplicate.

> Successful in 27m

**Comment by mathbunnyru** [comment]
Now, we upload our images as GitHub artifacts, so it's relatively easy to see the image size.
It's also not difficult to see the time it took to build the image.
And after that, we don't add new stuff to the images, so I don't think we really need this feature now.
