### ISSUE TITLE
Jupyter Notebook deprecation

### ISSUE THREAD

**Issue by romainx** [jupyter/docker-stacks#1217]
[Jupyter Notebook][1] **is deprecated and it is advised to transition to JupyterLab**.

> Please note that this repository is currently maintained by a skeleton crew of maintainers from the Jupyter community. We encourage users to transition to JupyterLab, where more immediate support can occur.

The recent issue #1205 has shown that keeping both may lead to issues.

The newly preferred backend for JupyterLab 3.0 is [`jupyter-server`][3] instead of [`notebook`][1]: https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html#jupyter-server. 

## Roadmap

1. **Deprecation**: Maintain compatibility with both backends and deprecate Jupyter Notebook. Jupyter Notebook remains the default but a message indicates that it is advised to transition to JupyterLab.
2. **Switch the default to JupyterLab**: Switch to JupyterLab by default. It is still possible to start Jupyter Notebook by positioning a new `JUPYTER_ENABLE_NB` variable. 
3. **Drop Jupyter Notebook**: Move to [`jupyter_server`][3] alone and point people to [`nbclassic`][4] for a classic-like experience. It provides the Notebook UI as a new-server extension and also translates old-server extensions into new-server extensions.  (To be clear, this isn't just something that looks like the Notebook UI, it is literally the same code, running through the compatibility layer.)

Note: Another option could be [retrolab][5] - the look and feel of the Notebook UI but built with Lab components.

## Deprecation

- [x] Done -> PR #1209

Changes
- **With no option (no specific environment variable)**: Jupyter Notebook is launched (no change). However a warning / deprecation message is printed pointing to [the dedicated section][6] in the README.
- **With `JUPYTER_ENABLE_LAB`**: Jupyter Lab is launched (no change).
- Notice added in [README][6]

## Switch the default to JupyterLab

- [x] Done -> PR #1575

Changes
- **With no option (no specific environment variable)**: JupyterLab is launched.
- **With `JUPYTER_ENABLE_LAB`**: JupyterLab is launched. A warning message informs that this option is no more required.
- **With `DOCKER_STACKS_JUPYTER_CMD=notebook`**: Jupyter Notebook is launched. This variable also allows to run other `jupyter` commands
- Documentation is updated to document the new default and the new start option

## Drop Jupyter Notebook support

- [x] Not planned

Changes
- Jupyter Notebook support dropped (along with corresponding environment variables).
- A solution providing a _classic-like_ UI built atop of JupyterLab will be proposed. The solution is not chosen at this time.

[1]: https://github.com/jupyter/notebook
[2]: https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html#v3-0
[3]: https://github.com/jupyter-server/jupyter_server
[4]: https://github.com/jupyterlab/nbclassic
[5]: https://github.com/jtpio/jupyterlab-classic
[6]: https://github.com/jupyter/docker-stacks#jupyter-notebook-deprecation-notice

**Comment by parente** [comment]
Noting that a convo opened in 2018 about making JLab the default in the Zero to JupyterHub tutorial has picked up steam again: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/776#issuecomment-703895108 and includes a community poll.

**Comment by willingc** [comment]
Let's look again at the date when these stacks will move to JupyterLab as the default front-end. April 2021 seems too aggressive a move and have the time to adequately inform those that expect classic.

**Comment by romainx** [comment]
Hello @willingc, thanks for the information. We can move the date, no rush on our side, it's just to reflect the message given by Jupyter Notebook maintainers. Could you please tell us what is the new target?

**Comment by romainx** [comment]
@parente & @willingc April is coming what is your advice? On my side, I have no strong opinion since I do not know the plans regarding Jupyter Notebook end of life. If we want to avoid unnecessary issues — like me — we could postpone the switch to a later date, for example June or October? Please tell me and I will take care of performing the change.

**Comment by mathbunnyru** [comment]
I would wait for Jupyter Notebook's decision regarding EOL.
I'm also not sure that all lab extensions are already updated to be compatible with jupyterlab 3.0.
And we have to give users more time to adjust their systems for jupyterlab.

**Comment by parente** [comment]
Since there's no votes here for switching in April and concern about it being too early, let's set the date further out. When Notebook no longer receives security fixes, when most other Jupyter projects make Lab the default (e.g., Binder, [Z2JH](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/776)), when there's a stable single-document interface for Lab akin to Classic, ... all seem like reasonable options to me.

**Comment by romainx** [comment]
@parente @mathbunnyru thank you for your very wise suggestions — one more time . I will take care to remove the date my saying something like "at some point", I think it's a better choice than setting a random date.

**Comment by krassowski** [comment]
I wonder if https://github.com/jupyterlab/retrolab might ease the transition.

**Comment by zeehio** [comment]
Following this issue, I changed the default from the classic jupyter notebooks view to the jupyterlab and some users started complaining about notebook rendering performance, and browser hanging.

Apparently related to:

-  https://github.com/jupyterlab/jupyterlab/issues/1639

Just for you to consider that performance issue as a potential blocker for the jupyter notebook deprecation

**Comment by krassowski** [comment]
There was a lot of work on the performance, some released in 3.1 and 3.2, more coming to 4.0.

Which version of JupyterLab have you deployed? Was the slowdown specific to Firefox? Is it attributable to more notebooks opened, or is it also visible in RetroLab? We really need more real-world data to be able to address it.

**Comment by mathbunnyru** [comment]
@romainx I think we can and probably should proceed with this issue and change the default.

Rationale:
- you're back :)
- it's been a long time - enough to switch to jupyterlab and update the extensions
- JupyterHub 2.0 switched to lab by default: (https://jupyterhub.readthedocs.io/en/stable/changelog.html#id3)
- repo2docker (and mybinder) use lab by default: https://mybinder.readthedocs.io/en/latest/howto/user_interface.html
- z2jh uses image for singleuser.cmd by default, so the image decides what to launch by default: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2449

**Comment by krassowski** [comment]
I think that it is important to mention [Notebook v7 JEP](https://jupyter.org/enhancement-proposals/79-notebook-v7/notebook-v7.html) ([discussion](https://github.com/jupyter/enhancement-proposals/pull/79)) in this conversation: Jupyter Notebook is here to stay, it is just getting a modernization/rewrite to use JupyterLab components and superpowers but it will retain its layout and features.

**Comment by romainx** [comment]
@mathbunnyru yes you're right I'm back 🤘 
Thanks a lot for all of the valuable links. If you don't mind I will take some time to look at them 👀 in depth since the landscape is rich. I will comment back here.

**Comment by romainx** [comment]
Hello,

Just a short update after reading most of the implementations. I'm wondering if the best solution to switch back to classic notebook is not to follow what has been done on [binder](https://mybinder.readthedocs.io/en/latest/howto/user_interface.html#classic-notebook-interface): just indicate to use the URL `http(s)://<server:port>/tree/`.  So there is no need to add a new variable as I proposed in the text of the issue (`JUPYTER_ENABLE_NB`). @mathbunnyru and @consideRatio if it's Ok for you I will update this issue and implement and document the change.

Best.

**Comment by mathbunnyru** [comment]
Sorry, @romainx I didn't understand how you want to proceed :(

**Comment by romainx** [comment]
Sorry @mathbunnyru my bad.

Here is the initial plan updated with the new proposal.

- **With no option (no specific environment variable)**: JupyterLab is launched, the classic notebook remains accessible through this URL:  `http(s)://<server:port>/tree/`.
-  **With `JUPYTER_ENABLE_LAB`**: Same behavior as without option + a warning message informs that this option is no more required.
- ~~**With `JUPYTER_ENABLE_NB`**: Jupyter Notebook is launched.  A warning / deprecation message is printed pointing to [the dedicated section][6] in the README.~~ [no new variable to switch back to the classic notebook] 
- Documentation is updated to document the new default and ~~the new start option~~ how to proceed to switch back to the classic notebook, just by using this URL `http(s)://<server:port>/tree/` exactly as defined in the [MyBinder](https://mybinder.readthedocs.io/en/latest/howto/user_interface.html#classic-notebook-interface) documentation.

Is it clearer now?

**Comment by romainx** [comment]
@mathbunnyru you're right it was unclear. I mixed the two last steps of the plan. Forget that, it was not a good idea. I will propose something in a PR.
