### ISSUE TITLE
Grant user mathbunnyru triage rights

### ISSUE THREAD

**Issue by romainx** [jupyter/docker-stacks#1218]
_Follows the same pattern as the issue that was created to grant me the same rights (#1036)._

@mathbunnyru  has been helping out quite a bit with responding to issues and submitting pull requests here for the past couple months, and doing so in a positive way in keeping with the Jupyter Code of Conduct. We would like to grant him triage rights as a stepping stone toward maintainer rights.

First, @mathbunnyru, are you interested? 😄 

There is no formal process for voting on elevating permissions in one-off Jupyter repos like this one, so I'm opening an issue here for community visibility and comment.

We plan to grant the permissions on January 26th.

@parente I hope you share the same opinion because I don't have the rights to do it by myself :sweat_smile:

**Comment by mathbunnyru** [comment]
> First, @mathbunnyru, are you interested? 😄

Yes, I would be glad to have triage rights and help when I can! 👍

Thanks for the proposal @romainx :)

**Comment by parente** [comment]
Thanks for opening this @romainx. I'm in favor. 

Thank you @mathbunnyru for your contributions so far. I'm happy to see you continue your participation in the project.

I've set my self a reminder to check back on the 26th.

**Comment by parente** [comment]
Today's the day. I see no objections and only support. 

@mathbunnyru I've added you as a collaborator with triage rights. You should get an invite via email. Cheers!

**Comment by mathbunnyru** [comment]
I received the invitation and accepted it 🎉
