### ISSUE TITLE
Update the base environment?

### ISSUE THREAD

**Issue by pylang** [jupyter/docker-stacks#1219]
**What docker image you are using?**

The link in the README to the latest image on master.

**What complete docker command do you run to launch the container (omitting sensitive values)?**

I clicked link 

https://mybinder.org/v2/gh/jupyter/docker-stacks/master?filepath=README.ipynb

**What steps do you take once the container is running to reproduce the issue?**

Example:

1. Open a new notebook
2. View conda info

```bash
> !conda list -n base | grep python
ipython                   7.2.0           py37h24bf2e0_1000    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
python                    3.7.1                h5001a0f_0    conda-forge
...
```
**What do you expect to happen?**

A later version of python.  At least python 3.8.

**What actually happens?**

The python version in the base environment appears [2 years old](https://anaconda.org/conda-forge/python/files/modal/info/5beb15fd5c424513598ab3c4) according to [Conda Cloud](https://anaconda.org/conda-forge/python/files?version=3.7.1&page=7).

Environments that clone from this base have a high chance of causing conflicts.  I've had some trouble with nbgrader lately.

Can the base image be updated?  

Trying to manually update it has some problems:

```bash
> !conda update -n base --all -y
...
Executing transaction: failed
ERROR conda.core.link:_execute(507): An error occurred while installing package 'conda-forge::asn1crypto-1.4.0-pyh9f0ad1d_0'.
FileNotFoundError(2, "No such file or directory: '/opt/conda/bin/python3.7'")
Attempting to roll back.

Rolling back transaction: done

FileNotFoundError(2, "No such file or directory: '/opt/conda/bin/python3.7'")
```

**Comment by mathbunnyru** [comment]
The issue is not actually in the base-image, it is updated quite a lot and right now we use python `3.8.6`, which should work just fine.

The problem is in the image used by mybinder.
https://mybinder.org/v2/gh/jupyter/docker-stacks/master?filepath=README.ipynb

And the phrase `You can try a recent build of the jupyter/base-notebook image on mybinder.org` is confusing as well.

**Comment by mathbunnyru** [comment]
I found the reason for the problem:

We hardcode the version for binder image:
https://github.com/jupyter/docker-stacks/blob/master/binder/Dockerfile

So, as a hotfix we can just update the tag used there.

**Comment by mathbunnyru** [comment]
I will craft a PR today or tomorrow, it sound super-easy.
