### ISSUE TITLE
Change UID for jovyan results in login as root

### ISSUE THREAD

**Issue by gaow** [jupyter/docker-stacks#1224]
According to [this page](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html#docker-options):

> -e NB_UID=1000 - Instructs the startup script to switch the numeric user ID of $NB_USER to the given value. ... The startup script will su $NB_USER after adjusting the group ID.

However it does not work for me:

```
$ echo $UID
1003
$ docker run -d --rm --security-opt label:disable -t -e NB_UID=$UID --user root --name test jupyter/base-notebook:latest 
3c85f6f9419fcd84ed81642b2b394f34f66281051796e8fe0cae2dfcd284def0
$ docker exec -it test bash
(base) root@3c85f6f9419f:~# 
```

I am expecting that by using `-e NB_UID=$UID --user root`  I'll be able to change UID for jovyan to 1003 then still run the container as jovyan for Jupyter -- I use command terminal above just to show what the problem is. Am I wrong about it? If so, how can I achieve this?

**Comment by romainx** [comment]
Hello @gaow,

No it's OK like this (even if you may need to expose the port to use the notebook UI).
You just need to tell `docker exec` to use the right user through the `--user` flag ([doc](https://docs.docker.com/engine/reference/commandline/exec/)).

```bash
echo $UID                                                                                                             
# 501

docker exec --user jovyan -it test id
# uid=501(jovyan) gid=100(users) groups=100(users)
```

Best
