### ISSUE TITLE
How can I see what packages are installed in the data science notebook

### ISSUE THREAD

**Issue by minertom** [jupyter/docker-stacks#1226]
I have successfully downloaded and built the docker file for the data science notebook.  It runs the jupyter notebook locally.

However, I don't really know which packages are loaded in it. For example, I type hit or miss "import pandas as pd" and that works, as to several others. But how can I tell which packages are really installed in the image?

Thank You
Tom

**Comment by mathbunnyru** [comment]
Hello, Tom!

You can run `!conda list` in a cell, which will run this command in place.
You can also run `conda list` in a terminal.

More info on how to use `conda`: https://docs.conda.io/projects/conda/en/latest/user-guide/index.html

**Comment by minertom** [comment]
Thank You!

Tom

**Comment by romainx** [comment]
Hello @minertom,

A **build manifest** is also available in the [GitHub Wiki](https://github.com/jupyter/docker-stacks/wiki).It displays the list of packages installed in each image tag. [Here](https://github.com/jupyter/docker-stacks/wiki/datascience-notebook-5cb007f03275#python-packages) is the list of packages for the latest `datascience-notebook`.

Best
