### ISSUE TITLE
Is there any way to send files to the local volume after starting jupyter stack?

### ISSUE THREAD

**Issue by amazongodman** [jupyter/docker-stacks#1227]
I have completed the tutorial from start to finish.

I confirmed that I can connect to local volume by starting the docker run command with the "-v" option.

If I forget to fill in -v at startup, is there any way to send files or notebooks 'ipynb' to local?
(or download)

thank you.

**Comment by Bidek56** [comment]
What's wrong with clicking the download button? :)

**Comment by amazongodman** [comment]
It seems to have been a temporary problems.
Now I was able to download and upload without any problems.
I thought It was not a temporary problems, but I mistakenly thought that I could not interact with the virtual environment.

thank you !
