### ISSUE TITLE
Volumes deleted when entering a container

### ISSUE THREAD

**Issue by pylang** [jupyter/docker-stacks#1229]
**What docker image you are using?**

`jupyter/scipy-notebook:latest`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

First, the setup:

```bash
> mkdir test_vols
> cd test_vols
> mkdir data
> touch data/foo.txt
```

Now the command:

```bash
  sudo docker run \
              -p 8888:8888 \
              -w /home/ \
              -e NB_USER=user \
              -e CHOWN_HOME=yes \
              -v `pwd`/data:/home/jovyan/data \
              --user root \
              --name test_vols \
              -it --rm jupyter/scipy-notebook:latest \
              start.sh \
              jupyter lab \
              --ip=0.0.0.0 \
              --no-browser
```

Note: `sudo` may be optional on your system.  Replace `user` with your appropriate username.

**What steps do you take once the container is running to reproduce the issue?**

No steps required.  

**What do you expect to happen?**

We are focusing on the volume outside the container:

```bash
> pwd
~/path/to/test_vol
```

1. After closing the container, I expect the contents of the volume folder to persist.

```bash
> tree
.
└──  data
    └── foo.txt
```

**What actually happens?**

1. After ~~closing~~ starting the container, the contents of the volume folder is deleted.

```bash
> tree
.
└── data
```

----

**Details**

*Problems*

Having the volume deleted is serious, and that seems like a bug.  The contents seem to be deleted once the container starts.

There is also an additional minor problem that occurs internally.   `/home/joyvan/` folder does not get properly renamed to `/home/user`.  You can see this while inside the containers via `ls` and `ls -al user`.

*Debugging*

I've invoked many combinations of parameters with a range of results.  I've narrow this particular bug to how mounted volumes are internally mapped:

Mapping | Rename `/home/jovyan/` to `/home/user`? (internal) | Volume preserved? (external)
---|---|---
` -v .../data:/home/jovyan/data ` | No | No 
` -v .../data:/home/user/data `     | No | Yes
` -v .../data:/home/data `             | Yes | Yes

If we map to either user internally, we get undesired results.  If we map elsewhere (e.g. the last row),  we get desired results.

**Pending work-around (so far)**

1. Avoid volume deletions - don't map mounted volumes to `jovyan`.
1. Fully rename jovyan to user homedir - don't include the `user` in any volume mapping `-v` or working directory `-w`.

This problem is related to #769, which is marked "Debugging needed"; hopefully this feedback will aid in enclosing the problem.  See also the related [source script](https://github.com/jupyter/docker-stacks/blob/5cb007f032755b61eb6b3c6d4581a5260ba6b8e5/base-notebook/start.sh#L50).

**Comment by tronicum** [comment]
could you supply an `docker info` output plz?

**Comment by pylang** [comment]
```bash
> sudo docker info
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 42
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-12-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 3.854GiB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Labels:
 Experimental: false
 Live Restore Enabled: false


```

**Comment by tronicum** [comment]
i am pretty new to juypter myself but it looks like you are mounting stuff, not "creating" volumes, are you? ever tried creating a specific volume beforehand? as on the docker docs
"Named volumes have a specific source from outside the container, for example awesome:/bar."
 "Anonymous volumes have no specific source so when the container is deleted, instruct the Docker Engine daemon to remove them."

if you create an specific volume it should persist. also i never tried cloudstor yet but it seems a nice concept: https://medium.com/@MahmoudGaballah/persistent-data-volumes-for-docker-swarm-4d6be0ae9ba3

**Comment by pylang** [comment]
Correct.  I'm mounting a directory using the `-v` flag per the docs

> `-v /some/host/folder/for/work:/home/jovyan/work` - Mounts a host machine directory as folder in the container. Useful when you want to preserve notebooks and other work even after the container is destroyed.

The trouble is I'm losing data if I use certain combinations of flags, recommended in the docs.  Here is a related [problem](https://github.com/jupyter/docker-stacks/issues/769#issuecomment-509499266).  I don't particularly want to get into making docker volumes and connecting them as you're suggesting, but yes I think that is an option.

**Comment by jeffyjefflabs** [comment]
I encountered the same thing - I didn't have time to investigate closely, but my guess was the combination of setting `$NB_USER` and mounting something underneath `/home/jovyan` causes docker to do bad things when the Jupyter startup script tries to rename the home directory.  Might be worth at least adding a warning to the docs in the `$NB_USER` section?

@pylang, if your end goal was the same as mine, to mount a local directory but have the permissions match the host user, what ended up working for me was setting

```
-e NB_UID=`id -u` -e NB_GID=`id -g`
```

The user*name* inside the container is still `jovyan`, but the uid and gid will match the host user, so the permissions will work out correctly both inside and outside the container.

**Comment by mathbunnyru** [comment]
Thanks to @rigzba21 , this should be fixed now.
