### ISSUE TITLE
Images tagging not done during the latest build

### ISSUE THREAD

**Issue by romainx** [jupyter/docker-stacks#1237]
Hello,

Just noticed that during the last build only the `latest` tag was pushed to DockerHub on all images of the stack.
It has been done through [this build ](https://github.com/jupyter/docker-stacks/runs/1882175244?check_suite_focus=true).
It's weird since the wiki is up to date and the corresponding PR #1236 was only about bumping some packages versions.

Best

**Comment by romainx** [comment]
In fact the last successfully tagged stack was done the **2021-02-08**, after this date only the latest tag is pushed to DockerHub. @mathbunnyru I do not understand what is going on, any idea on your side?

**Comment by mathbunnyru** [comment]
I will take a look. I'm not familiar with the dockerhub maintenance, but I will try my best, having all the tags is important.

**Comment by mathbunnyru** [comment]
Done :)
