### ISSUE TITLE
How does this work with dockerspawner?

### ISSUE THREAD

**Issue by quanghoc** [jupyter/docker-stacks#124]
Hi

I am new to this. I got the Jupyter spark docker works. But how to use dockerspawner in this whole thing? Please provide some examples?

**Comment by parente** [comment]
Someone contributed some documentation to jupyter/tmpnb about how to run these images there. It would probably make sense to contribute the equivalent in the JupyterHub documentation, if it's not already there.

I'm not a dockerspawner or Jupyter Hub expert. (I need to read up.) I do see that at least one of the images defined in `dockerspawner` are already based on the images here (e.g., https://github.com/jupyter/dockerspawner/blob/master/singleuser/Dockerfile). My guess is that you could swap out the `FROM` line in that Dockerfile with your image of choice from over here and it would work.

@minrk, do you have any advice?

**Comment by minrk** [comment]
Yup, in most cases for use with DockerSpawner, given any image that already has a notebook stack set up, you would only need to add:

1. install the jupyterhub-singleuser script (for the right Python)
2. change the command to launch the single-user server

Swapping out the FROM line in the jupyterhub/singleuser Dockerfile should be enough for most cases.

**Comment by parente** [comment]
I added the gist of this question and reply to the recipes wiki: https://github.com/jupyter/docker-stacks/wiki/Docker-recipes#use-with-jupyterhubs-dockerspawner

I'm going to close this as the info is now documented somewhat. @quanghoc, feel free to reopen or update the wiki page with more detail if you have it.
