### ISSUE TITLE
Redo PR to change jupyter_server_config

### ISSUE THREAD

**Issue by ChristophSchranz** [jupyter/docker-stacks#1240]
https://github.com/jupyter/docker-stacks/blob/c3d5df67c8b158b0aded401a647ea97ada1dd085/base-notebook/jupyter_notebook_config.py#L11-L13

Please redo this commit c41616d7f30ed957f1fdf523819d328083270062
in order to change the file `jupyter_notebook_config.py` to `jupyter_server_config.py` and change the Notebook fields.

Thanks! :)

**Comment by mathbunnyru** [comment]
@romainx this is your commit :)

If you have some time, could you check this out, please?

**Comment by romainx** [comment]
Hello @ChristophSchranz & @mathbunnyru,

The commit you mention has been replaced by the following code that basically does the same thing without file duplication.
https://github.com/jupyter/docker-stacks/blob/c3d5df67c8b158b0aded401a647ea97ada1dd085/base-notebook/Dockerfile#L159-L161

You can check that everything is fine in the resulting `base-notebook`.

```bash
$ docker run -t jupyter/base-notebook:latest grep ServerApp /etc/jupyter/jupyter_server_config.py
# c.ServerApp.ip = '0.0.0.0'
# c.ServerApp.port = 8888
# c.ServerApp.open_browser = False
# c.ServerApp.certfile = pem_file
```

@ChristophSchranz please could you confirm that it's Ok for you?

Thanks

**Comment by ChristophSchranz** [comment]
Yes that should be okay.

**Comment by ChristophSchranz** [comment]
I've found that the problem was caused by a deprecated cached dependency. Rebuilding without cache (`docker build --no-cache -t tagname .build/`) solved this issue for me:

**Comment by ChristophSchranz** [comment]
Thanks for the quick response and maintenance!

**Comment by mathbunnyru** [comment]
I always use `--pull` to make sure, that I use the latest (and, hopefully, greatest) version of Docker image.
