### ISSUE TITLE
Rollback to a tagged image does not work

### ISSUE THREAD

**Issue by hragbalian** [jupyter/docker-stacks#1247]
Hello, 

For several months, I've been spawning Lab instances using the jupyter/datascience-notebook image.  In my builds, I hadn't specified any tags so was just referencing the image as 

```
FROM jupyter/datascience-notebook as base
```

but most of our builds bypassed the image hosted on DockerHub and just updated via our cache (which is on ECR).  We had to do a cache-bust on a recent build to update some libraries, as they weren't updating otherwise, but this resulted in (I'm guessing) the 'latest' tagged image from jupyter/datascience-notebook getting pulled and installed.  

A recent change in the image (I believe with updates to the JupyterLab library) broke some dependencies with some extensions my team uses, so I've been looking to roll back to an older image from ~3 months ago. 

However, I'm having trouble doing this rollback effectively, because whenever I use any tagged image as part of my build, for example, 

```
FROM jupyter/datascience-notebook:d113a601dbb8 as base
```

while the build completes without any issues, and the post-spawn notebook logs look normal, the notebook itself is just a blank white screen. I've tried with ~20 different tags, and always get the same issue.  When I remove the tag and rebuild, i.e. back to 

```
FROM jupyter/datascience-notebook as base
```

all looks normal, except I still have the dependency issue I need to resolve.  

Is there something with building with tagged images that I need to account for? Any help would be greatly appreciated to explain why this is occurring.  

Hrag

**Comment by romainx** [comment]
Hello,

The problem you encounter with the extension is probably linked to the upgrade to JupyterLab `v3.0.x` that was done in the PR #1222. 
If you want to use a version with JupyterLab 2.2.x you can just use the tag `lab-2.2.9`.

```bash
docker run -it --rm -p 8888:8888 -e JUPYTER_ENABLE_LAB=yes jupyter/datascience-notebook:lab-2.2.9 
```

To answer your second question, you should be able to build from a tagged image the same way. There is nothing special to know except that the base image could be different, but it does not seems to be the problem.

For the blank notebook I don't know, maybe you can check if you have a config file containing a not compliant configuration that has persisted in your home or something in your browser cache (try to clear the cache)?

Hope it will help you.
Best

**Comment by hragbalian** [comment]
Thanks @romainx! Yes, there was an incompatible file in the .jupyter/lab directory.  When I wipe that directory the Lab loads fine.  Much appreciated.
