### ISSUE TITLE
pyspark library is missing from jupyter/pyspark-notebook when running with jupyterhub/zero-to-jupyterhub-k8s

### ISSUE THREAD

**Issue by uluzox** [jupyter/docker-stacks#1255]
pyspark library is not available in the pyspark-notebook when running on jupyterhub.

**What docker image you are using?**
jupyter/pyspark-notebook:9fe5186aba96

**What complete docker command do you run to launch the container (omitting sensitive values)?**
I am running a jupyterhub instance on k8s that starts the above mentioned container

**Description**
When running jupyter/pyspark-notebook locally, I can import pyspark as I would expect:
```
from pyspark import SparkConf, SparkContext
```
-> no errors

When I run jupyter/pyspark-notebook with my jupyterhub/zero-to-jupyterhub-k8s helm installation, the same code returns:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-ee46be618299> in <module>
----> 1 from pyspark import SparkConf, SparkContext

ModuleNotFoundError: No module named 'pyspark'
```

Running `python -m pip list --format columns`. Does return a lot of installed modules however not the pyspark module.

Having read https://stackoverflow.com/a/31541051/5930295 I tried to update the sys.path because I found that pyspark is installed in the container under the following locations. Running:
```
import sys
sys.path.insert(0, '/usr/local/spark/python')
sys.path.insert(0, '/usr/local/spark/python/lib/py4j-0.10.9-src.zip')

from pyspark import SparkConf, SparkContext
```
-> No errors

**Comment by mathbunnyru** [comment]
I know nothing about pyspark at all, but I can see that we have some hooks to enable pyspark in pyspark-notebook.

For example, we have this line:
https://github.com/jupyter/docker-stacks/blob/master/pyspark-notebook/Dockerfile#L50
`ln -s "${SPARK_HOME}/sbin/spark-config.sh" /usr/local/bin/before-notebook.d/spark-config.sh`

And the comment is actually makes sense:
`# Add a link in the before_notebook hook in order to source automatically PYTHONPATH`

Could it be that in your setup this file is not run or some variables are wrong?

**Comment by uluzox** [comment]
The contents of the script look exactly like what I am doing manually.
So I assume you are right. The script probably is not running. When should it be running? Who starts the run when running the container image with docker run?

**Comment by mathbunnyru** [comment]
This is the start script:
https://github.com/jupyter/docker-stacks/blob/master/base-notebook/start.sh
Note that there are 2 branches - if we're running from root and if not (and in both cases we run before-notebook.d hooks).

Docs on these start scripts:
https://github.com/jupyter/docker-stacks/blob/master/docs/using/common.md

https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile#L150
"start-notebook.sh" is a cmd which is run when container is started.

After that it runs `start.sh` with some params or `start-singleuser.sh` (which then also runs start.sh).

Which scripts are actually run actually depends on the params you launch your docker with.

General folder where to look for the start scripts: https://github.com/jupyter/docker-stacks/tree/master/base-notebook

**Comment by Bidek56** [comment]
I think this is an issue with `jupyterhub/zero-to-jupyterhub-k8s helm` because I am running this image on AKS
`FROM jupyter/pyspark-notebook:9fe5186aba96`
and have no issues, everything works just fine.

**Comment by Bidek56** [comment]
Have you looked at this [doc](https://zero-to-jupyterhub.readthedocs.io/en/latest/jupyterhub/customizing/user-environment.html)?

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/pyspark-library-is-missing-from-jupyter-pyspark-notebook-when-running-with-jupyterhub-zero-to-jupyterhub-k8s/8450/1

**Comment by uluzox** [comment]
Using the following config.yaml fixes the problem. 
```
singleuser:
  defaultUrl: "/lab"
  image:
    name: jupyter/pyspark-notebook
    tag: latest
  cmd: ["/usr/local/bin/start.sh", "jupyterhub-singleuser"]
```

The cause is, that the `jupyterhub/zero-to-jupyterhub-k8s` helm chart calls jupyterhub-singleuser directly and skips the start script.
