### ISSUE TITLE
Possibility of Publishing to GitHub Packages

### ISSUE THREAD

**Issue by THargreaves** [jupyter/docker-stacks#1264]
There would be considerable benefits to having the Jupyter Docker Stacks publish to [GitHub Package Repository](https://github.com/features/packages) as well as DockerHub. This allows [considerably faster caching](https://dev.to/dtinth/caching-docker-builds-in-github-actions-which-approach-is-the-fastest-a-research-18ei) than can be achieved via other means.

Are there plans to implement this? Is there anything preventing this?

**Comment by romainx** [comment]
Hello @THargreaves. 

To be honest I'm not familiar with GitHub Package Repository and its policy regarding open source projects. Would we be able to store all stacks built here for free?

I don't know neither if there is a global strategy at Jupyter organization level to stick to DockerHub and / or to provide an alternative.

Sorry I'm not a big help, but it could make sense, if you or someone else has more information, do not hesitate.

Best.

**Comment by THargreaves** [comment]
No worries. Yes, GPR is free for public repositories. 

As far as I am aware, the process for pushing to GPR is exactly the same as DockerHub but using specifying `ghcr.io` when logging in, tagging, and pushing.

E.g. here is the introductory Docker example provided by GitHub

```
echo $PAT | docker login ghcr.io --username phanatic --password-stdin
docker tag app ghcr.io/phanatic/app:1.0.0
docker push ghcr.io/phanatic/app:1.0.0
```

**Comment by mathbunnyru** [comment]
For me, the main question is - do we really need faster caching?
Right now, I don't think that is the case.
At the same time, there is a growing interest in images for other architectures, so the complexity might raise significantly.

**Comment by romainx** [comment]
@mathbunnyru good point we have prototyped that building multi-arch image is not sustainable with the current build solution. There is an open issue for that #1203 that could benefit from this solution.

**Comment by mathbunnyru** [comment]
@THargreaves are you still interested in publishing images to GitHub Packages?
I don't think we need caching, because currently build system works well.

**Comment by THargreaves** [comment]
This is not something I am personally interested in or have the time to look into anymore.

**Comment by mathbunnyru** [comment]
Then, I guess, we can close this issue.
