### ISSUE TITLE
Is there an image with ubuntu-20.04

### ISSUE THREAD

**Issue by midav7** [jupyter/docker-stacks#1265]
Hi there, 
Does jupyter/base-notebook base docker image with the latest ubuntu-20.04 version exist on DockerHub?
I can only find it with ubuntu-18.04 https://hub.docker.com/layers/jupyter/base-notebook/ubuntu-18.04/images/sha256-8502dd73c35fe239a33d52ee371a30282f570e387a5503ef69639fe0c35b13ac
I appreciate any advice. Thank you in advance.

**Comment by mathbunnyru** [comment]
All the images after the one you mentioned use 20.04.
So, pick a recent image and it should be fine.

The thing is that we manually tagged latest 18.04 image if people need more time adjusting their setup.

More info:
https://github.com/jupyter/docker-stacks/pull/1096#issuecomment-645741243

**Comment by romainx** [comment]
@mathbunnyru maybe another suggestion for the tag improvement you are working on #1250.
I think we can close this issue.
