### ISSUE TITLE
Deleting cache files

### ISSUE THREAD

**Issue by Kula4ud3e** [jupyter/docker-stacks#1266]
Good afternoon!

I am using the `jupyter/datascience-notebook` image for work. And I have a problem, when a pod is created for a user in the pod there should not be cache files at the paths `/opt/conda/share/jupyter/lab/staging` and `/home/jovyan/.cache`. The cache in `/home/jovyan/.cache` is created each time the user logs in to their pod. 

I would like to know how I can delete this cache?

Thanks!

**Comment by consideRatio** [comment]
I think it is out of scope to decide what the software running inside the container should or shouldn't do with regards to `/home/jovyan/.cache` during container startup in general.

I think it is in scope to consider if a container starting with a `bash` entrypoint have within `/opt/conda/share/jupyter/lab/staging`, and if it would make sense to clear that.

## Questions
1. Do you have a suggestion of configuration of some software to not emit something to that folder?
2. Can you motivate why `/opt/conda/share/jupyter/lab/staging` should be cleared during build?
   Note that I'm asking as I don't know either pro/con of doing so, as it relates to how jupyterlab would use this folder. My gut feeling is that it could make sense to clear it, but I'm also open to the idea it can cause trouble in some situations to do so.

**Comment by mathbunnyru** [comment]
Closing this one - there is no response from the user, please, reopen, if this issue is stilll valid.
