### ISSUE TITLE
Tensorflow 2 is finally on conda-forge!

### ISSUE THREAD

**Issue by maresb** [jupyter/docker-stacks#1268]
As of about 4 days ago. It is now finally possible to do `mamba install tensorflow` or `conda install tensorflow`.

It would be great to switch tensorflow-notebook from `pip` to `conda` or `mamba`. I have not yet had the chance to test it out though.

**Comment by mathbunnyru** [comment]
That's great news!

I also don't like using pip and conda together (better to install all the things using conda).
But, in this case, we're already using `2.4.1`, but for now only 2.4.0 is available in conda-forge.

https://anaconda.org/conda-forge/tensorflow/files

I hope, they will update soon and we will switch to conda.

**Comment by mathbunnyru** [comment]
There is a PR attempt to update the version:
https://github.com/conda-forge/tensorflow-feedstock/pull/114
