### ISSUE TITLE
jupyter/pyspark-notebook doesn't start  SparkUI

### ISSUE THREAD

**Issue by Bonifacio2** [jupyter/docker-stacks#1272]
Hello, I'm trying to use `jupyter/pyspark-notebook` and according to the docs [here](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/specifics.html#apache-spark), the SparkUI should be available at localhost:4040 after I run the following command `docker run -d -p 8888:8888 -p 4040:4040 -p 4041:4041 jupyter/pyspark-notebook`, but it doesn't seem to be the case.

**What docker image you are using?**

`jupyter/pyspark-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

`docker run -d -p 8888:8888 -p 4040:4040 -p 4041:4041 -p 4042:4042 jupyter/pyspark-notebook`

**What steps do you take once the container is running to reproduce the issue?**

1. Visit http://localhost:4040

**What do you expect to happen?**

The SparkUI is available at localhost:4040

**What actually happens?**

I get the message:
```This page isn’t working
localhost didn’t send any data.
ERR_EMPTY_RESPONSE
```

**Comment by mathbunnyru** [comment]
Note: I know nothing about spark :)

I've just checked and have the same issue as you do.

I think the idea here is that we don't launch any spark process automatically and you have to create the session like this:

```
from pyspark.sql import SparkSession

# Spark session & context
spark = SparkSession.builder.master('local').getOrCreate()
```

This way you will create a spark session in python.
After running this code, port `4040` works fine.
And, if I shut down the kernel, of course, the port is also down.

There is more information on how to use Spark in different languages:
https://jupyter-docker-stacks.readthedocs.io/en/latest/using/specifics.html?highlight=spark#using-spark-local-mode

**Comment by romainx** [comment]
@mathbunnyru you're right 👍 
Just we need to precise that the port 4040 has to be exposed to be accessed from the host.
For example.

```bash
docker run -it --rm -p 8888:8888 -p 4040:4040 -e JUPYTER_ENABLE_LAB=yes jupyter/pyspark-notebook 
```

Best

**Comment by Bonifacio2** [comment]
Thank you, both. I guess it just wasn't clear to me when the spark context would be created.
