### ISSUE TITLE
rpy2 not installed in `r-notebook` image

### ISSUE THREAD

**Issue by psychemedia** [jupyter/docker-stacks#1273]
One of the use cases for the R containers might be to demo differences between R and Pyhton notebooks.

Should `rpy2` be installed by default into those containers to allow testing / demoing the use of `rpy2` package and `%R / %%R` magics in a minimal Python environment ?

**Comment by romainx** [comment]
Hello @psychemedia,

I think the image you are looking for is `datascience-notebook`, it includes both R (including `rpy2`) and Python environment. The `r-notebook` image is intended to be a minimal image dedicated to R kernel / usage. For python in this image, there is no scientific packages installed, so it will not be very useful I guess.

Does it make sense for you?
Best

**Comment by psychemedia** [comment]
Hi @romainx 

Yes, makes sense. But I was thinking just very simple demos of R in a python notebook, not a data science application use, specifically.

The `r-notebook` image is pretty lightweight and ideal if you just want to demo to someone how to run an R command in a Python notebook. By comparison the datascience notebook is huge and overkill. There is a Python kernel in the `r-notebook` image so it just seems handy way to let folk compare behaviour. Plus it would provide a container to pull from for a custom image that for whatever reason wants to use R in a py notebook. (I guess the corollary is also to ensure reticulate is installed as an R package to demo how you might call Python from inside an R environment.)

**Comment by romainx** [comment]
Hello @psychemedia,

You made me change my mind 😄. 
Installing `rpy2` could be useful and it will not make the image heavier (2.56GB vs. 2.55GB-> You can draft a PR for that if you want.

And you're right 'reticulate` could also make sense but more in `datascience-notebook` since users will not benefit from so much Python packages in `r-notebook`.

Best

**Comment by mathbunnyru** [comment]
@psychemedia are you still interested in making this change?

**Comment by mathbunnyru** [comment]
No response from @psychemedia, so I will close this issue.
