### ISSUE TITLE
Permission to jupyter/docker-stacks.wiki.git denied to github-actions[bot].

### ISSUE THREAD

**Issue by mathbunnyru** [jupyter/docker-stacks#1280]
Pushing to the `https://github.com/jupyter/docker-stacks.wiki.git/` seems to be broken right now.

It means that no build manifests are generated.

Fir PR merge where it happened: https://github.com/jupyter/docker-stacks/commit/dfcb043bd88798a9419a5c7a38eb1218f7aac941
The Github Actions run: https://github.com/jupyter/docker-stacks/commit/dfcb043bd88798a9419a5c7a38eb1218f7aac941

It also happened during the last merge: https://github.com/jupyter/docker-stacks/commit/fde8f1eec3e70edf67560b5430545a22382334bf

So, unfortunately, it's not spurious.

The thing is that we didn't change this part of the process (in the first PR).
And it's the `remote`, which gives an error:

```
remote: Permission to jupyter/docker-stacks.wiki.git denied to github-actions[bot].
25
fatal: unable to access 'https://github.com/jupyter/docker-stacks.wiki.git/': The requested URL returned error: 403
```

So it means that something is wrong with the internal GitHub setup.

**Comment by consideRatio** [comment]
Is this an action related to secrets.GITHUB_TOKEN? Perhaps the jupyter org has reduced the permissions by default now?

See https://github.com/jupyterhub/team-compass/issues/404

**Comment by mathbunnyru** [comment]
Yes, it is.

https://github.com/jupyter/docker-stacks/blob/master/.github/workflows/docker.yml#L63-L69

Probably this is the reason why it doesn't work.
