### ISSUE TITLE
Diagram of how images relate

### ISSUE THREAD

**Issue by jakirkham** [jupyter/docker-stacks#129]
Maybe this is somewhere and then a good nudge in the right direction would be great.

I think it would be really nice to have a diagram that shows us how the different images here are related. It seems like we have quite a few and it would really help to understand which images are affected by making a change in one Dockerfile. It could probably be some SVG so it shows up nicely in the browser (even mobile) and we could embed it in the top level Readme. Thoughts?

**Comment by parente** [comment]
:+1: 

The interactions aren't that complex from a Docker inheritance standpoint. The max-depth of the tree is 2. But, to your point, it's good to depict that.

I'm also wondering if less popular images should be culled over time to reduce the maintenance and complexity cost. For example, r-notebook has been pulled from Docker Hub about 100 times total. In contrast, all-spark-notebook has been pulled 166,000 times.

**Comment by jakirkham** [comment]
> The interactions aren't that complex from a Docker inheritance standpoint.

Sure there is no multiple inheritance. So, simple tree.

> The max-depth of the tree is 2.

Of our tree? Sure.

> I'm also wondering if less popular images should be culled over time to reduce the maintenance and complexity cost. For example, r-notebook has been pulled from Docker Hub about 100 times total. In contrast, all-spark-notebook has been pulled 166,000 times.

Yes, generally, taking stock is a good idea, as well.

I think I recall seeing the pushes were counted in the total at some point. I don't know if it was intentional or not. Also, this was awhile ago so this behavior could have been corrected.

**Comment by parente** [comment]
Assuming all the outstanding PRs about singleuser and pyspark/all-spark unification go in, how about this?

http://interactive.blockdiag.com/?compression=deflate&src=eJyNjrEOgkAQRHu-4kLt9UaCkc7e0hizwELWW_bI3VGg8d8FCxMR0XLfzLxszrYwJUGtbpFS1hFKgEBWVKpa64IDCsmQlFhBx-FcWQmerjjE65Fn6siQI6dxiTmBbC7oPeHusM_iUxI9G3qrGhJqgLXYgLm1ZvUiBp0gj6ppZ9z5gtp-gWhPUjN2Ht2o-KyXEGCgKAX-5BPZ3D_uy_XHtO19C84ssolmbgLM-h_6pro_AAFCq-Y

which is the source for:

![](http://interactive.blockdiag.com/image?compression=deflate&encoding=base64&src=eJyNjrEOgkAQRHu-4kLt9UaCkc7e0hizwELWW_bI3VGg8d8FCxMR0XLfzLxszrYwJUGtbpFS1hFKgEBWVKpa64IDCsmQlFhBx-FcWQmerjjE65Fn6siQI6dxiTmBbC7oPeHusM_iUxI9G3qrGhJqgLXYgLm1ZvUiBp0gj6ppZ9z5gtp-gWhPUjN2Ht2o-KyXEGCgKAX-5BPZ3D_uy_XHtO19C84ssolmbgLM-h_6pro_AAFCq-Y)

**Comment by willingc** [comment]
Very pretty. I sent another PR to move it up the page #172
