### ISSUE TITLE
Removal of some ENV and ARG fields for Dockerfile readability?

### ISSUE THREAD

**Issue by consideRatio** [jupyter/docker-stacks#1291]
How to minimize complexity and maximize readability of the Dockerfile while introducing support for using the same Dockerfile to build more than one architecture? While considering this...

## I wonder if we can...

1. Stop declaring `CONDA_VERSION` and `MINIFORGE_VERSION` environment variables which was introduced [6](https://github.com/jupyter/docker-stacks/commit/96ab5502e1e582063d543b4bc4e2adeb1bd7f837#diff-9e27864f9363ab69ed89e3e00eab9c0d25872c92a97c868b271d0c21fa0e8f36R61) and [5 months ago](https://github.com/jupyter/docker-stacks/commit/86523f0619dcca40391529aecd762fabd16e22a0#diff-9e27864f9363ab69ed89e3e00eab9c0d25872c92a97c868b271d0c21fa0e8f36R71) respectively.
2. Stop accepting many different `--build-arg` such as these, and instead declare them in the beginning of a RUN step.

   https://github.com/jupyter/docker-stacks/blob/09fb66007615ea68d9bce8f8e1a2cf9402f1e432/base-notebook/Dockerfile#L22-L42

## This is why...

1. `TARGETPLATFORM` is a `--build-arg` given [special treatment by docker buildx](https://docs.docker.com/buildx/working-with-buildx/#build-multi-platform-images), and I plan that it or another single `--build-arg` can let us decide what checksum to use in a map of checksums, on for each supported arch.
2. To select one out of various checksums we must do it in a RUN step rather than an ARG or ENV step I think.[1]
3. To not separate logic about versions, checksums etc for a given installation, it can read better if we locate it at the top of a RUN step where the information is used such as installing miniforge.

### Notes
- [1] Whatever is set with ENV can only be influenced by ARG parameters to my knowledge, because it doesn't work to `export MY_VAR` in a RUN step to a separate step and you can read a file or similar while setting a variable within an ENV step. This means that ARG / ENV can't involve computed properties.

## Concrete questions I'm hoping for answers to

I feel my motivation is a bit vague, but the gist is that while trying things out I struggle with creating a Dockerfile that is easy to read while also retaining all ENV and ARG which have some limitations on them and often can be located separate from where they are needed. Can we compromise a bit on ENV and ARG definitions, or more specifically...

- Would it be acceptable to stop declaring CONDA_VERSION and MINIFORGE_VERSION?
- Would it be acceptable to stop declaring many other ARG fields for miniforge_xxxxx for example?

**Comment by manics** [comment]
A downside of `TARGETPLATFORM` is it's not set by `docker build`, so to retain compatibility you'd have to fallback to a default architecture such as `amd64`, but that will break `docker build` on `arm64`/`aarch64`.

The approach I took in Z2JH was to obtain the architecture from `uname -a` and avoid any special buildx variables, e.g.:
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/7a3d18606d7bd4573216302a8a8a7bab804defed/images/secret-sync/Dockerfile#L6-L10
(ignore the `date`, that must've crept in during debugging :smile: )

**Comment by mathbunnyru** [comment]
> Would it be acceptable to stop declaring CONDA_VERSION and MINIFORGE_VERSION?

Is there a way to be both flexible in the terms of arch and being able to change the behaviour using `--build-arg`?
If there is not, then I'm ok with losing the flexibility to specify versions with build arguments.
But if there is, let's consider it.

**Comment by mathbunnyru** [comment]
I think this is fixed now, because we switched to always using latest Miniforge
