### ISSUE TITLE
"Add a Python 3.x environment" documentation doesn't work

### ISSUE THREAD

**Issue by ItamarShDev** [jupyter/docker-stacks#1298]
Using [this docs page](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html#add-a-python-3-x-environment), i am trying to update python to 3.8.8 with JLab 2

The result is the I can open JHub and see the python packages listed under `pip freeze`
But the labextensions are not loaded and I can import any of the pip packages.

What am I missing here>

My Dockerfile
```docker
# ...
# Install git (for getting custom extensions from git)
USER root
RUN apt-get update
RUN apt-get install -y git vim curl

COPY backup_user_data.sh /etc/jupyter/backup_user_data.sh
RUN chmod +x /etc/jupyter/backup_user_data.sh

# name your environment and choose python 3.x version
ARG conda_env=python38
ARG py_ver=3.8.8

# you can add additional libraries you want conda to install by listing them below the first line and ending with "&& \"
RUN conda create --quiet --yes -p $CONDA_DIR/envs/$conda_env python=$py_ver ipython ipykernel && \
    conda clean --all -f -y

# create Python 3.x environment and link it to jupyter
RUN $CONDA_DIR/envs/${conda_env}/bin/python -m ipykernel install --user --name=${conda_env} && \
    fix-permissions $CONDA_DIR && fix-permissions /home/$NB_USER

USER jovyan

# Install pip packages
RUN $CONDA_DIR/envs/${conda_env}/bin/pip install  --no-cache-dir --trusted-host ${PIP_TRUSTED_HOST} --index-url ${PIP_INDEX_URL} --extra-index-url ${EXTRA_PIP_INDEX_URL} -r requirements.txt -r imubit-requirements.txt
# prepend conda environment to path

ENV PATH $CONDA_DIR/envs/${conda_env}/bin:$PATH

# Set environment as default
# ENV CONDA_DEFAULT_ENV ${conda_env}

# Install extensions
RUN bash install_extensions.sh ./extensions.txt
RUN jupyter lab build
# ...
```

**Comment by mathbunnyru** [comment]
@ItamarShDev may I ask you to simplify your example?

1. It should be reproducible by other people and complete. It means, there should be no `backup_user_data.sh` or `install_extensions.sh` steps or you should provide these files.
2. The same thing goes about the long `pip install` command, which has many arguments like `PIP_TRUSTED_HOST` or `requirements.txt -r`, `imubit-requirements.txt`
3. Delete all the steps which are not needed to reproduce the issue. Simplification will increase the chance that the bug will be found.
4. You forgot to specify base image - you might be using some fixed tag which was created a long time ago. Please, provide the details.
5. Could you please elaborate a little bit on the issue you have? I'm sorry, but I didn't get the problem. For example, provide us with some action/command you run and the output you see / expected output.

**Comment by ItamarShDev** [comment]
1. you can ignore those lines, basically i am installing our internal IpyWidgets based tools, install_extensions.sh installs private JLab extenstions
2. we are using our own pypi repository, works before the change.
3. will attach simpler example
4. jupyter/base-notebook:lab-2.0.1
5. The dockerfile shows no error but:
  a. i can see the python packages in pip freeze but cant import them.
  b. the JLab frontend extensions are not loaded.

```
FROM jupyter/base-notebook:lab-2.0.1

# Install git (for getting custom extensions from git)
USER root
RUN apt-get update
RUN apt-get install -y git vim curl

COPY backup_user_data.sh /etc/jupyter/backup_user_data.sh
RUN chmod +x /etc/jupyter/backup_user_data.sh

USER jovyan

# Install pip packages
RUN pip install some-ipywidgets-package

# Install extensions
RUN jupyter lab build
# install some Jupyter Lab Frontend extenstion
RUN jupyter lab build
```

**Comment by mathbunnyru** [comment]
@ItamarShDev your Dockerfile is still not reproducible.
Once again - make it as simple as possible, delete `backup_user_data.sh` if it's not relevant.
Instead of writing `some-ipywidgets-package`, write one concrete example which doesn't work (and it should).

The easy check - you should be able to run `docker build .` with your Dockerfile.

**Comment by consideRatio** [comment]
From a maintenance perspective of this repository, I think the only thing in scope of a GitHub issue is if we conclude that [the example in the documentation](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html#add-a-python-3-x-environment) is malfunctional.

The action point is then to make it functional, or update the documentation somehow. Is this example malfunctional?

**Comment by mathbunnyru** [comment]
Renamed this issue to make it more clear

**Comment by mathbunnyru** [comment]
This issue is a way of improving our docs to provide better info:
https://github.com/jupyter/docker-stacks/issues/1298

**Comment by oskarryn** [comment]
For me the recipe "Add a Python 3.x environment" works, I verified using jupyter/minimal-notebook and jupyter/pyspark-notebook images as the parent image. I suggest you start exactly with the recipe and once you get it working, incrementally add your stuff to identify what's causing the issue. I suspect an issue related to root/jovyan user.

**Comment by mathbunnyru** [comment]
I have updated the docs to use python 3.7 (python 3.6 has reached EOL) and I confirm that I can see new kernel.
Please, check, if you still have a problem and reopen the issue and provide more details.
