### ISSUE TITLE
I'd like to contribute to this repo's maintenance

### ISSUE THREAD

**Issue by consideRatio** [jupyter/docker-stacks#1300]
It made me so happy to see the maintenance momentum created by @romainx and @mathbunnyru in recent weeks and I want to contribute to it.

I'm asking here as the README file described...

> Anyone in the community can jump in and help with these activities at any time. We will happily grant additional permissions (e.g., ability to merge PRs) to anyone who shows an on-going interest in working on the project.

My past activity in the repo:
- Authored issues: https://github.com/jupyter/docker-stacks/issues?q=author%3Aconsideratio
- Authored PRs: https://github.com/jupyter/docker-stacks/pulls?q=author%3Aconsideratio

**Comment by parente** [comment]
The approach we’ve taken with other contributors has been to grant triage rights for a while and then maintainer. 

Given that @consideRatio is already a [**prolific** contributor to numerous other Jupyter projects](https://github.com/consideRatio), I’m OK with bypassing the triage trial period and granting maintainer rights here from the start. 

That said, I think @romainx and @mathbunnyru should make the call as the current, active maintainers and as folks who went through the totally-made-up-but-more-formal onboarding process. 😁

**Comment by romainx** [comment]
I have never seen so many notifications in a week since contributing here, so we need help to merge 😄. 
More seriously, I think @consideRatio knowledge of the Jupyter community and projects will be a great asset here in order to take the right decisions and move things forward in the same direction.
So the proposal is approved on my side ✅ and welcome @consideRatio 👋

**Comment by mathbunnyru** [comment]
If @consideRatio wants to help, I only support this decision. So let's give the maintainer rights.

**Comment by parente** [comment]
Done! Thanks @consideRatio .

**Comment by consideRatio** [comment]
Thank you for having me :heart:! @parente can I also get access to read the docs? I'm @consideratio there - I'd like to enable PR preview of the documentation.
