### ISSUE TITLE
Please, provide me with DockerHub access

### ISSUE THREAD

**Issue by mathbunnyru** [jupyter/docker-stacks#1309]
@parente I created an issue, to kindly ask you for additional permissions on DockerHub Read the Docs.
These permissions will sometimes make maintenance of this project much easier.

My username is `mathbunnyru` in both places.

**Comment by parente** [comment]
@mathbunnyru I’ve added you to the jupyter-docker-stacks project on readthedocs.org as well as all the translation projects.

**Comment by mathbunnyru** [comment]
Thanks, working great1

**Comment by mathbunnyru** [comment]
Could you please add me to DockerHub as well?

**Comment by parente** [comment]
XRef: https://github.com/jupyter/docker-stacks/issues/1347#issuecomment-855457154

We're at our free org limit of users. It appears we have 10+ users in the jupyter org on Docker Hub while the UI says we have 3 max on the free plan. 🤷

**Comment by mathbunnyru** [comment]
@parente do you know who is responsible for the dockerhub jupyter org?
There is a Open Source Community Application for Docker Hub.
https://www.docker.com/community/open-source/application
https://www.docker.com/blog/expanded-support-for-open-source-software-projects/

I think jupyter org could ask for benefits from Docker Hub.

**Comment by parente** [comment]
Most of the Jupyter Steering Council members are listed as owners of the Docker Hub jupyter org. I can have a look at the application.

**Comment by mathbunnyru** [comment]
> Most of the Jupyter Steering Council members are listed as owners of the Docker Hub jupyter org. I can have a look at the application.

Thanks!

**Comment by mathbunnyru** [comment]
@parente any update on this?

I've been doing a lot of maintenance for these images for the past couple of months and it would be nice to have DockerHub access.

**Comment by parente** [comment]
I submitted the Docker form but haven't heard anything back from Docker. The message at submit time said that wait times may be long because they have a lot of submissions.

**Comment by mathbunnyru** [comment]
> I submitted the Docker form but haven't heard anything back from Docker. The message at submit time said that wait times may be long because they have a lot of submissions.

Thanks!

**Comment by parente** [comment]
Thanks for being patient. I would give up my seat for you, but even that wouldn't help. We'd need to get the user count down from 10 or so to 3. I don't think that's tenable. 🙁

**Comment by mathbunnyru** [comment]
@parente @minrk @consideRatio now I think it should be possible to provide me with access.
Could you please take a look?

**Comment by minrk** [comment]
It still says we're limited to 3 seats on the org, so we can't invite more yet. Maybe we should contact them if that should have changed?

**Comment by mathbunnyru** [comment]
Thank you. I wrote an email with this question to the Docker team.

**Comment by consideRatio** [comment]
It seems we could possibly get 10 seats for the organizations. We currently have 17 users out of 3 seats in the jupyter organization so we need to remove 8 users at least. Because this is also a matter of security, just like access to the source code on github or released versions in PyPI I figure we should try reduce that and ask that users that have access enable 2FA on their hub.docker.com accounts as well.

**Comment by mathbunnyru** [comment]
@consideRatio could you please check if additional seats were allocated? :)

**Comment by consideRatio** [comment]
Sadly no =/ Still limited to 3. If we get ten, I'll work to revise the memberlist to fit you.

![image](https://user-images.githubusercontent.com/3837114/193570365-38ac6a27-08e8-4c8e-99ba-5bfd00e5c09d.png)

**Comment by mathbunnyru** [comment]
One and a half years later, I now have access 🎉 
I'm going to celebrate this one 😂 

I am closing this issue since it seems to be fully resolved for me.
