### ISSUE TITLE
Install pre-commit ci

### ISSUE THREAD

**Issue by mathbunnyru** [jupyter/docker-stacks#1316]
@parente I requested pre-commit ci installation for this repo.
It will automatically create PRs updating pre-commit hooks, so we will always have latest hooks.

http://pre-commit.ci

**Comment by parente** [comment]
@mathbunnyru I've added it. For reference, it required the following scopes:

- Read access to issues and metadata 
- Read and write access to code, commit statuses, pull requests, and workflows

**Comment by mathbunnyru** [comment]
Thanks, @parente !
