### ISSUE TITLE
Better documentation on how NB_UID, NB_GID, CHOWN_HOME work and how to use them properly

### ISSUE THREAD

**Issue by mathbunnyru** [jupyter/docker-stacks#1333]
We have quite a complicated setup using NB_UID, NB_GID, CHOWN_HOME so it's not obvious at all how to start using our docker images easily and in the correct way.

Some examples:
https://github.com/jupyter/docker-stacks/issues/1330

**Comment by jeffyjefflabs** [comment]
#1229 is related too, I think

**Comment by mathbunnyru** [comment]
Yes, you're right, thanks!

**Comment by rigzba21** [comment]
Hello! I'm interested in contributing to this issue.

**Comment by mathbunnyru** [comment]
@rigzba21 that's great!

I think, we have many issues with these variables.
First of all, you can try to solve the issue https://github.com/jupyter/docker-stacks/issues/1229.
It will definitely give you an understanding why we need these variables and how to use them.

After that, it would be great to search for issues (possibly closed), which also had troubles with these variables.

And then it would be great to understand how to improve our docs to make it easier for newcomers to use our docker stacks.

Sorry, that I don't know the exact steps to do, if someone has a better idea, feel free to post it here.

**Comment by rigzba21** [comment]
Great! I'll start by taking a look at https://github.com/jupyter/docker-stacks/issues/1229. Thank you for the advice for a starting point.

**Comment by jlphillipsphd** [comment]
#1465 is related

**Comment by masip85** [comment]
Hello

I had problems with this long ago:

https://github.com/jupyter/docker-stacks/issues/885

From that issue next one is linked:

https://github.com/jupyter/docker-stacks/issues/1077

**Comment by mathbunnyru** [comment]
Thanks for mentioning these issues @jlphillipsphd @masip85 !

@rigzba21 if you still have a desire to fix this problem, now you have many examples where it's not obvious how our docker images behave.

**Comment by rigzba21** [comment]
Hi all, thank you for the examples, this is helpful!

**Comment by rigzba21** [comment]
Linking https://github.com/jupyter/docker-stacks/issues/1497 here.

**Comment by mathbunnyru** [comment]
We have updated our docs and now we describe UID, GID and how to use them and how to troubleshoot common problems.

Configuration: https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html#user-related-configurations
Troubleshooting: https://jupyter-docker-stacks.readthedocs.io/en/latest/using/troubleshooting.html
