### ISSUE TITLE
how to add maven dependency in jupyter/pyspark-notebook

### ISSUE THREAD

**Issue by priamai** [jupyter/docker-stacks#1334]
**What docker image you are using?**

`jupyter/pyspark-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

Example: `docker run -it --rm -p 8888:8888 jupyter/pyspark-notebook:latest`

**What steps do you take once the container is running to reproduce the issue?**

I want to connect to a local docker instance via the hadoop connector

```
import random
import pyspark
import random
from pyspark.sql import SparkSession
from datetime import datetime
import pandas as pd

start = datetime.now()

ss = SparkSession.builder.config("spark.driver.memory", "8g").appName('ES').getOrCreate()

es_reader = (ss.read
    .format("org.elasticsearch.spark.sql")
    .option("inferSchema", "true")
    .option("es.read.field.as.array.include", "tags")
    .option("es.nodes","elasticsearch:9200")
    .option("es.net.https.auth.user","elastic")
)

sysmon_df = es_reader.load("test_index-*/")

end = datetime.now()
time_taken = end - start
print('Time: ',time_taken) 
ss.stop()
```

**What do you expect to happen?**

I would like to know how to add a maven dependency for the ES connector: https://www.elastic.co/guide/en/elasticsearch/hadoop/current/install.html

**What actually happens?**
The command fails because it is unable to find the JAR files:
` java.lang.ClassNotFoundException: Failed to find data source: org.elasticsearch.spark.sql
`

**Comment by romainx** [comment]
Hello,

You can declare jars through the property `spark.jars.packages` either by defining it at the creation of the Spark session. They will be downloaded dynamically.

```python
ss = (
    SparkSession.builder.appName("ES")
    .config("spark.driver.memory", "8g")
    .config(
        "spark.jars.packages",
        "org.elasticsearch:elasticsearch-spark-30_2.12:7.13.0"
    )
    .getOrCreate()
)
```

Or in the `spark-defaults.conf`. However, this has to be done by `root` (permission denied to `jovyan`) so it could be a good option if you intend to build your own image.

```bash
echo "spark.jars.packages org.elasticsearch:elasticsearch-spark-30_2.12:7.13.0" >> $SPARK_HOME/conf/spark-defaults.conf 
```

Best

**Comment by priamai** [comment]
That worked thanks!

**Comment by mathbunnyru** [comment]
@romainx how would you feel about adding your answer to the docs?
I think it might be useful for other people.

I reopened the issue only to not to forget about this suggestion - if you think it's not needed, please, tell me that and close this issue again.

**Comment by romainx** [comment]
Hello @mathbunnyru,

Yes you're right it could be helpful. I will take care of that. 
Good suggestion, thanks!
