### ISSUE TITLE
[base-notebook]Import of conda packages is not possible.

### ISSUE THREAD

**Issue by kwon14** [jupyter/docker-stacks#1337]
Hello.
I am using a very good program for your efforts.

I am using it as a base-notebook dockerfile as a jupyter-notebook.
By default, if you check the "conda list", you can see the packages installed with conda-forge.
However, quite a few packages cannot be imported.

ModuleNotFoundError: No module named'yaml' I get a message like this,
Is there a solution?

Some examples are zstd, reproc, and yaml packages that cannot be imported.
The pip package is imported normally.

Thank you for always.
Please give me a quick answer.

Thank you.

The environment is as follows.
---------------------------------
image : jupyter/base-notebook

start : docker run -p 8888:8888 jupyter/base-notebook:latest

**Comment by romainx** [comment]
Hello,

The package `yaml` you see in the list of package is in fact [a C package](https://github.com/conda-forge/yaml-feedstock) called [LibYAML](https://pyyaml.org/wiki/LibYAML) and shipped with the `conda` distribution.

If you want to use the YAML Python package you may use instead [PyYAML](https://github.com/yaml/pyyaml).

```bash
# install
conda install pyyaml
# use it
python -c "import yaml; print(yaml.__version__)"
# 5.4.1
```

Best
