### ISSUE TITLE
Change dockerhub password to personal access token

### ISSUE THREAD

**Issue by mathbunnyru** [jupyter/docker-stacks#1347]
I'm switching to docker/login-action in https://github.com/jupyter/docker-stacks/pull/1346 and there's an advice not to use passwords for authenticating.
https://github.com/marketplace/actions/docker-login#docker-hub
Our secret is called `secrets.DOCKERHUB_PASSWORD`, and there might be a chance, that it's a real password and not a token.
@parente please, change the name to `secrets.DOCKERHUB_TOKEN` and create a token.
I think this token only needs to be able to push the new images.

Unfortunately, I don't have the rights to change github secrets and I have no special rights on DockerHub at all.

**Comment by parente** [comment]
@mathbunnyru It’s definitely a personal access token, not a password. I’ll rotate it anyway for good measure.

Please let me know if mathbunnyru is also your username on Docker Hub and I’ll get you added to the “stacks” team there which has access to configure the image repositories. (cc: @romainx @consideRatio if interested)

**Comment by consideRatio** [comment]
@parente please do add me as well! I'm `consideratio` there as well.

**Comment by mathbunnyru** [comment]
> mathbunnyru

Yes, it's mathbunnyru!

**Comment by parente** [comment]
@mathbunnyru I've generated a new token and stored it in secret `DOCKERHUB_TOKEN` as you requested. I've left the old one enabled until you switch over.

@consideRatio I added you to the stacks team on Docker Hub. @mathbunnyru I was unable to add you because we're apparently at our free org member limit for the jupyter org. (@consideRatio was already in the org on another team.)

**Comment by mathbunnyru** [comment]
> @mathbunnyru I was unable to add you because we're apparently at our free org member limit for the jupyter org.

That's a bit unfortunate - I'm merging and changing a lot these days and it would be nice to have access if something goes wrong and we need a manual fix.
I have a separate issue where I ask for DockerHub access and I'll close this one (automatically) when the review will be merged.
https://github.com/jupyter/docker-stacks/issues/1309

**Comment by mathbunnyru** [comment]
> @mathbunnyru I've generated a new token and stored it in secret DOCKERHUB_TOKEN as you requested. I've left the old one enabled until you switch over.

Thank you @parente. As I said, I created a PR, which replace the old token with a new one (though this PR will only be actually checked when merged to master).

**Comment by mathbunnyru** [comment]
@parente everything works fine, please delete the old key.
