### ISSUE TITLE
Install pre-commit.ci in cookiecutter project

### ISSUE THREAD

**Issue by mathbunnyru** [jupyter/docker-stacks#1365]
**What docker images this feature is applicable to?**

Cookiecutter project

**What changes do you propose?**

Add pre-commit.ci

**How does this change will affect users?**

Faster CI + autoupdates for pre-commit hooks

**Comment by parente** [comment]
👍 It’s approved. I think one of the other admins got to it before I did.

**Comment by mathbunnyru** [comment]
Thanks. It works 👍 
A simple test that pre-commit is launched.
https://github.com/jupyter/cookiecutter-docker-stacks/pull/14
