### ISSUE TITLE
Consider adding openssh-client to all images containing git

### ISSUE THREAD

**Issue by weisdd** [jupyter/docker-stacks#1372]
**What docker images this feature is applicable to?**

All images derived from `jupyter/minimal-notebook`.

**What changes do you propose?**

I think pretty much everyone moves to git-over-ssh these days. It'd be great to have `openssh-client` included in all images, where git comes pre-installed (I think it's everything derived from minimal-notebook).
It's just around 4 MiB of extra packages.

**How does this change will affect users?**

In Kubernetes environment, it's normally not allowed to run containers as root, so the only way to install ssh is through conda, which is known for not being too fast. Plus, it's just inconvenient to install ssh upon every restart.
So, I'd say having ssh-client preinstalled would make docker-stacks more user-friendly out-of-the-box.

**Comment by consideRatio** [comment]
@weisdd is something like `git clone git@github.com:jupyterhub/jupyterhub` not possible without having `openssh-client` installed in the image?

**Comment by weisdd** [comment]
@consideRatio yep:
![image](https://user-images.githubusercontent.com/46579601/122602389-69d42e00-d07b-11eb-8985-62fc47e74f06.png)

**Comment by consideRatio** [comment]
@weisdd thanks for the clarification!

I support this feature request, I think this should be added at the same time we add `git` to the docker images - in the jupyter/minimal-notebook image.

**Comment by weisdd** [comment]
@consideRatio perfect :) Should be an easy change, I'll prepare a PR for that.
