### ISSUE TITLE
Refactor datascience-notebook to use scipy-notebook as base image

### ISSUE THREAD

**Issue by jakirkham** [jupyter/docker-stacks#139]
It looks like there is quite a bit shared in common between the `scipy-notebook` image and the `datascience-notebook` image. In fact, it appears the `datascience-notebook` image is just the `scipy-notebook` plus some more stuff. I wonder if it would make sense to refactor `datascience-notebook` to use `scipy-notebook` as its base image (`FROM`) instead. This would hopefully cut down build time, release time, disk usage, and maintenance burden. Though it could be that I am missing something.

**Comment by parente** [comment]
I haven't looked at the exact delta, but I agree. Especially since the scipy image is the second most popular download according to the dockerhub stats (https://gist.github.com/parente/316d5c242aeb484484c8) which means it's likely not going to be on our chopping block anytime soon.
