### ISSUE TITLE
NetworkX fails to be imported

### ISSUE THREAD

**Issue by migueltorrescosta** [jupyter/docker-stacks#1400]
**Image:**`jupyter/datascience-notebook`
**Docker command:** `docker run -it --rm -p 8888:8888 jupyter/all-spark-notebook:latest`
**Reproduction steps:**
1. Visit <http://localhost:8888>
2. Start a Python notebook
3. Run `import networkx as nx`

**What do you expect to happen:** Successful import
**What actually happens:** Error message due to invalid imports inside NetworkX. This problem has already been fixed on NetworkX's latest versions, so I believe upgrading the networkx version included in datascience-jupyter should suffice to fix this issue. NetworkX related issue: https://github.com/networkx/networkx/issues/4337

**Comment by mathbunnyru** [comment]
I have just checked and it seems to work well. I think, newer images will use newer versions on networkx and we hope we will not see this issue anymore.
