### ISSUE TITLE
Add .dockerignore to remove some files from docker build context

### ISSUE THREAD

**Issue by jakirkham** [jupyter/docker-stacks#142]
We should add a `.dockerignore` file to the root of the context to avoid issues with unrelated files busting the caching like READMEs, `.git`, etc.

**Comment by parente** [comment]
I thought COPY only considered the specific file being copied. From [the docs](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/):

> For the ADD and COPY instructions, the contents of the file(s) in the image are examined and a checksum is calculated for each file. The last-modified and last-accessed times of the file(s) are not considered in these checksums. During the cache lookup, the checksum is compared against the checksum in the existing images. If anything has changed in the file(s), such as the contents and metadata, then the cache is invalidated.

**Comment by jakirkham** [comment]
That was always my understanding, but the build adding the Travis CI badge to the README certainly suggests that this may not be how docker is working.

**Comment by parente** [comment]
For sure. Maybe checksum computes differently due to whitespace settings in git on travis?

**Comment by jakirkham** [comment]
Yeah, I was wondering if some Windows style newlines crept in or something. It is very strange that it should matter.
