### ISSUE TITLE
Track version changes in separate repository

### ISSUE THREAD

**Issue by maresb** [jupyter/docker-stacks#1428]
I'm very interested to see how #1378 works out. I hope that it makes maintenance easier. In this FR I'd like to address the issue of package versions no longer being explicitly tracked by proposing a first idea. I'm also interested in alternative ideas.

**What docker images this feature is applicable to?**

All.

**What changes do you propose?**

Create a new repository `jupyter/docker-stacks-versions`. Each commit to this repository corresponds to a build run of docker-stacks. Each commit updates several files with the current information. (Historical information is overwritten but naturally archived in the git history.)

* `docker-images.txt` is a list of the tags with hashes for each generated image.
* `environment-base-notebook.yaml`, … contain the result of the command `conda env export` for each image.
* Either several separate files or one larger file containing versions of the Ubuntu image, miniforge, and all other dependencies.

**How does this change will affect users?**

Users will be able to track changes in package versions between Docker images to assist in debugging dependency issues. In particular, users will be able to use the "blame" feature to see the last image in which a package version has changed.

**Comment by mathbunnyru** [comment]
@maresb what you're asking is already implemented using our wiki.
We create build manifest for each master branch run and the wiki is updated automatically.

https://github.com/jupyter/docker-stacks/wiki

Maybe, I missed something?
