### ISSUE TITLE
Updating the wiki page with build history in GitHub GUI truncates the index I think

### ISSUE THREAD

**Issue by consideRatio** [jupyter/docker-stacks#1429]
I wanted to update the [wiki page's](https://github.com/jupyter/docker-stacks/wiki) description to read like below, but I realize that the web based GUI to do so would truncate the auto-generated index. Also, that the index was already truncated by a previous edit like this I presume.

@mathbunnyru have you experience with updating that wiki page text before? Got recommendations?

```Markdown
Welcome! Please see https://jupyter-docker-stacks.readthedocs.io for help using, contributing to, and
maintaining the Jupyter Docker stacks images.

### Build History

This is an auto-generated index of information from the image building system. In this index you can find image tags, changed commits, and manifests that describes the image installed software versions.

Note that image tags like `python-3.9.6` will be updated just like the `latest` tag as long as Python 3.9.6 is being installed in the latest image builds. If you want to avoid a changing reference to an image, you should use a date tag.
```

**Comment by mathbunnyru** [comment]
Actually, wiki itself is a git repo, so you can clone it like this `git clone https://github.com/jupyter/docker-stacks.wiki`.

After that you can change it on your machine and make sure it is not truncated.

**Comment by mathbunnyru** [comment]
> Also, that the index was already truncated by a previous edit like this I presume.

Fixed, found my commit which truncated the wiki.

**Comment by mathbunnyru** [comment]
@consideRatio I also added some notes to prevent this in the future.
Please, take a look and if that looks well for you, please, close this issue.

**Comment by consideRatio** [comment]
@mathbunnyru deal!

I made your text a HTML comment instead, so if you press edit you will see it anyhow but it won't show for users that just browses the wiki.

![image](https://user-images.githubusercontent.com/3837114/128880575-b4e33d9c-0218-4c94-872e-b79fa7b37e96.png)
