### ISSUE TITLE
Base Image using EOL NodeJS v13

### ISSUE THREAD

**Issue by jovanni-hernandez** [jupyter/docker-stacks#1430]
**What docker image you are using?**

`jupyter/scipy-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

`docker run -it --rm -p 8888:8888 jupyter/all-spark-notebook:latest`

**What actually happens?**

The Base docker image is using an old version of NodeJS 13.13.0 that is no longer supported.

```bash
$ node --version
v13.13.0
```

This causes downstream affects for user's using custom JupyterLab Extensions. For example, I have a simple extension that adds an item to the main menu, requiring me to add @jupyterlab/mainmenu@3.1.3 to the package.json for my extension. This eventually brings in a dependency of postcss@8.3.6, which only works with the supported, LTS versions of NodeJS. 

```bash
$ npm ls postcss
└─┬ @jupyterlab/mainmenu@3.1.3
  └─┬ @jupyterlab/apputils@3.1.3
    └─┬ sanitize-html@2.3.3
      └── postcss@8.3.6
```
Thus, if I try to install my functioning extension into the current docker image, the following happens:

```bash
jovyan@a354132252f1:~$ jupyter labextension install jupyterlab_scheduler
Building jupyterlab assets (production, minimized)

An error occurred.
RuntimeError: npm dependencies failed to install
See the log file for details:  /tmp/jupyterlab-debug-mishsung.log

```
```bash
jovyan@a354132252f1:~$ cat /tmp/jupyterlab-debug-mishsung.log
[snip]
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error postcss@8.3.6: The engine "node" is incompatible with this module. Expected version "^10 || ^12 || >=14". Got "13.13.0"
error Found incompatible module.
[snip]
```

Newer LTS versions are available on Conda, but I was not successfully able to perform an in-place upgrade within the container.

**Comment by mathbunnyru** [comment]
Could you please update your docker image?

I have just checked the latest image and it's telling `v14.17.4`, which is quite new and supported.

<img width="829" alt="Снимок экрана 2021-08-10 в 17 04 17" src="https://user-images.githubusercontent.com/12270691/128881179-7673182d-a2b5-4d7e-b9da-0794684c1e98.png">

**Comment by jovanni-hernandez** [comment]
Really weird, I wonder if my computer had just cached the older image and wasn't honoring my pull of latest. After purging everything and repulling it definitely has v14.

Sorry for the wasted time!
