### ISSUE TITLE
How do I add jar while using scala shell ?

### ISSUE THREAD

**Issue by eromoe** [jupyter/docker-stacks#1432]
I know it only need add env  in pyspark , but there is no introduction tell how to add jar in scala

**Comment by Bidek56** [comment]
I think this question belongs to SO, not GH. 
This [link](https://stackoverflow.com/questions/34515598/apache-spark-shell-error-import-jars) should answer your question.

**Comment by eromoe** [comment]
Nope, it is here . Here is no document tell how to add jar while using jupyter/all-spark-notebook image .
It is easy to add jar when you directly run spark-shell which some parameters.

**Comment by Bidek56** [comment]
@eromoe Scala notebooks are no longer supported in this stack, if you need Scala support please use [almond](https://github.com/almond-sh/almond) Thx
