### ISSUE TITLE
Load configs in shell script before launching the notebook/lab 

### ISSUE THREAD

**Issue by MaisamMD** [jupyter/docker-stacks#1435]
Hi,

I am using the jupyter/base notebook to build a Docker image for my environment. I have some configurations in a shell script format (.sh file) that should be loaded before launching the notebook/lab. I normally do source the .sh file in the ~/.bashrc. It seems these configurations are not loaded when I start the docker container using the default start-notebook.sh CMD.
I need the ~/.bashrc ( or ~/.profile) to be loaded before starting the notebook in the default fashion. 
Any tip to fix this problem?

Cheers,
M.M.D

**Comment by mathbunnyru** [comment]
We have startup-hooks.
I haven't used them myself, but I think they might help you.

Could you please take a look?
https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html#startup-hooks
