### ISSUE TITLE
Type in Dockerfile affecting Arm64 builds?

### ISSUE THREAD

**Issue by consideRatio** [jupyter/docker-stacks#1436]
This looks like a typo, and that it shouldn't be `aarm64` but `aarch64`. But, why hasn't this failed earlier then? I note that the image is built and pushed to docker hub.

https://github.com/jupyter/docker-stacks/blob/70178b8e48d7825ceade6e2decf374bc3e792d90/base-notebook/Dockerfile#L103-L105

@holdenk what do you think about this?

**Comment by mathbunnyru** [comment]
I think I solved the mystery.

```
    export miniforge_arch && \
    if [ "$miniforge_arch" == "aarm64" ]; then \
      miniforge_arch="arm64"; \
    fi; \
    miniforge_installer="${miniforge_python}-${miniforge_version}-Linux-${miniforge_arch}.sh" && \
```

`uname -m` returns `aarch64`.
So, `if` condition is wrong.
But, fortunately for us, miniforge naming is already good, so we didn't need any replacements in the first place.

https://github.com/conda-forge/miniforge/releases/
For example, the file is called `Mambaforge-4.10.3-5-Linux-aarch64.sh`

**Comment by mathbunnyru** [comment]
I will fix this.
I will also add downloading the latest miniforge version, to make it follow our automatic updates principles.
