### ISSUE TITLE
Conflict between documentation on NB_USER envvar and start.sh script

### ISSUE THREAD

**Issue by twalcari** [jupyter/docker-stacks#1448]
Hi all,

In the [documentation](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html#docker-options) it is stated that when passing the NB_USER environment parameter, that you should also update the working directory for that docker container:

> -e NB_USER=jovyan - Instructs the startup script to change the default container username from jovyan to the provided value. Causes the script to rename the jovyan user home folder. For this option to take effect, you must run the container with --user root, **set the working directory -w /home/${NB_USER}** and set the environment variable -e CHOWN_HOME=yes (see below for detail). This feature is useful when mounting host volumes with specific home folder.

Indeed, when you don't do that, any `docker exec -ti <my_jupyter_container> <any command>` command fails because the working directory does not exist anymore.

However, by passing this working directory parameter, an empty folder is created by Docker, which conflicts with the following in [`start.sh`](https://github.com/jupyter/docker-stacks/blob/master/base-notebook/start.sh#L55):

```bash
        if [[ ! -e "/home/${NB_USER}" ]]; then
            echo "Copying home dir to /home/${NB_USER}"
            mkdir "/home/${NB_USER}"
            cp -R /home/jovyan "/home/${NB_USER}" || ln -s /home/jovyan "/home/${NB_USER}"
        fi
```

By not copying the files from `/home/jovyan` to `/home/${NB_USER}` things start to break (like jupyter lab extensions).

Any suggestions on how we can fix this? It should be possible to pass the working directory argument to docker, as this makes it possible to use `docker exec` on a docker-stacks container, but we also need to be careful for the case where `/home/${NB_USER}` is being mounted. Perhaps we should introduce an extra environment variable to specify whether the contents of `/home/jovyan` should be copied over when `/home/${NB_USER}` exists?

**Command to reproduce the issue:**
`docker run -it --rm -p 8888:8888 -e NB_USER=example -e CHOWN_HOME=yes -w /home/example jupyter/minimal-notebook:latest`

**What do I expect to happen:**
"Copying home dir to /home/${NB_USER}" should be outputted on the console

**What actually happens?**
This step is skipped because the home directory already exists because of the `-w` parameter passed into docker

**Comment by jlphillipsphd** [comment]
I usually install lab extensions globally, not locally, in images so they don't end up in /home/jovyan. This way, if the copy doesn't work, the extensions are still available.

**Comment by mathbunnyru** [comment]
I have run your command `docker run -it --rm -p 8888:8888 -e NB_USER=example -e CHOWN_HOME=yes -w /home/example jupyter/minimal-notebook:latest`

It gives me a warning: `WARNING: container must be started as root to change the desired user's name with NB_USER="example"!`

If I add `--user root`, I get:
```
Updated the jovyan user:
- username: jovyan       -> example
- home dir: /home/jovyan -> /home/example
Ensuring /home/example is owned by 1000:100
Running as example: jupyter lab
```
which seems to work.

So, I will close this issue and emphasize, that we need this issue to be implemented because people skip the warnings.
https://github.com/jupyter/docker-stacks/issues/1517
