### ISSUE TITLE
Missing IRkernel from r-notebook

### ISSUE THREAD

**Issue by aforsythe** [jupyter/docker-stacks#1450]
Hi! Thanks for using the Jupyter Docker Stacks.

Please answer the questions below to help us troubleshoot the problem. Please be as thorough as possible.

**What docker image you are using?**

Example: `jupyter/r-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

Example: `docker run -it --rm -p 8888:8888 jupyter/r-notebook:latest`

**What steps do you take once the container is running to reproduce the issue?**

Example:

1. Visit <http://localhost:8888>
2. Create new notebook
3. Choose kernel

**What do you expect to happen?**

Option to choose kernel should include `IRkernel`. 

**What actually happens?**

Only kernel available is `Python 3 (ipykernel)`

<img width="676" alt="Screen Shot 2021-08-31 at 12 39 16 PM" src="https://user-images.githubusercontent.com/309001/131575310-79afa113-e534-484c-8ae2-090669c5cb1e.png">

**Comment by mathbunnyru** [comment]
I checked - it works for me with latest image.
