### ISSUE TITLE
Pyspark notebook cannot recognize JAVA_HOME 

### ISSUE THREAD

**Issue by thuybt** [jupyter/docker-stacks#1459]
Thanks for using the Jupyter Docker Stacks.

Please answer the questions below to help us troubleshoot the problem. Please be as thorough as possible.

**What docker image you are using?**

jupyter/pyspark-notebook

**What complete docker command do you run to launch the container (omitting sensitive values)?**

helm upgrade --cleanup-on-fail \
  jupyterhub jupyterhub/jupyterhub \
  --namespace spark-jobs \
  --values config.yaml
My config.yaml file is as follow:
  singleuser:
    image:
      # You should replace the "latest" tag with a fixed version from:
      # https://hub.docker.com/r/jupyter/datascience-notebook/tags/
      # Inspect the Dockerfile at:
      # https://github.com/jupyter/docker-stacks/tree/HEAD/datascience-notebook/Dockerfile
      name: jupyterhub/pyspark-notebook
      tag: 0.0.1
  
    extraEnv:
      EDITOR: "vim"
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64

**What steps do you take once the container is running to reproduce the issue?**

1. Visit http://35.238.201.114:80
2. from pyspark.sql import SparkSession 

**What do you expect to happen?**

SparkSession sucessfully created 

**What actually happens?**

Error:  JAVA_HOME is not set 
![image](https://user-images.githubusercontent.com/59462501/132095481-7ea9aeb2-2854-448b-82d9-d4dc9a4b4b60.png)

**Comment by Bidek56** [comment]
Are you using K8s to run jupyter/pyspark-notebook? If so your issue is related to your Helm chart no this repo.
I would suggest checking SO for help with your charts.
jupyter/pyspark-notebook works just fine on K8s as long as the charts are configured correctly.

**Comment by mathbunnyru** [comment]
Closing this issue because of no response.
