### ISSUE TITLE
JupyterLab Git Extension

### ISSUE THREAD

**Issue by kslader8** [jupyter/docker-stacks#1464]
**What docker images this feature is applicable to?**
jupyter/scipy-notebook

**What changes do you propose?**
installing jupyterlab-git 
(mamba install jupyterlab-git)

**How does this change will affect users?**
It allows users to more easily collaborate (the main issue research teams I work on have with jupyterhub). I'm actually surprised that jupyterlab-git hasn't been absorbed into the default running of jupyter lab. It's a very wide value add and git is already installed in the minimal notebook.

The only downside is it isn't used by jupyter notebooks, but it's probably a good time to start incentivizing jupyter lab over jupyter notebooks.

**Comment by mathbunnyru** [comment]
@kslader8 could you please draft a PR?
And could you check how the size of the image changes after adding this package?

We try to minimize the image size, especially minimal-notebook(it makes sense to add this to minimal notebook, because git is also installed there as you said).

**Comment by mathbunnyru** [comment]
The author doesn't seem to be interested, so closing this issue.

**Comment by romeokienzler** [comment]
@mathbunnyru Can you please re-open?

Created PR #1895 

New size of image: 3.82 GB

**Comment by costa** [comment]
I'm sorry to report that as of today, this extension does not seem to work (I'm not sure any other extensions work because I need just this one).

I run JupyuterLab "locally" all-fresh with:
```docker-compose.yml
version: '2.1'
services:
  jupy:
    image: jupyter/scipy-notebook
    command: start-notebook.sh --IdentityProvider.token=''
```

If anyone can verify this and prove me wrong/right — or provide any other assistance, it will be greatly appreciated.

Thank you.

**Comment by mathbunnyru** [comment]
@costa unfortunately, I don't think this extension was adapted for JupyterLab 4.x, which is now used in our images.
The upstream issue:
https://github.com/jupyterlab/jupyterlab-git/issues/1245
If you can dedicate your time and help fixing the issue in the upstream project, that would be great.

If you want to use, you can either downgrade jupyterlab in an inherited image or use `jupyter/scipy-notebook:lab-3.6.3` (this image is not up-to-date though).

**Comment by costa** [comment]
@mathbunnyru Thank you, subscribed to the upstream issue (I hope the Jupyter team will be much more efficient fixing it than myself could be), `lab-3.6.3` seems to work for me.
