### ISSUE TITLE
Recent changes to start.sh (mkdir; cp -R instead of mv) makes use-case for NB_USER too narrow (breaks existing z2jh deployments)

### ISSUE THREAD

**Issue by jlphillipsphd** [jupyter/docker-stacks#1465]
**What docker image you are using?**

Example: `jupyter/minimal-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

I am running z2jh on k3s, and typically use NB_USER to change jovyan to a user id obtained from LDAP, AzureAD, or Github OAuth.

The relevant values.yaml would be:
```
singleuser:
  uid: 0
  cmd: start-notebook.sh
```
The environment variable NB_USER is set using a custom authenticator (see above) which then allows the user to utilize their username in the container rather than jovyan. I currently -do not- change NB_UID nor NB_GID since this requires chown -R of /opt/conda if the user would like to make any changes (these are, of course, ephemeral changes, but this is nice for users since they can simply restart their container if they make a mess of anything).

**What steps do you take once the container is running to reproduce the issue?**

Example:

1. Install jhub using the z2jh helm chart.
2. Log into the hub.
3. Container fails to start due to incorrect permissions on /home/${NB_USER}/.local

**What do you expect to happen?**

The old behavior of start.sh is anticipated: first it trys moving /home/jovyan to /home/${NB_USER}, which actually fails due to permissions, but then falls back to ln -s which symlinks /home/${NB_USER} to /home/jovyan and the container can then start up as usual.

**What actually happens?**

The start.sh script tries to make the directory `/home/${NB_USER}` and then `cp -R /home/jovyan` to `/home/${NB_USER}` (which actually results in the files actually residing in `/home/${NB_USER}/jovyan` which doesn't appear to be what is intended). However, the permissions of .local are being as set root instead of $NB_USER and so the permissions issue arises and causes the container to stop. I read through the new documentation, which does indicate that you should basically specify -three- other pieces of information: 1. CHOWN_HOME="yes", 2. CHOWN_HOME_OPTS="-R" (probably always going to be needed just based on the above behavior), and 3. set the -working directory- to /home/${NB_USER} << (this feature is probably hard to get using the helm chart right? maybe there is a way to set it in z2jh but I can't think of how to do that at the moment).

Something else that's confusing about the process (even if you use the CHOWN options, which also still result in the spurious 'jovyan' subdirectory in the user's home directory): the sequence is to make the home directory, copy jovyan over, and then fall back on the symlink if this fails... Since we are typically mounting a volume on /home/${NB_USER}, what exactly are we thinking would need to be carried over from /home/jovyan? I've been building off of the stacks for awhile and it seems that relying on anything useful being present in /home/jovyan is typically not a safe bet since a volume is usually mounted at that point right at the beginning (so any preexisting files there are effectively hidden from within the container).

I guess my main concern is: how can I get this method to fall back to the symlink? The symlink was a simple and effective solution, but now I can't get it to work due to the mkdir; cp -R combination ahead of it. Wasn't the existing mv operation a better choice anyway? It would pretty much always be faster, right? If it didn't succeed, why would a mkdir/cp succeed instead? The additional requirements for using CHOWN and setting the working directory also seem overly restrictive: can't we have a reasonable fallback (ln -s) instead - the files in /home/jovyan are being overlaid with a fresh volume anyway so it doesn't make sense to retain the files there as far as I can see... I understand there are other use-cases out there, but I imagine just about anyone setting NB_USER, NB_UID, NB_GID would be having trouble with the way start.sh behaves now, but maybe there is some other work-around? Currently, I am having to patch start.sh to get the symlink behavior back...

**Comment by twalcari** [comment]
The changes also broke things in our deployment. I've created a pull request with a fix wrt copying hidden files/directories, which I deployed locally and which has been running well for a couple of weeks on our side now. 

Lets hope for a quick merge!

**Comment by jlphillipsphd** [comment]
Thanks @twalcari for the potential fix, and @mathbunnyru for the quick merge!

This approach gets us farther along in a way, but introduces other issues (in a way):

1. If I -only- set NB_USER, then `/home/${NB_USER}` is getting created correctly and the container starts up. However, the mount point for the PVC using standard z2jh is `/home/jovyan`. As a result, none of the user's files are actually stored in the PVC, and are lost when the container restarts.
2. If I set NB_USER, NB_UID, and NB_GID, then I also need to add CHOWN_HOME='yes' and CHOWN_HOME_OPTS='-R' (following the documentation). This also allows the container to start up. However, the problem as the above still happens: all of the user's files are ephemeral.

The symlink worked before for the above cases because, even though the link is ephemeral since it's placed outside of `/home/jovyan`, it gets recreated on each restart of the container.

I guess the above might actually be the expected behavior though, and I probably just need to provide some additional configuration on my side to make sure the PVC is mounted at the new location on container startup now?

@twalcari is there something else you are setting to get the PVC to mount at the new location when the container starts up? Would you be willing to share an example of what you are using? The default PVC created by z2jh needs to be mounted at `/home/${NB_USER}` instead of `/home/jovyan` and I am unsure how to configure that in z2jh.

**Comment by jlphillipsphd** [comment]
OK, I found the solution for my deployments:
```
singleuser:
  storage:
    homeMountPath: /home/{username}
```
With this change to my values.yaml, I was able to essentially recreate the same user experience provided by my existing deployments.

One thing to note: the current solution doesn't appear to actually succeed in copying the files from `/home/jovyan` to `/home/${NB_USER}`. I don't see anything in the startup log to suggest that it failed, but none of the files/directories (the work subdirectory, for example) were present like I expected. This probably means that (before fixing the mount point) the mkdir was succeeding, the copy was failing, and then the symlink (fallback) would also fail because the directory already existed at that point. My change to the mount point for the PVC above now means that the mkdir will fail (since it already exists), the fallback to symlink then also fails, but the net effect is similar to what I expected from z2jh before: a clean home directory. I usually add custom hooks to populate those directories with files if needed.

**Comment by twalcari** [comment]
In our JupyterHub instance, we don't mount any external storage into the home directory of the user. We use clearly labeled paths (ex. `/project`), so that users know when they store something to a permanent location. Everything outside those paths is ephemeral by definition.

Our spawner only sets `NB_USER` and `NB_GID`. We don't set `CHOWN_HOME` or `CHOWN_HOME_OPTS`. 

Maybe you can investigate if it's possible to reintroduce the `ln -s` method without breaking the test case that @rigzba21 wrote in c5fe6a1f5fd958b85ef23e7e486501ff20d67118 ? I'm certain that some improvement to the `start.sh` script is possible, as #1448 is also causing issues at the moment.

_Small side remark_: I'm wary of mounting directly to `/home/jovyan` or `/home/${NB_USER}`, as it can introduce strange issues, especially when switching between the different Docker Stacks images.  Depending on which image that is being launched, other configuration files are present in the `/home/jovyan` folder.

**Comment by twalcari** [comment]
> One thing to note: the current solution doesn't appear to actually succeed in copying the files from `/home/jovyan` to `/home/${NB_USER}`. 

You've just encountered #1448 🙃

**Comment by jlphillipsphd** [comment]
Your side remark is interesting because the default storage setup for z2jh is a dynamic PVC mounted at `/home/jovyan`. I am not sure what the answer needs to be for the default, but since this **is** the default, it gives the impression that it's the expected way to do this. I agree with you that it can cause issues if you wanted to switch images: I haven't been doing so *so far* for my deployments, but it was something I have been considering. Thanks for the tip.
