### ISSUE TITLE
Cannot set password for jupyter server 

### ISSUE THREAD

**Issue by devas123** [jupyter/docker-stacks#1469]
**What docker image you are using?**

`jupyter/tensorflow-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

`docker run --rm -p 10000:8888 -e JUPYTER_ENABLE_LAB=yes -d jupyter/tensorflow-notebook `

**What steps do you take once the container is running to reproduce the issue?**

1. Visit http://localhost:10000
2. in the login window input token and set password (i used 123)
3. Open incognito window and visit http://localhost:10000
4. use password to login

**What do you expect to happen?**

I can login with the password that I set in step 2

**What actually happens?**

I get 'Invalid credentials'

**Comment by Bidek56** [comment]
Hmmm, this is probably a Hub bug since this repo does not make any jupyter_notebook_config.py changes.

**Comment by devas123** [comment]
in the logs I see that it creates the jupyter_serve_config.json in the workdid/.jupyter, and it appears to be in the container, but this takes no effect

**Comment by Bidek56** [comment]
Have you tried setting password in Jupyter Lab without the Docker container?
It maybe a Lab bug not a docker stack issue.

**Comment by mathbunnyru** [comment]
Thanks @Bidek56.

I will close this issue. Please, create an issue in the corresponding repo of discourse.

**Comment by devas123** [comment]
Just for the sake of history: the problem is not with the container. The jupyter server needs to be restarted for the changes to take effect. So for my problem I had to create an image from tensorflow-notebook, where I copied .jupyter dir with pre-configured files for the password into the home dir. It solved the problem

**Comment by mathbunnyru** [comment]
@devas123 there is a better way to do this

`command: "start-notebook.sh --NotebookApp.password='PASSWORD_SHA_TAG'"`

where you generate the sha tag from the password:
```
import IPython
IPython.lib.passwd()
```
