### ISSUE TITLE
Pytesting connection error

### ISSUE THREAD

**Issue by Data-drone** [jupyter/docker-stacks#1471]
**What docker image you are using?**

Example: `jupyter/base-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

`docker build -t base-notebook:latest ./base-notebook`

**What steps do you take once the container is running to reproduce the issue?**

`TEST_IMAGE=base-notebook:latest pytest -m "not info" --log-cli-level=INFO base-notebook/test`

**What do you expect to happen?**

All tests to get success

**What actually happens?**

I get a lot of:

```
WARNING  urllib3.connectionpool:connectionpool.py:744 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f36b9fae490>: Failed to establish a new connection: [Errno 111] Connection refused')': /
```

and also:

```
FAILED base-notebook/test/test_container_options.py::test_cli_args - requests.exceptions....
FAILED base-notebook/test/test_container_options.py::test_unsigned_ssl - requests.excepti...
FAILED base-notebook/test/test_start_container.py::test_start_notebook[env0-lab] - reques...
FAILED base-notebook/test/test_start_container.py::test_start_notebook[None-notebook] - r...
==
```

I have checked and I don't have any other containers running which might be blocking port 8888.

**Comment by mathbunnyru** [comment]
Hello, I think you're using the wrong commands:

1.

```
docker build --build-arg -t base-notebook:latest ./base-notebook
```
This doesn't work for me - it should probably be without `--build-arg`.

2.

```
TEST_IMAGE=base-notebook:latest pytest -m "not info" --log-cli-level=INFO base-notebook/test
```

I think it should be just `test` at the end like this:
```
TEST_IMAGE=base-notebook:latest pytest -m "not info" --log-cli-level=INFO test
```

It works this way as expected.

**Comment by Data-drone** [comment]
Oops yes pasted the wrong thing in but the error stands - updated the original post
