### ISSUE TITLE
Cannot install R's mosaic package on jupyter/datascience-notebook

### ISSUE THREAD

**Issue by nathancarter** [jupyter/docker-stacks#1481]
# Problem

**What is the problem?**

Attempting to install R's [mosaic package](https://github.com/ProjectMOSAIC/mosaic) (a common tool when using R in educational contexts) in the `jupyter/datascience-notebook` Docker image fails.

**What is the expected behavior?**

The R installation in the `jupyter/datascience-notebook` Docker image would be configured in such a way as to support installing arbitrary packages that can be installed on Ubuntu in general.

# Steps to reproduce:

## 1. Boot up the image and try to install mosaic, like so:

```
$ docker run -it --workdir /root --user root jupyter/datascience-notebook bash
(base) root@b042c0ac112e:/root# R

R version 4.1.1 (2021-08-10) -- "Kick Things"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-conda-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages('mosaic')
```

Result: The above fails because of this dependency chain: mosaic → leaflet → raster → terra.

## 2. Investigate why the build fails, like so:

```
> install.packages('terra')
* installing *source* package ‘terra’ ...
** package ‘terra’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: /opt/conda/bin/x86_64-conda-linux-gnu-cc
configure: CXX: /opt/conda/bin/x86_64-conda-linux-gnu-c++
checking for gdal-config... no
no
configure: error: gdal-config not found or not executable.
ERROR: configuration failed for package ‘terra’
* removing ‘/opt/conda/lib/R/library/terra’
```

This suggests that `gdal` is not installed correctly.

## 3. Try to install `gdal` for development, like so:

```
(base) root@b042c0ac112e:/root# apt-get update -y
(takes about 2 seconds, succeeds)
(base) root@b042c0ac112e:/root# apt-get install libgdal-dev
(installs many dependencies, eventually succeeds)
(base) root@b042c0ac112e:/root# gdal-config --version
3.0.4
(base) root@d2cecfa35796:/root# gdal-config --libs
-L/usr/lib -lgdal
```

That appears to have succeeded, but...

## 4. Note that installing terra still fails, like so:

```
(base) root@b042c0ac112e:/root# R
> install.packages('terra')
* installing *source* package ‘terra’ ...
** package ‘terra’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: /opt/conda/bin/x86_64-conda-linux-gnu-cc
configure: CXX: /opt/conda/bin/x86_64-conda-linux-gnu-c++
checking for gdal-config... /usr/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 3.0.4
checking GDAL version >= 2.0.1... yes
checking for x86_64-conda-linux-gnu-gcc... /opt/conda/bin/x86_64-conda-linux-gnu-cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /opt/conda/bin/x86_64-conda-linux-gnu-cc accepts -g... yes
checking for /opt/conda/bin/x86_64-conda-linux-gnu-cc option to accept ISO C89... none needed
checking how to run the C preprocessor... /opt/conda/bin/x86_64-conda-linux-gnu-cpp
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... no
checking GDAL: linking with --libs and --dep-libs... no
/opt/conda/bin/../lib/gcc/x86_64-conda-linux-gnu/9.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: warning: libarmadillo.so.9, needed by /usr/lib/libgdal.so, not found (try using -rpath or -rpath-link)
/opt/conda/bin/../lib/gcc/x86_64-conda-linux-gnu/9.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: warning: libpoppler.so.97, needed by /usr/lib/libgdal.so, not found (try using -rpath or -rpath-link)
```

...and literally thousands of other linker errors like the two shown at the end of that output.

The internet seems to think that the problem is the two lines before the linker errors, which show that GDAL is not set up correctly for linking.  (For example, see [this SO question](https://stackoverflow.com/questions/51897478/more-trouble-installing-rgdal-on-ubuntu-16-04) or [this GitHub issue](https://github.com/r-spatial/sf/issues/1209).  They suggest that conda/Anaconda may be the problem, and that I should uninstall it.  But of course, that is not an option, because that would remove the main purpose of having the `jupyter/datascience-notebook` Docker image in the first place, which is to have working R, Python, etc. in the container.

**Comment by mathbunnyru** [comment]
@nathancarter unfortunately, this seems to be an issue with upstream package(s).

I mean, if you can't have both `conda` and `terra`, the issue should be transferred either to conda (or maybe even corresponding `r` feedstock), or `terra` or maybe `gdal`.
I'm not really familiar with any of these packages, so I can't tell you which one of them is a good place to ask for help.

I'm sorry to say that, but this issue is out of the scope of this project and this is definitely an issue of the upstream packages, so I'm closing this issue.
