### ISSUE TITLE
Script `test_outdated.py` not working after replacing conda to mamba

### ISSUE THREAD

**Issue by gabrielmagno** [jupyter/docker-stacks#1482]
I tried running the `test/test_outdated.py` script to see packages to update, but it gives an error (reported below).
I tested reverting the commands in `test/helpers.py` from `mamba` to `conda`, and the scripts runs normally.

So I believe the error is related to the fact of the output of `mamba` being different from `conda`, so the parsing of the outputs should be different.

The easiest fix seems to be to reverting back the commands in `test/helpers.py` to `conda`.
But it would be good to update the scripts to properly parse mamba output.

**What docker image you are using?**

`jupyter/all-spark-notebook`, but I believe it affects all the images.

**What complete docker command do you run to launch the container (omitting sensitive values)?**

```
TEST_IMAGE="jupyter/all-spark-notebook" pytest test/test_outdated.py
```

**What steps do you take once the container is running to reproduce the issue?**

(irrelevant)

**What do you expect to happen?**

The script to run an show the packages with updates.

**What actually happens?**

The script failes with an error:
```
FAILED test/test_outdated.py::test_outdated_packages - AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by mathbunnyru** [comment]
Thanks for this issue.

Actually, I don't think `test_outdated.py` is actually useful for us anymore.
I mean, we don't pin versions of python packages at all.
It seems to work well - at least, we didn't have any failed builds and versions are updated in automatic way.

If you need this script for some reason, please, tell us why :)

**Comment by gabrielmagno** [comment]
Thank you very much @mathbunnyru !
The fix came quicker than I could even answer you :-)

I have created a private Dockerfile based on `all-spark-notebook`, which installs some extra conda packages, with explicit versioning. I do not create automatic updates, I release a new version once every 3 months, so I run the `test_outdated.py` to see what I could manually update. 

So, as you can see, this is mostly personal usage, don't need to bother so much about it. I realized just now that the Jupyter docker-stacks are not using explicit versioning anymore, so I might also update my project to do something similar.

Anyway, thank you again for the kind response and the quick fix 😊

**Comment by mathbunnyru** [comment]
But, be warned, when versions are automatic, it might end in non-latest versions sometimes, because version resolution is a difficult thing to do.
