### ISSUE TITLE
Remove translated webpages and the code to support it

### ISSUE THREAD

**Issue by mathbunnyru** [jupyter/docker-stacks#1489]
**What docker images this feature is applicable to?**

All

**What changes do you propose?**

Get rid of transifex and the translated websites

**How does this change will affect users?**

Right now, translation is done only for 1.77% of the project.
I haven't seen any demand to translate the project as well.
Translated versions of the webpage will be deleted and the code as well.

What I propose: wait for 2 months, if there is no negative feedback on deleting the existing translations, I will create a PR.

@consideRatio @parente @romainx what do you think?

**Comment by consideRatio** [comment]
That sounds good to me.

I perceive it as unrealistic to maintain those - and if they are unmaintained, the end users would be better off without them I think. I consider it a win/win for maintainers and end users at this point in time.

**Comment by mathbunnyru** [comment]
The wait is over. I will remove translations in a few days :)

**Comment by consideRatio** [comment]
/cc: @choldgraf as a reference regarding the challenge of maintaining translations in open source projects as discussed on twitter (https://twitter.com/choldgraf/status/1479640310447624193).

**Comment by romainx** [comment]
Ok for me, I could not say better 😄 
> I perceive it as unrealistic to maintain those - and if they are unmaintained, the end users would be better off without them I think. I consider it a win/win for maintainers and end users at this point in time.
