### ISSUE TITLE
Requirements to a bare singleuser image

### ISSUE THREAD

**Issue by TiemenSch** [jupyter/docker-stacks#1493]
What are the absolute minimal requirements for an image to be accepted as a "singleuser image" by JupyterHub?

I'm experimenting with trying to add different profiles to a JupyterHub instance that could use access to the same user volumes as the JupyterLab environment, but with frontends other than JupyterLab. That way I could let users change the "app" whilst sharing the centralized JupyterHub authentication and container management (e.g. user volumes, culling, etc.).

Let's assume I have some frontend running on "http://0.0.0.0:8080/" if I would start my container for a working example.

**Comment by manics** [comment]
It should be enough for the container to include `jupyterhub-singleuser` or equivalent:
https://github.com/jupyterhub/jupyterhub/blob/2.0.0rc2/singleuser/Dockerfile

**Comment by consideRatio** [comment]
> What are the absolute minimal requirements for an image to be accepted as a "singleuser image" by JupyterHub?

> It should be enough for the container to include jupyterhub-singleuser or equivalent:
https://github.com/jupyterhub/jupyterhub/blob/2.0.0rc2/singleuser/Dockerfile

I figure this is something we can close as a resolved question, it doesn't seem so relevant for this to be documented better in jupyter/docker-stacks project.
