### ISSUE TITLE
Getting help pages when using R

### ISSUE THREAD

**Issue by CholoTook** [jupyter/docker-stacks#1494]
Hi! Thanks for using the Jupyter Docker Stacks.

Please answer the questions below to help us troubleshoot the problem. Please be as thorough as possible.

**What docker image you are using?**
https://hub.docker.com/r/jupyter/r-notebook

**What complete docker command do you run to launch the container (omitting sensitive values)?**
`docker run --rm --name jupyter -p 49153:8888 -e JUPYTER_ENABLE_LAB=yes -v jupyter:/home/jovyan/work -d jupyter/r-notebook`

**What steps do you take once the container is running to reproduce the issue?**
Simply 'run' something like `?print` or `help(print)` in an R console (or code cell in a notebook running an R kernel).

Example:

1. Visit <http://localhost:49153>
2. Start an R notebook
3. Type `help(print)`

**What do you expect to happen?**
I want to see the help page for the given function, e.g. like this:
https://asciinema.org/a/ArAhm0ieaoUOml4DsJz29OnWT

**What actually happens?**
I get a big crufty error:

```
Warning message in seq_len(head.end.idx):
“first element used of 'length.out' argument”
ERROR while rich displaying an object: Error in seq_len(head.end.idx): argument must be coercible to non-negative integer

Traceback:
1. FUN(X[[i]], ...)
2. tryCatch(withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr)) 
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr)) 
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler), error = outer_handler)
3. tryCatchList(expr, classes, parentenv, handlers)
4. tryCatchOne(expr, names, parentenv, handlers[[1L]])
5. doTryCatch(return(expr), name, parentenv, handler)
6. withCallingHandlers({
 .     if (!mime %in% names(repr::mime2repr)) 
 .         stop("No repr_* for mimetype ", mime, " in repr::mime2repr")
 .     rpr <- repr::mime2repr[[mime]](obj)
 .     if (is.null(rpr)) 
 .         return(NULL)
 .     prepare_content(is.raw(rpr), rpr)
 . }, error = error_handler)
7. repr::mime2repr[[mime]](obj)
8. repr_html.help_files_with_topic(obj)
9. repr_help_files_with_topic_generic(obj, Rd2HTML)
```
Followed by what appears to be PostScript...
```
\inputencoding{utf8} \HeaderA{print}{Print Values}{print} \methaliasA{print.Dlist}{print}{print.Dlist} \methaliasA{print.factor}{print}{print.factor} \methaliasA{print.function}{print}{print.function} \methaliasA{print.listof}{print}{print.listof} \methaliasA{print.simple.list}{print}{print.simple.list} \methaliasA{print.table}{print}{print.table} \keyword{print}{print} %
\begin{Description}\relax
\code{print} prints its argument and returns it \emph{invisibly} (via
\code{\LinkA{invisible}{invisible}(x)}).  It is a generic function which means that
new printing methods can be easily added for new \code{\LinkA{class}{class}}es.
\end{Description}
%
\begin{Usage}
\begin{verbatim}

print(x, ...)

## S3 method for class 'factor'
print(x, quote = FALSE, max.levels = NULL,
      width = getOption("width"), ...)

## S3 method for class 'table'
print(x, digits = getOption("digits"), quote = FALSE,
      na.print = "", zero.print = "0",
      right = is.numeric(x) || is.complex(x),
      justify = "none", ...)

## S3 method for class 'function'
print(x, useSource = TRUE, ...)
\end{verbatim}
\end{Usage}
% 
...
```

I'm not sure if it's trying to render .ps or .pdf or whatever... A popup of the help (like I get with emacs) would be perfect :-D

Many thanks,
Dan.

**Comment by CholoTook** [comment]
There is a stack exchange question discussing this issue here:
https://bioinformatics.stackexchange.com/questions/17879/r-help-in-jupyter-notebook

**Comment by CholoTook** [comment]
> There is a stack exchange question discussing this issue here: https://bioinformatics.stackexchange.com/questions/17879/r-help-in-jupyter-notebook

Seems a fix is mentioned there!

https://github.com/IRkernel/repr/pull/144#event-5589475824
https://github.com/IRkernel/repr/issues/143

**Comment by mathbunnyru** [comment]
This fix seems to be merged, so closing this issue.

**Comment by CholoTook** [comment]
Yup, I can confirm it works as expected now.
