### ISSUE TITLE
ESS bindings for code cells in R?

### ISSUE THREAD

**Issue by CholoTook** [jupyter/docker-stacks#1495]
Hi! Thanks for using the Jupyter Docker Stacks.

Please see the [Suggesting a new feature](https://jupyter-docker-stacks.readthedocs.io/en/latest/contributing/features.html#suggesting-a-new-feature) section in the documentation for our preferred processes.

**What docker images this feature is applicable to?**
https://hub.docker.com/r/jupyter/r-notebook
(or any image that includes an R kernel)

**What changes do you propose?**
I'm used to writing R in emacs. There are a handful of super useful key-bindings that I've come to instictevly stab while writing R... if you type `blah_` literally, the underscore changes to ` <- ` so you would see `blah <- `.

**How does this change will affect users?**
Meh... Can I install my own custom key-bindings?

**Comment by mathbunnyru** [comment]
@CholoTook could you check this out?
Seems to be exactly what you need.

https://github.com/kpe/jupyterlab-emacskeys

I will also tag this as an upstream because this is definitely not the goal of this project to implement custom key-bindings and either jupyter/3rd-party extension should work here.

**Comment by mathbunnyru** [comment]
Closing this, because this won't be implemented as a part of this project.
And the extension seems to already exist.
