### ISSUE TITLE
Docker Hub automated builds and undesirable rebuilds

### ISSUE THREAD

**Issue by parente** [jupyter/docker-stacks#15]
I've been watching how the automated builds execute on Docker Hub as the number of branches and stacks have grown. With jupyter/minimal-notebook autobuild-on-push turned off, autobuilds for all other stacks turned on, and manual rebuilds of minimal triggering autobuild of all other stacks, there are numerous wasted rebuilds. For example:

- If minimal-notebook changes on git branch master, DH rebuilds latest from master, 3.2 from branch 3.2.x, and 4.0 from branch 4.0.x. The latter two should have been left alone.
- When the above builds complete successfully, **each one** triggers a rebuild of tag latest from master, tag 3.2 from branch 3.2.x, and tag 4.0 from branch 4.0.x for every other stack. That's `(# of branches)^2 x (# of stacks)` rebuilds when just one tagged image for each should have been touched.

This appears to be a fact of life on Docker Hub. We can cut down on the `branches^2` noise by removing the automated triggers from minimal-notebook to all the others if we remember to trigger each one manually every time minimal changes. But even this results in wasted builds. 

Worse, every rebuild potentially creates new image layer SHAs from different build machine which means poor users that decide to pull and pull again will wind up downloading the entire image over again, even if the layers are binary equivalent. Worse, differences may sneak in during undesirable rebuilds since we don't pin OS packages and lead to two equivalently tagged images having slightly different contents.

It appears this behavior is a fact of life with automated builds on DH which is unfortunate because they are more transparent than the build-and-push-yourself flavor. The only way I see around these problems completely is automating the builds more intelligently outside of DH using a third party service or rolling our own with a little GitHub listener.

**Comment by rgbkrk** [comment]
Not to mention the fact that builds race each other - if two builds are running for the same image, it's the last to complete that becomes the current version of the image.

**Comment by parente** [comment]
I was starting to toy with a Jenkins server out on a VM in the cloud that can listen for notifications from GitHub (there's a Jenkins service) and run a little custom script that checks:

* What branch is the change on?
* What folder(s) are the changes in?

Based on that info, it can build the tiny dependency graph of what needs to be rebuilt and pushed to Docker Hub.

**Comment by rgbkrk** [comment]
That or we split these out into separate repos.

On that same line, I do have something that may be aged by now for triggering actions based on Docker webhooks (https://github.com/rgbkrk/autodock)

**Comment by parente** [comment]
I thought about the split early on, but it still runs afoul of any change in a git repo (or base git repo) triggering a rebuild of every tagged Docker image based on that repo.

**Comment by parente** [comment]
Struck again. When the conda R package dependency updated to jupyter notebook, the 3.2 tagged image automatically rebuilt and upgraded to notebook 4.0 instead of 3.2.1. Can't win!

**Comment by rgbkrk** [comment]
le sigh. Sorry Peter! Perhaps we need to list all explicit dependencies, pinned, in an environment.yaml?

**Comment by parente** [comment]
Nothing to be sorry about. Just noting here that our own build system would have avoided this probably because we never would have touched the 3.2.1 image while fixing the 4.0.x one.

**Comment by parente** [comment]
Another finding: The description of the repo on Docker Hub comes from the last repo branch to upload its Dockerfile. Sometimes we get the 3.2.x README. Sometimes we get the 4.0.x README. Sometimes we get the master README. I've been fixing manually when anything but master shows up since master has the options for all versions / branches.

**Comment by rgbkrk** [comment]
Oh gosh. That's terrible.

**Comment by parente** [comment]
So I have Jenkins setup with a small Python script that rebuilds only the repositories affected by changes in a particular git branch and stack subfolder. I can hook github up to notify jenkins when changes are pushed here in order to trigger rebuilds. It needs a bit more testing, but no reason it can't work.

If we want to go down this path, we need to nuke the jupyte/minimal-notebook, jupyter/all-spark-notebook, etc.  automated build repos on Docker Hub first. Once we do that, we've lost the (brief) history so far, we're without ANY builds on Docker Hub until the new builds push, and there's really no easy undo button.

**Comment by parente** [comment]
No longer using Docker Hub to build as part of the work in #12. Docker caching now used to avoid wasted rebuilds.
