### ISSUE TITLE
Travis: Fix COPY command to not bust cache

### ISSUE THREAD

**Issue by jakirkham** [jupyter/docker-stacks#150]
This [`COPY`]( https://github.com/jupyter/docker-stacks/blob/630ceec2576a309ace2ebee1d766601a064bb0f3/minimal-notebook/Dockerfile#L93 ) command busts the cache every time on Travis CI. It would be nice to figure out why this is occurring on Travis CI and fix it. This is causing tests to run ~45min in length. Even simple changes that don't invalidate the builds at all like documentation changes suffer from this long build time.

**Comment by parente** [comment]
Here's a brain teaser. I went to do a new build. I noticed the build VM disk was nearly full. I did the following:

```
# get the latest code
git fetch origin
git reset --hard origin/master

# nuke all the existing images
service docker stop
rm -rf /var/lib/docker
service docker start

# build!
make release-all
```

Unlike on travis, the only step that broke cache was the actual change in the git diff from the last build. That's pretty surprising considering I was starting from a brand new docker store in `/var/lib/docker` and a brand new docker daemon process.

**Comment by jakirkham** [comment]
So, you mean the VM worked the way Travis should work. ;)

Yeah, I tried computing the SHA256 hash for the file being copied in this statement on Travis, the VM, and my Mac. The result was the same in all cases. Still confused.

**Comment by parente** [comment]
> So, you mean the VM worked the way Travis should work. ;)

Yes. Yes it did. :hurtrealbad:

**Comment by jakirkham** [comment]
Just as another interesting tidbit. The VM and Travis are both using the exact same version of docker.

**Comment by jakirkham** [comment]
Honestly, I think we should raise this issue with Travis. It looks like we have enough evidence at this point to suggest something weird is happening on Travis. Maybe they can let us inspect one of their VMs to figure out what is going wrong. As your last release went out, I am rebuilding master so we can use this as an example for them to look at.

**Comment by jakirkham** [comment]
Here is the corresponding issue on Travis' issue tracker. ( https://github.com/travis-ci/travis-ci/issues/5764 )

**Comment by parente** [comment]
I'm going to close this issue out because we were unable to determine what causes the docker cache invalidation on a VM graciously given to us by travis. If we start a new, strong push to deploy from a CI system, we can try to debug it again.
