### ISSUE TITLE
No more way to customize some parts of the generation of images

### ISSUE THREAD

**Issue by PuckCh** [jupyter/docker-stacks#1502]
Hello,

**What docker image you are using?**

We are creating custom images based on base-notebook with build like:

```bash
$ BASE_CONTAINER=ubuntu:focal-20211006@sha256:26c3bd3ae441c873a210200bcbb975ffd2bbf0c0841a4584f4476c8a5b8f3d99
$ NB_UID=1234
$ make build/base-notebook \
  ARGS="--build-arg BASE_CONTAINER=$BASE_CONTAINER --build-arg NB_UID=$NB_UID"
```

**What complete docker command do you run to launch the container (omitting sensitive values)?**

Not relevant here, the issue is on the build system, not running the standard images.

**What steps do you take once the container is running to reproduce the issue?**

In terminal of the image, do:
```bash
$ grep jovyan /etc/passwd
jovyan:x:1234:100::/home/jovyan:/bin/bash
$
```

**What do you expect to happen?**

answer should be having:
```
jovyan:x:1234:100::/home/jovyan:/bin/bash
```

**What actually happens?**

answer is:
```
jovyan:x:1000:100::/home/jovyan:/bin/bash
```

The problem was introduced in commit e8c614a7640406fb2775a4e37e729ff8a057286a (Simplify Makefile).
A way to fix is proposed in pull request #1501.

**Comment by mathbunnyru** [comment]
Fixed in https://github.com/jupyter/docker-stacks/pull/1501
