### ISSUE TITLE
proposal: support multiple bases image builds

### ISSUE THREAD

**Issue by ggaaooppeenngg** [jupyter/docker-stacks#1509]
**What docker images this feature is applicable to?**

From `jupyter/base-notebook` to the `jupyter/scipy-notebook`.

**What changes do you propose?**

Support multiple builds for some stable bases like (ubuntu20.04, cuda/10.2-cudnn7-runtime-ubuntu18.04,11.4.2-cudnn8-runtime-ubuntu20.04)x(python3.7,python3.8).  Provide these built images on the dockerhub, for example tag the scipy image as jupyter/scipy-notebook:cuda10.2-cudnn7-ubuntu18.04-python3.7.

**How does this change will affect users?**

This change mainly affects the image providers. Cloud providers maintain environments by docker images instead of conda environments. They need to build all the stable base images from scratch for example Pytorch1.10 with cuda10 and tensorflow 2.4.0 with cuda11.  Some packages are pinned to a specific python version. The built images will help to save the time for the whole cartesian product builds.

**Comment by consideRatio** [comment]
While it would be a relevant feature for some users, I think that is out of scope of what we are able to maintain reliably in this project.

Due to that, I'm quite clear in my mind that this is something we shouldn't go for.
