### ISSUE TITLE
R version in notebook kernel is different than R version specified in image tag on M1 Mac

### ISSUE THREAD

**Issue by juskaiser** [jupyter/docker-stacks#1536]
**What docker image you are using?**
`jupyter/r-notebook:r-4.1.1`

**What complete docker command do you run to launch the container (omitting sensitive values)?**
`docker run -p 8888:8888 jupyter/r-notebook:r-4.1.1`

Running on an Apple MacBook Pro Laptop:
- `OS: 12.0.1`
- `Chip: Apple M1 Pro`

Docker version:  `Docker Desktop 4.2.0 (70708)`

**To Replicate**
1.  Run `docker run -p 8888:8888 jupyter/r-notebook:r-4.1.1` from terminal.
2.  From within Jupiter in the running container, create a new terminal window. Run the command `R`:
 ```
R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: aarch64-conda-linux-gnu (64-bit)
...
```
3. Alternatively in an R-kernal notebook run the command `version`.
```
platform       aarch64-conda-linux-gnu     
arch           aarch64                     
os             linux-gnu                   
system         aarch64, linux-gnu          
status                                     
major          3                           
minor          6.3                         
year           2020                        
month          02                          
day            29                          
svn rev        77875                       
language       R                           
version.string R version 3.6.3 (2020-02-29)
nickname       Holding the Windsock  
```
**What do you expect to happen?**

I'm expecting that the version of R in the notebook kernel will be the same as the version of R specified in the image tag. In this case I am expecting the version of R in the notebook to be `4.1.1` because the `jupyter/r-notebook:r-4.1.1` image tag is being used.

**What actually happens?**

I am getting an older version of R (3.6.3), as shown in the output above. This is problematic because I'm unable to install any additional R libraries that require R 4.0 or greater.

**Comment by mathbunnyru** [comment]
@juskaiser the reason for this is explained in https://github.com/jupyter/docker-stacks/issues/1401

Unfortunately, there is no easy solution, but I hope one day our support for arm images will be much better than it is right now.
I will close this issue as a duplicate.
