### ISSUE TITLE
ci maintenance: queue workflows or jobs with new GitHub workflow `concurrency` option?

### ISSUE THREAD

**Issue by consideRatio** [jupyter/docker-stacks#1540]
I think this GitHub workflow thingy can be really useful. It makes two workflows being triggered not run in parallell if they are within the same group. This will make us queue workflows in sequence.

```yaml
concurrency: 
  group: ${{ github.head_ref }}
```

This can also be applied to specific jobs, but not steps within jobs. This makes it even more valuable if we manage to split apart our build workflow into multiple separate jobs and then merges them into a single later. By doing so, we can mark the job that does the push to github and could run into merge conflicts marked to belong to a specific concurrency group to ensure that never happens rather than marking the entire workflow with all steps that could happen cuncurrently.

**Comment by trallard** [comment]
Started experimenting with this as part of #1627  😉
