### ISSUE TITLE
Collaborative mode

### ISSUE THREAD

**Issue by tomron** [jupyter/docker-stacks#1541]
Following [collaborative mode](https://jupyterlab.readthedocs.io/en/stable/user/rtc.html) which was added to JupyterLab 3.1 I would like to run in a collaborative mode, i.e with `--collaborative`.

What would be the best way to do it?

**Comment by mathbunnyru** [comment]
We have NOTEBOOK_ARGS environment variable to be able to pass anything we want and not create specific options for everything.
Well, this variable is not documented at all (this is not good), but I think it should work perfectly well in your case.

https://github.com/jupyter/docker-stacks/blob/master/base-notebook/start-notebook.sh#L19

**Comment by adrienpacifico** [comment]
@mathbunnyru I have not been able to launch it with the `NOTEBOOK_ARGS` env variable. 
I tried : 
`docker run -it --network host -e JUPYTER_ENABLE_LAB=yes -e NOTEBOOK_ARGS="--collaborative"  jupyter/datascience-notebook:latest`

However, I made it work with :
`docker run --network host jupyter/datascience-notebook:latest start.sh jupyter lab --collaborative`

I think an `ENABLE_COLLABORATIVE` option would be nice to have (as it took me around 45 minutes to make it work).

**Comment by mathbunnyru** [comment]
@adrienpacifico it works for me well.
Could you please make `docker pull jupyter/datascience-notebook` and check it once again?

If we copy one useful flag, then we will have to copy each of them, which is not maintainable at all.

**Comment by adrienpacifico** [comment]
@mathbunnyru , thank you! I indeed forgot to pull the latest image. It works now.
