### ISSUE TITLE
Add a multi-architecture stack based on datascience-notebook without Julia

### ISSUE THREAD

**Issue by massongit** [jupyter/docker-stacks#1551]
**What docker images this feature is applicable to?**

`jupyter/datascience-notebook`

**What changes do you propose?**

Add a multi-architecture stack based on `jupyter/datascience-notebook` without Julia.

**How does this change will affect users?**

Users who do not use Julia will be able to use `jupyter/datascience-notebook` on M1 Mac and latest Docker Desktop for Mac.

**Comment by massongit** [comment]
https://github.com/jupyter/docker-stacks/issues/1549#issuecomment-1019451833
>I think it works now with Docker 4.4.2 🎉

So I close it.

**Comment by mathbunnyru** [comment]
Yes, amd64 image should work fine.
