### ISSUE TITLE
Broken link in docs [Community Stacks Section]

### ISSUE THREAD

**Issue by SauravMaheshkar** [jupyter/docker-stacks#1552]
In the [**Community Stacks Section**](https://jupyter-docker-stacks.readthedocs.io/en/latest/contributing/stacks.html#community-stacks) of the docs, in step 4, there's a link to **"list of community stacks"**

**What do you expect to happen?**

To be Redirected to a section/page where there are a list of community contributed stacks.

**What actually happens?**

I get the "This page doesn't exist" error.

**More Context**

This is the broken link https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.md#community-stacks.

But the section is actually present in the docs 

https://github.com/jupyter/docker-stacks/blob/ace92d3c5f3e619b4d9c33add1d745ba324ae72c/docs/using/selecting.md?plain=1#L212

**Comment by mathbunnyru** [comment]
I also saw this broken link, though markdown seems to be correct.
It might be sphinx bug or I don't understand something.

**Comment by romainx** [comment]
Hello @SauravMaheshkar,

Thanks to have reported this issue 👍.
I've just made a the PR #1564 to fix it.

Best.
