### ISSUE TITLE
sudo: account validation failure, is your account locked

### ISSUE THREAD

**Issue by uonxhou** [jupyter/docker-stacks#1556]
**What docker image you are using?**
jupyterhub/singleuser:1.3.0
I use this image as base image and add the following code in my Dockerfile.
```
From jupyterhub/singleuser:1.3.0

USER root
RUN echo dt_hdp_ops:x:50243:50243::/noexistent:/bin/false >> /etc/passwd && \
    echo PP_PAZ_TAHOE_DEV:x:57767: >> /etc/group && \
    echo PP_PAZ_HORTON_DEV:x:57768: >> /etc/group && \
    echo PP_PAZ_STAMPY_DEV:x:57769: >> /etc/group && \
    echo dt_hdp_ops:x:50243: >> /etc/group && \
    echo "%PP_PAZ_TAHOE_DEV ALL = (dt_hdp_ops) NOPASSWD:SETENV: /etl/LVS/dt_etldata6/dt_hdp_ops/distcp/chadoop"  >> /etc/sudoers.d/run_as_dt_hdp_ops && \
    echo "%PP_PAZ_HORTON_DEV ALL = (dt_hdp_ops) NOPASSWD:SETENV: /etl/LVS/dt_etldata6/dt_hdp_ops/distcp/chadoop"  >> /etc/sudoers.d/run_as_dt_hdp_ops && \
    echo "%PP_PAZ_STAMPY_DEV ALL = (dt_hdp_ops) NOPASSWD:SETENV: /etl/LVS/dt_etldata6/dt_hdp_ops/distcp/chadoop" >> /etc/sudoers.d/run_as_dt_hdp_ops
```

**What complete docker command do you run to launch the container (omitting sensitive values)?**
i use kubespawner to start the container which i built from the above dockerfile

**What steps do you take once the container is running to reproduce the issue?**
i execute the following command:
`sudo -Eu dt_hdp_ops  /etl/LVS/dt_etldata6/dt_hdp_ops/distcp/chadoop`

**What do you expect to happen?**
i want to execute /etl/LVS/dt_etldata6/dt_hdp_ops/distcp/chadoop successfully

**What actually happens?**
it encounted the error: `sudo: account validation failure, is your account locked.`

**Comment by uonxhou** [comment]
@mathbunnyru Cloud you please help there?

**Comment by mathbunnyru** [comment]
Sorry, @uonxhou I know nothing about `jupyterhub/singleuser`.
Maybe the issue should belong to the project which owns this image?
I can't see how our project is related.

**Comment by uonxhou** [comment]
Hi @mathbunnyru.Sorry to bother you again.
But i found the base of `jupyterhub/singleuser` is `jupyter/base-notebook` that you maintain.
The only thing this `jupyterhub/singleuser` accomplishes is pinning the jupyterhub version on top of base-notebook.
So I want to ask you for help, I have been stuck on this problem for many days.
![image](https://user-images.githubusercontent.com/48987742/147198772-9f63d602-2156-4707-bbf8-cd0aecb5a838.png)

**Comment by mathbunnyru** [comment]
Tried to build your example, I'm getting another error. Please, check, that you haven't missed anything.

```
sudo: unknown user: dt_hdp_ops
sudo: unable to initialize policy plugin
```

**Comment by mathbunnyru** [comment]
@uonxhou I will close this issue - didn't get a response from you.
Please, reopen, if you still have a problem and verify your example.
