### ISSUE TITLE
Add jdk-dependency to datascience-notebook.

### ISSUE THREAD

**Issue by DankoPenko** [jupyter/docker-stacks#1561]
Hi, could someone please help me how should i edit the Dockerfile for the datascience-notebook [https://github.com/jupyter/docker-stacks/blob/master/datascience-notebook/Dockerfile](url) so that it will also have java-11 installed?

**Comment by Bidek56** [comment]
Just copy these [lines](https://github.com/jupyter/docker-stacks/blob/11db461624b7b9f4e05e96d20a412da45a09839e/pyspark-notebook/Dockerfile#L25) from pyspark-notebook/Dockerfile

**Comment by romainx** [comment]
Thanks @Bidek56.
Nothing to add I'm closing the issue.
