### ISSUE TITLE
base-notebook: Failed to build for python 3.6

### ISSUE THREAD

**Issue by chengsh7** [jupyter/docker-stacks#1579]
**What docker image you are using?**
`jupyter/base-notebook`
branch: master
(Note: all the tags and releases are missing, so I am using the master branch)

**What complete docker command do you run to launch the container (omitting sensitive values)?**
```
docker build --compress --no-cache --build-arg PYTHON_VERSION=3.6 -t notebook36-base -f ./docker-stacks/base-notebook/Dockerfile ./docker-stacks/base-notebook/
```

**What steps do you take once the container is running to reproduce the issue?**
Hit error during docker build
```
+ rm Mambaforge-Linux-x86_64.sh
+ conda config --system --set auto_update_conda false
+ conda config --system --set show_channel_urls true
+ [[ 3.6 != \d\e\f\a\u\l\t ]]
+ mamba install --quiet --yes python=3.6
Encountered problems while solving:
  - package libmambapy-0.19.0-py39h8bfa403_0 requires python >=3.9,<3.10.0a0, but none of the providers can be installed

```

**What do you expect to happen?**
I should able to build the base-notebook image for python 3.6

**What actually happens?**
Failed to build the base-notebook image for python 3.6

**Comment by consideRatio** [comment]
It seems we require Python 3.9 which was a quite big step of lost support for Python versions, hmmm, can you reproduce this with Python 3.8 as well?

**Comment by mathbunnyru** [comment]
I have checked even this with python 3.7 and it seems to work.
Please, try to update your environment.

@chengsh7, unfortunately, we won't be able to support python 3.6, because, as it was mentioned by @consideRatio, it has reached EOL (I think it basically means that anyone can stop supporting python 3.6 code).
