### ISSUE TITLE
[Documentation] - content and wording enhancements

### ISSUE THREAD

**Issue by trallard** [jupyter/docker-stacks#1586]
Hey folks - I started working on #1071 but as I was re-familiarising myself with the docs I noticed some places where some wording might be updated to make it easier to follow. 

I am just opening this issue to give you a heads up that I will be opening a PR with some of these changes.

**Comment by trallard** [comment]
Asking for input: there are some instances in the docs where the word `whitelist` is used. I would be keen on replacing this with `welcome-list` or `allowlist` instead. 

Thoughts?

**Comment by mathbunnyru** [comment]
I see only one place, actually:
```docs/using/common.md
195:That directory is also whitelisted for use in `sudo` commands by the `start.sh` script.
```

If you want to, you can rewrite this, I don't mind merging it, so feel free to rewrite this - if it sounds nice and is understandable by other people, then I think it won't be a problem :)
