### ISSUE TITLE
The `help` command doesn't work in notebooks with the R interpreter

### ISSUE THREAD

**Issue by davidvandebunte** [jupyter/docker-stacks#1588]
**What docker image you are using?**

`jupyter/r-notebook` (and `jupyter/datascience-notebook`)

**What complete docker command do you run to launch the container (omitting sensitive values)?**

```bash
docker run --rm -it --entrypoint /bin/bash jupyter/datascience-notebook
```

**What steps do you take once the container is running to reproduce the issue?**

1. `R` (to start the R interpreter)
2. Any `help` command

In detail:
```
(base) jovyan@dd0b1bd0a300:~$ R

R version 4.1.2 (2021-11-01) -- "Bird Hippie"
...
Type 'q()' to quit R.

> help(demo)
/opt/conda/lib/R/bin/pager: 11: exec: less: not found
Warning message:
error in running command
```

**What do you expect to happen?**

The `help` for the command to display in my terminal.

**What actually happens?**

The command crashes, see above.

My fix for the last year or so has been to install the `less` system package in my own images. Could it be installed upstream?

**Comment by mathbunnyru** [comment]
Yes, I think it's perfectly fine to add `less` to our image to make help work in `R`.

I would suggest adding it to `minimal-notebook` with a comment.
Having a test for this would also be nice, probably.

Could you draft a PR, please?
