### ISSUE TITLE
[DOC] - Add FAQ

### ISSUE THREAD

**Issue by trallard** [jupyter/docker-stacks#1596]
Creating a new issue to make review - and follow through easier (Also I will be working on this 😉)

---

I think this is a good direction because we are frequently asked the same questions.

Several things are definitely worth adding in my opinion:
- why we do not add your favorite package :)
- issues we have with arm images and x86 also, related to our build process
- how to give root permissions to the user
- who `jovyan` is :)

I mean, these are the questions I saw quite frequently and it's not obvious how to answer them.
And, of course, it's completely up to you which questions you would like to answer in this PR.

_Originally posted by @mathbunnyru in https://github.com/jupyter/docker-stacks/issues/1589#issuecomment-1026713366_

**Comment by mathbunnyru** [comment]
@consideRatio @maresb @romainx @trallard feel free to add new frequently asked question to the list.
