### ISSUE TITLE
Tensorflow without CUDA

### ISSUE THREAD

**Issue by elferherrera** [jupyter/docker-stacks#1616]
Hi! Thanks for using the Jupyter Docker Stacks.

Please answer the questions below to help us troubleshoot the problem. Please be as thorough as possible.

**What docker image you are using?**

`jupyter/tensorflow-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

`docker run -it --rm jupyter/tensorflow-notebook /bin/bash`

**What steps do you take once the container is running to reproduce the issue?**

Example:

1. conda list

**What do you expect to happen?**

To see Tensorflow with cuda build

In order to get a cuda enabled tensorflow I have to install the package again with `conda install tensorflow-gpu`
These are the packages that change with the installation

```
  tensorflow                       2.7.0-cpu_py39h4655687_0 --> 2.7.0-cuda112py39h01bd6f0_0
  tensorflow-base                  2.7.0-cpu_py39hf4995fd_0 --> 2.7.0-cuda112py39hd98b2dd_0
  tensorflow-estima~               2.7.0-cpu_py39ha241409_0 --> 2.7.0-cuda112py39h23446aa_0
```

Is it possible to get a docker image with the cuda version already installed?

**Comment by mathbunnyru** [comment]
@elferherrera so you solved the problem, right?
Could you please close the issue, if there is no bug in the stacks?
