### ISSUE TITLE
Start using issue forms

### ISSUE THREAD

**Issue by mathbunnyru** [jupyter/docker-stacks#1620]
Right now issue templates allow not to answer important questions while creating the issue.

Issue forms are well-structured and easier to use.
They have been in beta for a few months, so I think they are quite stable to use.

Docs:
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
News:
https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/

**Comment by trallard** [comment]
+1 from me - I have been using them regularly in other projects (also I can help if needed)

**Comment by mathbunnyru** [comment]
@trallard feel free to make a PR - I haven't done anything for this issue yet, so if you want to, please proceed 👍
