### ISSUE TITLE
Refactor tests to run on all applicable images

### ISSUE THREAD

**Issue by mathbunnyru** [jupyter/docker-stacks#1621]
Right now, it works like this:
- there is a test folder, which is run for every image
- image specific tests folder

What I propose:
If a test is run for some image, then it should run for all dependent images.
This way we will make sure, that some feature works in all the images it should work.
And we will be able to put our common tests to `/tests/base-notebook` and every image will run these tests automatically.

**Comment by trallard** [comment]
This sounds like a sensible proposal. 

> And we will be able to put our common tests to /tests/base-notebook and every image will run these tests automatically.

I would suggest instead something like `tests/images-common` or something similar. It will make it clearer that those tests are for all the images and not solely for the `base-notebook` thus preventing confusion in the future?

**Comment by mathbunnyru** [comment]
I already implemented this in my local repo, will draft a PR in the evening - please, take a look, I tried to improve the documentation, so it's more clear.
