### ISSUE TITLE
Add 'make' in the docker image

### ISSUE THREAD

**Issue by pprados** [jupyter/docker-stacks#1625]
Hi! Thanks for using the Jupyter Docker Stacks.

Please see the [Suggesting a new feature](https://jupyter-docker-stacks.readthedocs.io/en/latest/contributing/features.html#suggesting-a-new-feature) section in the documentation for our preferred processes.

**What docker images this feature is applicable to?**
make and Makefile is a classical build process. In the image version "python-3.8.8", the make is present, but not after.

**What changes do you propose?**

Add /usr/bin/make in jupyter/pyspark-notebook docker image.

**How does this change will affect users?**

Current user are not affected. But, after, it's possible to use this image to check pyspark or other projets in a CI, with a 'make' tools

**Comment by mathbunnyru** [comment]
Hello @pprados ! Thank you for your suggestion.

I don't actually think we should add `make` to our images.

It was probably present because it was either in `ubuntu:focal` image or was installed as a dependency of other package.
It doesn't make sense to add `Make` to `jupyter/pyspark-notebook` and not `base` or `minimal` image, because there is no particular reason for it to be restricted for this image.
But I don't think a lot of users use `make` inside the container to add it for all the users.

What I suggest is to create your own image based on our images and install `make` there.
This way you will make sure it's gonna stay in the image.

**Comment by miraculixx** [comment]
> But I don't think a lot of users use make inside the container to add it for all the users.

I would respectfully disagree with this assessment. Actually, make (along with Makefile) is part of many workflows.  

> It doesn't make sense to add Make to jupyter/pyspark-notebook and not base or minimal image, because there is no particular reason for it to be restricted for this image.

Yes, there is a particular reason it should be included in minimal, or at least in scipy-notebook. That is, jupyter/pyspark-notebook is based on scipy-notebook, which includes Cython. Cython requires build-essential (see [Cython installation instructions](https://cython.readthedocs.io/en/latest/src/quickstart/install.html). build-essential includes make.

> probably present because it was either in ubuntu:focal image

build-essential (and thus make) is not part of ubuntu:focal. I tried to trace where it was installed in scipy-notebook:python-3.8.8 to no avail. Perhaps related to the conda => mamba changes?

**Comment by mathbunnyru** [comment]
> Yes, there is a particular reason it should be included in minimal, or at least in scipy-notebook. That is, jupyter/pyspark-notebook is based on scipy-notebook, which includes Cython. Cython requires build-essential ([Cython installation instructions](https://cython.readthedocs.io/en/latest/src/quickstart/install.html)). build-essential includes make.

Oh, I see.
I confirm that this is a valid issue.
I have tried to use minimal example and it doesn't work.
https://cython.readthedocs.io/en/latest/src/tutorial/cython_tutorial.html#cython-hello-world

Let's add `build-essential` to `scipy-notebook` with an inline comment why we add it.
Also, it would be nice to have a test which shows cython works well.

@pprados @miraculixx could you draft a PR, please?

**Comment by mathbunnyru** [comment]
I found the place where I removed this.
https://github.com/jupyter/docker-stacks/pull/1383
