### ISSUE TITLE
[Proposal] - add @trallard to triaging team

### ISSUE THREAD

**Issue by trallard** [jupyter/docker-stacks#1628]
Hi all 👋🏽  

I am not sure if there is a triaging team for this repo - but if there is  would it be possible to be added to help y'all to deal with the issues/PR as they come in

**Comment by mathbunnyru** [comment]
Yes, there is!
Let's follow the same (unofficial) procedure which gave me triage rights a year ago :)

https://github.com/jupyter/docker-stacks/issues/1218

I definitely agree to give you triage rights for this repo - you were helping a lot lately with issues and PRs.
Thank you for that!
So 👍 from me.

I think it's okay to plan granting the permissions on February 22th (let's give other maintainer a week to reply).
Hope @consideRatio @romainx @parente share the same opinion.

**Comment by consideRatio** [comment]
Wieee @trallard :heart: :tada: :sunflower: thanks for investing time and effort to help this project in such a foundational way!!! :+1:

**Comment by mathbunnyru** [comment]
I think we can proceed here :)
I have some time today, so doing it one day earlier))

@trallard I've added you as a collaborator with triage rights. You should get an invite via email. Cheers!
