### ISSUE TITLE
A tool to inspect built images - could be helpful to our maintenance work!

### ISSUE THREAD

**Issue by consideRatio** [jupyter/docker-stacks#1636]
Today I learned about https://github.com/wagoodman/dive#readme by @yuvipanda, and I figure I'd open an issue here to spread knowledge about it and then close this issue after ~2 weeks (9th March).

>A tool for exploring a docker image, layer contents, and discovering ways to shrink the size of your Docker/OCI image.
>
>![](https://github.com/wagoodman/dive/blob/master/.data/demo.gif?raw=true)

**Comment by trallard** [comment]
I loooove dive 💜  it is one of my tools of choice when working with docker/OCI images

**Comment by mathbunnyru** [comment]
@consideRatio I'm closing this. Hope you don't mind :)
