### ISSUE TITLE
Add/fix Julia HDF5 support

### ISSUE THREAD

**Issue by jakirkham** [jupyter/docker-stacks#165]
As we are providing HDF5 and Python support for it (via h5py), we should also provide support for Julia. Namely we should install the Julia HDF5 package and make sure it links against conda's HDF5 library (if possible).

**Comment by mkolovic** [comment]
Ok I think I figured it out. The following will tell Julia where to find the HDF5 libraries installed via `conda`:
```
push!(Sys.DL_LOAD_PATH, "/opt/conda/lib")
```

After that all HDF5 issues seen in #157 are cleared up. Throwing this into `.juliarc.jl` in the datascience stack would be the optimal fix I believe. This was found [here](https://libraries.io/julia/HDF5). The Julia Github page documentation has the slightly different syntax of:
```
push!(Libdl.DL_LOAD_PATH, "/opt/local/lib")
```
Which failed for me with the message:
```
Libdl not defined
```
So perhaps that is for a newer Julia version.

**Comment by jakirkham** [comment]
Sounds good. Do you want to try a new PR?
