### ISSUE TITLE
[ENH] - Become a dockerhub verified publisher

### ISSUE THREAD

**Issue by tobias-jenkner** [jupyter/docker-stacks#1650]
### What docker image(s) is this feature applicable to?

all-spark-notebook, base-notebook, datascience-notebook, minimal-notebook, pyspark-notebook, r-notebook, scipy-notebook, tensorflow-notebook

### What changes are you proposing?

Become a dockerhub verified publisher: https://docs.docker.com/docker-hub/publish/

### How does this affect the user?

Images that are part of the dockerhub verified publisher program can also be consumed easily in AWS ECR: https://aws.amazon.com/blogs/containers/docker-official-images-now-available-on-amazon-elastic-container-registry-public/

### Anything else?

No thanks!

**Comment by consideRatio** [comment]
I think this requires us to pay DockerHub, doesn't it? If so, then I think we can't manage as its too much hurdle to manage payments for us.

**Comment by tobias-jenkner** [comment]
I thought that it will be free of cost for open source projects, but in fact I do not know that. 

I will look into it and see if there is this possibility for open source projects.

**Comment by tobias-jenkner** [comment]
> I will look into it and see if there is this possibility for open source projects.
I only found the docker open source program: 
- https://www.docker.com/community/open-source/application
- https://www.docker.com/blog/expanded-support-for-open-source-software-projects/
It is unclear for me, if participating in this program would also result in becoming a verified publisher.

**Comment by consideRatio** [comment]
@tobias-jenkner hmmm, I think those may be separate aspects. We have a free account and seem to get by with the limitation of the amount of image pulled from our repositories etc which is what the first application was about I think. I think after having done that, then, you can apply to be a verified publisher etc.

**Comment by mathbunnyru** [comment]
@consideRatio I think @parente submitted an application, but I'm not sure he received a response.
https://github.com/jupyter/docker-stacks/issues/1309#issuecomment-873209253

I think you have an access to the docker hub team (I don't have any docker permissions at all) , could you please submit an application for the open source program?
I also think it's a good starting point.

**Comment by mathbunnyru** [comment]
We would probably benefit from being verified publishers, because we will be much higher in the search queries :)

<img width="308" alt="Снимок экрана 2022-03-16 в 17 01 16" src="https://user-images.githubusercontent.com/12270691/158622799-0f686cdd-3511-43ab-b5cb-868533bf8a97.png">

**Comment by trallard** [comment]
🎉  it would be good if we could get on the OSS program

For the verified publisher programme this is what I found 
1. https://www.docker.com/partners/programs/
2. https://docs.docker.com/docker-hub/publish/#:~:text=The%20Docker%20Verified%20and%20Publisher,components%20to%20build%20new%20applications.

From the Data sheet in the first link - it seems the minimum charge is almost 10K USD. So I wonder if there is a way to get this waived through the OSS programme too?

**Comment by mathbunnyru** [comment]
I have arranged a meeting with Docker team.

The timeslot:
```
Wed, Jun 01
07:45 PM - 08:15 PM
GMT+03:00
```

This is the message from Jeff Hadfield, he is DVP specialist.

```
Hi Ayaz, 

Looking forward to connecting, please see the agenda below.

Agenda:

* Introductions
* Current Docker Usage
* Docker Business Overview
* Q&A
* Next Steps

Please feel free to add any additional items and invite anyone on the team you think this would be relevant to. 

Thanks, 
Jeff
```

@consideRatio could you join this meeting?
I should have asked you first before choosing timeslot, I'm sorry for my mistake.
I think this is a great opportunity to know about DVP program and if it would work well for `jupyter`.

**Comment by consideRatio** [comment]
@mathbunnyru sure I'll join, i've scheduled an entry for the meet in my calendar. If there is a video link or calendar entry already, you can invite me at erik@sundellopensource.se!

**Comment by mathbunnyru** [comment]
Great 👍 
I've sent you an invitation and an email with some details.

**Comment by mathbunnyru** [comment]
@consideRatio may I ask you, did you apply for the open source Docker program?
During our call in the beginning of June, I had an impression, that this was definitely a good thing to have for us.

**Comment by consideRatio** [comment]
@mathbunnyru thanks for the ping! An application has now been submitted for jupyter + jupyterhub in combination.

![image](https://user-images.githubusercontent.com/3837114/177039428-f17aa33c-7535-41ca-aa7b-961974934a2a.png)

**Comment by consideRatio** [comment]
Progress! The Jupyter organization on dockerhub and the JupyterHub organization on dockerhub got accepted into the program! I wrote about it in https://github.com/jupyterhub/team-compass/issues/559!

**Comment by mathbunnyru** [comment]
We joined Docker Open Source program. I don't think there is a plan to become a verified publisher though (it will require us to pay for).

**Comment by mathbunnyru** [comment]
Closing this as not planned
