### ISSUE TITLE
[FATAL tini (7)] exec start-notebook.sh failed: Permission denied

### ISSUE THREAD

**Issue by Nehc** [jupyter/docker-stacks#1667]
### What docker image(s) are you using?

base-notebook

### OS system and architecture running docker image

Ubuntu

### What Docker command are you running?

docker run -it -p 8888:8888 -v "${PWD}":/home/jovyan/content -e DOCKER_STACKS_JUPYTER_CMD=notebook jupyter/base-notebook

### How to Reproduce the problem?

I am just clone repo and build image whith docker build base-notebook --tag jupyter/base-notebook. 
I'ts builded OK. But it do not  run. When i pulled image from docker hub - all works! 
My goal is change PYTHON_VERSION on build...

### Actual behavior

[FATAL tini (7)] exec start-notebook.sh failed: Permission denied

**Comment by mathbunnyru** [comment]
Could you try to start the container without `-v "${PWD}":/home/jovyan/content`?
This looks like a permission issue.

**Comment by Nehc** [comment]
i am tried - the same error. (

The most annoying thing: base-notebook from docker hub works as expected. And from this repository - an error... (

It seems to me that this is quite elementary, but I'm a beginner, so I can't figure it out.

**Comment by Nehc** [comment]
removed all unnecessary/optional keys:

~$ docker run jupyter/base-notebook
[FATAL tini (7)] exec start-notebook.sh failed: Permission denied

error on build process. IMHO...

**Comment by Nehc** [comment]
This is very strange... I did a build on Windows 10 PC and push image to docker hub and it worked... (

Those. this means that it is on my ubuntu 20.04 that the build somehow goes wrong. ((

Maybe it has something to do with nvidia-docker or I did something wrong during installation.

**Comment by mathbunnyru** [comment]
> removed all unnecessary/optional keys:
> 
> ~$ docker run jupyter/base-notebook [FATAL tini (7)] exec start-notebook.sh failed: Permission denied
> 
> error on build process. IMHO...

Could you please clarify?

You say "docker run jupyter/base-notebook [FATAL tini (7)] exec start-notebook.sh failed: Permission denied" and "error on build process".
So, do you have an error during the image build?

**Comment by Nehc** [comment]
>>> So, do you have an error during the image build?

I'm not quite sure. Looks like no...

I just ran build on two different systems - on ubuntu 20.04 and on Windows 10. In both cases, the image was formed. Thats one on Win10 works, but on Ubuntu it gives the indicated error...After run...

As I said - I'm a beginner... Maybe there was some problem in the logs during the build process that I didn't notice... What should I pay attention to?

**Comment by Nehc** [comment]
I think I found the problem - it's my fault. (

I was copying files from a Win10 PC rather than spinning out a repo on the target machine. I guess it's just that the sh files lost their exec attributes...

When I did a clean git clone the whole procedure went as expected.
