### ISSUE TITLE
JetBrains All Products Pack licenses

### ISSUE THREAD

**Issue by mathbunnyru** [jupyter/docker-stacks#1669]
I started using PyCharm to develop this project.
I've asked JetBrains to provide us with licenses for Open Source Development (https://www.jetbrains.com/community/opensource/).

They kindly provided me with 3 licenses.
One of them I will use myself, so 2 are left :)

This message is from the email:
```
Main facts about your license(s):
• They are valid for one year. You will receive an automatic email reminder shortly before the license expiration date.
• They should be used for developing your non-commercial open source projects only.
• If you’ve received more than one license, please share them only with active contributors to your project.
```

@romainx @trallard @consideRatio if someone is interested in getting the license, please, ping me :)

**Comment by trallard** [comment]
Thanks for the offer but I am not a PyCharm user anymore 😅 so will let the others call dibs

**Comment by mathbunnyru** [comment]
Closing this issue - if someone is interested, please, ping me :)
