### ISSUE TITLE
Cannot open Scala Notebook

### ISSUE THREAD

**Issue by codingbutstillalive** [jupyter/docker-stacks#167]
Dear All,

I got the docker image running after "_docker pull jupyter/all-spark-notebook_", but when I access the jupyter notebook interface under localhost:8888, I only see options to create Python2/3, R, and Apache_Toree notebooks. However, I need to create a scala Notebook!

What did I likely miss here?

Best!

**Comment by codingbutstillalive** [comment]
Alright, now I see more clear. "Apache Toree" is for Scala and Spark! Alright then.

**Comment by parente** [comment]
Yea, the Spark Kernel which provided scala support moved to Apache under the name Toree recently. We should definitely update the README to reflect this.

**Comment by codingbutstillalive** [comment]
Yes, this is currently missing from the README file. That is why I was so
confused.

Best!
