### ISSUE TITLE
https access to notebook

### ISSUE THREAD

**Issue by codingbutstillalive** [jupyter/docker-stacks#168]
Dear All,

I use the following command line:

    docker run -d -p 8888:8888 -e PASSWORD="XXXX" -e USE_HTTPS=yes -v /home/user/work/:/home/jovyan/work jupyter/all-spark-notebook

My browser then tells me "Your connection is not secure!". I could create an exception and state that I am confident, but I want to know if I have to change anything else.

**Comment by jakirkham** [comment]
This is likely because the certificate is self-signed. Could you share a screenshot?

**Comment by codingbutstillalive** [comment]
Yes, exactly. It says/complains that it's a self-signed signature.

**Comment by jakirkham** [comment]
Yeah, we generate these on the fly inside the container. So, no one should have access to the cert unless they can get to your container.

I suppose we could think about a way to get this approved by an authority, which would be pretty tricky actually given containers are spun up and shutdown regularly and often quite quickly. However, this should be fine for you to use.

**Comment by codingbutstillalive** [comment]
Thank you very much for your kind and rapid reply!

Best!

**Comment by jakirkham** [comment]
Are you using this locally or remotely?

**Comment by codingbutstillalive** [comment]
I am using it locally. Via "localhost:8888" if that's what you mean!?

**Comment by jakirkham** [comment]
Yes. Just curious.

**Comment by parente** [comment]
There's a set of scripts in there for automating and using a certificate from the Lets Encrypt! effort (https://letsencrypt.org/) in the examples folder. Or, If you purchase your own cert from a CA, you can mount it into the container following the instructions in the README.

Otherwise, like @jakirkham said, if you're working locally, the self-signed cert is just fine.

**Comment by codingbutstillalive** [comment]
Great, thanks a lot!

**Comment by parente** [comment]
Looks like this is resolved. @codingbutstillalive feel free to open a new issue if you find other problems using the let's encrypt example
