### ISSUE TITLE
Single user server as driver node in spark cluster k8s

### ISSUE THREAD

**Issue by porscheme** [jupyter/docker-stacks#1682]
### What docker image(s) are you using?

pyspark-notebook

### OS system and architecture running docker image

Ubuntu/amd64

### What Docker command are you running?

JupyterHub single user server

### How to Reproduce the problem?

1. Setup a K8s cluster
2. Deploy Spark Cluster using bitnami/spark:3.0.0 container images for both master and worker nodes
3. Make sure both master and worker nodes are up and running
4. Deploy JupyterHub
5. Use jupyter/pyspark-notebook:ubuntu-20.04 container image for single user container
6. Use below spark code to make call
```
 import pyspark
 from pyspark.sql import SparkSession
 from pyspark.sql import SQLContext
 from pyspark import SparkConf, SparkContext

 conf = SparkConf()
 conf.setMaster("spark://spark-cluster-master-svc.studio.svc.cluster.local:7077")
 conf.setAppName("MyApp")
 conf.set('spark.driver.host', socket.gethostbyname(socket.gethostname()))
 conf.set('spark.executor.instances', '2') 
 sc = SparkContext(conf=conf)
rdd = sc.parallelize(range(0, 2))
rdd.sum()
sc.stop()
``` 

### Expected behavior

Call should succeed

### Actual behavior

Observed below Error
```
Python in worker has different version 3.8 than that in driver 3.9, 
 PySpark cannot run with different minor versions. Please check environment 
 variables PYSPARK_PYTHON and PYSPARK_DRIVER_PYTHON are correctly set.
```

### Anything else?

Below are the other container images tried for single user server
- pyspark-notebook:python-3.8.8
-- With this image, spark worker nodes are not bale to communicate status to the single user server

**Comment by porscheme** [comment]
Someone also filed a similar issue on bitnami/spark side also.
https://github.com/bitnami/bitnami-docker-spark/issues/73

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/single-user-server-as-driver-node-in-spark-cluster-k8s/13857/2

**Comment by porscheme** [comment]
> This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:
> 
> https://discourse.jupyter.org/t/single-user-server-as-driver-node-in-spark-cluster-k8s/13857/2

It was me who raised the issue on spark side also, hope to quickly resolve this issue.

**Comment by Bidek56** [comment]
Spark on K8s worked fine using pyspark-notebook images but I do recall changing the entrypoint on the worker image.

**Comment by porscheme** [comment]
I created a custom image, this worked for me. 

```
FROM jupyter/pyspark-notebook:ubuntu-20.04
USER root
RUN conda install -y python=3.8.8
USER 1000
WORKDIR /home/jovyan
```

**Comment by mathbunnyru** [comment]
My guess would be that you have to have compatible versions between your spark image and workers - and it should be true both for `python` and `spark`.

I'm glad that you found a solution which works for you, so I'm closing this issue.
