### ISSUE TITLE
[ENH] - Add a jupyter/minimal-notebook:python-3.10.x image

### ISSUE THREAD

**Issue by Croydon** [jupyter/docker-stacks#1688]
### What docker image(s) is this feature applicable to?

minimal-notebook

### What changes are you proposing?

I would like to see a `jupyter/minimal-notebook:python-3.10.x` image.

### How does this affect the user?

They can use a newer Python version

**Comment by Croydon** [comment]
Generally asked: Where are Python versions declared in this repository?

 The `jupyter/minimal-notebook:python-3.9.x` images are missing the latest patch versions too

**Comment by mathbunnyru** [comment]
Hi, @Croydon!

This is where python comes from:
https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile#L100

We install latest Miniforge3 and currently it comes with python 3.9.
https://github.com/conda-forge/miniforge#miniforge3

As soon as this project decides that python3.10 should be used by default, we will automatically start using python 3.10.

**Comment by maresb** [comment]
We have just removed Miniforge3 thanks to Micromamba, so unless something unexpected goes wrong in the coming days, we should be able to set the Python version ourselves now.

**Comment by mathbunnyru** [comment]
> The jupyter/minimal-notebook:python-3.9.x images are missing the latest patch versions too

This one is fixed automatically by using micromamba.

**Comment by Croydon** [comment]
Thanks everyone!
