### ISSUE TITLE
Is SPARK_OPTS really effective?

### ISSUE THREAD

**Issue by boechat107** [jupyter/docker-stacks#169]
I tried to set the JVM options by using `SPARK_OPTS`, but I didn't find any evidence of usage of this environment variable. To check the container's JVM options, I did a `cat /proc/JVM-PID/cmdline` inside the container and I got this:

> /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java-cp/home/jovyan/drivers/postgresql-9.4.1208.jre7.jar:/usr/local/spark/conf/:/usr/local/spark/lib/spark-assembly-1.6.0-hadoop2.6.0.jar:/usr/local/spark/lib/datanucleus-api-jdo-3.2.6.jar:/usr/local/spark/lib/datanucleus-core-3.2.10.jar:/usr/local/spark/lib/datanucleus-rdbms-3.2.9.jar**-Xms1g-Xmx1g**-XX:MaxPermSize=256morg.apache.spark.deploy.SparkSubmitpyspark-shell

Since we have `--driver-java-options=-Xmx4096M` in `SPARK_OPTS`, is this result expected?

After checking the file `/usr/local/spark/conf/spark-env.sh.template`, I used the variable `SPARK_DRIVER_MEMORY` and it did work as I expected.

**Comment by parente** [comment]
Are you trying to set the options from within a notebook or before container start? Which language / kernel are you using?

**Comment by DrPaulBrewer** [comment]
Part of my earlier issue, which I did not have time to file upstream, was
with env SPARK_OPTS getting clobbered in various places....

**Comment by boechat107** [comment]
I created another image based on `all-spark-notebook` and I set the environment variable like [here](https://github.com/boechat107/ext-spark-notebook/blob/master/Dockerfile#L34). Perhaps I have done something wrong... But the point is, the original variable sets the JVM memory to a value different from I what I found in the container.

**Comment by parente** [comment]
If you're using the Toree (Scala) kernel, #180 has the problem and pointer to when it'll be fixed. If you're using R and Python and still not seeing the settings take effect, let's keep chatting. :)

**Comment by parente** [comment]
Build tag [401575ede910](https://github.com/jupyter/docker-stacks/wiki/Docker-build-history) has the newest Toree which does not override SPARK_OPTS.

**Comment by parente** [comment]
Going to close this. If you're still experiencing problems with SPARK_OPTS, please reopen.
