### ISSUE TITLE
Connect to an external spark master

### ISSUE THREAD

**Issue by eualin** [jupyter/docker-stacks#170]
I would like to connect to an external spark master. According to the documentation, I have to create a file under `~/.ipython/kernels/scala/kernel.json` and then place the following content:
```
{
    "display_name": "Scala 2.10.4",
    "language": "scala",
    "env": {
        "SPARK_CONFIGURATION": "spark.master=spark://172.17.0.2:7077,spark.executor.memory=4g,spark.app.name=jupyter"
    }
}
```

Although I can now see the new kernel in the corresponding list (Kernel > Change kernel > Scala 2.10.4), a red button appears on the upper right side of the Jupyter (Kernel error), saying:

> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.5/site-packages/notebook/base/handlers.py", line 458, in wrapper
>     result = yield gen.maybe_future(method(self, *args, **kwargs))
>   File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
>     value = future.result()
>   File "/opt/conda/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
>     raise_exc_info(self._exc_info)
>   File "<string>", line 3, in raise_exc_info
>   File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
>     yielded = self.gen.throw(*exc_info)
>   File "/opt/conda/lib/python3.5/site-packages/notebook/services/sessions/handlers.py", line 58, in post
>     sm.create_session(path=path, kernel_name=kernel_name))
>   File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
>     value = future.result()
>   File "/opt/conda/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
>     raise_exc_info(self._exc_info)
>   File "<string>", line 3, in raise_exc_info
>   File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
>     yielded = self.gen.throw(*exc_info)
>   File "/opt/conda/lib/python3.5/site-packages/notebook/services/sessions/sessionmanager.py", line 73, in create_session
>     self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
>   File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
>     value = future.result()
>   File "/opt/conda/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
>     raise_exc_info(self._exc_info)
>   File "<string>", line 3, in raise_exc_info
>   File "/opt/conda/lib/python3.5/site-packages/tornado/gen.py", line 282, in wrapper
>     yielded = next(result)
>   File "/opt/conda/lib/python3.5/site-packages/notebook/services/kernels/kernelmanager.py", line 87, in start_kernel
>     super(MappingKernelManager, self).start_kernel(**kwargs)
>   File "/opt/conda/lib/python3.5/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
>     km.start_kernel(**kwargs)
>   File "/opt/conda/lib/python3.5/site-packages/jupyter_client/manager.py", line 243, in start_kernel
>     **kw)
>   File "/opt/conda/lib/python3.5/site-packages/jupyter_client/manager.py", line 189, in _launch_kernel
>     return launch_kernel(kernel_cmd, **kw)
>   File "/opt/conda/lib/python3.5/site-packages/jupyter_client/launcher.py", line 123, in launch_kernel
>     proc = Popen(cmd, **kwargs)
>   File "/opt/conda/lib/python3.5/subprocess.py", line 950, in __init__
>     restore_signals, start_new_session)
>   File "/opt/conda/lib/python3.5/subprocess.py", line 1441, in _execute_child
>     executable = args[0]
> IndexError: list index out of range
> 

Any ideas?

**Comment by parente** [comment]
@lbustelo @Lull3rskat3r Is this still the right way to config Toree? Also, if there's doc, we should point to it from the README in all-spark-notebook. I don't think there's much in there right now about how to configure the Toree/Spark kernel.

**Comment by lbustelo** [comment]
We are working on it. We have a defect at the moment.

**Comment by eualin** [comment]
Hi again, any news on this? (or a workaround, maybe?)

**Comment by lbustelo** [comment]
https://github.com/apache/incubator-toree/pull/11 Is the pr that contains the fix. After that we will need to update Pypi and put a pr here.

**Comment by lbustelo** [comment]
Here are a couple of notes on what to expect.

1. Toree by default is meant to connect to a preconfigured master. It does support a cmd flag to stop it from managing the SpackContext, but in this image, it is configured to manage.
2. Configuration of Toree is possible through the environment variable `SPARK_OPTS`. This variable takes all the cmd arguments that would be passed to [Spark submit](http://spark.apache.org/docs/latest/submitting-applications.html). This includes `--master=<master url>` to configure the Spark master.
3. After fixing the bug in Toree, you should be able to start the container as follow:
```
docker run <other docker options> -e SPARK_OPTS='--master <your master url>  ...' jupyter/all-spark-notebook
```

**Comment by parente** [comment]
> but in this image, it is configured to manage.

Is it possible to configure it to optionally not create the SparkContext automatically in the image here via an env var as well? If so, it would be consistent with the Python / R setup if people want to capture the config params in a notebook, but still leaves the option open to config on container startup like you said above.

**Comment by lbustelo** [comment]
Not as is. I would need to add that to Toree.

**Comment by eualin** [comment]
thank you @lbustelo ! when should I except the fix to be live? correct me if I am wrong, but once it is live, the only think I have to do is to use `-e SPARK_OPTS="--master spark://172.17.0.2:7077", right? also, touching file `~/.ipython/kernels/scala/kernel.json` is no longer required?

**Comment by lbustelo** [comment]
@eualin right... No need to edit the kernel.json. As for timeframe, I'm still finishing up another PR in Toree https://github.com/apache/incubator-toree/pull/15 and then I will put out the dev pip package.

**Comment by parente** [comment]
@lbustelo does dev6 have the fix for this?

**Comment by lbustelo** [comment]
Yes

Gino B.

**Comment by parente** [comment]
Build tag [401575ede910](https://github.com/jupyter/docker-stacks/wiki/Docker-build-history) has the newest Toree which does not override SPARK_OPTS.

I'm going to close this as fixed, but @eualin please reopen if you still hit problems.
