### ISSUE TITLE
[Discussion] - Adding jupyter/accessibility Docker image to org in DockerHub

### ISSUE THREAD

**Issue by trallard** [jupyter/docker-stacks#1707]
### What changes are you proposing?

Please note **I am not proposing a new docker-stack image** but something entirely different

A bit of context:
I am currently working on https://github.com/jupyter/accessibility and to move forward with some of the development work we have realised we need to create and maintain a set of Docker images.

I have been thinking about where these images should live - should I create a new org? or can I use the jupyter org since the Docker images fall under the jupyter umbrella?

Of course, I am not asking to incubate/add/maintain the images but only to be able to push the accessibility Docker images to `jupyter` in DockerHub
It also seems that there is no longer free tier for the Organisation in DockerHub 😢  

### How does this affect the user?

None - we would just have a set of accessibility-related images in `jupyter` and the folks in https://github.com/jupyter/accessibility will be maintaining it

### Anything else?

I could not create a maintainers issue (since I am not a maintainer 😓 )

**Comment by mathbunnyru** [comment]
Could you please tell the purpose of these images and what they will contain?

**Comment by mathbunnyru** [comment]
@trallard I'm waiting for your reply here ;)

**Comment by trallard** [comment]
Oops thanks for the ping @mathbunnyru 

Purpose: we are working on a series of tools to diagnose accessibility issues in JupyterLab, Retrolab and notebook. 
There are significant challenges to get the development environment right due to the mixture of JS and Python dependencies so a Docker image with all these prerequisites and the suitable confs will make the team and contributors workflow much smoother. 

You can see a preliminary version of the dockerfile here https://github.com/jupyter/accessibility/blob/main/testing/tools/Dockerfile

It contains JS and Python dependencies, JupyterLab and axe testing libraries as well

**Comment by mathbunnyru** [comment]
@trallard could you please tell me, if you're still interested in having the image on DockerHub?

**Comment by consideRatio** [comment]
There are options:
- ghcr.io/jupyter/...
- quay.io/jupyter/... (do we control this?)
- dockerhub's: jupyter/...

A plus with ghcr.io is that you manage permissions using github identities and we have good control of permissions etc, for example tied to permissions in a github repo.

Another aspect is findability, is this something we want to advertise from the image repository itself etc. ghcr.io exposes them differently with some pro/cons.

One can also publish to both locations.

**Comment by trallard** [comment]
I'd be happy to have it under ghcr.io/Jupyter since it's for the Jupyter/accessibility project it makes sense to live under a Jupyter owned registry rather than under the Quansight-labs one

**Comment by mathbunnyru** [comment]
@consideRatio I don't think I have permissions on GitHub to create packages under `jupyter` org. Could you please either give me the permissions or create the package yourself?

**Comment by consideRatio** [comment]
Me neither @mathbunnyru, but before we ask for help, I know the following information is relevant to figure out.

1. What image repositories should be created, and what should they be named? (`ghcr.io/jupyter/<name?>`)
2. Permission to work with these images, push/pull etc, will be coupled to a specific project and the permissions of people within that project. @trallard can you confirm that it makes sense that maintainers of https://github.com/jupyter/accessibility will get push rights to these images?
3. When working with images like this, the following is good to have in a Dockerfile to get permissions configured initially. @trallard can you add these two labels to the images you want to build and publish to the ghcr.io registry?

   Example [from dask/dask-gateway](https://github.com/dask/dask-gateway/blob/2c2bed23b83831ad073fdbae80647e96d2111d22/dask-gateway-server/Dockerfile#L11-L15)):

   ```Dockerfile
   # Set labels based on the Open Containers Initiative (OCI):
   # https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys
   #
   LABEL org.opencontainers.image.source="https://github.com/dask/dask-gateway"
   LABEL org.opencontainers.image.url="https://github.com/dask/dask-gateway/blob/HEAD/dask-gateway-server/Dockerfile"
   ```

Following this, we can ask a jupyter github org admin to do the steps similar to those outlined in https://github.com/dask/dask-gateway/issues/484#issuecomment-1079184335.

**Comment by mathbunnyru** [comment]
I would also suggest moving this issue from `jupyter/docker-stacks` to `jupyter/accessibility`, so people from the relevant project see the change before it's done.
I can't do that as well, unfortunately.

**Comment by consideRatio** [comment]
> Yes, push access to the maintainers of [jupyter/accessibility](https://github.com/orgs/jupyter/teams/accessibility/members) sounds good

While it may be possible to grant that team access, it is also possible to grant those with access to write to the github repository jupyter/accessibility - is that good?

> "to the images"

I got a bit confused about a single repository name (ghcr.io/jupyter/accessibility) combined with a mention of images in plural. Are there more than one Dockerfile, and where are the Dockerfile(s) located?

**Comment by trallard** [comment]
Sure that should be fine re the maintainers and access 

Re "images" sorry - I was typing fast between meetings. It is only one image so no need to worry.

**Comment by mathbunnyru** [comment]
> Following here:
> 
> 1. For our use `jupyter/accessibility` should be good enough.
> 2. Yes, push access to the maintainers of [jupyter/accessibility](https://github.com/orgs/jupyter/teams/accessibility/members) sounds good
> 3. 💯  we need to make some improvements to the images - will make sure to add those labels ASAP
> 
> @mathbunnyru I think only owners can transfer issues - I will open a corresponding issue in `jupyter/accessibility` and x-reference this one for visibility.

@trallard please, create a corresponding issue in the accessibility repo 😄

**Comment by mathbunnyru** [comment]
I guess this is no longer needed, so I'm closing this issue.
