### ISSUE TITLE
[BUG] - Container fails health check when using non-empty "base_url"

### ISSUE THREAD

**Issue by zbig-t** [jupyter/docker-stacks#1709]
### What docker image(s) are you using?

scipy-notebook

### OS system and architecture running docker image

VMware Photon OS/Linux/x86_64

### What Docker command are you running?

```
docker run -d --name jupyter-lab-1 \
	--restart unless-stopped \
	-p 8888:8888 \
	--user 1026 --group-add users \
	-v /mnt/docker-shared/jupyter-lab:/home/jovyan/work \
	-v /mnt/conf/jupyter-lab/.jupyter:/home/jovyan/.jupyter \
	jupyter/scipy-notebook:latest \
        start-notebook.sh --NotebookApp.base_url=/jupyter/
```

### How to Reproduce the problem?

Start a jupyter container with a non-empty `base_url` - either via `--NotebookApp.base_url` parameter in a `docker run` invocation or a `c.ServerApp.base_url` parameter in a bind-mounted `jupyter_server_config.py` file.

Do `docker ps`

### Command output

```bash session
docker ps
CONTAINER ID   IMAGE                                    COMMAND                  CREATED          STATUS                      PORTS                                                                                            NAMES
27e0b443b186   jupyter/scipy-notebook:latest            "tini -g -- start-no…"   20 minutes ago   Up 20 minutes (unhealthy)   0.0.0.0:8888->8888/tcp, :::8888->8888/tcp                                                        jupyter-lab-1
```

### Expected behavior

`docker ps` showing a healthy jupyterlab container.

### Actual behavior

`docker ps` showing status "unhealthy" when container is configured with custom `base_url`, unless `-e JUPYTERHUB_SERVICE_PREFIX=custom_prefix` is added explicitly during `docker run`.

**Comment by mathbunnyru** [comment]
Hello!
Unfortunately, we can't provide healthcheck, which works in all cases (it will be to much parsing of config files).
If you really need to have healthcheck, use `--health-cmd CUSTOM_COMMAND`, where you add this base_url to our healthcheck.
If you don't want it at all, use `--no-healthcheck`

**Comment by zbig-t** [comment]
Hello

Thank you for your response and clarification, @mathbunnyru. This is not a problem and I kind of suspected that rectifying this programmatically could require adding complexity.

**Comment by antofthy** [comment]
It would be better if this was mentioned in the docker-stacks guide.

**Comment by mathbunnyru** [comment]
> It would be better if this was mentioned in the docker-stacks guide.

Now we mention it: https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html?highlight=base_url#jupyter-server-options

**Comment by mathbunnyru** [comment]
@antofthy @zbig-t this is fixed now.
