### ISSUE TITLE
[ENH] - Really minimal container

### ISSUE THREAD

**Issue by mnp** [jupyter/docker-stacks#1710]
### What docker image(s) is this feature applicable to?

base-notebook

### What changes are you proposing?

The `jupyter/minimal-notebook` image is 1.5 Gb in size. It contains a full ubuntu which is some 300 packages including python 2.7. By comparison, the `python:3.9-slim` and friends are about 129 mb.

Proposal: 
 - Create an `jupyter/experimental-minimal` image based off one of the `python:xx-slim` images instead of Ubuntu. 
 - Add most of the same minimal-notebook appendages to arrive approximately at parity for `minimal-notebook` for most users.
 - Long term consider migrating experimental- to minimal- if that seems useful.

### How does this affect the user?

The difference between image sizes is significant resource usage.

**Comment by mathbunnyru** [comment]
Thank you for your proposal @mnp!

A few comments on your proposal:

> The jupyter/minimal-notebook image is 1.5 Gb in size. It contains a full ubuntu which is some 300 packages including python 2.7.

Does it really contain `python 2.7`?
I've checked that it doesn't in the aarch64 image.

> based off one of the python:xx-slim

I'm not sure we should base on `python` docker images.
This will give a wrong impression, that we depend or use system python binary/package.
I think it would be better to base on `debian-slim`.
And another option is to be based on `alpine` images.


Overall, I think this is a good way to have smaller images (which has many benefits for the end users).

**Comment by benz0li** [comment]
> And another option is to be based on `alpine` images.

See https://github.com/jupyter/docker-stacks/issues/1242#issuecomment-785647782 ff.

**Comment by mnp** [comment]
This is the conversation I was hoping to have.  So yes, 2.7, 3.8.2, and hundreds of other packages lab users don't need are in there. 

```
docker run --rm --entrypoint bash jupyter/minimal-notebook:latest -c 'dpkg -l|grep "ii  python"'
ii  python2                     2.7.17-2ubuntu4                   amd64        interactive high-level object-oriented language (Python2 version)
ii  python2-minimal             2.7.17-2ubuntu4                   amd64        minimal subset of the Python2 language
ii  python2.7                   2.7.18-1~20.04.1                  amd64        Interactive high-level object-oriented language (version 2.7)
ii  python2.7-minimal           2.7.18-1~20.04.1                  amd64        Minimal subset of the Python language (version 2.7)
ii  python3                     3.8.2-0ubuntu2                    amd64        interactive high-level object-oriented language (default python3 version)
ii  python3-minimal             3.8.2-0ubuntu2                    amd64        minimal subset of the Python language (default python3 version)
ii  python3.8                   3.8.10-0ubuntu1~20.04.4           amd64        Interactive high-level object-oriented language (version 3.8)
ii  python3.8-minimal           3.8.10-0ubuntu1~20.04.4           amd64        Minimal subset of the Python language (version 3.8)
```

Etc.

> I'm not sure we should base on python docker images.
> This will give a wrong impression, that we depend or use system python binary/package.

What's the requirement here?  I'm assuming whoever packaged the python image knows what they're doing. This wold also address @benz0li 's link, where it appears the Alpine base might be unstable.

**Comment by mathbunnyru** [comment]
Sorry, my bad, I was checking base-notebook image.
And it indeed doesn't contain python system packages.

My guess would be that most of the packages come from installing texlive.
https://github.com/jupyter/docker-stacks/blob/master/minimal-notebook/Dockerfile#L33-L35
It definitely comes from this `apt install` command.

So, I think the main issue is not just in the base image we use, but also the packages we install in minimal Dockerfile.

**Comment by benz0li** [comment]
@mnp See [debuerreotype-slimify](https://github.com/debuerreotype/debuerreotype/blob/master/scripts/debuerreotype-slimify) about the magic for `slim` variants.

> # Image Variants
> 
> ## `debian:<suite>-slim`
> 
> These tags are an experiment in providing a slimmer base (removing some extra files that are normally not necessary within containers, such as man pages and documentation), and are definitely subject to change.
>
> See the `debuerreotype-slimify` script (`debuerreotype` linked above) for more details about what gets removed during the "slimification" process.

– https://github.com/docker-library/docs/tree/master/debian

I find man pages handy.

**Comment by mnp** [comment]
@mathbunnyru @benz0li thank you for exploring options with me. I'm okay to close this ENH for now. If I make a slim image I'll post a PR to play with.

**Comment by benz0li** [comment]
@mnp See https://github.com/jupyter/docker-stacks/issues/1754 on removing `inkscape` [and `python2.7`].

---

`python3.8` is required by `texlive-xetex`. The latter together with

> `texlive-fonts-recommended` and `texlive-plain-generic` _could_ be replaced by a variation of [TinyTeX](https://yihui.org/tinytex/).

–  https://github.com/jupyter/docker-stacks/issues/1754#issuecomment-1195495919
