### ISSUE TITLE
[BUG] - ipywidgets in JupyterLab behaves different if installed in Dockerfile

### ISSUE THREAD

**Issue by fauxneticien** [jupyter/docker-stacks#1715]
### What docker image(s) are you using?

base-notebook

### OS system and architecture running docker image

macOS/aarch64 (Mac Mini) + BinderHub

### What Docker command are you running?

`docker build . -t jupyter/base-notebook:lab-3.4.2_ipywidgets` and then `docker run --rm -p 8888:8888 jupyter/base-notebook:lab-3.4.2_ipywidgets`

Dockerfiles:

I have tried both:
  
```Dockerfile
FROM jupyter/base-notebook:lab-3.4.2

RUN pip install ipywidgets
```

and, trying to solve it the same way as #1434, 

```Dockerfile
FROM jupyter/base-notebook:lab-3.4.2

RUN jupyter lab clean --all && \
    pip install --no-cache-dir --upgrade ipywidgets && \
    jupyter labextension install @jupyter-widgets/jupyterlab-manager
```

### How to Reproduce the problem?

Build Docker file, open a new Python 3 Console in JupyterLab then run:

```python
from tqdm.auto import tqdm
from time import sleep

for i in tqdm(range(3)):
    sleep(1)
```

Or use Binder: https://mybinder.org/v2/gh/parledoct/tutorials/binderhub?urlpath=lab, built from https://github.com/parledoct/tutorials/blob/binderhub/Dockerfile

### Expected behavior

If you launch a plain `jupyter/base-notebook:lab-3.4.2` without ipywidgets, tqdm prompts you to install `ipywidgets` but at least a progress bar displays. Then, once you install `ipywidgets`, there is no more warning and a progress bar displays.

<img width="1866" alt="Screen Shot 2022-05-28 at 12 27 30 PM" src="https://user-images.githubusercontent.com/9938298/170841175-021b6149-4474-4582-922a-ffc9d475d6d0.png">

Or see Binder: https://mybinder.org/v2/gh/fauxneticien/tqdm-jupyterlab/main?urlpath=lab, built from https://github.com/fauxneticien/tqdm-jupyterlab/blob/main/Dockerfile

### Actual behavior

If `ipywidgets` is installed in the Docker build (e.g. with `RUN pip install ipywidgets`) then tqdm progress bar does not appear, only `Loading widget...`

<img width="1866" alt="Screen Shot 2022-05-28 at 12 27 37 PM" src="https://user-images.githubusercontent.com/9938298/170841314-7aabbfd9-4fca-4ffb-9516-bd191bae109a.png">

### Anything else?

I can get a progress bar to appear if I use `from tqdm import tqdm` instead of `from tqdm.auto import tqdm` but that isn't an option because I originally came down this rabbit hole because `huggingface_hub` uses `from tqdm.auto import tqdm` in their code (https://github.com/huggingface/huggingface_hub/blob/main/src/huggingface_hub/file_download.py#L18). So when the progress bar doesn't show, I can't track how a multi-gigabyte file download is going...

**Comment by mathbunnyru** [comment]
I've noticed one thing:
When you do `docker build . -t jupyter/base-notebook:lab-3.4.2_ipywidgets`, you build base-notebook on your own and you end up with fresh build.

When you build image from this:
```
FROM jupyter/base-notebook:lab-3.4.2

RUN pip install ipywidgets
```
you're using a prebuilt image.

So the comparison is not truly fair.


I tried 2 things:

1. Used the freshly built image:
```
FROM jupyter/base-notebook:lab-3.4.2_ipywidgets

RUN pip install ipywidgets
```

2. Used your Dockerfile with our pre-built image.
```
FROM jupyter/base-notebook:lab-3.4.2

RUN pip install ipywidgets
```
When building this one, I added `--pull` to make sure I get the latest image tagged by `lab-3.4.2`.

In both cases, it worked for me.
So, no warnings and there is a progress bar in your example.

Could you try this out?

Also, I would like to notice, there is a big issue with aarch64 images, so it's better not to assume that images are tagged correctly.
https://github.com/jupyter/docker-stacks/issues/1401

**Comment by mathbunnyru** [comment]
You're using ipywidgets in jupyterlab console.
I don't think they are officially supported.
https://github.com/jupyter-widgets/ipywidgets/issues/2370

I have no idea though why they work when `!pip install` from the console itself.
As there is no support from the upstream, I think the best way for you is to switch to running your code in notebook, not in console.

I've checked and it works fine in notebooks.

**Comment by fauxneticien** [comment]
> You're using ipywidgets in jupyterlab console.
I don't think they are officially supported.
https://github.com/jupyter-widgets/ipywidgets/issues/2370

Oh, I see — sorry, then I didn't come across this issue. I'll close this one...

> I've checked and it works fine in notebooks.

Yep, same

> I have no idea though why they work when !pip install from the console itself.
As there is no support from the upstream, I think the best way for you is to switch to running your code in notebook, not in console.

Fair point. Indeed this makes jupyter lab far less appealing (as someone else has also noted...)

> [CommonClimate](https://github.com/CommonClimate) commented [on Dec 28, 2021](https://github.com/jupyter-widgets/ipywidgets/issues/2370#issuecomment-1002277523)
> > +1 for issue above. I generally think of JupyterLab as "all the things jupyter notebook does and more" but this issue rains on the jlab parade in a significant way.
