### ISSUE TITLE
[BUG] - permission denied error with datascience-notebook 

### ISSUE THREAD

**Issue by verdurin** [jupyter/docker-stacks#1723]
### What docker image(s) are you using?

datascience-notebook

### OS system and architecture running docker image

Fedora CoreOS 35

### What Docker command are you running?

Whatever is the default in Zero To JupyterHub version 1.2.0...

### How to Reproduce the problem?

1. Launch an R server using the `datascience-notebook` image
2. Try to run an R command e.g. `capabilities()`

### Expected behavior

R command is executed and output is shown

### Actual behavior

No output visible in the notebook and in the server logs there are errors:
```
[I 2022-06-13 15:48:33.536 SingleUserLabApp restarter:75] AsyncIOLoopKernelRestarter: restarting kernel (5/5), new random ports
[D 2022-06-13 15:48:33.547 SingleUserLabApp manager:386] Starting kernel: ['R', '--slave', '-e', 'IRkernel::main()', '--args', '/home/jovyan/.local/share/jupyter/runtime/kernel-928c71a4-9525-49a1-a3fd-792974bd24bf.json']
[D 2022-06-13 15:48:33.548 SingleUserLabApp connect:604] Connecting to: tcp://127.0.0.1:37933
OMP: Error #179: Function Can't open SHM2 failed:
OMP: System error #13: Permission denied
```

### Anything else?

Test R commands do work on this same JupyterHub installation using the `r-notebook` image.

**Comment by mathbunnyru** [comment]
Hello @verdurin!

Could you reproduce this without `Zero To JupyterHub`?
It will be much easier to debug.

**Comment by mathbunnyru** [comment]
@verdurin could you check it once again please with latest docker images? (you will have to do `docker pull`)
And if possible, try to reproduce without `Zero To JupyterHub`.

**Comment by mathbunnyru** [comment]
@verdurin we're waiting for you response here. Could you please take a look?

**Comment by mathbunnyru** [comment]
Closing this as no response was received. Please, reopen, if you still see this issue.
