### ISSUE TITLE
[ENH] - Add lxml to scipy base notebook for easy data scraping on html.

### ISSUE THREAD

**Issue by faultfactory** [jupyter/docker-stacks#1726]
### What docker image(s) is this feature applicable to?

scipy-notebook

### What changes are you proposing?

- Add lxml to scipy-notebook for easy data scraping on html.

### How does this affect the user?

There are built in methods that pandas has to capture all of the tables in a web page into dataframes.  It only requires the lxml package to operate. Beautiful soup is great for exploring a path but if you know where the up to date data exists on a website you can more easily capture it with the lxml package. There's nothing that i see in the current image that allows for use of the xpath to easily pull down block of information in html. lxml enables both the automated parsing of tables and the easier access to html elements.

**Comment by Bidek56** [comment]
@faultfactory I would suggest extending the Docker image for your needs. Adding special libs will make the images larger and we are trying to avoid making it too large.

**Comment by bjornjorgensen** [comment]
The lxml package is 6,9 mb! 
@faultfactory you can use 
`!pip install lxml`
in a cell to install this.

**Comment by faultfactory** [comment]
Will do. I was just putting in because Pandas asked for it when i had an error on a built-in function

**Comment by consideRatio** [comment]
My intuition is that this is too specialized need to be shipped by default in this image which needs to draw a line for some things to not be part of it for sustainable maintenance.

**Comment by mathbunnyru** [comment]
I also think that this is better to have in your custom image, rather than adding to all the images here.
I will close this issue.
@faultfactory ping us, if you need some help.
