### ISSUE TITLE
[BUG] - pip is not able to establish connection

### ISSUE THREAD

**Issue by TPME** [jupyter/docker-stacks#1728]
### What docker image(s) are you using?

tensorflow-notebook

### OS system and architecture running docker image

Windows 10

### What Docker command are you running?

docker-compose.yml:

```
version: "2"
services:
  jupyter:
    image: jupyter/tensorflow-notebook:latest
    container_name: "data-jupyter"
    ports:
      - 8888:8888
    environment:
      JUPYTER_TOKEN: "docker"
    volumes:
      - ".:/home/jovyan/work"
    restart: always
```

### How to Reproduce the problem?

1. Start the docker container
2. Open a new terminal
3. Type `pip install tensorflow-recommenders` (or in fact, anything on pip)
4. The following error takes place:

```
ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/1b/1d/4e996de5363cfbd1cd6adeab51bca6143af8ef16a8dcc4d7dc1bca3b0c38/tensorflow_recommenders-0.6.0-py3-none-any.whl (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ff4f96d59c0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
```

### Command output

```bash session
(base) jovyan@66534c0fdd4c:~/work/src/post_recommender_v1/notebooks$ pip install tensorflow-recommenders
Collecting tensorflow-recommenders
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ff4f96d4fd0>: Failed to establish a new connection: [Errno -5] No address associated with hostname')': /packages/1b/1d/4e996de5363cfbd1cd6adeab51bca6143af8ef16a8dcc4d7dc1bca3b0c38/tensorflow_recommenders-0.6.0-py3-none-any.whl
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ff4f96d52a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname')': /packages/1b/1d/4e996de5363cfbd1cd6adeab51bca6143af8ef16a8dcc4d7dc1bca3b0c38/tensorflow_recommenders-0.6.0-py3-none-any.whl
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ff4f96d5450>: Failed to establish a new connection: [Errno -5] No address associated with hostname')': /packages/1b/1d/4e996de5363cfbd1cd6adeab51bca6143af8ef16a8dcc4d7dc1bca3b0c38/tensorflow_recommenders-0.6.0-py3-none-any.whl
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ff4f96d5600>: Failed to establish a new connection: [Errno -5] No address associated with hostname')': /packages/1b/1d/4e996de5363cfbd1cd6adeab51bca6143af8ef16a8dcc4d7dc1bca3b0c38/tensorflow_recommenders-0.6.0-py3-none-any.whl
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ff4f96d5810>: Failed to establish a new connection: [Errno -5] No address associated with hostname')': /packages/1b/1d/4e996de5363cfbd1cd6adeab51bca6143af8ef16a8dcc4d7dc1bca3b0c38/tensorflow_recommenders-0.6.0-py3-none-any.whl
ERROR: Could not install packages due to an OSError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/1b/1d/4e996de5363cfbd1cd6adeab51bca6143af8ef16a8dcc4d7dc1bca3b0c38/tensorflow_recommenders-0.6.0-py3-none-any.whl (Caused by NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ff4f96d59c0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
```

### Expected behavior

It installs the file from pip.

### Actual behavior

It returns an error that the connection to the hostname cannot be made.

### Anything else?

I encounter this issue with every docker image from jupyter. Uninstalling and reinstalling the image, as well as docker itself, does not help.

Strangely enough, conda packages work fine to install. However, that is not a solution, since I need to install files not found on conda (but only pip).

**Comment by Bidek56** [comment]
This seems to be your Docker or OS setup, it works fine for me.

`docker run --rm -it -p 8888:8888 -v $(PWD):/home/jovyan/work jupyter/pyspark-notebook`

`(base) jovyan@5dbb8fb19832:~$ pip install tensorflow-recommenders
Collecting tensorflow-recommenders
  Downloading tensorflow_recommenders-0.6.0-py3-none-any.whl (85 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.8/85.8 kB 4.3 MB/s eta 0:00:00`

**Comment by mathbunnyru** [comment]
@TPME as @Bidek56 suggested, could you try to use `pip` on a host machine itself?
Are you able to access `files.pythonhosted.org`?

**Comment by TPME** [comment]
> This seems to be your Docker or OS setup, it works fine for me.
> 
> `docker run --rm -it -p 8888:8888 -v $(PWD):/home/jovyan/work jupyter/pyspark-notebook`
> 
> `(base) jovyan@5dbb8fb19832:~$ pip install tensorflow-recommenders Collecting tensorflow-recommenders Downloading tensorflow_recommenders-0.6.0-py3-none-any.whl (85 kB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.8/85.8 kB 4.3 MB/s eta 0:00:00`

Are you using Windows 10?

**Comment by TPME** [comment]
> @TPME as @Bidek56 suggested, could you try to use `pip` on a host machine itself? Are you able to access `files.pythonhosted.org`?

Hey, yes that works fine using e.g. the WSL shell.

**Comment by TPME** [comment]
Unfortunately, neither reinstalling Docker Desktop nor trying another image works. Really bummed here :-/

**Comment by TPME** [comment]
After some intense googling sessions I've determined the cause and fix for the issue.

*Cause*
The problem lies in a DNS issue relating to a specific Docker Desktop version (potentially multiple) and Windows 10, which has nothing to do with this repo. I've discovered someone has a similar problem here: https://forums.docker.com/t/docker-dns-not-responding-from-inside-a-container/103982/2 resp. here: https://github.com/moby/moby/issues/40864#issuecomment-621510915 which turned out to be the same one I have.

*Resolution*
I've fixed this by adding a `dns` block to my `docker-compose` file:

```
services:
  myservice:
    dns:
      - 8.8.8.8
```

Similarly, I was able to fix it by adding `--dns 8.8.8.8` to my `docker run` command.

**Comment by adolfoarmas** [comment]
If it is helpful;

after adding:

`services:`
`  myservice:`
`    dns:`
`      - 8.8.8.8`
 
To my docker-compose file as explained in the answer given before by @TPME, i had to:

`service docker stop`
`service docker start` 

After it, running the build command again.

It worked for me.

**Comment by adolfoarmas** [comment]
If it is helpful;

after adding:

`services:`
`  myservice:`
`    dns:`
`      - 8.8.8.8`
 
To my docker-compose file as explained in the answer given before by @TPME, i also had to:

`service docker stop`
`service docker start` 

After it, running the build command again.

It worked for me.

**Comment by matv864** [comment]
pip can't watch all dns servers
and in my case in "/etc/resolv.conf" I have
```
# Generated by NetworkManager
nameserver 192.168.19.169
nameserver 8.8.8.8
nameserver 8.8.4.4
```

All problems have solved after comment first line
