### ISSUE TITLE
[ENH] - Delta Image

### ISSUE THREAD

**Issue by lymedo** [jupyter/docker-stacks#1746]
### What docker image(s) is this feature applicable to?

all-spark-notebook

### What changes are you proposing?

Can we get an image with Delta included?

https://docs.delta.io/latest/quick-start.html

### How does this affect the user?

It would provide additional functionality.

**Comment by mathbunnyru** [comment]
@lymedo could you draft a PR for this feature?
I've seen a few people here wanting this package, so it might make sense to add it for everyone.
We will see the image size increase.
We even have the recipe to add this package: https://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html#enable-delta-lake-in-spark-notebooks

Also, I would suggest adding this package to `pyspark-notebook`, it makes more sense (and it will also end up `all-spark-notebook`).

**Comment by lymedo** [comment]
@mathbunnyru I'm afraid that I'm a newbie to docker so I'm probably not the right person to draft the PR.

Thanks for the link to the recipe. I have a go at build that image locally.

**Comment by bjornjorgensen** [comment]
Delta Lake doesn't have support for [Spark 3.3.0](https://docs.delta.io/latest/releases.html) now 

The best thing you can do is to use scipy-notebook then !pip install delta-spark

**Comment by lymedo** [comment]
I'd picked on on the Spark version for Delta so built the image using the following:

## Dockerfile
```
FROM jupyter/pyspark-notebook:spark-3.2.1

ARG DELTA_CORE_VERSION="1.2.1"
RUN pip install --quiet --no-cache-dir delta-spark==${DELTA_CORE_VERSION} && \
     fix-permissions "${HOME}" && \
     fix-permissions "${CONDA_DIR}"

USER root

RUN echo 'spark.sql.extensions io.delta.sql.DeltaSparkSessionExtension' >> "${SPARK_HOME}/conf/spark-defaults.conf" && \
    echo 'spark.sql.catalog.spark_catalog org.apache.spark.sql.delta.catalog.DeltaCatalog' >> "${SPARK_HOME}/conf/spark-defaults.conf"

USER ${NB_UID}
RUN echo "from pyspark.sql import SparkSession" > /tmp/init-delta.py && \
    echo "from delta import *" >> /tmp/init-delta.py && \
    echo "spark = configure_spark_with_delta_pip(SparkSession.builder).getOrCreate()" >> /tmp/init-delta.py && \
    python /tmp/init-delta.py && \
    rm /tmp/init-delta.py
```
    

## Notebook
```
from delta import *

from pyspark.sql import SparkSession

builder = SparkSession.builder.appName("Delta") \
    .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension") \
    .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog")

spark = configure_spark_with_delta_pip(builder).getOrCreate()
spark.getActiveSession()
```

```
data = spark.range(0, 5)
data.write.format("delta").save("test-table")
```

```
df = spark.read.format('delta').load('test-table')
df.show()
```

**Comment by mathbunnyru** [comment]
The PR was merged, waiting for a release.

**Comment by Bidek56** [comment]
Databricks [11.1](https://docs.databricks.com/release-notes/runtime/11.1.html) has support for Spark 3.3.0 and Delta Lake: 2.0.0 already with this [merge](https://github.com/delta-io/delta/commit/2d47ffdaa3f3f18804d1c2e7d8c0c4262b1564df).

**Comment by Bidek56** [comment]
DL [2.1](https://github.com/delta-io/delta/releases/tag/v2.1.0) has been released.
Do we need a PR to include it or it is upstream? Thx

**Comment by bjornjorgensen** [comment]
I do have some issues with the reason why jupyter lab docker images should add delta lake. When delta lake have their own [docker file](https://github.com/delta-io/delta/blob/master/Dockerfile)  and delta lake is only a storage layer. 
Can the best solution here be to make a docker-compose file where there are both a jupyterlab image and delta lake image?

**Comment by Bidek56** [comment]
1. Not sure what the purpose of Delta docker file is. It doesn't even install Delta library.
2. I think we need the Delta library as part of the Docker stack to read and write Delta lake tables, no?

**Comment by bjornjorgensen** [comment]
2. No. Its just like S3. https://docs.delta.io/latest/quick-start.html

**Comment by Bidek56** [comment]
Maybe I am missing something but S3 is a storage engine like Hadoop, where Delta.io is a storage format which is an extension of Parquet that can be written to S3, Hadoop, Azure Blo, etc... No??

P.s. I use delta.io on a daily basis.

**Comment by Bidek56** [comment]
Since we have a [recipe](https://github.com/Bidek56/docker-stacks/blob/main/docs/using/recipes.md#enable-delta-lake-in-spark-notebooks) for Delta.io already, I would probably agree that we can close this issue.

**Comment by mathbunnyru** [comment]
Initially, I thought many people would like to see this package to be already included in the image.
But it seems that it won't be easy to add it, because many people want to use latest spark versions (at least we get such PRs quite often) and delta is a bit slow in supporting latest versions.

I'm gonna close this issue. If we have many requests to add this package again, we should think about it.
