### ISSUE TITLE
[BUG] - Unable to connect to all-spark-notebook URL

### ISSUE THREAD

**Issue by KatlehoJordan** [jupyter/docker-stacks#1752]
### What docker image(s) are you using?

all-spark-notebook

### OS system and architecture running docker image

Windows 10 Home with WSL2

### What Docker command are you running?

As per the tutorial for the `all-spark-notebook` [here](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/running.html):
```
docker run -d -P --name notebook jupyter/all-spark-notebook
docker port notebook 8888
docker logs --tail 3 notebook
```

All outputs match those shown in the tutorial. However, if I try to copy and paste either of the URLs from the final logs to a browser, I hit an error:
```
This site can't be reached
127.0.0.1 refused to connect
Try:
  * Checking the connection
  * Checking the proxy and the firewall
ERR_CONNECTION_REFUSED
```

I saw the *Tokens are being rejected*  section in the [troubleshooting section](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/troubleshooting.html#), but I do not have any lingering Jupyter processes to kill.

### How to Reproduce the problem?

1. Run these commands from shell:
```
docker run -d -P --name notebook jupyter/all-spark-notebook
docker port notebook 8888
docker logs --tail 3 notebook
```

2. Navigate to the URL from the logs from the final `docker logs` output
3. Encounter a `This site can't be reached` error.

### Command output

```bash session
$ docker run -d -P --name notebook jupyter/all-spark-notebook
7fcd6e37712df902a398cf40fe6ee99e0e768b85ede19ed9dee6adb03d220da3

$ docker port notebook 8888
0.0.0.0:49154

docker logs --tail 3 notebook
    Or copy and paste one of these URLs:
        http://7fcd6e37712d:8888/lab?token=1bcecbe866ea6139aebd1fc85f1b2b4bff2e5b5fbf8cca3a
     or http://127.0.0.1:8888/lab?token=1bcecbe866ea6139aebd1fc85f1b2b4bff2e5b5fbf8cca3a

# Navigate to 
# http://127.0.0.1:8888/lab?token=1bcecbe866ea6139aebd1fc85f1b2b4bff2e5b5fbf8cca3a
# but can't reach site

# Check for lingering Jupyter processes to kill as per
# troubleshooting guide
$ ps aux | grep jupyter
# No output from previous command
```

### Expected behavior

When I navigate to http://127.0.0.1:8888/lab?token=1bcecbe866ea6139aebd1fc85f1b2b4bff2e5b5fbf8cca3a I expected to come to a Jupyter notebook.

### Actual behavior

When I navigate to http://127.0.0.1:8888/lab?token=1bcecbe866ea6139aebd1fc85f1b2b4bff2e5b5fbf8cca3a I encounter an error that the site can't be reached.

### Anything else?

I **am** able to successfully connect to jupyter if I build from the `jupyter/scipy-notebook`. However, if I try to access the url indicated from the logs after building the `jupyter/r-notebook` image, I hit the same error.

Since the `all-spark-notebook` image is based on the `jupyter/r-notebook` image, I suspect that the root cause for them is the same.

#### Hotfix

If I specify the ports for `all-spark-notebook` or the `r-notebook` as instructed for the `scipy-notebook`, then I am able to access the URLs. For example:

```
 docker run -d -p 8888:8888 --name notebook jupyter/all-spark-notebook
```

or

```
 docker run -d -p 8888:8888 --name r-notebook jupyter/r-notebook
```

Thus, I will close this issue. I do not know why the ports have to be specified exactly like this, and why the ports in the instructions do not work, but at least I have a working solution.

**Comment by skr3178** [comment]
docker run -d -p 8888:8888  worked
