### ISSUE TITLE
[ENH] - Remove inkscape

### ISSUE THREAD

**Issue by benz0li** [jupyter/docker-stacks#1754]
### What docker image(s) is this feature applicable to?

minimal-notebook

### What changes are you proposing?

Remove inkscape from `minimal-notebook`.

### How does this affect the user?

Smaller size; less dependencies.

Images based on `minimal-notebook` will profit, too.

### Anything else?

See also https://github.com/JuliaLang/IJulia.jl/pull/1038#issuecomment-1194523666 on how to configure `IPython` and `IRkernel`

> to output both `image/svg+xml` and `application/pdf` plot formats in the notebook file:
> 
> *  `image/svg+xml` for plot display in the browser
>     \+ HTML conversion using SVG instead of PNG
> *  `application/pdf` for direct PDF conversion
> 
> ℹ️ With `application/pdf` plot format in the notebook file, `inkscape` is not required for PDF conversion using `nbconvert`.

👉 I am asking for help @JuliaLang as I have not found solution for `IJulia` yet.

---

Possible side-effect of using `image/svg+xml` + `application/pdf` instead of `image/png`: See https://nbviewer.org/github/mgeier/python-audio/blob/master/plotting/matplotlib-inline-defaults.ipynb.

**Comment by Bidek56** [comment]
Do you think some users are expecting the PDF functionality in the `minimal-notebook`?

**Comment by benz0li** [comment]
ℹ️ The `minimal-notebook` currently contains three versions of `python`:

1.  `/opt/conda/bin/python3.10`
1.  `/usr/bin/python3.8`
    *  required by `texlive-xetex`
1.  `/usr/bin/python2.7`
    *  required by `inkscape`

👉 To further optimize the `minimal-notebook`, `texlive-xetex` _could_ be replaced by a variation of [TinyTeX](https://yihui.org/tinytex/).

**Comment by Bidek56** [comment]
@benz0li I would suggest creating a PR and see what the community reaction is to this change.

**Comment by Bidek56** [comment]
I would tag @parente on this PR since he added `inkscape` based on this [issue](https://github.com/jupyter/docker-stacks/issues/243).

**Comment by mathbunnyru** [comment]
We have a test for `nbconvert` https://github.com/jupyter/docker-stacks/blob/main/tests/minimal-notebook/test_nbconvert.py.
I guess if it works without `Inkscape`, then we should be fine removing it.

**Comment by benz0li** [comment]
> @benz0li I would suggest creating a PR and see what the community reaction is to this change.

I am maintaining my own Docker Stacks based on Debian, Python-only, including code-server.
ℹ️ Just sharing my findings with the community. It is up the developers @jupyter what to do.

**Comment by consideRatio** [comment]
To me, the findings in https://github.com/jupyter/docker-stacks/issues/1754#issuecomment-1195484696 is a very strong case for removing inkscape.

For the sustainability of this project, cleaning up legacy packages parts as times goes is relevant. I figure anything that installs dedicated python versions is extra costly and if users depending on such could switch to something else it would be impactful.

It seems to me that inkscapes is a vector graphics graphical editor, not sure how it makes sense to provide that in this container unless its used with a remote desktop setup.

**Comment by benz0li** [comment]
@mathbunnyru @consideRatio If you remove `inkscape`, do not forget to configure `IPython` and `IRkernel` to output both `image/svg+xml` and `application/pdf` plot formats in the notebook file.  
ℹ️ See also https://github.com/JuliaLang/IJulia.jl/pull/1038#issuecomment-1194523666 for more information.

I have not found solution for `IJulia` yet.

**Comment by mathbunnyru** [comment]
Fixed in https://github.com/jupyter/docker-stacks/pull/1765
