### ISSUE TITLE
Container stops/crashes when machine suspends?

### ISSUE THREAD

**Issue by cboettig** [jupyter/docker-stacks#176]
When running the any of the images in this stack on my ubuntu laptop via a native (e.g. not virtualbox) docker installation, I've noticed that whenever I suspend the laptop, the container crashes and must be restarted.  I've never had this problem with any other container running on the laptop (e.g. rstudio-server) so not sure why it should happen here.  Has anyone else experienced that? Any idea what might be the culprit?  When the container stops after a suspend, there's no error message or anything logged in the docker logs...

**Comment by parente** [comment]
What does `docker ps -a` show as the exit code for the stopped containers?

**Comment by cboettig** [comment]
exit code 134.

**Comment by parente** [comment]
@cboettig did you find a cause or solution to this problem?

**Comment by cboettig** [comment]
Haven't been able to replicate this recently so closing; perhaps newer container or newer docker version has changed things.
