### ISSUE TITLE
[BUG] - misconfiguration of port and ip seetings in jupyter_notebook_config.py

### ISSUE THREAD

**Issue by tdudgeon** [jupyter/docker-stacks#1760]
### What docker image(s) are you using?

minimal-notebook, tensorflow-notebook

### OS system and architecture running docker image

Ubuntu x86_64

### What Docker command are you running?

Running in K8S

### How to Reproduce the problem?

Compare running jupyter/minimal-notebook:latest and jupyter/tensorflow-notebook:latest

Both types launch OK but only the minimal notebook is reachable. Both are OK from within the container but when being accessed through the K8S service the tensorflow notebook appear to be rejecting the connection.

The minimal notebook is running server 1.17.1 whereas the tensorflow one is running 1.18.1.

In the logs for the minimal notebook I see this:
```
[W 2022-08-01 11:12:29.352 LabApp] 'token' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-08-01 11:12:29.352 LabApp] 'base_url' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2022-08-01 11:12:29.360 ServerApp] jupyterlab | extension was successfully linked.
[W 2022-08-01 11:12:29.366 NotebookApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-08-01 11:12:29.366 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-08-01 11:12:29.367 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
```

The equivalent in the tensorflow notebook is:
```
[W 2022-08-01 11:03:13.710 LabApp] 'token' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-08-01 11:03:13.710 LabApp] 'base_url' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
```
Note that the warnings about `port` and `ip` are missing.

I assume that between 1.17.1 and 1.18.1 the behaviour changed and the `port` and `ip`  configs are not being "passed" to `ServerApp`, which means that the server is not listening on `0.0.0.0` which will be why the connections from the K8S service are being rejected.

The file `/etc/jupyter/jupyter_notebook_config.py` contains the following:
```
c.NotebookApp.ip = "0.0.0.0"
c.NotebookApp.port = 8888
c.NotebookApp.open_browser = False
```
so it looks like the built in config file has _not_ been updated to reflect the changes from `NotebookApp` to `ServerApp`?

### Expected behavior

All types of notebook should be reachable (depending on the setting of the `ip` property).

### Actual behavior

Tensorflow notebook is not reachable

**Comment by mathbunnyru** [comment]
Could you reproduce this issue without k8s?
This way it will be easier for maintainers to fix the issue.

**Comment by consideRatio** [comment]
I suspect that a very modern version of the JupyterHub Helm chart could be used, where JupyterHub 2+ is used etc where configuration like port/ip isn't something that should be provided any more at all.

These are all warnings and no real errors though.

**Comment by tdudgeon** [comment]
I was unable to reproduce with plain docker, but those investigations showed that the problem was probably a different bug that I've described in #1761

**Comment by mathbunnyru** [comment]
@tdudgeon could you please check that the solution in #1761 worked for you here as well?
