### ISSUE TITLE
[BUG] - Specifying --config doesn't work with server 1.18.1

### ISSUE THREAD

**Issue by tdudgeon** [jupyter/docker-stacks#1761]
### What docker image(s) are you using?

minimal-notebook

### OS system and architecture running docker image

Ubuntu x86_64

### What Docker command are you running?

docker run -it --rm -p 8888:8888 -v "$(pwd)"/jupyter_notebook_config.json:/home/jovyan/jupyter_notebook_config.json jupyter/minimal-notebook@sha256:0f18656bdf861cf811b5489a2a2970d6aa81119bd7d25312584550feea98e154 bash -c "jupyter lab --config /home/jovyan/jupyter_notebook_config.json"

### How to Reproduce the problem?

Create a `jupyter_notebook_config.json` file containing this:
```
{
  "ServerApp": {
    "token": "I3dzbSq7iP2X4DNp"
  }
}
```

Launch the notebook specifying to use that config like this:
```
docker run -it --rm -p 8888:8888 -v "$(pwd)"/jupyter_notebook_config.json:/home/jovyan/jupyter_notebook_config.json jupyter/minimal-notebook@sha256:0f18656bdf861cf811b5489a2a2970d6aa81119bd7d25312584550feea98e154 bash -c "jupyter lab --config /home/jovyan/jupyter_notebook_config.json"
```

This launches a `1.18.1` server. Specifying the `--config /home/jovyan/jupyter_notebook_config.json` option causes things to break. Nothing untoward is shown in the logs but trying to access http://127.0.0.1:8888/lab?token=I3dzbSq7iP2X4DNp does not work.

In contrast if you omit the `--config /home/jovyan/jupyter_notebook_config.json` part (but still  using `bash -c "jupyter lab`) things work OK with an automatically generated token.

Also In contrast if you roll back to a `1.17.1` server by running this:
```
docker run -it --rm -p 8888:8888 -v "$(pwd)"/jupyter_notebook_config.json:/home/jovyan/jupyter_notebook_config.json jupyter/minimal-notebook@sha256:31fa38b975e324a682acfa219e1dfa676d2e07716abeefb50249c00e92871717 bash -c "jupyter lab --config /home/jovyan/jupyter_notebook_config.json"
```

The notebook can be launched OK with the custom token.

Looks like specify a config file causes things to break with `1.18.1`.

### Command output

```bash session
This is the output when things are broken.

[I 2022-08-01 16:06:21.203 ServerApp] jupyterlab | extension was successfully linked.
[I 2022-08-01 16:06:21.210 ServerApp] nbclassic | extension was successfully linked.
[I 2022-08-01 16:06:21.211 ServerApp] Writing Jupyter server cookie secret to /home/jovyan/.local/share/jupyter/runtime/jupyter_cookie_secret
[I 2022-08-01 16:06:21.337 ServerApp] notebook_shim | extension was successfully linked.
[I 2022-08-01 16:06:21.353 ServerApp] notebook_shim | extension was successfully loaded.
[I 2022-08-01 16:06:21.354 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.10/site-packages/jupyterlab
[I 2022-08-01 16:06:21.354 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2022-08-01 16:06:21.357 ServerApp] jupyterlab | extension was successfully loaded.
[I 2022-08-01 16:06:21.359 ServerApp] nbclassic | extension was successfully loaded.
[I 2022-08-01 16:06:21.360 ServerApp] Serving notebooks from local directory: /home/jovyan
[I 2022-08-01 16:06:21.360 ServerApp] Jupyter Server 1.18.1 is running at:
[I 2022-08-01 16:06:21.360 ServerApp] http://localhost:8888/lab?token=...
[I 2022-08-01 16:06:21.360 ServerApp]  or http://127.0.0.1:8888/lab?token=...
[I 2022-08-01 16:06:21.360 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 2022-08-01 16:06:21.362 ServerApp] No web browser found: could not locate runnable browser.
```

It looks very similar to the output from the `1.17.1` server.
```


### Expected behavior

Notebook should be accessible when specifying the `--config /home/jovyan/jupyter_notebook_config.json` option.

### Actual behavior

Notebook cannot be accessed.

### Anything else?

_No response_

**Comment by Bidek56** [comment]
@tdudgeon Why do you think this is an issue with the Docker stacks not jupyter_server?
If it's an issue with jupyter_server than this issue belongs in [jupyter_server GH](https://github.com/jupyter-server/jupyter_server), not here.
Have you tried jupyter_server 1.18.1 locally?
Have you tried jupyter_server [2.0](https://github.com/jupyter-server/jupyter_server/blob/main/CHANGELOG.md#200b0) to see if it works?
Thanks

**Comment by Bidek56** [comment]
Creating `lab_config.py` with

```
from jupyter_core.paths import jupyter_data_dir

c = get_config()  # noqa: F821

c.ServerApp.token = 'I3dzbSq7iP2X4DNp'
```

Then using:

`docker run -it --rm -p 8888:8888 -v "$(pwd)"/lab_config.py:/home/jovyan/.jupyter/jupyter_lab_config.py jupyter/pyspark-notebook`

works just fine with `jupyter-server===1.18.1`

**Comment by mathbunnyru** [comment]
Another way of fixing this issue for me was to add `"ip": "0.0.0.0"` to your json config.
This is what we do in our config as well.

**Comment by mathbunnyru** [comment]
I've checked the jupyter-server docs and in the example they recommend setting an `ip` as I did above.
I think what happens when you don't set this value, is that jupyter attaches to localhost inside docker, that's why port forwarding doesn't work.
It might have been a breaking change in this release.

You also won't see this behaviour when running not in docker, because `localhost` will be the same as your machine.

I think this answers your question, so I'll close the issue. Please, reopen / comment, if this doesn't work for you.

**Comment by tdudgeon** [comment]
Confirmed. Using `"ip": "0.0.0.0"` in the json config file solves the problem.
