### ISSUE TITLE
[BUG] - Docker image jupyter/base-notebook:python-3.9.12 has Python version 3.9.13

### ISSUE THREAD

**Issue by veghp** [jupyter/docker-stacks#1763]
### What docker image(s) are you using?

base-notebook

### OS system and architecture running docker image

Ubuntu 20.04 x86_64

### What Docker command are you running?

`docker run -p 8888:8888 jupyter/base-notebook:python-3.9.12`

### How to Reproduce the problem?

```python
import sys
print(sys.executable)
print(sys.version)
print(sys.version_info)
```

### Command output

```bash session
/opt/conda/bin/python
3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21) 
[GCC 10.3.0]
sys.version_info(major=3, minor=9, micro=13, releaselevel='final', serial=0)
```
```


### Expected behavior

3.9.12

### Actual behavior

Version is 3.9.13 when the image tag is python-3.9.12

### Anything else?

See also https://hub.docker.com/layers/base-notebook/jupyter/base-notebook/python-3.9.12/images/sha256-6cf09d659458bbda5f656deace9393949c2c90b35770858c225847cc97ac47f2?context=explore

Thanks for making these images, very useful!

**Comment by mathbunnyru** [comment]
Unfortunately, this image was built around 2 months ago.
For many months our build system was misbehaving in the build process.

I was only able to fix it a month ago.
https://github.com/jupyter/docker-stacks/pull/1703

The best you can do is to select the image which works for you and ignore the tags for old images.
