### ISSUE TITLE
[BUG] - java & pyspark not pre-installed?

### ISSUE THREAD

**Issue by TBrannan** [jupyter/docker-stacks#1775]
### What docker image(s) are you using?

pyspark-notebook

### OS system and architecture running docker image

windows 11

### What Docker command are you running?

docker run --name pyspark -p 8888:8888 jupyter/scipy-notebook:latest

### How to Reproduce the problem?

from pyspark.sql import *

spark = SparkSession.builder.appName('PySpark Read CSV').getOrCreate()

# Reading csv file
df = spark.read.csv("users.csv")
df.printSchema()
df.show()

### Command output

```bash session
JAVA_HOME is not set
```

### Expected behavior

data frame created successfully

### Actual behavior

It seems that java is not installed on the docker container and the JAVA_HOME environment variable is not set

### Anything else?

I was able to fix this issue, but I had to pip install pyspark and install java through conda and set the environment variable.

I'm not sure if this is a bug or a feature but, I would image you would want the container to have java and pyspark pre installed?

**Comment by mathbunnyru** [comment]
In the docker command you're using `scipy-notebook`. This is a typo, right?

**Comment by Bidek56** [comment]
Please use **jupyter/pyspark-notebook** instead. Thx

`docker run --rm -it -p 8888:8888 -v $(PWD):/home/jovyan/work jupyter/pyspark-notebook`

**Comment by TBrannan** [comment]
oops, I was definitely pulling the wrong docker container. I pulled the correct container and it works as expected. apologies.
