### ISSUE TITLE
[BUG] - Docker images for ubuntu 20.04 not updated 

### ISSUE THREAD

**Issue by tiaden** [jupyter/docker-stacks#1779]
### What docker image(s) are you using?

base-notebook, datascience-notebook, minimal-notebook, pyspark-notebook, r-notebook, scipy-notebook, tensorflow-notebook

### OS system and architecture running docker image

amd64

### What Docker command are you running?

On dockerhub, the last ubuntu 20.04 images are a month old. Are you planning on supporting ubuntu 20.04 images ?

### How to Reproduce the problem?

n/a

### Actual behavior

n/a

**Comment by mathbunnyru** [comment]
Hello @tiaden.
This is not a bug, but intended behaviour. We only build one set of images and do not build several versions of any software.
The way we choose ubuntu version is described here: https://jupyter-docker-stacks.readthedocs.io/en/latest/maintaining/tasks.html#updating-the-ubuntu-base-image

**Comment by mathbunnyru** [comment]
@tiaden if you still need old images, we rebuilt them. This was a one-time thing, but you might find it useful:
https://jupyter-docker-stacks.readthedocs.io/en/latest/#using-old-images

**Comment by tiaden** [comment]
@mathbunnyru, thank you very much for letting me know. I will start using it immediately.
