### ISSUE TITLE
Adding Bokeh-Scala library

### ISSUE THREAD

**Issue by pdestrais** [jupyter/docker-stacks#178]
Hello,

I would like to use the Bokeh-Scala library for data visualisation in scala notebooks.
How can this be done inside the jupyter/all-spark-notebook image ?

**Comment by parente** [comment]
Good question. The bokeh-scala README docs how to use the library in a maven project. If you wanted to add it to a child dockerfile, perhaps you could use the `mvn` client to pull them down and somehow point the Toree (Scala) kernel in the all-spark-notebook image to the proper classpath containing them?

@mattpap probably has a much better answer than I do.

**Comment by parente** [comment]
@pdestrais Did you find a way to use the Bokeh-Scala library?

**Comment by parente** [comment]
This issue has been inactive for a long time. I'm going to close it. @pdestrais if you found a way to use Bokeh-Scala, please add it to the https://github.com/jupyter/docker-stacks/wiki/Docker-recipes page.
