### ISSUE TITLE
[ENH] - Exposing the Spark UI port

### ISSUE THREAD

**Issue by galimba39** [jupyter/docker-stacks#1781]
### What docker image(s) is this feature applicable to?

pyspark-notebook

### What changes are you proposing?

It would be useful for pyspark/spark users to expose the SparkUI port 4040 (please refer to this [https://spark.apache.org/docs/latest/monitoring.html](url)).

### How does this affect the user?

- Improve the overall Pyspark experience as a user

**Comment by bjornjorgensen** [comment]
https://jupyter-docker-stacks.readthedocs.io/en/latest/using/specifics.html#apache-spark

**Comment by galimba39** [comment]
I am not sure I have understood correctly your answer @bjornjorgensen but I'll try to expand my reasoning below.
I was thinking to expose it to make the interaction with the Docker Desktop more confortable.
Something like this

![image](https://user-images.githubusercontent.com/42516847/188617533-5807a86b-c501-44b4-8f9d-5c9e11f0ca49.png)

comes in handy when you plan to add different volumes (one for data, one for code, one for spark local storage etc) and you prefer to use UI to handle both ports and external volumes.

**Comment by mathbunnyru** [comment]
@galimba39 what does this window currently show for `pyspark-notebook` image?

**Comment by mathbunnyru** [comment]
I guess we just have to add `EXPOSE 4040` to the spark images to make sure docker knows which ports we are exposing.

**Comment by bjornjorgensen** [comment]
`docker run -d -p 8888:8888 -p 4040:4040 -p 4041:4041 jupyter/pyspark-notebook` work and it works with docker-compose. I don't think its a good options to expose 4040 as default for everyone. Its a page without password and everyone can stop running spark seasons thru the web page.

**Comment by galimba39** [comment]
@mathbunnyru it currently shows port 8888 only. Just adding EXPOSE 4040 return the image in my previous comment.

@bjornjorgensen 
I'm not an expert in Docker but if I have correctly understood from [this](https://docs.docker.com/config/containers/container-networking/#published-ports), only published ports can be reached from outside and exposed ports shouldn't raise a risk until published.

**Comment by bjornjorgensen** [comment]
hmm.. have been reading [this one..](https://www.cloudbees.com/blog/docker-expose-port-what-it-means-and-what-it-doesnt-mean)

The strange thing her is that I build spark master daily and start it with a docker-compose where I expose - "4040:4040"

But in the docker file I don't have 4040 only 
# Should match the service 
[EXPOSE 2222 EXPOSE 7777](https://github.com/bjornjorgensen/jupyter-spark-master-docker/blob/fcc09efa27c5ac17087ed79a747c272947da76cb/Dockerfile#L180)


So if you start your docker spark image and start pyspark can you open localhost:4040 ?

**Comment by mathbunnyru** [comment]
I am of mixed opinions on this one after reading @bjornjorgensen's message.
@galimba39 is right and `EXPOSE` in the docker image doesn't change published ports on the host machine. So I don't think this is gonna be a security issue.

**Comment by bjornjorgensen** [comment]
@mathbunnyru Yes, I'm more 1+ on this one now. A port can be exposed but not mapped. 

From the link that I posted:

"Exposing a port doesn't make it available when you run a container.  To do that, you need to publish your ports. Depending on how you want to use the port, you need to map it, too."

**Comment by bjornjorgensen** [comment]
@galimba39 `docker run -d -p 8888:8888 -p 4040:4040 jupyter/pyspark-notebook` open port 4040 

`docker ps`
`ea7be5642210   jupyter/pyspark-notebook          "tini -g -- start-no…"   10 minutes ago   Up 10 minutes (healthy)   0.0.0.0:4040->4040/tcp, :::4040->4040/tcp, 0.0.0.0:8888->8888/tcp, :::8888->8888/tcp` 
So why can't you open port 4040 from the GUI that you are using?

**Comment by galimba39** [comment]
@bjornjorgensen I see only [base-notebook](https://github.com/jupyter/docker-stacks/tree/main/base-notebook) exposes port in the docker heriarchy, but you are right saying that

> But in the docker file I don't have exposed 4040

This seems strange to me too. Could it be that passing -p 4040:4040 both does a publish+expose in a row?

Besided this, I made the port 4040 appear in the UI by building a docker on top of one of yours, this way

`FROM jupyter/pyspark-notebook:python-3.10.6`
`EXPOSE 4040`

May it be this the source of the different results?

**Comment by bjornjorgensen** [comment]
Yes, I just figured this out. expose are just for documentation [youtube What Does the Docker EXPOSE Command Do?](https://youtu.be/Rp2LtJH6Gzk)

**Comment by bjornjorgensen** [comment]
@galimba39 will you try to open a PR where you add EXPOSE 4040 https://github.com/jupyter/docker-stacks/blob/c8bbeff1fbc3e7a2a690c10a3f00df812dabe244/pyspark-notebook/Dockerfile#L72 ?

**Comment by galimba39** [comment]
I see you already done the PR, from my point of view port 4040 is a (Py)Spark thing, having that in other dockers may raise doubts in users

**Comment by mathbunnyru** [comment]
Merged the PR, in ~1.5 hours the images will be updated
