### ISSUE TITLE
[BUG] - ModuleNotFoundError: No module named 'pyspark'

### ISSUE THREAD

**Issue by tandav** [jupyter/docker-stacks#1782]
### What docker image(s) are you using?

pyspark-notebook

### OS system and architecture running docker image

Ubuntu22.04 aarch64

### What Docker command are you running?

```bash
docker run --rm -it  jupyter/pyspark-notebook python
```

```python
>>> import pyspark
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pyspark'
```

### How to Reproduce the problem?

run the command above

### Expected behavior

pyspark should be available without PATH manipulations and startup scripts.

### Actual behavior

pyspark is not available in python provided by ` jupyter/pyspark-notebook` image

**Comment by Bidek56** [comment]
Why are you adding Python at the end of `docker run` command?

**Comment by bjornjorgensen** [comment]
use `docker run -d -p 8888:8888 -p 4040:4040 jupyter/pyspark-notebook`

**Comment by Bidek56** [comment]
Or use: `docker run --rm -it -p 8888:8888 -p 4040:4040 -v $(PWD):/home/jovyan/work jupyter/pyspark-notebook` if you want the local storage.

**Comment by bjornjorgensen** [comment]
From jupyterlab you can start a terminal
![image](https://user-images.githubusercontent.com/47577197/188942430-1dfb7daa-3637-40fa-b1b0-82fbd3b5bd22.png)

**Comment by tandav** [comment]
> Why are you adding Python at the end of `docker run` command?

I want to use  `jupyter/pyspark-notebook` as image with pre-installed pyspark to run my python scripts and I don't need jupyter notebook for this. Is such usage out of scope of docker-stacks project?

**Comment by tandav** [comment]
> From jupyterlab you can start a terminal ![image](https://user-images.githubusercontent.com/47577197/188942430-1dfb7daa-3637-40fa-b1b0-82fbd3b5bd22.png)

Yes, I see that when you run jupyter notebook - there is a startup script which sets pyspark environment variables
https://github.com/jupyter/docker-stacks/blob/c8bbeff1fbc3e7a2a690c10a3f00df812dabe244/pyspark-notebook/Dockerfile#L57

My question is - is it possible to set these variables not only for jupyter notebook but also for regular python?  
This docker image is very handy when you quickly need to run pyspark but you don't need jupyter.  
Now you have to manually run that `spark-config.sh` file or `pip install pyspark` to make pyspark work for regular python.

**Comment by bjornjorgensen** [comment]
```bash
docker run --rm -it bjornjorgensen/jupyter-spark-master-docker python
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:35:26) [GCC 10.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyspark
>>> 
```

This is a build with spark master brach. 

https://github.com/bjornjorgensen/jupyter-spark-master-docker/blob/fcc09efa27c5ac17087ed79a747c272947da76cb/Dockerfile#L68 


You can try add 
pip install -e ${SPARK_HOME}/python

**Comment by mathbunnyru** [comment]
I will add a few details here:

1. You say you use `Ubuntu22.04 aarch64`. Then, if you want to use the latest image, please use it like this `jupyter/pyspark-notebook:aarch64-latest`, because we add this prefix to all arm64 image tags (including latest).
2. When you add `python` in the end, you don't run our scripts to set variables properly and so on. You should use `start-notebook.sh python`. There is already an existing issue that we should setup important things in ENTRYPOINT and not CMD. https://github.com/jupyter/docker-stacks/issues/1528

That being said, you should use `docker run --rm -it  jupyter/pyspark-notebook:aarch64-latest start-notebook.sh python`.

Please, tell me if this doesn't answer your question and it still doesn't work.

**Comment by tandav** [comment]
> That being said, you should use `docker run --rm -it jupyter/pyspark-notebook:aarch64-latest start-notebook.sh python`.
> 
> Please, tell me if this doesn't answer your question and it still doesn't work.

@mathbunnyru 

Thank you, I tried this command, but `start-notebook.sh` runs jupyter notebook. I see that `start-notebook.sh` runs `/usr/local/bin/start.sh` inside, so I tried:
```
docker run --rm -it jupyter/pyspark-notebook start.sh python
```
and it works. I can import pyspark inside this python without  ModuleNotFoundError

**Comment by mathbunnyru** [comment]
Yes, sorry, you're right, I meant `start.sh` of course :)
I'm glad I was able to help you.
