### ISSUE TITLE
[BUG] - In the running container,  permission denied in mapped volume

### ISSUE THREAD

**Issue by fymaterials98** [jupyter/docker-stacks#1786]
### What docker image(s) are you using?

datascience-notebook

### OS system and architecture running docker image

Amazon Linux 1

### What Docker command are you running?

`docker run -it --rm -p 7654:8888 -v $(pwd):/home/jovyan/work  --name my_test jupyter/datascience-notebook`

### How to Reproduce the problem?

1. Open localhost browser for Jupyter notebook
2. Tried to create a notebook in Docker container /home/jovyan/work 
3. !ls -l
`total 8
-rw-r--r-- 1 jovyan users   72 Sep 12 22:48 Untitled.ipynb
drwx------ 8    500   500 4096 Sep 12 22:04 work
`
4. !cd work
`
/bin/bash: line 1: cd: work: Permission denied
`
The docker container user and localhost user are different,  and the docker container user cannot access work folder,  which is mapped to the localhost folder.
Could you solve this issue?

### Command output

```bash session
/bin/bash: line 1: cd: work: Permission denied
```

### Actual behavior

The user can map localhost volume to the docker container volume,  and the user inside docker container can access mapped the volume.

**Comment by Bidek56** [comment]
It works fine for me, are you sure your Docker desktop is configured correctly to access the local volume?
Just FYI, these questions belong to SO not GH. :)

**Comment by fymaterials98** [comment]
When I type command in Jupyter notebook to show the user and group id for the current files and folders, 
`ls -l '
and the mapped volume work belongs to the host user instead of jovyan
`
total 8 -rw-r--r-- 1 jovyan users 72 Sep 12 22:48 Untitled.ipynb drwx
------ 8 500 500 4096 Sep 12 22:04 work
`
@Bidek56 I am wondering since I am jovyan user when in the docker container,  and I have no right to access work folder whose owner is 500 (userid) and 500 (group id),  could you show me how you configure docker daemon?
I installed docker on aws ec2 using these commands:
`
# install Docker
yes | sudo yum install docker
sudo service docker start
sudo usermod -a -G docker ec2-user
`

**Comment by Bidek56** [comment]
You may want to try adding: `-e NB_UID=<numeric uid>` and `-e NB_GID=<numeric gid>`
Have you looked at [this](https://github.com/jupyter/docker-stacks/blob/main/docs/using/common.md#user-related-configurations) documentation?
Since you are on AWS already, you may want to use [SageMaker](https://aws.amazon.com/sagemaker/) instead and skip the configuration troubles.

**Comment by Bidek56** [comment]
@fymaterials98 Did you resolve the issue? If so please close this ticket. Thx

**Comment by mathbunnyru** [comment]
@fymaterials98 we're waiting for your response here. Could you please take a look?

**Comment by mathbunnyru** [comment]
Closing this as no response was received. Please, reopen, if you still see this issue.
