### ISSUE TITLE
[ENH] - Stop JupyterLab terminal cursor from blinking

### ISSUE THREAD

**Issue by hzclarksm** [jupyter/docker-stacks#1787]
### What docker image(s) is this feature applicable to?

base-notebook, minimal-notebook

### What changes are you proposing?

Provide the ability manipulate the JupyterLab terminal cursor.  In particular turn off the blinking feature (blinkrate = 0)

### How does this affect the user?

At best the blinking cursor is highly distracting.  

Note: the JupyterNotebook terminal cursor does not blink.

**Comment by Bidek56** [comment]
Have you checked this [post](https://github.com/jupyterlab/jupyterlab/issues/10443)?
Have you checked SO for a solution?
Why do you think Docker will provide a solution to this issue?

**Comment by hzclarksm** [comment]
The suggested post addresses the blinking cursor issue in Jupyter notebooks.  Changing the setting as suggested does not address the problem in Jupyter Lab terminals.
I don't think this a Docker issue but a JupyterLab issue.

**Comment by Bidek56** [comment]
I would suggest posting this question in [Discourse](https://discourse.jupyter.org/c/jupyterlab/17) forum.

**Comment by hzclarksm** [comment]
Thank you.  I will take that under advisement.

**Comment by mathbunnyru** [comment]
@hzclarksm I tried this solution and it works fine for me.
https://github.com/jupyterlab/jupyterlab/pull/10485#issuecomment-871136470

You can also change it in this file to not always have to change it manually (and you can do it separately for three types of cell: code, markdown and raw):
```
~/.jupyter/lab/user-settings/@jupyterlab/notebook-extension$ cat tracker.jupyterlab-settings | grep Blink
        "cursorBlinkRate": 0,
```
