### ISSUE TITLE
[ENH] - Enable clipboard

### ISSUE THREAD

**Issue by adrienpacifico** [jupyter/docker-stacks#1796]
### What docker image(s) is this feature applicable to?

datascience-notebook

### What changes are you proposing?

This code does not work with docker images:

```python
import pandas as pd
df = pd.read_clipboard()
```
It throws a `PyperclipException`.

I do not know if it is possible, but it would be really nice to have this working with docker images.

### How does this affect the user?

- The use will be able to use any library that needs to access to the paperclip.

**Comment by mathbunnyru** [comment]
Hi @adrienpacifico!
I guess I found the solution here: https://github.com/asweigart/pyperclip/issues/161#issuecomment-1112942799
I haven't checked it out, but please try it.

I also think this issue is not related to our docker images in particular and you should use the thread with the message I mentioned (that's why I'm closing this issue).

**Comment by adrienpacifico** [comment]
Hi @mathbunnyru!

I am a bit sad that you closed the issue, as I think that being able to copy/paste at least for local jupyterlab docker image could be a nice option to have! 

It could be: 
1. Documented on how to proceed on https://jupyter-docker-stacks.readthedocs.io/
2. Maybe have xclip installed in minimal-notebook (not in base).

If anyone interested, I made it work on a debian based linux with the following method: 

1. Start jupyterlab container with `docker run --network host -v $(pwd):/home/jovyan/work -e GRANT_SUDO=yes --user root -e DISPLAY -it -v /tmp/.X11-unix:/tmp/.X11-unix jupyter/base-notebook`

2. copy paste the link from your terminal in your browser to access to Jupyter.
example:
```bash
Or copy and paste one of these URLs:
        http://pop-os:8889/?token=c370a0043b9bf8e2e10c39a501fe96f4fbe52da9f58bbfd0
```
3. From jupyter/jupyterlab install xclip with `!sudo apt-get update` if you are in a notebook cell (or remove the `!` if you use jupyterlab's terminal). 
4. From jupyter/jupyterlab install xclip with `!sudo apt-get install xclip --yes` if you are in a notebook cell (or remove the `!` if you use jupyterlab's terminal).

4. Install pandas if needed based on the docker image you are using
5. ```python
import pandas as pd
pd.read_clipboard()
```

And it works 🎉

It would be interesting to me to know if there exist a solution like that for macos (or windows).

**Comment by mathbunnyru** [comment]
Great solution @adrienpacifico!
I guess you're right and I was a bit too fast to close this issue.

Could you maybe share your instruction as a recipe?
https://jupyter-docker-stacks.readthedocs.io/en/latest/contributing/recipes.html

It will be easier for people to find it in the docs (and not in the github issue).

**Comment by mathbunnyru** [comment]
I would also suggest formulating it as a Dockerfile inherited from our Dockerfiles (to be persistent), and not to be run from `jupyter` terminal.

**Comment by Bidek56** [comment]
I believe copy/paste should work without any libs on Windows, but I have not tested it.
The above solution does not work on MacOS 12.6

**Comment by mathbunnyru** [comment]
Let's see how much megabytes the package adds to the image size.

**Comment by mathbunnyru** [comment]
@adrienpacifico as you suggested, I added xclip to the minimal image.
The image will be updated in around 1h30min.
Could you please check after that, that the new image works fine?

And this is the essential part to enable clipboard on Linux host system, right?
`-e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix`

**Comment by adrienpacifico** [comment]
@mathbunnyru,

I am sorry, I was using an old version of jupyterlab image, I just repulled the last version, and I have an error when I launch a jupyter kernel/open a notebook (Server Connection Error). 
I cannot confirm if it works. It seems that the issue I am facing has not an opened (or closed) issue on this repo. I may need to fill one. 

> And this is the essential part to enable clipboard on Linux host system, right?
The answer is yes. However, I have not tried without the `-e DISPLAY` option, it might be unnecessary.

**Comment by mathbunnyru** [comment]
@adrienpacifico I updated the docs.
Please, check again, that the latest image works well for you (and reply here).
