### ISSUE TITLE
Increase diver memory

### ISSUE THREAD

**Issue by jrosskopf** [jupyter/docker-stacks#180]
Hey,

it should be documented for the **all-spark-notebook** how to change the memory allocated for the drivers heap space. I tried several options, eg. set the `--driver-memory` in an environment variable `SPARK_OPTS` on the docker run command, which seemed to have worked some weeks ago. How to do this with Toree Kernel?

Thanks.
Joachim

**Comment by parente** [comment]
I think this is the same as #169. If you're talking about Toree specifically, I believe it sets the SPARK_OPTS env var in its `kernel.json` kernel spec file, so no overriding is possible from the container environment vars.

/cc @Lull3rskat3r @lbustelo

**Comment by Lull3rSkat3r** [comment]
As of right now, you can only set SPARK_OPTS in the kernel.json file. In the 0.1.0 release of Toree you will be able to specify spark options at runtime via SPARK_OPTS.  This environment variable will override the install time spark opts set via `jupyter toree install --spark_opts="..."`.

**Comment by jrosskopf** [comment]
Okay, so no documentation, but a real issue ;)
I'm a little bit confused, as [GitHub Toree Repo](https://github.com/apache/incubator-toree/releases) already shows releases > 0.1.0. Has the version schema changed?

**Comment by parente** [comment]
>  Has the version schema changed?

I think it was reset to 0.1.0 when it moved to Apache.

**Comment by Lull3rSkat3r** [comment]
@jrosskopf, @parente is correct. The version reset when we moved to apache.

**Comment by parente** [comment]
The documentation was updated to reflect the name change to Toree and the kernel.json as it exists. We have #169 to track the SPARK_OPTS issue which should be resolved with Toree 0.1.0. Going to close this one.
