### ISSUE TITLE
[ENH] - Introduce base image from which base-notebook derives

### ISSUE THREAD

**Issue by kevin-bates** [jupyter/docker-stacks#1809]
### What docker image(s) is this feature applicable to?

base-notebook

### What changes are you proposing?

Hello - first, thank you for the great project!  We've been using your images for years in [Jupyter Enterprise Gateway](https://github.com/jupyter-server/enterprise_gateway) and can't recall any issues - really solid!

Enterprise Gateway and (now) [Remove Provisioners](https://github.com/gateway-experiments/remote_provisioners) expose the ability to run Jupyter kernels in containers within Kubernetes and DockerSwarm, etc.  In EG, we've always extended one of the current images to include the kernel bootstrap support necessary to communicate back to the launching server.  Obviously, given these images have notebook, lab, and hub installed, they are far more bloated than necessary, yet having the base infrastructure in place - like `NB_USER`, `fix_permissions`, and `mamba` is extremely helpful - both for us and our users.

With Remote Provisioners, I would like to provide "thinner" kernel images but would like the infrastructure that docker-stacks provides.  To do this, I'm hoping we could introduce a "more base" image to `base-notebook` (e.g., `jupyter-base` or `jovyan-base`, the name is fairly arbitrary) which contains the docker-stacks infrastructure, but no Jupyter applications.  It would also forgo the installation of things like `fonts-liberation`, `pandoc`, and `run-one`, since these aren't necessary for non-notebook applications.  `base-notebook` would then derive from `jovyan-base` or `base-jovyan` (kinda liking the "jovyan" over "jupyter" angle on the name since there really aren't formal Jupyter apps present).

Would the maintainers be open to essentially moving the guts of the `base-notebook` Dockerfile to "jovyan-base" and deriving `base-notebook` from this base image?  Looking at the tests just now, I think many of the infrastructure tests would move to this new image, although I'd recommend leaving them in place (at least for a bit) as another means of validating the inheritance.  I would be happy to submit a pull request, but would likely need some guidance when it comes to testing and CI (outside of following the existing patterns).

### How does this affect the user?

This should have no impact on existing image behaviors, yet provide opportunities on which jupyter-related applications (like kernel-based images) can be built without unnecessary applications and bloat.

### Anything else?

If you'd like an idea of the change to the Dockerfile, I have a [commit in my remote-provisioners fork](https://github.com/gateway-experiments/remote_provisioners/compare/main...kevin-bates:remote_provisioners:add-dockerfiles#diff-9bbcbe5c024dcff8068bcff6fb2871843c55f2c023025fd97060c92e7b3b06de) that introduces a `base-kernel` image, but I wouldn't propose "kernel" be in the name if accepted into this repository.

I know there's probably a lot of overhead in maintaining another image, so completely understand any hesitancy, although I believe having a "non-application" base image may open some doors for other "compatible" container-based applications.

Thank you.

**Comment by Bidek56** [comment]
Without Jupyter these images would be just Python images which already [exists](https://github.com/docker-library/python) and are well maintained.

**Comment by kevin-bates** [comment]
Hi @Bidek56 - thanks for responding.  

I'm not proposing that Jupyter be _removed_ from the images.  I'm only proposing that the `base-notebook` Dockerfile be split into `base-jovyan` - which installs `mamba`, `fix_permissions`, creates the `jovyan` user, and adds some envs like `NB_UID`, `NB_GID`, etc.  That is, it provides the basis for _other_ Jupyter applications to extend.  

`base-notebook` (after deriving from `base-jovyan`) would then consist of installing Notebook, Lab, JupyterHub, pandoc, and various things that _those_ Jupyter applications need.

`base-jovyan` could then support applications like the kernels I was referring to (which really only need `jupyter_client`), but also, for example, `nbclient` applications that are not based on Notebook, Lab, and Hub.

I'm sorry if I wasn't clear in my initial description. The `base-jovyan` Dockerfile would resemble [this](https://github.com/gateway-experiments/remote_provisioners/compare/main...kevin-bates:remote_provisioners:add-dockerfiles#diff-9bbcbe5c024dcff8068bcff6fb2871843c55f2c023025fd97060c92e7b3b06de).

**Comment by mathbunnyru** [comment]
Hello, @kevin-bates. I will first address simple questions :)

> We've been using your images for years in [Jupyter Enterprise Gateway](https://github.com/jupyter-server/enterprise_gateway) and can't recall any issues - really solid!

Thank you ❤️ 

> Looking at the tests just now, I think many of the infrastructure tests would move to this new image, although I'd recommend leaving them in place (at least for a bit) as another means of validating the inheritance.

No need in this. I've implemented  feature to run the tests on all the inherited images as well automatically. So it's always better to move tests to parent images when possible.

>  I would be happy to submit a pull request, but would likely need some guidance when it comes to testing and CI (outside of following the existing patterns).

From the top of my head, I think this is not gonna be difficult. I don't have DockerHub admin permissions yet, but I hope I will get them quite soon. A few things that should be considered (apart from changing Dockerfiles):
1. Adding new image to DockerHub (this can only be done by admins).
2. Moving test to the `base-jovyan` folder, when possible. And updating [this file](https://github.com/jupyter/docker-stacks/blob/main/tests/images_hierarchy.py)
3. Adding this image to the [inheritance file in tagging](https://github.com/jupyter/docker-stacks/blob/main/tagging/images_hierarchy.py) and moving some tags and manifests.
4. Changing our workflow [kind-of a config file here](https://github.com/jupyter/docker-stacks/blob/main/.github/workflows/docker.yml)
5. Updating docs, [especially here](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html). Both the image descriptions and the diagram will have to be updated.
6. Updating [Makefile](https://github.com/jupyter/docker-stacks/blob/main/Makefile) for local development.

Hope this list will make your life easier when you create a PR.

> Would the maintainers be open to essentially moving the guts of the base-notebook Dockerfile to "jovyan-base" and deriving base-notebook from this base image?

This is a bit difficult question, because we haven't introduced new images for a long period of time. Personally, I don't have any trouble with doing such a thing, especially if it helps `jupyter` community. 
I would like to hear from other people as well what they think about this.
@Bidek56 @consideRatio @romainx @trallard @maresb @parente

**Comment by Bidek56** [comment]
So I am not opposed to this change but I do think that there are other stacks that provide this functionality, few examples:
1. [Python](https://github.com/docker-library/python)
2. [Mamba](https://github.com/mamba-org/micromamba-docker/) 
3. [Conda](https://github.com/conda-forge/miniforge-images)

If we do have the time, I rather for us to focus on other features which don't exist like Scala Spark image which would provide more value. Thanks

**Comment by consideRatio** [comment]
I'm leaning positive towards this kind of change at the moment as I see it as a valuable feature that I think could be worth the added long term complexity. My main considerations and perceived action points towards resolving them are:

- Can we ensure future contributors clearly understands what should go in `base-jovyan` respectively in `base-notebook`?
  - [ ] Formulate a clear description of this and seek agreement
  - [ ] Add such description to the future `base-jovyan` Dockerfile
- Does the scripts we provide have dependencies on things we install in `base-notebook` but not in `base-jovyan`, making them only partially work in a `base-jovyan` setup?
  - [ ] Figure out if that is the case
  - [ ] Propose how to resolve that and seek agreement

**Comment by mathbunnyru** [comment]
Hi @kevin-bates! Will you be willing to create a PR for this feature? I guess, everyone agrees that we can proceed with this.

**Comment by kevin-bates** [comment]
Hi @mathbunnyru - thank you for getting back to me - I wasn't sure how many more maintainers needed to weigh in.  I will try to get a PR submitted this week (preferably within the next day or two).
