### ISSUE TITLE
Enable single-user/JupyterHub support in all notebook docker-stack images by default?

### ISSUE THREAD

**Issue by jtyberg** [jupyter/docker-stacks#181]
I recently got JupyterHub running with the `jupyter/all-spark-singleuser` servers, and it got me thinking: should we bake in support for all the `*-notebook` docker-stacks to run in single-user mode as well as stand-alone mode?

From what I can tell, the only difference between the `*-notebook` and `*-singleuser` images is that the latter includes the [jupyter-singleuser](https://github.com/jupyter/jupyterhub/blob/master/scripts/jupyterhub-singleuser) script, which becomes the entrypoint script for the Docker container when running with JupyterHub, instead of the usual [start-notebook.sh](https://github.com/jupyter/docker-stacks/blob/master/minimal-notebook/start-notebook.sh).

If I'm maintaining an image `FROM` one of the `*-notebook` stacks, and I want my image to run in either mode, stand-alone or single-user, then to get around maintaining two identical Docker builds, I always have to inherit `FROM` the `*-singleuser` image and create a separate entrypoint script that invokes the correct notebook startup script, depending on the mode I run in (which I indicate by specifying a `JPY_SINGLE_USER` environment variable):

```
# Start JupyterHub Notebook server.
# If JPY_SINGLE_USER environment variables is set, start in singluser mode
# (we were spawned by JupyterHub);  otherwise, start normally.
if [ -n "${JPY_SINGLE_USER+x}" ]; then
  exec sh /srv/singleuser/singleuser.sh $*
else
  exec /usr/local/bin/start-notebook.sh $*
fi
```

This is working fine, but I wonder if this recipe will become common enough that baking either startup script into the `*-notebook` stacks would be beneficial.  A pro of this approach would be fewer images (no more `*-singleuser` versions).  Of course, the con is that now the notebook startup script becomes more complicated, as it tries to accommodate more use cases.

I'm happy to give a PR a shot, but I wanted to guage what others thought first.

cc/ @minrk

**Comment by minrk** [comment]
That's probably a better idea than what I did with the separate images, I like it.

**Comment by parente** [comment]
Works for me. @jtyberg Add the logic to the start-notebook.sh script that we already have. READMEs will need an update about the option and what happens when you by-pass that script (i.e., singleuser-no-workie).

All our other env vars are `NB_*` I think but `JPY_*` is fine too. Just gotta doc everything.

**Comment by jtyberg** [comment]
Of course, things get more complicated once you dig in a little bit.

The `*-singleuser` images are being built by including these scripts:

* [jupyter/dockerspawner/singleuser/singleuser.sh](https://github.com/jupyter/dockerspawner/blob/master/singleuser/singleuser.sh), which invokes
* [jupyter/jupyterhub/scripts/jupyter-singleuser](https://github.com/jupyter/jupyterhub/blob/master/scripts/jupyterhub-singleuser)

and by making `singleuser.sh` the Docker entrypoint script.  

@minrk I understand why you went the separate image route - it's good Docker practice.  We're overriding the entrypoint script and creating a new image as a result.  If we bake in the `singleuser` scripts into the `*-notebook` images instead, we still run into the same problem if a user wants a different startup script, such as [jupyter/dockerspawner/systemuser](https://github.com/jupyter/dockerspawner/blob/master/systemuser).  

I guess the question is, where does it end?  Do we stop at including the `singleuser.sh` option?  Is there a reason we're only building `*-singleuser` images now?

**Comment by parente** [comment]
> Opinionated stacks of ready-to-run Jupyter applications in Docker.

Opinion can change over time. If you want to start with singleuser today, and others want to expand later with systemuser (or whatever comes next), then 🍰  for everyone who wants to contribute.

**Comment by minrk** [comment]
The use case that prompted the creation of SystemUser is mostly gone now, so I don't think we should include system user versions of these. That doesn't mean there are *no* uses, only that the original reason it exists is going away.

If it seems simpler to leave the separate images, that's fine, too.
