### ISSUE TITLE
[BUG] - Hadoop command not found

### ISSUE THREAD

**Issue by nakvic** [jupyter/docker-stacks#1816]
### What docker image(s) are you using?

all-spark-notebook

### OS system and architecture running docker image

Debian GNU/Linux 11 (bullseye)/arm64

### What Docker command are you running?

docker run  -d -p 8087:8888 jupyter/all-spark-notebook

### How to Reproduce the problem?

Neither hadoop nor hdfs commands found in terminal.

docker exec -it all-spark-notebook-01 bash

jovyan@658dcc88c813:~$ hadoop
bash: hadoop: command not found
jovyan@658dcc88c813:~$ hdfs
bash: hdfs: command not found
jovyan@658dcc88c813:~$

### Command output

```bash session
jovyan@658dcc88c813:~$ hadoop
bash: hadoop: command not found
jovyan@658dcc88c813:~$ hdfs
bash: hdfs: command not found
jovyan@658dcc88c813:~$
```

### Expected behavior

Expected hadoop available from terminal

### Actual behavior

No command line hadoop available

### Anything else?

Not sure if it is a bug, but could not find the reason.
No hadoop executable in /usr/local/spark-3.3.1-bin-hadoop3/bin found

**Comment by Bidek56** [comment]
Spark uses "Hadoop Free" client libraries for HDFS and YARN. Please see this [document](https://spark.apache.org/docs/latest/hadoop-provided.html) for more info.

**Comment by mathbunnyru** [comment]
Thank you @Bidek56. Then, I guess it is expected behaviour, that these binaries are not present, so closing this issue.
