### ISSUE TITLE
[BUG] - Health Check fails if you change the port jupyter runs on

### ISSUE THREAD

**Issue by antofthy** [jupyter/docker-stacks#1817]
### What docker image(s) are you using?

minimal-notebook

### OS system and architecture running docker image

RHEL7  docker swarm

### What Docker command are you running?

Not really relevant, but I need to run it in a docker swarm, with a generalise 'ingress service'.

For this I needed to change internal port jupyter runs on needs to be changes for intergation into a 'ingress proxy'
To change the port I made a slight modification the docker image to set the internal port it runs on (see below)

The problem is the docker container  dies unexpectedly after running for 46 seconds.
During that time the service is visible within the conatiner, but not external to the container.
This is because the built-in heathcheck never succeeds, and eventually kills the container with little logged reporting.
(see below)

### How to Reproduce the problem?

Dockerfile, to set port

```dockerfile
FROM "jupyter/minimal-notebook:latest"
# Update Jupyter configuration to set port
RUN set -eux; \
    sed -i 's/port = 8888/port = 8080/' /etc/jupyter/jupyter_notebook_config.py ;\
    sed -i 's/port = 8888/port = 8080/' /etc/jupyter/jupyter_server_config.py ;\
    :;
```
You can also change the port in other ways such as... 

Creating a `~joyvan/.jupyter/jupyter_server_config.py` file (which can also set a password)

or setting a  JUPYTER_PORT environment variable (IF the setting in `/etc/jupyter` configs are removed)

### Command output

When you build and then run the modified docker image, `docker ps`  reports
`Up 9 seconds (health: starting)   8888/tcp`  despite the fact that jupyter is now running on port 8080

46 seconds after starting the container dies with a unhelpful (Signal 15)

Log output...
```
[I 2022-10-28 05:20:00.393 ServerApp] Jupyter Server 1.21.0 is running at:
[I 2022-10-28 05:20:00.393 ServerApp] http://jupyter_service:8080/lab?token=929eaaf2e60f8a947761cb1f2741d745fd46dde62f6fef7c
or http://127.0.0.1:8080/lab?token=929eaaf2e60f8a947761cb1f2741d745fd46dde62f6fef7c
[I 2022-10-28 05:20:00.393 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2022-10-28 05:20:00.397 ServerApp] 

To access the server, open this file in a browser:
file:///home/jovyan/.local/share/jupyter/runtime/jpserver-8-open.html
Or copy and paste one of these URLs:
http://jupyter_service:8080/lab?token=929eaaf2e60f8a947761cb1f2741d745fd46dde62f6fef7c
or http://127.0.0.1:8080/lab?token=929eaaf2e60f8a947761cb1f2741d745fd46dde62f6fef7c
Entered start.sh with args: jupyter lab
Executing the command: jupyter lab
[C 2022-10-28 05:20:46.261 ServerApp] received signal 15, stopping
[I 2022-10-28 05:20:46.262 ServerApp] Shutting down 2 extensions
[I 2022-10-28 05:20:46.263 ServerApp] Shutting down 0 terminals
```

### Expected behavior

Changing the internal port should not take days of work to track down, it should be straight forward and documented.

The healthcheck should also be properly documented in jupyter-stacks documentation.
This will make it more 'swarm friendly' as well as allow others to integrate it better when port 8888 is NOT available.

Yes you can map the port when doing a 'docker run', but that is NOT always possible.

### Actual behavior

Internal Port changing is undocumented in stacks

Heathcheck kills the container without notice (signal 15 hardly makes it clear) when port is different.

Days of work lost trying to figure out what should be a straight forward and simple task.

### Anything else?

There is an existing environment variable  "JUPYTER_PORT" that defines the default port.
But any such setting is currently overridden by the  configuration files in `/etc/jupyter`

This may be usable to set healthcheck, especially if the config file default is removed, or allows the env var to override.

in Dockerfile....
```
HEALTHCHECK  --interval=15s --timeout=3s --start-period=5s --retries=3 \
    CMD wget -O- --no-verbose --tries=1 --no-check-certificate \
    http${GEN_CERT:+s}://localhost:${JUPYTER_PORT:-8888}${JUPYTERHUB_SERVICE_PREFIX:-/}api || exit 1
```

That Environment variable also needs to be documented in the jupyter-stacks documentation, with the health check.

**Comment by imiro** [comment]
+1, I also experienced similar issue. In my case, I used custom port as well as changing the base url (using the `--ServerApp.base_url` parameter) as I want to host jupyter from a subpath.

The workaround that I came up with is to override the healthcheck using a custom-build downstream docker image or by  with docker compose configuration.

This should be better documented, and would be even better if there is easier way to specify custom ports and base url, just as how we can specify JUPYTERHUB_SERVICE_PREFIX using environment variable.

**Comment by antofthy** [comment]
Using JUPYTER_PORT (sets default port used) would be ideal. but needs the default port setting removed from the /etc config files (or it overrides it) and the variable added to the HEALTHCHECK.  Both of which substitute the environment variable value at run time, rather than at the time of Dockerfile image build.  

So if it is fixed in the library docker images, you can set it at run time, just like JUPYTERHUB_SERVICE_PREFIX

**Comment by mathbunnyru** [comment]
Hi everyone, thank you for all your suggestions!
`JUPYTER_PORT` was not there when these stacks were created, so I think it's a great idea to switch from config to env variable. https://github.com/jupyter/notebook/pull/5221

Is someone willing to create a PR for this?
1. Let's remove port setting in config.
2. Add `JUPYTER_PORT` with default value `8888` to the root file
3. Add a test which changes the internal port
4. Fix the health check command to use this env variable
5. Add a health check test (both using the default port and not using it).
6. Document health check behaviour (including https://github.com/jupyter/docker-stacks/issues/1709)

**Comment by mathbunnyru** [comment]
@antofthy @imiro any chance you could work on a PR?

**Comment by imiro** [comment]
Sorry I've been a bit busy, but I might have some time next week on this

**Comment by mathbunnyru** [comment]
@imiro if you're still interested, I've recently added a new healthcheck test.

**Comment by imiro** [comment]
Sorry for dragging this for so long. I opened a PR #1859 
Thanks @mathbunnyru for the healthcheck test, I added a couple of test cases to test the `JUPYTER_PORT` env variable.

Any suggestion on where to document the healthcheck behavior? I'm thinking of adding something to using/common.md, maybe?

**Comment by imiro** [comment]
@mathbunnyru Also, I know you mentioned on #1709 that it would be too much to check for custom base_url. 

I just noticed that the URL will be available on a json file that resides on `~/.local/share/jupyter/runtime` (I tried for lab, notebook, nbclassic, server but not jupyterhub)

What do you think of reading the URL from this json file and use it for healthcheck?

**Comment by mathbunnyru** [comment]
> @mathbunnyru Also, I know you mentioned on #1709 that it would be too much to check for custom base_url.
> 
> I just noticed that the URL will be available on a json file that resides on `~/.local/share/jupyter/runtime` (I tried for lab, notebook, nbclassic, server but not jupyterhub)
> 
> What do you think of reading the URL from this json file and use it for healthcheck?

I think that's a good idea. But at the same time our healthcheck is gonna be a bit too complicated.
A few things to think about:
- changing `jovyan` username (current approach will still work, while reading files might break, if not implemented correctly)
- we will have to read the file, parse it and maybe the best thing is to use python at this point (and not write a line of pure bash with jq and so on)

I think let's add the port and maybe in another PR (after the first one is merged) let's try to implement file-based approach.

**Comment by mathbunnyru** [comment]
@antofthy @imiro I merged the PR. Now you can change the internal port using `${JUPYTER_PORT}` env variable.
Thanks @imiro for the PR, good job 👍 

Also, if you really want to support base_url and want to try file-based approach, please, create a new issue (or even a PR with proposed changes).
