### ISSUE TITLE
[BUG] - Mounting a NFS share as the users home locks ip ipykernel

### ISSUE THREAD

**Issue by antofthy** [jupyter/docker-stacks#1820]
### What docker image(s) are you using?

minimal-notebook

### OS system and architecture running docker image

RHEL7 x86_64

### What Docker command are you running?

It runs in a swarm environment...

```
docker service create --detach --init --restart-condition=none --replicas 1 --name s357751 --hostname s357751.**domain**  --env HOME=/home/jovyan  --network ingress_net jupyter/minimal-notebook:latest
```
and then with a local mount of a NFS mount
```
docker service create --detach --init --restart-condition=none --replicas 1 --name s357751 --hostname s357751.**domain** --mount type=bind,src=/export/s357751/jovyan,dst=/home/jovyan --env HOME=/home/jovyan  --network ingress_net jupyter/minimal-notebook:latest
```
The contents of the direct has the correct uid:gid or 1000:100  and is a exact replica of the `/home/jovyan` within the image

### How to Reproduce the problem?

The first command above  (no mount, just the image itself) works perfectly fine.
I get the token from the logs, and login, and can run ipykernel notebooks

The second command (with a local bind mount of an NFS mount) also logs in fine, Lab pages are visible, and terminals can be opened.  But as soon as you try to run a ipykernel the web site locks up.
The server is running but no longer responds to any queries, from anywhere.
The log output ends with the line `[I 2022-10-31 16:47:10.952 ServerApp] Creating new notebook in` and no further.

If the directory is mounted else where I can see and access it, and looks perfect fine, with expected UIDs and files.
Mounting as just the work sub-irectory also works fine. Even if you start jupyter notebook while labs is in the mounted work sub-directory.  As such it likely involve home 'dot' files.

This system of mounting has been used for may other docker environments and has been in use by users for more than three years with code-server, NPM, apache, and larval software.   Only Jupyter Notebook locks up, using many attempts to allow its use, on and off over many years.   This is the first time I traced the problem so it only happens with the mounted home, while working fine without the mounted home.    

### Expected behavior

ipykernel starts and notebook page appears.

### Actual behavior

The notebook page does not appear, and a refresh results in a timeout to read data.

### Anything else?

The NFS mount that docker does a bind mount to is...
```
storage.**domain**:/homes on /export type nfs (rw,nosuid,nodev,noatime,nodiratime,vers=3,rsize=65536,wsize=65536,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.250.201.58,mountvers=3,mountport=635,mountproto=udp,local_lock=none,addr=10.250.201.58)
```
It is used for the homes for may other docker containers for our users, (running code-server).

The only thing I can think of is perhaps there is a lockfile that does not work with the NFS mount docker is bind mounting against.

**Comment by antofthy** [comment]
**UPDATE:**  
It only happens with mounting from the NFS home share mount,  which is a requirement for a full swarm service, where the docker container may run on any of a number of hosts.
Running with the home mounted from the host machines local disk works fine!  I can run ipykernel (notebook) just fine.
```
docker service create --detach --init --restart-condition=none --constraint node.hostname==na-dev-elf.itc.griffith.edu.au --replicas 1 --name s357751 --hostname s357751.*** --mount type=bind,src=/home/jovyan,dst=/home/jovyan --env HOME=/home/jovyan --network ingress_net remote.registry.itc.griffith.edu.au/jupyter/minimal-notebook:latest
```
Mount info...
```
# mount | grep /home
/dev/mapper/rootvg-lv_home on /home type xfs (rw,nosuid,nodev,noatime,nodiratime,attr2,inode64,noquota)
```
So it is likely something about NFS.   Perhaps some sort of lockfile failure.  NFS is known for file lock problems.

**Comment by antofthy** [comment]
**UPDATE #2**

At moment of failure docker reports...
`lockd: cannot monitor storage.**domain**`

So is there anything that can be done?   I have no control over the source of the storage.

**Comment by Bidek56** [comment]
Have you looked at [SO](https://stackoverflow.com/questions/72822339/docker-volumes-shared-with-the-jupyter-lock-the-folder)?

**Comment by antofthy** [comment]
> Have you looked at [SO](https://stackoverflow.com/questions/72822339/docker-volumes-shared-with-the-jupyter-lock-the-folder)?
1/ it is not mounting the whole home just the "work" sub-directory.
2/ it is addressing problems of UID/GID not file locking.   As mentioned I was very careful is ensuring that was not the problem.
3/ it works fine without a bind mount, or with a bind mount not involving NFS.
4/ I did track it down to bein cause by NFS file locking.  If I can determine what file is being locked, I could posibly move it out of the home directory (directory symlink?)
5/ I am investigating getting the NFS file locking working, but I don't have control of the source systems.
Most 'fixes'  are for NFSv3 with rpc.statd,  not NFSv4 which is supposed to have file locking built in.
 
 So really the issue boiled down to...  What file is being locked by notebook?  Can be done from the jupyter side?

**Comment by Bidek56** [comment]
1. If you are trying to set up a multi user learning env, I would suggest using [Google Colab](https://colab.research.google.com) and avoid all the setup issues.
2.  Jupyter NFS issues should be asked/addressed on [SO](https://stackoverflow.com) or [Jupyter Forum](https://discourse.jupyter.org) not on GH. :)

**Comment by antofthy** [comment]
Thank you [Bidek56,](https://github.com/Bidek56) for the suggestion about asking on the Jupyter Forum.

A user (big thanks to kevin-bates) who was able to point to some code information about NFS problems which resolved the problem!  [Notebook fails on NFS mount, lockd not available](https://discourse.jupyter.org/t/notebook-fails-with-nfs-mounted-home-and-lockd-not-available/16626/2?u=antofthy)

For reference... It is caused by a [SQLite history in ipykernal issue](https://github.com/ipython/ipython/issues/11893)
with the solution in the code [SQLite is known to misbehave on some NFS mounts](https://github.com/ipython/ipython/blob/3df473c58741eadf468cfb761ac9b7d9db576be4/IPython/core/history.py#L142-L159)

**Comment by antofthy** [comment]
Addendum... Perhaps this should be added to docker-stacks trouble shooting with regards to NFS mounted homes?

**Comment by Bidek56** [comment]
Feel free to submit a PR, this stack has a documentation and recipe section. Perhaps add. An entire recipe based on your findings.
I am glad you were able to resolve your issue.
