### ISSUE TITLE
[BUG] - KeyError 'code'

### ISSUE THREAD

**Issue by rwmajor2** [jupyter/docker-stacks#1826]
### What docker image(s) are you using?

scipy-notebook

### OS system and architecture running docker image

Ubuntu 22.04

### What Docker command are you running?

In examing the docker logs, I see this about every 10 minutes.  Any idea what is causing it?

[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 406, in dispatch_shell
    await result
  File "/opt/conda/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 798, in inspect_request
    content["code"],
KeyError: 'code'

### How to Reproduce the problem?

N/A

### Actual behavior

Run image and observe logs.

**Comment by Bidek56** [comment]
1. What is the command that you are running to start the container?
2. Have you checked SO or [Discord](https://discourse.jupyter.org) before posting?

**Comment by Bidek56** [comment]
I can not reproduce the problem. What are you running to produce the error?

**Comment by mathbunnyru** [comment]
@rwmajor2 
I agree with @Bidek56, please fill in all the details about this issue.

Also, please, try to recreate this issue with the latest image.
`/opt/conda/lib/python3.9/` in your path means you use `python3.9` image, which might be quite old.

**Comment by mathbunnyru** [comment]
We haven't received any response here. Please, reopen and add missing details, if this is still an issue.
