### ISSUE TITLE
Posting in a Jupyter Medium Blog

### ISSUE THREAD

**Issue by mathbunnyru** [jupyter/docker-stacks#1837]
I'm currently writing a post on a medium about how we enabled support for `aarch64` images.
Could someone share, who I should ask to publish it on jupyter medium?

If someone is willing to read it and review it, it would be great as well.
It's currently in progress and it will take some time to finish it.

**Comment by consideRatio** [comment]
I've never done it, but there was just a note in the jupyterhub/team-compass in a PR about this, i'm on a mobile not able to look up what PR it was, but check for open or recently merged!

**Comment by mathbunnyru** [comment]
Cool, thanks, I'll do it!

**Comment by mathbunnyru** [comment]
PR: https://github.com/jupyterhub/team-compass/pull/593/files

A guide: https://jupyterhub-team-compass.readthedocs.io/en/latest/practices/external-communication.html#blog-posts

Thank you @consideRatio ❤️

**Comment by mathbunnyru** [comment]
Closing this issue in favor of https://github.com/jupyterhub/team-compass/issues/610
