### ISSUE TITLE
[BUG] - curl & git clone not working after upgrade to 2.3.1 and newer

### ISSUE THREAD

**Issue by aloifolia** [jupyter/docker-stacks#1843]
### What docker image(s) are you using?

all-spark-notebook

### OS system and architecture running docker image

Alpine Linux v3.10

### What Docker command are you running?
```sh
docker build . -t myimage --build-arg HTTP_PROXY=myproxy
# plus build arguments for other variations (https_proxy, no_proxy, all uppercase...)
```

### How to Reproduce the problem?

Unsure because the error does not occur on my local machine, but inside a docker:18-dind Gitlab runner. The basic setting is a Dockerfile like this:

```Dockerfile
FROM jupyter/all-spark-notebook:hub-2.3.1
RUN curl --insecure -x "$HTTP_PROXY" -X GET -I www.google.de # you might notice my desperation, here
```

This file previously used the tag `hub-1.4.2` which worked flawlessly. In my .gitlab-ci.yml I use a `docker build` command to create a new image based on the Jupyterhub image. 

### Command output

```bash session
Step 8/14 : RUN curl --insecure -x "$HTTP_PROXY" -X GET -I www.google.de
 ---> Running in e7d0017fef70
curl: (5) getaddrinfo() thread failed to start
```

### Expected behavior

curl (like git which has the same problem) should behave like it did before the upgrade.

### Actual behavior

Curl (and Git) fail for every address they are fed.

**Comment by bjornjorgensen** [comment]
https://github.com/curl/curl/issues/6495

This have nothing to do with the images that `jupyter/docker-stacks` provide 

docker:18-dind this is 3 years old..
