### ISSUE TITLE
[BUG] Log WARNING: no write access to /home/jovyan

### ISSUE THREAD

**Issue by simonglet** [jupyter/docker-stacks#1856]
### What docker image(s) are you using?

datascience-notebook, scipy-notebook

### OS system and architecture running docker image

MacOS 10.13.6, High Sierra: 17.7.0 Darwin Kernel Version 17.7.0: Fri Oct 30 13:34:27 PDT 2020; root:xnu-4570.71.82.8~1/RELEASE_X86_64 x86_64

### What Docker command are you running?

docker run -p8890:8888 -v mylocaldir:/home/jovyan/work jupyter/scipy-notebook:b807da51d7f2

### How to Reproduce the problem?

Run the command and these lines will be logged:

$ docker run -p8890:8888 -v mylocaldir:/home/jovyan/work jupyter/scipy-notebook:latest
Entered start.sh with args: jupyter lab
WARNING: no write access to /home/jovyan. Try starting the container with group 'users' (100), e.g. using "--group-add=users".

if you let the container launch, open Jupyter, and double-click on the Python3 Notebook icon to get the following error message in a popup alert:
Unexpected error while saving file: Untitled.ipynb [Errno 2] No such file or directory: '/home/jovyan/.~Untitled.ipynb' -> '/home/jovyan/Untitled.ipynb'

### Expected behavior

Being able to mount a local dir in the container.

### Actual behavior

Cannot see the directory in Jupyter
Cannot create a file in the / dir

**Comment by mathbunnyru** [comment]
Please, take a look here:
https://jupyter-docker-stacks.readthedocs.io/en/latest/using/troubleshooting.html#permission-denied-when-mounting-volumes

I think the instruction provided there should help.

**Comment by simonglet** [comment]
Thank you for the reference.

By opening a bash session in the running container, I confirmed that the /home/jovyan directory is not visible from Jupyter. It is there, I can mount in it a writable directory without the extra CHOWN arguments.

So now it seems to be a Jupyter configuration issue. Just in case, how can I fix that?

Thanks

**Comment by mathbunnyru** [comment]
Please check permissions/ownership of your dir in the host machine and inside the container?
Also, please provide as many details as you can.

**Comment by simonglet** [comment]
Thank you for the follow-up.

Trying to run the Jupyter container on my Mac (MacBook Pro, early 2011, Intel i5) now stuck at macOS High Sierra (10.13.6) with Docker 19.03.13 was a bad idea.

Running the container on Docker 20.10.12 (another host) works just fine. I can mount host directories with no issue.

I did not read anything about the image's Docker compatibilities. Could that be added somewhere?

Thanks

**Comment by mathbunnyru** [comment]
I don't think we actually use something magical in our Dockerfiles (though I might be wrong).
So, some versions of Docker might be better than others.
Unfortunately, we are not able to test multiple versions of Docker on every platform, though we had some issues on Linux with old docker installations.

The best I can do I think is to add to the issue form a checkbox "I've updated Docker to the latest available version". This will encourage people to try updating before creating an issue.

Also, I'm glad you were able to resolve this issue. So, closing it.
