### ISSUE TITLE
[Python 3.11] - Debugger warning: It seems that frozen modules are being used

### ISSUE THREAD

**Issue by benz0li** [jupyter/docker-stacks#1861]
### What docker image(s) are you using?

base-notebook (modified build)

### Host OS system and architecture running docker image

Debian 11 / x86_64

### What Docker command are you running?

`docker run -it --rm -p 8888:8888 registry.gitlab.b-data.ch/jupyterlab/python/base:3.11.1`

### How to Reproduce the problem?

Visit `http://127.0.0.1:8888/lab?token=<token>`

### Command output

```bash session
...
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
```

### Expected behavior

This warning seems to be expected with Python 3.11: https://discourse.jupyter.org/t/debugger-warning-it-seems-that-frozen-modules-are-being-used-python-3-11-0/16544

### Actual behavior

This is not a bug.

The question is: What should be done here?

1. Nothing (it's just a warning).
2. Pass `-Xfrozen_modules=off` to python.
    * = disable frozen modules.
3. Set `PYDEVD_DISABLE_FILE_VALIDATION=1`.
    * = disable this validation.

### Latest Docker version

- [X] I've updated my Docker version to the latest available and the issue still persists

**Comment by benz0li** [comment]
@mathbunnyru @fcollonval Do you have any suggestion what should be done here?

1. Nothing (it's just a warning).
2. Pass `-Xfrozen_modules=off` to python.
    * = disable frozen modules.
3. Set `PYDEVD_DISABLE_FILE_VALIDATION=1`.
    * = disable this validation.

**Comment by mathbunnyru** [comment]
Unfortunately, I'm not yet familiar with frozen modules, so I can't answer this question, sorry :(

**Comment by benz0li** [comment]
Cross reference: https://github.com/jupyter/docker-stacks/pull/1844

**Comment by benz0li** [comment]
My recommendation is to leave *as is* at *system level*. it's just a warning.

If it bothers anyone,`PYDEVD_DISABLE_FILE_VALIDATION=1` can be set at *user level*.

**Comment by JustaGreenhand** [comment]
I could not understand yet.What does it mean?Could you teach me how to deal with it?I am just a greenhand.Thanks!

**Comment by mathbunnyru** [comment]
@JustaGreenhand you mentioned not a problem, but 3 possible solutions.
And my current advice is to use the first solution.

**Comment by JustaGreenhand** [comment]
> @JustaGreenhand you mentioned not a problem, but 3 possible solutions. And my current advice is to use the first solution.

OK.Thanks.But sometimes i would thought it unconfortable.(cry)

**Comment by theraghavjuneja** [comment]
But code isnt running in jupyter notebook due to this warning. Now what

**Comment by mathbunnyru** [comment]
> But code isnt running in jupyter notebook due to this warning. Now what

Please, create a new issue, explaining what doesn’t work for you.
