### ISSUE TITLE
[ENH] - Execute Scala Code in notebook

### ISSUE THREAD

**Issue by wscardua** [jupyter/docker-stacks#1865]
### What docker image(s) is this feature applicable to?

all-spark-notebook

### What changes are you proposing?

add the possibility to use Scala to code in notebook

### How does this affect the user?

it is an additional possibility to the use of pyspark

**Comment by bjornjorgensen** [comment]
well we have some problems finding a kernel that works with the latest Apache spark. 
[How to Properly setup Scala in Jupyter Notebook](https://stackoverflow.com/questions/71566404/how-to-properly-setup-scala-in-jupyter-notebook)
And there are [almond](https://almond.sh) witch also don't have support for the latest stuff. 

Have a look at https://github.com/jupyter/docker-stacks/pull/1729 and https://github.com/alexarchambault/ammonite-spark/issues/223

**Comment by bjornjorgensen** [comment]
FYI: Apache spark 3.4 will soon have a RC1 where spark connect is a new thing. With this connect there will be some support for Scala have a look at https://github.com/apache/spark/commit/934d14d73c14406242ccd11ba67e64fde1f3b955

**Comment by Bidek56** [comment]
I tried to resurrect [spylon-kernel](https://github.com/vericast/spylon-kernel) by contacting the repo owners, but I did not receive a response.
The issue with spylon-kernel is that is has: Copyright (c) 2017, Maxpoint

**Comment by Bidek56** [comment]
Apparently Maxpoint is owned by [Vericast](https://www.vericast.com/team/max-point/)
@parente do you have access to the [spylon-kernel](https://github.com/vericast/spylon-kernel) repo? or do you know who has? Thx

**Comment by bjornjorgensen** [comment]
https://github.com/apache/spark/pull/40515 FYI

**Comment by mathbunnyru** [comment]
@bjornjorgensen @Bidek56 do you know, maybe there were some changes in the projects you mentioned and they can be used to solve this issue?

**Comment by mathbunnyru** [comment]
Nice! Maybe we should update our docs and close this issue then?

**Comment by Bidek56** [comment]
I believe we had a note in the docs referencing Almond already but I can not find it ATM.

**Comment by mathbunnyru** [comment]
> I believe we had a note in the docs referencing Almond already but I can not find it ATM.

We might have deleted it when we were cleaning up.
Please, make a PR adding almond image here, I think it's the best place:
https://github.com/jupyter/docker-stacks/blob/main/docs/using/selecting.md#community-stacks

**Comment by Bidek56** [comment]
How are you going update the [pypi](https://pypi.org/project/spylon-kernel/) package?
Create a new one? Or bring in the code into this repo?

**Comment by mathbunnyru** [comment]
@bjornjorgensen really nice 👍 
I think if you want to pack this as a python package and then provide it as a recipe for the docker-stacks, it would be great.
