### ISSUE TITLE
Permission Denied - Building container via google cloud with jupyter/all-spark-notebook

### ISSUE THREAD

**Issue by bayerlse** [jupyter/docker-stacks#1873]
### What docker image(s) are you using?

all-spark-notebook

### Host OS system and architecture running docker image

kubernetes cos_containerd

### What Docker command are you running?

I'm trying to deploy the image via google cloud build and create some folders, while I'm getting a permission denied error all the time...

```
FROM jupyter/all-spark-notebook

WORKDIR /home/app

COPY jupyter_server_config.py /usr/share/jupyter/jupyter_server_config.py

RUN sudo mkdir -p /data/storage

RUN mkdir -p /data/storage

COPY . .
```

### How to Reproduce the problem?

Try to build:

```
FROM jupyter/all-spark-notebook

WORKDIR /home/app

COPY jupyter_server_config.py /usr/share/jupyter/jupyter_server_config.py

RUN sudo mkdir -p /data/storage

RUN mkdir -p /data/storage

COPY . .
```

### Expected behavior

There should be no "mkdir: cannot create directory ‘/data/storage’: Permission denied" error

### Actual behavior

mkdir: cannot create directory ‘/usr/share/data’: Permission denied

### Latest Docker version

- [X] I've updated my Docker version to the latest available, and the issue still persists

**Comment by mathbunnyru** [comment]
```
RUN sudo mkdir -p /data/storage
```

I would not recommend using `RUN sudo`.
Instead, use `USER root` (and then switch back).

On my machine, your Dockerfile doesn't build for another reason:
```
 => ERROR [4/6] RUN sudo mkdir -p /data/storage                                                                                                                                                            0.2s
------
 > [4/6] RUN sudo mkdir -p /data/storage:
#7 0.155 sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
#7 0.155 sudo: a password is required
```

**Comment by mathbunnyru** [comment]
I haven't received a response, so, closing this issue. Please, reopen, if my solution doesn't work for you.
