### ISSUE TITLE
[ENH] - Upcoming: Ubuntu ≥ 23.04 (lunar) has user with UID 1000

### ISSUE THREAD

**Issue by benz0li** [jupyter/docker-stacks#1877]
### What docker image(s) is this feature applicable to?

base-notebook

### What changes are you proposing?

This feature applies to image `docker-stacks-foundation` as soon as `ubuntu:24.04` is used as base image.

Proposal: Delete user with UID 1000 before https://github.com/jupyter/docker-stacks/blob/main/docker-stacks-foundation/Dockerfile#L70:

```bash
if $(grep -q 1000 /etc/passwd); then \
  userdel -r $(id -un 1000); \
fi && \
```

### How does this affect the user?

This feature ensures that `docker-stacks-foundation` successfully builds with upcoming `ubuntu:24.04`.

### Anything else?

```bash
docker run --rm -ti ubuntu:lunar cat /etc/passwd
```

```
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/run/ircd:/usr/sbin/nologin
_apt:x:42:65534::/nonexistent:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
ubuntu:x:1000:1000:Ubuntu:/home/ubuntu:/bin/bash
```

**Comment by benz0li** [comment]
@mathbunnyru This can already be added preventively.

**Comment by mathbunnyru** [comment]
Thank you, @benz0li!

We have more than a year before the ubuntu 24.04 release.
I suggest we wait because I think this might change before release, and we might not have this problem.

I don't like adding such a fix preventively, especially this early.
At the same time, I agree this is gonna be an issue if nothing changes and I think the fix you suggest is reasonable (though we might want to remove homedir as well).

**Comment by benz0li** [comment]
> I suggest we wait because I think this might change before release, and we might not have this problem.

Good point. This might change indeed.

> [...] (though we might want to remove homedir as well).

True. I have updated the command.

**Comment by benz0li** [comment]
Closed for now. I set a reminder for early 2024 😬.
