### ISSUE TITLE
[ENH] - Use "jupyter-lab" instead of "jupyter lab" in start-notebook.sh?

### ISSUE THREAD

**Issue by benz0li** [jupyter/docker-stacks#1878]
### What docker image(s) is this feature applicable to?

base-notebook

### What changes are you proposing?

I.e. use `jupyter-${DOCKER_STACKS_JUPYTER_CMD}` instead of `jupyter ${DOCKER_STACKS_JUPYTER_CMD}` at https://github.com/jupyter/docker-stacks/blob/main/base-notebook/start-notebook.sh#L22.

(`DOCKER_STACKS_JUPYTER_CMD="${DOCKER_STACKS_JUPYTER_CMD:=lab}"`)

### How does this affect the user?

Both commands work at this time. But maybe one will be deprecated at some point.

I did some tests with various future Debian-based distributions. And if I remember correctly, the `jupyter` executable was sometimes missing with only the `jupyter-*` executables available.

**Comment by mathbunnyru** [comment]
> Both commands work at this time. But maybe one will be deprecated at some point.

Do you have information if this is planned by jupyter?

> I did some tests with various future Debian-based distributions. And if I remember correctly, the jupyter executable was sometimes missing with only the jupyter-* executables available.

That's a bit surprising for me. If you install jupyter the way we do (using mamba), you will have the same package with the same content, so all executables should be there.

**Comment by benz0li** [comment]
> Do you have information if this is planned by jupyter?

No.

> That's a bit surprising for me. If you install jupyter the way we do (using mamba), you will have the same package with the same content, so all executables should be there.

I was surprised, too. I will try to reproduce.

**Comment by benz0li** [comment]
@mathbunnyru Dockerfile to reproduce:

```Dockerfile
ARG BASE_IMAGE=debian
ARG BASE_IMAGE_TAG=bookworm

FROM ${BASE_IMAGE}:${BASE_IMAGE_TAG}

ARG DEBIAN_FRONTEND=noninteractive

ARG JUPYTERHUB_VERSION=3.1.1
ARG JUPYTERLAB_VERSION=3.5.3

RUN apt-get update \
  && apt-get -y install --no-install-recommends \
    gcc \
    git \
    python3-dev \
    python3-pip \
    python3-venv \
    ## Problematic
    python3-gdal \
    python3-jinja2 \
    python3-lxml \
    python3-matplotlib \
    python3-owslib \
    python3-plotly \
    python3-psycopg2 \
    python3-pygments \
    python3-pyproj \
    python3-pyqt5 \
    python3-pyqt5.qsci \
    python3-pyqt5.qtmultimedia \
    python3-pyqt5.qtpositioning \
    python3-pyqt5.qtsql \
    python3-pyqt5.qtsvg \
    python3-pyqt5.qtwebkit \
    python3-sip \
    python3-yaml

RUN pip install \
    jupyterhub==${JUPYTERHUB_VERSION} \
    jupyterlab==${JUPYTERLAB_VERSION} \
    jupyterlab-git \
    jupyterlab-lsp \
    notebook \
    nbconvert \
    python-lsp-server[all]
```

👉 `/usr/local/bin/jupyter` is missing.

Build log: [docker-build_log.txt](https://github.com/jupyter/docker-stacks/files/10733501/docker-build_log.txt)

---

The *problematic* python packages installed via `apt` are required by another application [which has been build from source].

**Comment by benz0li** [comment]
`pip install --force` resolves this. Build log: [docker-build_log.txt](https://github.com/jupyter/docker-stacks/files/10733641/docker-build_log.txt)

@mathbunnyru Is this expected? I feel like a n00b...

**Comment by mathbunnyru** [comment]
@benz0li you were able to solve this, right? :)

**Comment by benz0li** [comment]
> @benz0li you were able to solve this, right? :)

Yes. But I do not know why exactly `pip install --force` is required.

**Comment by mathbunnyru** [comment]
`--force` is actually `--force-reinstall`.

```
  --force-reinstall           Reinstall all packages even if they are already up-to-date.
```

I recommend not using `apt` and `pip` at the same time because you will get an environment where one package can be installed multiple times.
I guess `force-reinstall` makes everything to be installed by `pip` in the right site-packages directory with correct versions, while not using this flag makes pip to try to use your apt installed versions sometimes, and this might be problematic.

**Comment by benz0li** [comment]
> I recommend not using `apt` and `pip` simultaneously because you will get an environment where one package can be installed multiple times.

This confirms what I secretly suspected. @mathbunnyru Thank you for the confirmation.
