### ISSUE TITLE
Image with jupyterHub

### ISSUE THREAD

**Issue by cairoapcampos** [jupyter/docker-stacks#1881]
### What docker image(s) is this feature applicable to?

datascience-notebook

### What changes are you proposing?

I would like an image with JupyterHub instead of JupyterLab.

### How does this affect the user?

It would enable a multi-user data science environment.

**Comment by mathbunnyru** [comment]
You need to use https://hub.docker.com/r/jupyterhub/jupyterhub image.
JupyterHub image doesn't have to contain all packages and so on, and it can spawn another image (for example datascience-notebook), which will actually contain all the packages.

**Comment by mathbunnyru** [comment]
Closing this one, as there was no response.
