### ISSUE TITLE
[BUG] - Recent images unable to be launched on Binder

### ISSUE THREAD

**Issue by tomyun** [jupyter/docker-stacks#1884]
### What docker image(s) are you using?

base-notebook

### Host OS system and architecture running docker image

Linux / amd64? (Binder)

### What Docker command are you running?

Local Docker works fine.

### How to Reproduce the problem?

Click the [Launch Binder](https://mybinder.org/v2/gh/jupyter/docker-stacks/main?urlpath=lab/tree/README.ipynb) button on the main page. Once the image is built, it will end up with an error message.

### Expected behavior

Should launch an instance of JupyterLab with no interrupt.

### Actual behavior

> 404 : Not Found
> You are requesting a page that does not exist!

### Anything else?

Other images derived from this repo seem like having the same issue. I got the exact same error with my custom image based on the latest version of `datascience-notebook`. IIRC, it used to work fine at least until a couple of months ago, so it likely has something to do with a recent change.

### Latest Docker version

- [X] I've updated my Docker version to the latest available, and the issue still persists

**Comment by mathbunnyru** [comment]
Thank you @tomyun.
It's an upstream issue and it's been resolved there, but not yet deployed.
I will pin older version of an image so it works for now.

https://github.com/jupyterhub/binderhub/issues/1634

**Comment by mathbunnyru** [comment]
Older versions works. I will update to a new one, when the upstream update mybinder.

**Comment by mathbunnyru** [comment]
This is fixed now and I've updated the image used in binder.
