### ISSUE TITLE
[BUG] - Stacks containing R 4.1.3 onwards cannot find its default packages

### ISSUE THREAD

**Issue by ddsouz5** [jupyter/docker-stacks#1885]
### What docker image(s) are you using?

datascience-notebook, r-notebook

### Host OS system and architecture running docker image

Ubuntu 20.04.2 LTS

### What Docker command are you running?

`docker run --rm -it -e OPENBLAS_NUM_THREADS=1 jupyter/r-notebook:r-4.1.3 R`

### How to Reproduce the problem?

Run the command below

`docker run --rm -it -e OPENBLAS_NUM_THREADS=1 jupyter/r-notebook:r-4.1.3 R`

### Command output

```bash session
R version 4.1.3 (2022-03-10) -- "One Push-Up"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-conda-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

During startup - Warning messages:
1: package ‘utils’ in options("defaultPackages") was not found 
2: package ‘stats’ in options("defaultPackages") was not found
```

### Expected behavior

If you used the the notebook with r-4.1.2, this didn't happen

Command
`docker run --rm -it -e OPENBLAS_NUM_THREADS=1 jupyter/r-notebook:r-4.1.2 R`

Output

`R version 4.1.2 (2021-11-01) -- "Bird Hippie"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-conda-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.
`

### Actual behavior

R version 4.1.3 (2022-03-10) -- "One Push-Up"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-conda-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

**During startup - Warning messages:
1: package ‘utils’ in options("defaultPackages") was not found 
2: package ‘stats’ in options("defaultPackages") was not found** 

### Anything else?

R 4.1.3 knows where the base libraries are but doesn't seem to load them on startup 

`.libPaths()`
`[1] "/opt/conda/lib/R/library"`

### Latest Docker version

- [X] I've updated my Docker version to the latest available, and the issue still persists

**Comment by mathbunnyru** [comment]
@ddsouz5 have you checked the latest image if it has this problem?
I mean, `r-4.1.3` was last built 5 months ago, so maybe the easiest way would be to update if it works.

**Comment by mathbunnyru** [comment]
```
~ > docker run --rm -it -e OPENBLAS_NUM_THREADS=1 jupyter/r-notebook R

R version 4.2.2 (2022-10-31) -- "Innocent and Trusting"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: aarch64-conda-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

>
```

**Comment by ddsouz5** [comment]
@mathbunnyru yes, all the images built after 4.1.2 have this problem

**# jupyter/r-notebook:r-4.2.2** 
`docker run --rm -it jupyter/r-notebook:r-4.2.2 R`
`
R version 4.2.2 (2022-10-31) -- "Innocent and Trusting"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-conda-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

During startup - Warning messages:
**1: package ‘utils’ in options("defaultPackages") was not found 
2: package ‘stats’ in options("defaultPackages") was not found** 
> 
`

**# jupyter/datascience-notebook:latest**
`docker run --rm -it -e OPENBLAS_NUM_THREADS=1 jupyter/datascience-notebook:latest R`
`
R version 4.2.2 (2022-10-31) -- "Innocent and Trusting"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-conda-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

During startup - Warning messages:
**1: package ‘utils’ in options("defaultPackages") was not found 
2: package ‘stats’ in options("defaultPackages") was not found** 
`

Thanks,

Darwin

**Comment by mathbunnyru** [comment]
It seems to work with the newest image. Could you please maybe start using it?

**Comment by mathbunnyru** [comment]
I've checked latest image under aarch64 and it works fine for me.
I will double check x86_64 image.

**Comment by ddsouz5** [comment]
Hmm, this must be an issue local to my computer if you're not having this problem. I ran your command and still get the issue. I'll do some debugging further. Thanks for checking.

**Comment by mathbunnyru** [comment]
@ddsouz5 I've just checked this on x86_64 for the latest image and it works fine fore me.
One thing you might need to add to make sure is `--pull always` to your command, so you're actually checking latest version (and not the one downloaded one some time ago with the same tag).

**Comment by ddsouz5** [comment]
Thanks. Looks like the issue was in my Docker version. Upgraded from 20.10 to 23.0.1 and I don't see the error anymore. Apologies, thought I was using the latest Docker version. Thanks again.

**Comment by mathbunnyru** [comment]
Great 👍 
Btw, this is exactly the reason we have `I've updated my Docker version to the latest available, and the issue still persists` 🙂
Sometimes old Docker versions create absolutely unexpected issues.

**Comment by ddsouz5** [comment]
Yes, you're absolutely correct. Lesson learnt
