### ISSUE TITLE
[ENH] - Tensorflow with GPUs support

### ISSUE THREAD

**Issue by GoldenCorgo** [jupyter/docker-stacks#1890]
### What docker image(s) is this feature applicable to?

tensorflow-notebook

### What changes are you proposing?

I propose to add GPUs support, because currently when I try to launch GPU calculations I get an error, I try to install inline Conda packages as described on tensor flow webpage, but it doesn't solve the problem.

### How does this affect the user?

- Users will be able to use GPUs
- Users will waste less time on trying to configure GPUs to work with TF

**Comment by mathbunnyru** [comment]
@GoldenCorgo is your issue the same as described [here](https://github.com/jupyter/docker-stacks/issues/1557)?

**Comment by mathbunnyru** [comment]
Closing as duplicate.

**Comment by benz0li** [comment]
@GoldenCorgo You may be interested in the [CUDA-enabled JupyterLab Python docker stack](https://github.com/b-data/jupyterlab-python-docker-stack/blob/main/CUDA.md), then:

> [...]
>
> ## Prerequisites
> 
> The same as the [JupyterLab Python docker stack](https://github.com/b-data/jupyterlab-python-docker-stack/blob/main/README.md#prerequisites) plus
> 
> * NVIDIA GPU
> * NVIDIA Linux driver
> * NVIDIA Container Toolkit
> 
> :information_source: The host running the GPU accelerated images only requires the NVIDIA driver, the CUDA toolkit does not have to be installed.
> 
> [...]
> 
> ## Similar projects
> 
> * [iot-salzburg/gpu-jupyter](https://github.com/iot-salzburg/gpu-jupyter)
> * [prp/jupyter-stack](https://gitlab.nrp-nautilus.io/prp/jupyter-stack)
> 
> **What makes this project different:**
> 
> 1. Multi-arch: `linux/amd64`, `linux/arm64/v8`
> 1. Derived from [`nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04`](https://hub.docker.com/r/nvidia/cuda/tags?page=1&name=11.8.0-cudnn8-devel-ubuntu22.04)
>     * including development libraries and headers
> 1. TensortRT and TensorRT plugin libraries
>     * including development libraries and headers
> 1. IDE: [code-server](https://github.com/coder/code-server) next to [JupyterLab](https://github.com/jupyterlab/jupyterlab)
> 1. Just Python – no [Conda](https://github.com/conda/conda) / [Mamba](https://github.com/mamba-org/mamba)
>
> See [Notes](https://github.com/b-data/jupyterlab-python-docker-stack/blob/main/NOTES.md) for tweaks, settings, etc.
