### ISSUE TITLE
Alternate image publish location (vs docker.io)

### ISSUE THREAD

**Issue by planetf1** [jupyter/docker-stacks#1891]
### What docker image(s) is this feature applicable to?

base-notebook

### What changes are you proposing?

Publish JupyterHub to an additional - or alternate - location

See https://web.docker.com/rs/790-SSB-375/images/privatereposfaq.pdf

- Docker has recently announced that 'free' organization repositories are going away in April. This will affect some open source projects that publish to dockerhub. I do not know if it affects Jupyter lab, or if the team has a paid account
- The docker faq does state that open source projects can apply to get a free accouunt
- Some projects publish to multiple repos. One option is 'quay.io'. I also know nginx use amazon. Even if docker.io is good for now, it may be worth considering publishing to an alternate repo

Ref: https://github.com/odpi/egeria/issues/7530

### How does this affect the user?

User would be unable to access a prebuilt docker stacks image

**Comment by mathbunnyru** [comment]
@planetf1 thank you for letting us know!

<img width="897" alt="Screenshot 2023-03-16 at 17 39 52" src="https://user-images.githubusercontent.com/12270691/225634872-fc2e0bc1-e9f0-4648-a315-ff414aff3cd9.png">

I've checked our `jupyter` org, and it tells `Docker Team` (not `Docker Free Team`).
We are also part of a Docker-Sponsored Open Source (DSOS) program for open source projects.

At the same time, I think it's a good idea now to start publishing to another place.
These are the places which we probably should change, it should not be too difficult.
https://github.com/jupyter/docker-stacks/blob/main/.github/workflows/docker-tag-push.yml
https://github.com/jupyter/docker-stacks/blob/main/tagging/apply_tags.py

**Comment by mathbunnyru** [comment]
> Publish JupyterHub to an additional - or alternate - location

JupyterHub images are located in another repo both in GitHub and DockerHub, and I have no information and/or control over these images.
At the same time `jupyterhub` is also part of DSOS program, afaik, so it should be fine.

**Comment by consideRatio** [comment]
@mathbunnyru do you have a quay.io account? I'll invite you to the quay.io jupyter organization if you wish to publish there as well or similar.

**Comment by mathbunnyru** [comment]
> @mathbunnyru do you have a quay.io account? I'll invite you to the quay.io jupyter organization if you wish to publish there as well or similar.

Currently, I don't. I will register today-tomorrow there and tell you when I do so.

**Comment by mathbunnyru** [comment]
@consideRatio done. `[mathbunnyru](https://quay.io/user/mathbunnyru)`

**Comment by mathbunnyru** [comment]
I guess we're not affected by this, since we haven't seen any negative feedback.

If any new contributor would like to work on this, I can offer help and tell which parts to look at.
Should be a nice first issue to resolve.

**Comment by covendev** [comment]
@mathbunnyru I would like to help with this, let me know the files that I have to look into

**Comment by mathbunnyru** [comment]
@covendev great!
Take a look at the article I wrote about how our build system works: https://dev.to/mathbunnyru/how-we-made-jupyter-docker-stacks-multi-arch-3ic1
You can skip to "How we did it" part, if you are not interested in history.

I think the important parts you are likely to change would be:
- [docker-tag-push.yml](https://github.com/jupyter/docker-stacks/blob/main/.github/workflows/docker-tag-push.yml) and corresponding [tagging/apply_tags.py](https://github.com/jupyter/docker-stacks/blob/main/tagging/apply_tags.py) file.
- [https://github.com/jupyter/docker-stacks/blob/main/.github/workflows/docker-merge-tags.yml] and the [tagging/merge_tags.py](https://github.com/jupyter/docker-stacks/blob/main/tagging/merge_tags.py) file.

The first one is responsible for downloading a saved image and a file containing a list of tags for this image and pushing a one-platform image with the correct tags.
The second one is responsible for collecting all possible tags which were pushed for `x86_64` and `aarch64` images and making `multi-arch` images by merging two single-platform images.

**Comment by mathbunnyru** [comment]
You would like to implement this for `quay.io`, right?
For now, you can use your personal quay.io account, if everything works fine there (it will probably require a bit of hardcoding in the mentioned .py files), before merge we will change it to jupyter and I will setup our quay.io images and will add necessary secrets to GitHub.

**Comment by covendev** [comment]
Yes will try on my personal quay.io, but are there like few test images that i can try because the free repository there would be public and wanted to know if pushing images to public repository would be fine or I can test on few sample images

**Comment by mathbunnyru** [comment]
Sure, you can publish images to your public repository.

**Comment by covendev** [comment]
I was slightly confused about the platform parameter here in docker-tag-push.yml workflow. It mentions it as input, but i'm unable to run a workflow call and if i tried to modify it on push, i wanted to know what specifically this parameter is.

**Comment by mathbunnyru** [comment]
> [docker-tag-push.yml](https://github.com/jupyter/docker-stacks/blob/main/.github/workflows/docker-tag-push.yml) is used to download built images (from GitHub artifacts), tag these images (using already computed tags) and then push these images (with correct tags). Note: This workflow only manipulates with one-platform image. We also add arch prefix for all the tags. For example, we push [jupyter/base-notebook:aarch64-python-3.10.8](https://hub.docker.com/r/jupyter/base-notebook/tags?page=1&name=aarch64-python-3.10.8) tag (and most likely, though not guaranteed [jupyter/base-notebook:x86_64-python-3.10.8](https://hub.docker.com/r/jupyter/base-notebook/tags?page=1&name=x86_64-python-3.10.8)).

This workflow is not meant to be called `on_push`, because it needs many GitHub artifacts to be already calculated.
And platform parameter takes either `aarch64` or `x86_64`.

**Comment by mathbunnyru** [comment]
@covendev any luck here?

**Comment by mathbunnyru** [comment]
I haven't heard any complaints about using DockerHub, so we don't need to publish to an alternative location.
So, closing this as not planned, because I don't see how our users will benefit from this, but we will have more maintaining to do.
