### ISSUE TITLE
[BUG] - Conflicting Information: Website mentions packages (Gadfly) that are not included in jupyter/datascience-notebook

### ISSUE THREAD

**Issue by t9ZFauRcOkl0UzNaP0sGRgvLbht4R7Qq** [jupyter/docker-stacks#1900]
### What docker image(s) are you using?

datascience-notebook

### Host OS system and architecture running docker image

Debian 11

### What Docker command are you running?

version:  "3"
services:
  datascience-notebook:
      image:            jupyter/datascience-notebook
      volumes:
        - /Absolute/Path/To/Where/Your/Notebook/Files/Will/Be/Saved:/home/jovyan/work
      ports:
        - 8888:8888

### How to Reproduce the problem?

using Gadfly
plot(y=[1,2,3])

....

import Pkg; Pkg.add("Gadfly")

### Command output

```bash session
ArgumentError: Package Gadfly not found in current path.
- Run `import Pkg; Pkg.add("Gadfly")` to install the Gadfly package.

Stacktrace:
 [1] macro expansion
   @ ./loading.jl:1163 [inlined]
 [2] macro expansion
   @ ./lock.jl:223 [inlined]
 [3] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:1144

.....



 Warning: could not download https://pkg.julialang.org/registries
│   exception = Failed to connect to pkg.julialang.org port 443 after 15222 ms: Connection timed out while requesting https://pkg.julialang.org/registries
└ @ Pkg.Registry /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/Pkg/src/Registry/Registry.jl:68
    Updating registry at `/opt/julia/registries/General.toml`
   Resolving package versions...
┌ Warning: could not download https://pkg.julialang.org/registries
│   exception = Failed to connect to pkg.julialang.org port 443 after 15203 ms: Connection timed out while requesting https://pkg.julialang.org/registries
└ @ Pkg.Registry /cache/build/default-amdci4-2/julialang/julia-release-1-dot-8/usr/share/julia/stdlib/v1.8/Pkg/src/Registry/Registry.jl:68
```

### Expected behavior

Information
"
Everything in the jupyter/scipy-notebook and jupyter/r-notebook images and their ancestor images

- rpy2 package
- The Julia compiler and base environment
- IJulia to support Julia code in Jupyter notebooks
- HDF5, **_Gadfly_**, RDatasets packages

"
provided at 
https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html

matches the actual packeges defined at

https://github.com/jupyter/docker-stacks/blob/main/datascience-notebook/Dockerfile

RUN julia -e 'import Pkg; Pkg.update()' && \
    julia -e 'import Pkg; Pkg.add("HDF5")' && \
    julia -e 'using Pkg; pkg"add IJulia"; pkg"precompile"' && \
    # move kernelspec out of home \
    mv "${HOME}/.local/share/jupyter/kernels/julia"* "${CONDA_DIR}/share/jupyter/kernels/" && \
    chmod -R go+rx "${CONDA_DIR}/share/jupyter" && \
    rm -rf "${HOME}/.local" && \
    fix-permissions "${JULIA_PKGDIR}" "${CONDA_DIR}/share/jupyter"

### Actual behavior

Gadfly is not included in this docker image.

### Latest Docker version

- [X] I've updated my Docker version to the latest available, and the issue still persists

**Comment by mathbunnyru** [comment]
Thank you for this issue!
Yes, I found a build where the package was removed.
I suppose RDatasets is not installed as well.

Since no one noticed this for around 5 years, I guess it's better to remove these packages from docs.
Could you make a PR, please?
