### ISSUE TITLE
[ENH] - Python 3.11 compatibility

### ISSUE THREAD

**Issue by djuarezg** [jupyter/docker-stacks#1910]
### What docker image(s) is this feature applicable to?

scipy-notebook

### What changes are you proposing?

- Make new images using Python 3.11, in order to profit from the new features and specially the performance improvements it comes with.

### How does this affect the user?

- Python 3.11 is widely available in all repos, it may be good to upgrade to it

**Comment by mathbunnyru** [comment]
@djuarezg the images are ready now.
