### ISSUE TITLE
all-spark-notebook hangs upon establishing SparkContext

### ISSUE THREAD

**Issue by EvanZ** [jupyter/docker-stacks#193]
> sc = pyspark.SparkContext('local[*]')

Just gives me the asterisk of death in the Jupyter notebook.

**Comment by parente** [comment]
What do you see in the console where you ran the notebook? Are you running the latest all-spark-notebook image? And which version of Python are you using in the notebook, 2 or 3?

**Comment by EvanZ** [comment]
Right now I’m having an issue even stopping the container it just holds (so I can’t even see what’s in the console). I wonder if it’s a memory issue? I noticed the image size is over 4.5 GB. Maybe that’s too big for the space I have allocated.
-evan

**Comment by parente** [comment]
Try without `local['*']`. Pass no parameters when you create the SparkContext.

**Comment by EvanZ** [comment]
Tried this and it still hangs and nothing is even being logged to the console:

➜  ~ docker run -it -p 8888:8888 jupyter/all-spark-notebook
[I 00:34:54.323 NotebookApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
[W 00:34:54.428 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 00:34:54.428 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.
[I 00:34:54.443 NotebookApp] Serving notebooks from local directory: /home/jovyan/work
[I 00:34:54.444 NotebookApp] 0 active kernels 
[I 00:34:54.444 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:8888/
[I 00:34:54.445 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 00:35:15.616 NotebookApp] Creating new notebook in 
[I 00:35:15.624 NotebookApp] Writing notebook-signing key to /home/jovyan/.local/share/jupyter/notebook_secret
[I 00:35:16.461 NotebookApp] Kernel started: 3c842ae9-08eb-47b6-8a36-7ba1418f7301
[I 00:35:31.241 NotebookApp] New terminal with automatic name: 1

**Comment by parente** [comment]
Are you running on VirtualBox? 

https://github.com/jupyter/docker-stacks/issues/75 was reported in the past. If you scroll through, you'll see various configs of docker and virtualbox that cause a hang.

**Comment by EvanZ** [comment]
Ah, that must be it. I’m running on VirtualBox. Thanks for pointing me in the right direction!
-evan

**Comment by parente** [comment]
No problem. Not sure where to put this so people can find it easily.

**Comment by EvanZ** [comment]
Ok! Finally just uninstalled and reinstalled Docker and now it works. :)
-evan
