### ISSUE TITLE
[BUG] - Not able to run notebook jobs 

### ISSUE THREAD

**Issue by go-kool** [jupyter/docker-stacks#1942]
### What docker image(s) are you using?

scipy-notebook

### Host OS system and architecture running docker image

jupyter/scipy-notebook:latest

### What Docker command are you running?

Hi Team,

I am using Docker jupyter/scipy-notebook image to run my code. I have requirement to create a job in notebook. But when I am trying to do it I am getting below error. Please help me on how to enable JavaScript on notebook.

![image](https://github.com/jupyter/docker-stacks/assets/44139805/19205e70-fd9a-4570-8e42-a61af0be25de)

### How to Reproduce the problem?

Pull the jupyter/scipy-notebook docker image and run it. And click on Notebooks jobs.

![image](https://github.com/jupyter/docker-stacks/assets/44139805/d7eb02c1-bd61-456f-be7a-54915c91fb0e)

### Actual behavior

Giving below error:

<!DOCTYPE HTML> <html> <head> <meta charset="utf-8"> <title>Jupyter Server</title> <link id="favicon" rel="shortcut icon" type="image/x-icon" href="/yoga/static/favicon.ico?v=50afa725b5de8b00030139d09b38620224d4e7dba47c07ef0e86d4643f30c9bfe6bb7e1a4a1c561aa32834480909a4b6fe7cd1e17f7159330b6b5914bf45a880"> <link rel="stylesheet" href="/yoga/static/style/bootstrap.min.css?v=0e8a7fbd6de23ad6b27ab95802a0a0915af6693af612bc304d83af445529ce5d95842309ca3405d10f538d45c8a3a261b8cff78b4bd512dd9effb4109a71d0ab" /> <link rel="stylesheet" href="/yoga/static/style/bootstrap-theme.min.css?v=8b2f045cb5b4d5ad346f6e816aa2566829a4f5f2783ec31d80d46a57de8ac0c3d21fe6e53bcd8e1f38ac17fcd06d12088bc9b43e23b5d1da52d10c6b717b22b3" /> <link rel="stylesheet" href="/yoga/static/style/index.css?v=30372e3246a801d662cf9e3f9dd656fa192eebde9054a2282449fe43919de9f0ee9b745d7eb49d3b0a5e56357912cc7d776390eddcab9dac85b77bdb17b4bdae" /> <meta http-equiv="X-UA-Compatible" content="IE=edge" /> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <style type="text/css"> /* disable initial hide */ div#header, div#site { display: block; } </style> </head> <body class="" data-jupyter-api-token="yoga" dir="ltr"> <noscript> <div id='noscript'> Jupyter Server requires JavaScript.<br> Please enable it to proceed. </div> </noscript> <div id="header" role="navigation" aria-label="Top Menu"> <div id="header-container" class="container"> <div id="jupyter_server" class="nav navbar-brand"><a href="/yoga/lab?token=yoga" title='dashboard'> <img src='/yoga/static/logo/logo.png?v=a2a176ee3cee251ffddf5fa21fe8e43727a9e5f87a06f9c91ad7b776d9e9d3d5e0159c16cc188a3965e00375fb4bc336c16067c688f5040c0c2d4bfdb852a9e4' alt='Jupyter Server' /> </a></div> </div> <div class="header-bar"></div> </div> <div id="site"> <div class="error"> <h1>404 : Not Found</h1> <p>You are requesting a page that does not exist!</p> </div> </div> <script type='text/javascript'> function _remove_token_from_url() { if (window.location.search.length <= 1) { return; } var search_parameters = window.location.search.slice(1).split('&'); for (var i = 0; i < search_parameters.length; i++) { if (search_parameters[i].split('=')[0] === 'token') { // remote token from search parameters search_parameters.splice(i, 1); var new_search = ''; if (search_parameters.length) { new_search = '?' + search_parameters.join('&'); } var new_url = window.location.origin + window.location.pathname + new_search + window.location.hash; window.history.replaceState({}, "", new_url); return; } } } _remove_token_from_url(); </script> </body> </html>

### Latest Docker version

- [X] I've updated my Docker version to the latest available, and the issue still persists

**Comment by mathbunnyru** [comment]
> Host OS system and architecture running docker image
> jupyter/scipy-notebook:latest

> What Docker command are you running

Please, provide the correct data here.

**Comment by mathbunnyru** [comment]
I also beleive you're not using the original `jupyter/scipy-notebook` image, but inherit from it, or install packages at runtime, because by default we don't provide `jupyter_scheduler`. So, please, tell us how you build your own image.

**Comment by go-kool** [comment]
I am running below Dockerfile.

FROM jupyter/scipy-notebook
ENV NB_USER="satya"
ENV JUPYTER_BASE_URL=/${NB_USER}
ENV JUPYTER_TOKEN=${NB_USER}
WORKDIR /home/${NB_USER}
RUN pip install mlflow==2.1.1 jupyter_scheduler==1.2.0
# Expose the Jupyter Notebook port
EXPOSE 8888
# Start Jupyter Notebook with custom base URL
CMD ["start-notebook.sh", "--no-browser","--NotebookApp.base_url=/satya"]

**Comment by go-kool** [comment]
Below is the Dockerfile I am running.

FROM jupyter/scipy-notebook
ENV NB_USER="satya"
ENV JUPYTER_BASE_URL=/${NB_USER}
ENV JUPYTER_TOKEN=${NB_USER}
WORKDIR /home/${NB_USER}
RUN pip install mlflow==2.1.1 jupyter_scheduler==1.2.0
# Expose the Jupyter Notebook port`
EXPOSE 8888
# Start Jupyter Notebook with custom base URL
CMD ["start-notebook.sh", "--no-browser","--NotebookApp.base_url=/satya"]

**Comment by go-kool** [comment]
> > Host OS system and architecture running docker image
> > jupyter/scipy-notebook:latest
> 
> > What Docker command are you running
> 
> Please, provide the correct data here.


Below is the Dockerfile I am running.
FROM jupyter/scipy-notebook
ENV NB_USER="satya"
ENV JUPYTER_BASE_URL=/${NB_USER}
ENV JUPYTER_TOKEN=${NB_USER}
WORKDIR /home/${NB_USER}
RUN pip install mlflow==2.1.1 jupyter_scheduler==1.2.0
EXPOSE 8888
CMD ["start-notebook.sh", "--no-browser","--NotebookApp.base_url=/satya"]

**Comment by mathbunnyru** [comment]
Thank you for the provided Dockerfile. Please, provide the correct data as well, for example:

> Host OS system and architecture running docker image

`Ubuntu 22.04 / aarch64`

> What Docker command are you running?

`docker run -it --rm -p 8888:8888 my-notebook`

**Comment by mathbunnyru** [comment]
I've built your Dockerfile and it doesn't work for me as well.
All you need to do is to install later versions of packages you use:
`RUN pip install mlflow==2.5.0 jupyter_scheduler==1.3.4`
