### ISSUE TITLE
Using my own certificate results in error

### ISSUE THREAD

**Issue by bdestombe** [jupyter/docker-stacks#196]
Hi all,
Currently I am having a lot of fun playing around with these Jupyter docker recipes, though I am kind of stuck on the following problem. Any help or pointers would be greatly appreciated.

I have Jupyterhub running, fully secured with let'sencrypt certificates. My jupyterhub_config.py includes the following two lines:
```python
c.JupyterHub.ssl_cert = '/etc/letsencrypt/live/domain/fullchain.pem'
c.JupyterHub.ssl_key = '/etc/letsencrypt/live/domain/privkey.pem'
```

However, when I am trying to use these docker recipes in combination with the fullchain.pem, I bump into problems. The self signed certificates work perfectly fine (when no PEM file is mounted using the docker-compose.yml file).

```python
notebook_1        | [E 18:53:41.368 NotebookApp] Exception in callback (<socket.socket fd=5, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 8888)>, <function wrap.<locals>.null_wrapper at 0x7fc0239a1ae8>)
notebook_1        |     Traceback (most recent call last):
notebook_1        |       File "/opt/conda/lib/python3.5/site-packages/tornado/ioloop.py", line 883, in start
notebook_1        |         handler_func(fd_obj, events)
notebook_1        |       File "/opt/conda/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
notebook_1        |         return fn(*args, **kwargs)
notebook_1        |       File "/opt/conda/lib/python3.5/site-packages/tornado/netutil.py", line 274, in accept_handler
notebook_1        |         callback(connection, address)
notebook_1        |       File "/opt/conda/lib/python3.5/site-packages/tornado/tcpserver.py", line 239, in _handle_connection
notebook_1        |         do_handshake_on_connect=False)
notebook_1        |       File "/opt/conda/lib/python3.5/site-packages/tornado/netutil.py", line 510, in ssl_wrap_socket
notebook_1        |         context = ssl_options_to_context(ssl_options)
notebook_1        |       File "/opt/conda/lib/python3.5/site-packages/tornado/netutil.py", line 487, in ssl_options_to_context
notebook_1        |         context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
notebook_1        |     ssl.SSLError: [SSL] PEM lib (_ssl.c:2824)
```

In my docker-compose.yml I added the following:
```
volumes:
      - /etc/letsencrypt/live/domain/fullchain.pem:/home/jovyan/.local/share/jupyter/notebook.pem
environment: 
      PASSWORD: 'YOURPASS'
      USE_HTTPS: 'yes'
```

When I log in into the docker container,  /home/jovyan/.local/share/jupyter/notebook.pem is correctly mounted and the content is similar as /etc/letsencrypt/live/domain/fullchain.pem on my own machine.

Am I correct that the only certificate that needs to be loaded into jupyter is the fullchain.pem?

Maybe this is related to NotebookApp.keyfile not being assigned in jupyter_notebook_config.py, which is the case in the `docker-stacks/examples/make-deploy/letsencrypt.makefile` file?

**Comment by parente** [comment]
Just to make sure I've got my bearings:

Are you using JupyterHub for external SSL termination with the Let's Encrypt cert and then trying to use self-signed certificates on the individual notebook servers behind the Jupyter Hub proxy?

**Comment by bdestombe** [comment]
Thanks for your quick response. But I just managed to get it all working. This is related to issue 190.

It should not be the fullchain.pem, but the privkey.pem and the fullchain.pem concatenated.

thus:
```
cat /etc/letsencrypt/live/<domain>/privkey.pem /etc/letsencrypt/live/<domain>/fullchain.pem > /etc/letsencrypt/live/<domain>/notebook.pem
```

And mount this file using:
```
volumes:
      - /etc/letsencrypt/live/domain/notebook.pem:/home/jovyan/.local/share/jupyter/notebook.pem
environment: 
      PASSWORD: 'YOURPASS'
      USE_HTTPS: 'yes'
```

Thanks again for your help
