### ISSUE TITLE
[BUG] - Jupyter refuse the connection inside iframe

### ISSUE THREAD

**Issue by AhmetTpc** [jupyter/docker-stacks#1963]
### What docker image(s) are you using?

base-notebook

### Host OS system and architecture running docker image

Ubuntu 20.04

### What Docker command are you running?

docker run --rm -p 8888:8888 -v /home/ahmet/Desktop/jpytr/:/home/jovyan/work/ jupyter/base-notebook

### How to Reproduce the problem?

every container start

### Command output

```bash session
Entered start.sh with args: jupyter lab
Executing the command: jupyter lab
[I 2023-08-11 07:37:06.647 ServerApp] Package jupyterlab took 0.0000s to import
[I 2023-08-11 07:37:06.667 ServerApp] Package jupyter_lsp took 0.0195s to import
[W 2023-08-11 07:37:06.667 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-08-11 07:37:06.674 ServerApp] Package jupyter_server_terminals took 0.0069s to import
[I 2023-08-11 07:37:06.678 ServerApp] Package nbclassic took 0.0027s to import
[W 2023-08-11 07:37:06.680 ServerApp] A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-08-11 07:37:06.680 ServerApp] Package notebook took 0.0000s to import
[I 2023-08-11 07:37:06.682 ServerApp] Package notebook_shim took 0.0000s to import
[W 2023-08-11 07:37:06.682 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-08-11 07:37:06.683 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2023-08-11 07:37:06.687 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-08-11 07:37:06.692 ServerApp] jupyterlab | extension was successfully linked.
[I 2023-08-11 07:37:06.695 ServerApp] nbclassic | extension was successfully linked.
[I 2023-08-11 07:37:06.699 ServerApp] notebook | extension was successfully linked.
[I 2023-08-11 07:37:06.700 ServerApp] Writing Jupyter server cookie secret to /home/jovyan/.local/share/jupyter/runtime/jupyter_cookie_secret
[I 2023-08-11 07:37:06.873 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-08-11 07:37:06.902 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-08-11 07:37:06.904 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2023-08-11 07:37:06.905 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-08-11 07:37:06.907 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.11/site-packages/jupyterlab
[I 2023-08-11 07:37:06.907 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2023-08-11 07:37:06.907 LabApp] Extension Manager is 'pypi'.
[I 2023-08-11 07:37:06.910 ServerApp] jupyterlab | extension was successfully loaded.
[I 2023-08-11 07:37:06.919 ServerApp] nbclassic | extension was successfully loaded.
[I 2023-08-11 07:37:06.925 ServerApp] notebook | extension was successfully loaded.
[I 2023-08-11 07:37:06.926 ServerApp] Serving notebooks from local directory: /home/jovyan
[I 2023-08-11 07:37:06.926 ServerApp] Jupyter Server 2.7.0 is running at:
[I 2023-08-11 07:37:06.926 ServerApp] http://057649d69189:8888/lab?token=a14b983e4eb1272d69b6beaa935e436796d9ddc5bfc5394d
[I 2023-08-11 07:37:06.926 ServerApp]     http://127.0.0.1:8888/lab?token=a14b983e4eb1272d69b6beaa935e436796d9ddc5bfc5394d
[I 2023-08-11 07:37:06.926 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2023-08-11 07:37:06.932 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///home/jovyan/.local/share/jupyter/runtime/jpserver-8-open.html
    Or copy and paste one of these URLs:
        http://057649d69189:8888/lab?token=a14b983e4eb1272d69b6beaa935e436796d9ddc5bfc5394d
        http://127.0.0.1:8888/lab?token=a14b983e4eb1272d69b6beaa935e436796d9ddc5bfc5394d
```

### Expected behavior

I use this image and ı want to add my website with iframe. Then ı will use jupyter notebook in my website.

### Actual behavior

Jupyter notebook refuse the connection in iframe. I didnt found why. I think because of  Jupyter config settings but i dont know how can ı solve this problem. Can you help me? 

![image](https://github.com/jupyter/docker-stacks/assets/58418202/9dfd3d07-9e9e-4acd-989d-73a79a53e231)

### Anything else?

I use this image and ı want to add my website with iframe but Jupyter Refuse the connection. I didnt found why and how can ı solve this problem? Can you help me?

### Latest Docker version

- [X] I've updated my Docker version to the latest available, and the issue still persists

**Comment by mathbunnyru** [comment]
Could you please try this answer?
https://github.com/jupyter/notebook/issues/284

**Comment by AhmetTpc** [comment]
I try this solution but nothing change. 
Here is the what i write jupyter_server_config.py ---->  c.ServerApp.tornado_settings = {'headers': { 'Content-Security-Policy': "frame-ancestors 'self' https://*.*"}

here is the output of logs:
![image](https://github.com/jupyter/docker-stacks/assets/58418202/f32a9b56-7f4d-41d8-95d8-667e982c378f)

**Comment by mathbunnyru** [comment]
@AhmetTpc I'm not really a web developer. Could you please tell me, how can I reproduce this on my machine?

**Comment by mathbunnyru** [comment]
> I try this solution but nothing change. Here is the what i write jupyter_server_config.py ----> c.ServerApp.tornado_settings = {'headers': { 'Content-Security-Policy': "frame-ancestors 'self' https://_._"}

This looks suspicious to me - shouldn't it be something like `https://*`?

**Comment by AhmetTpc** [comment]
Thx for reply, 
Firstly you can reproduce this like that (at least i try to use like that  in python-django-react project)

                    <div>
                        <iframe
                            src="http://127.0.0.1:8814/lab?token=4a912a58362a111d54b3a31e824f504ada0441d50fcb3e0b"
                            frameBorder="0"
                            style={{width: '100%', height: '500px'}}
                        ></iframe>


                    </div>
                    
Secondly i try https//* here is the result 
![first_way](https://github.com/jupyter/docker-stacks/assets/58418202/108e2e75-fdba-4bbd-8c24-91c5ce209726)
![frist_way_result](https://github.com/jupyter/docker-stacks/assets/58418202/70353f0f-7aef-441c-9dca-b083bfba8ae8)

And then ı try the only  "*" here is the result 
 
![second_way](https://github.com/jupyter/docker-stacks/assets/58418202/4d0bb769-6137-4479-866f-5d45948049b8)
![second_way_result](https://github.com/jupyter/docker-stacks/assets/58418202/e112af6d-0e14-470c-99f7-6033e88129ad)

Lastly i try this in my localhost project how can i write like that ;
"https://my-website-url.com/jupyter" (this is the your stackowerflow refrence example)
localhost:8000/#/ (this is the where i try add iframe)

**Comment by mathbunnyru** [comment]
```
Refused to frame 'http://127.0.0.1:8814/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors *". Note that '*' matches only URLs with network schemes ('http', 'https', 'ws', 'wss'), or URLs whose scheme 
```

**Comment by mathbunnyru** [comment]
@minrk may I ask you to help here?
I lack knowledge of CSP and its rules. I've made several attempts to make it work with docker, but it doesn't work for me.

**Comment by minrk** [comment]
I think you need to make sure the full `protocol://host[:port]` is in the frame-ancestors. I was able to embed the server in an iframe with this server config:

```python
c.ServerApp.tornado_settings = {
    'headers': {
        'Content-Security-Policy': "frame-ancestors  http://test-page.local.minrk.net:8000"
    }
}

# for testing:
c.ServerApp.token = "84b2542e5f7a19aa49d57e1a"
c.ServerApp.ip = '0.0.0.0'
```

and this HTML served at `http://test-page.local.minrk.net:8000/test-page.html` (via `python3 -m http.server`):

```html
<div>
  <iframe
    src="http://docker.local.minrk.net:9999/lab?token=84b2542e5f7a19aa49d57e1a"
    frameborder="0"
    style="width: 100%; height: 500px"
  ></iframe>
</div>
```

where the server is started with:

```
docker run --rm -it -v$PWD:/io -w /io -p9999:8888 jupyter/base-notebook:2023-08-14 jupyter server --config jupyter_server_config.py
```

Note that `*.local.minrk.net` all map to 127.0.0.1, so I can test with any number of domains. Note that only `test-page.local.minrk.net:8000` works, any other domain or port (e.g. `http://test-other-page.local.minrk.net:8000`) won't, even if they map to the same ip.

(also, probably don't test with my domains, since I control them and could steal your stuff by changing the DNS).

**Comment by AhmetTpc** [comment]
I change my server config py;

c.ServerApp.tornado_settings = {
    'headers': {
        'Content-Security-Policy': "frame-ancestors http://localhost:8815"
    }
}
c.ServerApp.token="96ac1f504026b54875ea411ec916adb511f133e1614b3bdd"
c.ServerApp.ip='0.0.0.0'

and i write this code for httpserver( i m not sure this code because i didnt use httpserver before);

from http.server import BaseHTTPRequestHandler, HTTPServer


class MyHTTPRequestHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path == '/':
            self.send_response(200)
            self.send_header('Content-type', 'text/html')
            self.end_headers()

            iframe_url = 'http://127.0.0.1:8814/lab?token=96ac1f504026b54875ea411ec916adb511f133e1614b3bdd'  
            iframe_code = f'<iframe src="{iframe_url}" width="800" height="600"></iframe>'

            response_content = f'''
                <html>
                <head>
                <title>IFrame example</title>
                </head>
                <body>
                {iframe_code}
                </body>
                </html>
            '''
            self.wfile.write(response_content.encode())


def run_server():
    server_address = ('', 8815)
    httpd = HTTPServer(server_address, MyHTTPRequestHandler)
    httpd.serve_forever()


if __name__ == '__main__':
    run_server()

And this is the my docker run command;

 docker run --rm -p 8814:8888 -v /home/ahmet/Desktop/jpytr/:/home/jovyan/work/ jupyter/base-notebook


I check localhost:8815 for iframe because httpserver shows here and then i want to use in my project. But localhost:8815  have refuse connection error still. 

![image](https://github.com/jupyter/docker-stacks/assets/58418202/87d87f43-0fa9-4936-a982-e1f517e61b9b)

Any problem with any thing? Anything wrong with my code or something ?

**Comment by minrk** [comment]
> and i write this code for httpserver

For clarity, I wrote a `page.html` and served it from the local directory with `python3 -m http.server` in a terminal, I didn't write any Python code against `http.server`.

What does the browser console say for the error?

**Comment by AhmetTpc** [comment]
Is this wrong way about httpserver? Can i use my way or i have to use your way ?

Here is the console log;

![image](https://github.com/jupyter/docker-stacks/assets/58418202/1820294c-78e9-46a5-8550-65ebdc46bd18)

**Comment by minrk** [comment]
It means your jupyter_server_config.py hasn't been loaded. Where did you put it? If it's not in the default config path, you can load a config file explicitly with `jupyter server --config /path/to/your/jupyter_server_config.py`

**Comment by AhmetTpc** [comment]
I use this docker command;
 " docker run --rm -p 8814:8888 -v /home/ahmet/Desktop/jpytr/:/home/jovyan/work/ jupyter/base-notebook jupyter server --config /home/ahmet/Desktop/jpytr/only/jupyter_server_config.py"  and this is the logs,
 
![image](https://github.com/jupyter/docker-stacks/assets/58418202/abff2b17-ecf7-4917-93a8-8cf2128047f9)


this is the config file content;
```python
# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
# mypy: ignore-errors
import os
import stat
import subprocess

from jupyter_core.paths import jupyter_data_dir

c = get_config()  # noqa: F821
c.ServerApp.ip = "0.0.0.0"
c.ServerApp.open_browser = True
c.ServerApp.tornado_settings = {
    'headers': {
        'Content-Security-Policy': "frame-ancestors http://localhost:8815"
    }
}
c.ServerApp.allow_iframe=True
# to output both image/svg+xml and application/pdf plot formats in the notebook file
c.InlineBackend.figure_formats = {"png", "jpeg", "svg", "pdf"}

# https://github.com/jupyter/notebook/issues/3130
c.FileContentsManager.delete_to_trash = False

# Generate a self-signed certificate
OPENSSL_CONFIG = """\
[req]
distinguished_name = req_distinguished_name
[req_distinguished_name]
"""
if "GEN_CERT" in os.environ:
    dir_name = jupyter_data_dir()
    pem_file = os.path.join(dir_name, "notebook.pem")
    os.makedirs(dir_name, exist_ok=True)

    # Generate an openssl.cnf file to set the distinguished name
    cnf_file = os.path.join(os.getenv("CONDA_DIR", "/usr/lib"), "ssl", "openssl.cnf")
    if not os.path.isfile(cnf_file):
        with open(cnf_file, "w") as fh:
            fh.write(OPENSSL_CONFIG)

    # Generate a certificate if one doesn't exist on disk
    subprocess.check_call(
        [
            "openssl",
            "req",
            "-new",
            "-newkey=rsa:2048",
            "-days=365",
            "-nodes",
            "-x509",
            "-subj=/C=XX/ST=XX/L=XX/O=generated/CN=generated",
            f"-keyout={pem_file}",
            f"-out={pem_file}",
        ]
    )
    # Restrict access to the file
    os.chmod(pem_file, stat.S_IRUSR | stat.S_IWUSR)
    c.ServerApp.certfile = pem_file

# Change default umask for all subprocesses of the Server if set in the environment
if "NB_UMASK" in os.environ:
    os.umask(int(os.environ["NB_UMASK"], 8))
```

and i try to open links where is the docker logs firstly without iframe but it didnt open anyway here is the result;

![image](https://github.com/jupyter/docker-stacks/assets/58418202/c2b10c98-8ee7-48f9-8e10-333b626e140a)

**Comment by minrk** [comment]
Unfortunately, jupyter doesn't log when specified config files aren't found. If you add `--debug`, you'll see it.

But you've specified the path `/home/ahmet/Desktop/jpytr/only/jupyter_server_config.py` which doesn't exist in the container, it's at `/home/jovyan/work/only/jupyter_server_config.py`. you can add print statements to your config file to prove to yourself that the file is loaded.

**Comment by AhmetTpc** [comment]
A lot of thanks dude finally work in iframe but i have kernel error. I can open jupiter url and i can use python on my local everything is ok but in iframe i didn't use python because kernel can't connect :/ 

![image](https://github.com/jupyter/docker-stacks/assets/58418202/743ced48-60a4-41d7-9faf-aaa57fc2b9a6)

**Comment by AhmetTpc** [comment]
I changed this to that **c.ServerApp.disable_check_xsrf = True** (in config file) and then kernel started,  everythink ok. Thanks for helping guys.
