### ISSUE TITLE
Issues installing module

### ISSUE THREAD

**Issue by ahdee** [jupyter/docker-stacks#1965]
### What docker image(s) are you using?

docker-stacks-foundation

### Host OS system and architecture running docker image

jupyter/datascience-notebook:2023-07-31

### What Docker command are you running?

docker run -it --rm -p 1007:8888 \
jupyter/datascience-notebook:2023-07-31

### How to Reproduce the problem?

I tried installing a module: 

```
!pip install PySeedRecover
import sys
sys.executable
```
module sucesfully intalls and shows that it is on: '/opt/conda/bin/python'

tried again with 
```
!/opt/conda/bin/pip install PySeedRecover
```
however I still get 

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[18], line 1
----> 1 import PySeedRecover

ModuleNotFoundError: No module named 'PySeedRecover'

```

when I tried, 
```
!pip show PySeedRecover


```

it shows that it was installed on Location: /opt/conda/lib/python3.11/site-packages

so I 
```
import sys
sys.path.append('/opt/conda/lib/python3.11/site-packages')
```
but same error. 

### Actual behavior

I tried install a module and it looks like its installed correctly however when I try to import it reads that the module is not found. 

### Latest Docker version

- [X] I've updated my Docker version to the latest available, and the issue still persists

**Comment by ahdee** [comment]
I also tried 
```
import sys

!{sys.executable} -m pip install PySeedRecover
``` 

however it reads 

```
import sys

!{sys.executable} -m pip install PySeedRecover

```
 but yet when I try to import it it says module not found, this was the same even in the terminal.

**Comment by mathbunnyru** [comment]
I think it should be `import seedrecover`, not `import PySeedRecover`.

**Comment by mathbunnyru** [comment]
And tip for a better setup - do not install python packages inside notebook. It's better to create a child docker image and use it (this way you can easily restart your image and you won't need to reinstall all the packages again).
https://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html#using-mamba-install-recommended-or-pip-install-in-a-child-docker-image

**Comment by ahdee** [comment]
@mathbunnyru ah I see, silly mistake, i terms of best practice, could'nt I just do something like this? I like the idea of child docker however for simplicity can't I just do something like this? 

```
import sys
sys.path.append('/custom/')
```
the only thing is that I need to run this every startup, so perhaps put this into ~/.bashrc which I have mounted as volume so both would be permanent?

**Comment by mathbunnyru** [comment]
> @mathbunnyru ah I see, silly mistake, in terms of best practice, couldn't I just do something like below? I like the idea of child docker however for simplicity can't I just do something like this?
> 
> ```
> import sys
> sys.path.append('/custom/')
> ```
> 
> the only thing is that I need to run this every startup, so perhaps put this into ~/.bashrc which I have mounted as volume so both would be permanent?

I don't think it's simpler.
Also, you want to add python code to `~/.bashrc`, which also won't work.
And, you will need somehow to make this code run for every python script you run and for every notebook.
Generally speaking, appending to `sys.path` is not also a recommended thing.

I think, creating a child image and building it once is a much better approach.

**Comment by ahdee** [comment]
@mathbunnyru I see thank you. I'm not familiar with docker so would have to take some time to get this to work but I agree what you said.
