### ISSUE TITLE
Cannot get passwordless sudo to work. 

### ISSUE THREAD

**Issue by ahdee** [jupyter/docker-stacks#1966]
### What docker image(s) are you using?

datascience-notebook

### Host OS system and architecture running docker image

Ubuntu 22.04.2

### What Docker command are you running?

```

docker run -it --rm -p 1007:8888 \
--user root \
-e NB_USER="test" \
-e CHOWN_HOME=yes \
-e GRANT_SUDO=yes \
-w "/home/${NB_USER}" \
jupyter/datascience-notebook:2023-07-31

```

### How to Reproduce the problem?

docker loads up fine however in terminal I can't get sudo to work, 
sudo <command> and a prompt comes up for a pwd,  I just push enter for password, and it would fail 

```
(base) test@1fd83ee2155e:/home$ sudo ls
[sudo] password for test: 
Sorry, try again.
[sudo] password for test: 
```

### Actual behavior

I tried using `-e GRANT_SUDO=yes`
however when I try anything with sudo it would ask for a password, however when I just push return it would fail. My understanding is that the pwd should be blank? 

### Latest Docker version

- [X] I've updated my Docker version to the latest available, and the issue still persists

**Comment by ahdee** [comment]
Also the command groups shows that user was not added to sudo 
```
(base) test@1fd83ee2155e:/home$ groups
users

```

**Comment by mathbunnyru** [comment]
Your command works for me and `sudo` also works. Maybe you're in the terminal from previous `docker run` where you didn't enable sudo?

**Comment by mathbunnyru** [comment]
Also, I think we have a bug in our documentation
`-w "/home/${NB_USER}"` doesn't do what people think it does
bash interprets `${NB_USER}` on the host machine, this env variable is not and shouldn't be set on a host machine, so this line is equivalent to `-w "/home/"`.
So, if you want to change your workdir, you will have to be explicit and say `-w /home/test` in your example.

**Comment by mathbunnyru** [comment]
I fixed the docs: https://github.com/jupyter/docker-stacks/pull/1967

**Comment by mathbunnyru** [comment]
@ahdee could you please fix your command and check once again, if you still have the issue?

**Comment by ahdee** [comment]
@mathbunnyru yes that works perfectly now. Thank you so much for the prompt reply.
