### ISSUE TITLE
A connection to the notebook server could not be established. The notebook will continue trying to reconnect, but until it does, you will NOT be able to run code. Check your network connection or notebook server configuration.

### ISSUE THREAD

**Issue by krautt** [jupyter/docker-stacks#199]
Hi all, I'm receiving the following error:

 "A connection to the notebook server could not be established. The notebook will continue trying to reconnect, but until it does, you will NOT be able to run code. Check your network connection or notebook server configuration" 
when i start docker with -e USE_HTTPS=yes:

sudo docker run -d -p 8888:8888 -v /home/myaccount/work:/home/jovyan/work -e PASSWORD='password' -e USE_HTTPS=yes  jupyter/datascience-notebook start-notebook.sh

BUT... if i start it without -e USE_HTTPS=yes, then it works just fine: 

sudo docker run -d -p 8888:8888 -v /home/myaccount/work:/home/jovyan/work -e PASSWORD='password'   jupyter/datascience-notebook start-notebook.sh

 I work for a security team so i sort of have to use HTTPS to encrypt that password else i'll be tormented:)

**Comment by krautt** [comment]
btw,  i did a chown -R 1000:1000 /home/user/work as well.

**Comment by parente** [comment]
Are you using Safari by chance?

**Comment by krautt** [comment]
chrome on windows 7.  Also tried Firefox with same effect.

**Comment by parente** [comment]
Interesting. I've seen this happen with Safari. It refuses to connect a websocket to a backend when you're using self-signed certs. I've never seen it with Chrome or FF, but maybe that's changed recently ...

Looks like you pulled whatever the latest was of the image. Can you paste the Docker image ID for me(though we haven't touched anything related to the SSL in ages).

**Comment by krautt** [comment]
REPOSITORY                     TAG                 IMAGE ID
 CREATED             SIZE
ubuntu                         latest              c5f1cf30c96b        47
hours ago        120.7 MB
jupyter/datascience-notebook   latest              137a50334d59        3
weeks ago         4.934 GB

**Comment by parente** [comment]
Your image isn't that old. 

I gave the latest a shot with your run command with no problems, but without the host mount (which I don't have).

I've had issues in the past with permissions on host mounts causing notebook errors that don't really reflect the underlying problem. The user in the container has UID 1000 by default. Does that UID have access on the host directory you're mounting?

**Comment by krautt** [comment]
It was giving me permission issues so i have since included the following
in the docker run statement:

--user=root  -e NB_UID=8858

**Comment by parente** [comment]
So switching to UID 8858 fixed the problem, where 8858 is the ID of a user on your host system that has access to the `/home/myaccount/work` folder?

**Comment by krautt** [comment]
correct.

**Comment by parente** [comment]
Glad to hear it. 👍  

I've added a note to the recipes page linking permission and connection errors to host mount permissions. 

https://github.com/jupyter/docker-stacks/wiki/Docker-recipes#host-volume-mounts-and-notebook-errors

**Comment by bright1993ff66** [comment]
I have the same problem! This problem appeared when I used Google chrome. However, if I changed the default browser from Google to Microsoft Edge, this problem disappeared and everything was OK. I am confused.....So is it browser's fault?

**Comment by brntsllvn** [comment]
confirmed...Chrome curiously cannot connect. Edge works fine.

**Comment by VijaySaiProfessional** [comment]
Hi everyone. I'm facing the same issue. I have edge and chrome browsers on my PC. So I tried running on both. I still keep getting the same error on both after running for around 10-12 hours. Could anyone suggest me a fix?

**Comment by kkingkill** [comment]
Hi, everyone, I use Python 3.7,  at first I use chrome and encounter the issue, and then I use safari, safari can work.  But suddenly, I remember my chrome uses proxy, so I close the proxy of chrome, and chrome can also work fine, **so you can check if your chrome use proxy by default.**

**Comment by vikasavnish** [comment]
I had the same problem . I have reinstall tornado server( downgrade from v6 to v5.1.1) and it get solved

I posted solution [here](https://www.servloci.com/a-connection-to-the-notebook-server-could-not-be-established-the-notebook-will-continue-trying-to-reconnect-but-until-it-does-you-will-not-be-able-to-run-code-check-your-network-connection-or-note/)

**Comment by mindej** [comment]
@vibhutisawant Thank you very match it worked for me.
Jupiter right now do not work with tornado server version 6.0.1

**Comment by Aravinviju** [comment]
I use jupyter in the GCP instance (ubuntu). It was perfectly working till yesterday with tornado==6.0.2. Suddenly today morning this error started showing up and I'm puzzled with it.
I have tried downgrading the tornado versions with all you accepted solutions above but non works for me.
Any help on this would be great!

Thanks
Arav

**Comment by mindej** [comment]
@Aravinviju You have to downgrade to 5.x

**Comment by VijaySaiProfessional** [comment]
If you are using n_jobs=-1 parameter, in your code, kindly make sure you
leave out one core.
For example, if your processor has 4 cores, then using n_jobs=-1 uses all
the 4 cores. Hence you have to leave out at least one core do that this
left out one core make sures there is no break in the internet connectivity.
Please use n_jobs=3 (if your processor has 4 cores)
Use n_jobs =7 (if your processor has 8 cores)

Regards,
Vijay.

**Comment by Aravinviju** [comment]
> @Aravinviju You have to downgrade to 5.x

Hi, I have already tried downgrading the version to 5.1.1, but it still gives me the same error.
I aslo tried reinstalling anaconda back again from the beginning but no joy!

Thanks
Arav

**Comment by jsr-magic** [comment]
A connection to the notebook server could not be established. The notebook will continue trying to reconnect. Check your network connection or notebook server configuration.

**Comment by sunnykevin19** [comment]
Facing the same problem: - 
A connection to the notebook server could not be established. The notebook will continue trying to reconnect. Check your network connection or notebook server configuration ??
