### ISSUE TITLE
[BUG] - nodejs pinned in python-3.10 image

### ISSUE THREAD

**Issue by rokroskar** [jupyter/docker-stacks#1990]
### What docker image(s) are you using?

base-notebook

### Host OS system

Ubuntu:22, Mac arm64

### Host architecture

x86_64

### What Docker command are you running?

```
docker run --rm -ti jupyter/base-notebook:python-3.10 cat /opt/conda/conda-meta/pinned
```

### How to Reproduce the problem?

see above

### Expected behavior

Only see the python version pinned

### Actual behavior

`jupyter/base-notebook:python-3.10` image has the following pinned in `/opt/conda/conda-meta/pinned`:

```
python 3.10.11
nodejs >=18.0
```

### Anything else?

This seems to be the only image version where nodejs is pinned - if I repeat the same with `latest`, `python-3.8`, `python-3.9` only the python version is pinned. This is causing problems trying to install additional packages that have different nodejs requirements. 

So, the question is whether this pinned version is required? It seems to potentially be related to https://github.com/jupyter/docker-stacks/pull/1902

### Latest Docker version

- [X] I've updated my Docker version to the latest available, and the issue still persists

**Comment by mathbunnyru** [comment]
Hi @rokroskar.

Unfortunately, this is not the currently supported python version, so we won't be able to update the image `jupyter/base-notebook:python-3.10`.

On the other hand, you can easily fix it on your own:
1. You can inherit an image from `jupyter/base-notebook:python-3.10` and remove the line from `/opt/conda/conda-meta/pinned`.
2. Or you can use the image which was pushed before https://github.com/jupyter/docker-stacks/pull/1902 was merged. The merge happened on 26th May, I've searched our images and it seems we also built our images May 25th, so you can use `jupyter/base-notebook :2023-05-25`: https://hub.docker.com/r/jupyter/base-notebook/tags?page=1&name=2023-05-25

Please, tell me if this helps.

**Comment by mathbunnyru** [comment]
```
~ > docker run -it --rm jupyter/base-notebook:2023-05-25 cat /opt/conda/conda-meta/pinned
python 3.10.11
```

Second options seems to work fine for me.

**Comment by rokroskar** [comment]
Hi @mathbunnyru thanks for the quick response - sure, I can do that. I was also more wondering if the fact that this pin is now gone is reverting the fix to #1901

**Comment by mathbunnyru** [comment]
I reverted the fix, because correct nodejs version was being installed by default so we no longer needed this fix.
https://github.com/jupyter/docker-stacks/pull/1914

**Comment by rokroskar** [comment]
Not sure how your image management works, but it seems that if this is causing unnecessary issues, an update to that tag could be pushed. I understand that's a potential can of worms though.

**Comment by rokroskar** [comment]
Yep, that makes sense, thanks!
