### ISSUE TITLE
Mounted folder is empty after running docker container

### ISSUE THREAD

**Issue by star2k** [jupyter/docker-stacks#1991]
### What docker image(s) are you using?

datascience-notebook

### Host OS system

ubuntu22

### Host architecture

aarch64

### What Docker command are you running?

docker run -p 8003:8888 --name 'jupyter_notebook' -dit -e JUPYTER_ENABLE_LAB=yes -v /root/docker/jupyter:/home/jovyan/work jupyter/datascience-notebook:latest

### How to Reproduce the problem?

 I specify the environment location here“ -v /root/docker/jupyter:/home/jovyan/work”, but after saving the file, the folder has no content.

### Actual behavior

 I specify the environment location here“ -v /root/docker/jupyter:/home/jovyan/work”, but after saving the file, the folder has no content.

### Latest Docker version

- [X] I've updated my Docker version to the latest available, and the issue still persists

**Comment by mathbunnyru** [comment]
Hi @star2k,

It is likely to be permission issues with the dir you're mounting.
Could you please try using this troubleshooting guide?
https://jupyter-docker-stacks.readthedocs.io/en/latest/using/troubleshooting.html

**Comment by mathbunnyru** [comment]
It seems that a user is not interested in this issue anymore.
So, closing this issue.
