### ISSUE TITLE
Pluto Notebook doesn't work on datascience-notebook

### ISSUE THREAD

**Issue by jlphillipsphd** [jupyter/docker-stacks#1992]
### What docker image(s) are you using?

datascience-notebook

### Host OS system

Debian 12 and Ubuntu 22.04

### Host architecture

x86_64

### What Docker command are you running?

docker run -it --rm -p 8888:8888 --user root -e GRANT_SUDO=yes -v /home/jphillips:/home/jovyan/work jupyter/datascience-notebook:2023-09-04

### How to Reproduce the problem?

1. Visit the provided JLab link - JupyterLab opens (working)
2. Visit the Pluto Notebook link on the Launcher (tab opens)
3. Page for pluto server seems to be broken/not working ![image](https://github.com/jupyter/docker-stacks/assets/5066775/f703234e-caff-4bd0-b0dd-5033ea5b2a4b)
4. Click on "Create a new notebook" and I just get a 500 error 
![image](https://github.com/jupyter/docker-stacks/assets/5066775/36c6dbba-fa4a-4ce3-a990-0848a762f621)

### Command output

```bash session
docker run -it --rm -p 8888:8888 --user root -e GRANT_SUDO=yes -v /home/jphillips:/home/jovyan/work jupyter/datascience-notebook:2023-09-04
```

### Expected behavior

Expected Pluto Notebook server to open since it's a part of this stack...

### Actual behavior

Non-working Pluto Server.

### Anything else?

Just wanting to try Pluto Notebook - don't feel like I can use datascience-notebook as a starting point for my stacks because it has a prominent non-functioning component.

### Latest Docker version

- [X] I've updated my Docker version to the latest available, and the issue still persists

**Comment by jlphillipsphd** [comment]
I've attached the traceback from the JLab server
[traceback-pluto.txt](https://github.com/jupyter/docker-stacks/files/12577119/traceback-pluto.txt)

**Comment by mathbunnyru** [comment]
I only have my M2 (aarch64) Mac currently, your command seems to work fine for me.
<img width="1470" alt="Screenshot 2023-09-12 at 00 08 56" src="https://github.com/jupyter/docker-stacks/assets/12270691/65c8cfa7-485f-4822-86fe-30f8090487fb">

Could you please try to install the official version of the Docker Engine?
https://docs.docker.com/engine/install/debian/
I've seen some weird things happening with distribution of Docker packages, provided by fistro maintainers.

**Comment by jlphillipsphd** [comment]
That's what I use...
```
jphillips@asyncritus:~$ cat /etc/apt/sources.list.d/docker.list
deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu       jammy stable
jphillips@asyncritus:~$ docker version
Client: Docker Engine - Community
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:31:44 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:44 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by jlphillipsphd** [comment]
Sorry, just hit the wrong button...

**Comment by jlphillipsphd** [comment]
I tried clearing out the cache and history on Chrome, but still have the issue... however, I sometimes see this when I request to "Create a new notebook" on the (still broken, missing images/says loading...) Pluto page:
![image](https://github.com/jupyter/docker-stacks/assets/5066775/4a5a077f-4a1e-4b73-ac7b-f5b2521e9191)

**Comment by mathbunnyru** [comment]
Could you please also try private Chrome tab with all extensions disabled?

I don't know what might help if it's a libc issue - maybe upgrading your OS, or trying images which were built with previous Julia versions.

**Comment by jlphillipsphd** [comment]
OK, so image tag `2023-09-04` appears to be the broken image for me... I had luck with both `ubuntu-22.04` and `2023-09-11`

I don't know why the discrepancy in these versions, but I guess it was just a temporary issue. Here are those image hashes if that helps in the future in some way...

```
jphillips@asyncritus:~$ docker pull jupyter/datascience-notebook:ubuntu-22.04
ubuntu-22.04: Pulling from jupyter/datascience-notebook
Digest: sha256:133c934126ec70c4277aeee5ebc0be3f5a08cefd952ad89d193a9ee109857b4d
Status: Image is up to date for jupyter/datascience-notebook:ubuntu-22.04
docker.io/jupyter/datascience-notebook:ubuntu-22.04
jphillips@asyncritus:~$ docker pull jupyter/datascience-notebook:2023-09-04
2023-09-04: Pulling from jupyter/datascience-notebook
Digest: sha256:cce1245214ea3ca3978f1f95731331daa2ef57b0b56130b2cd93c4bfb4cd5340
Status: Image is up to date for jupyter/datascience-notebook:2023-09-04
docker.io/jupyter/datascience-notebook:2023-09-04
jphillips@asyncritus:~$ docker pull jupyter/datascience-notebook:2023-09-11
2023-09-11: Pulling from jupyter/datascience-notebook
Digest: sha256:133c934126ec70c4277aeee5ebc0be3f5a08cefd952ad89d193a9ee109857b4d
Status: Image is up to date for jupyter/datascience-notebook:2023-09-11
docker.io/jupyter/datascience-notebook:2023-09-11
```

Thank you for the help @mathbunnyru !

**Comment by mathbunnyru** [comment]
Thank you @jlphillipsphd!

**Comment by andreasskeidsvoll** [comment]
I unfortunately get the same bug on new versions of the image (e.g. `2023-10-23`), and downgrading to `2023-09-04` seems to solve the problem.

**Comment by mathbunnyru** [comment]
@andreasskeidsvoll could you please create a new issue?
