### ISSUE TITLE
adjusting the timezone

### ISSUE THREAD

**Issue by marconr9** [jupyter/docker-stacks#1996]
### What docker image(s) is this feature applicable to?

all-spark-notebook

### What change(s) are you proposing?

My question is about changing the timezone.
Is possible to change the timezone ?
thanks

### How does this affect the user?

make it possible to change the timezone.

### Anything else?

nope

**Comment by mathbunnyru** [comment]
Here is an example of how you can do it:

```
FROM jupyter/all-spark-notebook

ENV TZ=Asia/Shanghai

USER root

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

USER ${NB_UID}
```

Note that `tzdata` is installed in `jupyter/minimal-notebook`, so we don't need to install it in all derived images (including `jupyter/all-spark-notebook`).

**Comment by benz0li** [comment]
@marconr9 You may also set the timezone at runtime with the `TZ` environment variable.

Use e.g. `-e TZ=Europe/Zurich` when starting the jupyter notebokk.

**Comment by benz0li** [comment]
@marconr9 Be aware, that setting at runtime does not change `/etc/localtime` and `/etc/timezone`, which some tools *might* depend on.

**Comment by marconr9** [comment]
thanks for the answers but I don't get it to work.
I tried it with environment table in docker
But the docker in stuck in the UTC timezone.
Maybe I'll try it later or I;m not that experienced

**Comment by benz0li** [comment]
@marconr9 What exact command do you execute when starting the jupyter container?

OR

What does your `Dockerfile` contain [in case you build your own image]?

**Comment by benz0li** [comment]
E.g. `docker run -it --rm -p 8888:8888 -e TZ=Asia/Shanghai jupyter/all-spark-notebook` *should* work.

**Comment by mathbunnyru** [comment]
I am closing this one, as no information has been received from the user, and several solutions were provided.
