### ISSUE TITLE
3.2 tagged images with R now run notebook 4.0

### ISSUE THREAD

**Issue by parente** [jupyter/docker-stacks#20]
Inverse problem of the other day. The conda R package now prereqs jupyter 4.0 which winds up upgrading the notebook server. Any way to get these images back on 3.2.1?

**Comment by rgbkrk** [comment]
Well that's funny. We could also pin with the old version of the R kernel too right?

**Comment by parente** [comment]
Doh! You're probably right. For some reason I assumed the dependency was updated with a corresponding version bump on irkernel itself. I'll have a look.

**Comment by parente** [comment]
Addressed by pinning the version and build number in the 3.2.1 brach. Good catch.
