### ISSUE TITLE
Best practice for installing python modules in a docker container

### ISSUE THREAD

**Issue by krautt** [jupyter/docker-stacks#200]
I'm trying to use some previously created code that use MySQLdb to make sql connections to a mysql database.   Looks like this module isn't installed in the image.  I'm wondering what the best way is to install it?   I tried the below installs from a notebook but this wasn't successful.  I suspect that perhaps the custom design of the container precludes the use of the native ubuntu locations?  Perhaps alternatively,  how might i include them?

> !sudo apt-get update
> !sudo apt-get install pymysql mysql build-essential python-dev libmysqlclient-dev python-mysqldb python-configparser --assume-yes
> 
> ImportError                               Traceback (most recent call last)
> <ipython-input-39-26e00b159b53> in <module>()
>       1 
>       2 import pandas as pd
> ----> 3 import MySQLdb
>       4 
>       5 import datetime
> 
> ImportError: No module named MySQLdb
> 

I also tried:  !pip install MySQL-python

but got the following error:

> Collecting MySQL-python
>   Using cached MySQL-python-1.2.5.zip
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-7tuxn_4l/MySQL-python/setup.py", line 13, in <module>
>         from setup_posix import get_config
>       File "/tmp/pip-build-7tuxn_4l/MySQL-python/setup_posix.py", line 2, in <module>
>         from ConfigParser import SafeConfigParser
>     ImportError: No module named 'ConfigParser'
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7tuxn_4l/MySQL-python/

**Comment by parente** [comment]
> ImportError: No module named 'ConfigParser'

Looks like MySQL-python is not python3 compatible. (The ConfigParser module changed names in py3.) Try a python2 notebook.

**Comment by parente** [comment]
Hit submit too soon ...

In general, the containers are set up to use conda and pip as package managers for Python and R dependencies. Prefer these over the OS package managers where possible.

**Comment by parente** [comment]
I'm closing this issue because it has been inactivate for a while now. If you have further questions about installing packages using conda or pip, feel free to open new issues.

**Comment by ScarletMcLearn** [comment]
How? Bump
