### ISSUE TITLE
python3-octave-kernel APT package do not compatible with default Python version

### ISSUE THREAD

**Issue by Ratizux** [jupyter/docker-stacks#2001]
### What docker image(s) are you using?

base-notebook

### Host OS system

openSUSE Leap 15.5

### Host architecture

x86_64

### What Docker command are you running?

`podman run -it --rm -p 8888:8888 jupyterlab-octave`
jupyterlab-octave was built from jupyter/base-notebook, the only difference is the installation of python3-octave-kernel and octave-general.

### How to Reproduce the problem?

1. Enter JupyterLab
2. Open a Octave Notebook or Console
3. Observe that JupyterLab unable to connect to Octave Kernel: `/opt/conda/bin/python3.11: No module named octave_kernel`

### Expected behavior

Module `octave_kernel` can be imported in default Python (3.11).

### Actual behavior

Module `octave_kernel` cannot be imported in default Python: `ModuleNotFoundError: No module named 'octave_kernel'`

### Anything else?

`octave_kernel` can be imported normally in `python3.10`.

### Latest Docker version

- [X] I've updated my Docker version to the latest available, and the issue still persists

**Comment by mathbunnyru** [comment]
`jupyterlab-octave was built from jupyter/base-notebook, the only difference is the installation of python3-octave-kernel and octave-general.`

Could you please share your Dockerfile to see how exactly you installed these packages?

**Comment by Ratizux** [comment]
Content of Dockerfile(Containerfile):
```
FROM docker.io/jupyter/base-notebook

USER root

RUN \

apt update && DEBIAN_FRONTEND="noninteractive" apt install python3-octave-kernel octave-general -y

USER ${NB_USER}
```

Containerfile built with `podman build -t jupyterlab-octave .`

**Comment by mathbunnyru** [comment]
You're installing `python3-octave-kernel` under root, which will only work for default ubuntu python and won't work for our `conda` environment.
It is always recommended to install packages with `mamba` or `pip` and under `${NB_USER}`. I personally recommend using `mamba` as soon as you have a version which you need available.

This works for me:
```
FROM docker.io/jupyter/base-notebook

USER root

RUN apt update && DEBIAN_FRONTEND="noninteractive" apt install octave-general -y

USER ${NB_USER}

RUN mamba install --yes octave_kernel
```

**Comment by Ratizux** [comment]
I see. Thank you for your help!
