### ISSUE TITLE
Docker Hub subscription about to expire.

### ISSUE THREAD

**Issue by Carreau** [jupyter/docker-stacks#2018]
@mathbunnyru you seem to be the most active contributor. 

Just to warn you that the docker subscription is about to expire and be downgraded to "free" in 6 days. I've contacted the Jupyter EC, they are aware on working on it I suppose.

**Comment by yuvipanda** [comment]
@Carreau being tracked and worked on in  https://github.com/jupyterhub/team-compass/issues/688.

**Comment by Carreau** [comment]
Ah! thanks !

if it's taken care of, you can also remove me from the jupyter team, as I
rarely use docker, publish even less. that will at least remove one seat.

**Comment by consideRatio** [comment]
There are two separate dockerhub orgs, one for jupyterhub, and one for jupyter.

@choldgraf applied for renewal successfully in the jupyterhub org on dockerhub (https://github.com/jupyterhub/team-compass/issues/688#issuecomment-1774379057), it would be good to do the same for jupyter org on dockerhub to avoid issues.

I got an invite to re-apply for another year two days ago: https://github.com/jupyterhub/team-compass/issues/688#issuecomment-1777140457

I'll submit an application

**Comment by consideRatio** [comment]
Or wait @choldgraf, do you think they approved both jupyter and jupyterhub org on dockerhub? They wanted these bundled when we applied last time i recall

**Comment by Carreau** [comment]
> There are two separate dockerhub orgs, one for jupyterhub, and one for jupyter.

I see 2 more: `jupyterincubator` and `ipython`.

It would be nice to get this clean up. I'm happy to add someone who know what they are doing to these orgs.

**Comment by mathbunnyru** [comment]
I prefer to close this issue, as there is already one with all the discussion (to keep everything in the same place).

**Comment by choldgraf** [comment]
Just to answer @consideRatio - I only applied for JupyterHub, I don't think I'm a member of any of the others.
