### ISSUE TITLE
Generate READMEs from common source

### ISSUE THREAD

**Issue by parente** [jupyter/docker-stacks#203]
There's a lot of duplicate text across the READMEs for reader convenience. @jakirkham and I briefly discussed improving the authoring experience a bit by generating these READMEs from a common source using a simple templating approach. Even this has a cost, however, as new contributors looking to update READMEs will have to send PRs against the source, not the READMEs themselves.

**Comment by parente** [comment]
We also briefly discussed the pros/cons of doing a full RTD site like all the other Jupyter projects, but both agreed we didn't want to lose the value of the simple README per stack that is immediately visible and accessible on GitHub and linked from Docker Hub.

**Comment by willingc** [comment]
I agree that the simple README per stack is most important. I'm going to do some research when I'm at Write The Docs conference in a couple of weeks to see if others have ideas. We may be able to use jinja to help generate the individual READMEs. For now, I would put a note in a CONTRIBUTORS.md reminding folks to search and replace across all stacks when making a change to an individual README. Worst case: we should be aware of it during review ;-)

**Comment by parente** [comment]
> We may be able to use jinja 

This was my first thought too, though it's a bit heavy. I wonder if there's a markdown way of doing simple includes?

**Comment by minrk** [comment]
There's not an *official* markdown way to do includes (official markdown is a not-at-all-extensible shorthand for HTML), but you might find a markdown implementation that supports it. However, it may be simplest to do a simple template version, such that we can do a `make readmes` which fills in the common blocks.

Given how this repo is used, though, the generated results should be committed to the repo.

**Comment by parente** [comment]
See comment in #261.
