### ISSUE TITLE
Firewall Vulnerability on Base Jupyter Notebook Stack

### ISSUE THREAD

**Issue by hqnicolas** [jupyter/docker-stacks#2030]
### What docker image(s) are you using?

base-notebook

### Host OS system

Ubuntu Jammy Docker

### Host architecture

aarch64

### What Docker command are you running?

podman pull quay.io/jupyter/base-notebook
docker run -it --rm -p 3000:8888 -v "${PWD}":/home/jovyan/work quay.io/jupyter/base-notebook

### How to Reproduce the problem?

Let just 1 infraestructure firewall port open

### Command output

```bash session
The System report a 'SCAN: TCP Port Scan' alert:
```

### Expected behavior

Palo alto ipV4 scan alert

### Actual behavior

I have the :80 http port and a 9090 port to receive data from client.
the 9090 port get stuck by the hacker using it to search for :22 port that doesnt exist on my infraestructure firewall

### Anything else?

I just let this work for 10 hours and !pwned!
I will reinstall it without password set, just the full stock install.

### Latest Docker version

- [X] I've updated my Docker version to the latest available, and the issue still persists

**Comment by yuvipanda** [comment]
If I run the command you specified, the actual way to access the notebook is:

```
        http://127.0.0.1:8888/lab?token=bc2dce2848a55de7134591df9f63a916e2d36bc4c2d09e36
```

so there's token authentication by default.

**Comment by hqnicolas** [comment]
@yuvipanda somebody get acces to the root user of the container image provided by quay.io/jupyter/base-notebook

**Comment by hqnicolas** [comment]
I have deployed the quay.io/jupyter/base-notebook
and somebody was pwned this container across the firewall
nothing else was atacced on my entire network 
Just this container....
