### ISSUE TITLE
[BUG] - Content Security Policy directive: "frame-ancestors 'self'" when trying to create iframe in Jupyter Notebook

### ISSUE THREAD

**Issue by IDianaM** [jupyter/docker-stacks#2031]
### What docker image(s) are you using?

base-notebook

### Host OS system

Ubuntu 22.04

### Host architecture

x86_64

### What Docker command are you running?

docker run -it --rm -p 8888:8888 jupyter/base-notebook start-notebook.py --ServerApp.base_url=/jupyter/ --ServerApp.allow_origin='*' --ServerApp.disable_check_xsrf=True --ServerApp.allow_remote_access=True --ServerApp.tornado_settings=/{'headers'={'Content-Security-Policy':"frame-ancestors http://localhost:4200"}}/

### How to Reproduce the problem?

1. Run docker with command using the command above.
![image](https://github.com/jupyter/docker-stacks/assets/57529174/2ce26a31-ce18-4014-9094-2ff4dd10bbc8)

2. Get token (for example `18ee1a18726cfde363660db90ac167bc0f720a93067987cf`) and paste it into src in iframe:
`  <iframe src="http://localhost:8888/jupyter/lab?token=18ee1a18726cfde363660db90ac167bc0f720a93067987cf"></iframe>`
3. Catch an error 
![image](https://github.com/jupyter/docker-stacks/assets/57529174/faaa8d17-d8ee-4ffd-a3dd-66e458d6137f)

### Actual behavior

Catch error **Refused to frame 'http://localhost:8888/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".**
![image](https://github.com/jupyter/docker-stacks/assets/57529174/25b34938-17eb-4299-996a-19f8dedf51b9)

### Anything else?

I saw the solution given in  #1963. However i get the same problem. I think there is a typo in the attribute --ServerApp.tornado_settings=/{'headers'={'Content-Security-Policy':"frame-ancestors http://localhost:4200"}}/

### Latest Docker version

- [X] I've updated my Docker version to the latest available, and the issue still persists

**Comment by mathbunnyru** [comment]
@AhmetTpc could you please take a look here?

**Comment by AhmetTpc** [comment]
i have a same issue and here is my solution;

this is my docker run command and jupyter config file can u try to start like that?

docker run --rm -p 8888:8888 -v path/to/local/jupyter_server_config.py:/home/jovyan/work/  jupyter/base-notebook jupyter server --config /home/jovyan/work/jupyter_server_config.py

```python

# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
# mypy: ignore-errors
import os
import stat
import subprocess

from jupyter_core.paths import jupyter_data_dir

c = get_config()  # noqa: F821
c.ServerApp.ip = "0.0.0.0"
c.ServerApp.open_browser = False
c.ServerApp.password=""
c.ServerApp.token=""
c.ServerApp.disable_check_xsrf=True
c.ServerApp.tornado_settings = {
    'headers': {
        'Content-Security-Policy': 'frame-ancestors self http://localhost:8000'
    }
}
c.ServerApp.allow_origin = 'http://localhost:8000' 

# to output both image/svg+xml and application/pdf plot formats in the notebook file
c.InlineBackend.figure_formats = {"png", "jpeg", "svg", "pdf"}

# https://github.com/jupyter/notebook/issues/3130
c.FileContentsManager.delete_to_trash = False

# Generate a self-signed certificate
OPENSSL_CONFIG = """\
[req]
distinguished_name = req_distinguished_name
[req_distinguished_name]
"""
if "GEN_CERT" in os.environ:
    dir_name = jupyter_data_dir()
    pem_file = os.path.join(dir_name, "notebook.pem")
    os.makedirs(dir_name, exist_ok=True)

    # Generate an openssl.cnf file to set the distinguished name
    cnf_file = os.path.join(os.getenv("CONDA_DIR", "/usr/lib"), "ssl", "openssl.cnf")
    if not os.path.isfile(cnf_file):
        with open(cnf_file, "w") as fh:
            fh.write(OPENSSL_CONFIG)

    # Generate a certificate if one doesn't exist on disk
    subprocess.check_call(
        [
            "openssl",
            "req",
            "-new",
            "-newkey=rsa:2048",
            "-days=365",
            "-nodes",
            "-x509",
            "-subj=/C=XX/ST=XX/L=XX/O=generated/CN=generated",
            f"-keyout={pem_file}",
            f"-out={pem_file}",
        ]
    )
    # Restrict access to the file
    os.chmod(pem_file, stat.S_IRUSR | stat.S_IWUSR)
    c.ServerApp.certfile = pem_file

# Change default umask for all subprocesses of the Server if set in the environment
if "NB_UMASK" in os.environ:
    os.umask(int(os.environ["NB_UMASK"], 8))
  
```
if you want to use token , you should edited this py file

**Comment by mathbunnyru** [comment]
It seems that the author is no longer interested in this issue.

**Comment by mathbunnyru** [comment]
@AhmetTpc thank you for your fast response though, I appreciate it 👍
