### ISSUE TITLE
Support for Ubuntu 23.10 version

### ISSUE THREAD

**Issue by mayank-h-chauhan-db** [jupyter/docker-stacks#2041]
### What docker image(s) is this feature applicable to?

datascience-notebook

### What change(s) are you proposing?

Is it possible to add support for ubuntu 23.10, currently it's 22.04

### How does this affect the user?

Image available based on latest ubuntu version

### Anything else?

NA

**Comment by mathbunnyru** [comment]
Hi @mayank-h-chauhan-db.
We only provide one set of images at a time and only using the latest LTS Ubuntu version.

Here is our policy:
https://jupyter-docker-stacks.readthedocs.io/en/latest/maintaining/tasks.html#updating-the-ubuntu-base-image

If you want to, you can build our images on your own and push them to your registry.
If you fix some bugs, do not hesitate to propose changes to our images so everyone can build them easily.
