### ISSUE TITLE
The home dir should be '/root', not '/home/root', when starting the container and set the env 'NB_USER' to 'root'.

### ISSUE THREAD

**Issue by orange-guo** [jupyter/docker-stacks#2042]
### What docker image(s) are you using?

base-notebook

### Host OS system

ubuntu 23.10

### Host architecture

x86_64

### What Docker command are you running?

```bash
docker run --rm --user root -p 8888:8888 -e JUPYTER_TOKEN=123 -e NB_UID=0 -e NB_GID=0 -e NB_USER=root jupyter/base-notebook:notebook-7.0.2 /usr/local/bin/start-notebook.sh --allow-root
```

### How to Reproduce the problem?

1. Run the following command
```bash
docker run --rm --user root -p 8888:8888 -e JUPYTER_TOKEN=123 -e NB_UID=0 -e NB_GID=0 -e NB_USER=root jupyter/base-notebook:notebook-7.0.2 /usr/local/bin/start-notebook.sh --allow-root
```
2. After the container starts, the logs contain the following information:
```bash
Entered start.sh with args: jupyter lab --allow-root
Running hooks in: /usr/local/bin/start-notebook.d as uid: 0 gid: 0
Done running hooks in: /usr/local/bin/start-notebook.d
Updated the jovyan user:
- username: jovyan       -> root
- home dir: /home/jovyan -> /home/root
Attempting to copy /home/jovyan to /home/root...
Success!
Changing working directory to /home/root/
Running hooks in: /usr/local/bin/before-notebook.d as uid: 0 gid: 0
Done running hooks in: /usr/local/bin/before-notebook.d
Running as root: jupyter lab --allow-root
````
The logs indicate that the home directory has been set to '/home/root' instead of '/root'.

### Command output

```bash session
Entered start.sh with args: jupyter lab --allow-root
Running hooks in: /usr/local/bin/start-notebook.d as uid: 0 gid: 0
Done running hooks in: /usr/local/bin/start-notebook.d
Updated the jovyan user:
- username: jovyan       -> root
- home dir: /home/jovyan -> /home/root
Attempting to copy /home/jovyan to /home/root...
Success!
Changing working directory to /home/root/
Running hooks in: /usr/local/bin/before-notebook.d as uid: 0 gid: 0
Done running hooks in: /usr/local/bin/before-notebook.d
Running as root: jupyter lab --allow-root
`
```

### Expected behavior

The home dir should be '/root', not '/home/root', when starting the container and set the env 'NB_USER' to 'root'.

### Actual behavior

When setting the NB_USER as 'root', the home dir should be '/root'.

### Latest Docker version

- [X] I've updated my Docker version to the latest available, and the issue persists

**Comment by benz0li** [comment]
@orange-guo See https://github.com/jupyter/docker-stacks/pull/2039 for an ongoing discussion.

**Comment by benz0li** [comment]
IMHO we do not want to use (and touch) the original `/root` directory.

For my explanation, see https://github.com/jupyter/docker-stacks/pull/2039#issuecomment-1823044530 ff.
