### ISSUE TITLE
[jupyter/tensorflow-notebook] Kernel stays in Busy mode indefinitely 

### ISSUE THREAD

**Issue by ravigunasekara** [jupyter/docker-stacks#2064]
### What docker image(s) are you using?

tensorflow-notebook

### Host OS system

Mac OS Ventura 13.6.1 

### Host architecture

aarch64

### What Docker command are you running?

docker run -p 8888:8888 -v $(pwd):/home/jovyan/work jupyter/tensorflow-notebook

### How to Reproduce the problem?

`import tensorflow as tf`

### Expected behavior

Should allow other notebook commands after importing TensorFlow. It could be TensorFlow or any other (eg: `data.head()` OR `tf.__version__`

### Actual behavior

No output. But the Python3 kernel stays in Busy mode indefinitely and does not allow execution of any other command after the above import

### Latest Docker version

- [X] I've updated my Docker version to the latest available, and the issue persists

**Comment by mathbunnyru** [comment]
We only push latest images to Quay.io, could you please try using `quay.io/jupyter/tensorflow-notebook` image?

**Comment by mathbunnyru** [comment]
Also, please, try executing your command without volume mounted - do you still have an error?

**Comment by mathbunnyru** [comment]
`docker run --pull always -p 8888:8888 quay.io/jupyter/tensorflow-notebook` + `import tensorflow` works fine for me on M2 MacBook Air, Docker Desktop 4.26.1, macOS Sonoma 14.2.1.
I remember a case when upgrading to Sonoma resolved the issue (it was about emulating x86_64 on a apple-silicon Mac though): https://github.com/jupyter/docker-stacks/issues/1999#issuecomment-1739113598

Could you please try to close all the jupyterlab tabs in a browser, run the command above, and then try to `import tensorflow` in a private tab?
Also, please, make sure, you have the same Docker Desktop version.

**Comment by benz0li** [comment]
Out of curiosity: Does it work with my JupyterLab Python docker stack?

### On your Apple computer

```bash
docker run -it --rm \
  -p 8888:8888 \
  -v "${PWD}":/home/jovyan \
  glcr.b-data.ch/jupyterlab/python/base
```

### In the container

#### JupyterLab Terminal

```bash
pip install tensorflow
```

```bash
python
```

#### Python REPL

```python
import tensorflow as tf
```

---

For more information, see https://github.com/b-data/jupyterlab-python-docker-stack.  
(with b-data's/my docker stack one is supposed to mount the entire *home directory*).

> 1. Multi-arch: `linux/amd64`, `linux/arm64/v8`  
>    :information_source: Runs on Apple M series using Docker Desktop.
> 1. Base image: [Debian](https://hub.docker.com/_/debian) instead of [Ubuntu](https://hub.docker.com/_/ubuntu)  
>    :information_source: CUDA-enabled images are Ubuntu-based.
> 1. IDE: [code-server](https://github.com/coder/code-server) next to [JupyterLab](https://github.com/jupyterlab/jupyterlab)  
>    :information_source: code-server = VS Code in the browser.
> 1. Just Python – no [Conda](https://github.com/conda/conda) / [Mamba](https://github.com/mamba-org/mamba)

**Comment by benz0li** [comment]
@ravigunasekara Bind mounting does not work with VirtioFS: https://github.com/docker/for-mac/issues/6243#issuecomment-1715552319

Use gRPC FUSE.
