### ISSUE TITLE
[BUG] Healthcheck fails when using a custom runtime dir

### ISSUE THREAD

**Issue by hhromic** [jupyter/docker-stacks#2073]
### What docker image(s) are you using?

scipy-notebook (but applies to all images based on the `base-notebook` image)

### Host OS system

RHEL 8.0

### Host architecture

x86_64

### What Docker command are you running?

The following command DOES work as expected (default runtime dir):
```
docker run --rm -p 8888:8888 --name jupyter quay.io/jupyter/scipy-notebook:2023-12-25 start-notebook.sh
```

The following command does NOT work as expected (customized runtime dir):
```
docker run --rm -p 8888:8888 --name jupyter -e JUPYTER_RUNTIME_DIR=/home/jovyan/custom-runtime quay.io/jupyter/scipy-notebook:2023-12-25 start-notebook.sh
```

### How to Reproduce the problem?

1. Start the Jupyter container using the commands above.
2. In another terminal, run the healtcheck script: `docker exec jupyter /etc/jupyter/docker_healthcheck.py`
3. Observe the healthcheck script failing due to server state JSON file(s) not being found.

### Command output

```bash session
$ docker run --rm -p 8888:8888 --name jupyter quay.io/jupyter/scipy-notebook:2023-12-25 start-notebook.sh
$ docker exec jupyter /etc/jupyter/docker_healthcheck.py
b'{"version": "2.12.1"}'

$ docker run --rm -p 8888:8888 --name jupyter -e JUPYTER_RUNTIME_DIR=/home/jovyan/custom-runtime quay.io/jupyter/scipy-notebook:2023-12-25 start-notebook.sh
$ docker exec jupyter /etc/jupyter/docker_healthcheck.py
Traceback (most recent call last):
  File "/etc/jupyter/docker_healthcheck.py", line 14, in <module>
    json_file = next(runtime_dir.glob("*server-*.json"))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration
```

### Expected behavior

Healthcheck script to not fail, e.g. to display `b'{"version": "2.12.1"}'`, even with a customized runtime dir.

### Actual behavior

The healthcheck script fails because it cannot find server state JSON files in the hard-coded default runtime dir.

### Anything else?

The problem is that the `/etc/jupyter/docker_healthcheck.py` healtcheck script hard-codes the default runtime directory to search for server JSON state files as below:
https://github.com/jupyter/docker-stacks/blob/fcb20a914ed20e44a96053caf43eef6e12fb4c04/images/base-notebook/docker_healthcheck.py#L13

When this directory is customized for example via `JUPYTER_RUNTIME_DIR`, then the healthcheck script does not work.

The actual problem is when deploying Jupyter containers as services.
The Jupyter images have a default healthcheck configured as below:
https://github.com/jupyter/docker-stacks/blob/fcb20a914ed20e44a96053caf43eef6e12fb4c04/images/base-notebook/Dockerfile#L66-L70

When the healthcheck fails due to a custom runtime dir, the service is restarted continuously.

I think the healthcheck script should use the output of `jupyter --runtime-dir` which respects customizations:
```
$ docker run --rm -e JUPYTER_RUNTIME_DIR=/home/jovyan/custom-runtime quay.io/jupyter/scipy-notebook:2023-12-25 jupyter --runtime-dir
/home/jovyan/custom-runtime
```

If you agree with the above, I can send a PR with this fix.

### Latest Docker version

- [X] I've updated my Docker version to the latest available, and the issue persists

**Comment by hhromic** [comment]
The workaround we are using for now is to disable healthchecks in the compose file. For example:
```yaml
services:
  notebook:
    image: quay.io/jupyter/scipy-notebook:2023-12-25
    healthcheck:
      disable: true
```

**Comment by mathbunnyru** [comment]
Hi @hhromic! Thank you for such a detailed issue - you've done a great job investigating this issue.

> If you agree with the above, I can send a PR with this fix.

I do agree and your solution seems to be reasonable.
Also, please, include the test here: https://github.com/jupyter/docker-stacks/blob/main/tests/base-notebook/test_healthcheck.py I think you will only need to add one line of code to this test file.

**Comment by hhromic** [comment]
@mathbunnyru done!
Let me know what do you think in the PR itself.
Happy to help to this nice project 👍.

**Comment by hhromic** [comment]
Hey @mathbunnyru!
Just wanted to report that we just deployed the new `2024-01-08` tag in our Swarm cluster and the healthcheck script is working perfectly with customised runtime dir now! 🎉 

Thanks for the quick review and tag update! Really appreciate the work you do with these images.

**Comment by mathbunnyru** [comment]
> Hey @mathbunnyru! Just wanted to report that we just deployed the new `2024-01-08` tag in our Swarm cluster and the healthcheck script is working perfectly with customised runtime dir now! 🎉

Thanks for the update, I'm glad everything works for you 🙂 

> Thanks for the quick review and tag update! Really appreciate the work you do with these images.

Thank you ❤️ Please, consider [sponsoring my work](https://github.com/sponsors/mathbunnyru/) (I do not insist, though) 🙂
