### ISSUE TITLE
After starting the container with NB_USER=root, NB_UID=0, and NB_GID=0, $HOME environment variable is still /home/jovyan

### ISSUE THREAD

**Issue by anil-resero** [jupyter/docker-stacks#2083]
### What docker image(s) are you using?

datascience-notebook

### Host OS system

Ubuntu 22.04

### Host architecture

x86_64

### What Docker command are you running?

docker run -d --rm --user root -p 8888:8888 -e JUPYTER_TOKEN=123 -e NB_UID=0 -e NB_GID=0 -e NB_USER=root -e
 NOTEBOOK_ARGS="--allow-root" quay.io/jupyter/datascience-notebook:2024-01-16

### How to Reproduce the problem?

1. Start the container using the comment above and exec into the container

```
ubuntu$ docker run -d --rm --user root -p 8888:8888 -e JUPYTER_TOKEN=123 -e NB_UID=0 -e NB_GID=0 -e NB_USER=root -e
 NOTEBOOK_ARGS="--allow-root" quay.io/jupyter/datascience-notebook:2024-01-16 
025ef42b70c01de329f8b6371feb008525a0393284b3d873df7642d396f2ff2d
```

2. Exec into the container
```
ubuntu$ docker ps
CONTAINER ID   IMAGE                                             COMMAND                  CREATED         STATUS                   PORTS                                       NAMES
025ef42b70c0   quay.io/jupyter/datascience-notebook:2024-01-16   "tini -g -- start-no…"   8 seconds ago   Up 7 seconds (healthy)   0.0.0.0:8888->8888/tcp, :::8888->8888/tcp   happy_sutherland
70058a13a501   resero-svc-studies:latest                         "/bin/bash"              27 hours ago    Up 27 hours                                                          resero-devcontainer
ubuntu$ docker exec -u root happy_sutherland bash
```
3. Check the user
```
ubuntu$ whoami
ubuntu
```

4. Check $HOME
(base) root@025ef42b70c0:~# echo $HOME
/home/jovyan

NOTE: /etc/passwd is fine

```
(base) root@025ef42b70c0:~# cat /etc/passwd
root:x:0:0:root:/home/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/run/ircd:/usr/sbin/nologin
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
_apt:x:100:65534::/nonexistent:/usr/sbin/nologin
jovyan:x:1000:100::/home/jovyan:/bin/bash
```

### Expected behavior

`echo $HOME` should be `/home/root`

### Actual behavior

`echo $HOME`  is `/home/jovyan`

### Latest Docker version

- [X] I've updated my Docker version to the latest available, and the issue persists

**Comment by mathbunnyru** [comment]
`4. Check $HOME`

I think you're checking it wrong.
You are probably doing `docker exec -it CONTAINER_ID bash` and then `echo $HOME`.
This way it will indeed show `/home/jovyan`.
The reason for this is that the Dockerfile was built `ENV /home/jovyan`.
I think there is no way to change during runtime the env variable saved for the image, so it will stay like this.

I checked the terminal inside JupyterLab and in the notebook - and `$HOME` is `/home/root`, which is correct.

**Comment by mathbunnyru** [comment]
@anil-resero 
If you really **need** to have $HOME to be `/home/root` when running `docker exec` commands, then I suggest you create your own Dockerfile like this:
```
FROM quay.io/jupyter/datascience-notebook:2024-01-16
HOME=/home/root
```

Then just build and use this image. I haven't tested this but I think this should work.
