### ISSUE TITLE
Python version pinning mechanism in docker-stack-foundation does not match comment description

### ISSUE THREAD

**Issue by ehfd** [jupyter/docker-stacks#2084]
### What docker image(s) are you using?

docker-stacks-foundation

### Host OS system

Ubuntu 22.04

### Host architecture

x86_64

### What Docker command are you running?

docker run -it -p 8888:8888 quay.io/jupyter/scipy-notebook

### How to Reproduce the problem?

Try to extend the containers based on docker-stacks-foundation and install other packages (such as RAPIDS.ai) with specific requirements for Python revision versions for Conda. The installation fails.

### Command output

```bash session
Pins seem to be involved in the conflict. Currently pinned specs:
 - python==3.11.7 (labeled as 'pin-1')
```

### Expected behavior

```
    # Pin major.minor version of python
    mamba list python | grep '^python ' | tr -s ' ' | cut -d ' ' -f 1,2 | sed 's/\.[^.]*$/.* /' >> "${CONDA_DIR}/conda-meta/pinned" && \
```
Adding `sed 's/\.[^.]*$/.* /'` is the correct solution to the explanation of `# Pin major.minor version of python`.

Thus:
```
cat "${CONDA_DIR}/conda-meta/pinned"
> python 3.11.*
```

### Actual behavior

```
cat "${CONDA_DIR}/conda-meta/pinned"
> python 3.11.7
```

### Latest Docker version

- [X] I've updated my Docker version to the latest available, and the issue persists

**Comment by mathbunnyru** [comment]
Thank you for the issue.
Could you please create a PR with the proposed change?
If you also know how to do in a more clear way than grep, tr, cut and sed, that would be nice.

And if you want to make sure it won’t break in a future, please add a test here:
https://github.com/jupyter/docker-stacks/blob/main/tests/docker-stacks-foundation/test_python.py
