### ISSUE TITLE
Update docker

### ISSUE THREAD

**Issue by sayem314** [jupyter/docker-stacks#2094]
### What docker image(s) is this feature applicable to?

scipy-notebook

### What change(s) are you proposing?

Docker image is outdatedThe docker

### How does this affect the user?

N/A

**Comment by mathbunnyru** [comment]
Could you please add more details?

**Comment by mathbunnyru** [comment]
We build our images weekly, but I will launch manual build now, if you really need the latest version right now.

**Comment by mathbunnyru** [comment]
Ah, I see. Nope, I see your mistake, you should use quay.io, we do not push to Docker Hub anymore.

**Comment by mathbunnyru** [comment]
https://quay.io/repository/jupyter/scipy-notebook?tab=tags
notebook will be updated to 7.0.8 automatically one day when all the other dependencies support it.
