### ISSUE TITLE
 Is the latest build correctly labeled on quay.io

### ISSUE THREAD

**Issue by diyoyo** [jupyter/docker-stacks#2098]
### What docker image(s) are you using?

minimal-notebook

### Host OS system

Debian 12

### Host architecture

aarch64

### What Docker command are you running?

docker pull quay.io/jupyter/minimal-notebook:latest

### How to Reproduce the problem?

1. Start JupyterLab instance
2. Go to About-> Jupyter
3. Check version number.

### Command output

```bash session
4.1.2
```

### Expected behavior

4.1.3

### Actual behavior

4.1.2

### Anything else?

Well, I'm assuming the problem goes deeper than just a mistake in version number, as the issues it was supposed to solve are not solved (like this one https://github.com/jupyterlab/jupyterlab/issues/15907) 

### Latest Docker version

- [X] I've updated my Docker version to the latest available, and the issue persists

**Comment by mathbunnyru** [comment]
This is not a bug.
Our images are rebuilt weekly at Monday 03:00 UTC. At that time jupyterlab 4.1.3 was not available, at least in conda-forge, the relevant PR: https://github.com/conda-forge/jupyterlab-feedstock/pull/416
I can also see that the image tag is correct and it says 4.1.2 as it should.

I launched the build manually, new set of images will be pushed in approximately one hour.

**Comment by mathbunnyru** [comment]
https://github.com/jupyter/docker-stacks/actions/runs/8179934809

**Comment by diyoyo** [comment]
Thanks
