### ISSUE TITLE
Updates to Docker Hub have stopped

### ISSUE THREAD

**Issue by marton78** [jupyter/docker-stacks#2099]
### What docker image(s) is this feature applicable to?

scipy-notebook

### What change(s) are you proposing?

I know this is an open source project and I as an user am entitled to nothing, but is everything okay? It seems the CI service which pushed new images to Docker has died, the last update was 5 months ago, see [here](https://hub.docker.com/r/jupyter/scipy-notebook/tags)

### How does this affect the user?

They would have access to newer versions

**Comment by consideRatio** [comment]
Brief response from mobile - They are published to quay.io/jupyter/ instead of jupyter/ (dockerhub), a note is about it in the readme.

**Comment by mathbunnyru** [comment]
Everything works fine, but now we use Quay.io.
This was a choice jupyter/jupyterhub made, and I haven't received any negative feedback about this change.

Our images: https://quay.io/organization/jupyter/

**Comment by marton78** [comment]
Oh, I missed that. Thanks!
