### ISSUE TITLE
Default JUPYTER_PORT

### ISSUE THREAD

**Issue by vincemulhollon** [jupyter/docker-stacks#2106]
### What docker image(s) are you using?

all-spark-notebook

### Host OS system

Many nodes of RKE2 K8S running on Ubuntu 20.04 with IPVS

### Host architecture

x86_64

### What Docker command are you running?

The entire kubectl yaml file is long, but here are the good parts.

spec:
  containers:
    - env:
        - name: RESTARTABLE
          value: 'yes'
      image: quay.io/jupyter/all-spark-notebook
      imagePullPolicy: Always
      name: jupyter-container
      ports:
        - containerPort: 8888
          name: jupyter
          protocol: TCP
        - containerPort: 4040
          name: spark
          protocol: TCP
      resources: {}

### How to Reproduce the problem?

Set up a simple deployment of all-spark-notebook in RKE2 K8S using kubectl (or Rancher if you want a web UI).
This is, I believe, a new and empty PV, so the /home/joyvan/work should be empty at startup.

### Command output

```bash session
There were no immediate errors during deployment; errors occur at pod startup.
```

### Expected behavior

Jupyter starts up and works without error messages logged

### Actual behavior

Some relevant log lines from the pod:

W 2024-04-12 12:31:58.753 ServerApp] notebook_shim | error linking extension: invalid literal for int() with base 10: 'tcp://10.43.73.21:80'
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.11/site-packages/traitlets/traitlets.py", line 632, in get
        value = obj._trait_values[self.name]
                ~~~~~~~~~~~~~~~~~^^^^^^^^^^^
2024-04-12T07:31:58.759154946-05:00     KeyError: 'port'
2024-04-12T07:31:58.759868728-05:00     ValueError: invalid literal for int() with base 10: 'tcp://10.43.73.21:80'

I would interpret this as port "probably should be" 8888 as I understand it, and it really wants a simple integer port number, but instead it's trying to set the integer port number to the string "tcp://10.43.73.21:80"

### Anything else?

All I have to do to make this work is force set the environment variable JUPTER_PORT to 8888 instead of the autogenerated value.  The K8S yaml file looks like this:

spec:
  containers:
    - env:
        - name: RESTARTABLE
          value: 'yes'
        - name: JUPYTER_PORT
          value: '8888'

Note the addition of a JUPYTER_PORT environment variable.

I don't use docker but as I understand it this would be the equivalent on the docker CLI of something like "-e JUPYTER_PORT=8888"

Anyway, everything works perfectly as long as the port is forced to 8888 manually, I don't know if this is a K8S specific thing or maybe the docs should mention it or maybe its a bug or ?

Thanks for your efforts in dockerizing Jupyter because I enjoy running a few in my cluster and it works perfectly except for the port number situation mentioned in this issue, thanks for all you do and have a great day!

### Latest Docker version

- [X] I've updated my Docker version to the latest available, and the issue persists

**Comment by mathbunnyru** [comment]
`JUPYTER_PORT` is already set to 8888 in our images: https://github.com/jupyter/docker-stacks/blob/main/images/base-notebook/Dockerfile#L54

I think something in your setup setting this or another variable to the wrong value.
I would first check the environment variables which our docker images runs with.
You can created an image where you change our `start.sh` script and just run `env` to list all environment variables.
And then try to find suspicious ones.
Please, let me know, if this helps.

I don't use k8s, but I suppose many our users do and we haven't had any negative feedback recently, so I doubt there is something wrong with the image.

**Comment by mathbunnyru** [comment]
Unfortunately, I haven't received a reply from the author of the issue, so probably, this is no longer an issue, so closing.
