### ISSUE TITLE
Update images to Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by lukasbehammer** [jupyter/docker-stacks#2114]
### What docker image(s) is this feature applicable to?

docker-stacks-foundation

### What change(s) are you proposing?

Use image ubuntu:24.04 to build from.

### How does this affect the user?

Newer g++ versions higher than g++-11 can be installed via apt-get.

### Anything else?

I develop a python package which uses C++20. To test the package before publishing I want to install it in a JupyterHub (Z2JH) instance. Since libraries that are not included with g++-11 are used, I want to use a newer Ubuntu version to be able to use g++-13. Changing the base image to ubuntu:24.04 fails because Ubuntu uses UID 1000 for the standard user "ubuntu" since Ubuntu 23.04. With the workaround under https://bugs.launchpad.net/cloud-images/+bug/2005129 (Adding "RUN userdel -r ubuntu"  after the FROM statement to delete the user "ubuntu") I was able to successfully build a minimal-notebook image myself using ubuntu:24:04, installing g++-13 and finally build and install my Python package.

**Comment by mathbunnyru** [comment]
You can install g++-13 on Ubuntu 22.04: https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test?field.series_filter=jammy

I don't think we will be updating Ubuntu version any time soon:
1. We have a policy where we wait for the first point release: https://jupyter-docker-stacks.readthedocs.io/en/latest/maintaining/tasks.html#updating-the-ubuntu-base-image
2. We need to give developers and maintainers some time to update their software to be used on Ubuntu 24.04

**Comment by lukasbehammer** [comment]
Thanks for your fast answer. I will keep using my custom built image until you support a newer version.

**Comment by jtroe** [comment]
Is there a timeline to update `docker-stacks-foundation` to 24.04? It is now the latest supported LTS.

**Comment by mathbunnyru** [comment]
> Is there a timeline to update `docker-stacks-foundation` to 24.04? It is now the latest supported LTS.

https://jupyter-docker-stacks.readthedocs.io/en/latest/maintaining/tasks.html#updating-the-ubuntu-base-image

Ubuntu 24.04.1 should be released August 15, 2024: https://wiki.ubuntu.com/Releases
