### ISSUE TITLE
PySpark Notebook 3.5.1

### ISSUE THREAD

**Issue by marcelo-franceschini** [jupyter/docker-stacks#2115]
### What docker image(s) is this feature applicable to?

pyspark-notebook

### What change(s) are you proposing?

It still in 3.5.0. 
3.5.1 was release in Feb 23, 2024

### How does this affect the user?

Newer version

**Comment by mathbunnyru** [comment]
We're using Quay.io registry now and the new version is available there: https://quay.io/repository/jupyter/pyspark-notebook?tab=tags
