### ISSUE TITLE
How to install external spark packages (like spark-csv) in all-spark-notebook?

### ISSUE THREAD

**Issue by thomas-keller** [jupyter/docker-stacks#212]
I'm wondering what the proper method is to install external spark packages in the all-spark notebook container. Installing python (through conda/pip) and R packages (through R, of course) seems straightforward, but spark packages seem harder.

 I thought it would be through using -e SPARK_OPTS and then --packages, but that ultimately leads to the following error "flag provided but not defined: --packages" .

Here is the code that I thought would work:

```
docker run -p 8888:8888 -v "/home/thomas/spark_notebooks:/home/jovyan/work" -e SPARK_OPTS  "--packages=com.databricks:spark-csv_2.11:1.6.0" --net host jupyter/all-spark-notebook
```

**Comment by parente** [comment]
I think there's a couple examples on the recipes page that show how to do this. Can you give one of those a shot?

https://github.com/jupyter/docker-stacks/wiki/Docker-recipes#using-spark-packagesorg
https://github.com/jupyter/docker-stacks/wiki/Docker-recipes#using-local-spark-jars

**Comment by thomas-keller** [comment]
My apologies. The first recipe works just as advertised. I looked everywhere but the wiki, sorry!

**Comment by parente** [comment]
No worries!
