### ISSUE TITLE
Marimo behind JupyterHub

### ISSUE THREAD

**Issue by scls19fr** [jupyter/docker-stacks#2123]
### What docker image(s) is this feature applicable to?

new community stack

### What change(s) are you proposing?

Marimo https://marimo.io/ is a Python reactive notebook.

Creating a JupyterHub docker stack to run Marimo behind JupyterHub could be a nice feature to have.

This feature is being discussed at https://github.com/marimo-team/marimo/issues/905 and a minimal viable solution have been found by @jyio 

### How does this affect the user?

marimo is an open-source reactive notebook for Python — reproducible, git-friendly, executable as a script, and shareable as an app.

### Anything else?

https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html

could provide ready to use image with Marimo as

- jupyter/marimo-notebook
- and as part of jupyter/datascience-notebook

**Comment by manics** [comment]
Marimo definitely sounds interesting! AFAIK it doesn't use the ipynb format though, which is probably the main thing that ties everything else in this repository together. What do you see as the advantages of it being in docker-stacks instead of in it's own repository in the marimo-team org?

**Comment by scls19fr** [comment]
Not sure Pluto.jl uses ipynb format as native format.
I think it could give some highlight to this interesting open source project.
I think having it easily installed in jupyter/datascience-notebook could help

**Comment by benz0li** [comment]
Alternative: Use b-data's/my [Jupyter](https://github.com/b-data/jupyterlab-mojo-docker-stack)[Lab](https://github.com/b-data/jupyterlab-julia-docker-stack) [docker](https://github.com/b-data/jupyterlab-python-docker-stack) [stacks](https://github.com/b-data/jupyterlab-r-docker-stack) and install at *user level*:

```bash
pip install marimo click
pip install git+https://github.com/b-data/jupyter-marimo-proxy.git@jupyterlab-docker-stack
```

Then restart the server (container) and click on `Marimo`.

Cross reference:

* https://github.com/jyio/jupyter-marimo-proxy/issues/1

**Comment by yuvipanda** [comment]
I think at least for now, it should probably be in its own repo maintained by the Marimo folks rather than in jupyter/docker-stacks. Marimo/docker-stacks perhaps?
