### ISSUE TITLE
Include netbase Ubuntu package in images

### ISSUE THREAD

**Issue by AlexHill** [jupyter/docker-stacks#2128]
### What docker image(s) is this feature applicable to?

base-notebook, docker-stacks-foundation, minimal-notebook

### What change(s) are you proposing?

Add the [netbase Ubuntu package](https://ubuntu.pkgs.org/22.04/ubuntu-main-amd64/netbase_6.3_all.deb.html) to images.

### How does this affect the user?

> This package provides the necessary infrastructure for basic TCP/IP based networking.
> In particular, it supplies common name-to-number mappings in /etc/services, /etc/rpc, /etc/protocols and /etc/ethertypes

[/etc/protocols](https://man7.org/linux/man-pages/man5/protocols.5.html) is part of the POSIX spec and required by the C functions getprotobyname and getprotobynumber. Some reading here: https://unix.stackexchange.com/questions/680494/what-is-the-significance-of-etc-protocols-in-linux

### Anything else?

If this proposal is accepted, it's as easy as adding `netbase` to an apt-get install somewhere in the chain of images.

**Comment by mathbunnyru** [comment]
@AlexHill could you please create a PR and then I will create a vote there?

**Comment by AlexHill** [comment]
Done, thanks
