### ISSUE TITLE
Build an Image with a Different Version of Spark

### ISSUE THREAD

**Issue by lymedo** [jupyter/docker-stacks#2134]
### What docker image(s) are you using?

all-spark-notebook

### Host OS system

Mac OS

### Host architecture

aarch64

### What Docker command are you running?

docker build --rm --force-rm -f "Dockerfile" -t pysparknotebookv1 "." --build-arg spark_version=3.4.3 --build-arg spark_download_url="https://archive.apache.org/dist/spark/"

Dockerfile:
FROM --platform=linux/arm64 pysparknotebook:latest
ARG spark_version=3.4.3
ARG spark_download_url="https://archive.apache.org/dist/spark/"

### How to Reproduce the problem?

1. Pull pyspark-notebook image
2. Run Docker command
3. Run container
4. Run spark-submit --version

### Command output

```bash session
[+] Building 0.0s (5/5) FINISHED                                                                                                          docker:desktop-linux
 => [internal] load build definition from Dockerfile                                                                                                      0.0s
 => => transferring dockerfile: 1.09kB                                                                                                                    0.0s
 => [internal] load metadata for docker.io/library/pysparknotebook:latest                                                                                 0.0s
 => [internal] load .dockerignore                                                                                                                         0.0s
 => => transferring context: 420B                                                                                                                         0.0s
 => CACHED [1/1] FROM docker.io/library/pysparknotebook:latest                                                                                            0.0s
 => exporting to image                                                                                                                                    0.0s
 => => exporting layers                                                                                                                                   0.0s
 => => writing image sha256:6d81a0bc50257749aa39526c432ed31035fd7f16eb74a99f981d22ce48c55e69                                                              0.0s
 => => naming to docker.io/library/pysparknotebookv                                                                                                       0.0s
```

### Expected behavior

Container has the specified Spark version from the build args

### Actual behavior

Spark version is 3.5.1

### Anything else?

Testing with 3.4.3 but actually want to use Spark 4.0.0-preview1

### Latest Docker version

- [X] I've updated my Docker version to the latest available, and the issue persists

**Comment by mathbunnyru** [comment]
I don't understand at all how you build the local image.

`FROM --platform=linux/arm64 pysparknotebook:latest ` - I don't understand what `pysparknotebook` means here.
Could you please elaborate what exactly you are doing and how to reproduce it

**Comment by lymedo** [comment]
That's my local image pulled from Jupyter/pyspark-notebook. 

I'm just trying to follow the image specific guidance [here](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/specifics.html#build-an-image-with-a-different-version-of-spark)

**Comment by lymedo** [comment]
Closing as I just realised what I was doing wrong. I should be building the source project and not pulling an image.
