### ISSUE TITLE
Need a start-notebook smoketest

### ISSUE THREAD

**Issue by parente** [jupyter/docker-stacks#214]
The last release was green on travis and built fine on the build VM. But when download and run, the start-notebook.sh was missing the execute bit and unusable.

We need to add a quick smoketest to our travis build and release process to avoid cases like this. Something as simple as:

1. Run container
2. Fetch the root of the notebook server API

If the response is OK within some timeout, ship it.

**Comment by jr-minnaar** [comment]
Hi, when running

`docker run -p 8888:8888 jupyter/datascience-notebook`

I get the following error:

> Executing child process 'start-notebook.sh' failed: 'Permission denied'

I saw there was a commit a few minutes ago to fix the executable bit. If I get this error does it mean the docker images have not yet been updated?

**Comment by parente** [comment]
@jr-minnaar Yep. A bad build just went out. It's always safest to pin to a known tag that works from https://github.com/jupyter/docker-stacks/wiki/Docker-build-history.

`docker run -p 8888:8888 jupyter/datascience-notebook:dc6ae8bd8209`

will get you running again.

**Comment by parente** [comment]
And the new build is running ...

**Comment by jr-minnaar** [comment]
Thanks for the docker build history link! Unfortunately it seems ":dc6ae8bd8209" will mean another 1GB+ download. For now, this seems to have worked:
```
docker run -it --user=root --name notebook jupyter/datascience-notebook bash -c "chmod +x /usr/local/bin/start-*"
docker commit notebook jupyter/datascience-notebook
docker run -d -p 8888:8888 jupyter/datascience-notebook /usr/local/bin/start-notebook.sh
```

Thanks for the awesome work with these containers! I've been dreaming of having such an environment for a long time!

**Comment by parente** [comment]
The new, fixed build is out.

**Comment by parente** [comment]
A simple test to ensure a server is running on 8888 in a container and returns something with the word `jupyter` in it went into #216. Works as long as the server is the jupyter notebook server. We can improve over time.
