### ISSUE TITLE
Example bake file for custom docker builds

### ISSUE THREAD

**Issue by alwaysmpe** [jupyter/docker-stacks#2140]
### What docker image(s) is this feature applicable to?

docker-stacks-foundation

### What change(s) are you proposing?

I'm using these docker stacks built locally with python3.12, out of the box that's quite cumbersome to do. There are args for each dockerfile but these need to be built manually with custom arguments in the correct order.

To simplify this process, I've configured this repo as a submodule, I'm then using a [bake](https://docs.docker.com/build/bake/) file to automate the builds. So in my local repo users can run 2 commands and have a comparable config setup:
```
docker buildx bake
docker compose up
```
This use case is explicitly cited by the [bake docs](https://docs.docker.com/build/bake/reference/#use-another-target-as-base)

> You can Use this feature when you have multiple Dockerfiles that can't be easily merged into one.

### How does this affect the user?

Makes using customized builds easier.

### Anything else?

For my example use, see [the bake file](https://github.com/alwaysmpe/what2_dsp/blob/main/docker-bake.hcl) in [my repo](https://github.com/alwaysmpe/what2_dsp/)  (the rest of the code is pretty hacked together stuff, I'm using it to teach basics of DSP).

Happy to create a PR  but not sure if this would be better as a recipe/example or whether it's something that you'd want as part of your standard build process.

**Comment by mathbunnyru** [comment]
Hi @alwaysmpe!

`bake` seems to be a nice tool and it's a good idea to have an example in our repo.

> Happy to create a PR but not sure if this would be better as a recipe/example or whether it's something that you'd want as part of your standard build process.

I think the new recipe should work fine here.
One implementation detail - please, put the bake file as a separate file in the repo, not inline as part of docs.
We do it for our custom recipes (search for `literalinclude`):
https://raw.githubusercontent.com/jupyter/docker-stacks/main/docs/using/recipes.md

**Comment by mathbunnyru** [comment]
@mj0nez you might be interested in this issue, as it is a nice way to build your own set of images.

**Comment by alwaysmpe** [comment]
Cool, I'll try to get to it soon. I've been playing/refining further and have worked out I don't need the submodule, bake can use a git url, so even simpler to use.
