### ISSUE TITLE
Quay Image Tags

### ISSUE THREAD

**Issue by lewis-strong** [jupyter/docker-stacks#2148]
### What docker image(s) are you using?

datascience-notebook

### Host OS system

Ubuntu 22.04

### Host architecture

x86_64

### What Docker command are you running?

N/A

### How to Reproduce the problem?

https://quay.io/v2/jupyter/datascience-notebook/tags/list

### Command output

Most recent tags should be displayed in the list in order for Dependabot to be able to suggest upgrading to the latest date tag

### Expected behavior

2024-09-30 should be listed as most recent tag

### Actual behavior

2024-08-26 is currently showing as latest tag

### Latest Docker version

- [X] I've updated my Docker version to the latest available, and the issue persists

**Comment by minrk** [comment]
https://quay.io/v2/jupyter/datascience-notebook/tags/list is a paginated list of all tags, alphabetically, not sorted by date and not controlled by the image owner, though dates do happen to be a contiguous section at the moment. The next page is at https://quay.io/v2/jupyter/datascience-notebook/tags/list?n=100&last=2024-08-26 (see the `link rel="next"` header in the response). There are many pages of tags (778 total tags right now).

Here's [a script](https://gist.github.com/minrk/ce9351a4db5fda8b893d5ef90da75037) that will fetch all tags for a repo.

If dependabot needs tags to be on a single page, it seems like something for dependabot to bring up with quay, not something we can do much about.

**Comment by manics** [comment]
There's a `latest` tag https://quay.io/repository/jupyter/datascience-notebook?tab=tags&tag=latest
![image](https://github.com/user-attachments/assets/ddec3e8f-a831-474a-9cc8-edd68cd5d91e)

If you pin to the SHA does dependabot work?

**Comment by lewis-strong** [comment]
We don't want to pin to latest as we don't want to unknowingly pull in changes and want to pin to a specific version of the image.

As there's no SemVer tags then the date seems the next best option 😞 

Dependabot does [support dates](https://github.com/dependabot/dependabot-core/tree/main/docker#supported-tag-schemas) in this format but as @minrk has pointed out the endpoint it's checking is only a partial result, therefore there may need to be some changes on the Dependabot Core side of things to be able to retrieve all tags from Quay to be able to accurately suggest a dependency upgrade

**Comment by lewis-strong** [comment]
https://github.com/dependabot/dependabot-core/issues/10347 - May be an intended fix it seems.

**Comment by manics** [comment]
You don't need to pin to latest- you should be able to pin to the SHA that latest currently points to, and dependabot should bump that SHA when the latest tag is updated.

**Comment by lewis-strong** [comment]
Agreed it should be it seems that it's currently not retrieving all the tags or commit SHA's at this point and therefore only suggesting version bumps to anything on the first page retrieved via https://quay.io/v2/jupyter/datascience-notebook/tags/list
