### ISSUE TITLE
Add support for more recent versions of Python than 3.10

### ISSUE THREAD

**Issue by rjurney** [jupyter/docker-stacks#2179]
### What docker image(s) is this feature applicable to?

base-notebook

### What change(s) are you proposing?

It would be great to be able to use Python 3.11+ with the Docker Stacks for Jupyter. There are no such images.

### How does this affect the user?

- Allows user to run an image with pre-installed Python 3.11.X, 3.12.X or even 3.13.X.

**Comment by manics** [comment]
The latest base-notebook contains Python 3.12: https://quay.io/repository/jupyter/base-notebook?tab=tags

**Comment by mathbunnyru** [comment]
@rjurney I think you were using Docker Hub, but we no longer upload images there. Please, use our images from quay.io.

**Comment by rjurney** [comment]
@mathbunnyru THANK YOU. Can we put a link on the Docker Hub page that directs you to Quay? Also... I went to Docker Hub by habit, but is this in the documentaton?

**Comment by mathbunnyru** [comment]
> [@mathbunnyru](https://github.com/mathbunnyru) THANK YOU

You're welcome

> Can we put a link on the Docker Hub page that directs you to Quay?

Each image on Docker Hub has a warning like this, for example https://hub.docker.com/r/jupyter/pyspark-notebook: `Images hosted on Docker Hub are no longer updated. Please, use [quay.io image⁠](https://quay.io/repository/jupyter/pyspark-notebook)`

> Also... I went to Docker Hub by habit, but is this in the documentaton?

It is.

1. Mentioned in Quick Start at top of README.md: https://github.com/jupyter/docker-stacks?tab=readme-ov-file#quick-start
2. The same thing is true about web docs: https://jupyter-docker-stacks.readthedocs.io/en/latest/
3. All the `docker run/docker pull` command references have been updated to use Quay.io images

**Comment by rjurney** [comment]
Glad you're on top of the docs! :)
