### ISSUE TITLE
Trying to install libxml2

### ISSUE THREAD

**Issue by codybushnell** [jupyter/docker-stacks#218]
I'm trying to install lxml in python using pip but it continues to fail, due to what I believe is missing libxml2-dev. I'm trying to use apt-get to install libxml but it is saying it can't locate it. I get the same error when I run apt-get update. Any suggestions?

**Comment by parente** [comment]
I think `!conda install -y lxml` should work in a Python3 notebook. (`!conda install -y -n python2 lxml` if you want to use it in a python2 notebook).

**Comment by codybushnell** [comment]
Solved!

Thanks so much @parente . It was such a headache parsing html tables with regex instead of pandas.read_html().
