### ISSUE TITLE
Plain text password required for env option

### ISSUE THREAD

**Issue by kcrkor** [jupyter/docker-stacks#220]
The env option to set a password is a problem:
- The password is in plaintext in the docker-compose file
- The password will be saved in any bash history and docker files on the server I run my notebook on

I am aware this is for convenience, but I'm sure it is best if users hash their own passwords!

**Comment by parente** [comment]
As a workaround today, it's possible to add or host mount your own notebook config .py file with a hashed password.

It's possible to add support for a `HASHED_PASSWORD` env var in here along as an alternative to the plain text one that does the hashing for you: https://github.com/jupyter/docker-stacks/blob/master/base-notebook/jupyter_notebook_config.py#L36

**Comment by kcrkor** [comment]
Thanks for the suggestion, it did the trick.
