### ISSUE TITLE
ipywidgets missing in tmpnb

### ISSUE THREAD

**Issue by akhmerov** [jupyter/docker-stacks#221]
Observed: ipywidgets missing in tmpnb.org

To reproduce: open a python notebook in tmpnb.org and execute `import ipywidgets`.

I guess it may be due to the update to the widgets installation in notebook 4.2 / ipywidgets 5.0, although not entirely sure.

**Comment by minrk** [comment]
@parente was this perhaps an effect of the recently reorganized minimal/base? jupyter/demo is based on jupyter/minimal-notebook:2d878db5cbff

**Comment by parente** [comment]
`2d878db5cbff` is from before the reorg. I don't think the tmpnb has been rebuilt any time recently either.

Were ipywidgets ever installed on tmpnb? I don't see them ever getting installed when I trace through the history of the Dockerfile, even before it was based on jupyter/minimal-notebook.

I think we should transfer this issue to jupyter/docker-demo-images.

**Comment by minrk** [comment]
Does minimal-notebook have widgets now? I'll update the tag and republish demo, if so. I don't think we need to migrate the issue since it's about to be closed as soon as I redeploy tmpnb.

Do you think we should put the demo image in this repo?

**Comment by minrk** [comment]
I see now that minimal-notebook doesn't have widgets, that's added in scipy-notebook, so it was probably when we switched over to minimal from the full docker-demo image that we lost it. Maybe now's the opportunity to base it on all-spark, removing lots of duplicate installation stuff.

**Comment by parente** [comment]
> so it was probably when we switched over to minimal from the full docker-demo image that we lost it

Partially this, but also because the widgets used to come with IPython Notebook 3.x and during the switch over to minimal-notebook here, we moved to 4.x where they were a separate package.

Ref: commit before the switch over. Notice ipython, not jupyter.
https://github.com/jupyter/docker-demo-images/blob/34a840c31f978128b6a10c25615cc8d34b5fd520/Dockerfile

> Maybe now's the opportunity to base it on all-spark, removing lots of duplicate installation stuff.

Agreed. Worth a shot. I can take a crack at it later in the week if someone else doesn't get to it first.

**Comment by minrk** [comment]
I've started a build removing the Python, Julia, R, and spark installation. We'll see how that goes. I can't spend too much time on it this week, so I may open a PR and ask you to take over if it doesn't come together quickly.

**Comment by parente** [comment]
https://github.com/jupyter/docker-demo-images/pull/94
