### ISSUE TITLE
Trying to install opencv but import cv2 fails with "ImportError: libgtk-x11-2.0.so.0: cannot open shared object file"

### ISSUE THREAD

**Issue by js1972** [jupyter/docker-stacks#228]
I've installed OpenCV3 with `conda install -c menpo opencv3=3.1.0`. This works perfectly well on Mac OSX, but in this image it installs okay but when I try to use it like below it fails:
```
$ python
>>> import cv2

$ ImportError: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
```

I've tried `apt-get install libgtk2.0` but nothing happens. This SO post says it works on Ubuntu: http://askubuntu.com/questions/761589/installing-libgtk-x11-2-0-so-0-in-ubuntu-15-04

Any ideas..? Or has anyone got OpenCV to work in these containers?

I launch my container with (based on jupyter/scipy-notebook): 
```
$ docker run -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY -v $(pwd):/home/jovyan/work -p 8888:8888 -t -i opencv3
```

**Comment by js1972** [comment]
Ignore me... Stupid n00b mistake. After doing apt-get update then apt-get install libgtk2.0-dev it worked fine.   ;-)

**Comment by caseypen** [comment]
That helps! THanks!

**Comment by dorbodwolf** [comment]
thanks

**Comment by pourya2374** [comment]
thanks a lot :+1:

**Comment by PkuRainBow** [comment]
Thanks!

**Comment by xagano** [comment]
Thanks!

**Comment by wys18** [comment]
thanks a lot 👍

**Comment by shishito-megane** [comment]
Thaks!!

**Comment by black0017** [comment]
thanks !

**Comment by MUZUIXIAOHAI** [comment]
thanks !

**Comment by blacknwhite5** [comment]
thanks!!

**Comment by parente** [comment]
For what it's worth, there's a opencv package on conda-forge that might just work when installed with `conda install -c conda-forge opencv` in an image build or container now.

**Comment by GalaxyFlow** [comment]
thanks!

**Comment by linzhiming0826** [comment]
tanks a lot!!

**Comment by linzhiming0826** [comment]
thanks a lot！！

**Comment by shlomi-viz** [comment]
Thanks that helps 👍

**Comment by efagundes93** [comment]
thanks!

**Comment by ZihaoXue1995** [comment]
Thanks a lot!

**Comment by BryanBo-Cao** [comment]
> For what it's worth, there's a opencv package on conda-forge that might just work when installed with `conda install -c conda-forge opencv` in an image build or container now.

I was trying to use ```cv2``` on a cluster without ```sudo``` permission. ```conda install -c conda-forge opencv``` works. Thanks!
