### ISSUE TITLE
Start out with empty `/home/$NB_USER`?

### ISSUE THREAD

**Issue by eigengrau** [jupyter/docker-stacks#229]
I’m launching these images from Jupyterhub. Something that confuzzled me in this context is that the images are provisioned so that Docker volumes must be bound to `/home/$NB_USER/workdir`, rather than `/home/$NB_USER`. Thus, when notebook users install their own modules via Jupyter terminal, or when Python modules download data files on the fly (which usually wind up under ~), they are installed to the image layer and not to the Docker volume, so that the data won’t be persisted when reprovisioning the container. (Alternatively, users would have to be instructed on how to install modules or data into `~/workdir`; in any case people would have to be instructed that anything not stored under `~/workdir` doesn’t persist, so as to prevent a pitchforks & torches scenario).

I intend to deploy a Jupyterhub server at our institution, but I’m tweaking the Dockerfiles so that everything is installed globally as root, and we only switch to `$NB_USER` prior to launching the server. This leaves `/home/$NB_USER` empty, so that it can be bound to a Docker volume wholesale, and `~/workdir` isn’t required anymore. Is there something I haven’t considered (but you may have) which makes such a setup undesirable? Otherwise, would it make sense to use something like this as the default?

**Comment by minrk** [comment]
It should be fine to mount user home directories as volumes, as long as anything in HOME that you need is moved to somewhere that doesn't get clobbered. I typically mount home in my JupyterHub instances, and don't use anything that these containers put in HOME. There are one or two things we write in home, but I think we don't actually *need* to write anything in home.

**Comment by eigengrau** [comment]
Oh, right; actually, no modules are being installed under home, after all. I was confused by the fact that pip was being invoked as a regular user a few times – but because it’s Conda’s pip the packages are installed under `/opt`. So it seems the only change needed to be able to mount volumes on top of ~ is `jupyter_notebook_config.py`, which could be installed to `/etc` instead to keep it accessible.

I’ll probably go ahead and install the whole Conda environment as root too, if only to ensure that users don’t install anything there (since it would be lost after a reprovisioning). Thank you kindly for the feedback. I can reference my commits here later, in case you find them useful.
