### ISSUE TITLE
Shorten path to notebook work directory?

### ISSUE THREAD

**Issue by parente** [jupyter/docker-stacks#23]
Currently, the notebook working directory is in /home/jovyan/work which is borrowed from the original setup from the original http://github.com/jupyter/docker-demo-images Dockerfile. It has been raised that this path is a bit long (https://github.com/jupyter/docker-stacks/pull/21#issuecomment-136131479) and that it introduces an extra if block check in the start-notebook.sh script to copy in skeleton files post jovyan user creation in the case where the work directory is host mounted. 

The first problem might be something we can change albeit at the cost of breaking existing users of the image. The second problem is not exclusive to the notebook directory location, however: if the user host mounts a Jupyter config or any other file in the home directory, the skeleton file copy logic is required.

Anything we can / should do?

**Comment by rgbkrk** [comment]
Would it be ok if the default working directory was `/home/jovyan/`?

**Comment by parente** [comment]
I forgot to /cc @costerwi who requested this change originally.

My vote: Leave it as is. It's not complicating anything in the startup script. We'd still need the skeleton logic to deal with jupyter config files, extensions, etc. that the user decides to mount at `docker run` time in the jovyan home dir before the dir gets created on container start. (Selfish hat on ...) Plus I know of a number of users of these containers internally here who will grumble if the path suddenly changes without an associated image version change.

**Comment by rgbkrk** [comment]
Sounds good to me. I've enjoyed the vision and direction you've laid out here, and a single directory is much cleaner (no dotfiles, misc. config, etc. showing on the dashboard)

**Comment by costerwi** [comment]
I initially separated the `/notebooks` directory because it was created in the Dockerfile before the jovyan user was added by the script. I made it writable by the group `users` which jovyan would eventually join. #16

It seems messy to have the notebooks intertwined within /home/jovyan but I don't have a strong argument against the current momentum.  I have no limitations in the current image.

**Comment by costerwi** [comment]
A potential benefit for creating a separate notebook directory within the Dockerfile (before jovyan and his home directory exist) is that it would allow dependent images to easily COPY starter notebooks into that directory.  Of course, this is solvable in other ways as well.

**Comment by parente** [comment]
What if the minimal-notebook Dockerfile does create the `/home/jovyan/work` directory? Then subimages could COPY files in there. And at runtime, I think the `start-notebook.sh` logic is already set to fix permissions and adapt to the fact that directory already exists.

**Comment by costerwi** [comment]
Yes, I think that would be a working option.

**Comment by parente** [comment]
Confirmed that subimages can COPY or ADD files anywhere in `/home/jovyan` and the start script will properly deal with them. Needs to be doc'ed in the READMEs.

**Comment by parente** [comment]
Think we agreed to keep path as-is. Current stack setup should allow COPY/ADD from Dockerfiles or mounting from host without any issues.
