### ISSUE TITLE
resuing to serve hidden directory

### ISSUE THREAD

**Issue by noahdesu** [jupyter/docker-stacks#230]
I just upgraded to Fedora 24 and have run into a problem using the scipy notebook. This is how I've been running things:

```bash
sudo docker run -p 8888:8888 -v `pwd`:/home/jovyan/work jupyter/scipy-notebook
[I 03:41:56.440 NotebookApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
[W 03:41:56.482 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 03:41:56.482 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.
[I 03:41:56.496 NotebookApp] Serving notebooks from local directory: /home/jovyan/work
[I 03:41:56.496 NotebookApp] 0 active kernels 
[I 03:41:56.496 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:8888/
[I 03:41:56.496 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```

When I navigate to `http://localhost:8888` I get the following error:

```bash
[I 03:42:37.817 NotebookApp] 302 GET / (172.17.0.1) 1.03ms
[I 03:42:37.828 NotebookApp] Refusing to serve hidden directory, via 404 Error
[W 03:42:37.860 NotebookApp] 404 GET /tree (172.17.0.1) 32.62ms referer=None
```

And the browser displays `404 : Not Found You are requesting a page that does not exist!`

My docker version is:

```bash
[nwatkins@eduroam-169-233-251-40 zlog-experiments]$ docker --version
Docker version 1.10.3, build 19b5791/1.10.3
```

**Comment by parente** [comment]
Since you've mounted the work directory from the host, you have to give the jovyan user (uid 1000, group 100) read, write, list permission to the host dir. Try chowning the host dir to that user id before running.

**Comment by noahdesu** [comment]
This still doesn't seem to work as I would expect. I create a directory with full access granted to anyone:

```bash
[nwatkins@eduroam-169-233-248-217 zlog-experiments]$ mkdir /tmp/foo
[nwatkins@eduroam-169-233-248-217 zlog-experiments]$ chmod a+rwx /tmp/foo
```

And mount that in the docker image with no access to list the directory

```
[nwatkins@eduroam-169-233-248-217 zlog-experiments]$ sudo docker run -v /tmp/foo:/home/jovyan/work jupyter/scipy-notebook ls /home/jovyan/work/
ls: cannot open directory /home/jovyan/work/: Permission denied
```

It also gives the same error when using `-u 1000:1000` which is the uid/gid of the host user.

**Comment by parente** [comment]
Tested the latest `jupyter/scipy-notebook` on a Ubuntu 14.04 VM with docker 1.11.x. As root:

```
mkdir /tmp/foo
touch /tmp/foo/a_file
chmod -R a+rwx /tmp/foo
docker run -v /tmp/foo:/home/jovyan/work jupyter/scipy-notebook ls -l /home/jovyan/work/
-rwxrwxrwx 1 root root 0 Jul  2 19:20 a_file
```

Do you have selinux enabled? What version of docker are you using?

**Comment by noahdesu** [comment]
This was indeed a SELinux issue. The solution was to modify the volume mount and use the 'z' option. So, it turns into `-v /work/path:/containter/path:z` which will set the SELinux policy automatically.

**Comment by parente** [comment]
@noahdesu Glad you found it. We should get this doc'ed on the recipes page probably.
