### ISSUE TITLE
Unable to set SparkContext for Python 2 kernel

### ISSUE THREAD

**Issue by jgwerner** [jupyter/docker-stacks#231]
When using Python 2 kernel with spark in local mode [as described here](https://github.com/jupyter/docker-stacks/tree/master/pyspark-notebook#using-spark-local-mode), the following error is returned:

> Exception: Python in worker has different version 3.5 than that in driver 2.7, PySpark cannot run with different minor versions

The same error appears in https://try.jupyter.org.

What would you suggest is the best way to enable Python 2 kernel for your version of PySpark notebook?

**Comment by parente** [comment]
You need to set the `PYSPARK_PYTHON` environment var to point to the python2 interpreter so that both the driver (kernel) and workers are using the same version of Python. This should probably go in the READMEs.

```
# make sure the driver and workers all use Python2
import os
os.environ['PYSPARK_PYTHON'] = '/opt/conda/envs/python2/bin/python'

import pyspark
sc = pyspark.SparkContext('local[*]')

# do something to prove it works
rdd = sc.parallelize(range(1000))
rdd.takeSample(False, 5)
```

**Comment by jgwerner** [comment]
@parente thank you. It works! It is in the README, I hadn't seen it because I was only configuring for Local Mode and it's detailed in the Mesos section. 👍
