### ISSUE TITLE
Importing matplot lib gives an error

### ISSUE THREAD

**Issue by jatinrajani** [jupyter/docker-stacks#232]
I installed matplotlib using pip install matplotlib in normal compiler it works fine but in virtual environment (jupyter notebook)it returns this stack trace 
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-82be63b7783c> in <module>()
----> 1 import matplotlib

ImportError: No module named matplotlib

**Comment by parente** [comment]
@jatinrajani Are you using one of the docker images from this repository? If so, which one?

**Comment by parente** [comment]
This issue has been idle for a while. @jatinrajani, feel free to reopen if you're still facing the issue and can provide the requested info.
