### ISSUE TITLE
Can't get to the pyspark shell

### ISSUE THREAD

**Issue by blahster** [jupyter/docker-stacks#234]
I'm using the all-spark-notebook image.
How do I start the pyspark shell?
I got in with a -it /bin/bash but couldn't find the pyspark command.

**Comment by parente** [comment]
The images are setup to run jupyter notebook pre-configured to work with local Spark or Spark on Mesos. If you're talking about using the pyspark command line:

```
docker run -it --rm jupyter/all-spark-notebook /usr/local/spark/bin/pyspark
```

should do the trick (for local mode at least).

**Comment by blahster** [comment]
That worked and also,
`docker exec -it <name> /bin/bash` with `/usr/local/spark/bin/pyspark` worked.
The trouble, I now see was that `/usr/local/spark/bin` was not in $PATH
Thanks @parente
