### ISSUE TITLE
Don't use supervisor as the init process

### ISSUE THREAD

**Issue by parente** [jupyter/docker-stacks#24]
See https://github.com/jupyter/notebook/issues/334#issuecomment-137703722 for background.

Possible fixes ...

1. Switch to phusion/baseimage. Concern: size and change of OS.

  ```
  phusion/baseimage              latest              e9f50c1887ea        7 weeks ago         237.7 MB
  ubuntu                         14.04               d2a0ecffe6fa        8 weeks ago         188.4 MB
  debian                         wheezy              065218d54d7d        11 weeks ago        84.97 MB
  ```

2.  Use runit like phusion/baseimage does (http://www.sourcediver.org/blog/2014/11/17/using-runit-in-a-docker-container/). Concern: env var workaround described therein.

3. Port phusion/baseimage to debian. Concern: yet another thing to maintain.

4. Wait for docker to give reaping "for free" (https://github.com/docker/docker/issues/11529).

**Comment by krallin** [comment]
Hey there,

I apologize for the shameless plug, but I noticed you were considering using `phusion/baseimage` for its zombie reaping capabilities but were concerned about the size and having to port it to Debian. 

I happen to have written a tool just for that. It's called `tini`, and it's used in a few official Docker images (see here: https://github.com/docker-library/official-images#init). You might want to have a look.

If you're curious; you can find it here on Github: https://github.com/krallin/tini

**Comment by mjbright** [comment]
I love the name already, 'tini' !

**Comment by parente** [comment]
@krallin thanks for sharing! I will definitely look into it.

**Comment by parente** [comment]
Started a branch with tini replacing supervisord. Works as advertised. I need to beat up each image a bit more to ensure there's no surprises.

One point worth clarifying: we're still going to have to set tini to run as root in the images, not because it needs to do so but because our start-notebook.sh script supports options that require root privileges, namely the jovyan UID switch and granting sudo.

**Comment by jakirkham** [comment]
Sounds cool. I've been trying out tini, as well. I'd be curious to know what you find out from your stress tests, @parente.
