### ISSUE TITLE
Save an matplotlib graph on Windows Docker

### ISSUE THREAD

**Issue by blissray** [jupyter/docker-stacks#240]
Greetings.

I try to save an ipynb file after generating a graph by matplotlib on Windows Docker (windows 10)
But I could not save the ipynb and I just saw the message "Error" on the status bar.
If I clean the matplotlib graph output, there is no problem to save the file.

Do you have any ideas regrading the problem?

**Comment by parente** [comment]
I really don't have any ideas. If you can save it without images, but with images fails, the only thing that is really changing is the size of the notebook file. Could it be a disk space issue?

**Comment by blissray** [comment]
Thank you, but I don't think so. The size of disk space is fully enough :). 

I think it's a kind of json parsing error. I don't know exactly the different methods to save images between Win and Ubuntu(or Mac OS) on Jupyter page. In Win 7, I could see the message regarding UTF-8 parsing error.

Next time, I will upload the error message with the kernel status of my python console.

**Comment by parente** [comment]
I'm closing this issue because it's been inactivate for a few months now. Please feel free to reopen it with the error message if you're still facing this issue.
