### ISSUE TITLE
jupyterhub - systemuser mode

### ISSUE THREAD

**Issue by steverweber** [jupyter/docker-stacks#242]
can the systemuser.sh also be included in the base?

```
https://github.com/jupyterhub/dockerspawner/blob/master/systemuser/systemuser.sh
```

**Comment by parente** [comment]
@jtyberg @minrk Does systemuser.sh make sense here?

**Comment by steverweber** [comment]
humm there is more to it....
https://github.com/jupyterhub/dockerspawner/blob/master/singleuser/Dockerfile

**Comment by parente** [comment]
@steverweber Well, the singleuser config is already included and all of the READMEs have a section on how to use it. (https://github.com/jupyter/docker-stacks/tree/master/base-notebook#jupyterhub)

You're asking about systemuser instead, right?

**Comment by steverweber** [comment]
/systemuser/

**Comment by jtyberg** [comment]
Well, I suppose it's the same thing as including singleuser.sh in the image.   Since jupyterhub/dockerspawner has both spawners, including both scripts seems consistent.

**Comment by steverweber** [comment]
@jtyberg I assume the same... however the Dockfiles are a little different from one-another so perhaps a little extra overview is needed.

https://github.com/jupyterhub/dockerspawner/blob/master/systemuser/Dockerfile
https://github.com/jupyterhub/dockerspawner/blob/master/singleuser/Dockerfile

**Comment by jtyberg** [comment]
`docker-stacks` doesn't use the Dockerfiles over in jupyterhub/dockerspawner.

All we do is copy the [start-singleuser.sh](https://github.com/jupyter/docker-stacks/blob/master/base-notebook/start-singleuser.sh) bash script into the container image so it's available.   

https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile#L89

So if someone comes along and wants to run the image in a JupyterHub setup, they just run the  script to run the notebook in a mode compatible with JHub.  We could do the same for `start-systemuser.sh`, I would think.

**Comment by parente** [comment]
@steverweber Would you like to submit the start-systemuser.sh script addition as a PR? The line to mimic has moved a bit since @jtyberg's comment. It's now here:

https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile#L94

**Comment by natbusa** [comment]
All the systemuser.sh currently does (on top of singleuser.sh) is to remove the default user jovyan and `useradd -u $USER_ID -s $SHELL $USER`.

I wonder if we could reduce the number of scripts by using the `-e NB_UID=$USER_ID` and `--user root` mechanism which is already availably in the jupyter stacks and map the `-v /home/jovyan/work`. @parente @jtyberg @minrk Any thought about this?

**Comment by parente** [comment]
Sorry for the delay in responding @natbusa. `-e NB_UID` was added specifically to support switching to the UID of a user on the host machine. I'm not sure how configuring that would work from the JupyterHub side.

**Comment by parente** [comment]
Also, I'm wracking my brain trying to remember why we don't fetch the singleuser.sh script from its source repository at build time instead of having a copy/pasted version here in docker-stacks. It may have been that way to start and we moved away from it. If that's not the case, we should consider it if those scripts change infrequently and are compatible across versions of JupyterHub.

**Comment by jtyberg** [comment]
@parente I brought over the start-singleuser.sh script. I _think_ the reason I didn't pull it in (from dockerspawner) was because I thought other spawners needed it too. In fact, I can't seem to find it in any other Jupyter repos now. But I think folks expect the script to be in the base notebook image nowadays (see https://github.com/jupyterhub/dockerspawner/pull/153).

**Comment by parente** [comment]
Re-reading this issue, I'm not sure whether it's something that we still need to address or not. A long time has passed and no one has re-raised the desire to have the systemuser script in the images or noted that it's no longer needed.

I'm going to close this issue as inactive. If someone does find that the systemuser script is worth having for some use case, I'll be happy to review a PR that adds it along with documentation about when and how to use it.
