### ISSUE TITLE
nbconvert failed: Inkscape svg to pdf conversion failed

### ISSUE THREAD

**Issue by parente** [jupyter/docker-stacks#243]
I tried converting a trivial notebook (1 markdown cell, 1 code cell, ggplot output) on the latest jupyter/datascience-notebook image (tag: `97a5071c5775`) to a PDF and it failed with a different error than the one in this issue: `nbconvert failed: Inkscape svg to pdf conversion failed`.

Reported in #99 but appears to be a new issue, not the same as the original report.

**Comment by parente** [comment]
Manually doing `apt-get install inkscape` fixes the problem. We can throw it into minimal-notebook where pandoc and the other nbconvert prereqs are.  Or we can put this only in images that use SVGs by default like r- and datascience-notebook.

I think the former is easier to reason about even though it bloats the minimal-notebook image by another ~30 MB.

**Comment by jakirkham** [comment]
Adding to minimal seems reasonable. I mean we are already adding TeXLive to it.
