### ISSUE TITLE
Add @jtyberg as a maintainer?

### ISSUE THREAD

**Issue by parente** [jupyter/docker-stacks#244]
I was chatting with @jtyberg who has contributed a few fixes here. He's willing to help out with reviewing PRs, builds, and whatnot.

Any objections? (+1 from me obviously)

**Comment by jtyberg** [comment]
Yeah, I'd be happy to help out.

**Comment by jakirkham** [comment]
👍 Seems you already have been helping out. 😄

**Comment by parente** [comment]
@jtyberg I've added your GitHub public key to the build VM and given you merge permissions here.  There's a maintainers section in the README.

Happy to have you helping out!
