### ISSUE TITLE
Pylab fails due to missing PyQT4. After installing it the kernel dies

### ISSUE THREAD

**Issue by brett--anderson** [jupyter/docker-stacks#245]
I'm using the following docker file:

```
FROM jupyter/datascience-notebook

RUN conda install -y pyqt

EXPOSE 8888
```

if I execute the code `%pylab` in a notebook I see the following:

`Using matplotlib backend: Qt4Agg
Populating the interactive namespace from numpy and matplotlib`

Then a popup appears with the message 

> The kernel appears to have died. It will restart automatically.

The notebook application states:

```
notebook_1 |  : cannot connect to X server
notebook_1 | [I 05:29:16.447 NotebookApp] KernelRestarter: restarting kernel (1/5)
notebook_1 | WARNING:root:kernel 52366f29-201e-4d9e-a1d4-a735e421e1d7 restarted
```

This seems like a bug (I also feel like a data science notebook should run pylab by default)

**Comment by jakirkham** [comment]
So if one is to run such a docker file, I think one must configure an X server and X11 port forwarding. This [tutorial]( http://wiki.ros.org/docker/Tutorials/GUI ) seems to be pretty well done.

As this is not behavior we currently support, I would argue it is not a bug. Instead it is either a feature request or a documentation issue.

Please let us know if you have more questions.

**Comment by brett--anderson** [comment]
Thanks for getting back to me. For anyone else who finds this as part of a Google search, the trick is to use:

```
%matplotlib inline

import matplotlib.pyplot as plt
```

Inside the notebook to get access to the 'plt' module. However, if you are using iPython directly from the shell you can use the command:

`%pylab`

Trying to use that last command in a notebook, rather than a shell, will kill the kernel.
