### ISSUE TITLE
missing SQLAlchemy for python2 in scipy-notebook 

### ISSUE THREAD

**Issue by midnightradio** [jupyter/docker-stacks#248]
While using datascience-notebook, I met a problem with importing a package sqlalchemy. And I found that there was no sqlalchemy installed for python2 which I was using with the notebook. I address the problem caused by scipy-notebook image installing conda packages for both python2 and python3 is based on base-notebook which only installs python3 and other pakcages including sqlalchemy. 

Though I think base-notebook should contain python2 with sqlalchemy instead of supporting only python3, to make a workaround solution much easier, I added the package to the parameters for conda install command for scipy-notebook. I built, tested and it works.

**Comment by parente** [comment]
SQLAlchemy is not installed directly in base-notebook. It's a dependency of jupyterhub which is installed there.

That said, I don't have a problem with adding it explicitly to both the Python2 and Python3 environments the scipy-notebook image. Would you mind updating your PR to include a statement to install it for both Python2 and 3 in that image?

**Comment by jakirkham** [comment]
Should we just added in base though if that is where it is getting added to Python 3?

**Comment by parente** [comment]
Base doesn't even have the Python 2 environment iirc. It's only in base by virtue of being an implicit dependency of jhub.

**Comment by midnightradio** [comment]
I was curious about which package in base-notebook leads sqlachemy to be installed implicitly and hesitate to put explicit installation in scipy-notebook skipping base and minimal. Now it seems reasonable to do so, right?

One other thing I had to think about after PR was it is still useless without any drivers for a database but we cannot provide all drivers before one got chosen by a user. However, putting necessaries of MySQL drivers along with sqlal hemy would help many users with supporting the most popular uses but also with providing a starting point letting certain users to know where should they modify to meet their own needs.

With those consideration, PR updated.

**Comment by parente** [comment]
Fixed by #249. Thanks again! 🎈
