### ISSUE TITLE
Conda version is old

### ISSUE THREAD

**Issue by niallrobinson** [jupyter/docker-stacks#252]
Its seems that the base notebook conda version is old
https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile#L60

I'm running 4.1.9 on my machine. This is leading to problems with `Warning: somethings is wrong with binstar_client (No module named binstar_client.utils)` when resolving some dependancies on subsequence conda installs. This should be resolved by a more modern conda https://github.com/conda/conda/issues/3141

Should we update the base notebook to use a more modern conda version?

**Comment by parente** [comment]
Sure. PRs accepted if you'd like to do it. Otherwise, we'll get to it.
