### ISSUE TITLE
adding external repositories and dependencies?

### ISSUE THREAD

**Issue by eualin** [jupyter/docker-stacks#254]
I have been using `spark notebook` for quite some time now but I would also like to give a try on jupyter's `all-spark-nootbook`. However, I cannot figure out how to add private/remote maven repositories and library dependences. Bellow, I quote how I do this on `spark notebook`. I would appreciate if you could give me some hints how to replicate this on jupyetr's `all-spark-notebook` and then I will be happy to add these instructions on the docker recipes page. :)

> :local-repo /jars/
> 
> :remote-repo REPO % default % http://DOMAIN:PORT/artifactory/libs-mirror % maven
> 
> :dp private-GroupId % private-ArtifactId % 2.1.0_s2.10
> 
> import my.private.api
> 
> :dp com.github.tototoshi % scala-csv_2.10 % 1.3.3
> 
> import com.github.tototoshi.csv._
>

**Comment by parente** [comment]
I think this is more a function of the kernel (roughly: language) you want to use than it is of the container / Jupyter notebook server itself. For example, the Toree kernel in all-spark-notebook supports an `%AddJar http://example.com/myjar.jar` magic. The IPython kernel doesn't have such a magic, but pyspark [honors package names in the PYSPARK_SUBMIT_ARGS env var](https://gist.github.com/parente/c95fdaba5a9a066efaab).

**Comment by eualin** [comment]
You're right. As far as I understand, I had to pass all those settings during the creation of the container. So, the following worked ok for me:

`-e SPARK_OPTS='--name NAME --master local[*] --repositories http://DOMAIN:PORT/artifactory/libs-mirror --conf spark.executor.memory=4g --conf spark.serializer=org.apache.spark.serializer.KryoSerializer --conf spark.jars.packages=com.github.tototoshi:scala-csv_2.10:1.3.3,com.databricks:spark-csv_2.10:1.4.0,my-private:library:2.1.0_s2.10' \`
