### ISSUE TITLE
Add tensorflow support

### ISSUE THREAD

**Issue by waitingkuo** [jupyter/docker-stacks#264]
Hi, I'd like to add a `tensorflow` in. Should I create a new branch based on `scipy-notebook`? Or just modify `scipy-notebook`?

Thanks

**Comment by parente** [comment]
I think Google already builds tensorflow Docker images specialized for GPUs and whatnot: https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#docker-installation

**Comment by waitingkuo** [comment]
The Google one seems to support tensorflow only. It's python2 only and it doesn't contains common pydata tools such like pandas and scikit-learn. I think we can build a more common one, i.e. supports python2 & python3, install common pyspark packages.

**Comment by parente** [comment]
Are you thinking about multiple TF configurations, like GPU vs CPU? Does it make sense to add TF here or inherit from the Google images and add the other libraries? 

I have not used TF much so I'm asking to understand whether it makes sense to add TF here and, if so, how.

**Comment by waitingkuo** [comment]
I used congo to install tensorflow. I think we can only provide the single machine mode (CPU) and the client for the distributed mode as we won't deploy the workers in notebook.

Following is the architecture for the distributed mode. Only the workers need to build with GPU supports. That could keep our notebook simple.
<img width="355" alt="screen shot 2016-08-24 at 8 05 55 pm" src="https://cloud.githubusercontent.com/assets/1100923/17929967/7d2df46e-6a36-11e6-859d-80ac5399c691.png">

**Comment by parente** [comment]
Fixed by #266.
