### ISSUE TITLE
https and password

### ISSUE THREAD

**Issue by ephes** [jupyter/docker-stacks#265]
If I set PASSWORD=password and USE_HTTPS=yes together it's possible to log in but, the notebook can not reach the kernel. After unsetting USE_HTTPS it works :/.

**Comment by parente** [comment]
Can you paste your docker run command?

**Comment by ephes** [comment]
Sure:
```
docker run -e PASSWORD=foobar -e USE_HTTPS=yes -p 8888:8888 jupyter/datascience-notebook
```

**Comment by parente** [comment]
Using those options on jupyter/base-notebook worked fine for me. I'll pull datascience-notebook and try that next.

**Comment by parente** [comment]
On my docker host, the same command works fine with the datascience-notebook. I'm able to launch Python2/3, R, and Julia kernels. 

What version of docker are you running? Are there any limits set on your docker host that might be impacting your container (e.g., low limit on number of processes or files or ports)?

**Comment by parente** [comment]
I'm going to close this issue since it's been inactivate for a couple of months now. Feel free to reopen it with the additional information about your host if you're still hitting the original problem.
