### ISSUE TITLE
start-notebook.sh should be split into config-notebook.sh and start-notebook.sh

### ISSUE THREAD

**Issue by mjbright** [jupyter/docker-stacks#27]
Related to my comment in issue [#25](https://github.com/jupyter/docker-stacks/issues/25) it would be useful to allow derivation of the various docker-stacks.

The start-notebook.sh script actually has 2 distinct functions
- configure the notebook (most of the script)
- starting the notebook (currently via supervisord)

We should have a CMD in the Dockerfile such as config-start.sh (you can surely think of a better name!) which then calls
- config-notebook.sh
- start-notebook.sh

In this way anyone can cleanly derive from the docker-stacks image by modifying config-start.sh to call
- config-notebook.sh
- derived-config.sh
- start-notebook.sh

**Comment by parente** [comment]
I think preferring the "Docker way" of doing thing should trump custom hooks. In issue #25, I think that's possible. (See my comment there.) If I'm missing something and it's not, or if there's another use case that does indeed require more scripts vs Dockerfile-isms, then script refactoring makes sense.

**Comment by mjbright** [comment]
I agree I'd prefer the Dockerfile approach, but I'd prefer it for the
creation of jovyan user also.

**Comment by parente** [comment]
Let's keep this convo going over in issue #25 which has the problem. This is a potential solution.
