### ISSUE TITLE
Add MicroBadger badge and labels

### ISSUE THREAD

**Issue by thewtex** [jupyter/docker-stacks#270]
It would be nice to have [MicroBadger](https://microbadger.com/) badges. They show the number of layers and size. E.g.

[![](https://images.microbadger.com/badges/image/microscaling/microscaling.svg)](http://microbadger.com/#/images/microscaling/microscaling)

Also, an enhancement may be to the adopt the [labeling / Makefile approach](https://microbadger.com/?utm_source=ilbrokentag&utm_medium=email&utm_campaign=microbadgeril#/labels) suggested on MicroBadger to [add Git revision metadata to the Docker image](https://microbadger.com/?utm_source=ilbrokentag&utm_medium=email&utm_campaign=microbadgeril#/about) with the LABEL command:

**Comment by parente** [comment]
Do you know if the LABEL directive breaks cache during Docker builds? Right now, we rely heavily on docker caching to avoid rebuilding dependent layers unnecessarily. We want to reduce the pull size as much as possible for users that want to update to newer images.

**Comment by thewtex** [comment]
A changed LABEL directive does break the cache. If caching for rebuilds / pulls is very important, then the revision label could be changed on an image only when that image's content actually changes. Or, the formal labelling could be skipped and the badges could just be adopted to show the size of each image.

**Comment by parente** [comment]
I'm cool with adopting the badges for now since that's straightfoward. Would you like to make the PR to update all the READMEs?

**Comment by thewtex** [comment]
Cool.  I will create a PR (although it may be a while).

**Comment by parente** [comment]
Fixed by #300
