### ISSUE TITLE
"plot without title" when trying to plot in R Notebook

### ISSUE THREAD

**Issue by LucianoSP** [jupyter/docker-stacks#276]
No graphics package works in R Notebook, it shows "plot without title".
Sorry, I´m kinda newbie with this but I can provide more information if needed. 
I just pulled the docker container today. As it didn´t work, I went to the image and tried "conda update --all". It updated a bunch of packages but it still didn´t work. 
Thanks.

**Comment by parente** [comment]
Thanks for the report. This is tracked in #210.
