### ISSUE TITLE
Widgets frontend and backend no longer compatible after latest docker pull

### ISSUE THREAD

**Issue by ian-contiamo** [jupyter/docker-stacks#285]
I pulled the latest docker image (tag `54552d36cf0a`), and I get the following warning in the console:
> Widget frontend version does not match the backend.

Are the versions really incompatible, or is it just a matter of updating the requirements somewhere?

**Comment by ian-contiamo** [comment]
PS. Creating a widget displays the ominous error message below, so it's definitely hurting usability:
> The installed widget Javascript is the wrong version.

**Comment by parente** [comment]
Interesting. What notebook stack are you using?

**Comment by ian-contiamo** [comment]
I use `jupyter/scipy-notebook` (sorry, I should have mentioned it from the beginning!)

**Comment by parente** [comment]
The conda environment in the container has:

```
ipywidgets                5.1.5                    py35_0    conda-forge
```

The jupyter-js-widgets JS sends a `jupyter.widget.version` comm message request and the kernel responds with `~1.1.2`.

**Comment by parente** [comment]
Starting with a fresh conda environment, I wind up with:

```
ipywidgets                5.2.2                    py35_0    conda-forge
```

and a `~1.2.0` response. Looks like an upgrade will fix things. Maybe it was a bad release that we happened to grab?

**Comment by ian-contiamo** [comment]
Thanks @parente, I'll look out for the upgrade!

**Comment by parente** [comment]
Tag `d0b2d159cc6c` on Docker Hub has the new version. Please reopen if you still see the problem.

**Comment by ian-contiamo** [comment]
Problem solved, thanks!
