### ISSUE TITLE
Error from numexpr and mkl when doing math with pandas Series objects

### ISSUE THREAD

**Issue by MichaelStetner** [jupyter/docker-stacks#295]
I am using scipy-notebook

I get an error when running the following code:
```python
import pandas as pd
N = 10001 # no problems if N=10000
x = pd.Series([1.0] * N)
x ** 2  # error
```
Not all math operations cause a crash. I tried `x / 2` which crashes, while `x * 2` and `x + 2` do not crash.

When it crashes, I get the following error message:
```
pythonpython: : symbol lookup errorsymbol lookup error: : /opt/conda/lib/python3.5/site-packages/numexpr/../../../libmkl_vml_mc3.so/opt/conda/lib/python3.5/site-packages/numexpr/../../../libmkl_vml_mc3.so: : undefined symbol: mkl_serv_getenvundefined symbol: mkl_serv_getenv
```

I'm pretty sure this is related to https://github.com/conda/conda/issues/2031
As suggested in that issue, I fixed it by doing:
```
conda install mkl-rt
```

What is the right way to fix this so I don't get these errors out of the box?

**Comment by parente** [comment]
`jupyter/scipy-notebook` installs `numexpr=2.5*` which not on conda-forge. It comes from the defaults channel where it the mkl version is preferred. Yet all of the other numpy-using packages come from conda-forge where open_blas is preferred. Mixing the two is causing this issue (and likely more lurking problems).

I'm prepping a PR that 1) bumps numexpr to 2.6 which is on conda-forge and 2) installs the nomkl package to prevent mixing from happening again. 

I don't know if anyone is relying on an mkl version of numpy in these images. We'll find out I guess.

**Comment by andrewgiessel** [comment]
Just reporting that I had this problem as well, when dividing a Pandas dataframe by a numpy array, using the most recent Anaconda 2.7 install (4.2.0)

Interstingly, dividing the underlying numpy arrays did not cause an error.

We solved this with: 
`conda install mkl-rt`

For reference/SEO, the error was:

`symbol lookup error: /shared/software/anaconda_20161017_py2/lib/python2.7/site-packages/scipy/special/../../../../libmkl_vml_avx2.so: undefined symbol: mkl_serv_getenv`

**Comment by brovercleveland** [comment]
Similar issue, using Python 3.5.2 :: Anaconda 4.2.0 (64-bit).  Was using numexpr via the `pandas.DataFrame.eval` method.  Issue was resolved with `conda install mkl-rt`.

**Comment by parente** [comment]
Since most of our packages are coming from conda-forge now, I was planning to go the no-mkl route instead of mixing mkl builds from the defaults channel with non-mkl everything else from conda-forge. 

Is anyone relying on the mkl on these images, other than to make things work at the moment?

**Comment by parente** [comment]
The nomkl approach is in image tag `6939ea1b1df3`. Please give it a shot and see if you hit any further issues.

**Comment by MichaelStetner** [comment]
It's working for me. Thanks!
