### ISSUE TITLE
"Operation not permitted (src/zmq.cpp:762)" Error

### ISSUE THREAD

**Issue by Jagmills** [jupyter/docker-stacks#297]
Hi everyone,

I am getting the error message with the latest scipy-notebook Docker image:

Operation not permitted (src/zmq.cpp:762)

output in my Jupyter logs when performing a couple of specific tasks - for example, configuring Matplotlib to plot with LaTeX formatting or creating a static print view.

I have:
pyzmq                     16.0.0                   py35_0 
zeromq                    4.1.5                         0    conda-forge

And I'm afraid I'm not sure of any other relevant packages. Has anyone seen this before?

**Comment by parente** [comment]
@Jagmills can you point me to an example notebook that I can use to reproduce the problem?

**Comment by parente** [comment]
This issue has been idle for a few months so I'm going to close it. @Jagmills if you're still having problems and can provide an example to help us reproduce the issue, please reopen with a link to your example notebook.
