### ISSUE TITLE
Include sparklyr on the Spark images

### ISSUE THREAD

**Issue by rgbkrk** [jupyter/docker-stacks#298]

**Comment by parente** [comment]
Sure. all-spark-notebook is the one with SparkR support.

**Comment by parente** [comment]
Still interested in submitting a PR? The images do have Spark 2.0.2 at the moment.

**Comment by transistorize** [comment]
@parente I'd like to jump in and help here if possible, as I just went through the exercise of trying to set all this up with RStudio. Also, I'd like to get Spark 2.1.0 in here. Would you prefer two separate PRs?

**Comment by parente** [comment]
Thanks for the interest, @transistorize. The R packages in the images are currently coming from the conda R channel. I'm not sure what that'll mean as far as getting sparklyr installed.

> Also, I'd like to get Spark 2.1.0 in here. Would you prefer two separate PRs? Aside from the version bump in pyspark and the README.md updates, anything else that should be done?

The Spark bump should probably be it's own PR. The main work in the upgrade will be checking the kernels in the all-spark-notebook to make sure they're all functioning:

* Python kernel w/ PySpark (should be fine, the py lib comes with Spark)
* R kernel w/ R Spark (should also be fine, the R lib comes with Spark)
* Scala Apache Toree kernel (needs a quick test, required new build for the 1.6 -> 2.0 upgrade)
* Spylon Kernel (should be fine, but should also be updated to use the latest version from conda-forge)

If you take a stab at the upgrade PR, I can jump in and help if any of this is unclear or you run into new problems.

**Comment by transistorize** [comment]
Sparklyr can be installed using the `devtools` toolset within R, so I don't think that should be an issue. The trick will come with configuring it properly for these sets of Spark notebooks.  I'll open a separate issue for the version bump.

**Comment by parente** [comment]
Made easier one #382 happens.
