### ISSUE TITLE
Toree would need to get installed from an URL and not pypi

### ISSUE THREAD

**Issue by lbustelo** [jupyter/docker-stacks#301]
This is a heads up that at some point we will need to update the Dockerfile for the all-spark-notebook to install Toree from an URL that points to a package hosted by Apache.org. We will no longer be able to store pip packages in pypi and pretty soon I'm going to be deleting pypi project. 

Before I do that, I will submit a PR pointing to the correct URL

/cc @parente

**Comment by parente** [comment]
Sure thing. Thanks.

**Comment by parente** [comment]
Closed by #263.
