### ISSUE TITLE
Unable to install R package because anaconda overwrites include path

### ISSUE THREAD

**Issue by bowenli37** [jupyter/docker-stacks#304]
Anaconda R overwrites R default include path of "/usr/include" to Anaconda home path. I intended to install R packages RPostgreSQL. So I install libpq-dev by apt-get. libpq-fe.h is located at /usr/include/postgresql/libpq-fe.h. But install.packages('RPostgreSQL') failed in R due to missing libpq-fe.h.  In /opt/conda/lib/R/etc/Makeconf file, it suggests that flags used in C & C++ compilation were overwritten at time of executing ./configure. Adding this line to /opt/conda/lib/R/etc/Makevars does not have any effect:

      PKG_CXXFLAGS=/usr/include 

Is there any possible solutions?

I came across some threads on similar problem in stackoverflow below:
[using-3rd-party-header-files-with-rcpp](http://stackoverflow.com/questions/13995266/using-3rd-party-header-files-with-rcpp)
[Installation of package ncdf fails due to missing header although it's there](http://stackoverflow.com/questions/17028465/installation-of-package-ncdf-fails-due-to-missing-header-although-its-there)

**Comment by parente** [comment]
Are you installing RPostgreSQL from the conda R channel? And it has requirements on system libraries that do not come in the package?

**Comment by parente** [comment]
I'm going to close this issue as inactive. @bowenli37 feel free to re-open with the additional information if you're still hitting problems.

**Comment by ibayer** [comment]
I have the same issue. I'm not installing RPostgreSQL from conda R channel.

**Comment by ibayer** [comment]
I have the some problem using the conda R channel:

``` bash 
conda install r-essentials
```
``` bash 
> install.packages('RPostgreSQL')

RS-PostgreSQL.h:23:26: fatal error: libpq-fe.h: No such file or directory
compilation terminated.
/home/xxx/.conda/envs/R/lib/R/etc/Makeconf:133: recipe for target 'RS-PQescape.o' failed

```
