### ISSUE TITLE
Unable to reload jupyter server with `docker kill -s HUP <container-id>`

### ISSUE THREAD

**Issue by samuelsinayoko** [jupyter/docker-stacks#309]
When sending the SIGHUP signal to a Jupyter server on a local machine (without Docker) the server is reloaded. This is convenient to reload the server with a different configuration for example. I'd like to be able to do this when running Jupyter inside a Docker container. However attempting this terminates the container instead of reloading the configuration, as shown below. 
```
$ docker run -d -p 9999:8888 jupyter/base-notebook
05a4c5110bf5a305c038595eed5cf52b8a7e9aa99a5d7a7e80ece5ba31ce4f57
$ docker kill -s HUP 05a4c511
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS      PORTS   NAMES
$ # container was killed  
```
Is there a way to achieve this?

**Comment by parente** [comment]
We run tini as the entrypoint. We may need to configure it so that it sends the signal along to the notebook server.

**Comment by mkolovic** [comment]
:+1:

**Comment by parente** [comment]
Seems that this doesn't work even after adding signal forwarding to the process group in #652

**Comment by parente** [comment]
I'm going to close this issue as inactive. If someone does find a way to get the SIGHUP forwarding to work without stopping the container along the way, I'll be happy to review a PR with the change.
