### ISSUE TITLE
Reproducing the base notebook image

### ISSUE THREAD

**Issue by EWouters** [jupyter/docker-stacks#313]
Hi all,

I'm having trouble reproducing the base notebook image using docker build on windows.

I've cloned the repo and executed the following commands in the base-notebook directory:

```bash
docker build -t my-jupyter-base .
docker run -d -p 8888:8888 my-jupyter-base
```
This doesn't seem to work:
```
$ docker ps -a
CONTAINER ID        IMAGE                   COMMAND                  CREATED              STATUS                          PORTS               NAMES
e2633b91d175        my-jupyter-base         "tini -- start-notebo"   5 seconds ago        Exited (1) 5 seconds ago                            clever_goldwasser
```

Can anyone help me build the base notebook?

**Comment by parente** [comment]
Can you try running with `-it --rm` instead of `-d` and collect the log output?

**Comment by parente** [comment]
I'm going to close this issue as inactive. @EWouters feel free to reopen it with the requested info you still need help.
