### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by bryaan** [jupyter/docker-stacks#314]
Just set USE_HTTPS="yes" and I'm getting:

`[W 06:31:31.800 NotebookApp] SSL Error on 9 ('172.25.0.1', 36564): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:645)`

**Comment by parente** [comment]
Do you get the error on first visit to the notebook server or after opening a notebook?

Can you include the URL you're using to access the notebook server in the container?

**Comment by parente** [comment]
I'm closing this issue as inactive. @bryaan feel free to reopen with the requested info if you still need help.
