### ISSUE TITLE
Cannot use jupyterhub with base notebook stack

### ISSUE THREAD

**Issue by naileakim** [jupyter/docker-stacks#316]
Hi,

I am starting with jupyter dockers stacks & jupyter hub and willing to serve the base notebook stack to multiple users in the same container.

I tried to launch the container with the alternative command `start-singleuser.sh`:

`docker run -it --rm jupyter/base-notebook start-singleuser.sh`

But got the error:

`Config option open_browser not recognized by SingleUserNotebookApp.  Did you mean browser?
JPY_API_TOKEN env is required to run jupyterhub-singleuser. Did you launch it manually?`

Can you provide a bit more info about how to use this stack with jupyter hub? (how and where to define users, location of the `jupyterhub_config.py`, etc).

Thanks in advance for all your answers 🙂

**Comment by parente** [comment]
https://github.com/jupyterhub/jupyterhub-deploy-docker has complete instructions for using these images with Jupyter Hub. I recommend starting there.

**Comment by parente** [comment]
I believe the pointer in the last comment addressed the question. Closing this.

**Comment by martinorpa** [comment]
you need add start-notebook.sh first and second  start-singleuser.sh


-> docker run -it --rm jupyter/base-notebook  start-notebook.sh  start-singleuser.sh

or 
-> on docker-compose.yml file
     volumes:
       - ./startup/start:/root/start:rw
     command: >
         sh -c "/root/start/start-notebook.sh && /root/start/start-singleuser.sh"
