### ISSUE TITLE
PEM path configuration

### ISSUE THREAD

**Issue by hholst80** [jupyter/docker-stacks#317]
When launching the notebook as a docker service it is not always possible to use the hard coded pem path here: https://github.com/jupyter/docker-stacks/blob/master/base-notebook/jupyter_notebook_config.py#L8

We have our pem files in a volume and we would like to pass the path to the docker container:
```
-e PEM_FILE=/etc/letsencrypt/live/example.com/fullcert.pem
```

and then mounting the volume with certificates into /etc/letsencrypt.

Suggested patch:

```
PEM_FILE = os.environ['PEM_FILE'] if 'PEM_FILE' in os.environ else os.path.join(jupyter_data_dir(), 'notebook.pem')
```

**Comment by parente** [comment]
You can already pass a custom path as a command line arg to the container. For example:

```
docker run -it --rm -v /example/host/volume:/etc/letsencrypt/live/example.com/fullcert.pem jupyter/scipy-notebook --NotebookApp. certfile=/etc/letsencrypt/live/example.com/fullcert.pem
```

The environment variables are largely a hold-over from the early days of these images when passing command line args through to the notebook was difficult.

Will this setup work for you? If so, we can document it in the README.

**Comment by parente** [comment]
This is now documented in the latest README for each stack.

@hholst80 feel free to reopen or open another issue if you hit any other problems.
