### ISSUE TITLE
The image of continuumio/anaconda3 has been hacked?

### ISSUE THREAD

**Issue by markqiu** [jupyter/docker-stacks#319]
I found strange minergate-cli process running in background and cosuming a lot of cpu, after I run docker of continuumio/anaconda3.

process infos are as follows:
26119 pts/0    Sl    29:24 ./opt/minergate-cli/minergate-cli -user asdfmnyy@hmamail.com -fcn+xmr
26126 pts/0    Sl     0:00 ./opt/minergate-cli/minergate-cli -user asdfmnyy@hmamail.com -fcn+xmr 0 2

# find / -name minergate-cli
/var/lib/docker/devicemapper/mnt/40a3b8140d398645055cab495a8449711ab011e47bced5c0ae3a81f93e0867cf/rootfs/root/.local/share/minergate-cli
/var/lib/docker/devicemapper/mnt/40a3b8140d398645055cab495a8449711ab011e47bced5c0ae3a81f93e0867cf/rootfs/root/.ttmp/usr/bin/minergate-cli
/var/lib/docker/devicemapper/mnt/40a3b8140d398645055cab495a8449711ab011e47bced5c0ae3a81f93e0867cf/rootfs/root/.ttmp/opt/minergate-cli
/var/lib/docker/devicemapper/mnt/40a3b8140d398645055cab495a8449711ab011e47bced5c0ae3a81f93e0867cf/rootfs/root/.ttmp/opt/minergate-cli/minergate-cli

# docker ps
CONTAINER ID        IMAGE                          COMMAND                CREATED             STATUS              PORTS                                            NAMES
40a3b8140d39        continuumio/anaconda3          "/usr/bin/tini -- /b   5 hours ago         Up 2 hours          0.0.0.0:8888->8888/tcp                           notebook

what happened?

**Comment by jakirkham** [comment]
We don't use or support `continuumio/anaconda3`. Please raise at Continuum's [repo]( https://github.com/ContinuumIO/docker-images ).

**Comment by markqiu** [comment]
sorry. ok

**Comment by jakirkham** [comment]
Not a problem.

**Comment by jakirkham** [comment]
xref: https://github.com/ContinuumIO/docker-images/issues/47
