### ISSUE TITLE
Use "NB_" prefix for environment variables

### ISSUE THREAD

**Issue by jtyberg** [jupyter/docker-stacks#32]
I ran the jupyter/all-spark-notebook container on a Mesos cluster with the notebook container port (8888) mapped to a random port on the host.  In this configuration, Mesos sets a "PORT" environment variable when running the container to the **host** port (e.g., 31674), and the notebook server ends up starting on http://localhost:31674 within the container.

To avoid potential conflicts with other environment variables, it may be a good idea to prefix the environment variables with "NB_" or similar, like we already do with NB_UID, NB_USER, etc.

**Comment by parente** [comment]
Good find.

Once again, I wonder how to make these changes while avoiding the nasty surprise of env var name changes for folks who have already pulled the image. I wonder if a tag scheme like `4.0_1`, `4.0_2`, etc. when we break **container** API compatibility (paths, env vars, etc.) could work.

**Comment by parente** [comment]
... of course by "I wonder" I mean "of course the tagging will work, but how much pain will it be to setup on Docker Hub".

**Comment by minrk** [comment]
@parente another option is to give the stacks entirely their own version, rather than tying them to the notebook package.

**Comment by parente** [comment]
That's one idea with which I'm toying. Still, it involved a tag or branch for every change that we want to capture in a Docker Hub version if we're using the automated builds on DH. If we're not, then it involves some external build system.

I'm hoping to settle on some idea for us to discuss that resolves #12 and #15 in one stroke.

**Comment by minrk** [comment]
Since DH versioning is tied to the repo, we may run into issues with branches/tags on this repo, which contains many different images. Are they all versioned/released together? etc.

**Comment by parente** [comment]
They are all versioned together at the moment because they're all notebook images. They're all rebuilt/released together too, but that's an undesirable consequence of the Docker Hub automated builds in some cases.

**Comment by parente** [comment]
@jtyberg if we move away from env vars for port, ip, and other notebook options that are now trivial to set via command line (see #47), will that cause a problem in your use case? More specifically, do you foresee any problems if we remove the INTERFACE and PORT env var support entirely to avoid conflicts like the one you hit, and require that you set these via args to the container instead?

**Comment by jtyberg** [comment]
For my use case, command line arguments should be fine, and in fact, probably better.

Now I do

```
NB_PORT=${PORT} start-notebook.sh
```

It would be more natural to do

```
start-notebook.sh --NotebookApp.port=${PORT}
```
