### ISSUE TITLE
Unknown minergate-cli

### ISSUE THREAD

**Issue by thucnc** [jupyter/docker-stacks#325]
My server got 100% CPU due to "minergate-cli -user alekx12555@mail.ru -xmr" which located in "/var/lib/docker/aufs/mnt/3e8d6784e8ebcebb116ba1899cfe1e80fb1d76eb5a0ce727320c1fa6cbc99eb8/home/jovyan/.deb/usr/bin/minergate-cli". 

As the jovyan* user is created by this docker image, so anyone can explain why I got this issue ? Thanks

(* ref: https://github.com/jupyter/docker-stacks/tree/master/minimal-notebook)

**Comment by parente** [comment]
Can you please let us know what command line you are using to start the image, where you are running the image (laptop? cloud vm?), and when you last docker pulled the image (he date in the output of docker images should be enough).

**Comment by parente** [comment]
Xref to a recent report of the same thing happening in an unrelated image https://github.com/ContinuumIO/docker-images/issues/47

**Comment by thucnc** [comment]
Hi, I ran the image by the command "docker run -p 8888:8888 --name jupyter jupyter/datascience-notebook" on 24th December 2016 on a Digital Ocean instance with built-in installed Docker.

**Comment by parente** [comment]
I suspect someone has accessed your notebook server and run commands to install minergate. 

The images here used to come up without any password protection by default. I strongly recommend you pull the latest images which at least start with a randomly generated token by default, but also allow you to configure a custom password as they always have. See any of the READMEs in the project here for more information.

If you still see minergate running after you start a new, password or token protected notebook server, please let us know.

**Comment by thucnc** [comment]
I actually set basic authentication of nginx before access to my notebook. Anyway, thank @parente, I'll try.

**Comment by parente** [comment]
If the problem reappears after you've set a password, please reopen this issue.

**Comment by Ouwen** [comment]
I have also gotten alekx12555@mail.ru mining bitcoins on my comp. Time to setup some tokens.
