### ISSUE TITLE
Consider not writing in user home

### ISSUE THREAD

**Issue by akhmerov** [jupyter/docker-stacks#331]
All the images (starting from base notebook) write part of the configuration inside the user home folder, and assume that `/home/$NB_USER/work` will be mounted. This has a practical limitation that it is not easy to setup a hub such that useful folders like `.ssh`, or e.g. `.bash_history` persist across container restarts.

I might be missing underlying assumptions and use cases, but I suggest to assume that home itself would be mounted, and instead modify the global configuration options.

**Comment by parente** [comment]
You make a good point. We've been slowly moving config files out of home and either into the sys-prefix or root prefix over time. It looks like the remaining files of significance in the user's home directory are:

```
.local/share/jupyter/jupyter_notebook_config.py
.ipython/profile_default/startup/mplimporthook.py
.conda/environments.txt
```

I know the first can move into the conda prefix /opt/conda/etc/jupyter. I think the second can as well. I have seen any negative consequences of simply deleting or ignoring the third, but I also haven't experimented or researched it much beyond running `conda env list`.

**Comment by akhmerov** [comment]
Are you referring to a specific derivative dockerfile? In `base-notebook` I only see `.bash_logout  .bashrc  .continuum  .curlrc  .jupyter  .profile  work` in home, and `.continuum` is empty.

**Comment by akhmerov** [comment]
I see now, it's in `scipy-notebook`. I might be confusing something, but I don't understand the role of this file:

```bash
docker run -it --rm jupyter/scipy-notebook bash
jovyan@9d2aacb3af29:~/work$ rm -rf ~/.conda
jovyan@9d2aacb3af29:~/work$ conda env list
# conda environments:
#
python2                  /opt/conda/envs/python2
root                  *  /opt/conda
```

**Comment by parente** [comment]
@akhmerov I don't know the role of the file either. It could be harmless to remove it. https://github.com/conda/conda/issues/945 seems to have a bit of info about it.

**Comment by akhmerov** [comment]
We're using an image without that file for a long time already. It appears it is indeed harmless to remove.

**Comment by yuvipanda** [comment]
This also means that you can't use this in KubeSpawner with Persistent storage, and I don't want to encourage the default to attach persistent storage somewhere other than $HOME. https://github.com/jupyterhub/kubespawner/issues/31 is related.

**Comment by jakirkham** [comment]
Raised an issue about `.conda` ( https://github.com/conda/conda/issues/5388 ) and `.continuum` ( https://github.com/conda/conda/issues/5389 ).

**Comment by yuvipanda** [comment]
Note that we've been mounting over $HOME in https://github.com/data-8/user-containers for a long time and it all works perfectly.

**Comment by minrk** [comment]
Re: .continuum, it's empty so presumably not needed (at least here). `.conda` only has an `environments.txt`, but removing that doesn't prevent the existing envs from working as demonstrated above, so that doesn't appear to be needed, either.
