### ISSUE TITLE
Volume Mounting via Docs Not Working with User Joyvan

### ISSUE THREAD

**Issue by nandanrao** [jupyter/docker-stacks#332]
Using jupter/scipy-notebook

From fresh Ubuntu 16.04 run docker command (as user ubuntu, uid 1000): 

```
docker run -d -v /home/ubuntu/work:/home/joyvan/work -p 8888:8888 jupyter/scipy-notebook start-notebook.sh --NotebookApp.token=''
```

Exec into the docker container to find the following, the image has created a new /home/joyvan/work directory under the root user!

```
jovyan@c45fec83bd1e:~/work$ cd /home
jovyan@c45fec83bd1e:/home$ ls -l
total 8
drwxr-xr-x 1 jovyan users 4096 Jan 27 13:05 jovyan
drwxr-xr-x 3 root   root  4096 Jan 27 13:05 joyvan
```

According to the docs, I was expecting this to mount a volume from my host machine into the /work directory that the Jupyter notebook uses as its work directory.

**Comment by DrPaulBrewer** [comment]
Check spelling it is jovyan

**Comment by nandanrao** [comment]
lol. well, shiiiiiiiiiiiiiiiit, my bad.

**Comment by pmbaumgartner** [comment]
I don't know if this is an issue, but is there some logic behind the user name? I ran into this exact same issue today. Yes, user error, yada yada, but if its preventable frustration for future users to switch to an identifiable/relevant name (conda / jupyter / jupyter-docker).

**Comment by entmike** [comment]
> lol. well, shiiiiiiiiiiiiiiiit, my bad.

Same thing happened to me today.  I keep reading `jovyan` and `joyvan`.  Lost 30 minutes of productivity on this LOL.

**Comment by Defunctionalize** [comment]
oh my god.  I've spent months on this.  I was sure the problem was some combination of Docker for Windows and using WSL (and then later in desperation WSL2) to interface with the containers.

Nope.  just spelled it wrong.   I hope someone finds this comment and judges me.

**Comment by not-so-smart** [comment]
> I don't know if this is an issue, but is there some logic behind the user name?

It's a reference to the word Jovian, which means "of or relating to Jupiter". 

Jup__i__ter -> Jup__y__ter
Jov__i__an -> Jov__y__an

I agree that spelling it with a Y just makes it look like "joy van" though.
