### ISSUE TITLE
Disable or manually set Token Auth

### ISSUE THREAD

**Issue by osobh** [jupyter/docker-stacks#336]
Hi! Thanks for using Jupyter's docker-stacks images.

**What docker image you are using?**
jupyter/datascience-notebook

**What complete docker command do you run to launch the container (omitting sensitive values)?**

docker run -d -v /root/userdata/notebooks:/home/jovyan/work/notebooks -v /${hostStorageDir}/${userNickname}:${notebookStorageDir} -e GRANT_SUDO=yes -p ${notebookMinPort}-${notebookMaxPort}:${hostPort} ${containerImage}`
Example: `docker run -it --rm -p 8889:8888 jupyter/all-spark-notebook:latest`

**What steps do you take once the container is running to reproduce the issue?**
Look at the logs and see what happened or visit the interface to see if it's alive.

**What do you expect to happen?**

be taken to a dashboard

**What actually happens?**

I'm taken to the token auth. page

What i'm looking for is a way to set my own custom auth password, like a string or something simple and also have the option to disable auth by setting a flag on my docker run command. Currently with this docker image the logs inside the container have the auth key and you would have to do a docker logs -f and look for the key in the those logs to input on the web dash to login.

In my case i'm doing auth earlier on in my process and don't  need to have these notebooks using auth, however if there is a way to set my auth to a string then i'll be fine.

**Comment by parente** [comment]
Can you try the last example under https://github.com/jupyter/docker-stacks/tree/master/base-notebook#notebook-options?

**Comment by osobh** [comment]
Thank you sir, I looked harder and in that last example after calling the container I missed adding the  "start-notebook.sh". This has solved my issues and when I run the notebook with your recommendation it starts without prompting for a password.

**Comment by NaelsonDouglas** [comment]
> Can you try the last example under https://github.com/jupyter/docker-stacks/tree/master/base-notebook#notebook-options?

The example was erased from the master branch, but if you came here looking for a solution like me, you can get a snapshot here.
https://github.com/jupyter/docker-stacks/tree/eef4285cc290fc3ca20fb00417d8d3bb81a54a85

**Comment by kylezeeuwen** [comment]
Note for posterity : here is a better link to find the common options on the base-notebook : https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html
