### ISSUE TITLE
Cant run the jupyter/pyspark-notebook on windows

### ISSUE THREAD

**Issue by sameermotwani** [jupyter/docker-stacks#338]
Hi!

**What docker image you are using?**

Example: `jupyter/pyspark-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

docker run -it --rm -p 8888:8888 \ -v "$PWD":/home/jovyan/work jupyter/pyspark-notebook

**What steps do you take once the container is running to reproduce the issue?**

Example:

1. Visit http://localhost:8888

**What do you expect to happen?**

Example: I expect the notebook to open

**What actually happens?**

Example: The site can't be reached

I checked the container is indeed running : using docker ps

**Comment by parente** [comment]
How are you running Docker on Windows: Using docker-machine in the Docker Toolkit for Windows 7 and lower, or using Docker for Windows 10 and up?

**Comment by sameermotwani** [comment]
Docker Toolkit for windows 10.

**Comment by parente** [comment]
Thanks. I was wondering if it could be how you're trying to access the container from your browser via localhost versus the IP address of a docker-machine VM. Can you include the output of `docker ps` and `docker log <your notebook container ID>` after you start the container?

**Comment by sameermotwani** [comment]
yes i was trying to access it using the local host.
Thanks! I was able to access it using the IP 192.168.99.100:2376.

However, I am facing another problem, when I start a notebook and work on it, as i make changes. They are not autosaved  and i get an error message at the top : permission denied

**Comment by sameermotwani** [comment]
Also, Why din't it work with localhost?

**Comment by parente** [comment]
> Also, Why din't it work with localhost?

The Docker Toolkit runs a virtualbox VM with its own IP. If you switch to using the more modern "Docker for Windows", you'll be able to access your containers on localhost.

> However, I am facing another problem, when I start a notebook and work on it, as i make changes. They are not autosaved and i get an error message at the top : permission denied

I'm guessing the `jovyan` user inside the container (uid: 1000, gid: 1000) does not have write permission on the directory you're mounting from the host into the container with `-v "$PWD":/home/jovyan/work`.

**Comment by sameermotwani** [comment]
Thanks a lot peter! :)

I will close this issue now.
