### ISSUE TITLE
Update Jessie to the most recent version

### ISSUE THREAD

**Issue by dhuebner** [jupyter/docker-stacks#342]
It would be good to udate the base-notebook to the most recent debian version.
Currently it's from May 2016. AFAIK there is a Jessie version 8.7 released in January 2017.
   
```
# Debian Jessie image released 2016 May 03.
FROM debian@sha256:f7062cf040f67f0c26ff46b3b44fe036c29468a7e69d8170f37c57f2eec1261b
```

**Comment by parente** [comment]
Tag `72cca2a7f3ea`
