### ISSUE TITLE
External jar not loading in notebook

### ISSUE THREAD

**Issue by fbeneventi** [jupyter/docker-stacks#346]
Hi! 

I'm using the latest jupyter/all-spark-notebook docker image and run it as:

```
docker run -d --name jupyter --restart=always\
 -p 8888:8888\
 -p 4040:4040\
 jupyter/all-spark-notebook
```

When I execute the following code in the notebook:

```
import os
os.environ['PYSPARK_SUBMIT_ARGS'] = '--packages org.apache.bahir:spark-streaming-mqtt_2.11:2.0.2 pyspark-shell'
from mqtt import MQTTUtils
```

it returns the following error:

```
ImportErrorTraceback (most recent call last)
<ipython-input-1-3dee8c3608aa> in <module>()
      1 import os
      2 os.environ['PYSPARK_SUBMIT_ARGS'] = '--packages org.apache.bahir:spark-streaming-mqtt_2.11:2.0.2 pyspark-shell'
----> 3 from mqtt import MQTTUtils

ImportError: No module named mqtt
```

While, when I run the same thing using pyspark from command line:

`jovyan@776e4a5e480e:~/work$ /usr/local/spark/bin/pyspark --packages org.apache.bahir:spark-streaming-mqtt_2.11:2.0.2`

it imports the module correctly:

```
Using Python version 2.7.9 (default, Jun 29 2016 13:08:31)
SparkSession available as 'spark'.
>>> import mqtt
>>>
```

In notebook, I tried also using:
`os.environ['SPARK_CLASSPATH'] = '/home/jovyan/work/jars/spark-streaming-mqtt_2.11-2.0.2.jar'`
or
`os.environ['PYSPARK_SUBMIT_ARGS'] = '--jars /home/jovyan/work/jars/spark-streaming-mqtt_2.11-2.0.2.jar pyspark-shell'`
with no luck.

I appreciate any help in addressing the problem in the notebook.

Best regards

**Comment by parente** [comment]
```
import os
os.environ['PYSPARK_SUBMIT_ARGS'] = '--packages org.apache.bahir:spark-streaming-mqtt_2.11:2.0.2 pyspark-shell'
from mqtt import MQTTUtils
```

I think you need to initialize a spark context after setting the environment variable and before trying the import.

**Comment by fbeneventi** [comment]
I followed your suggestion and it works but only with the `--packages` flag. 

The jars are downloaded from the maven repository and put in the classpath.

However, if I set the same jar file downloaded locally, using the --jars flag as follow:

`os.environ['PYSPARK_SUBMIT_ARGS'] = '--jars /home/jovyan/.ivy2/jars/org.apache.bahir_spark-streaming-mqtt_2.11-2.0.2.jar pyspark-shell'`

I still doesn't work.
Of course, I tried putting all dependency jars in the above statement with no success.

The `--jars` option is important because I'm going to use a modified local version of the jar package.

**Comment by fbeneventi** [comment]
After further searches, the problem seems due to the particular jar I'm using, due to this [https://issues.apache.org/jira/browse/BAHIR-35?jql=project%20%3D%20BAHIR%20AND%20text%20~%20%22mqtt%22%20ORDER%20BY%20cf%5B10010%5D%20ASC](url).

I solved specifying both `--jars` and `--py-files` flags pointing to the same jar file:

`os.environ['PYSPARK_SUBMIT_ARGS'] = '--jars /home/jovyan/work/spark-streaming-mqtt-test-2.0.2.jar --py-files  /home/jovyan/work/spark-streaming-mqtt-test-2.0.2.jar pyspark-shell'`

thank you very much.
