### ISSUE TITLE
extending jupyter/all-spark-notebooks 

### ISSUE THREAD

**Issue by ConnieZ** [jupyter/docker-stacks#348]
Hi! Thanks for the great Docker images you created! I don't have an issue per se, more of a question.

I was wondering what the best ethical way would be to build on top of one of the images  you have shared? I am interested in adding a few more R packages (specifically dplyr, which is available in others, but not this one, and also C50 for decision tree analysis) into jupyter/all-spark-notebooks Docker image. This would simplify sharing this image in an offline/slow-internet environment at a conference.

I see that you have Modified BSD license. Would the best way be to fork this jupyter/docker-stacks repo here and add the missing R packages to Dockerfile, without changing the other code, including maintainers and license clause?

Please let me know. Thank you!

**Comment by parente** [comment]
Hi @ConnieZ. Submitting a pull request to add those R packages to the all-spark-notebook definition here seems perfectly reasonable to me. All of the Python package from scipy-notebook are inherited into the image already, so why not a few more useful R packages?

If you do want to maintain your own image for whatever reason, you can feel free to fork this repository and do whatever you'd like under the BSD license, including adding whatever you need to the Dockerfiles.

**Comment by parente** [comment]
@ConnieZ I wanted to check back in and see if you've created your images or if you were considering submitting a pull request with the additional packages here.

**Comment by parente** [comment]
This issue appears to be idle so I'm going to close it. Please reach out @ConnieZ if you need further help.
