### ISSUE TITLE
Unable to pull jupyter/pyspark-notebook

### ISSUE THREAD

**Issue by drorata** [jupyter/docker-stacks#357]
**What docker image you are using?**

`jupyter/pyspark-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

`docker pull jupyter/pyspark-notebook`

**What steps do you take once the container is running to reproduce the issue?**

N/A

**What do you expect to happen?**

Complete the pulling successfully.

**What actually happens?**

Pulling stops with the following error message: `unauthorized: authentication required`

**Comment by drorata** [comment]
This is interesting; I just tried it again from a different network and it worked smoothly.

**Comment by jakirkham** [comment]
Maybe a VPN issue?

**Comment by drorata** [comment]
No... I guess it was some ISP issue.

**Comment by archenroot** [comment]
Same issue here, while having timezone of country in EU region, but being in middle-east region at moment. After establishing VPN tunnel to EU region it works....
