### ISSUE TITLE
Connection refused on OSX 10.10.5 with both Chrome and Firefox

### ISSUE THREAD

**Issue by tarelli** [jupyter/docker-stacks#361]
**What docker image you are using?**

`jupyter/base-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

`docker run -it --rm -p 8888:8888 jupyter/base-notebook:latest`

I get:

```
docker run -it --rm -p 8888:8888 jupyter/base-notebook:latest                               (master✱)
[I 23:29:12.709 NotebookApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
[W 23:29:12.764 NotebookApp] Widgets are unavailable. Please install widgetsnbextension or ipywidgets 4.0
[W 23:29:12.770 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[I 23:29:12.811 NotebookApp] JupyterLab alpha preview extension loaded from /opt/conda/lib/python3.5/site-packages/jupyterlab
[I 23:29:12.814 NotebookApp] Serving notebooks from local directory: /home/jovyan/work
[I 23:29:12.815 NotebookApp] 0 active kernels
[I 23:29:12.815 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:8888/?token=c4bd12a486b5f1b2b971471e822d40ed2f4fe6e2a0ec8bf5
[I 23:29:12.815 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 23:29:12.815 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=c4bd12a486b5f1b2b971471e822d40ed2f4fe6e2a0ec8bf5
```

**What steps do you take once the container is running to reproduce the issue?**

1. Visit http://localhost:8888/?token=xxxxx

**What do you expect to happen?**

Jupyter notebook appears on my browser

**What actually happens?**

Connection refused
<img width="919" alt="screen shot 2017-03-28 at 01 35 12" src="https://cloud.githubusercontent.com/assets/81127/24382483/ce2fc3b4-1356-11e7-87ae-5940cb727756.png">

**Comment by parente** [comment]
Are you using Docker for Mac or the older Docker Toolbox for Mac? If the latter, you need to visit the IP address of the boot2docker vm that the toolbox installs.

**Comment by tarelli** [comment]
I am using docker-machine grabbed that IP address and now I can connect. maybe should be added to the documentation. Thanks!

**Comment by parente** [comment]
Cool. Happy to take a PR that adds it to the tips and tricks section of the README if you'd like to submit one.

**Comment by vegabondx** [comment]
I have the same problem but I am NOT using docker machine I guess. Any help here?
Things I have tried already
1. Using 0.0.0.0 (ip=0.0.0.0 in starting notebook ) 
 2. Accessing via localhost , 0.0.0.0 . 192.168.99.103 
3. Changing the port mapping -p 8889:8888 etc
