### ISSUE TITLE
openjdk-8

### ISSUE THREAD

**Issue by Bidek56** [jupyter/docker-stacks#363]
Please upgrade openjdk to version 1.8. Thanks

**Comment by parente** [comment]
1.8 is already in the latest images:

https://github.com/jupyter/docker-stacks/blob/master/pyspark-notebook/Dockerfile#L16

**Comment by Bidek56** [comment]
I think it's still using 1.7 because I get warnings: 
WARN SparkContext: Support for Java 7 is deprecated as of Spark 2.0.0

**Comment by Bidek56** [comment]
These are the lines of code that worked for me. Except for the remove part, which is not working.
# Upgrade Java to 1.8
RUN echo 'deb http://ftp.de.debian.org/debian jessie-backports main' >> /etc/apt/sources.list
RUN apt-get -y update && apt-get -y install openjdk-8-jdk openjdk-8-jre-headless && apt-get clean && rm -rf /var/lib/apt/lists/* \
    && /usr/sbin/update-java-alternatives -s java-1.8.0-openjdk-amd64
# RUN apt-get -y remove openjdk-7-jdk openjdk-7-jre && apt-get clean && rm -rf /var/lib/apt/lists/*

**Comment by parente** [comment]
Here's what I see when I pull that latest all-spark-notebook image and check the java version:

```
docker pull jupyter/all-spark-notebook:latest
docker run -it --rm -p 8888:8888  jupyter/all-spark-notebook bash
jovyan@5233c4d45aa4:~/work$ which java
/usr/bin/java
jovyan@5233c4d45aa4:~/work$ java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-1~bpo8+1-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
jovyan@5233c4d45aa4:~/work$
```

When I launch a notebook server and Apache Toree kernel, I don't see any warnings in the log about java 1.7. Can you confirm you have the latest image by running `docker images | grep all-spark-notebook` and pasting the output here?

**Comment by Bidek56** [comment]
You are correct, it was my mistake, one of my actions installed default-jdk, which turns out to be 1.7. Sorry for the trouble!!
