### ISSUE TITLE
unauthorized error when pulling docker datascience-notebook image

### ISSUE THREAD

**Issue by tugberkayar** [jupyter/docker-stacks#364]
**What docker image you are using?**
jupyter/datascience-notebook
**What complete docker command do you run to launch the container (omitting sensitive values)?**
docker run -d -p 8888:8888 jupyter/datascience-notebook start-notebook.sh --NotebookApp.token=''
**What steps do you take once the container is running to reproduce the issue?**
NA
**What do you expect to happen?**
Pull the image
**What actually happens?**
unauthorized: authentication required while pulling the image

**Comment by parente** [comment]
@tugberkayar This is probably the same as #357.

**Comment by tugberkayar** [comment]
My flatmate has successfully pulled the image with using same network but different computer. It doesn't seem like a network issue.

**Comment by parente** [comment]
Try a `docker logout`. It's possible your authentication with Docker Hub has expired, and your token is being sent along with the pull request, even though these images are public and the token is not needed.

**Comment by tugberkayar** [comment]
It worked. Thank you.

**Comment by souravpatnaik** [comment]
**Solution :**

[root@xx ~]# docker pull hello-world
Using default tag: latest
Pulling repository docker.io/library/hello-world
**Error while pulling image: Get https://index.docker.io/v1/repositories/library/hello-world/images: authenticationrequired**


earlier i have set docker proxy in file   /etc/systemd/system/docker.service.d/https-proxy.conf
#[Service]
#Environment="HTTPS_PROXY=http://xxx:8080/"

then i commented this, and sys-reloaded
#sudo systemctl daemon-reload
#sudo systemctl restart docker

then i tried to pull hello-world and i got it.

sometime docker works with proxy also without proxy :(

**Comment by shogun-tester-AT** [comment]
**The recommendations given above do not work in my case:** 
see the following messages:```

docker pull jupyter/datascience-notebook
Using default tag: latest
latest: Pulling from jupyter/datascience-notebook
a48c500ed24e: Already exists
1e1de00ff7e1: Already exists
0330ca45a200: Already exists
471db38bcfbf: Already exists
0b4aba487617: Already exists
d44ea0cd796c: Already exists
5ac827d588be: Already exists
d8d7747a335e: Already exists
08790511e3e9: Already exists
e3c68aea9a5f: Already exists
484c6d5fc38a: Already exists
0448c1360cb9: Already exists
eed3d219811a: Already exists
944dbdf0ba87: Already exists
a881c93edb03: Already exists
bd3b8240d415: Already exists
8991111fa910: Already exists
8dc01f4de9c9: Already exists
aba43354736a: Already exists
74d185ef112b: Pull complete
baa81842b3da: Downloading [=========>                                         ]  93.29MB/498.4MB
dd956fb4b809: Download complete
76625c9b2859: Download complete
db151e4ba560: Download complete
70ec87377474: Download complete
ab4aa9cdd9e4: Download complete
9950015b5218: Download complete
8e0350bbe1a1: Downloading [=======>                                           ]  33.77MB/236MB
ff79c10d66aa: Downloading
unauthorized: authentication required
```
_I suspect it is an issue with my internet connection speed, causing a time-out with downloading 
large images_.

**Comment by chrisshasha** [comment]
On windows you need to make sure that
1) You've shared your drive
2) You've added `COMPOSE_CONVERT_WINDOWS_PATHS` with value of `1` on you system variables
3) Try logging out then in from  your terminal (When doing it on Docker for Windows - sometimes the issue persists).

After I'd made share those were checked and ready, everything seemed to work fine.

**Comment by ThejYapa** [comment]
Check for updates and update docker. Then logout and login again.
If you are working on windows verify with "docker login".
