### ISSUE TITLE
Install lmodern with the scipy notebook

### ISSUE THREAD

**Issue by theoDiefenthal** [jupyter/docker-stacks#368]
Hi,

If I do something like the following in my Python3-Jupyter-Notebook: (all-spark-notebook in my case but probably applicable from scipy notebook on for all notebooks using matplotlib): 

```python 
from matplotlib.backends.backend_pgf import FigureCanvasPgf
matplotlib.backend_bases.register_backend('pdf', FigureCanvasPgf) 

plt.clf()
seaborn.distplot(df_dataset['Normal1-Values'], kde=False)
plt.savefig("normal1-histogram.pdf")
```

I get a LaTeX error and an invalid PDF file is generated. The error I received was something like
```
! Font EU1/lmr/m/n/10=[lmroman10-regular]:mapping=tex-text at 10.0pt not loadab
le: Metric (TFM) file or installed font not found.
```

Googling for a few secods resulted in the solution: The `texlive-xetex` package is not dependent on the package `lmodern`, but matplotlib requires it here. An installation with `apt-get install lmodern` solved my issue.  I would be happy if you could include this in the installation list.

Best regards

**Comment by jakirkham** [comment]
As it sound like you know what the fix is, would you like to do a PR?

**Comment by naveenkumarmarri** [comment]
@parente  can I take up the PR?

**Comment by parente** [comment]
@naveenkumarmarri Absolutely. I'd recommend adding the lmodern package to the same apt-get command line where the rest of the texlive packages get installed.

**Comment by parente** [comment]
lmodern added in PR #374.
