### ISSUE TITLE
Julia not available via IPython kernel magic - in datascience-notebook

### ISSUE THREAD

**Issue by mjbright** [jupyter/docker-stacks#37]
I tried to run Fernando Perez's "mixed languages" notebook
(https://github.com/fperez/talk-1504-boulder/blob/master/Multiple%20languages%20from%20inside%20IPython.ipynb)

At the first cell trying to load julia (see below), an error message was reported
        %load_ext julia.magic
        %julia @pyimport matplotlib.pyplot as plt
        %julia @pyimport numpy as np
gave the error:
        ImportError: No module named 'julia'

I performed a
        pip install julia

but was still not able to run the cell due to a `GLIBCXX_3.4.20' library error, see below.

```
%load_ext julia.magic
%julia @pyimport matplotlib.pyplot as plt
%julia @pyimport numpy as np
Initializing Julia interpreter. This may take some time...
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-8-2e5a2b66155b> in <module>()
----> 1 get_ipython().magic('load_ext julia.magic')
      2 get_ipython().magic('julia @pyimport matplotlib.pyplot as plt')
      3 get_ipython().magic('julia @pyimport numpy as np')

/opt/conda/lib/python3.4/site-packages/IPython/core/interactiveshell.py in magic(self, arg_s)
   2334         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2335         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2336         return self.run_line_magic(magic_name, magic_arg_s)
   2337 
   2338     #-------------------------------------------------------------------------

/opt/conda/lib/python3.4/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line)
   2255                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2256             with self.builtin_trap:
-> 2257                 result = fn(*args,**kwargs)
   2258             return result
   2259 

/opt/conda/lib/python3.4/site-packages/IPython/core/magics/extension.py in load_ext(self, module_str)

/opt/conda/lib/python3.4/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    191     # but it's overkill for just that one bit of state.
    192     def magic_deco(arg):
--> 193         call = lambda f, *a, **k: f(*a, **k)
    194 
    195         if callable(arg):

/opt/conda/lib/python3.4/site-packages/IPython/core/magics/extension.py in load_ext(self, module_str)
     64         if not module_str:
     65             raise UsageError('Missing module name.')
---> 66         res = self.shell.extension_manager.load_extension(module_str)
     67 
     68         if res == 'already loaded':

/opt/conda/lib/python3.4/site-packages/IPython/core/extensions.py in load_extension(self, module_str)
     89                     __import__(module_str)
     90             mod = sys.modules[module_str]
---> 91             if self._call_load_ipython_extension(mod):
     92                 self.loaded.add(module_str)
     93             else:

/opt/conda/lib/python3.4/site-packages/IPython/core/extensions.py in _call_load_ipython_extension(self, mod)
    136     def _call_load_ipython_extension(self, mod):
    137         if hasattr(mod, 'load_ipython_extension'):
--> 138             mod.load_ipython_extension(self.shell)
    139             return True
    140 

/opt/conda/lib/python3.4/site-packages/julia/magic.py in load_ipython_extension(ip)
     80 def load_ipython_extension(ip):
     81     """Load the extension in IPython."""
---> 82     ip.register_magics(JuliaMagics)

/opt/conda/lib/python3.4/site-packages/IPython/core/magic.py in register(self, *magic_objects)
    389             if type(m) in (type, MetaHasTraits):
    390                 # If we're given an uninstantiated class
--> 391                 m = m(shell=self.shell)
    392 
    393             # Now that we have an instance, we can register it and update the

/opt/conda/lib/python3.4/site-packages/julia/magic.py in __init__(self, shell)
     47         # Flush, otherwise the Julia startup will keep stdout buffered
     48         sys.stdout.flush()
---> 49         self.julia = Julia(init_julia=True)
     50         print()
     51 

/opt/conda/lib/python3.4/site-packages/julia/core.py in __init__(self, init_julia, jl_init_path)
    252                     raise JuliaError("Julia sysimage (\"sys.ji\") not found! {}".format(sysimg_relpath))
    253 
--> 254             self.api = ctypes.PyDLL(libjulia_path, ctypes.RTLD_GLOBAL)
    255             self.api.jl_init_with_image.arg_types = [char_p, char_p]
    256             self.api.jl_init_with_image(JULIA_HOME.encode("utf-8"),

/opt/conda/lib/python3.4/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    349 
    350         if handle is None:
--> 351             self._handle = _dlopen(self._name, mode)
    352         else:
    353             self._handle = handle

OSError: /opt/conda/lib/python3.4/site-packages/zmq/backend/cython/../../../../.././libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so)
```

**Comment by Carreau** [comment]
I'm not sure, but IIRC [pyjulia](https://github.com/JuliaLang/pyjulia) is not Python 3 compatible, it might be the reason why.

**Comment by mjbright** [comment]
Thanks a lot for your replies Matthias.

I did try this morning selecting a Python2 kernel without success.
I also tried with Python2/3 with the "old" jupyter/demo docker image without success.

I'm busy now with work and also preparing to present Jupyter at my local user group tomorrow, but when I have more time I'll try to provide more specific information again.

Generally speaking I've not had much luck trying Julia in various situations (installing IJulia myself I've fallen on the ZeroMQ problem with both julia 0.3.x and 0.4-dev, on Windows and Linux) or with the demo images ijulia kernel seems a little flaky.

**Comment by jacksonloper** [comment]
Trouble seems to be the coexistence of two versions of stdlibc++ in one process, `/opt/conda/lib/libstdc++.so.6` (e.g. zmq links against this) vs the `/usr/lib/x86_64-linux-gnu/libstdc++.so.6` (julia links against this).  

There must be some way to make them play nice.  Does somebody smart know how to do that?  e.g. how do we make this code work (it fails due to the same problem)

    int main() 
    {
        void *lib_handle1;
        void *lib_handle2;

        // if you comment out the following block, loading libjulia will give no trouble
        // if you leave it, loading julia fails
        lib_handle1 = dlopen("/opt/conda/lib/libstdc++.so.6", RTLD_NOW);
        if (!lib_handle1) {
            printf("%s\n", dlerror());
            return 1;
        } 
        

        lib_handle2 = dlopen("/usr/lib/x86_64-linux-gnu/julia/libjulia.so", RTLD_NOW);  
        if (!lib_handle2) {
            printf("%s\n", dlerror());
            dlclose(lib_handle1);
            return 1;
        } 

        dlclose(lib_handle1);
        dlclose(lib_handle2);
        return 0;
    }

**Comment by parente** [comment]
We're starting to experiment with a general Q&A section on https://discourse.jupyter.org/c/questions to see if cross-technology questions like this one catch more attention from a broader community audience. You might try re-posting your question over there to see if someone with more experience in using Julia + IPython together.

I'm going to close this issue since it has been idle for a significant amount of time now. If you do post the question again on the Discourse site, feel free to leave a link in a comment here for those that happen upon this closed issue.
