### ISSUE TITLE
Unrecognized flag - no root access

### ISSUE THREAD

**Issue by hANSIc99** [jupyter/docker-stacks#371]
I'm using:

jupyter/minimal-notebook

and when I run it with:
sudo docker run -e GRANT_SUDO=yes -p 8888:8888 --name minimal1 jupyter/minimal-notebook start-notebook.sh --NotebookApp.token='' --user root

The result is: 
[C 15:34:56.859 NotebookApp] Unrecognized flag: '--user'

Additionally, the output says if I can set '--alow-root'

But I'm still the user jovyan, if I want to sudo, I'm still asked for a password.

**Comment by parente** [comment]
--user is a docker flag and must come before the docker image name, jupyter/minimal-notebook.
