### ISSUE TITLE
Keras stack 

### ISSUE THREAD

**Issue by hakandilek** [jupyter/docker-stacks#389]
Hi There,

I would like to bring up a discussion about a keras stack image based on the existing tensorflow stack.

**Comment by Stibbons** [comment]
+1. Keras should be installed inside the tensorflow image

**Comment by parente** [comment]
Happy to take a PR here. https://github.com/conda-forge/keras-feedstock exists so this should be a an addition to conda install in that Dockerfile.

**Comment by parente** [comment]
`786611348de1` on docker hub/cloud.
