### ISSUE TITLE
feature request: auto-tag or more frequent manual tagging of builds

### ISSUE THREAD

**Issue by kbroughton** [jupyter/docker-stacks#39]
There's a lot of activity on docker-stacks and our team is having a tough time building off minimal-notebook as a base image.  We could fork and build our own, but I'd rather just be able to bump the tag pointing into jupyter/minimal-notebook.

The trouble is, there are only two pinnable tags right now - 3.2 and 4.0
Right now, our container only works based off more recent containers.  
But we don't want to build off latest as it's to unstable.
This would be resolved if you had auotomated tagging (a third digit autoincrementing) or at least more frequent tagging.

thanks!

**Comment by parente** [comment]
Issues #12 and #15 are open to address this concern. There's no silver bullet solution yet since Docker Hub automated builds only allow us to build off of tags/branches, and even then they're not immutable builds.

**Comment by parente** [comment]
> The trouble is, there are only two pinnable tags right now - 3.2 and 4.0

One thing to note: all master changes are backported to the 4.0.x branch (4.0 docker image). And because of issue #15, both are rebuilt (for better or worse) any time any branch changes.

**Comment by parente** [comment]
Being addressed now in issue #12.
