### ISSUE TITLE
Can't install magellan on pyspark-notebook

### ISSUE THREAD

**Issue by PapaBravo** [jupyter/docker-stacks#390]
I'm running `jupyter/pyspark-notebook` on my Windows 7 machine via docker toolbox.

My start command is 
```
docker run -it --rm --name ds -v /c/Users/<some-folder>:/home/jovyan/work/share -p 8888:8888 jupyter/pyspark-notebook start-notebook.sh
```
I'm tying to run the spark package magellan. In the notebook I'm running

```
import os
os.environ['PYSPARK_SUBMIT_ARGS'] = '--packages harsha2010:magellan:1.0.4-s_2.11  pyspark-shell'
import pyspark
sc = pyspark.SparkContext('local[*]')
from magellan.types import Point, Polygon
```

But the module `magellan` can't be found.

What am I missing?

**Comment by parente** [comment]
Adding it to packages makes it available on the cluster to Spark executors. If you want to make the package available in your notebook as well, I *think* you'll need to use `sc.addPyFile` and point it to the URI of the package online or copied into the container.

**Comment by parente** [comment]
This issue has been inactive for nearly a month. @PapaBravo if you managed to install magellan successfully, please add it to the [recipes page on the wiki](https://github.com/jupyter/docker-stacks/wiki/Docker-recipes).
