### ISSUE TITLE
Using  "GRANT_SUDO=yes" doesn't work

### ISSUE THREAD

**Issue by arjones** [jupyter/docker-stacks#394]
When trying to use `-e GRANT_SUDO=yes` parameter during startup it won't work.
This is because the last line of `/etc/sudoers` is commented, preventing the new file `/etc/sudoers.d/notebook` to be included in the configuration.

Uncommenting this last line would be enough to solve this issue.

```
# cat /etc/sudoers

...
...
# Allow members of group sudo to execute any command
%sudo	ALL=(ALL:ALL) ALL

# See sudoers(5) for more information on "#include" directives:

#includedir /etc/sudoers.d
^^^^^^^^^^^^^^^^^^^^^^^^^^--- issue here
```

**Comment by mnagaku** [comment]
It seems that it is not reflected in the latest docker hub images.

ex)
https://hub.docker.com/r/jupyter/minimal-notebook/tags/
latest is df7a34bebed0

/etc/sudoers is 
```
includedir /etc/sudoers.d
```

**Comment by jujug42** [comment]
#includedir is a directive not a comment !!
Removing the # sign break the  sudoers inclusion

see this QA https://stackoverflow.com/a/21640893/210553
and the [sudoers man page](https://www.sudo.ws/man/sudoers.man.html#Including_other_files_from_within_sudoers)

Pullrequest #403 should be reverted

**Comment by parente** [comment]
PR #403 is the revert and re-adds the #
