### ISSUE TITLE
How to include external library to spark notebook

### ISSUE THREAD

**Issue by edi90** [jupyter/docker-stacks#399]
How to include external library to spark notebook,
such as if I want to include this https://github.com/databricks/spark-tfocs to be able to used by my notebook web service.

**Comment by parente** [comment]
I'm not sure since the project doesn't seem to provide any install steps. If it's available on spark-packages.org, then https://github.com/jupyter/docker-stacks/wiki/Docker-recipes#using-spark-packagesorg should work.

**Comment by parente** [comment]
@edi90 this issue has been inactive for a while. I'm going to close it. If you found a way to use spark-tfocs and would like to share it with the community, feel free to post it here or on the https://github.com/jupyter/docker-stacks/wiki/Docker-recipes page.
