### ISSUE TITLE
Cannot mount local folder under /home/jovyan/work

### ISSUE THREAD

**Issue by andmib** [jupyter/docker-stacks#409]
**What docker image you are using?**

`jupyter/pyspark-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

`docker run -it -v /home/me:/home/jovyan/work -p 8888:8888 jupyter/pyspark-notebook`

**What steps do you take once the container is running to reproduce the issue?**

Visit http://localhost:8888 on my local host using the URL + token provided by the container interactive console.

**What do you expect to happen?**

See all of the files in my /home/me directory as I do with other docker containers.

**What actually happens?**

The directory is entirely blank. There is no 'work' folder, or any other folder.

**What OS am I running?**
I'm running CentOS 7.

**What have I tried?**
I tried setting the UID and GID to the same ID as the user I'm running the docker command from. But then the container gets hung up on the "Set ownership to uid 1002: /opt/conda" step.

I've also edited the Dockerfile to include pip install of several packages. But regardless of whether I run the built-container using my modified Dockerfile, or I use the above command to get the container from Docker Hub, I cannot get my local volume mounted under /home/jovyan/work. 

Any suggestions?

**Comment by josephinemho** [comment]
```docker run -it -v `pwd`:/home/jovyan/work -p 8888:8888 jupyter/pyspark-notebook```
