### ISSUE TITLE
Problem with jupyter and localhost

### ISSUE THREAD

**Issue by LukeMathWalker** [jupyter/docker-stacks#412]
Hi!

I'd like to use the basic pyspark jupyter notebook.
I launch the docker script:
`docker run -it --rm -p 8888:8888 jupyter/pyspark-notebook`

And the server starts correctly. But I can't access `localhost:8888/tree` from my host pc :/
Am I missing something stupid but crucial?

**Comment by parente** [comment]
What operating system are you using?

**Comment by LukeMathWalker** [comment]
Windows 7!

Il 08/07/2017 17:58, Peter Parente ha scritto:

What operating system are you using?

**Comment by parente** [comment]
If you're on windows 7, then you're using the older Docker Toolbox which runs a virtual machine with its own IP address. The container will be exposed on that IP, not local host. The docker-machine command should be able to tell you the IP of that VM.

**Comment by parente** [comment]
@LukeMathWalker this ticket has been idle for some time so I'm going to close it. Reach out again if the last suggest did not help.
