### ISSUE TITLE
consider allowing to change the username

### ISSUE THREAD

**Issue by akhmerov** [jupyter/docker-stacks#414]
I'm bringing this up more as a discussion point rather than feature request (it is easy to work around this limitation): right now the username is fixed in the images as `NB_USER=jovyan`. In some circumstances it'd be nicer to allow changing the username on startup: sometimes a different generic name is more suitable (e.g. `student`), or one could even pass the username from the authenticator.

I believe changing this would amount to:
* Checking in `start.sh` whether `$NB_USER=jovyan`.
* If not, renaming `jovyan` into `$NB_USER`, changing the location of the home folder, and only after that updating permissions.

**Comment by minrk** [comment]
I think it definitely makes sense to rename the user. Moving the home directory is perhaps more costly in terms of aufs than desirable, so perhaps making the homedir stable relative to username is best.

**Comment by minrk** [comment]
oh, yeah. Easy enough.

**Comment by akhmerov** [comment]
BTW, this may remove the need for `SystemUserSpawner` as a separate entity, if I understand correctly.

**Comment by parente** [comment]
Could we use `usermod -d /home/newHomeDir -m newUsername`?

**Comment by akhmerov** [comment]
@parente that's pretty much what I was thinking about. However I'm not informed about Linux user management enough to be sure that nothing is missing.
