### ISSUE TITLE
Consider adding Facets

### ISSUE THREAD

**Issue by iyanmv** [jupyter/docker-stacks#416]
Google has released Facets, a new **open source visualization tool** that can be very useful for data scientist:
https://research.googleblog.com/2017/07/facets-open-source-visualization-tool.html

Maybe it is a good idea to add it to datascience-notebook (or perhaps scipy-notebook?). What do you think?

Code and instructions can be found here:
https://github.com/PAIR-code/facets

**Comment by parente** [comment]
Happy to take a PR installing facets using conda or pip from anyone who would like to contribute it!

**Comment by naveenkumarmarri** [comment]
@parente can I take it up?

**Comment by parente** [comment]
Sure thing. Thanks.

**Comment by naveenkumarmarri** [comment]
@parente  should I install as jupyter extension?

**Comment by naveenkumarmarri** [comment]
@parente  should we install bazel as well which helps in modifying some functionality in the visualizations
or just adding jupyter extension is good enough?

**Comment by naveenkumarmarri** [comment]
@parente PR #453 added

**Comment by naveenkumarmarri** [comment]
@parente I think now we can close this issue

**Comment by parente** [comment]
Agreed. Thanks.
