### ISSUE TITLE
`--user root -e NB_UID ` breaks notebook.

### ISSUE THREAD

**Issue by csbrown** [jupyter/docker-stacks#418]
**What docker image you are using?**

`jupyter/datascience-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

`sudo docker run --user root -e NB_UID=1001 -v [my_folder]:/home/jovyan/work -d -p 8888:8888 jupyter/datascience-notebook start-notebook.sh --NotebookApp.password=[my_hash]

**What steps do you take once the container is running to reproduce the issue?**

1. Visit http://localhost:8888

**What do you expect to happen?**

Notebook opens and asks for password

**What actually happens?**

Chrome complains:
This site can’t be reached

The connection was reset.
Try:
Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_RESET

The problem is with the `--user root -e NB_UID=1001`.  Without that, it works as expected.

The docker container is running, and nmap shows the port 8888 to be open.  `$ id` reveals my UID to be 1001, hence that number.

**Comment by csbrown** [comment]
nm, it just takes a lot longer to get running with those options, for some reason.

**Comment by parente** [comment]
Yes. It does a chown of the /opt/conda directories to the new UID.

**Comment by csbrown** [comment]
Seriously, though, it takes like 10m to get going when I set the NB_UID, vs <1m for not.
