### ISSUE TITLE
Jupyter notebook docker and CRIU don't play well together.

### ISSUE THREAD

**Issue by csbrown** [jupyter/docker-stacks#419]
**What docker image you are using?**
`jupyter/datascience-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

`sudo docker run --user root --name jupyter_notebook -e NB_UID=1001 -v [my_dir]:/home/jovyan/work -d -p 8888:8888 jupyter/datascience-notebook start-notebook.sh --NotebookApp.password=[my_hash]`

**What steps do you take once the container is running to reproduce the issue?**

1) Get The latest CRIU on ubuntu: https://launchpad.net/ubuntu/+source/criu/3.2.1-1ubuntu1/+build/12853212
2) Start a notebook.
3) `sudo docker checkpoint create jupyter_notebook save`
4) `sudo docker start --checkpoint save jupyter_notebook`
5) Try to go back to the same notebook
6) Fail.  "An unknown error occurred while loading this notebook. This version can load notebook formats v4 or earlier. See the server log for details."

`docker logs`:

[I 16:48:07.777 NotebookApp] 302 GET / (172.17.0.1) 0.66ms
[E 16:48:13.370 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/site-packages/notebook/base/handlers.py", line 516, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
        value = future.result()
      File "/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
        yielded = next(result)
      File "/opt/conda/lib/python3.6/site-packages/notebook/services/contents/handlers.py", line 124, in get
        path=path, type=type, format=format, content=content,
      File "/opt/conda/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 384, in get
        model = self._notebook_model(path, content=content)
      File "/opt/conda/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 344, in _notebook_model
        self.mark_trusted_cells(nb, path)
      File "/opt/conda/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 456, in mark_trusted_cells
        trusted = self.notary.check_signature(nb)
      File "/opt/conda/lib/python3.6/site-packages/nbformat/sign.py", line 437, in check_signature
        return self.store.check_signature(signature, self.algorithm)
      File "/opt/conda/lib/python3.6/site-packages/nbformat/sign.py", line 237, in check_signature
        (datetime.utcnow(), algorithm, digest),
    sqlite3.OperationalError: attempt to write a readonly database
[E 16:48:13.374 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|ed18d301|7627b76bc39b445c8faef730a71dc996|1499354119",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36",
      "Referer": "http://localhost:8888/notebooks/work/Untitled.ipynb",
      "Accept-Encoding": "gzip, deflate, sdch, br",
      "Accept-Language": "en-US,en;q=0.8",
      "Cookie": "username-localhost-8889=\"2|1:0|10:1499096956|23:username-localhost-8889|44:M2M4YTA4NjA4YzM5NGJkZWJkYjc2OTZlNjQ1YjkyOGY=|4aedc5d1983b1c4a43aa06c80674cb6b788ca5f141bddbe20d6db7199a2cb7cd\"; _xsrf=2|ed18d301|7627b76bc39b445c8faef730a71dc996|1499354119; username-localhost-8888=\"2|1:0|10:1500482680|23:username-localhost-8888|44:ODM1OTZiNDgzMGZhNGM1ZTg2ZjliODk0YTNhNWE0MDE=|ed07110acab44d92b183a438a834963dd45bac6e515df65c9bd0a1972d25e2bb\""
    }
[E 16:48:13.374 NotebookApp] 500 GET /api/contents/work/Untitled.ipynb?type=notebook&_=1500482893137 (172.17.0.1) 8.88ms referer=http://localhost:8888/notebooks/work/Untitled.ipynb

**What do you expect to happen?**

The notebook to pick up working in a way similar to if I had "hibernated" my computer in a non-docker environment.

**What actually happens?**

Breakage

This may be an error with CRIU.  If you guys think that is the case, I'll file a bug report with them.

Cheers,
-Scott!

**Comment by csbrown** [comment]
It's not the `user root` `-v` or `-e` stuff.  `sudo docker run --name jupyter_notebook -d -p 8888:8888 jupyter/datascience-notebook start-notebook.sh --NotebookApp.password=[hash]` has the same error.

**Comment by parente** [comment]
Thanks for digging into the details, @csbrown. I wonder what the permissions are on the various files in `~/.jupyter` and `~/.local/share/jupyter` before and after the checkpoint. The error indicates the sqlite history database has become read-only.

**Comment by parente** [comment]
This issue has been inactive for some time and I'm going to close it. If someone would like to pick up the reigns on debugging checkpointing problems, we'll definitely review a PR.
