### ISSUE TITLE
Figure out how to deal with JupyterHub 0.8

### ISSUE THREAD

**Issue by yuvipanda** [jupyter/docker-stacks#423]
JupyterHub 0.8 is going to be out soon, and it's backwards incompatible. So images with prior versions in them can't be used with 0.8, and vice versa.

What version should we install in docker-stacks? Should we provide variants? Unsure!

**Comment by parente** [comment]
The mantra here has always been to update to support the latest upon the request (https://github.com/jupyter/docker-stacks#stacks-tags-versioning-and-progress). If a user needs support for a prior version, she can pin to any of the image tags prior to the version bump (https://github.com/jupyter/docker-stacks/wiki/Docker-build-history).

Is there a reason to handle jupyterhub differently?

**Comment by minrk** [comment]
Not in the stacks, really. But JupyterHub (DockerSpawner, really) needs to have a clear way to say at least "this image works with Hub 0.8". It's not really the stacks problem.

**Comment by parente** [comment]
OK to close this?

**Comment by minrk** [comment]
Yeah

**Comment by minrk** [comment]
For anyone who finds this while looking for upgrade info: The fix is to make sure that the same version of jupyterhub is installed in your image as the Hub itself.

In general, this is enough:

```Dockerfile
FROM  jupyter/base-notebook:5ded1de07260
RUN pip install jupyterhub==0.8.0b1
```

(with the appropriate jupyterhub version for your deployment)

**Comment by parente** [comment]
I've added the above to the recipes on the wiki.
