### ISSUE TITLE
Unable to start Jupyter Lab in jupyter/datascience-notebook

### ISSUE THREAD

**Issue by tylere** [jupyter/docker-stacks#426]
**What docker image you are using?**

jupyter/datascience-notebook              latest              2cb666af7f44
jupyter/minimal-notebook                  latest              1acb11ca5e3b

**What complete docker command do you run to launch the container (omitting sensitive values)?**

docker run -it --rm jupyter/datascience-notebook start.sh jupyter lab

**What steps do you take once the container is running to reproduce the issue?**

1. Visit http://localhost:8888/?token=f9da971cb6efdcded6899efxxxxxxxxxxxxxxxxxx

**What do you expect to happen?**

JupyterLab should appear in the browser

**What actually happens?**

Browser returns: "This site can’t be reached.  localhost refused to connect."

$ docker logs happy_snyder
Execute the command
[I 20:01:45.373 LabApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
[W 20:01:45.391 LabApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[I 20:01:45.399 LabApp] JupyterLab alpha preview extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab
JupyterLab v0.24.1
Known labextensions:
[I 20:01:45.401 LabApp] Running the core application with no additional extensions or settings
[I 20:01:45.404 LabApp] Serving notebooks from local directory: /home/jovyan
[I 20:01:45.404 LabApp] 0 active kernels 
[I 20:01:45.404 LabApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:8888/?token=f9da971cb6efdcded6899efxxxxxxxxxxxxxxxxxx
[I 20:01:45.404 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 20:01:45.405 LabApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=f9da971cb6efdcded6899efxxxxxxxxxxxxxxxxxx

**Additional info**

Attempting to launch the Jupyter Notebook with start.sh results in similar behavior.
docker run -it --rm jupyter/minimal-notebook start.sh jupyter notebook

**Comment by minrk** [comment]
With Docker, you need to explicitly expose ports for the host port to be forwarded to the container:

    docker run -it -p 8888:8888 --rm jupyter/minimal-notebook

**Comment by tylere** [comment]
Thanks. That information might be useful to add to the docker stacks instructions, which explicitly mention starting jupyter lab:
https://github.com/jupyter/docker-stacks/blob/master/minimal-notebook/README.md#startsh

**Comment by parente** [comment]
The port info does appear in the basic use section: https://github.com/jupyter/docker-stacks/blob/master/minimal-notebook/README.md#basic-use It's excluded from the ipython example because it is a console app and does not use a port. That said, I do see lab mentioned underneath that example, so perhaps a second example showing lab would be handy, maybe even up in the basic use section.

**Comment by parente** [comment]
Every README now has an explicit snippet showing how to run lab with the proper port exposed. Thanks for the feedback.

**Comment by Jyotirm0y** [comment]
You may need to disable the hypervisor.

So, follow the next steps:

1) Open command prompt as Administrator

2) Run bcdedit to check hypervisor status:
bcdedit
3) Check hypervisor launch type:
4) If is set to auto then disable it:
bcdedit /set hypervisorlaunchtype off
5) Reboot host machine and launch VirtualBox again
