### ISSUE TITLE
Add live slideshow plugin inside the minimal notebook image

### ISSUE THREAD

**Issue by pdonorio** [jupyter/docker-stacks#43]
There is a great repo called [RISE](https://github.com/damianavila/RISE) which allow via extension to create live slideshows of your notebooks, with no conversion, adding javascript Reveal.js.

I like it a lot, and find my self often adding this feature on top of your official images.
Since the plugin is great, works with python2 and python3, is light and usefull, you might consider to add it inside the base Dockerfile.

As a quick example of how you could do it, taken from my [personal repo](https://github.com/pdonorio/dockerizing/blob/master/python/py3plus/Dockerfile):
```
# Add Live slideshows with RISE
RUN wget https://github.com/pdonorio/RISE/archive/master.tar.gz \
    && tar xvzf *.gz && cd master && python3 setup.py install
```

Very simple.

Inside that code the github link is my fork of RISE, where i changed keyboard shortcuts for my convenience.

**edit:** of course you should use the original repo, thanks to Damian Avila.

Paolo

**Comment by mjbright** [comment]
+1

Though I'd expect it to be directly from damian avila's repo.

**Comment by pdonorio** [comment]
> Though I'd expect it to be directly from damian avila's repo.

I edited my post to reflect this better, as i also wanted the original repo to be used.

**Comment by parente** [comment]
I don't believe the extension (or any extension) belongs in minimal-notebook. I believe the minimal image is intended to include the minimal set of dependencies required for the complete feature set of Jupyter Notebook to function and nothing else.

To clarify, I'm not opposed images with extensions, but rather extensions in minimal-notebook in particular. They bloat the image that serves as the basis for other images here and elsewhere.

In the RISE case, the RUN command recipe seems like an easy enough thing for someone to add to their own Dockerfile or to run on container start. And maybe a place for easily finding those kinds "recipes" for installing additional bits without requiring everything to be in the initial images provided by docker-stacks is something we should think about.

/cc @rgbkrk thoughts?

**Comment by ellisonbg** [comment]
Agree with Peter's take on this.

On Thu, Oct 22, 2015 at 1:02 PM, Peter Parente <notifications@github.com>
wrote:

> I don't believe the extension (or any extension) belongs in
> minimal-notebook. I believe the minimal image is intended to include the
> minimal set of dependencies required for the complete feature set of
> Jupyter Notebook to function and nothing else.
>
> To clarify, I'm not opposed images with extensions, but rather extensions
> in minimal-notebook in particular. They bloat the image that serves as the
> basis for other images here and elsewhere.
>
> In the RISE case, the RUN command recipe seems like an easy enough thing
> for someone to add to their own Dockerfile or to run on container start.
> And maybe a place for easily finding those kinds "recipes" for installing
> additional bits without requiring everything to be in the initial images
> provided by docker-stacks is something we should think about.
>
> /cc @rgbkrk <https://github.com/rgbkrk> thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/docker-stacks/issues/43#issuecomment-150291767>
> .
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by rgbkrk** [comment]
I agree with Peter on that as well. If it goes in the demo image, that's fine. It's like the kitchen sink of Docker images.

**Comment by parente** [comment]
I've started a new wiki page in this repo called Docker Recipes and captured @pdonorio's snippet of how to install RISE there.

https://github.com/jupyter/docker-stacks/wiki/Docker-Recipes

Let's see if the page grows. I'll link to it from the README.

**Comment by pdonorio** [comment]
I like the recipes, thanks for doing this. 
Very glad to be a part of it.
