### ISSUE TITLE
start.sh performance issue

### ISSUE THREAD

**Issue by wakonp** [jupyter/docker-stacks#434]
Hi there! I am currently working at my master theses, which is about integrated practicing environments for computer science classes. For the practical part of my thesis the target is to create a scalable, secure and and easy to use Jupyterhub setup for my university. I am currently working at this [solution](https://github.com/wakonp/jupyterhub-fhjoanneum), which covers the [SwarmSpawner](https://github.com/cassinyio/SwarmSpawner), the [LDAPAuthenticator](https://github.com/jupyterhub/ldapauthenticator), [nbgrader](https://github.com/jupyter/nbgrader) and a persitant [nfs storage](https://github.com/ErezHorev/dockerized_nfs_server). I can report that all works fine and I hope that I get the documentation ready in the next few days.

Coming to my question:
I am using the `NB_UID` and `NB_GID` change steps, when executing the `start.sh` as root. This is  awesome, because in my setup every students also gets a NFS User, where the UID and GID must match. I can report that, the following part of the script creates perform issues when spawning the notebook server:

```
# Careful: $HOME might resolve to /root depending on how the
# container is started. Use the $NB_USER home path explicitly.
for d in "$CONDA_DIR" "$JULIA_PKGDIR" "/home/$NB_USER"; do
    if [[ ! -z "$d" && -d "$d" ]]; then
        echo "Set ownership to uid $NB_UID: $d"
        chown -R $NB_UID "$d"
    fi
done
```
The main problem is, that the `$CONDA_DIR aka /opt/conda` gets most likely bigger with each kernel you install and the recursive `chown` while starting the server is not the best approach I think. In my setup I used the `scipy-notebook` as my base image and added the `IHaskell`kernel from [here](https://github.com/gibiansky/IHaskell) and the `Javascript` kernel from [here](https://github.com/notablemind/jupyter-nodejs). Dockerimage Size 9.57GB [Dockerfile](https://github.com/wakonp/jupyterhub-fhjoanneum/blob/master/fhj-notebooks/teacher-notebook/Dockerfile.teachernotebook) - [DockerHub](https://hub.docker.com/r/walki12/teachernotebook/).

I had do modify the `start.sh` script and remove the `chown` loop to make it work. To overcome a permission issue at server start, I installed all additional kernels with `UMASK 0002` to assure that the `NB_Group`(users) gets full-access to all the installed kernel files. 

I think that the `start.sh` should be modified and maybe it would be nice if it is possible to change the username too. My solution can to it:

```
#!/bin/bash
# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

set -e

# Handle special flags if we're root
if [ $(id -u) == 0 ] ; then
    # Change UID of NB_USER to NB_UID if it does not match
    if [ "$NB_UID" != $(id -u $NB_USER) ] ; then
        echo "Set user UID to: $NB_UID"
        usermod -u $NB_UID -l $JPY_USER $NB_USER
        NB_USER=$JPY_USER
        # Careful: $HOME might resolve to /root depending on how the
        # container is started. Use the $NB_USER home path explicitly.
        #for d in "$CONDA_DIR" "$JULIA_PKGDIR" "/home/$NB_USER"; do
        #    if [[ ! -z "$d" && -d "$d" ]]; then
        #        echo "Set ownership to uid $NB_UID: $d"
        #        chown -R $NB_UID "$d"
        #    fi
        #done
    fi

    # Change GID of NB_USER to NB_GID if NB_GID is passed as a parameter
    if [ "$NB_GID" ] ; then
        echo "Change GID to $NB_GID"
        groupmod -g $NB_GID -o $(id -g -n $NB_USER)
    fi

    # Enable sudo if requested
    if [ ! -z "$GRANT_SUDO" ]; then
        echo "$NB_USER ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/notebook
    fi

    # Exec the command as NB_USER
    echo "Execute the command as $NB_USER"
    exec su $NB_USER -c "env PATH=$PATH $*"
else
    # Exec the command
    echo "Execute the command"
    exec $*
fi
```
see [here](https://github.com/wakonp/jupyterhub-fhjoanneum/blob/master/fhj-notebooks/teacher-notebook/start.sh). The `$JPY_USER` will get added by the SwarmSpawner when executing the `start-singleuser.sh` script.

I am not quite sure if this could help you.

**Comment by minrk** [comment]
If skipping that step is okay, then you probably want to launch the containers with specified user IDs directly, instead of launching as root and letting the container execute the code as root to become the user.

**Comment by wakonp** [comment]
The problem is, that the specific user ID is only available after the user logged in and not at docker build time. 

When a user logs in at the Hub the Authenticator checks if he is authorized for the service. If this is the case the authenticate function is called in any Jupyterhub Authenticator. So if everything works fine, this function returns the username to the Hub, which is instantiating the Spawner and providing it with the username.

I did following:
Before the username is returned by the Authenticator I create a new user in a NFS-Container (example - userA:1004:1000)

Furthermore, before the notebook server is started with start-singleuser.sh I call:

`NB_UID=docker exec jupyterhub_nfs id -u username`
`NB_GID=docker exec jupyterhub_nfs id -g username`

This adds `NB_UID` and `NB_GID` to the ENV of the 'not yet spawned' notebook. Now the notebook only needs to get started with the root user.

The `start.sh` script checks if the Notebook-Server is spawned as root and takes the ENV variables `UID` and `GID` and alters the $NB_USER (jovyan:1000:100 to userA:1004:1000). 

At the end root starts the notebook as $NB_USER which has the new NB_UID and NB_GID and can write in his/her NFS share.

I described this [here](https://github.com/cassinyio/SwarmSpawner/pull/15).

If the username (jovyan) can be altered within the start.sh script `nbgrader` could also be used and use the correct username for assignments. But that's a different story.

**Comment by minrk** [comment]
If you retrieve that NFS info in `Spawner.start`, you can specify the user id and group id in `extra_create_kwargs`. Then you don't need to start the container as root.

**Comment by wakonp** [comment]
>Then you don't need to start the container as root.

Well the container aka service will always run as $NB_USER because of the `start.sh` script, so I don't get your point there. 

I don't get it why I need to change the `extra_create_kwargs`, when I already can change the UID of jovyan with the environment variables.

> -e NB_UID=1000 - Specify the uid ... For this option to take effect, you must run the container with --user root. (The start-notebook.sh script will su jovyan after adjusting the user id.)
https://github.com/jupyter/docker-stacks/tree/master/base-notebook

I am not using the DockerSpawner because it can only spawn containers, not services. My setup uses Docker Swarm. Therefore, I used [SwarmSpawner](https://github.com/cassinyio/SwarmSpawner) as a Jupyterhub Spawner Class.

I just want to point out, that if `$NB_UID` or/and `$NB_GID` is defined in the environment of the notebook and `start.sh` is called as `root` (to change the UID/GID of jovyan), the script tries to run `chown` on `/opt/conda aka $CONDA_DIR`, which works fine if there are no other kernels installed (tested with `scipy-notebook` - works fine), but will take ages if more kernel installation files are stored there (`scipy-notebook`  + IHaskell and JavaScript - takes up to 5-10mins to start the notebook server).
