### ISSUE TITLE
Doesn't work for Amazon EC2 container services

### ISSUE THREAD

**Issue by ruloweb** [jupyter/docker-stacks#436]
Hi all,

I'm trying to make the image jupyter/scipy-notebook works in a Amazon EC2 container but I can't success.

Looks like everything goes ok, but the notebook never get started, when I run docker logs <containerid> it returns:
```bash
/usr/local/bin/start.sh: line 48: [: missing `]'
/usr/local/bin/start.sh: line 48: : command not found
Execute the command
```

I have the same error message in my local, but after Execute the command I can see the jupyter starting, which doesn't happen in the EC2 Container Service.

Have anyone tried that?

**Comment by nikitakrutoy** [comment]
I got this  while running datascience-notebook container with -e GRANT_SUDO=1 (running with "yes" leads to infinity printing of "==")
```
/usr/local/bin/start.sh: line 33: [: missing `]'
/usr/local/bin/start.sh: line 33: 1: command not found
```
33 and 48 lines looks the same:
```
if [ "$GRANT_SUDO" == "1" || "$GRANT_SUDO" == 'yes' ]; then
```
I guess to run correctly it should be something like this instead :

```
if [[ "$GRANT_SUDO"=="1" || "$GRANT_SUDO"=="yes" ]]; then
```

**Comment by ruloweb** [comment]
Yeah, there is a bug that triggers that error message, the same happens in
my local and Jupiter starts ok, but it doesn't in a C2 Container Service.

**Comment by parente** [comment]
This should be fixed by https://github.com/jupyter/docker-stacks/pull/437 which was merged 2 hours ago. The builds should appear on Docker Hub/Cloud soon-ish.

**Comment by ruloweb** [comment]
hey @parente yeah that should fix the error message, but as I said the same error was shown in my local and the container is able to start, which is not in Amazon EC2 Container service. Anyway I will give it a try let you know, thanks.

**Comment by parente** [comment]
@ruloweb I'm going to close this issue as fixed. If you're still seeing the problem on EC2 with the latest image, feel free to reopen it.
