### ISSUE TITLE
shell error about if condition

### ISSUE THREAD

**Issue by jacknlliu** [jupyter/docker-stacks#439]
@minrk 
https://github.com/jupyter/docker-stacks/blob/82b978b3ceeb8ae1520c8cb420f20b7b8aa8471e/base-notebook/start.sh#L48

should it be like
```sh
if [[ "$GRANT_SUDO" == "1" || "$GRANT_SUDO" == 'yes' ]]; then
```
because I got error from the origin
```
/usr/local/bin/start.sh: line 48: [: missing `]'
/usr/local/bin/start.sh: line 48: : command not found
```

**Comment by parente** [comment]
This should be fixed in the latest build, tag 37af02395694 (https://github.com/jupyter/docker-stacks/wiki/Docker-build-history).
