### ISSUE TITLE
unable to install bioconductor packages into R

### ISSUE THREAD

**Issue by ohnoplus** [jupyter/docker-stacks#447]
I am unable to install the phyloseq, or dada2 package (or possibly any package) from bioconductor into R when using the jupyter/r-notebook docker. 

**What docker image you are using?**

Example: `jupyter/r-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

Example: `docker run -it --rm -p 8888:8888 jupyter/r-notebook`

**What steps do you take once the container is running to reproduce the issue?**

Example:

1. Visit http://localhost:8888 and put in relevant token
2. Start an R notebook
3. In the first cell run
     `source('http://bioconductor/org/biocLite.R')`
     `biocLite('phyloseq')`

**What do you expect to happen?**

I expect phyloseq to successfully install into R, as it does in a normal R installation

**What actually happens?**
I get the following output which contains error messages message

> Updating HTML index of packages in '.Library'
> Making 'packages.html' ... done
> Bioconductor version 3.4 (BiocInstaller 1.24.0), ?biocLite for help
> A new version of Bioconductor is available after installing the most recent
>   version of R; see http://bioconductor.org/install
> BioC_mirror: https://bioconductor.org
> Using Bioconductor 3.4 (BiocInstaller 1.24.0), R 3.3.2 (2016-10-31).
> Installing package(s) ‘phyloseq’
> also installing the dependencies ‘zlibbioc’, ‘rhdf5’, ‘S4Vectors’, ‘IRanges’, ‘XVector’, ‘irlba’, ‘pkgconfig’, ‘survival’, ‘permute’, ‘BiocGenerics’, ‘ade4’, ‘ape’, ‘biomformat’, ‘Biostrings’, ‘cluster’, ‘data.table’, ‘igraph’, ‘multtest’, ‘vegan’, ‘Biobase’
> 
> Warning message in install.packages(pkgs = doing, lib = lib, ...):
> “installation of package ‘igraph’ had non-zero exit status”Warning message in install.packages(pkgs = doing, lib = lib, ...):
> “installation of package ‘phyloseq’ had non-zero exit status”Updating HTML index of packages in '.Library'
> Making 'packages.html' ... done
> Old packages: 'assertthat', 'backports', 'BH', 'car', 'curl', 'DBI',
>   'devtools', 'digest', 'dplyr', 'evaluate', 'forecast', 'foreign', 'haven',
>   'httpuv', 'httr', 'jsonlite', 'knitr', 'lattice', 'MASS', 'Matrix', 'mgcv',
>   'modelr', 'pbdZMQ', 'psych', 'purrr', 'R6', 'Rcpp', 'RcppArmadillo',
>   'RcppEigen', 'readr', 'repr', 'rmarkdown', 'RSQLite', 'scales', 'shiny',
>   'SparseM', 'stringi', 'stringr', 'tibble', 'tidyr', 'tidyverse', 'tseries',
>   'withr', 'zoo'

Similar process for package dada2. I presume this is universal across bioconductor packages.

**Comment by ohnoplus** [comment]
Ok. I think I found a work-around for phyloseq, but not dada2. It looks like phyloseq depends on igraph, and the cran version thereof isn't compatible with this version of R. I fond installing igraph from github first got around this issue.

     install.packages("devtools") # we need this to install github packages
     options(unzip = "unzip") # the default is "", we need to to set this option to unzip for installations
     ## Install igraph from github
     devtools::install_github("gaborcsardi/pkgconfig")
     devtools::install_github("igraph/rigraph")
     ## Now I can install phyloseq
     biocLite("phyloseq")

Less luck with the dada2 installation. It appears to depend on package ShortRead, which I can't seem to install from either biocLite, or from github.

biocLite("ShortRead")
returns to the teminal 
"configure: error: zlib not found"

This site https://ubuntuforums.org/showthread.php?t=692704 says, that I require zlib1g-dev. I tried running 
      system("apt-get install zlib1g-dev")
but that returns
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?

I'm kind of new at editing docker containers, mabye there is a proper way to install linux packages within them? I'd appreciate any leads.
Thanks

**Comment by ohnoplus** [comment]
Further progress:
I can install packages and get dada2 to install as well. I just need to work in docker containers where I have sudo privileges. I can create one of those with

###### CODE HERE#####
then, since I am in bash

     sudo apt-get update
     sudo apt-get install zlib1g-dev

then I can launch jupyter notebook
      jupyter notebook

and install ShortRead 

     biocLite("ShortRead")

and then phyloseq

     biocLite("phyloseq")

at that point
     library("phyloseq") packageVersion("phyloseq")

> [1] '1.19.1'

I'm not closing this issue because I think these bioconductor packages ought to install without this much fuss.

**Comment by parente** [comment]
I'm guessing the problems here stem from the use of conda and [R packages from conda-forge](https://github.com/jupyter/docker-stacks/blob/master/r-notebook/Dockerfile#L20) to setup the base images. It's possible that both [phyloseq](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bioconductor-phyloseq/meta.yaml) and [dada2](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bioconductor-dada2/meta.yaml) from [bioconda](http://bioconda.github.io/) will install more easily and be compatible with the underlying libs coming from conda-forge (e.g., zlib). Try `conda install -c bioconda dada2 phyloseq` from a terminal in the container.

If that doesn't work, then I imagine this only gets simpler if and when there are [conda-forge packages for bioconductor available](https://github.com/conda-forge/staged-recipes/pull/3449#issuecomment-326355095).
