### ISSUE TITLE
Why remove python2 tensorflow support?

### ISSUE THREAD

**Issue by dustycodes** [jupyter/docker-stacks#449]
Hey,

Why is the TensorFlow image no longer using python2? If you are removing it forever, you should also update the readme in the Tensorflow directory to state 2.7 tensorflow is no longer included.

Thanks!

**Comment by parente** [comment]
We removed Python 2 from all of the stacks in https://github.com/jupyter/docker-stacks/pull/433. We missed updating the tensorflow README at the time. PR #451 corrects that problem. Thanks for the heads up.

If you need an image with Python 2 support, there's now a section on the recipes page of the wiki with an example Dockerfile showing how to build an image with both 2.7 and 3.x Python in it.
