### ISSUE TITLE
add base_url config as an ENV option

### ISSUE THREAD

**Issue by a86c6f7964** [jupyter/docker-stacks#45]
I think that its common to run these behind a reverse proxy, so it would be great to be able to set the base_url through an environmental config option

**Comment by parente** [comment]
@rgbkrk How are we doing this for tmpnb.org already? I think via command line arg?

**Comment by rgbkrk** [comment]
Yeah.

**Comment by rgbkrk** [comment]
Sorry, phone commenting. We use `--NotebookApp.base_url={base_path}`

**Comment by parente** [comment]
That's right. The `start-notebook.sh` script passes these through as command line args to the notebook server. So a stack container can be run like:

`docker run -d jupyter/minimal-notebook --NotebookApp.base_url=/some/path`

@a86c6f7964 does this work for you?

**Comment by rgbkrk** [comment]
Just today I set up the `CMD` for a pyspark Docker image to (effectively) this:

```
"/bin/bash -c 'IPYTHON_OPTS=\"notebook --NotebookApp.base_url=/{base_path} --ip=0.0.0.0\" pyspark --packages com.databricks:spark-csv_2.10:1.2.0'"
```

ENV are cool, but of course tmpnb would have to render to the configured ENV for what path they're being stuck on.

**Comment by a86c6f7964** [comment]
That worked great. Thanks for the help. What is the reason that some of the variables are part of the ENV, such as ip and port, when they could all be specified with command line arguments?

**Comment by parente** [comment]
Legacy: we didn't know how to support command line initially when the images were using supervisord as the entrypoint.
