### ISSUE TITLE
OpenCV support for working with images etc?

### ISSUE THREAD

**Issue by niyazpk** [jupyter/docker-stacks#464]
It would be great to have a docker image with OpenCV support. I would want this to be based on scipy-notebook or tensorflow-notebook, though I am not sure if that is the right place to branch off.

OpenCV with contribs docker image can be found here: https://github.com/janza/docker-python3-opencv/blob/opencv_contrib/Dockerfile

I'd try and send a PR myself, but I am pretty new to docker - like just installed docker.

**Comment by parente** [comment]
There's a opencv package on conda-forge: https://github.com/conda-forge/opencv-feedstock. You could easily make a new Dockerfile:

```Dockerfile
FROM jupyter/scipy-notebook:<some tag version here>
RUN conda install opencv && conda clean -tipsy && fix-permissions $CONDA_DIR
```

Then run `docker build -t opencv-notebook .` in that directory to get an image. I don't think maintaining a whole other stack here for opencv alone makes sense. Maybe we could put it in the scipy-notebook image, if it doesn't make it substantially larger.

**Comment by niyazpk** [comment]
Wow man, that was very useful!

Did not think it was going to be so easy. I was trying whole today to get OpenCV to build from source in the docker container and it was failing with various library compat issues.

Feel free to close this. Thanks again!

**Comment by parente** [comment]
Bookmark https://conda-forge.org/feedstocks. There's a treasure trove of packages there, well beyond Python now too (e.g., `conda install git`, `conda install openjdk`). Good luck!

**Comment by niyazpk** [comment]
Bookmarked! Thank you.
