### ISSUE TITLE
Missing timezone data OS package

### ISSUE THREAD

**Issue by szaydel** [jupyter/docker-stacks#466]
**What docker image you are using?**

`jupyter/datascience-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

`docker run -e GRANT_SUDO=yes --user=root -d -p 8123:8888 -v /var/lib/docker/volumes/jupyter/r/$NAME:/home/jovyan/work --name=jupyter-$NAME jupyter/datascience-notebook start-notebook.sh --NotebookApp.token='' $NAME` 
...
where `$NAME == $1` from command line. This is a snippet from a shell script.

**What steps do you take once the container is running to reproduce the issue?**

1. Visit http://localhost:8123
2. Start an R noteobok
3. require(tidyquant)

The problem I am observing is inability to process CSV files due to missing timezone data. It seems like the timezone data package is not by default installed with the base OS image.

I addressed this issue via shell as such: `sudo apt-get update ; sudo apt install tzdata` . In my mind this package should have really been there from the start.

**Comment by anatoliykmetyuk** [comment]
Any news about this one? It is pretty strange that a standard feature of a standard library does not work out of the box.

Am not able to do `sudo apt-get update ; sudo apt install tzdata`, because "passwordless" sudo requires password, which I don't know.

**Comment by anatoliykmetyuk** [comment]
For anyone else struggling.

I have used a custom `Dockerfile` with the following contents:

```
FROM jupyter/r-notebook

USER root
RUN apt-get update
RUN apt install tzdata

USER $NB_USER
```

Then build and run this image as specified in the [official tutorial](https://docs.docker.com/get-started/part2/).

**Comment by jakirkham** [comment]
Care to do a PR @anatoliykmetyuk?
