### ISSUE TITLE
Trying to mount locally but the notebooks always gets deleted

### ISSUE THREAD

**Issue by JeremyLG** [jupyter/docker-stacks#467]
```
sudo docker run -d -p 8888:8888 --user=root -e NB_UID=1000 -e NB_GID=100  -v /home/ec2-user/test/notebook.pem:/etc/ssl/notebook.pem  \
   jupyter/all-spark-notebook start-notebook.sh \
    --NotebookApp.certfile=/etc/ssl/notebook.pem  \
   --NotebookApp.password='sha1:2fb7c700a659:1eba03ab4dc3e3c3a9d58ad477b710e98c47e0a0'
```

Hi I almost understood everything except the part about mounting the noteoboks locally...

I have my jupyter docker on an EC2 instance, which is linked through nginx, so everything works.

My ssl .pem file is the /etc/ssl directory

I created a directory /home/ec2-user/test/ and I chown 1000 it

But even with the -v option, this doesn't save anything locally. What am I missing ?

Thanks a lot and sorry for this dumb issue

**Comment by parente** [comment]
You need to add a `-v /home/ec2-user/test:/home/jovyan/work` to the command to mount the folder you created on the host somewhere in the container where you can save and preserve notebooks.

**Comment by JeremyLG** [comment]
If I had both `-v /home/ec2-user/test:/home/jovyan/work` and just after in the command `-v /home/ec2-user/test/notebook.pem:/etc/ssl/notebook.pem` then Jupyter launches but it doesn't save the notebooks on the local folder.

If I only add `-v /home/ec2-user/test:/home/jovyan/work` then Jupyter doesn't even launch.

Am I doing something wrong ?

Thank for your help anyway !

**Comment by parente** [comment]
> If I had both -v /home/ec2-user/test:/home/jovyan/work and just after in the command -v /home/ec2-user/test/notebook.pem:/etc/ssl/notebook.pem then Jupyter launches but it doesn't save the notebooks on the local folder.

Are you creating the notebooks in the `work` subfolder?

> If I only add -v /home/ec2-user/test:/home/jovyan/work then Jupyter doesn't even launch.

If you only mount that one folder and do not also remove the `--NotebookApp.certfile`, then the notebook server will fail to find the `pem` file. You shouldn't need to remove the other mount though.

**Comment by JeremyLG** [comment]
Hey man, thank a lot, you're right. The issue was pretty simple, I was pretty dumb ! :p 

Thank again for the help !

By the way, I have another question about Nginx, maybe you have an answer, if not then it's fine !

I want to link my Jupyter node to mydomain.com/jupyter and not just the root location. But I can't make this nginx conf works... Do you have any insights about this ? 

```
location /jupyter {
            proxy_pass https://10.33.1.164:8888;

           # proxy_set_header X-Real-IP $remote_addr;
           # proxy_set_header Host $host;
           # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
     location ~* /(api/kernels/[^/]+/(channels|iopub|shell|stdin)|terminals/websocket)/? {
            proxy_pass https://10.33.1.164:8888;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # WebSocket support
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            #proxy_set_header Connection $connection_upgrade;

        }

```

Anyway have a good week end ! 
Regards

**Comment by jakirkham** [comment]
Going to close as the original issue was solved. Feel free to raise additional issues for new topics.

**Comment by stephenconnolly1** [comment]
Thanks for the env variables for the UID and GID. Was driving me mad
