### ISSUE TITLE
add databricks/spark-deep-learning

### ISSUE THREAD

**Issue by kietly** [jupyter/docker-stacks#468]
Hi! Thanks for using Jupyter's docker-stacks images.

If you are requesting a library upgrade or addition in one of the existing images, please state the desired library name and version here and disregard the remaining sections.

If you are reporting an issue with one of the existing images, please answer the questions below to help us troubleshoot the problem. Please be as thorough as possible.

**What docker image you are using?**
jupyter/all-spark-notebook

**What complete docker command do you run to launch the container (omitting sensitive values)?**
docker run -it --rm -p 8888:8888 --name spark -v <my-local-dir>:/home/$NB_USER -e GEN_CERT=yes jupyter/all-spark-notebook

Please add databricks/spark-deep-learning to your jupyter docker-stacks.

**Comment by parente** [comment]
spark-deep-learning is available on sparkpackages.org which means it can be dynamically added  to a notebook at SparkContext creation time. I think there's already a generic recipe for using packages from the site in the docs (http://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html#using-spark-packages-org) but it'd still be nice to have a more specific example for this package right in the docs.

**Comment by parente** [comment]
This issue has been idle for some time but I'd like to leave it open as low-hanging fruit for someone looking to contribute to the project by improving upon the rather terse recipe for using spark packages in the recipes here: https://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html#using-spark-packages-org

**Comment by Bidek56** [comment]
[databricks/spark-deep-learning](https://github.com/databricks/spark-deep-learning) only contains HorovodRunner code for local CI and API docs. 
Databricks Runtime for Machine Learning is necessary to run it. 
@kietly  I don't think this ask is relevant to this stack anymore hence we can close this ticket. Thx
