### ISSUE TITLE
ppc64le dockerhub images

### ISSUE THREAD

**Issue by vaibhavsood** [jupyter/docker-stacks#472]
Hi, I'm looking to enable docker containers for packages like jupyter for multiple architectures on dockerhub, starting off with a focus on ppc64le. Wanted to check on the work that will be involved to do that

I have locally been able to successfully test ppc64le changes to the dockerfiles in this repo - changes for enabling additional arch would be minimum.

Would like to know how a multi-arch image for this can be initiated? The official images have this method for enabling multi-arch : https://github.com/docker-library/official-images#multiple-architectures, however this repo isnt an official image yet. Would the first step be to make this an official image or are there any other ways the dockerhub jupyter image can be enabled for ppc64le?

Hi! Thanks for using Jupyter's docker-stacks images.

If you are requesting a library upgrade or addition in one of the existing images, please state the desired library name and version here and disregard the remaining sections.

If you are reporting an issue with one of the existing images, please answer the questions below to help us troubleshoot the problem. Please be as thorough as possible.

**What docker image you are using?**

Example: `jupyter/scipy-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

Example: `docker run -it --rm -p 8889:8888 jupyter/all-spark-notebook:latest`

**What steps do you take once the container is running to reproduce the issue?**

Example:

1. Visit http://localhost:8889
2. Start an R noteobok
3. ...

**What do you expect to happen?**

Example: ggplot output appears in my notebook.

**What actually happens?**

Example: No output is visible in the notebook and the notebook server log contains messages about ...

**Comment by parente** [comment]
There was a contribution of a ppc64 Dockerfile a while back: https://github.com/jupyter/docker-stacks/tree/master/base-notebook. We haven't kept it up to date or invested in automatically building the images for that platform since then.

**Comment by vaibhavsood** [comment]
Ok thanks! 

Want to check if you would be willing to make the docker images official https://docs.docker.com/docker-hub/official_repos/#how-do-i-create-a-new-official-repository , that would offload the build process to docker. They also build for multi-arches so that could be used to auto build additional arches like ppc64le.

Alternatively, i can help to bring the ppc64le dockerfile upto date (i work with the original contributor of the ppc64le dockerfile @seth-priya ) and can also help with setting up a CI build for autobuilding ppc64le images locally, would that be okay?

My interest here is to publish ppc64le docker images (ideally official images), want to know your thoughts, thanks!

**Comment by parente** [comment]
I'm OK with the official image route, but I personally don't have the time to invest in doing the research and making that move at the moment. If you (or anyone) wants to figure out what it would take to make either base- or or minimal-notebook conform to the official repository requirements and still function as a base for the other stacks here, I'm all for it. Happy to provide some guidance along the way.

If you're not up to tackling that, automating the ppc64 build is also welcome. Note that we've moved all the builds to Docker Cloud since the last time alternative architectures came up. Maybe that helps? Is it possible to setup ppc64 build pipelines on the free tier of Docker Cloud?

**Comment by jakirkham** [comment]
Looks like PR ( https://github.com/docker-library/official-images/pull/3639 ) would add it to the Official Docker Library.

**Comment by parente** [comment]
This issue has been inactive for quite some time and so I'm going to close it. If someone would like to pick up the torch on restoring the ppc64 builds in this repo, I'll be happy to review the PR though I don't have suggestions on where to do the PowerPC builds. If anyone has an interest in leading the charge on making the base-notebook image a Docker official image, please open a new issue and maybe we'll find others willing to help out.
