### ISSUE TITLE
openjdk-9-jre-headless upgrade

### ISSUE THREAD

**Issue by Bidek56** [jupyter/docker-stacks#475]
Please upgrade openjdk-8-jre-headless in pyspark-notebook/Dockerfile to openjdk-9-jre-headless, since Java 1.9 is out. Thanks

**Comment by jhermann** [comment]
NOT a good idea, since 9 is not LTS (and unsurprisingly EOL by now because of that). The next target version should be 11 , and special care has to be taken because 8→11 involves the Jigsaw classpath mechanics change.

**Comment by Bidek56** [comment]
This is an old issue, closing it since it's irrelevant at this time.
