### ISSUE TITLE
can't hide #header-container anymore

### ISSUE THREAD

**Issue by parmentelat** [jupyter/docker-stacks#480]
Hi folks

I had initially reported this as (now closed) issue ipython/ipython#10852

I use image jupyter/scipy-notebook 

I need to hide the first part of the header (with the logo and notebook name) and I have this line in my `custom.css`

```
#header-container {display: none; }
```

this used to work fine with this image:
sha256:d6ebaf357aa9cbc20aa8982b1860a454b90aa599377999212e2889ab5f764aea   853caf4b6a07        12 weeks ago 

 but I have recently moved to a newly installed box and have rebuilt my docker image on top of the latest tag from dockerhub, namely this one:

sha256:853cd6594621d9cfddbf325098352aac8ac6b8f7efebcf7d568298411ef97deb          9 days ago

and with that image the notebooks show up with the header fully displayed; 

obviously something somehow comes after `custom.css` gets loaded and reinstates this.

trying to investigate, I went to the browser's debug mode, it shows that the css file was loaded and the setting has been seen, but ignored (it shows in strike-through under chrome)

**Comment by parente** [comment]
Try adding `!important` to the end of your style rule. This is most likely due to an upgrade from notebook 5.0 to 5.1 across the two tags you mention, and associated stylesheet changes in the notebook project.

**Comment by parmentelat** [comment]
thanks so much, this worked for me 👍
