### ISSUE TITLE
can't run with option GRANT_SUDO on ubuntu

### ISSUE THREAD

**Issue by AlexAbraham1** [jupyter/docker-stacks#483]
hi!

when I try to run the following command I get an error "option -e not valid"

docker run -d -p 8888:8888 jupyter/datascience-notebook start-notebook.sh --NotebookApp.password='sha1:78f1988b6a17:91e3e10508156128c6f7e97cddbbe4f073d58fd9' --user root -e GRANT_SUDO=yes --name=jupyter_notebook

anyone else experience that issue? How can I start the container with sudo access?

thanks!

**Comment by parente** [comment]
The -e and —user are docker arguments and have to come before the image name like the -p

**Comment by AlexAbraham1** [comment]
Thanks! that worked :)
