### ISSUE TITLE
A notebook for Ruby stack

### ISSUE THREAD

**Issue by jimmynguyc** [jupyter/docker-stacks#487]
I think it would be nice to have a notebook for IRuby. Made a PR https://github.com/jupyter/docker-stacks/pull/486

**Comment by jimmynguyc** [comment]
I'll submit another one for `pycall` if you guys think it's a good idea.

**Comment by parente** [comment]
@jimmynguyc Thanks for submitting the Ruby PR.

Are you interested in helping maintain the image over time in this repository with us? This would involve answering questions from users, upgrading versions, adding packages, fixing permission bugs, debugging build problems on Docker Cloud, and so on for the Ruby image in particular. If you're interested, then let's get the PR merged here. If you're not (and it's fine if you aren't: it is a time commitment), I'm not sure I (we?) have the Ruby know-how or bandwidth to take it on at the moment, without help from the community.

As for `pycall`, that sounds like a reasonable addition to the datascience-notebook stack which contains both Julia and Python. If it has a Julia 0.6.0 requirement, note that #471 and #454 are both open.

**Comment by jimmynguyc** [comment]
> Are you interested in helping maintain the image over time in this repository with us?

@parente Sure I can do that :) 

> As for pycall, that sounds like a reasonable addition to the datascience-notebook stack which contains both Julia and Python. If it has a Julia 0.6.0 requirement, note that #471 and #454 are both open.

Since `pycall` is just a Python object wrapper in Ruby I don't think it will have issues with Julia < 0.6.0. I'll check it out.

**Comment by parente** [comment]
I'm going to close out this issue as we have PR #486 with more of a comment history.
