### ISSUE TITLE
all-spark-notebook image with R3.3.1

### ISSUE THREAD

**Issue by yu2003w** [jupyter/docker-stacks#488]
Hi，
How could I get all-spark-notebook image with R3.3.1 and ubuntu as base image?

Thanks.

**Comment by parente** [comment]
You might try creating your own Dockerfile that starts from the jupyter/all-spark-notebook, but uses conda to downgrade from the r-base 3.3.2 package to 3.3.1. Something like this:

```
# latest image tag from https://github.com/jupyter/docker-stacks/wiki/Docker-build-history
FROM jupyter/all-spark-notebook:da2c5a4d00fa

# use the specific version of R that you want
RUN conda install --quiet --yes r-base=3.3.1 && \
    conda clean -tipsy && \
    fix-permissions $CONDA_DIR
```

Then use docker to build your own image using the Dockerfile

```
# run this in the folder that contains the Dockerfile above
docker build --rm -t my-all-spark-notebook .
```

You might run into problems with other packages in the upstream image not being compatible with 3.3.1, or conda-forge not having the older version.

**Comment by yu2003w** [comment]
@parente 
When build the image, I met the following problem,
UnsatisfiableError: The following specifications were found to be in conflict:
  - r-base 3.3.1*
  - r-rlang -> r-base 3.4.1*
Use "conda info <package>" to see the dependencies for each package.

For downgrade R version, do I need to remove firstly?

Thanks.

**Comment by parente** [comment]
You can try removing packages until the install works, or create a new conda environment in the image and install the version of R you want there. In both cases, the image will be larger than if you started from jupyter/minimal-notebook because of the way docker file system layering works. So perhaps starting with minimal and installing what you need is the way to go.

**Comment by yu2003w** [comment]
I removed R3.3.2 and installed R3.3.1. However, image size is still about 4.8G.
If I want much more smaller image, how could I do?
Is that possible to only include base ubuntu image and discard unnecessary packages?
Thanks for your help.

**Comment by blacknred0** [comment]
@yu2003w if all you are looking for is R, you can use jupyter/r-notebook instead of jupyter/all-spark-notebook.  It probably has a smaller footprint due to the packages that are required on jupyter/all-spark-notebook.

**Comment by yu2003w** [comment]
I tried to build only with r/python kernel,  image size is more than 4G.
Is that possible to build much smaller images?

**Comment by blacknred0** [comment]
yes, you probably could, but would be risking losing a lot of the features.  you can probably start with `jupyter/minimal-notebook` or clean up `jupyter/scipy-notebook` (by removing unnecessary packages that you think you won't need.

**Comment by yu2003w** [comment]
@blacknred0 Thanks for response. I will try again.
