### ISSUE TITLE
Unable to write R/lib path on jupyter/all-spark-notebook (bbfb8aad625b)

### ISSUE THREAD

**Issue by blacknred0** [jupyter/docker-stacks#489]
I am not sure if this is related to [Issue 443](https://github.com/jupyter/docker-stacks/issues/447), but it could be.  I was trying to install a package and wasn't able through jupyter.  

I ended up solving the issue by 

1. Starting `docker run -it --rm -p 8888:8888 -p 4040:4040 -v $(pwd):/home/jovyan -e GRANT_SUDO=yes --user root jupyter/all-spark-notebook start.sh bash`
2. Then `sudo chmod -R 777 /usr/local/spark-2.2.0-bin-hadoop2.7/R/lib/`
3. Then `jupyter-notebook` and was able to install with no issues.

**What docker image you are using?**

`jupyter/all-spark-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

`docker run -it --rm -p 8888:8888 -p 4040:4040 -v $(pwd):/home/jovyan -e GRANT_SUDO=yes --user root jupyter/all-spark-notebook`

**What steps do you take once the container is running to reproduce the issue?**

Example:

1. Visit http://localhost:8889
2. Start an R notebook
3. Run this command to install a package
```
install.packages("Hmisc", dependencies = TRUE, repos = "http://cran.rstudio.com/")
```

**What do you expect to happen?**

Installation of the package should take place successfully.

**What actually happens?**

The package is unable to install due to `/usr/local/spark-2.2.0-bin-hadoop2.7/R/lib` not being able to write to the path.

```
Loading required package: Hmisc
Warning message in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE, :
“there is no package called ‘Hmisc’”Installing package into ‘/usr/local/spark-2.2.0-bin-hadoop2.7/R/lib’
(as ‘lib’ is unspecified)
Warning message in install.packages("Hmisc", dependencies = TRUE, repos = "http://cran.rstudio.com/"):
“'lib = "/usr/local/spark-2.2.0-bin-hadoop2.7/R/lib"' is not writable”
Error in install.packages("Hmisc", dependencies = TRUE, repos = "http://cran.rstudio.com/"): unable to install packages
Traceback:

1. install.packages("Hmisc", dependencies = TRUE, repos = "http://cran.rstudio.com/")   # at line 3 of file <text>
2. stop("unable to install packages")
```

If needed, I could probably take a look at these two issues and push PR.

**Comment by parente** [comment]
The jovian user has permission to install R package in the conda environment using conda or `install.packages`. The all-spark-notebook Dockerfile has `ENV R_LIBS_USER $SPARK_HOME/R/lib` to refer to RSpark rather than the default lib path in the conda environment. Perhaps we need to set this to the conda path first followed by the Spark path so that `install.packages` targets the conda dir but the RSpark libs are still available?

Happy to take a PR if you know how to address the problem with this additional bit of info. Otherwise, I need to do some reading and experimentation with R paths and packages.

**Comment by blacknred0** [comment]
I wasn't aware of this... 😕 .  I could take a look as well since it seems that there are two `install.packages` location one for conda and the other for RSpark.

Thanks for the share!

**Comment by blacknred0** [comment]
@parente - Would this be worthy enough as the solution to this bug?  If so, then we can consider this close unless you want me to submit a PR with that one liner :hammer: 

from 
``` R
# RSpark config
ENV R_LIBS_USER $SPARK_HOME/R/lib
```
to
``` R
# RSpark config
ENV R_LIBS_USER $SPARK_HOME/R/lib
RUN fix-permissions $R_LIBS_USER
```
I can confirm that by adding this to the docker file, the R package installed successfully as jovian with out super user powers.  Caveat is that will install in `/usr/local/spark-2.2.0-bin-hadoop2.7/R/lib` and not `/opt/conda/lib/R/lib`.  Not sure if that's really an issue.

Proof
``` R
install.packages("Hmisc", dependencies = TRUE, repos = "http://cran.rstudio.com/")

Installing package into ‘/usr/local/spark-2.2.0-bin-hadoop2.7/R/lib’
(as ‘lib’ is unspecified)
also installing the dependencies ‘bindr’, ‘zoo’, ‘bindrcpp’, ‘pkgconfig’, ‘plogr’, ‘httpuv’, ‘xtable’, ‘sourcetools’, ‘backports’, ‘MatrixModels’, ‘mvtnorm’, ‘TH.data’, ‘sandwich’, ‘codetools’, ‘dplyr’, ‘glue’, ‘tidyselect’, ‘shiny’, ‘Matrix’, ‘checkmate’, ‘htmlwidgets’, ‘viridisLite’, ‘SparseM’, ‘quantreg’, ‘nlme’, ‘polspline’, ‘multcomp’, ‘highr’, ‘markdown’, ‘bit’, ‘fastmatch’, ‘tidyr’, ‘hexbin’, ‘crosstalk’, ‘purrr’, ‘lattice’, ‘survival’, ‘Formula’, ‘latticeExtra’, ‘cluster’, ‘rpart’, ‘nnet’, ‘acepack’, ‘foreign’, ‘gridExtra’, ‘data.table’, ‘htmlTable’, ‘viridis’, ‘htmltools’, ‘chron’, ‘rms’, ‘mice’, ‘tables’, ‘knitr’, ‘ff’, ‘ffbase’, ‘plotly’

require("Hmisc")
Loading required package: Hmisc
Loading required package: lattice
Loading required package: survival
Loading required package: Formula
Loading required package: ggplot2

Attaching package: ‘Hmisc’

The following objects are masked from ‘package:base’:

    format.pval, round.POSIXt, trunc.POSIXt, units
```

end of log
```
gcc -std=gnu99 -shared -L/opt/conda/lib/R/lib -L/opt/conda/lib -lgfortran -o rms.so init.o lrmfit.o mlmats.o ormuv.o robcovf.o -lgfortran -lm -lquadmath -L
/opt/conda/lib/R/lib -lR
installing to /usr/local/spark-2.2.0-bin-hadoop2.7/R/lib/rms/libs
** R
** demo
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (rms)

The downloaded source packages are in
        ‘/tmp/Rtmp0Xa8tb/downloaded_packages’
```

**Comment by HOHOOO** [comment]
The same problem with u, and I use `chown` to solve the problem.
 
`chown 777 /usr/local/spark-2.2.0-bin-hadoop2.7/R/lib`

**Comment by parente** [comment]
> Caveat is that will install in /usr/local/spark-2.2.0-bin-hadoop2.7/R/lib and not /opt/conda/lib/R/lib. Not sure if that's really an issue.

I'm not sure either, but installing and working anywhere seems preferable to not installing or working at all.

If you have time to submit the PR to make the 2 line change, please do.
