### ISSUE TITLE
opening spark-shell with parameters not available in Jupyter

### ISSUE THREAD

**Issue by uday2002** [jupyter/docker-stacks#494]
Typically, we uses Jupyter to access resources on Hadoop servers, e.g., http://localhost/hub/login. 

However, sometimes we need to open a spark-shell with parameters other than the defaults that load in a Jupyter session.  For example, spark-shell --num-executors 25 --executor-memory 1g --executor-cores 4 --driver-memory 3g.

While this works in an SSH session, it appears to bypass the YARN limitations that prevent teams from hogging all resource on one server.  We would like to find a solution that allows us to modify Spark parameters, like those above, while keeping our session managed under YARN.  We would prefer to do this in a Jupyter environment, as we frequently use Jupyter on other platforms.

Could you help us find a solution that allows us to change parameters like those above while still working in the Jupyter/YARN environment?

Any ideas. Please let me know.

Thanks,
Uday

**Comment by parente** [comment]
How you configure these parameters depends on what your kernel supports.

The https://github.com/maxpoint/spylon-kernel Scala metakernel supports this kind of configuration via an `%%init_spark` magic. The https://github.com/apache/incubator-toree Scala kernel supports configuration of these parameters by setting them up in a [kernel spec file](https://github.com/apache/incubator-toree/blob/master/etc/kernel.json). When using pyspark via an IPython kernel, you can specify them via options on the SparkConfig object.

**Comment by uday2002** [comment]
Hi Pete,

Thanks for the response.. let me try this in next week. I will get in touch with you. once I try this and any concerns/issue I'm facing in.

Thanks,
Uday

**Comment by parente** [comment]
@uday2002 Just checking in. Did you find a solution to your issue?

**Comment by uday2002** [comment]
Hi  Peter,

Yes, Please close the ticket. Thanks for the help.

Thanks,
Uday
