### ISSUE TITLE
all-spark-notebook  inconsistent spark context after import libraries

### ISSUE THREAD

**Issue by fxofxo** [jupyter/docker-stacks#500]
Hi,
I'm trying to uses jupyter/all-spark-notebook/  (apache-toree Scala kernel) to get a data from kafka with a spark-streaming.
I need to import the library org.apache.spark:spark-streaming-kafka-0-10_2.11:2.2.0, so I use the magic 
AddDeps to get the package
`%AddDeps org.apache.spark spark-streaming-kafka-0-10_2.11 2.2.0. `
It seem to work well, I get 
```
Marking org.apache.spark:spark-streaming-kafka-0-10_2.11:2.2.0 for download Preparing to fetch from:
-> file:/tmp/toree_add_deps8235567186565695423/
-> https://repo1.maven.org/maven2
-> New file at /tmp/toree_add_deps8235567186565695423/https/repo1.maven.org/maven2/org/apache/spark/spark-streaming-kafka-0-10_2.11/2.2.0/spark-streaming-kafka-0-10_2.11-2.2.0.jar
```
Now it is possible to import kafka streaming libraries without error,
```
import org.apache.spark.SparkConf
import org.apache.spark.streaming._
import org.apache.spark.streaming.kafka010.

```
However when I try to create streaming context, I got and exception

```
val ssc = new StreamingContext(sc, Seconds(2))

    Name: Compile Error
Message: <console>:38: error: overloaded method constructor StreamingContext with alternatives:
  (path: String,sparkContext: org.apache.spark.org.apache.spark.org.apache.spark.org.apache.spark.org.apache.spark.SparkContext)org.apache.spark.streaming.StreamingContext <and>
  (path: String,hadoopConf: org.apache.hadoop.conf.Configuration)org.apache.spark.streaming.StreamingContext <and>
  (conf: org.apache.spark.SparkConf,batchDuration: org.apache.spark.streaming.Duration)org.apache.spark.streaming.StreamingContext <and>
  (sparkContext: org.apache.spark.org.apache.spark.org.apache.spark.org.apache.spark.org.apache.spark.SparkContext,batchDuration: org.apache.spark.streaming.Duration)org.apache.spark.streaming.StreamingContext
 cannot be applied to (org.apache.spark.org.apache.spark.org.apache.spark.org.apache.spark.org.apache.spark.SparkContext, org.apache.spark.streaming.Duration)
       val ssc = new StreamingContext(sc, Seconds(2))
                 ^
StackTrace: 
```
I haven't got this error if I don't  import org.apache.spark.streaming.kafka010.

Thanks in advance.

**Comment by parente** [comment]
@fxofxo You should probably file this issue in the Apache Toree issue tracker at https://issues.apache.org/jira/projects/TOREE for better support. On the face of it, the error doesn't look related to Jupyter specifically or the Docker image, other than perhaps an upgrade of Toree is needed if there's a newer release. (Upgrade PRs welcome!)

**Comment by parente** [comment]
This issue has been inactive for quite a while. I'm going to close it out. Feel free to comment here with a link to an upstream Toree ticket about the problem or a solution if it was fixed. If a newer version of Toree addresses the problem, we can take an upgrade PR.
