### ISSUE TITLE
Error when trying to change to python 3.5 in jupyter/minimal-notebook

### ISSUE THREAD

**Issue by nasedil** [jupyter/docker-stacks#501]
**What docker image you are using?**

jupyter/minimal-notebook:7fd175ec22c7

**What complete docker command do you run to launch the container and reproduce the issue?**

`docker run -it --rm jupyter/minimal-notebook:latest conda install -y python=3.5`

**What do you expect to happen?**

Anaconda python version to be downgrated to python 3.5

**What actually happens?**

It fails with an error with the following output:
```
WARNING conda.core.link:run_script(516): pre-unlink script failed for package conda-forge::jupyterlab-0.29.1-py36_0
consider notifying the package maintainer
ERROR conda.core.link:_execute_actions(337): An error occurred while installing package 'conda-forge::jupyterlab-0.29.1-py35_0'.
LinkError: post-link script failed for package conda-forge::jupyterlab-0.29.1-py35_0
running your command again with `-v` will provide additional information
location of failed script: /opt/conda/bin/.jupyterlab-post-link.sh
==> script messages <==
<None>

Attempting to roll back.


LinkError: post-link script failed for package conda-forge::jupyterlab-0.29.1-py35_0
running your command again with `-v` will provide additional information
location of failed script: /opt/conda/bin/.jupyterlab-post-link.sh
==> script messages <==
<None>
```

**Comment by parente** [comment]
Looks like the link and unlink scripts in the jupyterlab conda-forge package (https://github.com/conda-forge/jupyterlab-feedstock) failed during the downgrade. Can you run bash in a container, try the downgrade with the `-v` flag as suggested, and post the additional info if there is any?

/cc @blink1073

**Comment by blink1073** [comment]
It could be that there are insufficient permissions to modify the jupyter configuration file that the pre-post link scripts are affecting (`jupyter_notebook_config.py`).

**Comment by jakirkham** [comment]
This is basically a bug (or missing feature depending on your perspective) in `conda` 4.3. AIUI `conda` 4.4.0+ fixes this issue ( https://github.com/conda/conda/issues/5417 ). Since we are now on `conda` 4.4.10 thanks to @parente's PR ( https://github.com/jupyter/docker-stacks/pull/624 ), this should be resolved going forward.

**Comment by parente** [comment]
Thanks @jakirkham. @nasedil I'm going to close this issue as resolved by the conda update. Feel free to open a new one if you're still having trouble after updating to the latest images.
