### ISSUE TITLE
Cannot adjust timezome and date / time

### ISSUE THREAD

**Issue by antowan** [jupyter/docker-stacks#504]
Hi,
I am using the latest version of the jupyter/scipy-notebook and I would like to change the default time / date and timezone

I could adjust only in the docker-compose as follow.
> environment: -"TZ=Japan"

Also as I couldn't find any information about the root password I am unable to execute any commands with the root privilege to adjust this. 

Thank you for your update.

**Comment by parente** [comment]
@antowan can you clarify your issue a bit for us. Are you saying that you *can* adjust the timezone in a docker-compose.yaml but *can't* using some other method?

**Comment by antowan** [comment]
@parente I could advance a little on that and what I understand from the various forum I could check is that it's not related to this docker image but it is a general "issue" with the docker containers that need to adjust the time / clock. Indeed it is not permitted to change this from the container as it is an hardware settings. 
For containers running on different timezone I can still adjust the TZ from the docker-compose yaml file.
But for the clock management I'm stuck. I guess it is a bug with the MobyVMLinux VM on Windows as the hardware clock is OK but the container clock is drifted...

**Comment by parente** [comment]
@antowan Thanks for clarifying and sharing what you found.
