### ISSUE TITLE
Please add to scipy-notebook/Dockerfile: jupyter labextension install @jupyter-widgets/jupyterlab-manager

### ISSUE THREAD

**Issue by tlinnet** [jupyter/docker-stacks#505]
**What docker image you are using?**
jupyter/scipy-notebook:7fd175ec22c7

The Dockerfile for scipy-notebook installs ipywidgets.
https://github.com/jupyter/docker-stacks/blob/master/scipy-notebook/Dockerfile

The jupyter/scipy-notebook can run in JupyterLab mode.
But the ipywidgets extension is not enabled for JupyterLab.

Please add this to the Dockerfile:
`jupyter labextension install @jupyter-widgets/jupyterlab-manager`

This is also discussed here: https://github.com/jupyter-widgets/ipywidgets/issues/1683#issuecomment-328952119

**Comment by parente** [comment]
Thanks @tlinnet.  If you or anyone would like to submit a PR before we get to it, mimicking how the jupyterlab-hub  extension gets installed in the base image https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile#L82 is probably the way to go.

**Comment by tlinnet** [comment]
Hi @parente . I have now made a PR. I tested it, and it works as expected.

**Comment by tlinnet** [comment]
This was solved by a PR
