### ISSUE TITLE
%matplotlib inline must be at the top

### ISSUE THREAD

**Issue by jfpuget** [jupyter/docker-stacks#51]
If `%matplotlib inline` is executed after imports that drag matplotlib, then the kernel issues an error about the missing `libXrender.so.1`

Installing the missing library with
  `sudo apt-get install libxrender1`
fixes the isue but grows the image.

Another fix would be to have `%matplotlib inline` be implicit at the top of all notebooks.  Then you need to have a way to disable it if need be.

**Comment by jfpuget** [comment]
The issue is that existing notebooks may not run as is.  The %matplotlib inline line will have to be moved to the top manually.

**Comment by parente** [comment]
I'll have a look at if we set a default to inline in the config for the notebook, can user still override it with a magic at notebook start time (like %matplotlib notebook). If so, that might be a reasonable fix so that the image does something reasonably by default.

**Comment by jfpuget** [comment]
libXrenderer1 is also required to display R plots inline.  I'm opening a separate issue for that.

**Comment by parente** [comment]
Sounds like lobbing the lib into the image is the right answer then. Let me check on how much it increases the image size to see if it should go in the base minimal-notebook or not.

**Comment by parente** [comment]
I'm actually not seeing this in the latest images. Were you using all-spark-notebook? Can you paste the lines you were executing in the order you were executing them to get the libxrender.so.1 error?

**Comment by jfpuget** [comment]
I am not seeing it either anymore.  But I still see #54 with all-spark-notebook.

**Comment by parente** [comment]
Thanks for confirming. The PR for #54 is still pending so yes that one is still an issue.

I'm going to close this one for now, but if you (or anyone) manages to reproduce it, please reopen.
