### ISSUE TITLE
JupyterLab extensions

### ISSUE THREAD

**Issue by dhirschfeld** [jupyter/docker-stacks#511]
I'm building my own JupyterLab analytics images using Windows Containers and have a conceptual question about how best to manage lab extensions.

In [`scipy-notebook`](https://github.com/jupyter/docker-stacks/blob/033056e6d1648e484b61e523f22eb87fefedd3bd/scipy-notebook/Dockerfile#L50) I notice that the usual `jupyter labextension install` command is just run as part of image build:
https://github.com/jupyter/docker-stacks/blob/033056e6d1648e484b61e523f22eb87fefedd3bd/scipy-notebook/Dockerfile#L50

...however I'm concerned that this might create a lot of temporary files which will explode the image size. After installing 5 extensions as part of my image build I'm seeing an image which is 15GB rather than 10GB without the lab extensions.

I wondering if it would be better to do the install in a multi-stage build and to copy the `share/jupyter/lab/extensions` folder into the final image? Does that sound sensible? Would that work or is there a reason that's not already being done?

**Comment by parente** [comment]
> Does that sound sensible? Would that work or is there a reason that's not already being done?

On the face of it, it should work. I'm not familiar with how much would be involved in rearranging the existing Dockerfiles to support it.

I did notice the /home/jovyan/.npm was caching all the packages from the npm install. I slipped a commit into a testing PR I'm working on to address that, but haven't yet merged it.

**Comment by dhirschfeld** [comment]
I'll give it a go an report back...

**Comment by dhirschfeld** [comment]
So, it turns out my image explosion was for a different reason, not related to the building of JupyterLab extensions.

Using multi-stage builds to avoid npm temp junk *does* save a little space but only 9.49GB vs 9.55GB so possibly not even enough to worry about. Still, 60MB is 60MB!

I'll go ahead and close this, but in case it's useful for comparison purposes the multi-stage recipe I used is below. I tested the at least the plotly extension worked fine in the resulting image.

```powershell
FROM miniconda as quantdev-base

SHELL ["powershell", "-Command", "$ErrorActionPreference='Stop'; $ProgressPreference='SilentlyContinue';"]

COPY quantdev.yml C:/

RUN Start-Process conda -ArgumentList 'config','--set','channel_priority','false' -NoNewWindow -Wait; \
    Start-Process conda -ArgumentList 'env','update','--quiet','--file','C:/quantdev.yml'  -NoNewWindow -Wait; \
    Start-Process conda -ArgumentList 'clean','-tisy', -NoNewWindow -Wait; \
    Remove-Item -Force C:/quantdev.yml;


FROM quantdev-base as quantdev-build

SHELL ["powershell", "-Command", "$ErrorActionPreference='Stop'; $ProgressPreference='SilentlyContinue';"]

RUN Start-Process jupyter -ArgumentList 'labextension','install','@jupyterlab/geojson-extension' -NoNewWindow -Wait;
RUN Start-Process jupyter -ArgumentList 'labextension','install','@jupyterlab/plotly-extension' -NoNewWindow -Wait;
RUN Start-Process jupyter -ArgumentList 'labextension','install','@jupyter-widgets/jupyterlab-manager' -NoNewWindow -Wait;
RUN Start-Process jupyter -ArgumentList 'labextension','install','@jupyterlab/hub-extension' -NoNewWindow -Wait;
RUN Start-Process jupyter -ArgumentList 'labextension','install','jupyterlab_bokeh' -NoNewWindow -Wait;
RUN Start-Process jupyter -ArgumentList 'lab','build' -NoNewWindow -Wait;
RUN Remove-Item -Force -Recurse "C:\Miniconda3\share\jupyter\lab\staging"


FROM quantdev-base

SHELL ["powershell", "-Command", "$ErrorActionPreference='Stop'; $ProgressPreference='SilentlyContinue';"]

RUN Remove-Item -Force -Recurse "C:\Miniconda3\share\jupyter\lab"

COPY --from=quantdev-build "C:/Miniconda3/share/jupyter/lab" "C:/Miniconda3/share/jupyter/lab"

ENV R_USER="ContainerAdministrator"
ENV R_HOME="C:\Miniconda3\R"

SHELL ["cmd", "/S", "/C"]
```

**Comment by blink1073** [comment]
@dhirschfeld, I'd recommend adding a `--no-build` on each of those `labextension install` calls, otherwise it is auto-building each time.

**Comment by dhirschfeld** [comment]
Ah, right - that'll save a fair bit of time! Thanks @blink1073!
