### ISSUE TITLE
Updates to the tensorflow stack

### ISSUE THREAD

**Issue by yuvipanda** [jupyter/docker-stacks#513]
Hello! I'm at KubeCon, and spent some time with @foxish and @vishh about TensorFlow. They indicated a desire to add some extra functionality to our tensorflow based stack here, so am filing this issue to remind me and them :)

**Comment by parente** [comment]
This issue has been idle for quite some time. Is it OK to close it out for now? We can certainly discuss changes to the tensorflow image in new issues / PRs.

**Comment by parente** [comment]
I'm going to close out this issue as it's been inactive for some time now.
