### ISSUE TITLE
Question: can i share data from scala to R?

### ISSUE THREAD

**Issue by tomer-ben-david** [jupyter/docker-stacks#521]
Hi! Thanks for using Jupyter's docker-stacks images.

If you are requesting a library upgrade or addition in one of the existing images, please state the desired library name and version here and disregard the remaining sections.

If you are reporting an issue with one of the existing images, please answer the questions below to help us troubleshoot the problem. Please be as thorough as possible.

**What docker image you are using?**

Example: `jupyter/scipy-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

Example: `docker run -it --rm -p 8889:8888 jupyter/all-spark-notebook:latest`

**What steps do you take once the container is running to reproduce the issue?**

Example:

1. Visit http://localhost:8889
2. Start an R noteobok
3. ...

**What do you expect to happen?**

Example: ggplot output appears in my notebook.

**What actually happens?**

Example: No output is visible in the notebook and the notebook server log contains messages about ...

**Comment by parente** [comment]
@tomer-ben-david The answer depends on the Jupyter kernel you are using.

* With Apache Toree, the answer is "yes", if the data are in a Spark DataFrame" which can be shared via the shared SparkContext.
* With spylon-kernel, the answer is "not easily".
* I'm not sure what the answer is when using [jupyter-scala](https://github.com/jupyter-scala/jupyter-scala).

**Comment by parente** [comment]
@tomer-ben-david I'm going to close this issue as it has been inactive for quite some time. Hopefully the information provided answered your question. Feel free to ask further questions in new issues.
