### ISSUE TITLE
Step 10/28 : ADD fix-permissions /usr/local/bin/fix-permissions ADD failed: stat /var/lib/docker/tmp/docker-builder520912608/fix-permissions: no such file or directory

### ISSUE THREAD

**Issue by hpham04** [jupyter/docker-stacks#523]
Hi!
I tried to download the Dockerfile then tried to build it 
It was OK until step 10/28

**What docker image you are using?**

Example: `jupyter/base-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

docker build  .

**What steps do you take once the container is running to reproduce the issue?**

Example:

1. Download Dockerfile, add a line to download minio client 'RUN conda install -c anaconda-platform minio-client before line 87  '# Install Jupyter Notebook and Hub' (but it didn't reach this line)
2. Move to directory contains Dockerfile, then execute: 'docker build  .'
3. Error message appeared "Step 10/28 : ADD fix-permissions /usr/local/bin/fix-permissions ADD failed: stat /var/lib/docker/tmp/docker-builder520912608/fix-permissions: no such file or directory"

**What do you expect to happen?**

It should build from Dockerfile successfuly

**What actually happens?**

Error occured

Below is the full logs:

Hais-MacBook-Pro:jupyter-notebook haipham$ docker build  .
Sending build context to Docker daemon  5.632kB
Step 1/28 : FROM ubuntu@sha256:84c334414e2bfdcae99509a6add166bbb4fa4041dc3fa6af08046a66fed3005f
sha256:84c334414e2bfdcae99509a6add166bbb4fa4041dc3fa6af08046a66fed3005f: Pulling from library/ubuntu
e0a742c2abfd: Already exists 
486cb8339a27: Already exists 
dc6f0d824617: Already exists 
4f7a5649a30e: Already exists 
672363445ad2: Already exists 
Digest: sha256:84c334414e2bfdcae99509a6add166bbb4fa4041dc3fa6af08046a66fed3005f
Status: Downloaded newer image for ubuntu@sha256:84c334414e2bfdcae99509a6add166bbb4fa4041dc3fa6af08046a66fed3005f
 ---> 14f60031763d
Step 2/28 : LABEL maintainer "Jupyter Project <jupyter@googlegroups.com>"
 ---> Running in 096a455fd35e
 ---> b995b1656733
Removing intermediate container 096a455fd35e
Step 3/28 : USER root
 ---> Running in b8dea81407ba
 ---> 3fd81f4b4c2e
Removing intermediate container b8dea81407ba
Step 4/28 : ENV DEBIAN_FRONTEND noninteractive
 ---> Running in 5e28a43f0547
 ---> 2261c018b971
Removing intermediate container 5e28a43f0547
Step 5/28 : RUN apt-get update && apt-get -yq dist-upgrade  && apt-get install -yq --no-install-recommends     wget     bzip2     ca-certificates     sudo     locales     fonts-liberation  && apt-get clean  && rm -rf /var/lib/apt/lists/*
 ---> Running in 7608ad390195
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Get:2 http://security.ubuntu.com/ubuntu xenial-security/universe Sources [56.7 kB]
Get:3 http://archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Get:5 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [521 kB]
Get:6 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Get:7 http://security.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages [12.9 kB]
Get:8 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [239 kB]
Get:9 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [3481 B]
Get:10 http://archive.ubuntu.com/ubuntu xenial/universe Sources [9802 kB]
Get:11 http://archive.ubuntu.com/ubuntu xenial/main amd64 Packages [1558 kB]
Get:12 http://archive.ubuntu.com/ubuntu xenial/restricted amd64 Packages [14.1 kB]
Get:13 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages [9827 kB]
Get:14 http://archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages [176 kB]
Get:15 http://archive.ubuntu.com/ubuntu xenial-updates/universe Sources [233 kB]
Get:16 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [882 kB]
Get:17 http://archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages [13.7 kB]
Get:18 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [726 kB]
Get:19 http://archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [18.5 kB]
Get:20 http://archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages [5162 B]
Get:21 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [7146 B]
Fetched 24.6 MB in 1min 56s (211 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
The following packages will be upgraded:
  apt base-files dpkg gcc-5-base libapparmor1 libapt-pkg5.0 libcryptsetup4
  libdb5.3 libkmod2 libstdc++6 libsystemd0 libudev1 perl-base systemd
  systemd-sysv
15 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 10.3 MB of archives.
After this operation, 13.3 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 base-files amd64 9.4ubuntu4.5 [68.4 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 dpkg amd64 1.18.4ubuntu1.3 [2084 kB]
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 perl-base amd64 5.22.1-9ubuntu0.2 [1282 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 gcc-5-base amd64 5.4.0-6ubuntu1~16.04.5 [17.1 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libstdc++6 amd64 5.4.0-6ubuntu1~16.04.5 [393 kB]
Get:6 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libapt-pkg5.0 amd64 1.2.24 [707 kB]
Get:7 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 apt amd64 1.2.24 [1043 kB]
Get:8 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libapparmor1 amd64 2.10.95-0ubuntu2.7 [31.2 kB]
Get:9 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libcryptsetup4 amd64 2:1.6.6-5ubuntu2.1 [73.3 kB]
Get:10 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libkmod2 amd64 22-1ubuntu5 [39.9 kB]
Get:11 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libsystemd0 amd64 229-4ubuntu21 [205 kB]
Get:12 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 systemd amd64 229-4ubuntu21 [3628 kB]
Get:13 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 systemd-sysv amd64 229-4ubuntu21 [12.1 kB]
Get:14 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libdb5.3 amd64 5.3.28-11ubuntu0.1 [670 kB]
Get:15 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libudev1 amd64 229-4ubuntu21 [54.6 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 10.3 MB in 3min 14s (53.0 kB/s)
(Reading database ... 4764 files and directories currently installed.)
Preparing to unpack .../base-files_9.4ubuntu4.5_amd64.deb ...
Unpacking base-files (9.4ubuntu4.5) over (9.4ubuntu4.4) ...
Setting up base-files (9.4ubuntu4.5) ...
Installing new version of config file /etc/issue ...
Installing new version of config file /etc/issue.net ...
Installing new version of config file /etc/lsb-release ...
(Reading database ... 4764 files and directories currently installed.)
Preparing to unpack .../dpkg_1.18.4ubuntu1.3_amd64.deb ...
Unpacking dpkg (1.18.4ubuntu1.3) over (1.18.4ubuntu1.2) ...
Setting up dpkg (1.18.4ubuntu1.3) ...
(Reading database ... 4764 files and directories currently installed.)
Preparing to unpack .../perl-base_5.22.1-9ubuntu0.2_amd64.deb ...
Unpacking perl-base (5.22.1-9ubuntu0.2) over (5.22.1-9) ...
Setting up perl-base (5.22.1-9ubuntu0.2) ...
(Reading database ... 4764 files and directories currently installed.)
Preparing to unpack .../gcc-5-base_5.4.0-6ubuntu1~16.04.5_amd64.deb ...
Unpacking gcc-5-base:amd64 (5.4.0-6ubuntu1~16.04.5) over (5.4.0-6ubuntu1~16.04.4) ...
Setting up gcc-5-base:amd64 (5.4.0-6ubuntu1~16.04.5) ...
(Reading database ... 4764 files and directories currently installed.)
Preparing to unpack .../libstdc++6_5.4.0-6ubuntu1~16.04.5_amd64.deb ...
Unpacking libstdc++6:amd64 (5.4.0-6ubuntu1~16.04.5) over (5.4.0-6ubuntu1~16.04.4) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Setting up libstdc++6:amd64 (5.4.0-6ubuntu1~16.04.5) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
(Reading database ... 4764 files and directories currently installed.)
Preparing to unpack .../libapt-pkg5.0_1.2.24_amd64.deb ...
Unpacking libapt-pkg5.0:amd64 (1.2.24) over (1.2.20) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Setting up libapt-pkg5.0:amd64 (1.2.24) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
(Reading database ... 4764 files and directories currently installed.)
Preparing to unpack .../archives/apt_1.2.24_amd64.deb ...
Unpacking apt (1.2.24) over (1.2.20) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Setting up apt (1.2.24) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
(Reading database ... 4766 files and directories currently installed.)
Preparing to unpack .../libapparmor1_2.10.95-0ubuntu2.7_amd64.deb ...
Unpacking libapparmor1:amd64 (2.10.95-0ubuntu2.7) over (2.10.95-0ubuntu2.6) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Setting up libapparmor1:amd64 (2.10.95-0ubuntu2.7) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
(Reading database ... 4766 files and directories currently installed.)
Preparing to unpack .../libcryptsetup4_2%3a1.6.6-5ubuntu2.1_amd64.deb ...
Unpacking libcryptsetup4:amd64 (2:1.6.6-5ubuntu2.1) over (2:1.6.6-5ubuntu2) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Setting up libcryptsetup4:amd64 (2:1.6.6-5ubuntu2.1) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
(Reading database ... 4766 files and directories currently installed.)
Preparing to unpack .../libkmod2_22-1ubuntu5_amd64.deb ...
Unpacking libkmod2:amd64 (22-1ubuntu5) over (22-1ubuntu4) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Setting up libkmod2:amd64 (22-1ubuntu5) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
(Reading database ... 4766 files and directories currently installed.)
Preparing to unpack .../libsystemd0_229-4ubuntu21_amd64.deb ...
Unpacking libsystemd0:amd64 (229-4ubuntu21) over (229-4ubuntu17) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Setting up libsystemd0:amd64 (229-4ubuntu21) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
(Reading database ... 4766 files and directories currently installed.)
Preparing to unpack .../systemd_229-4ubuntu21_amd64.deb ...
Unpacking systemd (229-4ubuntu21) over (229-4ubuntu17) ...
Setting up systemd (229-4ubuntu21) ...
Initializing machine ID from random generator.
addgroup: The group `systemd-journal' already exists as a system group. Exiting.
Operation failed: No such file or directory
(Reading database ... 4768 files and directories currently installed.)
Preparing to unpack .../systemd-sysv_229-4ubuntu21_amd64.deb ...
Unpacking systemd-sysv (229-4ubuntu21) over (229-4ubuntu17) ...
Setting up systemd-sysv (229-4ubuntu21) ...
(Reading database ... 4768 files and directories currently installed.)
Preparing to unpack .../libdb5.3_5.3.28-11ubuntu0.1_amd64.deb ...
Unpacking libdb5.3:amd64 (5.3.28-11ubuntu0.1) over (5.3.28-11) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Setting up libdb5.3:amd64 (5.3.28-11ubuntu0.1) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
(Reading database ... 4768 files and directories currently installed.)
Preparing to unpack .../libudev1_229-4ubuntu21_amd64.deb ...
Unpacking libudev1:amd64 (229-4ubuntu21) over (229-4ubuntu17) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Setting up libudev1:amd64 (229-4ubuntu21) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libidn11 libssl1.0.0 openssl
Suggested packages:
  bzip2-doc
The following NEW packages will be installed:
  bzip2 ca-certificates fonts-liberation libidn11 libssl1.0.0 locales openssl
  sudo wget
0 upgraded, 9 newly installed, 0 to remove and 0 not upgraded.
Need to get 6559 kB of archives.
After this operation, 23.9 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu xenial/main amd64 bzip2 amd64 1.0.6-8 [32.7 kB]
Get:2 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libidn11 amd64 1.32-3ubuntu1.2 [46.5 kB]
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 libssl1.0.0 amd64 1.0.2g-1ubuntu4.10 [1083 kB]
Get:4 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 locales all 2.23-0ubuntu9 [3220 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 sudo amd64 1.8.16-0ubuntu1.5 [390 kB]
Get:6 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 openssl amd64 1.0.2g-1ubuntu4.10 [492 kB]
Get:7 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 ca-certificates all 20170717~16.04.1 [168 kB]
Get:8 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 wget amd64 1.17.1-1ubuntu1.3 [299 kB]
Get:9 http://archive.ubuntu.com/ubuntu xenial/main amd64 fonts-liberation all 1.07.4-1 [829 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 6559 kB in 60s (108 kB/s)
Selecting previously unselected package bzip2.
(Reading database ... 4768 files and directories currently installed.)
Preparing to unpack .../bzip2_1.0.6-8_amd64.deb ...
Unpacking bzip2 (1.0.6-8) ...
Selecting previously unselected package libidn11:amd64.
Preparing to unpack .../libidn11_1.32-3ubuntu1.2_amd64.deb ...
Unpacking libidn11:amd64 (1.32-3ubuntu1.2) ...
Selecting previously unselected package libssl1.0.0:amd64.
Preparing to unpack .../libssl1.0.0_1.0.2g-1ubuntu4.10_amd64.deb ...
Unpacking libssl1.0.0:amd64 (1.0.2g-1ubuntu4.10) ...
Selecting previously unselected package locales.
Preparing to unpack .../locales_2.23-0ubuntu9_all.deb ...
Unpacking locales (2.23-0ubuntu9) ...
Selecting previously unselected package sudo.
Preparing to unpack .../sudo_1.8.16-0ubuntu1.5_amd64.deb ...
Unpacking sudo (1.8.16-0ubuntu1.5) ...
Selecting previously unselected package openssl.
Preparing to unpack .../openssl_1.0.2g-1ubuntu4.10_amd64.deb ...
Unpacking openssl (1.0.2g-1ubuntu4.10) ...
Selecting previously unselected package ca-certificates.
Preparing to unpack .../ca-certificates_20170717~16.04.1_all.deb ...
Unpacking ca-certificates (20170717~16.04.1) ...
Selecting previously unselected package wget.
Preparing to unpack .../wget_1.17.1-1ubuntu1.3_amd64.deb ...
Unpacking wget (1.17.1-1ubuntu1.3) ...
Selecting previously unselected package fonts-liberation.
Preparing to unpack .../fonts-liberation_1.07.4-1_all.deb ...
Unpacking fonts-liberation (1.07.4-1) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Setting up bzip2 (1.0.6-8) ...
Setting up libidn11:amd64 (1.32-3ubuntu1.2) ...
Setting up libssl1.0.0:amd64 (1.0.2g-1ubuntu4.10) ...
Setting up locales (2.23-0ubuntu9) ...
Generating locales (this might take a while)...
Generation complete.
Setting up sudo (1.8.16-0ubuntu1.5) ...
Setting up openssl (1.0.2g-1ubuntu4.10) ...
Setting up ca-certificates (20170717~16.04.1) ...
Setting up wget (1.17.1-1ubuntu1.3) ...
Setting up fonts-liberation (1.07.4-1) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
Processing triggers for ca-certificates (20170717~16.04.1) ...
Updating certificates in /etc/ssl/certs...
148 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
 ---> da138c5de4f0
Removing intermediate container 7608ad390195
Step 6/28 : RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen &&     locale-gen
 ---> Running in 29c9ca02fcd0
Generating locales (this might take a while)...
  en_US.UTF-8... done
Generation complete.
 ---> bfad5b669211
Removing intermediate container 29c9ca02fcd0
Step 7/28 : RUN wget --quiet https://github.com/krallin/tini/releases/download/v0.10.0/tini &&     echo "1361527f39190a7338a0b434bd8c88ff7233ce7b9a4876f3315c22fce7eca1b0 *tini" | sha256sum -c - &&     mv tini /usr/local/bin/tini &&     chmod +x /usr/local/bin/tini
 ---> Running in 315a1727be97
tini: OK
 ---> a15babf5a7b2
Removing intermediate container 315a1727be97
Step 8/28 : ENV CONDA_DIR /opt/conda SHELL /bin/bash NB_USER jovyan NB_UID 1000 NB_GID 100 LC_ALL en_US.UTF-8 LANG en_US.UTF-8 LANGUAGE en_US.UTF-8
 ---> Running in d8f44715b2ec
 ---> b103dff3bbff
Removing intermediate container d8f44715b2ec
Step 9/28 : ENV PATH $CONDA_DIR/bin:$PATH HOME /home/$NB_USER
 ---> Running in 30e7ed0fcdbf
 ---> 67780e67ef92
Removing intermediate container 30e7ed0fcdbf
Step 10/28 : ADD fix-permissions /usr/local/bin/fix-permissions
ADD failed: stat /var/lib/docker/tmp/docker-builder520912608/fix-permissions: no such file or directory

**Comment by parente** [comment]
@hpham04 You'll need to git clone this entire project if you plan to build the images yourself locally. There are scripts and files besides the Dockerfile for some of the images that need to be in the same directory.

Example of how to build the jupyter/base-notebook image locally:

```
git clone https://github.com/jupyter/docker-stacks.git
cd docker-stacks
make build/base-notebook
```

**Comment by hpham04** [comment]
@parente 
Thank you so much for your help
I tried again and now it's executing Step 14/27, overcome this issue 👍
