### ISSUE TITLE
Hadoop 3.0 is out

### ISSUE THREAD

**Issue by Bidek56** [jupyter/docker-stacks#527]
Hadoop 3.0 is out, it's a major release. Please upgrade the docker-stacks to include hadoop-*3.0.0.jar.
Thanks

**Comment by parente** [comment]
@Bidek56 Thanks for the news. I'm happy to review a PR updating the Spark distribution to one including Hadoop 3.0 when it's available.

**Comment by Bidek56** [comment]
Jar files for Spark with Hadoop 3.0 are not available yet, so this may have to wait till those jar files are available.

**Comment by Bidek56** [comment]
Spark 2.3 is out, I have created a PR https://github.com/jupyter/docker-stacks/pull/565 for it.

**Comment by parente** [comment]
The Apache Spark website does not list a release containing Hadoop 3.0 JARs today either.

I'm going to close this issue as it has been idle for over a year now. If someone does make an official  Apache Spark release with the Hadoop 3.0 JARs and we haven't moved away from including Spark+Hadoop in these images by then (#626), I'll happily take a PR with the update.
