### ISSUE TITLE
gfortran is required [in all-spark-notebook] for some R package installation

### ISSUE THREAD

**Issue by jfpuget** [jupyter/docker-stacks#53]
The following triggers an error when executed in a R notebook:
install.packages("randomForest", lib='/opt/conda/lib/R/library', repo="http://cran.us.r-project.org")
The error says installation had non-zero exit status.

I had to run R directly in the container to find the issue, see attached file.

![irkernel0](https://cloud.githubusercontent.com/assets/10423052/10663801/87daaff2-78be-11e5-96de-76ade450a54f.png)

Installing gfortran with the following fixed the issue.  

 `sudo apt-get install gfortran`

I think gfortran should be installed in the image if R is to be supported.

**Comment by parente** [comment]
Was this on an upgrade of random forest in the r-notebook image? Or a fresh install in one of the other images. (There's a precompiled version already installed via conda in the r-notebook.)

I'm wondering if gfortran is really needed at the moment or if conda should be used to install the prebuilt in another image.

**Comment by jfpuget** [comment]
This was with the jupyter/all-spark-notebook image
Point is that I used the R way to install it via
`install.packages("randomForest", lib='/opt/conda/lib/R/library', repo="http://cran.us.r-project.org")`

If you force users to use conda then you're not fully supporting R IMHO.

I undertsand we can preload this package, but the issue is about installing packages in general.  There will always be packages not pre installed, and some may require gfortran.

**Comment by parente** [comment]
You're always going to need more packages. It's always a question of where to draw the line for what's in the image by default vs what the user has to install.

In the case of gfortran, I think I agree it should go into the image by default. It's one of those must have deps for working with R.

For things that the opinionated stack image doesn't pre-install, the user can install using conda or, if this is an user-isolating environment, using the GRANT_SUDO option gives the user the ability to install system packages him/herself when needed.

This probably needs to be documented somewhere.

**Comment by jfpuget** [comment]
Agreed.  I wasn't clear maybe.  I am not asking for any more R packages to be pre installed.  I rather think we should have gfortran to allow the installation of packages that depend on it.

**Comment by parente** [comment]
Turns out it's just missing from all-spark-notebook, but exists in r-notebook and datascience-notebook.
