### ISSUE TITLE
Consider adding jupyterhub-lab to images with JupyterHub and Lab

### ISSUE THREAD

**Issue by yuvipanda** [jupyter/docker-stacks#531]
We currently install JupyterHub and JupyterLab into all the notebook images. It'll be great to install https://github.com/jupyterhub/jupyterlab-hub too in them, since without it Lab doesn't have clean links to JupyterHub control panel.

**Comment by parente** [comment]
Seems reasonable to me. I can't imagine it'll add many bytes to the base-notebook image, as long as we clear the temporary build artifacts like we do when we install ipywidgets in scipy-notebook.

**Comment by parente** [comment]
Looks like we already have it.

https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile#L82

IIRC, the start command has to be `jupyter labhub`. We probably need some documentation about how to enable it appropriately using the `start-singleuser.sh`, `start-notebook.sh`, or `start.sh` scripts here.
