### ISSUE TITLE
R package hexbin for r-notebook image

### ISSUE THREAD

**Issue by terhorst** [jupyter/docker-stacks#532]
The R package `hexbin` (https://cran.r-project.org/web/packages/hexbin) is required to use `geom_hex` in ggplot, however it does not come with the r-notebook image.

**Comment by parente** [comment]
@terhorst Thanks for reporting this issue. If you'd like to add `r-hexbin` to the list of packages conda installed in r-notebook, I'll be happy to review and merge that PR.
