### ISSUE TITLE
 libXrender.so.1 is required to display R plots inline

### ISSUE THREAD

**Issue by jfpuget** [jupyter/docker-stacks#54]
R plots such as the following only create a RPlots.pdf file in the working directory, then issue an error:

`x<-1:10
plot(x)`

output is:
`Error in file(con, "rb"): cannot open the connection`

`Error in file(con, "rb"): cannot open the connection`

`Error in file(con, "rb"): cannot open the connection`

`Error in file(con, "rb"): cannot open the connection`

`plot without title`

Installing the lib in the container with the following fixes the error

`sudo apt-get install libxrender1`

This issue is linked to #51

**Comment by parente** [comment]
Need to resolve rebuild problem in #55 first. Then can fix this.

**Comment by jfpuget** [comment]
Sounds good.

**Comment by parente** [comment]
It's actually installed in r-notebook (https://github.com/jupyter/docker-stacks/blob/master/r-notebook/Dockerfile#L13) and datascience-notebook. I'm guessing you're using all-spark-notebook where it's not.

**Comment by jfpuget** [comment]
Right, I should have said it was for all-spark-notebook.
It is good it is already installed in other images.

**Comment by parente** [comment]
Merged and rebuilt. If you hit any other problems on the latest build, give a shout.

**Comment by jfpuget** [comment]
Just tested and it works fine.  Thanks for the quick build.

**Comment by diegocgaona** [comment]
I have the same error in a Linux AMI from Amazon in AWS.
I already installed libXrender.x86_64 and tried libXrender.i686, but without results. I see the error, and Jupyter generates a PDF in the directory.
I tried with ggplot() and plot()
Someone knows how to solve it?
Thanks!

**Comment by parente** [comment]
@diegocgaona which stack image are you using?

**Comment by diegocgaona** [comment]
@parente  Amazon Linux AMI 2015.09.1 (HVM), SSD Volume Type - ami-60b6c60a

**Comment by parente** [comment]
I'm sorry, I meant which of the Docker container images in this repository are you using? If you're not using one of them, and are installing directly to the VM, then you need to replicate the Docker image contents, in particular the libxrender1 package installed here: https://github.com/jupyter/docker-stacks/blob/master/minimal-notebook/Dockerfile#L28
