### ISSUE TITLE
Unable to access host directory from within container : getting permission denied

### ISSUE THREAD

**Issue by ksingh7** [jupyter/docker-stacks#542]
Hi! Thanks for using Jupyter's docker-stacks images.

If you are requesting a library upgrade or addition in one of the existing images, please state the desired library name and version here and disregard the remaining sections.

If you are reporting an issue with one of the existing images, please answer the questions below to help us troubleshoot the problem. Please be as thorough as possible.

**What docker image you are using?**
``jupyter/all-spark-notebook`` and ``jupyter/pyspark-notebook``

**What complete docker command do you run to launch the container (omitting sensitive values)?**

```
docker run -d -p 8889:8888 \
-e NB_UID=1000 -e NB_GID=100 --user=root \
-v /nvme/jupiter-notebook/all-spark-notebook/work:/home/jovyan/work jupyter/all-spark-notebook start-notebook.sh  \
--NotebookApp.password='sha1:e82e6a7ab4f8:0f712ca0de41256805dc003dc2134e0ff70a58d8'
```

**What steps do you take once the container is running to reproduce the issue?**

1. (on host machine) ``chown 1000 /nvme/jupiter-notebook/all-spark-notebook/work`` also done ``chown 1000:100 DIR_NAME``

2. Launch docker container
```
docker run -d -p 8889:8888 \
-e NB_UID=1000 -e NB_GID=100 --user=root \
-v /nvme/jupiter-notebook/all-spark-notebook/work:/home/jovyan/work jupyter/all-spark-notebook start-notebook.sh  \
--NotebookApp.password='sha1:e82e6a7ab4f8:0f712ca0de41256805dc003dc2134e0ff70a58d8'
```
3. Visit jupyter notebook >> open terminal >> cd work  got ``permission denied`` 
4. ``work`` directory is mounted also in container also permission set to ``jovyan:users`` and 755 but still cant touch any file inside work directory

**What do you expect to happen?**

Host directory should get mount inside docker container also user jovyan is allowed to access the mounted directory.

**What actually happens?**

work directory gets mounted but user jovyan is not allowed to access the directory ( not even cd)
...

**Comment by ksingh7** [comment]
- Here is the output from host machine that shows ``/nvme/jupiter-notebook/all-spark-notebook/work`` directory is owned by``ksingh`` user whose id is ``1000``
```
[root@beast work]# ls -ld /nvme/jupiter-notebook/all-spark-notebook/work
drwxr-xr-x. 2 ksingh users 6 Feb  1 00:25 /nvme/jupiter-notebook/all-spark-notebook/work
[root@beast work]#

[root@beast work]# id ksingh
uid=1000(ksingh) gid=1000(ksingh) groups=1000(ksingh),10(wheel)
[root@beast work]#
```
- Next i launch container successfully
```
[root@beast work]# docker run -d -p 8889:8888 \
> -e NB_UID=1000 -e NB_GID=100 --user=root \
> -v /nvme/jupiter-notebook/all-spark-notebook/work:/home/jovyan/work jupyter/all-spark-notebook start-notebook.sh  \
> --NotebookApp.password='sha1:e82e6a7ab4f8:0f712ca0de41256805dc003dc2134e0ff70a58d8'
741ba66b50e67a29ca982b502e37441d796621898fa5f0638d5bf1d8f0355443
[root@beast work]#


[root@beast work]# docker ps -a | grep -i all-spark
741ba66b50e6        jupyter/all-spark-notebook                                                                                 "tini -- start-notebo"   12 seconds ago      Up 9 seconds               0.0.0.0:8889->8888/tcp   clever_roentgen
[root@beast work]#
```
- Logs from jupyter terminal , that shows ``/nvme/jupiter-notebook/all-spark-notebook/work`` is mounted on ``/home/jovyan/work``
```
ovyan@741ba66b50e6:~$ df -h
Filesystem                                                                                           Size  Used Avail Use% Mounted on
/dev/mapper/docker-253:0-101458878-5698c442ca17326037ad9c98b43957e05c5d6a575b76c7635ff0d36c1e848e89   10G  5.6G  4.5G  56% /
tmpfs                                                                                                 32G     0   32G   0% /dev
tmpfs                                                                                                 32G     0   32G   0% /sys/fs/cgroup
/dev/mapper/rhel00-root                                                                               50G   12G   39G  24% /etc/hosts
shm                                                                                                   64M     0   64M   0% /dev/shm
/dev/nvme0n1p3                                                                                        30G   33M   30G   1% /home/jovyan/work
tmpfs                                                                                                 32G     0   32G   0% /proc/scsi
jovyan@741ba66b50e6:~$
jovyan@741ba66b50e6:~$ cd work
jovyan@741ba66b50e6:~/work$
jovyan@741ba66b50e6:~/work$ ls -l
ls: cannot open directory '.': Permission denied
jovyan@741ba66b50e6:~/work$
jovyan@741ba66b50e6:~/work$ touch tes
touch: cannot touch 'tes': Permission denied
jovyan@741ba66b50e6:~/work$ pwd
/home/jovyan/work
jovyan@741ba66b50e6:~/work$
jovyan@741ba66b50e6:~/work$
```

**Comment by ksingh7** [comment]
Also if i try to change user id to a different number on host machine and try to launch container, the container fails like this.
```
[root@beast all-spark-notebook]# chown 1010:100 work
[root@beast all-spark-notebook]# ll
total 0
drwxr-xr-x. 2 1010 users 6 Feb  1 00:25 work
[root@beast all-spark-notebook]#
[root@beast all-spark-notebook]#
[root@beast all-spark-notebook]#
[root@beast all-spark-notebook]# docker run -d -p 8889:8888 \
> -e NB_UID=1010 -e NB_GID=100 --user=root \
> -v /nvme/jupiter-notebook/all-spark-notebook/work:/home/jovyan/work jupyter/all-spark-notebook start-notebook.sh  \
> --NotebookApp.password='sha1:e82e6a7ab4f8:0f712ca0de41256805dc003dc2134e0ff70a58d8'
8333ca140b4bd1211789032e68200d081de24317dde4a41615c164ac233f6d1c
[root@beast all-spark-notebook]#
[root@beast all-spark-notebook]# docker ps -a | grep notebook
8333ca140b4b        jupyter/all-spark-notebook                                                                                 "tini -- start-notebo"   About a minute ago   Exited (12) About a minute ago                            mad_hawking
660d79c12a2e        jupyter/pyspark-notebook                                                                                   "tini -- start-notebo"   5 hours ago          Up 5 hours                       0.0.0.0:8890->8888/tcp   stupefied_engelbart
5bd0fa768c77        jupyter/datascience-notebook:latest                                                                        "tini -- start-notebo"   4 days ago           Up 4 days                        0.0.0.0:8888->8888/tcp   kickass_hodgkin
[root@beast all-spark-notebook]#
[root@beast all-spark-notebook]#
[root@beast all-spark-notebook]#
[root@beast all-spark-notebook]# docker logs 8333ca140b4b
Set username to: jovyan
usermod: no changes
Set jovyan UID to: 1010
usermod: Failed to change ownership of the home directory[root@beast all-spark-notebook]#
[root@beast all-spark-notebook]#
```

**Comment by parente** [comment]
@ksingh7 Thanks for the report. I'm seeing the same behavior on OSX with Docker version 17.12.0-ce-mac47. Can you post back with your version of docker and operating system? I'm wondering if Docker for Mac or the Docker daemon now maps container uid/gids to different, ephemeral users on the host by default. Some evidence: `chmod 777 /the/host/folder` and the `jovyan` user in the container can write to the `work` folder just fine.

**Comment by brospars** [comment]
I'm also having permission related issues building a notebook image based on `jupyter/minimal-notebook`. I wonder if this is related.

```
...
creating /opt/conda/lib/python3.6/site-packages/oauth2
    error: could not create '/opt/conda/lib/python3.6/site-packages/oauth2': Permission denied
...
```

**Comment by parente** [comment]
I finally found some time to sit down and try some combinations on my Mac
and Linux boxes. tl;dr: the configuration you need to use to successfully
write to a host mounted volume now differs between the two.

## Mac OSX

https://docs.docker.com/docker-for-mac/osxfs/#ownership explains the ownership
model demonstrated below.

```
$ docker --version
Docker version 18.03.0-ce, build 0520e24

$ uname -a
Darwin aether.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

$ cd ~
$ mkdir test

# NOTE: do NOT chown test! doing so will result in permission errors no matter
# what uid and gid you use in the container

$ docker run -it --rm --user root -e NB_UID=1234 -e NB_GID=1234 -v `pwd`/test:/home/jovyan/work jupyter/base-notebook start.sh
/usr/local/bin/start.sh: ignoring /usr/local/bin/start-notebook.d/*
Set username to: jovyan
usermod: no changes
Set jovyan UID to: 1234
Set jovyan GID to: 1234
Executing the command: bash

# no permission errors when creating files within the container
$ echo "foo" > work/foo
$ ls -ln work/
total 4
-rw-r--r-- 1 1234 1234 4 Apr  8 02:46 foo

$ exit

# view from the host shows files have my host uid and gid
$ ls -ln test/
total 8
-rw-r--r--  1 501  20  4 Apr  7 22:46 foo

# configure jovyan with an alternative uid and gid
$ docker run -it --rm --user root -e NB_UID=5432 -e NB_GID=1111 -v `pwd`/test:/home/jovyan/work jupyter/base-notebook start.sh
/usr/local/bin/start.sh: ignoring /usr/local/bin/start-notebook.d/*
Set username to: jovyan
usermod: no changes
Set jovyan UID to: 5432
Set jovyan GID to: 1111
Executing the command: bash

# no permission errors again
$ echo "bar" > work/bar
$ ls -ln work/
total 8
-rw-r--r-- 1 5432 1111 4 Apr  8 02:47 bar
-rw-r--r-- 1 5432 1111 4 Apr  8 02:46 foo

$ exit

# view from the host shows files have my host user ownership + group again
$ ls -ln test/
total 16
-rw-r--r--  1 501  20  4 Apr  7 22:47 bar
-rw-r--r--  1 501  20  4 Apr  7 22:46 foo

## Linux

The traditional ownership model applies on Linux.

```
$ docker --version
Docker version 18.03.0-ce, build 0520e24

$ uname -a
Linux vm4-002 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ mkdir test
$ sudo chown 1234:1234 test

$ docker run -it --rm --user root -e NB_UID=1234 -e NB_GID=1234 -v `pwd`/test:/home/jovyan/work jupyter/base-notebook start.sh
/usr/local/bin/start.sh: ignoring /usr/local/bin/start-notebook.d/*
Set username to: jovyan
usermod: no changes
Set jovyan UID to: 1234
Set jovyan GID to: 1234
Executing the command: bash

# no permission errors when creating files in the mount from within the container
$ echo "foo" > work/foo
$ ls -ln work/
total 4
-rw-r--r-- 1 1234 1234 4 Apr  8 02:50 foo

$ exit

# view from the host is as expected
$ ls -ln test/
total 4
-rw-r--r-- 1 1234 1234 4 Apr  7 22:50 foo

# trying to use an alternative uid and gid in the container will result in
# permission errors
$ docker run -it --rm --user root -e NB_UID=5432 -e NB_GID=1111 -v `pwd`/test:/home/jovyan/work jupyter/base-notebook start.sh
/usr/local/bin/start.sh: ignoring /usr/local/bin/start-notebook.d/*
Set username to: jovyan
usermod: no changes
Set jovyan UID to: 5432
Set jovyan GID to: 1111
Executing the command: bash

$ echo "bar" > work/bar
bash: work/bar: Permission denied
```

**Comment by rubensa** [comment]
> I finally found some time to sit down and try some combinations on my Mac
> and Linux boxes. tl;dr: the configuration you need to use to successfully
> write to a host mounted volume now differs between the two.
> ## Mac OSX
> 
> https://docs.docker.com/docker-for-mac/osxfs/#ownership explains the ownership
> model demonstrated below.
> 
> ```
> $ docker --version
> Docker version 18.03.0-ce, build 0520e24
> 
> $ uname -a
> Darwin aether.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
> 
> $ cd ~
> $ mkdir test
> 
> # NOTE: do NOT chown test! doing so will result in permission errors no matter
> # what uid and gid you use in the container
> 
> $ docker run -it --rm --user root -e NB_UID=1234 -e NB_GID=1234 -v `pwd`/test:/home/jovyan/work jupyter/base-notebook start.sh
> /usr/local/bin/start.sh: ignoring /usr/local/bin/start-notebook.d/*
> Set username to: jovyan
> usermod: no changes
> Set jovyan UID to: 1234
> Set jovyan GID to: 1234
> Executing the command: bash
> 
> # no permission errors when creating files within the container
> $ echo "foo" > work/foo
> $ ls -ln work/
> total 4
> -rw-r--r-- 1 1234 1234 4 Apr  8 02:46 foo
> 
> $ exit
> 
> # view from the host shows files have my host uid and gid
> $ ls -ln test/
> total 8
> -rw-r--r--  1 501  20  4 Apr  7 22:46 foo
> 
> # configure jovyan with an alternative uid and gid
> $ docker run -it --rm --user root -e NB_UID=5432 -e NB_GID=1111 -v `pwd`/test:/home/jovyan/work jupyter/base-notebook start.sh
> /usr/local/bin/start.sh: ignoring /usr/local/bin/start-notebook.d/*
> Set username to: jovyan
> usermod: no changes
> Set jovyan UID to: 5432
> Set jovyan GID to: 1111
> Executing the command: bash
> 
> # no permission errors again
> $ echo "bar" > work/bar
> $ ls -ln work/
> total 8
> -rw-r--r-- 1 5432 1111 4 Apr  8 02:47 bar
> -rw-r--r-- 1 5432 1111 4 Apr  8 02:46 foo
> 
> $ exit
> 
> # view from the host shows files have my host user ownership + group again
> $ ls -ln test/
> total 16
> -rw-r--r--  1 501  20  4 Apr  7 22:47 bar
> -rw-r--r--  1 501  20  4 Apr  7 22:46 foo
> ```
> 
> ## Linux
> 
> The traditional ownership model applies on Linux.
> 
> ```
> $ docker --version
> Docker version 18.03.0-ce, build 0520e24
> 
> $ uname -a
> Linux vm4-002 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
> 
> $ mkdir test
> $ sudo chown 1234:1234 test
> 
> $ docker run -it --rm --user root -e NB_UID=1234 -e NB_GID=1234 -v `pwd`/test:/home/jovyan/work jupyter/base-notebook start.sh
> /usr/local/bin/start.sh: ignoring /usr/local/bin/start-notebook.d/*
> Set username to: jovyan
> usermod: no changes
> Set jovyan UID to: 1234
> Set jovyan GID to: 1234
> Executing the command: bash
> 
> # no permission errors when creating files in the mount from within the container
> $ echo "foo" > work/foo
> $ ls -ln work/
> total 4
> -rw-r--r-- 1 1234 1234 4 Apr  8 02:50 foo
> 
> $ exit
> 
> # view from the host is as expected
> $ ls -ln test/
> total 4
> -rw-r--r-- 1 1234 1234 4 Apr  7 22:50 foo
> 
> # trying to use an alternative uid and gid in the container will result in
> # permission errors
> $ docker run -it --rm --user root -e NB_UID=5432 -e NB_GID=1111 -v `pwd`/test:/home/jovyan/work jupyter/base-notebook start.sh
> /usr/local/bin/start.sh: ignoring /usr/local/bin/start-notebook.d/*
> Set username to: jovyan
> usermod: no changes
> Set jovyan UID to: 5432
> Set jovyan GID to: 1111
> Executing the command: bash
> 
> $ echo "bar" > work/bar
> bash: work/bar: Permission denied
> ```

On **Linux** (I don't have MacOS) this solution works but if you want to set not only **UserID, GroupID** but **UserName, GroupName** (via **NB_USER** and **NB_GROUP**) you end up with a new user **home directory owned by root** and **without jovyan default home files** (.bash_logout, .bashrc, .cache, .conda, .config, .jupyter, .profile, .yarn), **only the mounted work directory**.

If I run:
```bash
$ docker run -it --rm --user root -e NB_UID=1234 -e NB_GID=1234 -e NB_USER=username -e NB_GROUP=groupname jupyter/base-notebook start.sh
Set username to: username
Relocating home dir to /home/username
Setting CWD to /home/username/
Set username UID to: 1234
Add username to group: 1234
Executing the command: bash
username@9dbfc95b69ae:~$ pwd
/home/username
username@9dbfc95b69ae:~$ ls -la
total 48
drwsrwsr-x 8 username groupname 4096 Jul  4 09:05 .
drwxr-xr-x 1 root     root      4096 Jul  8 13:03 ..
-rw-rw-r-- 1 username groupname  220 Apr  4  2018 .bash_logout
-rw-rw-r-- 1 username groupname 3770 Mar 14 02:54 .bashrc
drwsrwsr-x 2 username groupname 4096 Jul  4 09:05 .cache
drwsrwsr-x 2 username groupname 4096 Jul  4 08:55 .conda
drwsrws--- 3 username groupname 4096 Jul  4 09:02 .config
drwsrws--- 2 username groupname 4096 Jul  4 09:05 .jupyter
-rw-rw-r-- 1 username groupname  807 Apr  4  2018 .profile
drwsrwsr-x 2 username groupname 4096 Apr  8 23:37 work
drwsrwsr-x 3 username groupname 4096 Jul  4 09:04 .yarn
username@9dbfc95b69ae:~$ 
```

but if I run:
```bash
$ docker run -it --rm --user root -e NB_UID=1234 -e NB_GID=1234 -e NB_USER=username -e NB_GROUP=groupname -v `pwd`/test:/home/username/work jupyter/base-notebook start.sh
Set username to: username
Setting CWD to /home/username/
Set username UID to: 1234
Add username to group: 1234
Executing the command: bash
username@3bce498aebda:~$ pwd
/home/username
username@3bce498aebda:~$ ls -la
total 12
drwxr-xr-x 3 root root 4096 Jul  8 13:10 .
drwxr-xr-x 1 root root 4096 Jul  8 13:10 ..
drwxr-xr-x 2 1001 1001 4096 Jul  8 12:52 work
username@3bce498aebda:~$ 

```

So, looks like, when creating the new user's home directory if the home directory does not exists (as It was not externally mapped) the home directory is created with default files and permissions; but when the home directory exists (as It was created cause the external volume mapping -done by the root user-) then no default user files are created and directory permissions are not changed.

The only solution I found (without changing base images) is to create the container without the mapping (and without --rm), stop it, and re-run with the mapping (without --rm).

**Comment by dschneiderch** [comment]
> The only solution I found (without changing base images) is to create the container without the mapping (and without --rm), stop it, and re-run with the mapping (without --rm).

@rubensa how does this work? you can only run `docker run` once to create a container, right?

these permission issues are super frustrating because the [docs ](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html) seem to be misleading or I don't get it.

I'm running a server with CentOS 7 and trying to map an nfs mount to my container. 
`(base) [dominik@cppc-server nfs-pcv-test]$ uname -a
Linux cppc-server 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux` 

my permissions:
```
(base) [dominik@cppc-server nfs-pcv-test]$ id
uid=8545(dominik) gid=7204(kamiak) groups=7204(kamiak),10(wheel),978(docker),1000(dominik)
```
the directory `nfs-pcv-test` is on the the nfs

The nfs mount is only writable with specific UID/GID so I set NB_UID and NB_GID and CHOWN_HOME.

(base) [dominik@cppc-server nfs-pcv-test]$ docker run -it --name nfs-pcv-args --user root -e NB_UID=8545 -e NB_GID=7204 -e NB_GROUP=kamiak -e CHOWN_HOME=yes -e CHOWN_HOME_OPTS='-R' -e NB_UMASK=002 -w /home/jovyan jupyter/minimal-notebook start.sh bash
Set username to: jovyan
usermod: no changes
Changing ownership of /home/jovyan to 8545:7204 with options '-R'
Set user jovyan UID:GID to: 8545:7204
Executing the command: bash
(base) jovyan@24f830d52402:~$ id
uid=8545(jovyan) gid=7204(kamiak) groups=7204(kamiak),100(users)
```
 this appears to work, but I can't start a container with a mapping to the nfs mount.

for example:
```
(base) [dominik@cppc-server nfs-pcv-test]$ docker run -it --name nfs-pcv-args2 --user root -e NB_UID=8545 -e NB_GID=7204 -e NB_GROUP=kamiak -e CHOWN_HOME=yes -e CHOWN_HOME_OPTS='-R' -e NB_UMASK=002 -v $(pwd):/home/jovyan/work -w /home/jovyan jupyter/minimal-notebook start.sh bash
Set username to: jovyan
usermod: no changes
Changing ownership of /home/jovyan to 8545:7204 with options '-R'
chown: cannot read directory '/home/jovyan/work': Permission denied
```

i also tried without -w and setting -e NB_USER=dominik which is my server username

```
(base) [dominik@cppc-server nfs-pcv-test]$ docker run -it --rm --user root -e NB_UID=8545 -e NB_GID=7204 -e NB_GROUP=kamiak -e NB_USER=dominik -e CHOWN_HOME=yes -e CHOWN_HOME_OPTS='-R' -e NB_UMASK=002 -w /home/$NB_USER -v $(pwd):/home/dominik jupyter/minimal-noteboo
k start.sh bash
Set username to: dominik
Changing ownership of /home/dominik to 8545:7204 with options '-R'
chown: cannot read directory '/home/dominik': Permission denied
```

am I missing something?

**Comment by mathbunnyru** [comment]
We have updated our docs and now we describe UID, GID and how to use them and how to troubleshoot common problems.

Please, take a look:

Configuration: https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html#user-related-configurations
Troubleshooting: https://jupyter-docker-stacks.readthedocs.io/en/latest/using/troubleshooting.html

If the issue still persists, then, please, create a new issue.
