### ISSUE TITLE
How to install jupyter/docker-stacks with python 2.x

### ISSUE THREAD

**Issue by moonlight16** [jupyter/docker-stacks#543]
Please find the question here:
https://stackoverflow.com/questions/48590900/how-to-install-jupyter-docker-stacks-with-python-2-x

**Comment by parente** [comment]
@moonlight16 Please see / try https://github.com/jupyter/docker-stacks/wiki/Docker-recipes#add-a-python-2x-environment

**Comment by jakirkham** [comment]
Good to close?

**Comment by parente** [comment]
I think this issue has been addressed via the recipes page on the wiki, soon to be included in the ReadTheDocs site. I'm going to close this issue. Feel free to reopen if you have other questions.
