### ISSUE TITLE
Unable to share folder from windows 10 to container

### ISSUE THREAD

**Issue by iolbr** [jupyter/docker-stacks#568]
**What docker image you are using?**
jupyter/all-spark-notebook

**What complete docker command do you run to launch the container (omitting sensitive values)?**
docker run -it --rm -p 8888:8888 jupyter/all-spark-notebook -v C:/docker/jupyter:/mnt 
--user root -e NB_UID=1000 -e NB_GID=100 -e GRANT_SUDO=yes

Results in: 
[FATAL tini (5)] Executing child process '-v' failed: 'No such file or directory'

Mounting share is working:
docker run -v C:/docker/jupyter:/data alpine ls /data
test.txt

Docker is runnint on Windows 10 1709

**Comment by iolbr** [comment]
Same for
docker run -it --rm -p 8888:8888 jupyter/all-spark-notebook -v C:/docker/jupyter:/home/jovyan/work --
user root -e NB_UID=1000 -e NB_GID=100 -e GRANT_SUDO=yes
[FATAL tini (5)] Executing child process '-v' failed: 'No such file or directory'

**Comment by parente** [comment]
@iolbr The various docker options (-v, -e, --user) have to come before the docker image name (jupyter/all-spark-notebook).

**Comment by iolbr** [comment]
Missed that information! Now it works, many thanks!
