### ISSUE TITLE
The open_browser config option in base-notebook

### ISSUE THREAD

**Issue by mrocklin** [jupyter/docker-stacks#569]
I've been getting errors like the following in my logs

    [W 2018-03-05 12:02:24.533 SingleUserNotebookApp configurable:168] Config option `open_browser` not recognized by `SingleUserNotebookApp`.  Did you mean `browser`?

I tracked the open_browser config option to the `base-notebook` image config file

```python
c = get_config()
c.NotebookApp.ip = '*'
c.NotebookApp.port = 8888
c.NotebookApp.open_browser = False
```

**Comment by mrocklin** [comment]
Hrm, it looks like this is still a valid option.  I realize now that this may not be the best place to raise this issue.  Please let me know if I should reroute.

**Comment by parente** [comment]
@mrocklin I see on the downstream issue that you traced your problem back to kubernetes on GCE (which is good, because I don't think the warning here was related :). OK to close?

**Comment by mrocklin** [comment]
Yes, apologies for the noise.
