### ISSUE TITLE
When using a volume, the work dir belongs to root

### ISSUE THREAD

**Issue by ewjoachim** [jupyter/docker-stacks#575]
**What docker image you are using?**

`jupyter/scipy-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

`docker run -it --rm -p 127.0.0.1:8888:8888 --user=root -e NB_UID=$UID -e NB_GID=$GID -e CHOWN_HOME=1 -v "$pwd/notebooks:/home/jovyan/work" --name notebook jupyter/scipy-notebook`

**What steps do you take once the container is running to reproduce the issue?**

Example:

1. Visit http://localhost:8888
2. Try creating a notebook in work/

**What do you expect to happen?**

Example: Notebook is created

**What actually happens?**

![screenshot from 2018-03-09 18-51-03](https://user-images.githubusercontent.com/1457576/37221601-d9ba4a8a-23ca-11e8-8a82-24876588e6f8.png)

![screenshot from 2018-03-09 18-51-47](https://user-images.githubusercontent.com/1457576/37221635-f13dd212-23ca-11e8-8b71-2557150e346b.png)

Output of start.sh before the notebook starts:
```
Set username to: jovyan
usermod: no changes
Changing ownership of /home/jovyan to 1000:1000
Set jovyan GID to: 1000
Executing the command: jupyter notebook
```

Given that [these lines](https://github.com/jupyter/docker-stacks/blob/master/base-notebook/start.sh#L24-L25) are executed, I don't see how work could still belong to root, but it is so...?

**Comment by ewjoachim** [comment]
Actually, chown is not -R, that's why it doesn't work. I've made a PR :)

**Comment by ewjoachim** [comment]
Should be closed now. Let's reopen if a new problem arises :)

**Comment by cam72cam** [comment]
This needs to be re-opened

**Comment by ewjoachim** [comment]
What happened ? Do the steps outlined above lead to the same bug ? After it was merged, I think it worked for me...
