### ISSUE TITLE
Add netcat to pyspark notebook

### ISSUE THREAD

**Issue by gglanzani** [jupyter/docker-stacks#583]
Hi, thanks for the project!

I was wondering if it would make sense to add netcat (`nc`) to the pyspark image.

The rationale is that, when learning Spark Streaming, many examples use netcat to send data through socket to Spark.

Netcat only takes approximately 130kb up, so that would not influence the size of the image much.

If this is useful, please let me know and I will create a PR (also let me know if pyspark is the right level at which to add this).

**Comment by parente** [comment]
I think it'd be best to put it in minimal-notebook along side the other "handy tools".

**Comment by parente** [comment]
Thanks for the PR!
