### ISSUE TITLE
feature request sparkmagic

### ISSUE THREAD

**Issue by bclipp** [jupyter/docker-stacks#585]
Hi,

I'm using r-notebook, but I feel this would be useful for most notebooks.  the command in this case I'm using is just : 
run -it --rm -p 8888:8888 jupyter/r-notebook

sparkmagic is a livy plugin for jupyter so that jupyternotebook will allow python, R or scala to talk to a Livy API server who then runs the spark session. The trick is you will need to allow the run time env variable of hostname to be passed and then json config file to have the updated hostname.

**Comment by parente** [comment]
We've started to encourage fewer additions to the images here and more contributions to the recipes in the documentation (http://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html).

I think a recipe about how to add and configure sparkmagic would make sense in the docs, if someone would like to send a PR (http://jupyter-docker-stacks.readthedocs.io/en/latest/contributing/recipes.html).

**Comment by bclipp** [comment]
ok when I have a moment I can do that.

**Comment by parente** [comment]
This issue has been inactive for a few months now and so I'm going to close it. That said, I'll be happy to review a PR updating the recipes page with guidance on how to add sparkmagic if someone has the time and interest to write it up.
