### ISSUE TITLE
 don't understand --no-switch_user flag break link

### ISSUE THREAD

**Issue by lastnod** [jupyter/docker-stacks#587]
Hello !
i want to use pyspark-notebook with mesos
and this step is not really clear to me 

> Configure each slave with the --no-switch_user flag or create the jovyan user on every slave node.

and the link on  --no-switch_user flag is not available anymore

Could you write a little explanation or fix the link ?

**Comment by parente** [comment]
http://mesos.apache.org/documentation/latest/configuration/agent/ is an updated page with the agent settings and description of the flag. Search for `switch_user` on that page.

Would you mind submitting a PR updating the README with that link and any improvements you feel warranted based on what you learn from that page?
