### ISSUE TITLE
r-notebook downgrades pyzmq to 16.0, nb fails to start

### ISSUE THREAD

**Issue by parente** [jupyter/docker-stacks#589]
Something in the r-notebook image is causing pyzmq to downgrade to 16.x which is incompatible with the latest tornado 5.0 release. Trying to force `pyzmq>=17` leads to:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - pyzmq >=17
  - r-base 3.3.2*
  - r-irkernel 0.8*
```

Current workaround: forcing `tornado<5` so that pyzmq 16.x works with the notebook server.

Need to figure out what's dragging the packages down and fix upstream.

**Comment by jakirkham** [comment]
Merged PR ( https://github.com/conda-forge/r-pbdzmq-feedstock/pull/4 ). Hopefully that helps.
