### ISSUE TITLE
pyspark-notebook - spark 2.3 default user id in downloaded files

### ISSUE THREAD

**Issue by stijndehaes** [jupyter/docker-stacks#592]
Hi I am using the pyspark-notebook on a kubernetes cluster. I am starting from your image and adding some extra libraries. However since moving to spark 2.3 I can not pull the docker image in my jenkins machine. 

This is because the spark files inside the downloaded spark package are owned by user with uid: 1311767953. And on my jenkins machine user namespace mapping is enabled. For this the work id's should be between 0 - 65535.

For more info see: https://circleci.com/docs/2.0/high-uid-error/

I have already opened a PR with a fix in it: https://github.com/jupyter/docker-stacks/pull/591

**Comment by parente** [comment]
Closing because I believe this was fixed in #591. Feel free to comment if that's not the case.
