### ISSUE TITLE
Question: why doesn't ifconfig work in tensorflow image's terminal?

### ISSUE THREAD

**Issue by cywang16** [jupyter/docker-stacks#597]
Greeting,

I just pulled the latest jupyter/tensorflow-notebook docker image, and launched it. I opened a new terminal, but found 'ifconfog' and 'ip addr' not working. Why is that?

Thanks,

Chun-Yen

**Comment by parente** [comment]
They're not installed in the ubuntu base image nor the `jupyter/*` images defined here by default. You can add them in your own Dockerfile like:

```
FROM jupyter/tensorflow-notebook:sometag

RUN apt-get update && \
    apt-get install -y --no-install-recommends  net-tools && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
```

https://stackoverflow.com/questions/42870005/how-to-install-ifconfig-command-in-my-ubuntu-docker-image

**Comment by parente** [comment]
I'm going to close this issue out as answered (and confirmed answered with a thumbs up 😄 ).
