### ISSUE TITLE
Update notebook stacks for 4.0

### ISSUE THREAD

**Issue by parente** [jupyter/docker-stacks#6]
1. [x] Get builds going with 3.2.1 first (Issue #2 ). 
2. [x]  Tag and/or branch as v3.2.1.
3. [x] Get 3.2.1 tag/branch build going on Docker Hub.
4. [x] Then get new container images on master and 4.0 branch working.

**Comment by rgbkrk** [comment]
`conda` should have the latest version of Jupyter/IPython 4.0 now. :smile:

**Comment by parente** [comment]
Ah, I was trying `conda install jupyter-notebook`. I see the package is just `notebook` (or `jupyter for everything).

**Comment by parente** [comment]
PR #14 is in. Getting 4.0 tag building on Docker Hub next.

**Comment by parente** [comment]
All 4.0 tags built on Docker Hub. Final step is to merge to master so that latest becomes the 4.0 image instead of 3.2.1. It's not a straight up merge, however, because all the Dockerfiles will need to point to the base `latest` image not the 4.0 image. Kind of a chicken and egg problem, but such is life with DH automated builds.

**Comment by rgbkrk** [comment]
Feel free to merge when you want to trigger those!

**Comment by parente** [comment]
Did last night. Everything is built and available on Docker Hub. Was doing a bit of testing before closing.

**Comment by rgbkrk** [comment]
Ok, cool!
