### ISSUE TITLE
SparkUI

### ISSUE THREAD

**Issue by drdwitte** [jupyter/docker-stacks#60]
Hi,

How to get to the SparkUI, i tried starting the docker image with the standard UI port open but it didn't work. Any help, appreciated, I would like to have a look at the Spark UI visualizations..

Regards, Dieter

**Comment by parente** [comment]
@alewitt I think you got this working. Can you post the essence of what you had to do here?

**Comment by alewitt** [comment]
Im assuming when you say standard you are talking about port 4040 (http://spark.apache.org/docs/latest/monitoring.html)

basically, just opening the additional ports should be enough to access the spark ui.

This is the command i am using to run docker, with spark monitoring visualization working. I also use a volume from my local directory, a password, and i change which directory the notebook uses as its home.
`docker run -d -p 8888:8888 -p 4040:4040 -e "PASSWORD=password" -v ~/localDir:/home/jovyan/work/DockerDir jupyter/all-spark-notebook start-notebook.sh --NotebookApp.notebook_dir=/home/jovyan/work/DockerDir/`

**Comment by drdwitte** [comment]
Thanks I might have tried 8080, my apologies. It's working properly, great work guys! My students will be very pleased using our docker stacks instead of doing manual installs!

**Comment by parente** [comment]
Great!

I'm going to leave this item open and use it to document this in the READMEs for the two spark stacks. It's a "good to know".

@alewitt if you want to send a PR to do it, I'll take it. If not, I'll get around to it.

**Comment by alewitt** [comment]
Yeah I'll take care if it! Happy to help! 


-------- Original message --------

**Comment by parente** [comment]
Much obliged @alewitt.
