### ISSUE TITLE
When can we upgrade to tensorflow 1.5?

### ISSUE THREAD

**Issue by dexterchan** [jupyter/docker-stacks#606]
I tried to change the tensorflow version to 1.5 in dockerfile....

When running, I catch error:
Seem there is compatibility issue on numpy
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xa

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
ImportError: numpy.core.multiarray failed to import

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
ImportError: numpy.core.umath failed to import

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
ImportError: numpy.core.umath failed to import

**Comment by parente** [comment]
The tensorflow 1.5 package on conda-forge has `numpy>=1.12` as a requirement so that should be installing the necessary version. Are you using conda to update tensorflow? If that is yielding a broken install, it's possible the tensorflow package definition on conda-forge needs fixing.

https://github.com/conda-forge/tensorflow-feedstock/blob/master/recipe/meta.yaml#L28

**Comment by parente** [comment]
@dexterchan Just to clarify, are you saying it works now when you install with conda? If so, would you like to submit a pull request updating the version in the tensorflow-notebook Dockerfile so everyone benefits?

**Comment by dexterchan** [comment]
I have created pull request:

update higher version of tensorflow and keras 
#629
