### ISSUE TITLE
GPU

### ISSUE THREAD

**Issue by RaRam** [jupyter/docker-stacks#607]
Hello,

is there a docker file for tensorflow with GPU support?

Best!

**Comment by parente** [comment]
@RaRam there isn't. The past discussion and decision on this topic is here: https://github.com/jupyter/docker-stacks/issues/516#issuecomment-363633558

**Comment by parente** [comment]
I'm going to close this issue out as resolved by the comment in the prior issue. 

@RaRam if you looked around for an answer to your question and couldn't find it before opening this issue, please let me know where you looked. I'm always looking for better ways to document these decisions. Searching through closed issues to find them is not ideal.
