### ISSUE TITLE
Following Debian upstream in adopting ffmeg over libav-tools

### ISSUE THREAD

**Issue by taqtiqa-mark** [jupyter/docker-stacks#611]
Hi! Thanks for all the effort making Jupyter's docker-stacks images.

libav-tools (jupyter/scipy-notebook)

I'm porting the Jupyter stacks to Apline Linux containers.  As part of that, while building  `jupyter/scipy-notebook` I discovered libav is not available on Alpine Linux, but ffmeg is.  The libav team was not very responsive/proactive about the patch to try make it work, and things seem to have stalled.  I don't see any evidence to expect this to change.

On further digging I discovered that, unfortunately, there has been some ping-pong in Debian around libav vs ffmeg. 
 Having dropped ffmeg at one point they seem now to have now dropped libav and picked ffmpeg back up. 
Previously this affected this project per issue #90, where ffmpeg was not available in a ubuntu distribution.  
Some detail behind the change is set out in a [LWN article](https://lwn.net/Articles/650816/).  It seems the reasons (security) for switching back to ffmeg are not trivial.  The [announcement is here](https://lwn.net/Articles/650495/)

Any chance you'd consider following upstream and using ffmpeg in place of libav-tools?  

If not that is fine, I will just need to include a notice in the README.md.

**Comment by parente** [comment]
> Previously this affected this project per issue #90, where ffmpeg was not available in a ubuntu distribution.

I believe the images here were based on Debian Jessie at the time. Now they derive from Ubuntu 16.04, so switching to ffmpeg shouldn't be all that difficult. If you'd like to submit a PR with the change, along with a notebook showing that matplotlib animation still works properly, I think we can merge it.

**Comment by jakirkham** [comment]
There’s also `ffmpeg` in `conda-forge`, which could be used to this end.

**Comment by taqtiqa-mark** [comment]
Unfortunately, I'm going to have to leave this to someone else.  The Alpine build is taking all my spare cycles.

I'll use ffmpeg with the hope/expectation that at some point the switch from libav-tools will be made.

Happy for you to close this or leave it open.  As you wish.

**Comment by parente** [comment]
No problem, @taqtiqa-mark. Please leave the issue open.

**Comment by jakirkham** [comment]
If it's any help, I use `ffmpeg` from `conda-forge` to generate videos either with `matplotlib` or `moviepy` (primarily on our Linux-based cluster). Don't know what bar you had in mind for testing, but maybe that provides some assurance that this does work.

**Comment by Bidek56** [comment]
I have attempted to build the stack using Ubuntu 18.04 but Mesos is not available for 18.04 yet.
I should be available in few weeks according to the forum.

**Comment by parente** [comment]
This was closed by #641. The images now include ffmpeg instead of libav-tools.
