### ISSUE TITLE
Reduce image sizes

### ISSUE THREAD

**Issue by nspaeth** [jupyter/docker-stacks#62]
The minimal-notebook installs texlive, which pulls in x11 for a hefty increase in image size. It would be nice to install a version that doesn't require those extra dependencies, or to manually remove them after install, if that won't break anything.

**Comment by parente** [comment]
I've thought about this. On the one hand, minimal notebook is the minimal image that enables *all* of the notebook server functions, including the Download As menu items. Without texlive, some of those don't work (according to my experiments at least). On the other hand, I recognize that getting a minimal image that enables all-but-notebook-conversion might be desirable for some use cases.

**Comment by nspaeth** [comment]
Sorry, I think I misspoke. I assumed that texlive was necessary for something, so what I intended to say was to install a version of texlive that doesn't require x11 (ie, not compiled with support for it).

**Comment by parente** [comment]
Ah. I'm not aware of a different version that doesn't have the x11 bits, but I'm definitely open to finding one.

**Comment by nspaeth** [comment]
Unfortunately I think it might be somewhat involved. The following stackexchange questions give some possibilities, but I haven't had a chance to try any of it yet:

http://tex.stackexchange.com/questions/1092/how-to-install-vanilla-texlive-on-debian-or-ubuntu
(which links to: http://www.tug.org/texlive/debian.html )
http://askubuntu.com/questions/74523/how-can-i-install-a-package-without-installing-some-dependencies

**Comment by parente** [comment]
I'm playing a bit with https://github.com/jwilder/docker-squash against the minimal-notebook to see if/how it helps.

**Comment by parente** [comment]
Comparisons of before/after squash:

```
$ docker images
jupyter/minimal-notebook                          latest-squashed     56c057ff3066        About an hour ago   1.777 GB
jupyter/minimal-notebook                          latest              bb9372ddc21e        3 weeks ago         2.162 GB
```

```
$ docker history jupyter/minimal-notebook:latest
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
bb9372ddc21e        3 weeks ago         /bin/sh -c chown -R $NB_USER:users /home/$NB_   1.353 kB
59be73705b0e        3 weeks ago         /bin/sh -c #(nop) COPY file:92ab115ce14297458   1.353 kB
ebb4a093127c        3 weeks ago         /bin/sh -c #(nop) COPY file:2b820ac933e1e163a   398 B
7074a66d320d        4 weeks ago         /bin/sh -c #(nop) CMD ["start-notebook.sh"]     0 B
c3c43ba6d813        4 weeks ago         /bin/sh -c #(nop) ENTRYPOINT &{["tini" "--"]}   0 B
c7d2036ab4ac        4 weeks ago         /bin/sh -c #(nop) WORKDIR /home/jovyan/work     0 B
d72436f026b9        4 weeks ago         /bin/sh -c #(nop) EXPOSE 8888/tcp               0 B
d9345d9f94bd        4 weeks ago         /bin/sh -c useradd -m -s /bin/bash -N -u $NB_   349.5 MB
2c1885f235fe        4 weeks ago         /bin/sh -c conda install --yes     'notebook=   59.28 MB
d50ac9f94f43        4 weeks ago         /bin/sh -c mkdir -p $CONDA_DIR &&     echo ex   325 MB
e0abdc437766        4 weeks ago         /bin/sh -c #(nop) ENV NB_UID=1000               0 B
82adda8ddef8        4 weeks ago         /bin/sh -c #(nop) ENV NB_USER=jovyan            0 B
7c829fac917f        4 weeks ago         /bin/sh -c #(nop) ENV SHELL=/bin/bash           0 B
af1211470049        4 weeks ago         /bin/sh -c #(nop) ENV PATH=/opt/conda/bin:/us   0 B
b73b6312da8d        4 weeks ago         /bin/sh -c #(nop) ENV CONDA_DIR=/opt/conda      0 B
bd138b8b5cd7        4 weeks ago         /bin/sh -c wget --quiet https://github.com/kr   14.58 kB
68cfe93759e2        4 weeks ago         /bin/sh -c apt-get update && apt-get install    1.303 GB
de8a3f4bbb91        5 weeks ago         /bin/sh -c #(nop) ENV DEBIAN_FRONTEND=noninte   0 B
53224307697d        5 weeks ago         /bin/sh -c #(nop) USER [root]                   0 B
ec31c18c930e        5 weeks ago         /bin/sh -c #(nop) MAINTAINER Jupyter Project    0 B
58016a5acc80        5 weeks ago         /bin/sh -c #(nop) CMD ["/bin/bash"]             0 B
e2a4fb18da48        5 weeks ago         /bin/sh -c #(nop) ADD file:fd73312d29edb04f9c   125.2 MB
```

```
docker history jupyter/minimal-notebook:latest-squashed
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
56c057ff3066        About an hour ago   /bin/sh -c #(nop) CMD ["start-notebook.sh"]     0 B
97e14f5cb585        About an hour ago   /bin/sh -c #(nop) ENTRYPOINT &{["tini" "--"]}   0 B
d92da82eb9ec        About an hour ago   /bin/sh -c #(nop) WORKDIR /home/jovyan/work     0 B
e2770ee10d44        About an hour ago   /bin/sh -c #(nop) EXPOSE 8888/tcp               0 B
769fc6b30e07        About an hour ago   /bin/sh -c #(nop) ENV NB_UID=1000               0 B
abde9c831653        About an hour ago   /bin/sh -c #(nop) ENV NB_USER=jovyan            0 B
f515ac368ddd        About an hour ago   /bin/sh -c #(nop) ENV SHELL=/bin/bash           0 B
ed59459a396a        About an hour ago   /bin/sh -c #(nop) ENV PATH=/opt/conda/bin:/us   0 B
c3f900352bd1        About an hour ago   /bin/sh -c #(nop) ENV CONDA_DIR=/opt/conda      0 B
4ac2998e21fa        About an hour ago   /bin/sh -c #(nop) ENV DEBIAN_FRONTEND=noninte   0 B
30c457541f25        About an hour ago   /bin/sh -c #(nop) USER [root]                   0 B
c232070bf750        About an hour ago   /bin/sh -c #(nop) MAINTAINER Jupyter Project    0 B
92e5719aedeb        About an hour ago   /bin/sh -c #(nop) CMD ["/bin/bash"]             0 B
ca9bf6004eba        About an hour ago   /bin/sh -c #(squash) from e2a4fb18da48          1.652 GB            squashed w/ docker-squash
e2a4fb18da48        5 weeks ago         /bin/sh -c #(nop) ADD file:fd73312d29edb04f9c   125.2 MB
```

**Comment by jakirkham** [comment]
There are certainly some more things that can be done on this front that don't involve removing functionality, but will reduce size. Was just running `jupyter/datascience-notebook` and was able to clear ~0.5GB from conda alone. Given that image is ~5GB currently that is a ~10% reduction. Not huge, but not unnoticed. Likely there are a few more places this can be done. Will give that a go and submit a PR. Thinking that lower image sizes may help reduce frequency of push failures, as well.

**Comment by jakirkham** [comment]
After cleaning the conda install detritus, it looks like the image size of the `jupyter/minimal-notebook` is `1.841 GB`, which gets pretty close to the `1.777 GB` that @parente cited some months back. There are probably some more tricks that can be used to clean up some apt-get stuff for some small savings `~10 MB`. If you have some thoughts as to how to get rid of X11 without making the build to complex, we would certainly appreciate your contributions, @nspaeth. Otherwise, I'm leaning towards marking this as resolved.

**Comment by jakirkham** [comment]
Added an additional clean of apt-get to get the size down to `1.831 GB`. Further improvements aren't yielding as significant of returns. It appears like we are reaching the smallest sizes we can get here with a reasonable amount of effort. Also, it appears the original request of removing X11 cannot be easily achieved (if at all). While additional improvements to the size are welcomed, I am going to mark this as solved.
