### ISSUE TITLE
Architecture: Make 'spark' container: spark, hadoop and cluster manager agnostic

### ISSUE THREAD

**Issue by taqtiqa-mark** [jupyter/docker-stacks#626]
Hi! Thanks for all the work that has gone into creating Jupyter's docker-stacks images.

I'm wondering if you are open to breaking out spark into a separate container, rather than the current monolithic container. By "open" I mean willing to work in that direction, i.e. accept pull requests etc.
That means I don't propose this issue resolve all the implementation issues/details.

Some advantages for this are:
- Cluster manager agnostic : Currently tied to mesos, and some environments don't have this on "approved"/licensed technology lists
- Hadoop agnostic: Currently tied to specific hapdoop versions, while spark itself is more flexible.
- Container sizes reduced considerably
- Retire pyspark and maintain only the all-spark container
- Support multiple spark client library versions in one container.  That is configure client library versions at container runtime - use a launch script parameter, e.g. `spark=230`, `spark=210`, etc to set env variables, linked files etc.

Some disadvantages for this are:
- Identify a robust spark container that new users are directed to as an easy default, e.g. [BDE/docker-spark](https://github.com/big-data-europe/docker-spark)
- Spark container needs to be launched, but users can be directed to [such resources](https://grzegorzgajda.gitbooks.io/spark-examples/content/basics/docker.html)
- Example R and Py files showing connection parameters for different cluster managers

Won't go into more detail until there is interest in taking this approach.

**Comment by parente** [comment]
Hi @taqtiqa-mark 

> I'm wondering if you are open to breaking out spark into a separate container, rather than the current monolithic container.

I think I need a bit more information to understand whether we should update all-spark-notebook or manage a set of Spark related images outside this repo. I've got a couple questions about your advantages and disadvantage that should help.

> Identify a robust spark container that new users are directed to as an easy default, e.g. BDE/docker-spark

Would the new image(s) you're proposing derive from `jupyter/base-notebook` or another docker-spark image like `BDE/docker-spark`? I'd like for all the images in this repository to stay within the inheritance tree of `jupyter/base-notebook` for consistency. That said, I completely understand if you're proposing one or more new images that start from a Spark-specific base and add Jupyter instead of the other way around. I just think those images deserve their own repository for clarity.

> Support multiple spark client library versions in one container. That is configure client library versions at container runtime - use a launch script parameter, e.g. spark=230, spark=210, etc to set env variables, linked files etc.
> Container sizes reduced considerably

I'm probably misunderstanding what "multiple spark client library versions in one container" means here, since I'd expect that change to increase the container size rather than decrease. Can you explain what I'm missing?

**Comment by taqtiqa-mark** [comment]
Apologies for the delay - sidetracked by life.

> I think I need a bit more information to understand whether we should update all-spark-notebook or manage a set of Spark related images outside this repo.

I don't think there is a requirement/need to manage spark related images for the `all-spark` notebook to be able to work.  Spark does make backward compatibility commitments in the minor version number series, so the spark version the container relates to is less important - Notes in `Readme.md` should suffice. 
An issue **might arise** with some client libraries that don't make backward compatibility commitments (these are issues defects that need to be raised with those libraries). For example Scala users are largely immune and assured that things "just-work(TM)", if they don't it's a defect upstream, similarly for Python and R client libraries.
I think you'd just need to indicate that the container client libraries (SparklyR, etc) relate to Spark version(s) `X.Y.*` and **possibly** earlier.  Leave compatibility claims to the upstream client library authors.

Which Spark cluster manager the user has in place is out of scope.  [These](https://github.com/jupyter/docker-stacks/issues/515) [questions](https://github.com/jupyter/docker-stacks/issues/369) become moot. Also there is no longer the need to [rebuild the container to use YARN](https://github.com/jupyter/docker-stacks/wiki/Docker-recipes#use-jupyterall-spark-notebooks-with-an-existing-sparkyarn-cluster), etc.
Which version of Hadoop, etc. the user has compiled Spark against is also out of scope.

All this this should expand the potential user base for Jupyter containers?

Obviously the Jupyter containers should be tested against something and the project might want to maintain your own spark container for that purpose?  I'd advocate just using one of the several spark containers that are around.  But this is really a CI scripting/setup issue.  Jupyter configuration to connect to Spark should be reasonably common.
Are there known cases where the notebook content needs to be changed to use a different spark/hadoop/MC - that is, beyond using `conf.setMaster(...)` on Python or `sparkR.session(...)` on R?
If so we could distribute example notebooks with  required boilerplate code if there are gotchas.

> Would the new image(s) you're proposing derive from jupyter/base-notebook or another docker-spark image like BDE/docker-spark?

Apologies for the ambiguity. I'm trying *not to* propose new containers.  I *am trying* to reduce their complexity and size or retire some (pyspark) to relieve the maintenance burden.  
I would also like to increase the use cases/environments where the jupyter-4-spark container can be deployed and 'just-work(TM)'.  But I am acknowledging that if you wanted/needed to you could maintain a separate spark container.

> I'd like for all the images in this repository to stay within the inheritance tree of jupyter/base-notebook for consistency.

Agreed.  I don't propose to change that.  I just see MC/Spark/Hadoop as orthogonal to my Jupyter notebooks (subject to the above caveat that some client libs **might** not be backward compatible within a minor series).  All a Jupyter container users need know is the Spark version the client libraries relate to.

Apologies for the wall of text.  My 2c.

**Comment by parente** [comment]
Parroting back to check my understanding: the proposal here is to treat the all-spark-notebook image as a Spark client-only container by removing mesos, hadoop, etc. libraries and making it configurable/pluggable to work with the hadoop version and cluster manager of the user's choice.

If the above is more or less correct, it sounds good to me. I admit my understanding of the detail is fuzzy, but incremental PRs moving all-spark-notebook in the desired direction will start to clear things up I'm sure.

**Comment by taqtiqa-mark** [comment]
> the proposal here is to treat the all-spark-notebook image as a Spark client-only container by removing mesos, hadoop, etc. libraries and making it configurable/pluggable to work with the hadoop version and cluster manager of the user's choice.

Correct.

No longer should you need to fork and rebuild the [`all-spark-notebook` container](http://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html#use-jupyter-all-spark-notebooks-with-an-existing-spark-yarn-cluster) to use a different cluster manager

Instead the user should be able to adjust their PySpark/SparklyR notebook to the equivalent of the following:

**Nomad**
````
$ spark-submit \
    --class org.apache.spark.examples.SparkPi \
    --master nomad \
    --deploy-mode cluster \
    --conf spark.nomad.sparkDistribution=https://s3.amazonaws.com/nomad-spark/spark-2.1.0-bin-nomad.tgz \
    lib/spark-examples*.jar
````

**YARN**
````
./bin/spark-submit \ 
    --class org.apache.spark.examples.SparkPi \
    --master yarn-cluster \
    --conf spark.yarn.jar=hdfs:///spark-assembly-1.5.0-hadoop2.6.0.jar \
    ...
````

**Standalone Spark cluster**
````
./bin/spark-submit \
  --class org.apache.spark.examples.SparkPi \
  --master spark://207.184.161.138:7077 \
  ...
````

etc.

**Comment by romainx** [comment]
Hello @taqtiqa-mark 

Mesos support has been recently removed #911. I've read your suggestions and they are very interesting. If you have any update / additional suggestions do not hesitate to post them here.

Many thanks

**Comment by romainx** [comment]
Hello,

With the merge of the PR #1145 it's now possible to build an image with a different version of Spark. This [part of the documentation](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/specifics.html#build-an-image-with-a-different-version-of-spark) explains how to do it.

I propose to close this issue soon if you agree.

Best.

**Comment by romainx** [comment]
Hello,

I think we have done most of the job and the remaining activity is described in another issue #1163.
@taqtiqa-mark if you don't mind I'm closing this issue.
Thanks again for sharing your relevant suggestions.

Best.
