### ISSUE TITLE
jupyter_notebook_config.py not loaded in minimal-notebook image

### ISSUE THREAD

**Issue by jdfreder** [jupyter/docker-stacks#63]
This may be a problem with the other images too, but I'm only using the minimal image.

`jupyter_notebook_config.py` is not getting loaded by the notebook because it is being installed to `/users/jovyan/.jupyter/` and the server is being launched using the root account.  The server expects the config to be in `/root/.jupyter/`.  

Side effects of the config not being loaded include broken password and encryption features.  The caveman method I used to test this was to add a print statement to the config and use `docker logs` to look at the output of the container.

cc: @rgbkrk who I chatted with about this
and cc: @parente , who I think is the man in control of this

**Comment by parente** [comment]
@jdfreder can you put how you're running the container? The ENTRYPOINT in minimal points to tini (tiny init process for dealing with child processes) and the CMD points to `start-notebook.sh` which does a su to `jovyan`. I just ran the latest here and confirmed the notebook is running as `jovyan` and using `/home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret` and `/home/jovyan/.jupyter` directories when starting with:

`docker run -it --rm -P jupyter/minimal-notebook`

**Comment by jdfreder** [comment]
I'm running it with tmpnb:

- open docker quick term
- `make build` in docker-stacks repo
- run:
```bash
docker run --net=host -d -e CONFIGPROXY_AUTH_TOKEN=$TOKEN \
           -v /var/run/docker.sock:/docker.sock \
           jupyter/tmpnb python orchestrate.py --image='jupyter/minimal-notebook' --command="ipython notebook --NotebookApp.base_url={base_path} --ip=0.0.0.0 --port {port}"
```

**Comment by parente** [comment]
Probably does make sense to put it here somewhere. I'll keep this open until we do.

**Comment by parente** [comment]
Added a tips / gotchas section in the main README and a bullet in that section directing readers to the details in the individual stack READMEs for more information about the consequences of replacing the `start-notebook.sh` command.

**Comment by jdfreder** [comment]
Thanks Peter, I also added a note to tmpnb'so readme
