### ISSUE TITLE
Starting notebook on different port ??

### ISSUE THREAD

**Issue by tgamal** [jupyter/docker-stacks#630]
I am using the `jupyter/tensorflow-notebook` and I would like to open the tensorflow-notebook container on another port rather than 8888. In this case it is 8889 so this is the command I use

`docker run -it --rm -p 8889:8888 --network none jupyter/tensorflow-notebook start.sh jupyter notebook --port=8889`

the notebook start successfully but when I visit http://localhost:8889  I get "Unable to connect error". I tried to get port 8889 to bypass the firewall (sudo ufw allow 8889) but it did not help

When I try to run the same command but using the default 8888 port, it works good:
 `docker run -it --rm -p 8888:8888 --network none jupyter/tensorflow-notebook start.sh jupyter notebook --port=8888`...

Please advise.. I need to spawn multiple notebook containers on different ports

**Comment by parente** [comment]
Try:

```
docker run -it --rm -p 8889:8888 --network none jupyter/tensorflow-notebook
```

The first port in `-p` is the external facing docker port, the one you visit on local host. The second port after the colon is the one used inside the docker container which you do not need to change.

**Comment by parente** [comment]
This issue has been inactive for a while now. I'm going to close it out. Feel free to open another if you have further questions.

**Comment by kapsner** [comment]
I have solved this for the [gpu-jupyter repo](https://github.com/iot-salzburg/gpu-jupyter), which is building upon docker-stacks.

You could provide an updated `jupyter_notebook_config.py` script, where you change the `c.NotebookApp.port` to `c.NotebookApp.port = int(os.getenv("JPY_PORT"))`.

https://github.com/kapsner/gpu-jupyter/blob/own_image/.build/jupyter_notebook_config.py#L12

To take affect in the building process, you further need to comment out the line that copies this file from docker-stacks:
https://github.com/kapsner/gpu-jupyter/blob/own_image/generate-Dockerfile.sh#L72

Then, you can provide the environment variable `JPY_PORT` when deploying the container.
