### ISSUE TITLE
Can't open Jupyter Notebook from Docker

### ISSUE THREAD

**Issue by ozaparth2803** [jupyter/docker-stacks#634]
I have Windows 10 Home version. Due to this, I downloaded the older Docker toolbox from following link:

`https://docs.docker.com/toolbox/overview/#next-steps
`I run:

`$ docker run -it --rm -p 8888:8888 jupyter/pyspark-notebook
`
I get the output as:
Copy/paste this URL into your browser when you connect for the first time,
to log in with a token:
`http://localhost:8888/?token=****030452*******d6a
`
When I paste this into the browser I get the following error:

**This site can’t be reached**

Can anyone help me fix this?

**Comment by jakirkham** [comment]
How was it solved?

**Comment by ozaparth2803** [comment]
There would be a line on top of Docker terminal.
"docker is configured to use default machine with IP xxxx.xx.xxx.
So you can replace localhost with that IP.
