### ISSUE TITLE
Question about external package in docker stack for custom recipe

### ISSUE THREAD

**Issue by urania277** [jupyter/docker-stacks#640]
Hi all! 

I am rather new to the Jupyter Docker Stacks but I think they're a great idea, and I'm looking to use them a lot more for research and teaching. If this works out, a few more high energy physicists may be encouraged to use a similar recipe. 

I don't know if this question is suitable for this forum (it is not a notebook issue - all I wanted to do there works), but I'll try anyway as it is a question on customizing one of the contributed recipes. 

I want to add a new package to the jupyter/data-science notebook. This package is CERN ROOT:

[https://root.cern.ch/homepage](https://root.cern.ch/homepage)

I am roughly following the contributed recipe [here](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html) (substituting pip for conda). 

My Dockerfile looks like this: 

```
# Start from a core stack version
FROM jupyter/datascience-notebook:latest
# Install in the default python3 environment
RUN conda update -n base conda
RUN conda config --add channels https://conda.anaconda.org/NLeSC
RUN conda install root=6
```

I then build it:

```
docker build --rm -t jupyter/my-datascience-notebook .
[snip]
Successfully tagged jupyter/my-datascience-notebook:latest
```

So far so good. So I run the notebook:

`docker run -p 8888:8888 jupyter/my-datascience-notebook:latest`

When I open a console, ROOT refuses to start normally because it doesn't find a X server (expected), but it's a good sign as it means the system finds it where I expect it. 

```
jovyan@53f90230d0a3:~$root
root: can't figure out DISPLAY, set it manually
In case you run a remote ssh session, restart your ssh session with:
=========>  ssh -Y
```

The problem is now that the ROOT modules are not seen by the iPython modules when I start jupyter (whether plain or lab). E.g. in the ipython console

`jovyan@53f90230d0a3:~$ python
Python 3.6.3 |Anaconda, Inc.| (default, Nov  9 2017, 00:19:18)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
 from ROOT import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ROOT'`

I suspect it's a problem with PYTHONPATHs and the like. I can't run the magical script that usually does all of that for me, and I have an obscure error that is probably conda's problem:

```
jovyan@53f90230d0a3:~$ source /opt/conda/bin/thisroot.sh
bash: /opt/conda/lib/libtinfo.so.5: no version information available (required by bash)

```
but I *think* the libraries I need are already in the right place:

```
jovyan@53f90230d0a3:~$ echo $LD_LIBRARY_PATH
/opt/conda/lib
jovyan@53f90230d0a3:~$ echo $PYTHONPATH
/opt/conda/lib
jovyan@53f90230d0a3:~$ echo $ROOTSYS
/opt/conda/
```

As a final note: I have been able to install ROOT with these conda package on my Mac OSX laptop (where I encountered horrible library conflicts upon running), on a linux machine (where everything worked ok) and from inside the Docker image, but in the last case the notebook is also oblivious of ROOT's existence. 

Thanks a lot for any input you may have!
Caterina

**Comment by parente** [comment]
If I fire up a container and run `conda install root`, everything proceeds smoothly until the very last step of the install where conda logs:

```
IsADirectoryError(21, 'Is a directory')
```

The conda command appears to exit with a success. After that, if I run `conda list | grep root` I find that root did not finish installing. If I run `conda install root` again, conda starts the install over again confirming it does not think it finished correctly the first time.

Do you see a similar log line in your docker build logs? If I had to guess, I suspect there's something wrong with root conda package or conda's handling of it.

**Comment by urania277** [comment]
Hi Peter, 

thanks for the answer! I saw the IsADirectoryError on screen (*) in one instance before updating conda, but not after.  I tried twice, and we may be looking at what is discussed here:

https://github.com/conda/conda/issues/6811

It came right after the installation of one of the other packages (not always the same) rather than the installation of ROOT. The fact that it disappeared after updating conda may not necessarily mean that the update fixed it though, maybe it's the fact that I run it multiple times over...

Caterina

(*) I was expecting a log here but it's empty: ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/log/d‌​ocker.log
am I looking in the wrong place?

**Comment by parente** [comment]
FWIW, I tried installing root in fresh conda 4.5.4 environment on a Ubuntu 14.04 Linux box outside the docker container and wound up with the same error running the `source thisroot.sh`:

```
conda create -n root-test python=3.6
source activate root-test
conda install root=6 -c https://conda.anaconda.org/NLeSC
cd $CONDA_PREFIX
. ./bin/thisroot.sh
```

yields

```
bash: /home/pparente/miniconda/envs/root-test/lib/libtinfo.so.5: no version information available (required by bash)
```

**Comment by parente** [comment]
This issue has been idle for some time now and so I'm going to close it. If someone has figured out how to use ROOT via the conda package, a PR updating the recipes page in the doc with instructions would be welcome.
