### ISSUE TITLE
Haskell Recipe

### ISSUE THREAD

**Issue by Bamieh** [jupyter/docker-stacks#643]
First I want to thank you for the docker stack! I love this project and i have been using it for several notebooks.

I want to implement a stack recipe for haskell, does anyone have an already working recipe for haskell that I can use as a starting point? Any maybe submit a PR for the recipe after finalizing it?

I can start working on it based on other docker jupyter/haskell images, but i dont want to start from scratch if that is not needed,

Cheers!

**Comment by parente** [comment]
Hi @Bamieh. Thanks for your interest in creating a new stack. We're currently working on documentation (https://jupyter-docker-stacks.readthedocs.io/en/latest/contributing/stacks.html) and a cookiecutter project (https://github.com/jupyter/cookiecutter-docker-stacks) for members of the community to maintain docker stack images in their own github repositories and [have them listed here](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#community-stacks).

It's definitely a work in progress, but it would be great to have someone pilot the approach as we flesh it out.

**Comment by Bamieh** [comment]
@parente I'd love to contribute! I'll read the links and start from there.

**Comment by Bamieh** [comment]
@parente I am sure this issue is not the right place for this, but here is my thoughts hoping you'll provide feedback and guide this conversation elsewhere.

So cookiecutter is basically a boilerplate to help create docker images for jupyter stack. It is nice but the problem is that if i want to use multiple stacks at once, I have to create yet another dockerfile and extend it to have multiple stacks (also a limitation in the current implementation of docker-stacks). I was hoping for something like this instead:


```Dockerfile
FROM jupyter/minimal-notebook
RUN extend_stack Bamieh/jupyter-reveal-stack
RUN extend_stack jupyter/jupyter-r-stack
```

the `extend_stack` command is can be provided from the base image or installed separately, and it accepts a github repo URL which contains a bash script to extend the stack

for example, `Bamieh/jupyter-reveal` would contain a bash file with the following:

```
conda install -c damianavila82 rise
```

the tool `extend_stack` can also take some arguments like specifying branch/commit number, or changing github to something else, etc. This tool can be also used by both the community stacks and the current jupyter hosted stacks.

**Comment by parente** [comment]
> the problem is that if i want to use multiple stacks at once, I have to create yet another dockerfile and extend it to have multiple stacks

Yep. The single inheritance model of Dockerfiles does have its limitations.

> the extend_stack command is can be provided from the base image or installed separately, and it accepts a github repo URL which contains a bash script to extend the stack

This sounds like a nifty tool for docker in general. I'm not sure how one would go about merging multiple stacks at docker build time like depicted in the examples. If you have an idea of how to do it, it sounds like a great mini project that we could link from the documentation here.

**Comment by jakirkham** [comment]
How does this compare to [multistage builds]( https://docs.docker.com/develop/develop-images/multistage-build/#use-an-external-image-as-a-stage )?

**Comment by parente** [comment]
If I understand correctly, the proposal above is meant to include all of the layers from the referenced images whereas `COPY --from=<some image> some-path some-destination-path` only copies a file or directory from the image.

**Comment by jakirkham** [comment]
How would it resolve merge conflicts?

**Comment by parente** [comment]
This issue has been idle for quite some time now and so I'm going to close it. If someone does work up a Haskell image based on the instructions in the documentation or repo2docker, I'll gladly review a PR that adds a link to it in the documentation here.
