### ISSUE TITLE
Rebuild jupyter/all-spark-notebook to include spark kernel fixes

### ISSUE THREAD

**Issue by wellecks** [jupyter/docker-stacks#65]
The `jupyter/all-spark-notebook` image needs to be rebuilt and pushed after ibm-et/spark-kernel#203 is merged

The kernel PR contains a fix that's necessary for jupyter declarative widgets, a project that uses `jupyter/all-spark-notebook`, to move to `jupyter 4` (see [this issue](https://github.com/jupyter-incubator/declarativewidgets/issues/67))

**Comment by wellecks** [comment]
[ibm-et/spark-kernel#203](https://github.com/ibm-et/spark-kernel/pull/203) has been merged

**Comment by parente** [comment]
Test build went fine. Will be a bit for real build to complete and new version to land on Docker Hub.

**Comment by parente** [comment]
Latest and tag dbb9c7b50531 now on Docker Hub to match master HEAD.
