### ISSUE TITLE
Does it make sense to parameterize NB_USER=jovyan using Docker ARG ?

### ISSUE THREAD

**Issue by wutianchen** [jupyter/docker-stacks#660]
It is annoying to see jovyan everywhere. Does it make sense to parameterize NB_USER in base-notebook with ARG, so it can be customized ?

I tried

```
c.Dockerspawner.environment = {
'NB_USER': 'my-user'
}
```

it changes the NB_USER but not other environment variables based on NB_USER

**Comment by parente** [comment]
I think it's fine to expose NB_USER as a build-time overridable ARG with a default of `jovyan` as long as its value is also set as an ENV of the same name so that it's available at runtime as before.

**Comment by parente** [comment]
I believe this was addressed in #720.
