### ISSUE TITLE
About switch to Ubuntu bionic. Mesos Spark support is now broken

### ISSUE THREAD

**Issue by asyd** [jupyter/docker-stacks#663]
**What docker image you are using?**

Example: `jupyter/pyspark-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

Example: `docker run -p 8888:8888 jupyter/pyspark-notebook:latest`

**What steps do you take once the container is running to reproduce the issue?**

Example:

1. Visit http://localhost:8889
2. Start an python notebook
3. Run a notebook that use a Mesos to run spark executors

**What do you expect to happen?**

Well, I expect that work:)

**What actually happens?**

spark-submit failed, with

```
Py4JJavaError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext.
: java.lang.UnsatisfiedLinkError: /usr/lib/libmesos-1.2.3.so: libevent_openssl-2.0.so.5: cannot open shared object file: No such file or directory
```

After digging a bit, I find the following issue:

```
docker exec -it <contaienr name> bash
jovyan@cdcc15e1ffe0:~$ ldd /usr/local/lib/libmesos.so  | grep 'not found'
        libevent_openssl-2.0.so.5 => not found
        libevent_pthreads-2.0.so.5 => not found
        libevent-2.0.so.5 => not found

jovyan@cdcc15e1ffe0:~$ dpkg -l mesos

ii  mesos                                          1.2.3-2.0.1                  amd64                        Cluster resource manager with efficient resource isolation

```

The issue is related to the ubuntu bump version. libevent-* packages are now in version` 2.1.8-stable-4build1`, so that explain the link failed (mesos expect a `2.0.x` version). Since there is no packages available for mesos on mesosphere, I guess a custom build of mesos is required. 

Regarding your feedbacks I may try to help :)

Thanks you

**Comment by Bidek56** [comment]
It's a know issue because of [MESOS-8921](https://issues.apache.org/jira/browse/MESOS-8921)
I have pointed it out in the [PR641](https://github.com/jupyter/docker-stacks/pull/641) but @parente merged the PR anyway, so it will be broken till MESOS fixes it and we do another PR.
I would suggest pulling an older image from Docker Hub which contains Ubuntu 16.04, before PR641

**Comment by asyd** [comment]
Ok, thanks for the feedback.

**Comment by Bidek56** [comment]
I would keep the issue open so we can keep track of it and fix it when Mesos fixes [MESOS-8921](https://issues.apache.org/jira/browse/MESOS-8921)

**Comment by asyd** [comment]
ok! sure

**Comment by parente** [comment]
FYI: There's a proposal on the table to make the spark images more cluster manager agnostic in #626 . Removing Mesos is a first step proposed: https://github.com/jupyter/docker-stacks/pull/641#issuecomment-396018306

**Comment by ezreal92170** [comment]
It seems that MESOS-8921 is resolved. But I think this is not solved in pyspark and all-spark notebooks. 
Will you deprecate mesos support or try to solve it?

**Comment by parente** [comment]
I think we should move the few Dockerfile lines showing how to setup Mesos support to a recipe in the documentation, and continue to grow recipes for running Spark on numerous fabrics (mesos, local, yarn, k8s, ...) or more concrete community stacks that target specific use cases.

**Comment by ezreal92170** [comment]
I am still using an older image from Docker Hub which contains Ubuntu 16.04, before PR641.
I would be perfect if a recipe could exist

**Comment by parente** [comment]
I can make an attempt at the recipe based on what’s in the Dockerfile today but I have no mesos cluster to truly test it against.

**Comment by doctapp** [comment]
@parente I can test the recipe.

**Comment by ezreal92170** [comment]
i can test the recipe too

**Comment by parente** [comment]
OK. I'll see if I can adapt the mesos install when I get some time. If someone else wants to give it a go, by all means please do.

**Comment by aidan-plenert-macdonald** [comment]
Just so you are aware, you've been generating broken images for 12-18 months. I count ~120 broken images (spot checking) 2.4Tb of images.

**Comment by fcomte** [comment]
is mesos supported or not ? is a recipe was done ?
pyspark-notebook still containing mesos lib installation but this is not working...
So this image will become cluster agnostic or not ?

**Comment by romainx** [comment]
The mesos support has been recently removed from `all-spark-notebook` #911. The image is now cluster agnostic. If a recipe is needed for mesos, I think we should address it in a different issue.

Best.

**Comment by romainx** [comment]
I'm closing this issue because mesos support has been droped.
