### ISSUE TITLE
Adding a spellchecker

### ISSUE THREAD

**Issue by avitase** [jupyter/docker-stacks#675]
could you add one of the spellchecker plugins?

**Comment by parente** [comment]
This issue is old, but I'd like to leave it open as a good starting point for someone who wants to contribute here.

**Comment by mathbunnyru** [comment]
There is a spellchecker for jupyterlab and the documentation is quite good about installing it, so I'm closing this issue.
https://github.com/jupyterlab-contrib/spellchecker
