### ISSUE TITLE
add rpy2 in datascience-notebook

### ISSUE THREAD

**Issue by cboettig** [jupyter/docker-stacks#68]
Really enjoying these images, thanks for the great work.  Would you consider adding `rpy2` to the datascience-notebook image?  Given that it has R and python engines already, it would be nice to be able to mix and match in a notebook.

**Comment by parente** [comment]
I think it makes sense in the datascience image.

**Comment by parente** [comment]
Adding rpy2=2.7* also requires r-devtools=1.9*, r-tidyr=0.3*, and r-rmarkdown=0.8* to fix conflicts.

**Comment by parente** [comment]
Merged. Need to do a build. Will get to it this evening and close when done.

**Comment by parente** [comment]
Rebuilt and pushed. Tag cbf05e05fca9.

**Comment by cboettig** [comment]
Nice, thanks!

On Mon, Dec 7, 2015, 7:25 PM Peter Parente <notifications@github.com> wrote:

> Rebuilt and pushed. Tag cbf05e0
> <https://github.com/jupyter/docker-stacks/commit/cbf05e05fca9c49b485505714d5067e081b3d2d4>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/docker-stacks/issues/68#issuecomment-162747946>
> .
>
-- 

http://carlboettiger.info

**Comment by parente** [comment]
@cboettig np. Report back if you have any problems using it.
