### ISSUE TITLE
Image Download Issue "Unexpected EOF"

### ISSUE THREAD

**Issue by vishalsaroha** [jupyter/docker-stacks#681]
Hi! Thanks for using the Jupyter Docker Stacks.

If you are looking to contribute to the images, please see the [Contributor's Guide] (http://jupyter-docker-stacks.readthedocs.io/en/latest/#) in the documentation for our preferred processes.

If you are reporting an issue with one of the existing images, please answer the questions below to help us troubleshoot the problem. Please be as thorough as possible.

**What docker image you are using?**

jupyter/pyspark-notebook

**What complete docker command do you run to launch the container (omitting sensitive values)?**

**What steps do you take once the container is running to reproduce the issue?**

Everytime I am trying to load this image, I am getting "Unexpected EOF " error.

aba43354736a: Downloading  747.7MB/747.7MB
74d185ef112b: Download complete 
baa81842b3da: Downloading  395.9MB/395.9MB

74d185ef112b: Downloading  68.49MB/68.49MB

It gets stuck at one or another layer.

**What do you expect to happen?**

**What actually happens?**

Example: No output is visible in the notebook and the notebook server log contains messages about ...

**Comment by parente** [comment]
EOF errors typically indicate a problem communicating with Docker Hub (e.g., early proxy termination, problems with the service) or problems saving images to local disk.

Can you check if your local disk is full, or, if you're using Docker for Mac / Windows, if the VM hosting Docker has a full disk? Are you on a corporate network that proxies connections to the public internet?

**Comment by parente** [comment]
I'm going to close out this issue as inactive. Feel free to comment back on whether the suggestions in the last comment addressed your issue or not for future generations.
