### ISSUE TITLE
cannot launch IJulia if running with NB_UID/GID set

### ISSUE THREAD

**Issue by boolewinkle** [jupyter/docker-stacks#682]
Hi! Thanks for using the Jupyter Docker Stacks.

If you are looking to contribute to the images, please see the [Contributor's Guide] (http://jupyter-docker-stacks.readthedocs.io/en/latest/#) in the documentation for our preferred processes.

If you are reporting an issue with one of the existing images, please answer the questions below to help us troubleshoot the problem. Please be as thorough as possible.

**What docker image you are using?**

datascience-notebook

**What complete docker command do you run to launch the container (omitting sensitive values)?**

'docker run -p 8888:8888 -it --rm -e NB_UID=$(id -u) -e NB_GID=$(id -g) -e GRANT_SUDO=yes --user root --mount type=bind,source="$(pwd)",target=/home/jovyan/work datascience-notebook `

**What steps do you take once the container is running to reproduce the issue?**

Try to create a julia notebook

**What do you expect to happen?**

A new julia notebook is created and opens

**What actually happens?**

ERROR: LoadError: SystemError: opening file /opt/julia/lib/v0.6/IJulia.ji: Permission denied

On linux.   I have successfully run julia without specifying NB_UID/GID , however it creates the .ipymb file in the mounted folder with uid 1000, and requires the mounted (host machine) folder has read/write permission by "other", both of which ugly.  So the command above is trying to run with  joyvan mapped to my own uid.  The problem is that joyvan can no longer read files under /opt inside the container.

I expect this error would apply to Python/R and any other language that uses the jupyter kernel or other files installed under /opt.

**Comment by boolewinkle** [comment]
It is worth mentioning that the host gid is not the default one for linux ubuntu. This was not originally decided by me.

**Comment by parente** [comment]
@boolewinkle can you share the tag of the `jupyter/datascience-notebook` you're using? #665 recently merged to fix a similar problem.

The fix-permissions script (https://github.com/jupyter/docker-stacks/blob/master/datascience-notebook/Dockerfile#90) should be making sure the `users` group retains write access, even when you add a supplementary group ID via NB_GID.

**Comment by parente** [comment]
This issue has been inactive for some time now without more information and so I'm going to close it. If someone can reproduce the issue with a recent image tag, feel free to open a new issue with the tag, steps to reproduce, etc.
