### ISSUE TITLE
docker pull jupyter/datascience-notebook fails:  authorization required  

### ISSUE THREAD

**Issue by shogun-tester-AT** [jupyter/docker-stacks#683]
**What docker image you are using?**
 `jupyter/datascience-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**
`docker pull jupyter/datascience-notebook`

**What do you expect to happen?**
complete download of image

**What actually happens?**
see following messsage:
```
docker pull jupyter/datascience-notebook
Using default tag: latest
latest: Pulling from jupyter/datascience-notebook
a48c500ed24e: Already exists
1e1de00ff7e1: Already exists
0330ca45a200: Already exists
471db38bcfbf: Already exists
0b4aba487617: Already exists
d44ea0cd796c: Already exists
5ac827d588be: Already exists
d8d7747a335e: Already exists
08790511e3e9: Already exists
e3c68aea9a5f: Already exists
484c6d5fc38a: Already exists
0448c1360cb9: Already exists
eed3d219811a: Already exists
944dbdf0ba87: Already exists
a881c93edb03: Already exists
bd3b8240d415: Already exists
8991111fa910: Already exists
8dc01f4de9c9: Already exists
aba43354736a: Already exists
74d185ef112b: Pull complete
baa81842b3da: Downloading [=========> ] 93.29MB/498.4MB
dd956fb4b809: Download complete
76625c9b2859: Download complete
db151e4ba560: Download complete
70ec87377474: Download complete
ab4aa9cdd9e4: Download complete
9950015b5218: Download complete
8e0350bbe1a1: Downloading [=======> ] 33.77MB/236MB
ff79c10d66aa: Downloading
unauthorized: authentication required
```
There exists a similar issue already (#364) which has been closed, the recommendations given there, however, cannot be applied in my case. 
ANY explanation or WORKAROUND  for this ?

**Comment by parente** [comment]
All of the `jupyter/*` images are public so there should be no reason for docker to report auth is required, especially in the middle of a pull operation. My wild guess is that if you've ever logged in using the docker client, it uses that authentication even when it's needed. If your auth expires between image layer pulls, then the whole operation fails. The `docker logout` workaround mentioned in #364 "fixed" the problem by forcing the user to access Docker Hub anonymously from the start, so that no auth could go stale.

Again, just a guess.

**Comment by shogun-tester-AT** [comment]
Note that there was **never** a docker login. The only command used was, as stated above:
`docker pull jupyter/datascience-notebook`
The error could be reproduced by simply repeating the command.

I suspect it might have something to do with my internet connection speed ( appr. 5 MBit/s ), which causes a time-out with the server. (?)

**Comment by parente** [comment]
Possibly. Maybe if you can enable debug logging in the docker daemon, it'll provide more info:

https://success.docker.com/article/how-do-i-enable-debug-logging-of-the-docker-daemon

**Comment by aks0033** [comment]
Docker Version: 18.03.1-ce-win65 (17513)
I am also stuck with the same response
I've tried login->pull/logout->pull/again login->pull
![image](https://user-images.githubusercontent.com/22841068/43190219-28512896-9016-11e8-8961-52602784b6df.png)

**Comment by shogun-tester-AT** [comment]
When I open a docker _quickstart terminal_ (as admin), I can indeed go to directory /etc and create a subdirectory docker, and create a file` /etc/docker/daemon.json` with  "debug" set TRUE, but is has no
effect, i.e. debug mode  is not switched ON.

If I open by _docker-machine_ and `ssh` into the started machine, I am logged in as `docker@mydockermachine` and do not have any root privileges to alter anything in /etc, while it again may not have any effect on logging anyway.

**Comment by shogun-tester-AT** [comment]
**WORK-AROUND:**
I managed to pull successfully the docker image by _incrementally_ pulling all predecessor images:
```
docker pull jupyter/minimal-noteboook
docker pull jupyter/scipy-noteboook
(docker pull jupyter/r-noteboook)
(docker pull jupyter/tensorflow-noteboook)
docker pull jupyter/datascience-noteboook
```

pull requests in parentheses () are maybe not necessary.

**MY EXPLANATION is:**
docker hub server creates up to three parallel threads for downloading image components;
these threads apparently have to be initiated within a certain time limit. If exceeded, no more
threads can be created and the pull operation is terminated (_"authorization required"_).
This problem occurs, if internet connection speed is too low (in my case appr. 5 MBit/s).
By incrementally pulling predecessor images, many required components of the image to be pulled
already exist on the client computer, and thus server time-out may be avoided.
