### ISSUE TITLE
How to tie Docker image tags to JupyterLab release version?

### ISSUE THREAD

**Issue by amit1rrr** [jupyter/docker-stacks#684]
Hey guys,
I'm looking to get answers to 2 simple questions about Docker stacks? 

1. How often are images updates on DockerHub?
2. I'm using [this image](https://hub.docker.com/r/jupyterhub/k8s-singleuser-sample/tags/) for JupyterLab. Given the docker image tags, how do I know which JupyterLab version the tag corresponds to?

I checked the Readme documentation and couldn't find the info. 

Thanks for your time.

-Amit

**Comment by parente** [comment]
> How often are images updates on DockerHub?

Every merge to master. See http://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#versioning for details.

> I'm using this image for JupyterLab. Given the docker image tags, how do I know which JupyterLab version the tag corresponds to?

That image is not built from the source or CI for this repository so I'm not sure. Maybe @yuvipanda or @minrk knows?

**Comment by amit1rrr** [comment]
I'm going to close it since I don't need the answer anymore and the question is not related to the source in this repo.
