### ISSUE TITLE
Cannot write to disk from notebook

### ISSUE THREAD

**Issue by SofianeB** [jupyter/docker-stacks#689]
I have tried with other docker containers (centos and ubuntu based) and it works!

**What docker image you are using?**

 `jupyter/base-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

Starting using dockerspawner

**What do you expect to happen?**

Write file to disk.

Example:
```
with open ("empty5.txt", "w") as f:
      f.write("")
```
**What actually happens?**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IOError: [Errno 22] invalid mode ('w') or filename: 'empty5.txt'
```

**Comment by parente** [comment]
Hi @SofianeB. Were you able to resolve this problem? Can you share what you did so that others may benefit? Thanks!
