### ISSUE TITLE
Please update to pandas 0.17

### ISSUE THREAD

**Issue by jtyberg** [jupyter/docker-stacks#69]
It would make my life easier to be able to use some of the new features in pandas 0.17 (current stacks are pegged at 0.16.2).

**Comment by ellisonbg** [comment]
+1

On Fri, Dec 4, 2015 at 2:16 PM, Justin Tyberg <notifications@github.com>
wrote:

> It would make my life easier to be able to use some of the new features in
> pandas 0.17 (current stacks are pegged at 0.16.2).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/docker-stacks/issues/69>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by parente** [comment]
Per the README, sure!

> Stack contents (e.g., new library versions) will be updated upon request via PRs against this project.
> Users looking to remain on older builds should refer to specific git SHA tagged images in their work, not latest.

**Comment by parente** [comment]
Rebuild in progress. Will comment when complete.

**Comment by parente** [comment]
Docker hub push failed. Retrying.

**Comment by parente** [comment]
Done. Tag a5678f472c25.

**Comment by parente** [comment]
For the record, this required also bumping fastly to 0.4*, numba to 0.22*, and bokeh to 0.10* to avoid conflicts.

**Comment by jtyberg** [comment]
FYI...I successfully built an image FROM jupyter/all-spark-notebook:a5678f472c25.  All seems to be working.
