### ISSUE TITLE
GPU recipe?

### ISSUE THREAD

**Issue by iyanmv** [jupyter/docker-stacks#706]
I know that `jupyter/tensorflow-notebook` only supports CPU to avoid including NVIDIA propietary software in the project (see https://github.com/jupyter/docker-stacks/issues/516). However, would it be ok to include a recipe in `docs/using/recipes.md`?

I know that some people (including me) would like to work with an image based on `jupyter/base-notebook` but with GPU support because [official docker images](https://hub.docker.com/r/tensorflow/tensorflow/) lacks some interesting features.

**Comment by jzf2101** [comment]
See  jupyterhub/zero-to-jupyterhub-k8s#994  as well as a reference

**Comment by beniz** [comment]
Believing Jupyter is right to stay away from closed source binaries as provided by NVidia, though driven by immediate industry requirements, we have put a version of this repository with added GPU support, including recipes and an additional one for Tensorflow + Pytorch (see #745 ), here: https://github.com/jolibrain/docker-stacks

The Tensorflow + Pytorch recipe is here: https://github.com/jolibrain/docker-stacks/tree/master/jupyter-dd-notebook-gpu

Note: we're only planning to update the GPU recipes irregularly at the moment.

**Comment by parente** [comment]
@beniz Thanks for sharing your work. 

This issue has been idle for some time now so I'm going to close it. If anyone would like to submit a PR to the recipes or community images doc pages linking to information about GPU-enabled images, I'll be happy to review it.
