### ISSUE TITLE
Update docs for .d folders

### ISSUE THREAD

**Issue by parente** [jupyter/docker-stacks#715]
https://github.com/jupyter/docker-stacks/pull/688 introduced `/usr/local/bin/before-notebook.d/`.

We should update the docs to note the current behavior.

**Comment by rkdarst** [comment]
Weren't they always sourced, just with `.` instead of `source` ?  I
don't think I changed it, just used the more clear form...

I checked docs and can't seem to find where hooks are mentioned... are they?

**Comment by parente** [comment]
> Weren't they always sourced, just with `.` instead of `source` ?  I

You're right. I missed the `.` reading the script. More evidence that your long-hand change is for the better.

**Comment by parente** [comment]
> I checked docs and can't seem to find where hooks are mentioned... are they?

The original hook may never have been documented either. A new section "Start-Up Hooks"  under "Docker Options" on https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html is my recommendation.
