### ISSUE TITLE
Question:  Modify base-notebook to have username/id/gid passed as ARGs?

### ISSUE THREAD

**Issue by rwmajor2** [jupyter/docker-stacks#719]
Question.  Can we modify the base-notebook Dockerfile so that the username/UID/GID can be passed in as ARGs on the Docker build process?  We are wanting to use these environments almost "as-is" but want to use a different username than "jovyan".

Yes, I know that you can launch these Docker containers and change the username on the fly, but you have to do that by launching the container as root and there are big security concerns of doing that within our organization.  So, we just want to rebuild them with our own username/UID from the base.

Let me know your thoughts and I can submit a PR.

**Comment by parente** [comment]
Hi @rwmajor2. #660 has a discussion about this. Please check there for a bit of detail. PRs welcome.

**Comment by rwmajor2** [comment]
@parente Any preferences on ARG names?
```
ARG BUILD_USER="jovyan"
ARG BUILD_UID="1000"
ARG BUILD_GID="100"
```

**Comment by rwmajor2** [comment]
@parente When I build base-notebook with a group other than 100 (for example 1050), I see a lot of this:
```
chgrp: changing group of '/opt/conda/pkgs/jsonschema-2.6.0-py36_2': Operation not permitted
chgrp: changing group of '/opt/conda/pkgs/jsonschema-2.6.0-py36_2/bin': Operation not permitted
chgrp: changing group of '/opt/conda/pkgs/jsonschema-2.6.0-py36_2/bin/jsonschema': Operation not permitted
chgrp: changing group of '/opt/conda/pkgs/jsonschema-2.6.0-py36_2/lib': Operation not permitted
chgrp: changing group of '/opt/conda/pkgs/jsonschema-2.6.0-py36_2/lib/python3.6': Operation not permitted
```

I think I understand why, but curious if this is a "bug" in the current Dockerfile related to how the groupid is assigned.
