### ISSUE TITLE
datascience-notebook hangs when setting NB_GID

### ISSUE THREAD

**Issue by nbonnotte** [jupyter/docker-stacks#722]
**What docker image you are using?**

`jupyter/datascience-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

`docker run -it --rm --user root -e NB_UID=1000 -e NB_GID=1000 jupyter/datascience-notebook `

**What do you expect to happen?**

Jupyter should start

**What actually happens?**

The command hangs on:
```
$ docker run -it --rm --user root -e NB_UID=1000 -e NB_GID=1000 jupyter/datascience-notebook  
Set username to: jovyan
usermod: no changes
Add jovyan to group: 1000
```

This does not happen with `jupyter/scipy-notebook`

**Comment by parente** [comment]
No hang here with the latest image:

```
docker pull jupyter/datascience-notebook
docker run -it --rm --user root -e NB_UID=1000 -e NB_GID=1000 -p 8888:8888 jupyter/datascience-notebook

Set username to: jovyan
usermod: no changes
Add jovyan to group: 1000
Executing the command: jupyter notebook
[I 02:38:44.333 NotebookApp] Writing notebook server cookie secret to /home/jovyan/.local/share/jupyter/runtime/notebook_cookie_secret
[W 02:38:44.564 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[I 02:38:44.602 NotebookApp] JupyterLab extension loaded from /opt/conda/lib/python3.6/site-packages/jupyterlab
[I 02:38:44.602 NotebookApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 02:38:44.612 NotebookApp] Serving notebooks from local directory: /home/jovyan
[I 02:38:44.612 NotebookApp] The Jupyter Notebook is running at:
[I 02:38:44.612 NotebookApp] http://(05968a4a64e8 or 127.0.0.1):8888/?token=cfb5928d3c83473e4a0890aab755d4fea3164dac899d3331
[I 02:38:44.612 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 02:38:44.613 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://(05968a4a64e8 or 127.0.0.1):8888/?token=cfb5928d3c83473e4a0890aab755d4fea3164dac899d3331
```

Are you exposing the port properly with `-p 8888:8888`?

**Comment by rkdarst** [comment]
I actually *think* I recently saw something similar recently, though
the image would have been based on that of a few weeks or months ago.
At the time I wasn't in a position to debug it and now have forgotten
just what happened.  I will probably be doing more with images in the
near future, and will try to reproduce.

**Comment by nbonnotte** [comment]
I'm exploring a bit. It appears that the following line does not really hang but takes forever:
```
usermod -g $NB_GID -a -G $NB_GID,100 $NB_USER
```
To investigate, I'm using `strace` (which requires docker to run with `--cap-add=SYS_PTRACE`)
```
strace usermod -g $NB_GID -a -G $NB_GID,100 $NB_USER
```
and what I can see is that this line causes the group ownership of all `/home/jovyan/.julia/` to change, which takes forever. The strace is full of
```
...
lstat("/home/jovyan/.julia/packages/Gadfly/p8TXc/test/testscripts/point_color_numerical.jl", {st_mode=S_IFREG|0644, st_size=121, ...}) = 0
lchown("/home/jovyan/.julia/packages/Gadfly/p8TXc/test/testscripts/point_color_numerical.jl", -1, 1000) = 0
lstat("/home/jovyan/.julia/packages/Gadfly/p8TXc/test/testscripts/dodged_discrete_histogram.jl", {st_mode=S_IFREG|0644, st_size=168, ...}) = 0
lchown("/home/jovyan/.julia/packages/Gadfly/p8TXc/test/testscripts/dodged_discrete_histogram.jl", -1, 1000) = 0
lstat("/home/jovyan/.julia/packages/Gadfly/p8TXc/test/testscripts/subplot_grid_free_y_2.jl", {st_mode=S_IFREG|0644, st_size=251, ...}) = 0
lchown("/home/jovyan/.julia/packages/Gadfly/p8TXc/test/testscripts/subplot_grid_free_y_2.jl", -1, 1000) = 0
lstat("/home/jovyan/.julia/packages/Gadfly/p8TXc/test/testscripts/errorbar.jl", {st_mode=S_IFREG|0644, st_size=403, ...}) = 0
lchown("/home/jovyan/.julia/packages/Gadfly/p8TXc/test/testscripts/errorbar.jl", -1, 1000) = 0
lstat("/home/jovyan/.julia/packages/Gadfly/p8TXc/test/testscripts/step.jl", {st_mode=S_IFREG|0644, st_size=238, ...}) = 0
lchown("/home/jovyan/.julia/packages/Gadfly/p8TXc/test/testscripts/step.jl", -1, 1000) = 0
lstat("/home/jovyan/.julia/packages/Gadfly/p8TXc/test/testscripts/smooth_lm.jl", {st_mode=S_IFREG|0644, st_size=143, ...}) = 0
lchown("/home/jovyan/.julia/packages/Gadfly/p8TXc/test/testscripts/smooth_lm.jl", -1, 1000) = 0
...
```
That explains why I don't have the same issue with `scipy-notebook`.

**Comment by rkdarst** [comment]
> and what I can see is that this line causes the group ownership of all `/home/jovyan/.julia/` to change, which takes forever. The strace is full of

This actually sounds like what it could have been for me.  I think I
discovered this long ago, cleaned home, and probably it is what
happened again more recently and I had forgotten about it by then.
Thanks for figuring it out!

**Comment by parente** [comment]
This issue has inactive for some time now and so I'm going to close it. The container startup logic has changed a bit since this issue was opened, but if there's still a way to improve it to reduce the time it takes to chown, I'll be happy to review a PR suggesting it. Failing that, a doc PR calling out increased startup time when using a custom UID/GID would also be welcome.
