### ISSUE TITLE
Wrong environment name to enable jupyter lab in the document

### ISSUE THREAD

**Issue by popcornylu** [jupyter/docker-stacks#724]
**What do you expect to happen?**

in document
https://jupyter-docker-stacks.readthedocs.io/en/latest/index.html#

To  run the jupypterlab, the command should be
```
docker run --rm -p 10000:8888 -e JUPYTER_ENABLE_LAB=yes -v "$PWD":/home/jovyan/work jupyter/datascience-notebook:e5c5a7d3e52d
```

**What actually happens?**
Wrong environment name `JUPYTER_LAB_ENABLE` -> `JUPYTER_ENABLE_LAB`
```
docker run --rm -p 10000:8888 -e JUPYTER_LAB_ENABLE=yes -v "$PWD":/home/jovyan/work jupyter/datascience-notebook:e5c5a7d3e52d
```

**Code location**
https://github.com/jupyter/docker-stacks/blob/master/base-notebook/start-notebook.sh#L11
https://github.com/jupyter/docker-stacks/blob/master/docs/index.rst#quick-start

**Comment by parente** [comment]
Thanks @popcornylu . Would you like to submit a PR to fix the doc?

**Comment by parente** [comment]
We "fixed" the wrong part of the doc. Doh!
