### ISSUE TITLE
FROM container as an arg

### ISSUE THREAD

**Issue by graemes** [jupyter/docker-stacks#727]
One small change I've made at my site is to change the Dockerfiles to use an ARG for the FROM clause (see below).  This makes it simpler for me to change the base container to something other than the hardcoded entry i.e. <cough>cuda</cough> or my own registry in my build scripts.  Would there be any benefit to submitting a PR with the change made throughout the tree?

ARG BUILD_CONTAINER=jupytper/base-notebook
FROM $BUILD_CONTAINER

**Comment by parente** [comment]
Seems reasonable. If you submit a PR, we can watch how the build process goes on Travis.

**Comment by ericdill** [comment]
@parente closed by #731
