### ISSUE TITLE
Notebook path setting (probably doc understanding issue)

### ISSUE THREAD

**Issue by dartdog** [jupyter/docker-stacks#73]
I get it to start up fine but it is in it's own world. I want to access the files on my local machine.

The instructions indicate to start it with the following to set a custom Base url

    docker run -d -p 8888:8888 jupyter/all-spark-notebook start-notebook.sh --NotebookApp.base_url=/some/path
However I cannot figure out a valid path syntax

I have tried /Home, ~/Home, /home, ~/home as well as longer versions. I keep getting the Jupyter notebook page saying 404??

Any Ideas?

Using Ubuntu 14.04

A user on SO suggest that I need to set a virtual drive for the image like,,,

If you're looking to access the files on your local machine, you'll need to mount a volume to the docker container. Your command for start-notebook.sh will have to reference a path that is relevant to your docker container, which would be the right-side of the volume argument:

    docker run -d -p 8888:8888 -v /some/path/on/my/local:/some/path/on/my/container jupyter/all-spark-notebook start-notebook.sh --NotebookApp.base_url=/some/path/on/my/container

Posted on SO as http://stackoverflow.com/questions/34098610/docker-jupyter-notebook-setting-base-url

**Comment by parente** [comment]
You don't need to touch the base URL which controls the root of the web server, not the root path on disk. Try:

```
docker run -d -p 8888:8888 -v /some/path/on/your/local:/home/jovyan/work jupyter/all-spark-notebook
```

The only part you need to change is the `/some/path/on/your/local`. The right side of the volume mount is the notebook root path preconfigured in the image. This hint comes from the *Docker Options* in each of the stack README:

> -v /some/host/folder/for/work:/home/jovyan/work - Host mounts the default working directory on the host to preserve work even when the container is destroyed and recreated (e.g., during an upgrade).

I agree, it's a bit confusing. This should probably go on the *Recipes* wiki page associated with this repo.

**Comment by dartdog** [comment]
Appreciate the help but still no joy...
I tried both of the following and do not get my "Documents" folder (which contains a bunch of Jupyter notebooks in various directories...  and when I try to just create a text file so i can try to find the path I get a permission denied...

docker run -d -p 8888:8888 -v ~/tom/Documents/:/home/jovyan/work jupyter/all-spark-notebook
^^ ng tried
tom@tom-sam:~$ docker run -d -p 8888:8888 -v /Documents/:/home/jovyan/work jupyter/all-spark-notebook
Will be reading the wiki recipes but any help appreciated, and I suspect others following behind would appreciate!

**Comment by dartdog** [comment]
Finally got it! in case someone else follows:
tom@tom-sam:~$ docker run -d -p 8888:8888 -v ~/Documents/:/home/jovyan/work jupyter/all-spark-notebook
