### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by statiksof** [jupyter/docker-stacks#732]
**What docker image you are using?**

`jupyter/base-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

`DockerSpawner`

I am just asking on how to make a reference to jupyter/base-notebook. 
My image is not completely based on that image and I am not using 

```
FROM jupyter/base-notebook
```
but some layers are taken from the base-notebook source code like creating jovyan user.

**Comment by ericdill** [comment]
Hi @statiksof -- It looks like you're asking how you should license some of the layers that you copied from the `base-notebook`. (Or *if* you even need to specifically call out those copied lines in a license file somewhere?) If this is not correct, can you please reply or update the original post with clarifications?

**Comment by statiksof** [comment]
Thanks @ericdill  this is exactly what I did ```copied some layers from base-notebook```

**Comment by ericdill** [comment]
Hi @statiksof -- I am not a lawyer, but reading the [BSD license associated with this project](https://github.com/jupyter/docker-stacks/blob/master/LICENSE.md), it specifically says that:

> Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

[Here is a really nice stackexchange](https://softwareengineering.stackexchange.com/a/293786) answer about how to handle copying BSD licensed contents out into a different project. I would suggest talking with a lawyer if you have concerns, or following the advice in the aforementioned stackexchange.

**Comment by parente** [comment]
I think this question has been addressed. I'm going to close the issue.
