### ISSUE TITLE
Info required for those wishing to continue with Julia 0.6* (i.e. which docker image tag corresponds to Julia 0.6*)

### ISSUE THREAD

**Issue by dnk8n** [jupyter/docker-stacks#738]
I need to know the correct tag to use in order to get the latest datascience-notebook with Julia 0.6* installed. I can see where that is in the git code but couldn't find where your CI is done and what the resulting tag is.

Any insights?

The reason I need this is for example, [Levenshtein](https://github.com/rawrgrr/Levenshtein.jl) doesn't work on Julia 1.0. Would be useful to have multiple julia kernels (latest of 0.6*, 0.7* 1*) until Julia reaches a 1.1.0 release at least.

**Comment by parente** [comment]
The docker tags correspond with docker commit hashes. If you look back in the datascience notebook Dockerfile to find the commit ID where it was upgraded (or search through the pull requests to find the merge that removed it), the first twelve characters of the git SHA before that is the image ID you want to use.

https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#versioning has more detail.

We used to have a bot that would build a nice table on the wiki with this info, but it's fallen into disrepair (#537).

**Comment by dnk8n** [comment]
Do you mean: The docker tags correspond with git commit hashes?

I find no correlation between the git repo and the docker tags...

For example where does docker tag ebb42274ac29 (https://hub.docker.com/r/jupyter/datascience-notebook/tags/) come from. I don't see any sha256 matches in the repo at https://github.com/jupyter/docker-stacks/commits/master/datascience-notebook/Dockerfile

I am interested in the docker image immediately prior to the build at - https://github.com/jupyter/docker-stacks/commit/9b2ed35aeaa747534cb6ad56e35f193846a423bc#diff-3389ba209110caaa37aa59ecba2a3d6d

**Comment by dnk8n** [comment]
I found that I could more easily locate the commit of interest with the repo checked out on my laptop (compared to using gihub). The tag I am after is 8ccdfc1da8d5 I am pretty sure.

There has got to be a more sane tagging system. Why not use versioning with git tags?

**Comment by parente** [comment]
We've discussed versioning in the past (e.g., #12, https://github.com/jupyter/docker-stacks/issues?q=is%3Aissue+versioning+is%3Aclosed). If you have suggestions for improvement that takes into account the issues solved by the current system, please let us know.

**Comment by parente** [comment]
This issue has been idle for quite some time now and so I'm going to close it. #823 has a recent conversation and new work to make the contents of the images more readily visible to users.
