### ISSUE TITLE
I wan't to use the xenial version of docker-stacks

### ISSUE THREAD

**Issue by apur005** [jupyter/docker-stacks#740]
**What docker image you are using?**

Example: `jupyter/base-notebook`

I wan't to use the xenial version of dockerfiles [base-notebook, minimal-notebook] which branch should i checkout?

Regards'
Apur

**Comment by ericdill** [comment]
I believe you are looking for the set of docker images with tag `3a5f57dc4660`. You can pull the base notebook and check the version yourself with:

```
docker run -it jupyter/base-notebook:3a5f57dc4660 /bin/bash
```

The remaining notebooks will have the same tag:

```
docker run jupyter/datascience-notebook:3a5f57dc4660
```

**Comment by parente** [comment]
I'm going to close this issue as resolved. Since the question was asked, we've added [build manifests to the wiki](https://github.com/jupyter/docker-stacks/wiki) so that users can track what each image build contains. They're still a work in progress (#823) but useful already.
