### ISSUE TITLE
Using hashes as a docker image label - can we prefer version labels?

### ISSUE THREAD

**Issue by rothwewi** [jupyter/docker-stacks#742]
As a consumer of jupyter docker-stacks I want to be able to download the latest image against a specific version number so that I can know what features are in it and know that it has the latest OS / Middleware versions on it.

With a githash (as many are currently solely labelled with), it may tie neatly to source control, but it communicates little to the consumer directly.

I want to be able to tell at a glance which version an image is, and the most recent version of a particular version.

Note (also raised against jupyterhub).

**Comment by parente** [comment]
We're addressing some concerns raise here in #823. For example, the project wiki on this site now automatically updates after builds in Docker Hub to show complete build manifests of the apt, python, r, julia, etc. packages in the image.

Please feel free to join the conversation in #823. I'm going to close this issue out as a duplicate, even though I know it was opened first. (I just had time to start working on the problem around the time the other one was opened.)
