### ISSUE TITLE
Spark Streaming's Kafka libraries not found in class path

### ISSUE THREAD

**Issue by boredev** [jupyter/docker-stacks#743]
Hi,

I have a problem when I try to run a python script in the jupyter lab.

Here my steps to reproduce it : 

- Launch the container :
`docker run -it --rm -p 8888:8888 --name jupyter docker.io/jupyter/all-spark-notebook`

- Take the url with the token, go to the lab and try to execute this code :

```
from pyspark import SparkConf, SparkContext
from pyspark.streaming import StreamingContext
from pyspark.streaming.kafka import KafkaUtils
import json
import time
from datetime import datetime

sc.stop();
conf = SparkConf().setMaster("local[*]").setAppName("app-logs-dev-streaming")
sc = SparkContext(conf = conf)

sc.setLogLevel("WARN")
ssc = StreamingContext(sc, 10)

kafkaStream = KafkaUtils.createDirectStream(ssc, ['customer-login-history-topic'], {"metadata.broker.list":  'kafka:9092'})

lines = kafkaStream.map(lambda x: json.loads(x[1]))

lines.pprint()

ssc.start();
ssc.awaitTermination()

```

I get this error :

> ________________________________________________________________________________________________
> 
>   Spark Streaming's Kafka libraries not found in class path. Try one of the following.
> 
> [...]
>      $ bin/spark-submit --packages org.apache.spark:spark-streaming-kafka-0-8:2.3.1 ...
> [..]
> ________________________________________________________________________________________________
> 
> 
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-4-3bbd91d545dc> in <module>()
>      13 ssc = StreamingContext(sc, 10)
>      14 
> ---> 15 kafkaStream = KafkaUtils.createDirectStream(ssc, ['customer-login-history-topic'], {"metadata.broker.list":  'kafka:9092'})
>      16 
>      [...]
>     219             if str(e) == "'JavaPackage' object is not callable":
> 
> TypeError: 'JavaPackage' object is not callable

Obviously I'm missing some packages but how to import them ? I tried this but doesn't change anything :
```
import os
os.environ['PYSPARK_SUBMIT_ARGS'] = '--packages org.apache.spark:spark-streaming-kafka-0-8_2.11:2.0.2 pyspark-shell'
```

I also tried the suggested command line (with --package or --jars) like :

`bin/spark-submit --packages org.apache.spark:spark-streaming_2.11:2.3.2 test_script.py`

or 

`bin/spark-submit --jars /usr/local/spark-2.3.1-bin-hadoop2.7/jars/spark-streaming_2.11-2.3.1.jar test_script.py`

but still the same error (also the package could not be downloaded).

I'm surely doing something wrong but can't find what it is. What am I missing ?

Can someone help me please ?

**Comment by chainarong-Trainapakul** [comment]
+1 , i got the same problem

**Comment by Manoj1881** [comment]
Same here

**Comment by parente** [comment]
We're starting to experiment with a general Q&A section on https://discourse.jupyter.org/c/questions to see if cross-technology questions like this one catch more attention from a broader community audience. You might try re-posting your question over there to see if someone with more experience in PySpark + Kafka + Docker can help.

I'm going to close this issue since it has been idle for some time now. If you do post the question again on the Discourse site, feel free to leave a link in a comment here for those that happen upon this closed issue.

**Comment by sourabhdattawad** [comment]
You need to download jar files (https://mvnrepository.com/artifact/org.apache.spark/spark-streaming-kafka-0-8-assembly_2.11) directly and place it under jovyan
Add reference inside the code
`import os
os.environ['PYSPARK_SUBMIT_ARGS'] = '--jars /home/jovyan/spark-streaming-kafka-0-8-assembly_2.11-2.0.0-preview.jar pyspark-shell'`

**Comment by dz-s** [comment]
@sourabhdattawad It works! Thanks.
