### ISSUE TITLE
[Suggestion] Can we update the jupyterlab to 0.35.0?

### ISSUE THREAD

**Issue by bobmayuze** [jupyter/docker-stacks#744]
Can we update the jupyterlab in base-notebook to 0.35.0?

**Comment by parente** [comment]
As soon as all the extensions we also install in the image are 0.35.0 compatible, I'm happy to review a PR bumping the versions.

See https://github.com/jupyter/docker-stacks/pull/737 for recent attempt.

**Comment by parente** [comment]
Reopening so that we have a note about it for others to see.
