### ISSUE TITLE
Include xarray?

### ISSUE THREAD

**Issue by RafalSkolasinski** [jupyter/docker-stacks#748]
I wonder if it would be good idea to include [xarray](http://xarray.pydata.org/en/stable/) in the ``scipy-notebook`` image? 
It's quite useful library that extend pandas to multidimensional data.

**Comment by parente** [comment]
This issue has been idle for some time now without any comments from the community about adding xarray. I see there's a linked issue from the pangeo project where they solved it by building their own images using repo2docker. 

I'm going to close out this issue for the time being. If there's a groundswell of support for adding it, we can revisit adding it by default.
