### ISSUE TITLE
JupyterHub - nbgitpuller?

### ISSUE THREAD

**Issue by consideRatio** [jupyter/docker-stacks#751]
nbgitpuller allows you to utilize a url like http://jupyter.example.com/hub/user-redirect/git-pull?repo=consideratio/jupyter-se-math-teacher and boom you have git cloned a repo. This is very useful for a teacher or similar wanting to distribute material to students.

I often find myself wanting to install nbgitpuller on docker-stack images as the only additional package - it may very well be a bit too specific to include though. Got some input regarding this?

**Comment by parente** [comment]
Sounds like good fodder for a recipe on the face of it: https://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html

**Comment by consideRatio** [comment]
Deal! It is a simple matter of installing it if you are to build an image at all, closing this.

**Comment by parente** [comment]
@consideRatio I'd like to leave the issue open as a lightning rod. If there's a groundswell of support for a generally useful package from users, we should definitely add it.

**Comment by parente** [comment]
This issue has been idle for some time now after my last comment. I'm going to close it but would still welcome a PR describing how to add nbgitpuller to the recipes page in the documentation.
