### ISSUE TITLE
`jupyter lab clean` - something to be utilized?

### ISSUE THREAD

**Issue by consideRatio** [jupyter/docker-stacks#752]
Is using `jupyter lab clean` something that makes sense to utilize?

I recall seeing it used like `RUN jupyter lab build && jupyter lab clean` in a Dockerfile.

It sais by using the `--help` flag of the clean command that...

> This will clean the app directory by removing the staging and static directories.

And I also notice how there are statements like the following to be found in the docker-stacks:

https://github.com/jupyter/docker-stacks/blob/610bb8b938dbd3c5f881aa4628af6a6581897413/scipy-notebook/Dockerfile#L57

**Comment by parente** [comment]
Seems reasonable to switch to `clean` if it accomplishes the same thing or does better at cleaning up working files. Might be we added the lab extensions before it existed or just didn't know about it.

**Comment by consideRatio** [comment]
@dhirschfeld wrote this in the gitter chat of jupyterlab btw, I found it to be related and relevant to consider as well. I don't know what differences will come out of it etc though.

> @consideRatio - I use docker multi-stage builds, build the extensions in a throwaway container then copy the lab folder into my final image. This has the benefit of ensuring you don't end up with any npm cache stuff in your final image and minimises layers.

**Comment by consideRatio** [comment]
Related: https://github.com/jupyterlab/jupyterlab/issues/4930

**Comment by parente** [comment]
Clean all the things!

**Comment by romainx** [comment]
Hello,

The command has evolve with the new `2.x` Jupyterlab version.

> Added options for jupyter lab clean to clean specific parts of the build, such as --extensions, --settings, --static, and --all (#7583, #6734)

- <cite>https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html</cite>

We could only use `jupyter lab clean` to remove the `staging` since other options will lead to not usable extension.

> The `staging` directory is used to create the build and then populate the `static` directory.

- <cite>https://jupyterlab.readthedocs.io/en/stable/user/extensions.html#staging-and-static</cite>

I've tested in the `scipy-notebook` we are already removing the entire folder so there is nothing more to do.

```bash
jovyan@3486515cf88f:~$ jupyter lab clean
[LabCleanApp] Cleaning /opt/conda/share/jupyter/lab...
[LabCleanApp] staging not present, skipping...
[LabCleanApp] Success!
```

However we could replace the `rm` by a call to `jupyter lab clean`, it would be cleaner :grin:

```diff
- rm -rf $CONDA_DIR/share/jupyter/lab/staging && \
+ jupyter lab clean && \
```

I've open the PR #1046 with this change.

Best

**Comment by romainx** [comment]
Hello,

The PR #1046 has just been merged and `jupyter lab clean` is now used in place of `rm`.

I'm closing the issue, thank you for the suggestion :smile:

Best

**Comment by arunkumaralagesan** [comment]
is there a way to stop cleaning, as like no-clean to prevent the staging webpack files from overridden, so that custom webpack configs can be added?

**Comment by mathbunnyru** [comment]
@arunkumaralagesan could you please create a new issue and describe the issue you have?
