### ISSUE TITLE
pulling jupyter/tensorflow-notebook latest

### ISSUE THREAD

**Issue by cywang16** [jupyter/docker-stacks#753]
In [jupyter/tensorflow-notebook tags](https://hub.docker.com/r/jupyter/tensorflow-notebook/tags/) I see the tag a6fc0cfbd01b was created 2 days ago, but when I pulled latest, I still got a 11 days old image.

does that mean the latest tag does not point to tag a6fc0cfbd01b?

Thanks.

**Comment by parente** [comment]
You might have pulled while latest was still being updated. https://hub.docker.com/r/jupyter/tensorflow-notebook/tags/ currently shows both `a6fc0cfbd01b` and `latest` are the same age.

**Comment by cywang16** [comment]
Thanks, Peter:

But I still get 13 days old image. I deleted the image first:

delete a list of docker images
docker rmi tensor
Untagged: jupyter/tensorflow-notebook:latest
Untagged: jupyter/tensorflow-notebook@sha256
:df60a87d43a3756ff859fae4719f503c4c503f0dcc2afc908743668240557e07
Deleted:
sha256:7331d8c429a3df8ede0919da861596db7621f233d2d577912910b65284c3f0f6
Deleted:
sha256:4d1529517e2e8ff4f73c251de3150da41f5ac787ac3344dd619973ff1314cc51
Deleted:
sha256:ba96d2c47672ce19544ea2d57416831da45ee3e493a1c38f3d34b27b78feea18
Deleted:
sha256:e0a8cf7bfeeadcb98a3757bb524e7efc84464cf3d7849fe8c72ef14b9268529e
Deleted:
sha256:6d59df827b0ad52c78e6db2a7870bfd01e8d94d331ede1230f067447dd7dd576
Deleted:
sha256:5ba8486a6633023703b9e340e3198858761c2be793586569686f052e568ad606
Deleted:
sha256:855ce02ecece57915e24aff80d1a2eec56fcd4859ce878253ace979fce967392
Deleted:
sha256:0f4c87c44e22298f5b028c32dbc207efeaf459bce8ab2601586b1eca3e6d2166
Deleted:
sha256:787ffdcc55ef7c9e4cc82df594c64957ee55868300ddb66baa5a3223590e6420
Deleted:
sha256:b619d77c2a9a156b166dc8872cfdafb3fa91e0a13c56455521d692e377b21c49
Deleted:
sha256:ad2e595905d478d6ef2e0ea2b37f2449dfb28802c34c48d61cce04ef54f85831
Deleted:
sha256:7241678199cd45d2d0ff09478fe472740198701145cd3e1523c2b8ef65dc4668
Deleted:
sha256:7f360ec7ef08c3b5793957d604390b32aa495c1b6cdf090d0c8b46e93bba24c7
Deleted:
sha256:de636efb2815ffcbe90fcdb28ff2fea33ae77c28cbe5121e802ea51bae5a2caa
Deleted:
sha256:311d3073bd6255cc7e3eee49cfd96c1763a08a1659447f9b5dec77d57b527d02
Deleted:
sha256:8857713c8f51f84f832e52d122a95d1c9b4513a9b3eb7a9fda2f39feab6e6a9b
Deleted:
sha256:1bcded270ba1c2e8a4d122e513a6a1ea4f0166281b19effeb53a7e878698dfbb
Deleted:
sha256:710a4d1f6bf7095b4036b06bdbc913dfe5431f12e65b21f48fd977171a93ba7a
Deleted:
sha256:2cd4062db0ded88093f038ebef483e23677724b2fad38fa01ae9a73ef9af267c
Deleted:
sha256:653fd294708c0e5f6bb85d3cf36ea5b7cf1189fdae651cb5855af2ea68eb601a
Deleted:
sha256:96fccbf869d3c0ee0fb2e976fdf356dc5872f6410030fd094bbc5b34a7559cdb
Deleted:
sha256:38ffa1479cb9fd81d0d4d057c282a155a4a83bff5d2b507ee9563f996d74272d
Deleted:
sha256:cc6967c5525a55626688a773e4fe578321a2e126a3b1df1bc0763cfd1583c50c
Deleted:
sha256:2a2d486f02032f5a6cc56290a244512daa07a8efe0124bccc5701f0a778aa947
Deleted:
sha256:65bdd50ee76a485049a2d3c2e92438ac379348e7b576783669dac6f604f6241b

Then I pulled by launching a dockercompose

docker-compose up -d
Creating network "tensorflownotebook_default" with the default driver
Pulling sci-notebook (jupyter/tensorflow-notebook:latest)...
latest: Pulling from jupyter/tensorflow-notebook
a48c500ed24e: Pull complete
1e1de00ff7e1: Pull complete
0330ca45a200: Pull complete
471db38bcfbf: Pull complete
0b4aba487617: Pull complete
27261a5cbf78: Pull complete
2773b009b29a: Pull complete
0915dfd6dae3: Pull complete
ee7dca77f9ed: Pull complete
cf5be5e11621: Pull complete
33aa38e94d28: Pull complete
68f4b2245d2a: Pull complete
f5ab1b831f77: Pull complete
7ba257ca073a: Pull complete
0eb8f950b3ea: Pull complete
7774c2ec4751: Pull complete
2b9f5766a263: Pull complete
e4052009a673: Pull complete
f9e7255ce189: Pull complete
267a2399516f: Pull complete
3b54695138ea: Pull complete
d23336e5273c: Pull complete
e612b1583510: Pull complete
0d8ebcda14df: Pull complete
Digest:
sha256:df60a87d43a3756ff859fae4719f503c4c503f0dcc2afc908743668240557e07
Status: Downloaded newer image for jupyter/tensorflow-notebook:latest

Then I checked what I got

sudo docker images
REPOSITORY                    TAG                 IMAGE ID
CREATED             SIZE
jupyter/tensorflow-notebook   latest              7331d8c429a3        13
days ago         5.14GB

What do I miss?

Chun-Yen

**Comment by parente** [comment]
@cywang16 Quite a bit of time has passed since our conversation above. Were you able to resolve the problem of your docker client not downloading the latest image?

**Comment by cywang16** [comment]
Thanks @parente 
Looks good now. Let me close this issue.
