### ISSUE TITLE
Bump pyspark-notebook to spark 2.4.0

### ISSUE THREAD

**Issue by zaredb** [jupyter/docker-stacks#754]
Spark 2.4.0 is now released at https://archive.apache.org/dist/spark/spark-2.4.0/

**Comment by parente** [comment]
Happy to take a PR from someone that would like to make the update. Here's the last commit updating to 2.3.1 as a reference: https://github.com/jupyter/docker-stacks/pull/664/commits/9f2072b8e6589e38f4a6f33868fb9847a2ba45fb

**Comment by borregore** [comment]
Hello there, I would like to contribute on this Spark update.

**Comment by Bidek56** [comment]
PR #756 is done for this request.

**Comment by Bidek56** [comment]
py4j is up to 0.10.8.1, it could be worth updating as well.

**Comment by borregore** [comment]
PR #757 id done for this request with py4j update.

**Comment by parente** [comment]
Closed by #756 and #757.
