### ISSUE TITLE
Advice on running these images behind nginx?

### ISSUE THREAD

**Issue by cboettig** [jupyter/docker-stacks#76]
Curious if you have any examples or advice on running one of these images behind a nginx proxy?  I tried [this nginx configuration](https://gist.github.com/cboettig/8643341bd3c93b62b5c2) but this doesn't appear to work.  

(Yes, I see the image already has a `USE_HTTPS` option, but would like to map the port to a path on the server, e.g. SERVER/jupyter instead of SERVER:8888.  Also it seems sensible to have the image running behind the same nginx proxy handling other apps on the server).  

Thanks for your help and apologies if this is out of scope for issues here.

**Comment by parente** [comment]
This is good fodder for the recipes page on this repo. I do have an nginx config somewhere but will need to dig it up. I suspect others watching this repo do too.

**Comment by ben-github** [comment]
This is what I use. I pass " --NotebookApp.base_url=/Jupyter"  when I build the docker container so I can put Jupyter in a subdirectory on my mail webserver (and thus share ssl cert with other apps) Then in nginx I have:

```
 location /Jupyter {

   if ($scheme = 'http') {
              #Insecure, lets go to https
              rewrite ^/(.*)$ https://$host/$1 redirect;
   }

    access_log  /var/log/nginx/juypter_access.log;
    error_log   /var/log/nginx/juypter_error.log;

    proxy_pass http://localhost:8888;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_cache_bypass $http_upgrade;
```


I've found you can't use nginx 1.2 because of issues proxying websockets. Nginx 1.6 works, not sure about 1.4.

**Comment by cboettig** [comment]
@ben-github Thanks, that sounds just like what I needed.  Looks like setting `NotebookApp.base_url` is the missing piece to my config (linked above).

Would it be possible to make `--NotebookApp.base_url=/Jupyter` into something that can be configured at runtime rather than build time; e.g. an env var similar to the existing options like `USE_HTTPS`?

**Comment by parente** [comment]
@cboettig Just pass it as a command line arg to `docker run`. They flow through to the start-notebook.sh script which passes them as command line args to `jupyter notebook`:

```
# omitting a bunch of options for clarity ...
docker run jupyter/minimal-notebook --NotebookApp.base_url=/Jupyter
```

**Comment by cboettig** [comment]
Nice! sorry I missed that.  All working now.  

In case it's useful wiki fodder, I just updated [the above gist](https://gist.github.com/cboettig/8643341bd3c93b62b5c2) btw, other than dropping in a valid `.crt` and `.key` it should be a portable example anyone can run with a quick download & `docker-compose up -d`.  Thanks for the help!

**Comment by parente** [comment]
Excellent. Would you mind adding a small section linking to that gist over on the [recipes wiki page](https://github.com/jupyter/docker-stacks/wiki/Docker-Recipes)?

**Comment by cboettig** [comment]
thanks for the link; done.

**Comment by cboettig** [comment]
@parente @ben-github hmm.. I've just come back to trying to run this, and now I find that while I can log in with this configuration, I cannot (or can no longer?), and launch a notebook, but it consistently errors with "cannot connect to kernel".  (Likewise I cannot start a terminal instance, though I just end up then with a blank screen rather than an error)....  hmm...  Any ideas?

Unless someone can confirm that the recipe I copied over to the wiki actually still works, I think I should re-open this issue.

**Comment by ben-github** [comment]
What version of nginx are you using? To connect to the kernel, you need websockets, which nginx 1.2 doesn't have. The code I posted above works for me with nginx 1.6 (but not 1.2).

**Comment by cboettig** [comment]
nginx 1.9 

(which is nginx:latest in docker; what you'll get if you just run `docker-compose up` with my sample config: https://gist.github.com/cboettig/8643341bd3c93b62b5c2)

**Comment by ben-github** [comment]
Maybe try nginx 1.6 and see if that works. Maybe some options changed from 1.6 to 1.9.

**Comment by cboettig** [comment]
@ben-github Same problem in 1.7, Docker doesn't have images any further back.  I'd be surprised if the newer nginx version was the problem though -- more like I've mislaid something in my config https://gist.github.com/cboettig/8643341bd3c93b62b5c2, but I certainly can't spot it.

**Comment by parente** [comment]
@cboettig In another issue I think you said you updated the gist with a functioning nginx config. If that's correct, can we close this one?

**Comment by cboettig** [comment]
Yup

On Tue, Jan 12, 2016, 6:49 PM Peter Parente <notifications@github.com>
wrote:

> @cboettig <https://github.com/cboettig> In another issue I think you said
> you updated the gist with a functioning nginx config. If that's correct,
> can we close this one?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/docker-stacks/issues/76#issuecomment-171140846>
> .
>
-- 

http://carlboettiger.info

**Comment by parente** [comment]
Cool. Thanks.
