### ISSUE TITLE
Community Stacks - Build error on cloud.docker.com - post_push hook - No such file or directory

### ISSUE THREAD

**Issue by tlinnet** [jupyter/docker-stacks#763]
Hi !

I am trying your new guide for [Community Stacks](https://jupyter-docker-stacks.readthedocs.io/en/latest/contributing/stacks.html).

It's very well written!

I aim for a little project to bring C# to Jupyter Notebook. To try it out easily.
* Github repo: [github.com/tlinnet/csharp-notebook](https://github.com/tlinnet/csharp-notebook)
* Cloud Docker: [cloud.docker.com/repository/docker/tlinnet/csharp-notebook](https://cloud.docker.com/repository/docker/tlinnet/csharp-notebook)

When I try to build on cloud.docker.com, I get an error.

```
Done building project "/icsharp/iCSharp.sln".
Build succeeded.
0 Warning(s)
0 Error(s)
Time Elapsed 00:00:44.5250460
Removing intermediate container 0be778c8290f
---> e9e1e0c44f40
Step 6/8 : RUN chown -R $NB_USER:users $HOME/.local && chown -R $NB_USER:users $HOME/.mono && chown -R $NB_USER:users $HOME/.nuget && echo '{' > /icsharp/kernel-spec/kernel.json && echo ' "argv": ["mono", "/icsharp/build/Release/bin/iCSharp.Kernel.exe", "{connection_file}"],' >> /icsharp/kernel-spec/kernel.json && echo ' "display_name": "C#",' >> /icsharp/kernel-spec/kernel.json && echo ' "language": "csharp"' >> /icsharp/kernel-spec/kernel.json && echo '}' >> /icsharp/kernel-spec/kernel.json
---> Running in 275eef437144
Removing intermediate container 275eef437144
---> c2b6d3bbd9c1
Step 7/8 : USER $NB_USER
---> Running in 6f3ad61d6409
Removing intermediate container 6f3ad61d6409
---> 21cc03db1a83
Step 8/8 : RUN cd /icsharp && jupyter-kernelspec install --user kernel-spec
---> Running in 9a91d96d4d41
[InstallKernelSpec] Installed kernelspec kernel-spec in /home/jovyan/.local/share/jupyter/kernels/kernel-spec
Removing intermediate container 9a91d96d4d41
---> d3ce35014d12
Successfully built d3ce35014d12
Successfully tagged tlinnet/csharp-notebook:latest
Pushing index.docker.io/tlinnet/csharp-notebook:latest...
Done!
Executing post_push hook...
Unexpected error
Encountered error: [Errno 2] No such file or directory
Traceback (most recent call last):
File "/stage/builder/runner.py", line 292, in _run
self.push()
File "/stage/builder/runner.py", line 246, in push
hooks.run('post_push')
File "/stage/builder/hooks.py", line 21, in run
utils.execute_command(hook_path, '{} hook failed!'.format(name))
File "/stage/builder/utils.py", line 43, in execute_command
bufsize=1)
File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory
```

The post_push folder is part of the repo, and looks normal.

**Comment by parente** [comment]
Thanks for reporting this @tlinnet. I wonder if there's an extra config step in the Docker Cloud UI that we forgot to mention to allow `post_push` to execute `docker`. I'll have to take a pass through the build jobs.

Out of curiosity, has the build failed this way multiple times?

**Comment by tlinnet** [comment]
Hi. I have only tried to build like this on cloud.docker.com 1 time. 

The error message for me, looks like something cannot find a file. The "post_push" hook? But I don't know where to start debugging.

**Comment by parente** [comment]
@tlinnet I took a look at your repo setup and what I can see of the Docker Hub project setup. Everything looks in order. If you manually trigger the build using the Docker Hub web UI, do you get the same error? I wonder if it was a transient Docker Hub build error.

**Comment by tlinnet** [comment]
Hm. This looks like an issue with Windows.

I created the project on Win10. The first thing I noticed, that when I visited the file through github, the file was not marked as executable. The command ' git update-index --chmod=+x post_push' changed that. Then I tried removing the shebang line 

```
Done!
Executing post_push hook...
Could not execute hook at 'hooks/post_push'. Is it missing a #! line?
```

or changing to '#!/usr/bin/env bash'.
```
Executing post_push hook...
/usr/bin/env: 'bash\r': No such file or directory
post_push hook failed! (127)
```

The post_push file has Windows (CR LF) as line endings instead of linux (LF). I have now converted the file in Notepad++ and try again.

**Comment by tlinnet** [comment]
Indeed....

It was a problem of line endings in Windows.
After conversion everything is smooth.

This is **hooks/post_push** as executable with Linux line endings (LF)

```
#!/bin/bash

# e: Exit when first line is an error: x: Echo info per command
set -e
echo "IMAGE_NAME: $IMAGE_NAME"
echo "DOCKER_REPO: $DOCKER_REPO"
echo "SOURCE_COMMIT: $SOURCE_COMMIT"
set -ex
# Tag the latest build with the short git sha. Push the tag in addition to the "latest" tag already pushed.
GIT_SHA_TAG=${SOURCE_COMMIT:0:12}
docker tag $IMAGE_NAME $DOCKER_REPO:$GIT_SHA_TAG
docker push $DOCKER_REPO:$GIT_SHA_TAG
```


```
Successfully built f3c985065762
Successfully tagged tlinnet/csharp-notebook:latest
Pushing index.docker.io/tlinnet/csharp-notebook:latest...
Done!
Executing post_push hook...
IMAGE_NAME: index.docker.io/tlinnet/csharp-notebook:latest
DOCKER_REPO: index.docker.io/tlinnet/csharp-notebook
SOURCE_COMMIT: 9691abc749cb952c8d39dc342e1b490b6282be46
+ GIT_SHA_TAG=9691abc749cb
+ docker tag index.docker.io/tlinnet/csharp-notebook:latest index.docker.io/tlinnet/csharp-notebook:9691abc749cb
+ docker push index.docker.io/tlinnet/csharp-notebook:9691abc749cb
The push refers to repository [docker.io/tlinnet/csharp-notebook]
```
