### ISSUE TITLE
GRANT_SUDO=yes still doesn't seem to work

### ISSUE THREAD

**Issue by terrisgit** [jupyter/docker-stacks#770]
Sorry, this is an issue that doesn't seem to die. I would like to add some JARs via sudo. Perhaps there is a better way to do that but sudo would come in handy for other tasks.

(1)
docker run -d -v $PWD:/home/jovyan/work -e GRANT_SUDO=yes -p 8888:8888 jupyter/all-spark-notebook

(2)
Get the container id via:

docker ps

(3)
docker exec -it __containerid__ bash

(4)
sudo ls

Prompts for password for user jovyan

**Comment by parente** [comment]
Try adding `--user root` to your run command. The doc for `GRANT_SUDO` explains why (https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html). Maybe we can make it clearer since it seems to trip a lot of people up.

**Comment by terrisgit** [comment]
How does one avoid running Jupyter as root if you do this?

**Comment by terrisgit** [comment]
Thanks. So here is an example

```docker run -d -v $PWD:/home/jovyan/work -e GRANT_SUDO=yes --user root -p 8888:8888 jupyter/all-spark-notebook```

**Comment by rjurney** [comment]
This isn't working for me...

**Comment by mathbunnyru** [comment]
@rjurney please, create a new issue, where you describe in full, what command you're running and the problem you have.
