### ISSUE TITLE
Error building base-notebook

### ISSUE THREAD

**Issue by rwmajor2** [jupyter/docker-stacks#771]
**What docker image you are using?**

`jupyter/base-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

`docker build --build-arg NB_USER=arcgis --build-arg NB_UID=1050 -t myrun:base-notebook-0.2 .`

**What steps do you take once the container is running to reproduce the issue?**

**What do you expect to happen?**

For it to build correctly.

**What actually happens?**

```Errored, use --debug for full output:
ValueError: Please install nodejs >=6.11.5 before continuing. nodejs may be installed using conda or directly from the nodejs website.
The command '/bin/sh -c conda install --quiet --yes     'notebook=5.7.2'     'jupyterhub=0.9.4'     'jupyterlab=0.35.4' &&     conda clean -tipsy &&     jupyter labextension install @jupyterlab/hub-extension@^0.12.0 &&     npm cache clean --force &&     jupyter notebook --generate-config &&     rm -rf $CONDA_DIR/share/jupyter/lab/staging &&     rm -rf /home/$NB_USER/.cache/yarn &&     fix-permissions $CONDA_DIR &&     fix-permissions /home/$NB_USER' returned a non-zero code: 1
```

**Comment by parente** [comment]
FWIW: The daily cron rebuild on Travis CI has been succeeding using the commands in the `Makefile` and `.travis.yml`. Not clear why a manual rebuild with the args you've given would fail.

**Comment by ianalis** [comment]
I also encountered the same problem. It seems a dependency of `jupyterhub` is `configurable-http-proxy`, which, in turn, depends on `nodejs=6.*`. The latest available `nodejs 6.*` though is `6.11.2` hence the `nodejs >= 6.11.5` requirement fails. I don't know if there's a more elegant solution/workaround but what I did was to explicitly install the latest version of `nodejs` (`nodejs=10.13.*`) along with `jupyterhub=0.9.4`.

**Comment by parente** [comment]
We've not seen a similar build failure in the daily Travis cron or the release builds on Docker Hub. I'm inclined to close the issue unless someone states the problem still exists and can provide a bit more context. For instance, is the docker build command from the description being run in the base-notebook subdir?
