### ISSUE TITLE
apt-get clean redundant in these ubuntu images

### ISSUE THREAD

**Issue by consideRatio** [jupyter/docker-stacks#776]
Apparently apt-get clean is a redundant command if using an official ubuntu image as we are doing, so at worst we have additional time:

> In addition, when you clean up the apt cache by removing /var/lib/apt/lists it reduces the image size, since the apt cache is not stored in a layer. Since the RUN statement starts with apt-get update, the package cache is always refreshed prior to apt-get install.
> 
> Official Debian and Ubuntu images automatically run apt-get clean, so explicit invocation is not required.

https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run

Feel free to close this without further action!

**Comment by parente** [comment]
Fixed in #777.
