### ISSUE TITLE
Can't make ODBC connection in Docker Jupyter R Notebook running R version 3.5.1?

### ISSUE THREAD

**Issue by heoa** [jupyter/docker-stacks#794]
I need ODBC driver to work with Jupyter Docker R notebook but the following packages fire errors

    install.packages("unixodbc-dev")
    install.packages("odbc")
    install.packages("RODBC")
    install.packages("r-cran-rodbc")
    install.packages("unixodbc")

further details in SO [here](https://stackoverflow.com/questions/54057120/odbc-driver-for-jupyter-r-notebook-based-on-jupyter-docker-stack).

**Is there some ready ODBC package preinstalled in Docker R Jupyter Notebook? Or what is your intended way to make the ODBC connection?**

*Version*

> platform       x86_64-conda_cos6-linux-gnu 
> arch           x86_64                      
> os             linux-gnu                   
> system         x86_64, linux-gnu           
> status                                     
> major          3                           
> minor          5.1                         
> year           2018                        
> month          07                          
> day            02                          
> svn rev        74947                       
> language       R                           
> version.string R version 3.5.1 (2018-07-02)
> nickname       Feather Spray               

**Potential fix**

The installation of the debian/ubuntu package as required in Docker file such that

     sudo apt-get install r-cran-rodbc

as illustrated [here](https://superuser.com/questions/283272/problem-with-rodbc-installation-in-ubuntu/283274).

**Comment by itnavigate** [comment]
Nice that this is closed - I assume you found a resolution. I note SO question is also deleted.
I have a similar (perhaps even the same) problem. What was you resolution @heoa?
did r-cran-rodbc fix it for you?
