### ISSUE TITLE
Adding nbgrader to the datascience stack or just make a new recipe?

### ISSUE THREAD

**Issue by damianavila** [jupyter/docker-stacks#799]
Howdy all,

I think a lot of people would find useful to have nbgrader in the data science notebook stack.
I also saw someplaces in the docs to add custom recipes.
I raised this issue just to discuss if I should contribute with a recipe or if it is worth to add nbgrader in the default data science stack (I would prefer the second option but I am interested about what the community thinks about this).

Ping @parente @jhamrick for thoughts... and everyone else who wants to chime in :wink:

**Comment by parente** [comment]
> I am interested about what the community thinks about this.

If there's enough support for it, let's get it in. My main concern is that, if I remember correctly, nbgrader is a notebook extension too, so it'll suddenly appear in the toolbar for everyone using the image, including people using jupyter/datasciece-notebook in a non-academic context.

Some alternatives to consider:

* Using github.com/jupyter/repo2docker to make an education specific image.
* Making a community maintained jupyter-for-education docker stack which can be based on jupyter/datascience-notebook but adds education specific extensions (https://jupyter-docker-stacks.readthedocs.io/en/latest/contributing/stacks.html, https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#community-stacks)

**Comment by damianavila** [comment]
> My main concern is that, if I remember correctly, nbgrader is a notebook extension too, so it'll suddenly appear in the toolbar for everyone using the image, including people using jupyter/datascience-notebook in a non-academic context.

That's a reasonable concern.

> Making a community maintained jupyter-for-education docker stack which can be based on jupyter/datascience-notebook but adds education specific extensions (https://jupyter-docker-stacks.readthedocs.io/en/latest/contributing/stacks.html, https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#community-stacks)

I like this second idea. We can put RISE and nbgrader at first and then add some other tools (by request) useful for education.

If we get enough traction, I guess, we can probably move the stack into the core, right? How we define what images live on this repo?

**Comment by parente** [comment]
> If we get enough traction, I guess, we can probably move the stack into the core, right? How we define what images live on this repo?

We've tried to freeze the number of images here and encourage new repos for all new images for reasons first documented in #517. #693 is an example (stalled) PR trying to *remove* some of the images here already. There's been discussions of splitting up the repo as well.

I think a new repo in https://github.com/jupyter/docker-for-education having just that image definition would work best. It can still be jupyter associated and can move at whatever pace the maintainers want to set for it, without having to also worry about builds failing, package updates, etc. for these other images.

**Comment by damianavila** [comment]
I think I would probably go in the other direction, I mean... we can create a repo in whatever place containing this education-notebook image. If we get enough traction, we can think about requesting the repo to be moved in the Jupyter space. In this way, we filter out the case where we created a new official jupyter repo that does not have any maintenance people behind it.

Let create the tool and the community supporting it and then we can graduate that project later down the road. I think that is probably a more sustainable way to do it.

How does it sound?

Obviously I will PR against this repo to update the community stack section :wink:

**Comment by parente** [comment]
I think you're on the right track. Thanks for sharing what you're working on, @damianavila.

For those following along, the new image is in https://github.com/umsi-mads/education-notebook and now linked from the docker-stacks docs. I'm going to close out this issue as solved.
