### ISSUE TITLE
non-conda R packages

### ISSUE THREAD

**Issue by vilhelmen** [jupyter/docker-stacks#806]
Hi everyone. Due to some various conda package issues, I was installing r-rgdal through `install.packages` with `libgdal` provided through apt and a very long and painful story short, conda's R support for building package using system libraries is [flakey or even being removed](https://github.com/conda-forge/r-base-feedstock/issues/68).

With r-base 3.5.1, build `h391c2eb_5` supports building with system libraries but `he45234b_1005` does not. Is this something the community is aware of, or is `install.packages` generally unsupported in these containers? Does anyone have experience getting system libraries to work when conda doesn't provide either the r package or a library dependency?

**Comment by rkingdc** [comment]
You could take a look at the official R docker images at [rocker/geospatial](https://github.com/rocker-org/geospatial/blob/master/Dockerfile)

Looks like the install all needed dependencies and use `littler`'s `install2.r`, which is basically a nice cli wrapper for `install.packages`

**Comment by parente** [comment]
Installing Jupyter components in R-heavy images is probably a much easier path to walk than the other way around, so 👍 to @rkingdc 's suggestion.

FWIW, we're starting to experiment with a general Q&A section on https://discourse.jupyter.org/c/questions to see if cross-technology questions like this one catch more attention from a broader community audience. You might try re-posting your question over there to see if there are other suggestions.

I'm going to close this issue as answered here. If you do post the question again on the Discourse site, feel free to leave a link in a comment for those that happen upon this closed issue.
