### ISSUE TITLE
r-rgdal package installed correctly, but dependency libraries are not installed.

### ISSUE THREAD

**Issue by drzhouq** [jupyter/docker-stacks#808]
**What docker image you are using?**

Example: `jupyter/r-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

Example: `docker run -it --rm -p 8889:8888 jupyter/r-notebook:latest`

**What steps do you take once the container is running to reproduce the issue?**
0. get into the docker shell to run `conda install -y r-rgdal`. It finished without issue
1. Visit http://localhost:8889
2. Start an R noteobok
3. input `library('rgdal')`

**What do you expect to happen?**

The rgdal library should be loaded.

**What actually happens?**
complains a dependency is not met. 
Error: package or namespace load failed for ‘rgdal’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/opt/conda/lib/R/library/rgdal/libs/rgdal.so':
  libpoppler.so.76: cannot open shared object file: No such file or directory

There is a /opt/conda/lib/libpoppler.so.78, apparently newer library is in place but the rgdal still links to an older version.

**Comment by parente** [comment]
The problem is likely with the rgdal package in conda-forge. This upstream issue looks relevant: https://github.com/conda-forge/r-rgdal-feedstock/issues/18

**Comment by dzanaga** [comment]
This is a working solution to this issue:

```
RUN apt-get update && \
    apt-get install -y gdal-bin

USER jovyan

RUN conda install -y gdal && \
    echo "install.packages('rgdal',repos='https://cran.rstudio.com',configure.args=c('--with-gdal-config=/opt/conda/bin/gdal-config', '--with-proj-include=/opt/conda/include','--with-proj-lib=/opt/conda/lib','--with-proj-share=/opt/conda/share/proj/'))" | R --no-save && \
    echo "install.packages('gdalUtils',repos='https://cran.rstudio.com')" | R --no-save
```
I build an image starting from the ```all-spark-notebook```, adding these commands. I assume you can do that from the `r-notebook` as well, or type these commands directly in the container.

**Comment by drzhouq** [comment]
Thanks @dzanaga and @parente for your valuable inputs.
