### ISSUE TITLE
Adding dask to the scipy-notebook

### ISSUE THREAD

**Issue by jakirkham** [jupyter/docker-stacks#816]
Currently the `scipy-notebook` indirectly pulls in `dask-core` through `scikit-image`. That said, there are a fair number of users that will expect a fully featured dask install when they find it is in the image. Would suggest we go ahead and add the `dask` Conda package to the dependencies explicitly. This should pull in the fully featured dask install from conda-forge. Thoughts?

**Comment by parente** [comment]
Agree since dask is already present.

**Comment by jakirkham** [comment]
Added PR ( https://github.com/jupyter/docker-stacks/pull/817 ).
