### ISSUE TITLE
add the `datascience` module to the jupyter/datascience-notebook stack?

### ISSUE THREAD

**Issue by cboettig** [jupyter/docker-stacks#83]
As you may know, UC Berkeley is teaching an introductory data science course entirely in Jupyter notebooks (see http://data8.org) ; which makes heavy use of the `datascience` module that is being developed in parallel with the course (https://github.com/dsten/datascience).  Seems like it would thus be a good fit for datascience stack.  

Thanks for considering!

**Comment by dartdog** [comment]
just looked at 'datascience', it is not immediately clear what this does (or proposes to do) that the current pandas/numpy and statsmodels libraries do not? Most initial functionality looks duplicative to me?

**Comment by cboettig** [comment]
@dartdog correct.  The package is being developed by several faculty and collaborators at UC Berkeley to provide a lower bar to entry than pandas, particularly for instructional purposes.  Yes, it is very much a subset of pandas motivated by what makes for good pedagogy rather than good performance.

So for the moment the only audience would be the several hundred students a year at Berkeley wanting to build on the methods they learn in that course, as well as anyone else learning from the openly developed course material based on this, http://data8.org.  Sorry that I didn't explain that better or if instruction / education is outside of the use case you are trying to support.

**Comment by dartdog** [comment]
Just a personal opinion, (I am not on the project team) that the students
would be way better served by teaching an introductory subset of the real
thing, Pandas, than getting them stuck in a purpose built limited
library..Where among other things they won't even learn to use the fine
documentation provided by the "real thing" (it just is not that complex..)

**Comment by cboettig** [comment]
@dartdog I completely understand that perspective, but the question of what the course or campus *should* teach is beyond the scope of the issue here. 

I only observe that many students *are* learning the `datascience` module (in a class that is entirely based on cloud Jupyter notebooks, even the textbook, http://data8.org/text is a jupyter notebook) and I thought it would be able to point them at some stage to this stack.

**Comment by parente** [comment]
> So for the moment the only audience would be the several hundred students a year at Berkeley wanting to build on the methods they learn in that course, as well as anyone else learning from the openly developed course material based on this

Based on the current scope, I think the library is more suitable to a recipe that students can follow to get it installed atop the datascience-notebook stack (e.g., using pip, using a Dockerfile). If the library becomes more widely used, then we should certainly re-evaluate. Filling in the API documentation at http://data8.org/datascience/ as a reference to compliment the text-book-of-notebooks (naming is hard!) at http://data8.org/text might help in this regard.

**Comment by cboettig** [comment]
Thanks
