### ISSUE TITLE
 import rpy2.robjects error

### ISSUE THREAD

**Issue by aabor** [jupyter/docker-stacks#840]
I am trying to import rpy2.robjects from rpy2 library. 

`
import rpy2.robjects as robjects
from rpy2.robjects import pandas2ri
pandas2ri.activate()
`
which gives me error message.

There were not such a problem in notebook image with this tag:
jupyter/datascience-notebook:635a1d142580

But when I upgraded to jupyter/datascience-notebook:be289da10d60
the problem arose.

As a work around I downgraded image version to previous mentioned one, please, make some tests on this library to resolve the issue for the long run.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-9-33eceeb7f902> in <module>
----> 1 import rpy2.robjects as robjects
      2 import rpy2.robjects.numpy2ri
      3 from rpy2.robjects.packages import importr
      4 r = robjects.r
      5 rpy2.robjects.numpy2ri.activate()

/opt/conda/lib/python3.7/site-packages/rpy2/robjects/__init__.py in <module>
     14 import itertools
     15 from datetime import datetime
---> 16 import rpy2.rinterface as rinterface
     17 import rpy2.rlike.container as rlc
     18 

/opt/conda/lib/python3.7/site-packages/rpy2/rinterface/__init__.py in <module>
     49 del(os)
     50 
---> 51 from rpy2.rinterface._rinterface import (baseenv,
     52                                          emptyenv,
     53                                          endr,

ImportError: libgfortran.so.3: cannot open shared object file: No such file or directory

**Comment by parente** [comment]
This is likely a problem with the upstream conda-forge package for rpy2: https://github.com/conda-forge/rpy2-feedstock/pulls

**Comment by mathbunnyru** [comment]
@aabor the issue seems to be resolved, because I was able to run your commands in the latest image.

> As a work around I downgraded image version to previous mentioned one, please, make some tests on this library to resolve the issue for the long run.

I'm closing this issue for now, because I think everything is going to be fine.
If you want to be on a safe side, please, make a PR adding the test like you suggest.

The best way is to just copy the existing test and change some lines to use the needed library.
https://github.com/jupyter/docker-stacks/blob/master/scipy-notebook/test/test_pandas.py
