### ISSUE TITLE
requests-html module can't find

### ISSUE THREAD

**Issue by solider245** [jupyter/docker-stacks#841]
![image](http://ws4.sinaimg.cn/large/6613a37fgy1g1qbl7yy29j20kr03qwen.jpg)

requests-html module can't find

It is a new but it is very important.

**Comment by parente** [comment]
We don't include that module in any of the images by default. You can `pip install` it most likely or create a custom Docker image in which you install it:

```
FROM jupyter/minimal-notebook:ae5f7e104dd5
RUN pip install -yq requests
```

It doesn't appear to be packaged on conda-forge for conda install.

**Comment by solider245** [comment]
> We don't include that module in any of the images by default. You can `pip install` it most likely or create a custom Docker image in which you install it:
> 
> ```
> FROM jupyter/minimal-notebook:ae5f7e104dd5
> RUN pip install -yq requests
> ```
> 
> It doesn't appear to be packaged on conda-forge for conda install.

thank you for answer。
