### ISSUE TITLE
Trouble installing keras

### ISSUE THREAD

**Issue by vtrajan** [jupyter/docker-stacks#843]
I got similar problem when trying to install keras:

(FYI: I just installed anaconda for my use only. Should I have installed it in the root?
I had it installed in the root before, then removed it.)

Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(568): An error occurred while uninstalling package 'defaults::python.app-2-py37_9'.
PermissionError(1, 'Operation not permitted')
Attempting to roll back.

Rolling back transaction: done

[Errno 1] Operation not permitted: '/Users/vtrajan/anaconda3/python.app/Contents/PkgInfo' -> '/Users/vtrajan/anaconda3/python.app/Contents/PkgInfo.c~'

**Comment by parente** [comment]
```
[Errno 1] Operation not permitted: '/Users/vtrajan/anaconda3/python.app/Contents/PkgInfo' -> '/Users/vtrajan/anaconda3/python.app/Contents/PkgInfo.c~'
```

Looks like you're using conda directly on your Mac, not in the docker images maintained here. Please try asking your question or filing an issue in the appropriate anaconda/conda forum. 

* https://support.anaconda.com/
* https://github.com/conda/conda
