### ISSUE TITLE
Can someone explain why SBT is specifically removed from this image?

### ISSUE THREAD

**Issue by dartdog** [jupyter/docker-stacks#86]
Seems that it may have use for various Scala/Spark functions? (I'm over my head here though!)
I just noticed it was specifically removed form the image.. and I was looking to use it in the Jupyter console shell?

**Comment by parente** [comment]
SBT is only needed to compile the Scala Spark kernel. After that, it's removed to cut down on the image size. We could keep it in if there's a strong need for having it remain in the image for use in the notebook afterward, at a cost of making the image bigger.

**Comment by parente** [comment]
@dartdog Any strong feelings on this, one way or the other?

**Comment by dartdog** [comment]
Not really, since I'm still a neophyte, but the code I get from co-workers
relies on SBT to run and needs refactoring to be useful in Jupyter. So it
is different use cases but not having it makes for lack of smooth
transitions, IMHO. Maybe once I get more experiance I'll have a valid
opinion, thanks for asking!

**Comment by parente** [comment]
I'm not a Scala guru by any means either. I'll leave this open for you to check back in as you gain experience. Thanks!

**Comment by parente** [comment]
I'm going to close this issue because it's been inactive for a few months. If you find a common use case that requires sbt in the image, please feel free to open a new issue or PR.
