### ISSUE TITLE
Permission denied, Windows 10 WSL

### ISSUE THREAD

**Issue by itaysk** [jupyter/docker-stacks#862]
I'm running Windows 10 - WSL Ubuntu (docker for windows)

**What docker image you are using?**
`jupyter/pyspark-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**
`docker run -it --rm -p 8888:8888 -v $(pwd)/work:/home/jovyan/work jupyter/pyspark-notebook`

**What steps do you take once the container is running to reproduce the issue?**
try to create a file under `work`

**What do you expect to happen?**
succeed

**What actually happens?**
Permission denied
in container stdout:
```
[I 17:21:12.670 NotebookApp] Creating new file in /work
[W 17:21:12.672 NotebookApp] 403 POST /api/contents/work (172.17.0.1): Permission denied: work/untitled.txt
[W 17:21:12.672 NotebookApp] Permission denied: work/untitled.txt
[W 17:21:12.673 NotebookApp] 403 POST /api/contents/work (172.17.0.1) 4.25ms referer=http://localhost:8888/tree/work
```
Here's the dir listing from working dir:
`drwxrwxrwx 1 itaysk 512 May  3 19:46 work`
in the container:
`uid=1000(jovyan) gid=100(users) groups=100(users)`
on host:
`uid=1000(itaysk) gid=1000(itaysk) groups=1000(itaysk) ...`

adding `--user $(id -u):$(id -g)` didn't help. 
also tried mounting a windows dir and a wsl dir, both scenarios failed.

From my understanding the fact that it's the same uid (1000) should be enough right?

**Comment by parente** [comment]
This behavior sounds suspiciously related to https://github.com/jupyter/docker-stacks/issues/542#issuecomment-379515332. The setup is not quite the same, but I wonder if the host OS -> hypervisor running Docker daemon on Windows/macOS -> container user mapping is causing grief.

**Comment by itaysk** [comment]
I wanted to simulate the mac test, but couldn't get through creating the file:
```
❯ docker run -it --rm -p 8888:8888 -v $(pwd)/work2:/home/jovyan/work -e NB_UID=1234 -e NB_GID=1234 --user root jupyter/pyspark-notebook star
t.sh
Set username to: jovyan
usermod: no changes
Set jovyan UID to: 1234
Add jovyan to group: 1234
Executing the command: bash
jovyan@f6ca893feb55:~$ echo "foo" > work/foo
bash: work/foo: Permission denied
jovyan@f6ca893feb55:~$ cd work/
jovyan@f6ca893feb55:~/work$ ll
total 4
drwxr-xr-x 2 root   root     40 May  4 15:45 ./
drwsrwsr-x 1 jovyan jovyan 4096 Apr 25 18:21 ../
```

**Comment by parente** [comment]
Hmm. I unfortunately do not have a Win10 environment to help debug the issue myself. I wonder what owner, group, and permissions you'll see in the container if you create a file in the host-mounted directory *from the Windows side (i.e., in *$(pwd)/work*). Maybe that'll provide more information about the problem?

**Comment by dzanaga** [comment]
I also use docker with WSL and I can run jupyter containers without issues. Maybe it's a problem related to your Docker setup with WSL?
I followed this guide to set it up: https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly
I speculate the main problem is your mount point. In WSL you need to bind /mnt/c to /c and then you need to mount volumes with the path starting from /c, e.g. `-v /c/Users/yourname/your/folder:/home/jovyan/work`.
What is the full path you are giving when you expand `pwd`?

I tried with:
```
# Start container
JUPY_CONTAINER_NAME="jupytest"
IMAGE="jupyter/base-notebook:latest"

HOST_WORK=`pwd`
CONTAINER_WORK=/home/jovyan/work

docker run -it --rm \
  -p 8888:8888 \
  -v "${HOST_WORK}":"${CONTAINER_WORK}" \
  $IMAGE start-notebook.sh
```
and can save files to the mounted folder. 

As a side note, WSL handles file permissions in different way than linux, everything is owned by root. It does not make much difference in my experience to run the containers with the --user option in WSL...

**Comment by itaysk** [comment]
@dzanaga Thank you! As a matter of fact I did setup my docker according to the same guide, but I forgot when running the command to use the /c mount and not the /mnt mount. Confirmed working now.
