### ISSUE TITLE
Should conda-metachannel be used instead of conda-forge?

### ISSUE THREAD

**Issue by echowhisky** [jupyter/docker-stacks#865]
Anaconda made a [post](https://www.anaconda.com/understanding-and-improving-condas-performance/) back in March about improving the performance of conda.  @parente mentioned it [here](https://github.com/jupyter/repo2docker/pull/666#issuecomment-489366493) when discussing a different issue (hardlinks), but at the top of the post it mentions several times the idea of using the `conda-metachannel` instead of `conda-forge`. The docker-stacks containers don’t currently do this. 

* Is the use of `conda-metachannel` established and stable enough?
* Would the use of `conda-metachannel` solve any issue or improve things enough to merit a change?
* Would the use of `conda-metachannel` cause some issue or problem?

More information about [conda-metachannel](https://medium.com/@marius.v.niekerk/conda-metachannel-f962241c9437).

**Comment by betatim** [comment]
One thing I didn't realise from the Anaconda blog post nor the linked Medium post: there is now a live hosted version of this! Take a look at https://github.com/regro/conda-metachannel, the live instance is linked at the top of the README.

**Comment by betatim** [comment]
Just did a small experiment in repo2docker: we install a basic environment for every repository and for this we know the list of packages up front. So I went and replaced the list of channels in the `environment.yml` that we use with `https://metachannel.conda-forge.org/defaults,conda-forge/notebook,nbconvert,jupyterlab,ipywidgets,python,ipykernel` building a trivial repository with this takes basically the same time as without metachannel. 2:05minutes (`master`, no meta channel) vs 2:25min (with metachannel). I think the slight slowdown could just be noise?? Either way it seems like this doesn't buy as a huge amount in repo2docker.

Maybe at a later point when there is tooling to autogenerate the metachannel link we can trial it for user environments.

**Comment by parente** [comment]
Hazarding a guess, metachannel might help with the build time of the scipy-notebook and r-notebook images which both install non-trivial packages using conda. That said, I don't know the current build time of the conda install step in either, and so they might not be worth the effort.

**Comment by betatim** [comment]
Now I can use my favourite quote related to optimisation things: "Measuring is what gives me a leg up on experts who are too good to measure". We should all measure more so we can get ahead of the experts :)

**Comment by javabrett** [comment]
My only comment is that I have found the presence of `conda-forge` in the default-channels of images to cause stability issues.  Mostly this is when trying to manage Conda envs e.g. cloning etc.  That tooling is very unforgiving of packages which have been replaced/removed, and this happens in the `conda-forge` channel all the time - an exact version is there one day and not the next.

**Comment by mathbunnyru** [comment]
`conda-metachannel` is unmaintained and hasn't received update for some time (https://github.com/regro/conda-metachannel).
And, they suggest to use `mamba`, if one wants to have faster alternative to conda.
And, we already install mamba for all the images and it is even used in tensorflow image.

So, I think this issue can be closed.
Please, reopen, if you think otherwise.

**Comment by mathbunnyru** [comment]
`conda-metachannel` is unmaintained and hasn't received update for some time (https://github.com/regro/conda-metachannel).
And, they suggest to use `mamba`, if one wants to have faster alternative to conda.
And, we already install mamba for all the images and it is even used in tensorflow image.

So, I think this issue can be closed.
Please, reopen, if you think otherwise.
