### ISSUE TITLE
Enable magics %%spark and/or %%sql

### ISSUE THREAD

**Issue by aaronsteers** [jupyter/docker-stacks#868]
```
Hi! Thanks for using the Jupyter Docker Stacks.

Please review the following guidance about how to ask questions, contribute changes, or report bugs in the Docker images maintained here.

1. If you have a general question about using these Docker images or with Jupyter + Docker in general, please post your question in the [Jupyter Discourse Q&A section](https://discourse.jupyter.org/c/questions) so that it can be seen, discussed, and hopefully answered by the community.

2. If you are looking to contribute to the images, please see the [Contributor's Guide](http://jupyter-docker-stacks.readthedocs.io/en/latest/#) in the documentation for our preferred processes.

3. If you are reporting an issue with one of the existing images, please answer the questions below to help us troubleshoot the problem. Please be as thorough as possible.
```

**What docker image you are using?**

`jupyter/all-spark-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

```
docker-compose run $MODAL_FLAGS \
    -p $LOCAL_PORT:$INTERNAL_PORT \
    --name $CONTAINER_NAME \
    $DOCKER_SERVICE_NAME start.sh jupyter $LAB_OR_NOTEBOOK \
      --NotebookApp.notebook_dir="/home/jovyan/work";
```

**What steps do you take once the container is running to reproduce the issue?**

1. Open a Python notebook.
2. Attempt to load spark magic using loadextention (fails)
3. Attempt to load spark magic using %%sql and/or %%spark (fails)

**What do you expect to happen?**

Would expect to see Spark and SparkSQL magics support in the Spark-targeted notebook image.

**What actually happens?**

No support yet for %%sql or %%spark.

**Comment by parente** [comment]
You're right that there is no kernel or package installed in the Spark images that provides`%%sql` and `%%spark` magics by default. The Apache Toree kernel in `jupyter/all-spark-notebook` has some magics for loading JARs and other actions, but I'm not sure about writing raw SQL in a cell.

Did you have an extension in mind? What would `%%spark` provide above and beyond what the kernels in the images already support (https://jupyter-docker-stacks.readthedocs.io/en/latest/using/specifics.html#apache-spark)?

**Comment by aaronsteers** [comment]
For my primary use case, I'd like users to be able to type SparkSQL queries directly, and have them execute against the default or local spark implementation, without having to wrap the query in Python. So, for instance, after writing some data to a spark or hive table, I could write:

%%sql
CREATE TABLE myTable
as
SELECT t1.*, t2.extra_col 
FROM t1 
JOIN t2 USING my_key

#Separate Cell:
%%sql
SELECT * FROM myTable 
WHERE extral_col IS NOT NULL
```

**Comment by aaronsteers** [comment]
The jupyter-incubater/sparkmagic project seems to support this use case:
https://github.com/jupyter-incubator
 https://github.com/jupyter-incubator/sparkmagic/blob/master/examples/Spark%20Kernel.ipynb

**Comment by sgloutnikov** [comment]
I briefly looked at the sparkmagic project myself, but have not really tested it to see if it will work with Toree on the Jupyter Spark images--it is built to work with remote Spark clusters through Livy. Right now the all-spark-notebook images work amazingly well out of the box with Toree, but if there is a way to also get %%sql for SparkSQL it would be amazing.

**Comment by aaronsteers** [comment]
Agreed! I noted as well that Livy was a potential roadblock but will post back here if I have any success.

**Comment by sgloutnikov** [comment]
I just saw on Toree's [page](https://toree.apache.org/) that it does come with a SQL magic which I was not aware of. Just tested it and it works pretty nicely. 

`sparkSession.read.parquet("s3a://.../xyz.parquet").createOrReplaceTempView("MyTable")`

then I was able to do `%%sql
select * from MyTable`

**Comment by parente** [comment]
I think this request is addressed by Toree I'm going to close the issue.
