### ISSUE TITLE
No Magic or ! access from Scala kernel?

### ISSUE THREAD

**Issue by dartdog** [jupyter/docker-stacks#87]
Just noticed I get no magic commands from a Scala NB nor can I access the system using ! both are pretty fundamental to Jupyter useage, and the lack of magic prevents interoperating with other kernels eg R/Python?

**Comment by lbustelo** [comment]
@dartdog What magic are you looking for. Each kernel is responsible of defining their own set of magics. There is no specification with a list of all magics that kernels need to implement. The spark kernel does have certain magics and they are listed https://github.com/ibm-et/spark-kernel/wiki/List-of-Current-Magics-for-the-Spark-Kernel. 

If you have any specific needs for the spark kernel, direct issues to this project https://github.com/ibm-et/spark-kernel.

As for `!`, that is yet another magic syntax specific to the Python kernel (maybe others implement it).

**Comment by dartdog** [comment]
Thank you for the prompt reply will redirect the comment.
