### ISSUE TITLE
How do I see spark webui  and History Server ??

### ISSUE THREAD

**Issue by eromoe** [jupyter/docker-stacks#875]
I have search for `port`, `webui` and `history` but nothing found . 
I want to see the executing progress so that can improve code performance.

**Comment by parente** [comment]
https://github.com/jupyter/docker-stacks/issues/60 has the answer I believe. It would be much appreciated if you could submit a pull request adding the solution to the docs somewhere under here:  https://github.com/jupyter/docker-stacks/blob/master/docs/using/specifics.md#apache-spark

**Comment by eromoe** [comment]
Is this https://github.com/jupyter/docker-stacks/pull/876  OK ?
