### ISSUE TITLE
pandas.read_hdf

### ISSUE THREAD

**Issue by alanchalk** [jupyter/docker-stacks#877]
`jupyter/scipy-notebook`

**What steps do you take once the container is running to reproduce the issue?**

import pandas as pd
pd.read_hdf('myh5Store', 'filename')

**What actually happens?**

fails with the error 

ImportError: HDFStore requires PyTables, "No module named 'tables'" problem importing

Would you be able to include the "tables" module in this image?

Many thanks for these amazing images.

**Comment by parente** [comment]
I suspect `tables` is a minor addition. Feel free to send a PR adding the conda package we can see how much it pulls into the image.

**Comment by romainx** [comment]
Hello,

Good news `tables` is now available on `scipy-notebook` since the PR #1069.
So I'm closing this issue.

Best
