### ISSUE TITLE
conda environment inconsistency in scipy-notebook

### ISSUE THREAD

**Issue by philippegr** [jupyter/docker-stacks#878]
**What docker image you are using?**
`jupyter/scipy-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

`docker run -it jupyter/scipy-notebook bash`

**What steps do you take once the container is running to reproduce the issue?**
 `conda update --all`
(or `conda`command that will try to install something)

**What do you expect to happen?**
No warmings reported by conda

**What actually happens?**
`conda` reports an environment inconsistency 

> Collecting package metadata: done
> Solving environment: \ 
> The environment is inconsistent, please check the package plan carefully
> The following packages are causing the inconsistency:
> 
>   - conda-forge/linux-64::matplotlib==3.0.3=py37_1
> done

**Comment by miramar-labs** [comment]
I am seeing this also in all-spark-notebook

**Comment by Blizzke** [comment]
I'm experiencing the same issue for my `all-spark-notebook` based installed and it's preventing me from installing other needed packages. 
Is there any progress on this matter?

**Comment by Blizzke** [comment]
I don't know yet what the impact will be for my users and if it is a fix for anyone else, but installing `matplotlib` as `3.1*` has allowed me to continue working (notebook blocks version of `matplotlib` on `3.0*`).
I also don't know how to feel about `sip` being downgraded, but I just wanted to share things here for you all.

```
/opt/conda/bin/conda install matplotlib=3.1*
Collecting package metadata (current_repodata.json): done
Solving environment: failed
Collecting package metadata (repodata.json): done
Solving environment: /
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - conda-forge/linux-64::matplotlib==3.0.3=py37_1
done

## Package Plan ##

  environment location: /opt/conda

  added / updated specs:
    - matplotlib=3.1

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    matplotlib-3.1.1           |           py37_0           6 KB  conda-forge
    pyqt-5.9.2                 |   py37hcca6a23_0         5.7 MB  conda-forge
    qt-5.9.7                   |       h52cfd70_2        85.9 MB  conda-forge
    sip-4.19.8                 |py37hf484d3e_1000         290 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        91.9 MB

The following NEW packages will be INSTALLED:

  pyqt               conda-forge/linux-64::pyqt-5.9.2-py37hcca6a23_0
  qt                 conda-forge/linux-64::qt-5.9.7-h52cfd70_2

The following packages will be UPDATED:

  matplotlib                                   3.0.3-py37_1 --> 3.1.1-py37_0

The following packages will be DOWNGRADED:

  sip                                4.19.13-py37he1b5a44_0 --> 4.19.8-py37hf484d3e_1000


Proceed ([y]/n)? y


Downloading and Extracting Packages
pyqt-5.9.2           | 5.7 MB    | ################################################  | 100%
qt-5.9.7             | 85.9 MB   |  ################################################ | 100%
sip-4.19.8           | 290 KB    | ################################################  | 100%
matplotlib-3.1.1     | 6 KB      | ################################################  | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

**Comment by rubensa** [comment]
Last available scipy-notebook version (jupyter/scipy-notebook:6c3390a9292e) on [dockerhub](https://hub.docker.com/r/jupyter/scipy-notebook/tags) has the same **environment inconsistency problem**.  Also looks like the installed **conda** version is not the last available:
```bash
Collecting package metadata: done
Solving environment: \
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - conda-forge/linux-64::matplotlib==3.0.3=py37_1
done


==> WARNING: A newer version of conda exists. <==
  current version: 4.6.14
  latest version: 4.7.5

Please update conda by running

    $ conda update -n base conda
```

**Comment by jamesdbrock** [comment]
There is a PR for conda 4.7 https://github.com/jupyter/docker-stacks/pull/896
