### ISSUE TITLE
add libjemalloc1 package

### ISSUE THREAD

**Issue by ivmaks** [jupyter/docker-stacks#879]
https://gist.github.com/StephanErb/2deeb80b40e59671380a

plz, add this package and add to /etc/ld.so.preload

**Comment by parente** [comment]
Customizing the memory allocation strategy sounds like fodder for a recipe in the documentation rather than a default for all users. Feel free to [submit a PR adding it to the docs](https://jupyter-docker-stacks.readthedocs.io/en/latest/contributing/recipes.html).

**Comment by mathbunnyru** [comment]
`libjemalloc1` is outdated (libjemalloc2 has been for some time with us).
There is also a duplicate (issue)[https://github.com/jupyter/docker-stacks/issues/1072] (sorry for that, it's actually mine) which proposes to add latest `jemalloc`.
And another issue has a bit more details, so I'll close this one as a duplicate.

**Comment by mathbunnyru** [comment]
I moved your messages to the topic of my issue to have everything in one place. Thanks!
