### ISSUE TITLE
 Check and update documentation and potentially stale info about Docker images [Cross filed in jupyter/jupyter]

### ISSUE THREAD

**Issue by willingc** [jupyter/docker-stacks#89]
FYI to developers working on docker-stacks. We will be working on documentation freshness and accuracy. See details at https://github.com/jupyter/jupyter/issues/87

Any documentation update work needed on docker-stacks can be left in this issue.

**Comment by parente** [comment]
I think we can close this as we've been iterating on doc across numerous issues. @willingc feel free to open new issues / PRs about doc any time!
