### ISSUE TITLE
Question:  Plans to update from ubuntu:bionic-20180526?

### ISSUE THREAD

**Issue by rwmajor2** [jupyter/docker-stacks#897]
Are there plans to update the base image from ubuntu:bionic-20180526 to a newer version?

**Comment by parente** [comment]
Done in https://github.com/jupyter/docker-stacks/pull/896.

We used to point to latest, but found severe build instability with that approach. Maybe it's time to revisit that assumption now that docker has been around for years.

In the meantime, please don't hesitate to submit a PR updating the base ubuntu build when you've seen it's gotten old / stale.
