### ISSUE TITLE
Provide animation engine

### ISSUE THREAD

**Issue by ben-github** [jupyter/docker-stacks#90]
Could we add an animation engine (avconv or mencoder) to the build so that matplotlib animations would work?

When running the notebook from https://github.com/jrjohansson/scientific-python-lectures/blob/master/Lecture-4-Matplotlib.ipynb, in the annimations sections, you get this error:

```
/opt/conda/lib/python3.4/site-packages/matplotlib/animation.py:742: UserWarning: MovieWriter avconv unavailable
  warnings.warn("MovieWriter %s unavailable" % writer)
```

Thanks,

**Comment by ben-github** [comment]
I believe all that is needed is to add 
 ffmpeg or lbav-tools to the apt-get install line.

**Comment by parente** [comment]
Do you have a suggestion for which stack these would go in? They could potentially go in any stack that includes matplotlib (scipy, datascience, pyspark, etc.) but I think that the animation use case is not very common in comparison to the static plot use case, and hence the cost may not be justified in shipping them in every Python stack.

I'm leaning toward these being part of a recipe for a sub-dockerfile, not in the stacks themselves:

```dockerfile
FROM jupyter/scipy-notebook # or your favorite stack
RUN apt-get update && apt-get install -y ffmpeg
```

and you're off and running.

**Comment by ben-github** [comment]
I'm not sure where best this would go. I think a sub docker file is fine. Either that or a variable that could be passed to enable installing ffmpeg.

**Comment by parente** [comment]
I think the above 2 line dockerfile should go on the recipes wiki attached to this repo for the time being. If many users start asking for it, then we can revisit where to add it in the generic stack images maintained here.

**Comment by parente** [comment]
Added to the wiki https://github.com/jupyter/docker-stacks/wiki/Docker-Recipes#enable-matplotlib-animation.

Will leave this open in case others want to chime in and vote for it going into one of the existing stacks.

**Comment by fperez** [comment]
BTW, I tested the `apt-get install ffmpeg` line on this stack, but got an error:

```
Step 39 : RUN apt-get install ffmpeg
 ---> Running in 937e3e0121b4
Reading package lists...
Building dependency tree...
Reading state information...
Package ffmpeg is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ffmpeg' has no installation candidate
```

I actually think it would be good to provide the scipy/data-science stacks working with the full matplotlib capabilities; most users simply will get an error but will probably not bother to come and complain.  These images are large enough that an extra library isn't really that big of a deal.

But evidently ffmpeg isn't the package to install, so we'd need to know what the right package to use is; @ben-github, do you know what the right one is on debian jessie?

**Comment by jakirkham** [comment]
Thanks @fperez. Completely agree. I have a working ffmpeg conda package we could try as well, but sticking with apt-get is also reasonable. Which Dockerfile was this?

**Comment by fperez** [comment]
Either the one for the datascience or the scipy notebooks (and any others that carry the scipy stack, those are the only two I was using).

There may be an alternate package that provides the animate support on debian jessie, I just haven't had time to debug that part (I'm working on other stuff, but caught this along the way).

**Comment by parente** [comment]
> BTW, I tested the apt-get install ffmpeg line on this stack, but got an error:

Doh. Yes. I too easily forget the images here are debian, not ubuntu. At a minimum, the recipe on the wiki needs an update.

**Comment by ben-github** [comment]
I believe I added

apt-get install libav-tools 

instead of ffmpeg. That should work on debian.

**Comment by fperez** [comment]
For the [scipy](https://github.com/jupyter/docker-stacks/blob/master/scipy-notebook/Dockerfile) and [data science](https://github.com/jupyter/docker-stacks/blob/master/datascience-notebook/Dockerfile) ones, adding `libav-tools` sounds reasonable...

**Comment by parente** [comment]
I can have a look at adding it to those two images in particular soon.

**Comment by parente** [comment]
PR coming in a few. Add libav-tools and did the build locally. 

![matplotlibanim](https://cloud.githubusercontent.com/assets/153745/13353495/cbedd572-dc62-11e5-87c9-2583d0d0237d.gif)

Tested with http://jakevdp.github.io/blog/2013/05/12/embedding-matplotlib-animations/ on a Python 2 kernel. (Python 3 hit an encoding problem and I didn't get into debugging the example).

(And yes, that's an animated GIF of a base64 encoded MP4 movie that I put in this GitHub issue. What a world.)

**Comment by jakirkham** [comment]
:clap:

**Comment by parente** [comment]
Tagged `c9428336463c` on Docker Hub (and now listed on the [Docker build history page](https://github.com/jupyter/docker-stacks/wiki/Docker-build-history))

**Comment by fperez** [comment]
Thanks!
