### ISSUE TITLE
R-Studio in a notebook

### ISSUE THREAD

**Issue by perllaghu** [jupyter/docker-stacks#902]
I have a Jupyterhub installation that spawns notebooks into a Kubernetes cluster (or which a Jupyter Notebook with R 3.5 & Jupyterlabs is one)

I've been asked to provide a notebook with R-Studio - and I've [mostly] done that (I can provide the Dockerfile if people are interested).... and by _mostly done_, I mean that the demo() examples run

I've one, maybe two, issues to resolve - for which I need some help:

1. Once the user quits the R-Studio session, the only way to restart is to restart the whole docker image... is there a way to restart an R-Studio session without doing that?

2. Is there a way to get the Jupyter Notebook to auto-start the R-Studio session, and not have to select from the new menu once the docker image has started?

**Comment by parente** [comment]
We're starting to experiment with a general Q&A section on https://discourse.jupyter.org/c/questions to see if cross-technology questions like this one catch more attention from a broader community audience. You might try re-posting your question over there to see if someone with more experience in this topic can help.

I'm going to close this issue as it's not directly related to the docker stacks images, but rather a question about how to combine R-Studio with Jupyter.
