### ISSUE TITLE
R package install broken

### ISSUE THREAD

**Issue by medis87** [jupyter/docker-stacks#904]
Hi,

I try install r-rpostgresql on  `jupyter/scipy-notebook` image, but I get some version error:

```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

  - conda-forge/linux-64::curl==7.65.3=hf8cf82a_0 -> krb5[version='>=1.16.3,<1.17.0a0'] -> libedit[version='>=3.1.20170329,<4.0a0']
  - conda-forge/linux-64::krb5==1.16.3=h05b26f9_1001 -> libedit[version='>=3.1.20170329,<4.0a0']
  - conda-forge/linux-64::libcurl==7.65.3=hda55be3_0 -> krb5[version='>=1.16.3,<1.17.0a0'] -> libedit[version='>=3.1.20170329,<4.0a0']
```
And so on..

From the other channel there was no error:
`conda install -c conda-forge/label/gcc7 r-rpostgresql`
but when I try to import the package it was not found. 
`Error in library(RPostgreSQL): there is no package called ‘RPostgreSQL’`
What did I wrong?

**Comment by parente** [comment]
This looks like a compatibility problem with the latest packages upstream in conda-forge and versions we have pinned in scipy-notebook. It might be time to refresh all the package versions in the stacks to ensure they work with the latest and greatest upstream.

Happy to take a PR from anyone that wants to update version numbers of pandas, numpy, etc. to the latest `major.minor.*` versions, as long as it builds.

**Comment by parente** [comment]
PR #918 updated nearly all of the packages in the `jupyter/scipy-notebook` image. @medis87 can you try installing the R package again in the latest image?

**Comment by romainx** [comment]
Hello,

We have recently updated the R stack (PR #1000 ).

I've made a try with the latest version of the scipy-notebook and it's OK .

```bash
jovyan@d5e6d3fffb7a:~$ conda install -c conda-forge/label/gcc7 r-rpostgresql
jovyan@d5e6d3fffb7a:~$ R
> library(RPostgreSQL)
Loading required package: DBI
> packageVersion("RPostgreSQL")
[1] ‘0.6.2’
```

Best

**Comment by parente** [comment]
I think @romainx has shown this issue is fixed in the latest images. I’m going to close the issue. Please file another if you still see the problem locally.
