### ISSUE TITLE
if I need import opencv2, do I need get into this docker and pip install it?

### ISSUE THREAD

**Issue by spectrumzhang** [jupyter/docker-stacks#905]
I am running this docker image https://hub.docker.com/r/jupyter/tensorflow-notebook/

and found can't import cv2 and some frequent lib(see picture)

is that I am running the wrong container which there is some image actually including all most useful lib already?

![image](https://user-images.githubusercontent.com/50335164/61575957-c46a5580-ab05-11e9-9257-c73f1fed4101.png)

**Comment by parente** [comment]
https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html documents the libraries in each image and is mostly up to date. The Dockerfiles in this repository are the ground truth of what gets installed (e.g., https://github.com/jupyter/docker-stacks/blob/master/scipy-notebook/Dockerfile#L18)

If a package you wish to use does not appear in one of the images, then you do need to install it either by building your own docker image, optionally starting from one of the images here (https://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html#using-pip-install-or-conda-install-in-a-child-docker-image) or using a tool like [repo2docker](https://github.com/jupyter/repo2docker).

**Comment by romainx** [comment]
Hello,

This issue is old, is it OK to close it?
We will do it soon if you have no feedback.

Best

**Comment by mathbunnyru** [comment]
There was no feedback for a loooooong time and I think @parente's answer does answer the question, so I'm closing this issue.
Feel free to reopen, if you need some help.
