### ISSUE TITLE
Update R to 3.6

### ISSUE THREAD

**Issue by dmpe** [jupyter/docker-stacks#907]
3. If you are reporting an issue with one of the existing images, please answer the questions below to help us troubleshoot the problem. Please be as thorough as possible.

**What docker image you are using?**

datascience-notebook

**What do you expect to happen?**
To have latest R version which currently is 3.6

**What actually happens?**

R 3.5

**Comment by parente** [comment]
If someone wants to pick this up and submit a PR, here are the steps that need to be done.

1. Update `r-base` to the latest version (3.6.1 at the time of this writing) from conda-forge in datascience-notebook, r-notebook, and all-spark-notebook
2. Update all other `r-*` packages in those images for compatibility and to get to the latest version available anyway.
3. Iterate on resolving version conflicts until the build succeeds.

**Comment by parente** [comment]
Resolved in #918.
