### ISSUE TITLE
Numpy version not compatible to Catboost

### ISSUE THREAD

**Issue by tqa236** [jupyter/docker-stacks#914]
**What docker image you are using?**

`jupyter/tensorflow-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

In short, I tried to install [CatBoost](https://github.com/catboost/catboost) on the top of jupyter/tensorflow-notebook

Dockerfile:
```
FROM jupyter/tensorflow-notebook:0c84b71d9f3d
USER root

COPY ./environment.yml environment.yml
RUN conda env update -f environment.yml && \
    conda build purge-all && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$NB_USER

USER $NB_UID

# Test Python library installation 
COPY ./src/docker_test.py docker_test.py
RUN python3 docker_test.py

USER $NB_UID
WORKDIR /home/$NB_USER/work/
```
 environment.yml

```
name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - catboost
  # - numpy=1.16*
  - conda-build
prefix: /opt/conda
```

docker_test.py

```
import numpy
print(numpy.__version__)
from catboost import CatBoostRegressor
```

Command: `docker build --tag experiment .`

The last image that works is jupyter/tensorflow-notebook:7a3e968dd212, I built it around 10 days ago.

**What steps do you take once the container is running to reproduce the issue?**
```
from catboost import CatBoostRegressor
```

**What do you expect to happen?**

Import successfully without error.

**What actually happens?**

`ValueError: numpy.ufunc size changed, may indicate binary incompatibility`

The error is similar to [this issue](https://github.com/scikit-learn-contrib/hdbscan/issues/272), and according to the solution in that issue, the error disappears when we bump numpy version to `1.16*` (I tested and it succeeded with numpy version 1.16.4.)

I didn't see that you specify numpy version anywhere in the image stacks, will you consider specify `numpy>=1.16` to avoid incompatibility in the future?

**Comment by parente** [comment]
Related: https://github.com/jupyter/docker-stacks/issues/904#issuecomment-515681444

I'm happy to review a PR that updates conda package versions throughout. We haven't done it in some time.

**Comment by tqa236** [comment]
Is there any easy way to update and test the compatibility of the packages? I will see if I can give a small help.

**Comment by parente** [comment]
We do not have compatibility tests for all packages in the images. We rely on conda to tell us two packages are incompatible at install time.

In the past, we've updated to the latest of all available packages listed in one of the Dockerfiles, attempted the docker build, and investigated problems when the conda refused to install some subset of the packages.

**Comment by linglu** [comment]
I also encounter this problem, I have numpy version is 1.17.0 and catboot version is 0.16.1 installed in my win10_64. Is there any mehtod to solve this problem?

**Comment by parente** [comment]
@tqa236 Can you try again with the latest image? Numerous libraries were updated in #918

**Comment by tqa236** [comment]
Thank you very much. It looks good to me. I'll close this issue.
