### ISSUE TITLE
How to provide docker image while spawning the notebook server in jupyerhub.yaml ( singleuser).

### ISSUE THREAD

**Issue by navneetkrverma** [jupyter/docker-stacks#925]
Hey Team,

As jupyter hub takes a jupyterhub.yaml config file to know which single user docker image to be spawned. This happens just after we logs into the jupyter hub.

I want to know if there is any way to provide a docker image dynamically when we can jupyterhub and points to login and spawn user container.

So use case is one user can spawn one image another user can spawn another image using the same jupyter hub.

Thanks

**Comment by markperri** [comment]
I haven't used it, but there is a spawner options form:  https://jupyterhub.readthedocs.io/en/stable/reference/spawners.html#spawner-options-form

**Comment by navneetkrverma** [comment]
Hey @markperri Thanks for your reply, but i want to know if there is any hub / kubespawner API to provide image details as we provide as hub config:
 - name: SINGLEUSER_IMAGE
          value:  "docker.artifactory.hostname.com/my_custom_image:1.0.0"
And i want this configuration to be custom to each user who logs into jupyter hub.

**Comment by mathbunnyru** [comment]
Hi @navneetkrverma!
Unfortunately, I don't think this issue belongs to this project - it would be better to create an issue in jupyterhub repo, or, even better - in the repo of the spawner you use.
So, I'm closing this one.
