### ISSUE TITLE
Updating to 1.1.2?

### ISSUE THREAD

**Issue by hiramf** [jupyter/docker-stacks#936]
https://github.com/jupyter/docker-stacks/blob/82d1d0bf0867e410a2abc66862fa77c3e2a8d304/base-notebook/Dockerfile#L107

Looks like there are a lot of bugs that get fixed with Jupyter Lab v. 1.1.2. Any plans to update the version?

**Comment by ltammariello** [comment]
We are seeing this issue https://github.com/jupyterlab/jupyterlab/issues/7178  which seems to be fixed in 1.1.1 (or later).  We are interested in the updated datascience-notebook as well.

**Comment by dhirschfeld** [comment]
IIUC 1.1.1 has a problem with widgets so it would be best to jump straight to 1.1.2

**Comment by hiramf** [comment]
> IIUC 1.1.1 has a problem with widgets so it would be best to jump straight to 1.1.2

Agreed, although I seem to be having issues running `jupyter lab build`, as referenced here:
https://github.com/jupyterlab/jupyterlab/issues/7180

**Comment by edurenye** [comment]
It already uses 1.1.3 so I guess we can close this issue
