### ISSUE TITLE
how to use spark package?

### ISSUE THREAD

**Issue by bgrayburn** [jupyter/docker-stacks#94]
Id like to use the spark csv package from spark-packages.org.  is there a way to do this for a particular notebook in the all-spark stack? Thank for these awesome stacks!

**Comment by parente** [comment]
Give this a shot if you're working in Python: https://gist.github.com/parente/c95fdaba5a9a066efaab

If you're using Scala or R, the same should be possible with minor tweaks.

If it works for you too, I'll link that gist in the recipes wiki.

**Comment by bgrayburn** [comment]
Works great thank you!

**Comment by parente** [comment]
Added to the wiki.
