### ISSUE TITLE
rpy2 is quite outdated.

### ISSUE THREAD

**Issue by lgautier** [jupyter/docker-stacks#941]
https://github.com/jupyter/docker-stacks/blob/1386e20468332f32a028c6224bbd8439eb406ee4/datascience-notebook/Dockerfile#L67

The current rpy2 release is 3.1.0 (and 3.2.0 likely very soon).

**Comment by Bidek56** [comment]
I think you need to do a PR for an upgrade.

**Comment by lgautier** [comment]
Conda is generally quite behind rpy2 releases, and the images appear to be designed for conda.

I have created a jupyter image that does not use conda: https://github.com/rpy2/rpy2-docker

**Comment by romainx** [comment]
The latest version available and used in notebooks is now `3.1` which is still behind the latest version available on Pypi `3.2.6`. IMO to be consistent with other packages it could be better to ensure that https://github.com/conda-forge/rpy2-feedstock is up-to-date. The [PR #46](https://github.com/conda-forge/rpy2-feedstock/pull/46) intended to publish the version `3.2.6` seems to encounter issues in the pipeline.

Best

**Comment by mathbunnyru** [comment]
Latest version of rpy2 right now is 3.3.6 (https://pypi.org/project/rpy2/)

And rpy2-feedstock also has this version (https://github.com/conda-forge/rpy2-feedstock/blob/master/recipe/meta.yaml)

And it is getting installed in the latest datascience stack:
https://github.com/jupyter/docker-stacks/runs/1370687524#step:8:5229

So, I think this issue can be closed.

@romainx @lgautier

**Comment by romainx** [comment]
@mathbunnyru thank you 🍰 
You're right I'm closing this issue.
Best.
