### ISSUE TITLE
could it be possible to install libgit2 and pygit2 in the image?

### ISSUE THREAD

**Issue by gbrault** [jupyter/docker-stacks#943]
Latest version seems 0.28.2.

This would allow to script git in python right away in notebooks.
of course as an alternative we can use shell as git is installed...
But using python might lead to more elegant UI.

Thanks

**Comment by romainx** [comment]
Hello,

Very sorry for not responding earlier. We have to take a closer look to decide if these libraries have to be installed or not. We try to keep images as slim as possible so we have to find the good tradeoff between the benefits for the community to have these librairies installed and the penalty on the image size.

Here are the links to the repos

- [libgit2](https://github.com/libgit2/libgit2)
- [pygit2](https://github.com/libgit2/pygit2)

Thanks for your proposal.
Best.

**Comment by gbrault** [comment]
Thanks @romainx !
