### ISSUE TITLE
Update to tensorflow 2.0

### ISSUE THREAD

**Issue by edurenye** [jupyter/docker-stacks#948]
Would be great to update to TensorFlow 2.0 the tensorflow-notebook stack.

**Comment by Bidek56** [comment]
I think you need to a PR in order to upgrade it.

**Comment by edurenye** [comment]
Do we need to remove Keras now that it is included in TensorFlow 2.0?

**Comment by larsmathuseck** [comment]
Any progress on this one?

**Comment by edurenye** [comment]
Looks like it was merged so we can close this issue. Thanks @gokgozf and @parente
