### ISSUE TITLE
What is the password for using "sudo apt-get install" command?

### ISSUE THREAD

**Issue by blatoo** [jupyter/docker-stacks#949]
Hi all,

I want to install some software on the docker container, but when I use `apt-get install xxx`, then I will get a "permission denied" problem.  So I guess, I should use "sudo apt-get install xxx", my question is what is the password for the `sudo ` command?

**Comment by narquette** [comment]
Running into the same issue. Trying to install curl.

**Comment by DrPaulBrewer** [comment]
Reading the docker files, I see they point back to `jupyter/base-image` and from there, back to:
`ubuntu:bionic-20190612@sha256:9b1702dcfe32c873a770a32cfd306dd7fc1c4fd134adfb783db68defc8894b3c`. 

So the ubuntu:bionic pinned image runs as root, and does not have sudo.  

Trying sudo from `docker run -it jupyter/base-image /bin/bash` requests a password.

The [Dockerfile](https://github.com/jupyter/docker-stacks/blob/master/base-notebook/Dockerfile) creates the `jupyter` user [here](https://github.com/jupyter/docker-stacks/blob/1386e20468332f32a028c6224bbd8439eb406ee4/base-notebook/Dockerfile#L56).

The man page for `useradd` discloses under `-p` that the default is not no password, but a disabled password.  Between having a disabled password and not being in the sudoers file, using sudo against the base image without start.sh opening up sudo isn't going to work...

The [start.sh script](https://github.com/jupyter/docker-stacks/blob/master/base-notebook/start.sh) will [open up password-less sudo](https://github.com/jupyter/docker-stacks/blob/1386e20468332f32a028c6224bbd8439eb406ee4/base-notebook/start.sh#L93) if you pass an ENV with GRANT_SUDO=1 (or yes).

**Comment by DrPaulBrewer** [comment]
I'm not an official project volunteer, so someone with more knowledge might want to chime in.

This worked for me.

To build your own custom jupyter docker image with curl

1. Decide what base image you are going to use.  Here I used `jupyter/scipy-notebook`
2. Create a directory where the custom build will go.  Here we will name it `./jupyter-scipy-curl`
3. Create ./jupyter-scipy-curl/Dockerfile with this content:

```
FROM jupyter/scipy-notebook
# must reset to user root to install more stuff
USER root
# apt-utils is missing and needed to avoid warning about skipping debconf
RUN apt-get update && apt-get --yes install apt-utils
# install whatever else you want on this line
RUN apt-get --yes install curl
# set the user back to original setting
USER $NB_UID
```

4. `docker build -t your-name-here/jupyter-ds-curl ./jupyter-scipy-curl`

To test:

```
docker run -it your-name-here/jupyter-ds-curl /bin/bash
jovyan@053666d05bb0:~$ 
jovyan@053666d05bb0:~$ curl
curl: try 'curl --help' or 'curl --manual' for more information
jovyan@053666d05bb0:~$ exit
exit
```

**Comment by blatoo** [comment]
> There's no password as far as I know. Have you tried adding "-e GRANT_SUDO=yes" as illustrated below?
> 
> docker run -d -v $PWD:/home/jovyan/work -e GRANT_SUDO=yes --user root -p 8888:8888 jupyter/all-spark-notebook

I tried, but it doesn't work for me...

**Comment by Bidek56** [comment]
I have just tried:
`docker run -d -v $PWD:/home/jovyan/work -e GRANT_SUDO=yes --user root -p 8888:8888 jupyter/all-spark-notebook`

then

```
sudo apt install wget
sudo apt update
sudo apt upgrade
```

It all works fine, what error messages do you see?

**Comment by Bugatti100Peagle** [comment]
> 
> 
> I have just tried:
> `docker run -d -v $PWD:/home/jovyan/work -e GRANT_SUDO=yes --user root -p 8888:8888 jupyter/all-spark-notebook`
> 
> then
> 
> ```
> sudo apt install wget
> sudo apt update
> sudo apt upgrade
> ```
> 
> It all works fine, what error messages do you see?

I try it OK,thanks

**Comment by parente** [comment]
This question comes up from time to time. I've opened a PR adding more explicit section in the documentation about how to grant the `NB_USER` passwordless sudo and brief explanation about why password auth is disabled.

**Comment by marscod** [comment]
adding the following to the base model, works for me: `-e GRANT_SUDO=yes --user root`

**Comment by RichardBronosky** [comment]
If you want to understand the `docker run -it --rm -e GRANT_SUDO=yes` thing, see https://github.com/jupyter/docker-stacks/blob/master/base-notebook/start.sh#L89-L93

I will add that if the way the maintainers have chosen to handle users and password, you can change it in a Dockerfile. I explain how to add/change user/password in https://askubuntu.com/a/1307156/146273
```
username=jovyan
password=jovyan

adduser --gecos "" --disabled-password $username
chpasswd <<<"$username:$password"
# this would also work if username=root
```

**Comment by gerroon** [comment]
GRANT_SUDO in docker compose does not work. I have it enabled

```
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
      - JUPYTER_TOKEN=''
      - JUPYTER_PASSWORD=''
      -
```

```
jovyan@bfbef172b26f:~$ sudo su
[sudo] password for jovyan:
```

**Comment by mathbunnyru** [comment]
@gerroon you need to use `user: root`.

https://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html#using-sudo-within-a-container

**Comment by gerroon** [comment]
This is how one can login as su

`docker exec -it -u root container bash`
