### ISSUE TITLE
Docker images leaving a zombied `tini` process

### ISSUE THREAD

**Issue by perllaghu** [jupyter/docker-stacks#951]
Platform details:
* Boxen - Centos7: `Linux my_host 3.10.0-1062.1.1.el7.x86_64 #1 SMP Fri Sep 13 22:55:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
* docker:  `Docker version 19.03.3, build a872fc2f86`
* K8 cluster: `Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}`
* Jupyter notebooks based on the May 2019 images : `jupyter/r-notebook:abdb27a6dfbb`

I'm experiencing zombie process issues..... and I've yet to identify a repeatable trigger - less that 0.1% of terminations fail, but when you run 500+ notebooks a day, that's still a weekly occurrence :sad-face:

We are running Jupyter notebooks in a K8 cluster, using KubeSpawner - and the effect is we have a pod that won't terminate, thus the user cannot start a new instance for a later class (or homework)

At a process-level, a happy container looks something like:
```
 43338 106036 106036  43338 ?            -1 Sl       0   0:00  \_ containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/bed33e403b4bf0bdd536698df1721b5ee8a7b2bce4f0c934f168a1264cc1530f -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd -runtime-root /var/run/docker/runti
106036 106054 106054 106054 ?            -1 Ss    1000   0:00  |   \_ tini -g -- /usr/local/bin/docker-entrypoint.sh jupyter-notebook --ip=0.0.0.0 --port=8888 --NotebookApp.base_url=/user/user_a/ --NotebookApp.token=Xgfcf0fDQfGfM3utR2VFrw --NotebookApp.default_url=/tree --NotebookApp.trust_xheaders=True --NotebookApp.disable_check_xsrf=T
106054 106074 106074 106054 ?            -1 Sl    1000   0:05  |       \_ /opt/conda/bin/python /opt/conda/bin/jupyter-notebook --ip=0.0.0.0 --port=8888 --NotebookApp.base_url=/user/1_s1985869/ --NotebookApp.token=Xgfcf0fDQfGfM3utR2VFrw --NotebookApp.default_url=/tree --NotebookApp.trust_xheaders=True --NotebookApp.disable_check_xsrf=True
106074 106188 106188 106188 ?            -1 Ssl   1000   0:01  |           \_ /opt/conda/bin/python -m ipykernel_launcher -f /home/jovyan/.local/share/jupyter/runtime/kernel-baa4d67d-2ab9-4321-8265-0cb79e911de2.json
106074   8775   8775   8775 ?            -1 Ssl   1000   0:00  |           \_ /opt/conda/bin/python -m ipykernel_launcher -f /home/jovyan/.local/share/jupyter/runtime/kernel-c363be05-417c-4a74-a2c6-e2e1d6d2b87e.json
```
however my broken container looks like:
```
 98917  90147  90147  98917 ?            -1 Sl       0   0:00  \_ containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/81cb907d22fe090012823091ba27aee2a0fe8b1339b8170db6db89501a038520 -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd -runtime-root /var/run/docker/runtime-runc
 90147  90164  90164  90164 ?            -1 Ss    1000   0:00  |   \_ [tini]
 90164  90182  90182  90164 ?            -1 Rl    1000  25:21  |       \_ /opt/conda/bin/python /opt/conda/bin/jupyter-notebook --ip=0.0.0.0 --port=8888 --NotebookApp.base_url=/user/user_b/ --NotebookApp.token=2cVgcb-8QOGFjpDN8VqTCA --NotebookApp.default_url=/tree --NotebookApp.trust_xheaders=True --NotebookApp.disable_check_xsrf=True
 90182  90818  90818  90818 ?            -1 Rsl   1000  42:58  |           \_ /opt/conda/bin/python -m ipykernel_launcher -f /home/jovyan/.local/share/jupyter/runtime/kernel-e13ed0b6-bd44-43d2-873b-962ff2f8b297.json
 90182  90920  90920  90920 ?            -1 Rsl   1000  44:41  |           \_ /opt/conda/bin/python -m ipykernel_launcher -f /home/jovyan/.local/share/jupyter/runtime/kernel-a83a7ee8-ab57-4a74-92a7-c183b31cd5a5.json
```
The `[tini]` is clearly the zombie process here.

If I kill (`sudo kill -9 <pid>`) on the `containerd-shim` process, the `tini` process gets inherited by `init` (`pid 1`, as you would expect).
If I try and kill the zombied `tini` or any of the child processes, nothing happens... they don't go.

Whilst I can force the K8Cluster to drop the pod, and Jupyterhub will [eventually] clear it from it's proxy records... I still have a stack of processes left on the box.

The only solution we've found, so far, is to actually reboot the machine (which needs a `cordon` & wait process because, well... _users_)

Do you have any suggestions where we can look?

(Log files simply say _docker terminated_ and then say nothing more)

**Comment by parente** [comment]
You might try re-posting your question on https://discourse.jupyter.org/c/questions to see if someone with more experience in running notebooks at scale on k8s with kubespawner can help.

**Comment by romainx** [comment]
@perllaghu 

I'm a bit late however I would like to share something on this topic.
Have you tried to enable **PID sharing between the containers that are running in the POD**?. This is done by specifying `shareProcessNamespace: true`. It can be used to 
address Docker’s zombie problem by reaping orphaned zombies in the infra container.

I've written a [blog post}(https://www.back2code.me/2020/02/zombie-processes-back-in-k8s/) on this topic if you want more information.

Best.

**Comment by mathbunnyru** [comment]
@perllaghu could you tell us please if your issue was resolved?

**Comment by romainx** [comment]
Hello, I'm closing it to clean things up since we have no answer for a long time.
