### ISSUE TITLE
Question:  What is nodejs used for in the build stack?

### ISSUE THREAD

**Issue by rwmajor2** [jupyter/docker-stacks#958]
I noticed nodejs is installed as part of the stack images.  Can someone explain how this is used along the way?

**Comment by parente** [comment]
JupyterLab requires node to build and install JupyterLab extensions. We use it during the docker build process but leave it installed since it's required to install additional extensions.

**Comment by romainx** [comment]
I think the answer is clear, I'm closing this question.

Best.
