### ISSUE TITLE
Would be nice to have NB extensions configured by default

### ISSUE THREAD

**Issue by dartdog** [jupyter/docker-stacks#96]
Jupyter has availability of Notebook extensions which can be accessed at https://github.com/ipython-contrib/IPython-notebook-extensions and then accessed via the NB extensions page to enable/disable.. Would be nice to have..

**Comment by parente** [comment]
I don't know much about how these extensions are maintained with respect to the latest Jupyter notebook version. I'd hate to toss them in minimal-notebook and then have them break every time the notebook package revs.

Also, do they make sense in minimal-notebook?

**Comment by dartdog** [comment]
they would still only be active if activated, and can be easily deactivated all via a web interface..

**Comment by Stibbons** [comment]
+1, could be provided in a derivative of minimal-notebook, "full-notebook"

**Comment by jdb78** [comment]
How do I actually install these extensions using a dockerfile. When I run the install with the conda install -c conda-forge jupyter_contrib_nbextensions it does not throw an error, but once I try to run the container, it cannot find the extensions anymore in opt/conda/share/jupyter/nbextensions. However, I know they are there as directly logging into the container shows the files.

It must have to do something with permissions (running fix-permissions $CONDA_DIR$ did not help though).

Any ideas?

**Comment by parente** [comment]
I think these are a good fit for the recipes page in the forthcoming doc or currently on the wiki.

**Comment by parente** [comment]
This issue has inactive for some time now and so I'm going to close it. If someone would like to send a PR against the recipes page in the documentation with instructions about how to install the extensions in these images, I'll be happy to review it.
