### ISSUE TITLE
Cant pull image (pyspark)

### ISSUE THREAD

**Issue by skw1990** [jupyter/docker-stacks#962]
Hi! Thanks for using the Jupyter Docker Stacks.

Please review the following guidance about how to ask questions, contribute changes, or report bugs in the Docker images maintained here.

1. If you have a general question about using these Docker images or with Jupyter + Docker in general, please post your question in the [Jupyter Discourse Q&A section](https://discourse.jupyter.org/c/questions) so that it can be seen, discussed, and hopefully answered by the community.

Can't pull image at all...

2. If you are looking to contribute to the images, please see the [Contributor's Guide](http://jupyter-docker-stacks.readthedocs.io/en/latest/#) in the documentation for our preferred processes.

3. If you are reporting an issue with one of the existing images, please answer the questions below to help us troubleshoot the problem. Please be as thorough as possible.

jupyter/pyspark-notebook

Example: `jupyter/scipy-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

Example: `docker run -it --rm -p 8889:8888 jupyter/all-spark-notebook:latest`

**What steps do you take once the container is running to reproduce the issue?**
Restart virtualbox

**What do you expect to happen?**
Image starts to download

**What actually happens?**
![image](https://user-images.githubusercontent.com/7208012/68685710-7e9a3700-05a5-11ea-98a0-b7ac18345b92.png)

**Comment by Bidek56** [comment]
This seems like a local Docker configuration issue. I am pulling and installing images all day long and it works just fine. Also if it was a true docker image pull issue, it does not belong here, it belong on a Docker hub forum.

**Comment by skw1990** [comment]
I have no issue downloading other images apart from this.....

**Comment by Bidek56** [comment]
In the example above you are showing 3 different images, which image are you trying to pull?

**Comment by romainx** [comment]
@skw1990 could you please confirm that this issue is still relevant?

Many thanks for your reply.
Best.

**Comment by romainx** [comment]
Hello

Since we have no feedback for a long time now, I'm closing this issue.
Feel free to open a new one if it's still relevant.

Best.
