### ISSUE TITLE
Shutdown the notebook from Running section

### ISSUE THREAD

**Issue by mathbunnyru** [jupyter/docker-stacks#968]
**What docker image you are using?**

`jupyter/scipy-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

`docker run -p 8888:8888 jupyter/scipy-notebook:latest`

**What steps do you take once the container is running to reproduce the issue?**

1. Visit http://127.0.0.1:8888
2. Start a Python Notebook
3. Save it
4. Go to Running section on the main screen
5. Try to shutdown the notebook

**What do you expect to happen?**

My notebook disappears from the "Running" section.

**What actually happens?**

Nothing.

Shutdown works fine from the main screen if I choose this notebook, only "Running" section doesn't work.

**Comment by Bidek56** [comment]
This is a [Jupyter issue](https://github.com/jupyter/notebook/issues/4867) fixed with [PR](https://github.com/jupyter/notebook/pull/4939) but not yet released. Please close this ticket.

**Comment by mathbunnyru** [comment]
@Bidek56 thanks!
