### ISSUE TITLE
Would be nice if IPython parallel is installed in all-spark-notebook by default?

### ISSUE THREAD

**Issue by FreeBirdLjj** [jupyter/docker-stacks#97]
As is in the title.

**Comment by parente** [comment]
Is there a use case for combining IPy parallel and Spark? I'm legitimately asking because I don't know. My gut reaction is that it would fit better in the scipy stack.

**Comment by parente** [comment]
@FreeBirdLjj ping re: the above.

**Comment by jakirkham** [comment]
Yeah, this also seems confusing to me. My understanding was ipyparallel and Spark are two totally orthogonal things.

**Comment by minrk** [comment]
I think ipyparallel and spark don't really go together.

**Comment by parente** [comment]
I'm going to close this out. @FreeBirdLjj feel free to reopen if you have a use case for ipyparallel in one of the images.
