### ISSUE TITLE
cannot run with a public ip

### ISSUE THREAD

**Issue by ly3too** [jupyter/docker-stacks#972]
**What docker image you are using?**
 `jupyter/base-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

Example: `docker run -it --rm -p 8889:8888 jupyter/all-spark-notebook:latest`
 sudo docker run -dt --name=jupyter --restart=always -p 8866:8888 -v /home/jupyter:/home/jovyan jupyter/base-notebook jupyter notebook --ip 0.0.0.0 --port 8888 --no-browser

**What steps do you take once the container is running to reproduce the issue?**
1. use nginx reverse proxy to locahost:8866

**What do you expect to happen?**
be able to access from public ip
be able to run python code

**What actually happens?**
can access
cannot run any code. the opened tab shows connecting to server, but without success

the docker logs shows:
[I 05:06:02.101 NotebookApp] 302 GET / (172.17.0.1) 1.49ms
[E 05:06:02.272 NotebookApp] Could not open static file ''
[W 05:06:02.560 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js (172.17.0.1) 14.01ms referer=https://xxx:2019/tree?
[W 05:06:06.130 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js (172.17.0.1) 6.52ms referer=https://xxx:2019/notebooks/Untitled.ipynb
[W 05:06:06.427 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js (172.17.0.1) 4.88ms referer=https:/xxx:2019/notebooks/Untitled.ipynb
[W 05:06:07.103 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20191209050523 (172.17.0.1) 5.14ms referer=https://xxx:2019/notebooks/Untitled.ipynb
[I 05:06:07.219 NotebookApp] Kernel started: aee2f11a-d85c-451c-be81-bbd80a9c6653
[W 05:06:07.819 NotebookApp] 400 GET /api/kernels/aee2f11a-d85c-451c-be81-bbd80a9c6653/channels?session_id=400149354b20452182cbc72a8f1f58ff (172.17.0.1) 284.38ms referer=None
[W 05:06:09.117 NotebookApp] Replacing stale connection: aee2f11a-d85c-451c-be81-bbd80a9c6653:400149354b20452182cbc72a8f1f58ff

**Comment by Bidek56** [comment]
Although I am not familiar with nginx reverse proxy, I believe you need to look at your nginx config and notebook config. I use the `jupyter/pyspark-notebook` image on Azure AKS with ingress controller and it works just fine. In the past I had to modify these settings in the ` jupyter_notebook_config.py` file.

> c.NotebookApp.base_url
c.NotebookApp.tornado_settings

**Comment by ly3too** [comment]
> Although I am not familiar with nginx reverse proxy, I believe you need to look at your nginx config and notebook config. I use the `jupyter/pyspark-notebook` image on Azure AKS with ingress controller and it works just fine. In the past I had to modify these settings in the ` jupyter_notebook_config.py` file.
> 
> > c.NotebookApp.base_url
> > c.NotebookApp.tornado_settings

Yes, I know that there must be something wrong with notebook config. but I dont know exactly what it is. I can access the notebook webpage and event edit and save file, but just cannot run the code.

Thanks

**Comment by parente** [comment]
@ly3too Jupyter notebook relies on websocket connections for executing code. It sounds like the nginx configuration may be preventing those connections.

There's a community-contributed nginx configuration linked from https://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html#running-behind-a-nginx-proxy. Could you compare that config with your own, particularly the part that mentions websockets?

**Comment by ly3too** [comment]
> @ly3too Jupyter notebook relies on websocket connections for executing code. It sounds like the nginx configuration may be preventing those connections.
> 
> There's a community-contributed nginx configuration linked from https://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html#running-behind-a-nginx-proxy. Could you compare that config with your own, particularly the part that mentions websockets?

Thanks, 
It indeed looks like the websockets problem. Since all /api/xxx got a 404.
