### ISSUE TITLE
Downgrade Python from 3.7 to 3.6 or tag 3.6 version

### ISSUE THREAD

**Issue by yuriploc** [jupyter/docker-stacks#976]
**What docker image you are using?**

`jupyter/scipy-notebook`

**What complete docker command do you run to launch the container (omitting sensitive values)?**

 `docker run -it --rm -p 8889:8888 jupyter/scipy-notebook`

**What steps do you take once the container is running to reproduce the issue?**

Example:

1. Visit http://localhost:8888
2. Try to install `turicreate`: `!pip install turicreate` 
3. There's no version of `turicreate` for Python 3.7 on Linux (https://github.com/apple/turicreate/issues/788)

**What do you expect to happen?**

I expected to be able to install `turicreate` or to easily downgrade from Python 3.7 to Python 3.6

**What actually happens?**

I'm not able to install the dependencies I need or downgrade.

I'd suggest a tagged version of `scipy-notebook` with Python 3.6, so we can use the `docker-stacks` with the Python version that matches our dependencies.

I'm not experienced in building Docker images, but I can try to do that. If someone can help, I'd be happy to contribute.

**Comment by Bidek56** [comment]
Can you use an older image that has Python 3.6 as a base?

**Comment by yuriploc** [comment]
Thank you for the suggestion, @Bidek56. 

The image `jupyter/scipy-notebook:7d427e7a4dde` from 2019-04-15 works fine for my use case.

**Comment by archienorman11** [comment]
Is it possible to run the most recent image with `python3.6`? (There are some Jupyter features I require that are not available in `jupyter/scipy-notebook:7d427e7a4dde`)

**Comment by fburak** [comment]
> I'd suggest a tagged version of `scipy-notebook` with Python 3.6, so we can use the `docker-stacks` with the Python version that matches our dependencies.
Same problem for me and i agree with the advice above
