### ISSUE TITLE
Enable jupyterlab-dash extension in jupyter lab 

### ISSUE THREAD

**Issue by METAVar** [jupyter/docker-stacks#978]
Hi,

I am running jupyter/minimal-notebook:latest image with jubyter lab  enabled.
Currently i am trying to install  jupyterlab-dash extension using extension manager and i am able to install the package but when try to run script 

```python
import jupyterlab_dash
import dash
import dash_html_components as html

viewer = jupyterlab_dash.AppViewer()

app = dash.Dash(__name__)

app.layout = html.Div('Hello World')

viewer.show(app)
```

I get error saying extenstion jupyterlab-dash not installed.

**Comment by parente** [comment]
I'm not familiar with the dash extension. Perhaps someone who is from the community can help here.

**Comment by rahulpshah** [comment]
@METAVar Can you post the output of `jupyter labextension list`, this will help to understand whether your extension was actually installed.

**Comment by romainx** [comment]
Hello,

In fact we have upgraded the stack to JupyterLab `2.0.x` and the `jupyterlab-dash` extension is not compatible with this version. There is an issue open in their repo about that: https://github.com/plotly/jupyterlab-dash/issues/37.

```bash
$ jupyter labextension install jupyterlab-dash

# An error occured.
# ValueError: The extension "jupyterlab-dash" does not yet support the current version of JupyterLab.
# 
# 
# Conflicting Dependencies:
# JupyterLab              Extension      Package
# >=2.0.2 <2.1.0          >=0.19.1 <0.20.0@jupyterlab/application
# >=2.0.2 <2.1.0          >=0.19.1 <0.20.0@jupyterlab/console
# >=2.0.2 <2.1.0          >=0.19.2 <0.20.0@jupyterlab/notebook
# See the log file for details:  /tmp/jupyterlab-debug-m4fhjm59.log
```

We will have to wait to be able to use it.

Best

**Comment by mathbunnyru** [comment]
https://github.com/plotly/jupyterlab-dash was archived.
But luckily, now there is https://github.com/plotly/jupyter-dash

And it was even updated to support jupyterlab 3 (which we're using).
https://github.com/plotly/jupyter-dash/pull/51

So, I think this effectively resolves this issue.
