### ISSUE TITLE
update datascience to Julia 1.3 or make available a few tags for different version of Julia?

### ISSUE THREAD

**Issue by xiaodaigh** [jupyter/docker-stacks#979]
I am new to docker so which I can contribute, but I think changing the JULIA_VERSION to 1.3 worked for me.

**Comment by kjfergu** [comment]
I've made the changes to `Dockerfile` that uses Julia 1.3.1 instead of 1.2.0. I'll upload it and submit a pull request.

**Comment by parente** [comment]
Updated in #980. Thanks!
