### ISSUE TITLE
Key Not Found in store Error | Any help is appreciated

### ISSUE THREAD

**Issue by arghyakusumdas** [jupyter/docker-stacks#984]
$ docker run --rm -p 10000:8888 -e JUPYTER_ENABLE_LAB=yes -v "$PWD":/home/users/argo/MyDockerImages jupyter/datascience-notebook:9b06df75e445
Unable to find image 'jupyter/datascience-notebook:9b06df75e445' locally
Trying to pull repository registry.access.redhat.com/jupyter/datascience-notebook ... 
Pulling repository registry.access.redhat.com/jupyter/datascience-notebook
Trying to pull repository docker.io/jupyter/datascience-notebook ... 
9b06df75e445: Pulling from docker.io/jupyter/datascience-notebook
a48c500ed24e: Pulling fs layer 
1e1de00ff7e1: Pulling fs layer 
0330ca45a200: Pulling fs layer 
471db38bcfbf: Pulling fs layer 
0b4aba487617: Pulling fs layer 
1bac85b3a63e: Pulling fs layer 
245be47b44f6: Pull complete 
bc9f2b515993: Pull complete 
70c66ba9da3a: Pull complete 
5b37a77208e7: Pull complete 
69924084d9e8: Pull complete 
022c4b9a03b7: Pull complete 
05102897a60a: Pull complete 
9fba983e02fb: Pull complete 
dcf71afb398e: Pull complete 
e865c5e8a2cb: Pull complete 
d73d51d80aa0: Pull complete 
deaf1fca6bf2: Pull complete 
244180169cc3: Pull complete 
081de9d56061: Pull complete 
602989f9a9b5: Pull complete 
0c450a703dd5: Pull complete 
1b0a8e05918b: Pull complete 
91611e462042: Pull complete 
f80df58e0fb6: Pull complete 
8b44e09f5e0f: Pull complete 
c774de4a38e9: Pull complete 
0774d36fc441: Pull complete 
c7e9a9a05704: Pull complete 
Digest: sha256:fecf0c5e8085f6dfd05675f841f4d3d53caefe89be361b587cb61c51db9df19b
Status: Downloaded newer image for docker.io/jupyter/datascience-notebook:9b06df75e445
docker: Error response from daemon: failed to update store for object type *libnetwork.endpointCnt: Key not found in store.

**Comment by Bidek56** [comment]
This is a Docker problem not an image problem. Have you moved your docker directory recently? Is your disk out of space? Please search for a solution on the web.

**Comment by romainx** [comment]
Hello @arghyakusumdas 

Any update on this issue? We will close it soon if we have no feedback.

Thanks

**Comment by romainx** [comment]
Hello,

Since we have no feedback I'm closing the issue. Feel free to open a new one if you are facing this issue again.

Best
