### ISSUE TITLE
Current Base-Notebook Image does not have pip

### ISSUE THREAD

**Issue by velaraptor** [jupyter/docker-stacks#988]
Noticed that pip will not work with latest image [7f696fe2cb4e](https://hub.docker.com/layers/jupyter/base-notebook/latest/images/sha256-7f696fe2cb4ee581262c8c053831188efbe048751bd8e7f0e2011cae41ec555c)

This Fix will work

```
RUN conda install pip
```

**Comment by consideRatio** [comment]
I've looked through this in depth, it seems like it should have if i rebuild it without cache. I don't know what have happened, but it ended up without pip for some reason but doesn't if i build the Dockerimage locally.

Can we trigger a rebuild without cache?

**Comment by shingo78** [comment]
I tried to build locally without cache, but the built image does not have pip.
Looking at the build logs, I found that `conda update` removed pip.

```
The following packages will be REMOVED:

  asn1crypto-0.24.0-py37_0
  bzip2-1.0.8-h7b6447c_0
  libarchive-3.3.3-h5d8350f_5
  libxml2-2.9.9-hea5a465_1
  lz4-c-1.8.1.2-h14c3975_0
  lzo-2.10-h49e0be7_2
  pip-19.1.1-py37_0
  python-libarchive-c-2.8-py37_11
  wheel-0.33.4-py37_0
  zstd-1.3.7-h0b5b093_0
```
The problem seems to be in conda.
If I update Miniconda to 4.7.12 and rebuild, pip is available.
