### ISSUE TITLE
PDF download not working with R in datascience stack?

### ISSUE THREAD

**Issue by gdelangel** [jupyter/docker-stacks#99]
Hi there. I'm not able to do a PDF download of even a trivial R document. If I start my container with:
docker run -d -p 8888:8888 jupyter/datascience-notebook

And then proceed to do a trivial notebook in R, followed by File, Download as, PDF via LaTex, I get a window with "nbconvert failed: PDF creating failed".

Looking at the container log yields the following error: 

[I 19:51:36.235 NotebookApp] Saving file at /Untitled.ipynb
[I 19:51:36.397 NotebookApp] Writing 13493 bytes to notebook.tex
[I 19:51:36.397 NotebookApp] Building PDF
[I 19:51:36.398 NotebookApp] Running pdflatex 3 times: ['pdflatex', 'notebook.tex']
[C 19:51:36.537 NotebookApp] pdflatex failed: ['pdflatex', 'notebook.tex']
    This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2015/dev/Debian) (preloaded format=pdflatex)
     restricted \write18 enabled.
    entering extended mode
    (./notebook.tex
    LaTeX2e <2014/05/01>
    Babel <3.9l> and hyphenation patterns for 2 languages loaded.
    (/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
    Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
    (/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
    (/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty
    (/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty
    (/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/latexconfig/graphics.cfg)
    (/usr/share/texlive/texmf-dist/tex/latex/pdftex-def/pdftex.def
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ltxcmds.sty))))
    (/usr/share/texlive/texmf-dist/tex/latex/adjustbox/adjustbox.sty
    (/usr/share/texlive/texmf-dist/tex/latex/xkeyval/xkeyval.sty
    (/usr/share/texlive/texmf-dist/tex/generic/xkeyval/xkeyval.tex
    (/usr/share/texlive/texmf-dist/tex/generic/xkeyval/xkvutils.tex)))
    (/usr/share/texlive/texmf-dist/tex/latex/adjustbox/adjcalc.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/adjustbox/trimclip.sty
    (/usr/share/texlive/texmf-dist/tex/latex/collectbox/collectbox.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/adjustbox/tc-pdftex.def))
    (/usr/share/texlive/texmf-dist/tex/latex/ifoddpage/ifoddpage.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/varwidth/varwidth.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty
    (/usr/share/texlive/texmf-dist/tex/latex/latexconfig/color.cfg))
    (/usr/share/texlive/texmf-dist/tex/latex/tools/enumerate.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/geometry/geometry.sty
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
    (/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty
    For additional information on amsmath, use the `?' option.
    (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty
    (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty
    (/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/eurosym/eurosym.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/ucs/ucs.sty
    (/usr/share/texlive/texmf-dist/tex/latex/ucs/data/uni-global.def))
    (/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty
    (/usr/share/texlive/texmf-dist/tex/latex/ucs/utf8x.def))
    (/usr/share/texlive/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty
    Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix 
    <2008/02/07> (tvz))
    (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/grffile.sty
    (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/etexcmds.sty
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifluatex.sty))))
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/auxhook.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)
    (/usr/share/texlive/texmf-dist/tex/latex/latexconfig/hyperref.cfg)
    (/usr/share/texlive/texmf-dist/tex/latex/url/url.sty))
    
    Package hyperref Message: Driver (autodetected): hpdftex.
    
    (/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def
    (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/booktabs/booktabs.sty)
    
    ! LaTeX Error: File `ulem.sty' not found.
    
    Type X to quit or <RETURN> to proceed,
    or enter new name. (Default extension: sty)
    
    Enter file name: 
    ! Emergency stop.
    <read *> 
             
    l.37 ^^M
            
    !  ==> Fatal error occurred, no output PDF file produced!
    Transcript written on notebook.log.
    
[I 19:51:36.538 NotebookApp] Running bibtex 1 time: ['bibtex', 'notebook']
[W 19:51:36.571 NotebookApp] bibtex had problems, most likely because there were no citations
[I 19:51:36.571 NotebookApp] Running pdflatex 3 times: ['pdflatex', 'notebook.tex']
[C 19:51:36.705 NotebookApp] pdflatex failed: ['pdflatex', 'notebook.tex']
    This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2015/dev/Debian) (preloaded format=pdflatex)
     restricted \write18 enabled.
    entering extended mode
    (./notebook.tex
    LaTeX2e <2014/05/01>
    Babel <3.9l> and hyphenation patterns for 2 languages loaded.
    (/usr/share/texlive/texmf-dist/tex/latex/base/article.cls
    Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
    (/usr/share/texlive/texmf-dist/tex/latex/base/size10.clo))
    (/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty
    (/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty
    (/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/latexconfig/graphics.cfg)
    (/usr/share/texlive/texmf-dist/tex/latex/pdftex-def/pdftex.def
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ltxcmds.sty))))
    (/usr/share/texlive/texmf-dist/tex/latex/adjustbox/adjustbox.sty
    (/usr/share/texlive/texmf-dist/tex/latex/xkeyval/xkeyval.sty
    (/usr/share/texlive/texmf-dist/tex/generic/xkeyval/xkeyval.tex
    (/usr/share/texlive/texmf-dist/tex/generic/xkeyval/xkvutils.tex)))
    (/usr/share/texlive/texmf-dist/tex/latex/adjustbox/adjcalc.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/adjustbox/trimclip.sty
    (/usr/share/texlive/texmf-dist/tex/latex/collectbox/collectbox.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/adjustbox/tc-pdftex.def))
    (/usr/share/texlive/texmf-dist/tex/latex/ifoddpage/ifoddpage.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/varwidth/varwidth.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty
    (/usr/share/texlive/texmf-dist/tex/latex/latexconfig/color.cfg))
    (/usr/share/texlive/texmf-dist/tex/latex/tools/enumerate.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/geometry/geometry.sty
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
    (/usr/share/texlive/texmf-dist/tex/generic/ifxetex/ifxetex.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty
    For additional information on amsmath, use the `?' option.
    (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty
    (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amssymb.sty
    (/usr/share/texlive/texmf-dist/tex/latex/amsfonts/amsfonts.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/eurosym/eurosym.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/ucs/ucs.sty
    (/usr/share/texlive/texmf-dist/tex/latex/ucs/data/uni-global.def))
    (/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty
    (/usr/share/texlive/texmf-dist/tex/latex/ucs/utf8x.def))
    (/usr/share/texlive/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty
    Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix 
    <2008/02/07> (tvz))
    (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/grffile.sty
    (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/kvoptions.sty
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/etexcmds.sty
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/ifluatex.sty))))
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/hyperref/hyperref.sty
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
    (/usr/share/texlive/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/auxhook.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/hyperref/pd1enc.def)
    (/usr/share/texlive/texmf-dist/tex/latex/latexconfig/hyperref.cfg)
    (/usr/share/texlive/texmf-dist/tex/latex/url/url.sty))
    
    Package hyperref Message: Driver (autodetected): hpdftex.
    
    (/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def
    (/usr/share/texlive/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
    (/usr/share/texlive/texmf-dist/tex/latex/tools/longtable.sty)
    (/usr/share/texlive/texmf-dist/tex/latex/booktabs/booktabs.sty)
    
    ! LaTeX Error: File `ulem.sty' not found.
    
    Type X to quit or <RETURN> to proceed,
    or enter new name. (Default extension: sty)
    
    Enter file name: 
    ! Emergency stop.
    <read *> 
             
    l.37 ^^M
            
    !  ==> Fatal error occurred, no output PDF file produced!
    Transcript written on notebook.log.
    
[W 19:51:36.706 NotebookApp] 500 GET /nbconvert/pdf/Untitled.ipynb?download=true (192.168.99.1): nbconvert failed: PDF creating failed
[E 19:51:36.708 NotebookApp] Exception in exception handler
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.4/site-packages/notebook/nbconvert/handlers.py", line 102, in get
        "config_dir": self.application.settings['config_dir'],
      File "/opt/conda/lib/python3.4/site-packages/nbconvert/exporters/pdf.py", line 152, in from_notebook_node
        raise IOError("PDF creating failed")
    OSError: PDF creating failed
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.4/site-packages/tornado/web.py", line 1443, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/conda/lib/python3.4/site-packages/tornado/web.py", line 2800, in wrapper
        return method(self, *args, **kwargs)
      File "/opt/conda/lib/python3.4/site-packages/notebook/nbconvert/handlers.py", line 106, in get
        raise web.HTTPError(500, "nbconvert failed: %s" % e)
    tornado.web.HTTPError: HTTP 500: Internal Server Error (nbconvert failed: PDF creating failed)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.4/site-packages/tornado/web.py", line 1450, in _execute
        self._handle_request_exception(e)
      File "/opt/conda/lib/python3.4/site-packages/tornado/web.py", line 1502, in _handle_request_exception
        self.send_error(e.status_code, exc_info=sys.exc_info())
      File "/opt/conda/lib/python3.4/site-packages/tornado/web.py", line 978, in send_error
        self.finish()
      File "/opt/conda/lib/python3.4/site-packages/tornado/web.py", line 934, in finish
        self._log()
      File "/opt/conda/lib/python3.4/site-packages/tornado/web.py", line 1474, in _log
        self.application.log_request(self)
      File "/opt/conda/lib/python3.4/site-packages/tornado/web.py", line 1936, in log_request
        self.settings["log_function"](handler)
      File "/opt/conda/lib/python3.4/site-packages/notebook/log.py", line 46, in log_request
        log_method(json.dumps(request.headers, indent=2))
      File "/opt/conda/lib/python3.4/json/__init__.py", line 237, in dumps
        **kw).encode(obj)
      File "/opt/conda/lib/python3.4/json/encoder.py", line 194, in encode
        chunks = list(chunks)
      File "/opt/conda/lib/python3.4/json/encoder.py", line 429, in _iterencode
        o = _default(o)
      File "/opt/conda/lib/python3.4/json/encoder.py", line 173, in default
        raise TypeError(repr(o) + " is not JSON serializable")
    TypeError: <tornado.httputil.HTTPHeaders object at 0x7f5b91ba5748> is not JSON serializable

**Comment by parente** [comment]
Not that it should matter, but does the same thing happen with a Python notebook? An R notebook with only the markdown for "Hello world" in it?

**Comment by parente** [comment]
I reproduced it here with a simple markdown only notebook. Looks like a regression in what we were installing via the various latex packages. `ulem` is in the `texlive-generic-recommended` Ubuntu package supposedly. Could be the `--no-install-recommends` flag wasn't on the apt-get for the tex packages before when it use to work.

I'll need to dig back through the history to see if anything changed in the Dockerfiles here or if it was an external change.

**Comment by gdelangel** [comment]
Cool - yes, I was going to say that it appears even in a trivial doc.

**Comment by parente** [comment]
`jupyter/minimal-notebook:4.0` has the same apt-get install list but converts PDFs properly. So this is a change in the the required dependencies of the other packages (pandoc? notebook itself?)

At any rate, adding `texlive-generic-recommended` fixes the problem.

**Comment by parente** [comment]
Building now.

**Comment by parente** [comment]
Pushing to docker hub with tag `c922d1f83e0b`

**Comment by parente** [comment]
Some images failing to push. Will update again when all are successful.

**Comment by parente** [comment]
Done. All images.

**Comment by willembressers** [comment]
I'm having the same issue. 

i've downloaded kitematic (windows 8) today. any thoughts on how i can solve this?

**Comment by parente** [comment]
I tried converting a trivial notebook (1 markdown cell, 1 code cell, ggplot output) on the latest jupyter/datascience-notebook image (tag: `97a5071c5775`) to a PDF and it failed with a different error than the one in this issue: `nbconvert failed: Inkscape svg to pdf conversion failed`. I'm opening a separate issue about this.
