### ISSUE TITLE
scipy-notebook DockerHub image not updating

### ISSUE THREAD

**Issue by maresb** [jupyter/docker-stacks#992]
Hi, I just noticed that `scipy-notebook` hasn't been [built on DockerHub](https://hub.docker.com/r/jupyter/scipy-notebook/builds) for almost 2 months.  This is although the Dockerfile was [updated 5 days ago](https://github.com/jupyter/docker-stacks/commit/75519a57515ae04e8f66d22f26f9511c1fdb5591#diff-ce4141738e05cf3732ff298c1955b6ce).  The [Dockerfile on DockerHub](https://hub.docker.com/r/jupyter/scipy-notebook/dockerfile) does not reflect that commit.  In contrast, `base-notebook` was [built 3 days ago](https://hub.docker.com/r/jupyter/base-notebook/builds).

I would have expected to see a build of `scipy-notebook` from 3 days ago, since it depends on `base-notebook` via `minimal-notebook`.  I don't know how things are set up, but even if the automated build doesn't recognize the dependency, I'd expect an update from the commit from 5 days ago.

Why no update?  Is it a build fail?  Deliberate decision due to too much resource usage?  Thanks!

**Comment by Bidek56** [comment]
It seems that none of the images have been build on DockerHub for the last 2 months.
@parente would you know what's going on? Thanks

**Comment by maresb** [comment]
@Bidek56, note that `base-notebook` was [built 3 days ago](https://hub.docker.com/r/jupyter/base-notebook/builds).

**Comment by parente** [comment]
Looks like downstream image builds broke without raising an explicit error from Docker Hub after the 2019-12-02 build. I'll have a look at the config tonight to see what regressed.

**Comment by parente** [comment]
The cross-repository trigger hostname supported by Docker apparently changed from cloud.docker.com to hub.docker.com. I've adjusted the hostname in the build configs on Docker Hub and kicked off a new build of base-notebook. I'll close this after confirming the other builds triggered in proper sequence.

Thanks for raising the issue @maresb and @Bidek56.

**Comment by parente** [comment]
Everything is built or in in-progress building. I think this is safe to close.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/docker-stacks-latest-jupyter-datascience-notebook-image-is-not-up-to-date/3167/2
