### ISSUE TITLE
Feature request: dask lab extension in scipy-notebook

### ISSUE THREAD

**Issue by raybellwaves** [jupyter/docker-stacks#999]
I'm not sure if this is the place to ask this. I can move it to the discourse channel if you prefer https://discourse.jupyter.org/

Is it worth adding the dask lab extension to the scipy-notebook docker file (https://github.com/jupyter/docker-stacks/blob/master/scipy-notebook/Dockerfile#L52_? https://github.com/dask/dask-labextension

I understand this may be too bespoke and therefore would not fit the generic build.

**Comment by parente** [comment]
We generally prefer adding [recipes in the documentation](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html) over installing new packages in the images to avoid forever increasing the size of the docker images and maintenance burden of this repository. We'd be happy to review and merge a [recipe pull request](https://jupyter-docker-stacks.readthedocs.io/en/latest/contributing/recipes.html) for the dask lab extension if you'd like to submit one.

However, if there's overwhelming support for adding the dask extension, we could add it.

**Comment by raybellwaves** [comment]
Will do and we can discuss further. Thanks.
